### ISSUE TITLE
[utils] Easy log sanitization with Obfuscated<T>

### ISSUE THREAD

**Issue by jakekidd** [connext/monorepo#1058]
### What is?

Sometimes we are logging sensitive information by mistake. Even if we patch it, however, mistakes may continue to get made. Maybe we roll out a hasty update, for example, where we log `Bid` objects in plaintext, revealing the router's path signatures in the logs. Not ideal.

### What do?

Create a custom type or class called `Obfuscated<T>`, where, when passed into the `Logger` class, will either:
A) Throw an error. Class shouldn't be logged directly. Properties should be consciously picked out for logging.
B) Call a custom `obfuscate` method, if available, that formats the properties for logging as needed. Properties like mnemonics, signatures, secrets, API keys, etc. could be covered up with this.

Latter (B) is more intensive and would involve creating an abstract class and extending it, former (A) is more simple and would prevent dumb mistakes.

**Comment by rhlsthrm** [comment]
I like this idea of the type. However, the type isn't available at runtime so you can't throw based on the type. But it would fail lint checks, etc so I think it's still a good idea.

**Comment by sanchaymittal** [comment]
too much effort, let's revisit in future
