### ISSUE TITLE
As a router, I want to bridge and add liquidity at the same time

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#1317]
**Problem**
For example, router starts with a big bag of USDC on ETH. Ideally they can just bridge to multiple chains in a single tx and add liquidity within the same call. Otherwise they need to bridge then add liquidity in separate txs.

**Ideas to solve this**
Add function to contracts 
OR 
build layer on top outside the contracts 

**Acceptance Criteria**
[ ] In call params user can specify 
[ ]

**Comment by alexwhte** [comment]
P3 - nice optimization

**Comment by LayneHaber** [comment]
not planned
