### ISSUE TITLE
As a router, I would like to monitor bid analytics

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#1333]
**Problem**
Routers want to understand the bidding system (sequencer). They want to monitor to ensure fairness, but also to ensure that the system is working as expected.

- router_auctions_received_total    //Total count of auction requests received from Sequencer 
- router_auctions_sent_total        //Total count of auction bids sent to Sequencer 
- router_auctions_successful_total  //Total count of auction approvals received from Sequencer 

**Ideas to solve this**
Log these events with the right segmentation metadata, then create an API endpoint.

<google-sheets-html-origin><style type="text/css"></style>
Metric | Status | Priority | Description | Vectors (guesstimate) | Calc | Notes | Task
-- | -- | -- | -- | -- | -- | -- | --
Router bids | To Do | P1 | Bids sent from router to sequencer | date, asset, chain, router, status | count, avg, median, max, min | Status = sent, received, accepted

**Acceptance Criteria**
[ ] Events are logged correctly 
[ ] Users can get this information from our API
 Routers can see where they have submit bids
 Routers can see where they have won vs. lost bids
 Routers can see if their bids are somehow not being captured in auctions

**Other**
Since this is not necessarily tied to a transfer, we may need to think through how the sequencer is logging this info

**Comment by alexwhte** [comment]
Idea: 
Dashboard for sequencer for all bids and seeing what activity is.

**Comment by sanchaymittal** [comment]
remvoing this issue from epic: #2102

**Comment by rhlsthrm** [comment]
Closing in favor of sequencer dashboard task.
