### ISSUE TITLE
As a sequencer, I need to have my relayer API key privatized

### ISSUE THREAD

**Issue by jakekidd** [connext/monorepo#1428]
**What is?**
Given:
- Sequencer sends the `execute` calls to relayer (Gelato) via the relayer's https API
- A special key is used to *temporarily* ensure the relayer network carries out the transaction even though it isn't directly profitable (we haven't built any sort of solution for Gelato relayers to handle the claiming pipeline yet). The transaction, of course, must be a connext transaction (the connext contracts are whitelisted by Gelato).

This exposes a small vulnerability. Example case to illustrate:
- I run my own router. I am whitelisted, have liquidity deployed, etc.
- I bootstrap and run a sequencer on the side. Instead of having my router talk to the official connext sequencer for the network, it talks to my sequencer. I also set the auction times to be basically 1 second.
- Now my router is firing off bids and winning every one of them bc it's a closed ecosystem, with the sequencer immediately sending every `execute` to the relayers. This, of course, affects the network at large. The router would be winning every transfer.

NOTE: This system could easily be simplified further by simply coding a custom router that does the sequencer stuff as well.

**How fix?**
Our network's sequencer should be unique in that it should have a 'direct line' of communication with the relayer network that no one else can have. Otherwise, what's the incentive to participate in the decentralized auction rather than run your own?

Best solution I see: have a custom private key that gelato gives us that goes in an .env file (as opposed to being hardcoded).

**Acceptance Criteria**
[ ] I, a rogue agent, am unable to boot up my own sequencer and run my own connext network that competes with the one on-chain.

**Other**
Finally, worth noting that the integration tests basically use this mechanism of a 'rogue connext network' to short-circuit the auctions. This is fine for the sake of staging testnet. Maybe we should leave the hardcoded gelato API key as a default that only works with staging contracts, and not with prod contracts?

**Comment by rhlsthrm** [comment]
We've talked about whitelisting the sequencer which would solve this problem in a more direct way @LayneHaber. We can also make the API key a secret I don't see an issue with that cc @carlomazzaferro .

**Comment by rhlsthrm** [comment]
The sequencer is whitelisted and the API keys are secret. I will close this.
