### ISSUE TITLE
As a dev, I want xcall to support multiple destination domains

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#1594]
**Problem**
Wonderland: 
Small question, is there any chance for xcalls to support multiple destination domains? It is something that Nomad supports, so it would be great to have it at least when using forceSlow. This would be pretty cool for Keep3r Multichain

**Ideas to solve this**
This could be a contract change or multiple xcalls offchain

**Acceptance Criteria**

- [ ] X happens
- [ ] Y happens

**Other**

**Comment by just-a-node** [comment]
To discuss in execution layer upgrade.
