### ISSUE TITLE
As a dev user, I need to calculate optimal proportion for stableswap deposits

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#1669]
**Problem**

Since users can deposit any arbitrary amounts via `addLiquidity`, UIs should be able to use the sdk to determine what the current optimal proportion is for token pairs in a pool. 

This will allow for adding tokens in a balanced proportion (if a user has both sides available) OR supply any amounts and conduct a swap-then-deposit into the balanced proportion.

**Ideas to solve this**

Add a function that swaps any imbalanced amounts into the optimal proportion taking into account:
1) the slippage from the swap
2) the pool's altered reserve ratio due to the swap

**Acceptance Criteria**

- [ ] takes input amounts[] and calculates the optimal proportion to deposit given current pool ratio +  slippage from an internal swap if input amounts are imbalanced + new pool ratio
- [ ] calls `addLiquidity` with new balanced amounts[]

**Other**

**Comment by alexwhte** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Connext-6272a34e0368a200141cd949/issues/connext/nxtp/1669?planning-poker) with Zenhub @rhlsthrm

**Comment by alexwhte** [comment]
Confirm if we should remove from Alpha

**Comment by alexwhte** [comment]
@just-a-node evaluate getvirtual price vs optimal solution please

**Comment by just-a-node** [comment]
This can be calculated using `calculateTokenAmount` on the user's input for tokenX and tokenY.
