### ISSUE TITLE
AWS should not leave behind inactive instances

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#1672]
**Describe the bug**
Sometimes after redeploy, instances of old version tasks in `INACTIVE` status are running after successful deploy.

**To Reproduce**
This was noticed in `staging` env recently for `router` `sequencer` and `cartographer` instances.

**Comment by preethamr** [comment]
This has not been seen in recent past. Keeping this in backlog, as we never found the root cause for this, and I am not a sure if this can happen again

**Comment by rhlsthrm** [comment]
Closing for now.
