### ISSUE TITLE
Grafana & Prometheus board for Lighthouse

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#1691]
**Problem**
A clear and concise description of what the problem is

**Ideas to solve this**
A clear and concise description of what you think could solve this problem.

- Number of transfers ( forcedSlow, Normal)
- Avg time for each domain
- frequency of each domain

**Acceptance Criteria**

- [ ] X happens
- [ ] Y happens

**Other**

**Comment by LayneHaber** [comment]
out of scope
