### ISSUE TITLE
As a team, we need e2e logs to be easily accessible

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#1720]
**Problem**
e2e tests logs are not easily visible. The logs of e2e services are in the docker containers are not easily accessible.

**Ideas to solve this**
We need a log export and aggregate mechanism, that makes it easy see all the logs from all the docker containers.

**Acceptance Criteria**

- [ ] Logs form e2e docker containers are exported, and can be aggregated.

**Comment by preethamr** [comment]
Moving to backlog, for when we want to rethink our e2e architecture.

**Comment by sanchaymittal** [comment]
re-open when we have new stuff once e2e implemented
