### ISSUE TITLE
Sequencer should handle mutipath transfers

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#1731]
**Describe the bug**
Sequencer should check for the minimum number of bids for multipath transfers, before executing the transfer.

**To Reproduce**
1. Send a single bid to sequencer for a transfer with path length > 1

**Additional context**
This check should happen in `sequencer-subscriber`

**Comment by preethamr** [comment]
TBD

**Comment by sanchaymittal** [comment]
another issue
