### ISSUE TITLE
As a dev, I want to subsidize gas costs for my users using sponsor vaults

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#1772]
**Problem**

We currently have a 1:1 mapping of sponsor vault per chain. Some xapps are interested in funding a vault to subsidize gas costs for their specific xapp's users. This would require adding a mapping for vaults that xapps can register. 

**Ideas to solve this**

Change vaults to a mapping and open a path for registration.

**Acceptance Criteria**

- [ ] Anyone can register a sponsor vault and fund it
- [ ] Funded sponsor vault is pointed at a specific xapp, subsidizing xcall gas costs going thru that xapp

**Other**

**Comment by rhlsthrm** [comment]
This would go a long way and help with onboarding/user growth IMO. Marking as P2.

**Comment by LayneHaber** [comment]
out of scope
