### ISSUE TITLE
As a developer, I would like to have a centralised location for each service's configuration

### ISSUE THREAD

**Issue by carlomazzaferro** [connext/monorepo#1800]
Currently the configuration for the service is split between JSON files, terraform configs, and default values defined in application code.

This leads to duplication and a lot of error-proneness in terms of knowing how to configure and run the services (locally), as well as knowing which configuration is being used in the live services

For Terraform config

**Comment by alexwhte** [comment]
https://www.notion.so/Config-Management-Local-Dev-Optimisations-49d13166e1c14911bca31cb354dc77b4

**Comment by rhlsthrm** [comment]
Nice to have but not realistic anytime soon.

**Comment by preethamr** [comment]
Should be an epic.

**Comment by preethamr** [comment]
Not a priority right now
