### ISSUE TITLE
Ensure pollers connection pool is closed

### ISSUE THREAD

**Issue by aandreakis** [connext/monorepo#1903]
**Describe the bug**

There are 3 files within the cartographer `poller/src/pollers` directory that initialize a connection pool to Postgres, run some code, and then close the pool and the underlying connections. The pollers do not ensure that the connection pool is closed if an exception occurs between initializing and closing the pool. This does not seem to be an issue currently because exceptions are caught further down the call stack. However, connection leaks can occur if underlying code changes and exceptions start leaking.

As a good practice, it is recommended to ensure that resources, like connection pools, are closed at the same level where they are opened.

The affected files:
- poller/src/pollers/messagePoller.ts
- poller/src/pollers/routersPoller.ts
- poller/src/pollers/transfersPoller.ts

All of them have code of this kind:
```
// do stuff (1) ...
context.adapters.database = await getDatabase();
// do stuff (2) ...
await closeDatabase();
```

A typical solution is to use `try-finally` or something with equivalent semantics:

```
// do stuff (1) ...
context.adapters.database = await getDatabase();
try {
   // do stuff (2) ...
} 
finally {
   await closeDatabase();
}
```

**To Reproduce**
1. throw exception after `getDatabase()`
2. verify that `closeDatabase()` is not called

**Comment by LayneHaber** [comment]
**Complexity: 2**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/22) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Urgency: 1**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/44) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Impact: 1**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/43) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
