### ISSUE TITLE
Router should not freeze

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#1960]
**Describe the bug**
Router-publisher was found to freeze, likely while polling the subgraph for `xcall`s, without producing any logs or exiting.

**To Reproduce**
There are no clear steps to reproduce this.

**Additional context**
Need to implement a way to detect such a stall, and trigger a timeout/restart.

Exact list of subtasks TBD.

**Comment by alexwhte** [comment]
P2 - workaround is to restart

**Comment by preethamr** [comment]
This has not happened in the recent past, and during all the load tests, and live nets.
But keeping it in backlog, as this part "Need to implement a way to detect such a stall, and trigger a timeout/restart." might be needed still.

**Comment by LayneHaber** [comment]
closing, this is stale pending recent refactors
