### ISSUE TITLE
As a deployer, I want the init script to be able to update the adopted asset

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2056]
## Problem
If a different canonical<>adopted mapping is specified compared to what is currently registered for an asset, then the init script should remove the current mapping and set it up with the new one.

For example: if an asset was originally registered where `local == adopted` and later the `desiredAdopted` should be different, then the script needs to handle this.

See `TODO` line [here](https://github.com/connext/nxtp/blob/fbe3017921f3058eaac7f2f5ec4ec6fb2d0e7352/packages/deployments/contracts/src/init/helpers/assets.ts#L70).

## Proposed Solution
- [ ] If `desiredAdopted` != current adopted, call `removeAssetId` to clear the existing registration.
- [ ] Call `setupAssetWithDeployedRepresentation` to set up the new mapping.

## Acceptance Criteria
- [ ] Init script can update the canonical<>adopted mapping.

**Comment by preethamr** [comment]
Is it still the case @just-a-node
