### ISSUE TITLE
Bump slippage % on UI

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2094]
## Summary

If slippage is exceeded on destination, we need to communicate with user

## Proposal to fix
SEE SPEC
https://www.notion.so/connext/Bump-slippage-Relayer-fee-UX-bd1e267baca046988976a64879224abf

## Acceptance Criteria
- [ ] User is notified of the slippage failure
- [ ] User is presented options to proceed
- [ ] User can bump slippage
- [ ] Execute retries automatically (if they bump OR not)

**Comment by alexwhte** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Connext-6272a34e0368a200141cd949/issues/connext/nxtp/2094?planning-poker) with Zenhub @sanchaymittal @just-a-node @rhlsthrm

**Comment by just-a-node** [comment]
Going to consider this non-launch blocking, we have a workaround in case this edge case occurs:
- user will need to grab the input fields for TransferInfo (available in subgraph data or cartographer)
- user will call `forceUpdateSlippage` on the contract via Etherscan or otherwise

**Comment by alexwhte** [comment]
@just-a-node @sanchaymittal 
Can we prioritize higher a super light spec for Coinhippo to display an error icon on transfers where slippage was exceeded

We can implement full UX for bumping separately but this is a good start

**Comment by rhlsthrm** [comment]
I created a task here: https://github.com/connext/monorepo/issues/2962.

> @just-a-node @sanchaymittal Can we prioritize higher a super light spec for Coinhippo to display an error icon on transfers where slippage was exceeded
> 
> We can implement full UX for bumping separately but this is a good start

**Comment by alexwhte** [comment]
unblocked by https://github.com/connext/monorepo/issues/3061

**Comment by pjenviri** [comment]
We handle it similarly to the insufficient relayer fee approach. In this case, we checks if the `error_status` = `XTransferErrorStatus.LowSlippage`, then  `sdk.nxtpSdkBase.updateSlippage`

**Comment by just-a-node** [comment]
This one should be a LowSlippage issue but the call to action doesn't show on UI: https://connextscan.io/tx/0x93768e9fe5c6bb43f49277a2cd2b19660bd878975a34f12c6f67531a698778d3

**Comment by just-a-node** [comment]
QA again after https://github.com/connext/monorepo/issues/3409
