### ISSUE TITLE
Improve backend unit tests

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#2122]
### Problems

The backend(cartographer) unit test doesn't cover all the branches and functions.  
for example, to cover the functions and branches for src/lib/operations/roots, we should have a test to deeply check both `updateAggregatedRoots` and `updatePropagatedRoots`. Right now, we're just calling `bindRoots` in test/lib/operations/roots.spec.ts which seems wrong.
This case exists in src/lib/operations/messages.ts as well.

**Comment by alexwhte** [comment]
fixed
