### ISSUE TITLE
Add banner in nxtp-v1 to use Amarok

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2184]
## Problem
We need a way to cut over users from nxtp-V1 to the new product

## Acceptance Criteria
- [x] User sees a banner in nxtp-v1 to replace "xPollinate is now Connext Bridge."  
It should instead say
"New V2 UIs are live! Click here to be an early liquidity provider."
- [x] User are directed into https://amarok.bridge.connext.network/pools
- [ ] Amarok mainnet has a 'BETA' tag added under the Connext Logo on all UI pages
- [ ] Add ability to return back to nxtp-v1 if they choose
- [ ] Add button bottom right that says "Issues or feedback" and links to our Discord https://discord.com/invite/connext

**Comment by pjenviri** [comment]
@alexwhte 
should we add the links for returning to the old version & receiving feedback like this: 
![ui.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/caef2e15-f7d0-4666-9536-029b1fd1d1b8)

**Comment by pjenviri** [comment]
@alexwhte 
should we add the links for returning to the old version & receiving feedback like this:![ui.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/0c67ce01-b4b6-41c5-9c89-b4902b2f9ee7)

**Comment by pjenviri** [comment]
This is related to the issue we discussed [here](https://github.com/connext/monorepo/issues/3223#issuecomment-1408002655). I believe that the upcoming fix release should resolve this card as well.

**Comment by alexwhte** [comment]
Can we make it brighter and more modern font like this? 
![image](https://user-images.githubusercontent.com/37959170/215632890-a87aa32d-aeb3-47b0-8088-dcc40a0890b9.png)
https://www.figma.com/file/4FEgX8CwUgNbSpz2kpiZdE/Untitled?node-id=0%3A1&t=vAiTA1bLgWPjOPvu-1

Also change the new tags to be better aligned and inside square corner boxes to align with UI panes 
![image](https://user-images.githubusercontent.com/37959170/215634392-c24712d1-d1e8-4fd6-8492-a9040741b408.png)

**Comment by sanchaymittal** [comment]
QA done, looking good!!
