### ISSUE TITLE
Mainnet contract deployment is too expensive.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2186]
It costs >1 ETH to deploy everything. We should make sure everything we deploy is actually required, and if not remove it. Things like Multicall and PriceOracle off the top of my head are not being used.

Deployer: https://etherscan.io/address/0xade09131C6f43fe22C2CbABb759636C43cFc181e

**Comment by liu-zhipeng** [comment]
Actually we don't deploy `PriceOracle` contract.

**Comment by alexwhte** [comment]
Sad
