### ISSUE TITLE
As a dev, i want to make sure contract upgrade doesn't change the storage layout

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#2187]
## Problem
_What problem are we solving and why does it matter, ser?_ 

## Proposed Solution
- integration https://github.com/odyslam/bash-utils to CI/CD

> Commit the storage layout to a Git repository and have the CI run forge-inspect check. If the check fails, that means that the storage layout changed. The developer will need to acknowledge that difference and commit the new storage layout for the test to pass

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens

**Comment by LayneHaber** [comment]
out of scope
