### ISSUE TITLE
stable swap subgraph mapping update

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#2205]
## Summary
What are we doing, ser? 

- created the structure for stableswap subgraph, but will need to test it against the live data.
- add mapping for handleRampA, handleRemoveLiquidityOne, handleTokenSwap

## Acceptance Criteria
- [ ] X happens

**Comment by just-a-node** [comment]
We need to account for internal StableSwap events too. Create new subgraph mappings for those?
