### ISSUE TITLE
Batch proofs in proveAndProcess

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2257]
## Problem
We can optimize gas calls on prove and process by proving multiple messages within a single aggregate root.

## Proposed Solution
- [ ] Send multiple proofs for the same aggregate root in a single proveAndProcess tx.

## Acceptance Criteria
- [ ] ProveAndProcess is called with multiple messages.

**Comment by rhlsthrm** [comment]
I believe the work here is done, but needs to be configured with reasonable batch sizes on all environments.

**Comment by preethamr** [comment]
> 

How do we decide what is reasonable ?
Do we want to have granular controls - per chain max gas and batch size ?
Or do we want to make it dynamic, based on current chain conditions ?

**Comment by rhlsthrm** [comment]
> > 
> 
> How do we decide what is reasonable ? Do we want to have granular controls - per chain max gas and batch size ? Or do we want to make it dynamic, based on current chain conditions ?

Eventually we should make it smarter but for now we should make it simple: Use a batch size that works for all chains and won't fail at high gas prices.

**Comment by rhlsthrm** [comment]
Finding out that the batch size we are using for all chains isn't working. We need to configure this per chain.

**Comment by rhlsthrm** [comment]
Fairly low effort, potentially high impact.

Need to:
- Test with forks and see what batch sizes work on different chains.
- Set batch sizes appropriately.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/22) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Related to getting testnet-prod back up.

**Comment by wanglonghong** [comment]
Here's the gas consumption per batch size. 

[Gas Price: 1.5 gwei]
Single - 0.00047 ETH
https://explorer.goerli.linea.build/tx/0xc3c6a052abf4171aecf561d781b47428c073b4465adc23b71fca93e712ad4b99/logs

5 batch - 0.00114 ETH
https://explorer.goerli.linea.build/tx/0x2d08aa191d74e209ebe5917a95aae96133653a266972e99b2843de0d8f6e1a14/logs

10 batch - 0.00199 ETH
https://explorer.goerli.linea.build/tx/0xbca82bea96d0da9941953f1adde7e25e1b3b0ffd200daa7822aac9c457e870e0

**Comment by rhlsthrm** [comment]
Excellent! What's the highest we can get it before we hit gas limit issues?

**Comment by rhlsthrm** [comment]
Gas usage:

Single: 315,097
10 batch: 1,329,445

So we verified 10x the amount of transfers for around 5x the gas, which is still a solid savings. Curious to see how high we can get the batches.

**Comment by rhlsthrm** [comment]
PR in, working on local, needs some small fixes.
