### ISSUE TITLE
As a [end user], I want set destination address without going to settings in order to do it faster/find it easier

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2314]
## Problem
Destination address being too hidden/inaccessible. We got this feedback from a few users already. I don't know if it's worth implementing due to possible (noob) user errors that don't know how to use it correctly.

## Proposed Solution
Include the destination address field at the bottom of the bridge card. We would need some safeguards to prevent users from screwing up.
![image](https://user-images.githubusercontent.com/84744304/199574370-f4579633-df94-406d-b52c-65a752b1fe41.png)

## Acceptance Criteria
User can fill in a different destination address from the main UI.

**Comment by alexwhte** [comment]
We should query data around what % of bridge transfers or wallets change this today

**Comment by Tommy-R8** [comment]
We should definitely implement this at least:
![image](https://user-images.githubusercontent.com/84744304/199907236-15c9f84a-2c57-4d8c-bacf-dec919c04bc5.png)
I found myself quadruple checking many times and this would add peace of mind

**Comment by alexwhte** [comment]
It makes sense to show if the user updates it. 

@Coinhippo please display user destination address under the You Receive section if they change it in advanced settings
![image](https://user-images.githubusercontent.com/37959170/212775315-b469994c-ce83-488b-b11b-3e8c95ccdb18.png)

The reason I'd backlogged moving it out of advanced was not having a strong sense of demand.  Like say adding anything to the main pane we see if like >20% of users or if a frequent user cohort always updates custom destination address. And/or or test if showing it in the main UI moves the needle on usage/engagement. 

But please keep noting requests here we can better track demand in the meantime

**Comment by alexwhte** [comment]
love it!
