### ISSUE TITLE
As a [end user], I want to see the infinite approval toggle in the main UI

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2315]
## Problem
The infinite approval toggle is hidden in the settings by default (and set to on). I believe I discussed this with @alexwhte in our call.

## Proposed Solution
If the toggle will be set to on by default, then show it in the main UI.

## Acceptance Criteria
Infinite approval toggle is shown in the main UI.

**Comment by alexwhte** [comment]
This is intentionally in advanced settings right now.Our hypothesis is the majority of users don't know what this is, and it's often not an option in bridges. 

Need more data on this or broader user feedback @Tommy-R8, but others said they dont need to see it or wouldnt use it.

**Comment by pjenviri** [comment]
To confirm, should we move the infinite approval toggle to the main UI? or should we wait for more feedback on this?

**Comment by pjenviri** [comment]
To confirm, should we move the infinite approval toggle to the main UI? Or should we wait for more feedback on this? @alexwhte

**Comment by just-a-node** [comment]
Won't do.
