### ISSUE TITLE
Slippage setting resets when changing network

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2324]
**Describe the bug**
Default slippage is 3%. When you change this and apply changes, these changes do not persist if you switch network. It resets to 3%.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Click on Settings
3. Switch slippage from 3% to another number
4. Apply changes
5. Switch origin chain
6. Click on Settings
7. See error

**Expected behavior**
Slippage settings (and all special settings) should be persistent on origin chain changes.

**Comment by alexwhte** [comment]
fixed
