### ISSUE TITLE
As a [end user], I want tooltip icons to know there's a tooltip

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2328]
## Problem
It's unclear to the user what happens when, for example, the swap rate exceeds the slippage tolerance.

## Proposed Solution
Hint/tooltip next to the tolerance setting should show something like "The transfer won’t go through if the bridge rate moves unfavorably by more than this percentage when the transfer is executed." (words from the user that suggested this). Things become weird when talking about a cross chain swap not going through. I believe @alexwhte had some similar suggestions listed about other settings.

## Acceptance Criteria
From a user perspective, understand where my funds will end up and in what form (next assets, canonical assets).

**Comment by alexwhte** [comment]
@Tommy-R8 We have a tooltip, do we need tooltip icon? I am updating the text to be a little more like this though 
Alex

**Comment by Tommy-R8** [comment]
Thinking about how many people will use mobile, an icon would probably be a good idea.

**Comment by alexwhte** [comment]
Good point

**Comment by pjenviri** [comment]
Added the _tooltip_ icon to the mobile view.
![Screenshot 2566-01-17 at 21.53.13.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/5ab7677d-6ca8-4c6f-a03c-011f00ccf5f7)
