### ISSUE TITLE
As a [end user], I want a clipboard button in order to copy my TX ID

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2366]
## Problem
Users can't copy their TX ID without going to the explorer link.

## Proposed Solution
Add copy to clipboard button next to the "see more in explorer" link just like in current NXTP.

## Acceptance Criteria
Button copies TX ID correctly? idk, kinda self explanatory.

**Comment by alexwhte** [comment]
will get back to this

**Comment by sanchaymittal** [comment]
it's already there, copy icon is present in front of txId.
