### ISSUE TITLE
As a [end user], I want to receive a notification when a transfer is completed

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2368]
## Problem
Users want to fire a transaction and click away, and so they won't know when their transaction is completed unless they check manually.

## Proposed Solution
Some notification system (like a sound) to alert the user that the bridging was completed.

## Acceptance Criteria
Reliably notify the user when a transfer is completed.

**Comment by alexwhte** [comment]
I like this

**Comment by alexwhte** [comment]
@pjenviri @nrsirapop i'm just reviewing outstanding issues, let me know if this might need more scoping or specifics on how to show notifications, i realize it's open-ended

**Comment by pjenviri** [comment]
We're concerned about building a separate backend system for solely maintaining this feature and don't think it will be worth the effort for now (it's hard to maintain).
