### ISSUE TITLE
Unclear Approve and Transfer

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2379]
**Describe the bug**
The site checks for token spending approval _after_ clicking transfer, and then prompts 2 transactions to the user (approval and transfer). We should make it clear to the user that they are doing 2 separate transactions and show what they are before clicking on "Transfer".

**To Reproduce**
Have approval limit set to 0 before starting.
1. Go to https://amarok-testnet.coinhippo.io/
2. Select an amount
3. Click Transfer
4. See problem

**Expected behavior**
The site should check for token approval and show an approve button before clicking on transfer.

We received this feedback from a few users but I still think this is up for debate. I believe some platforms do it the way I described and some others do it like we're doing right now.

**Comment by sanchaymittal** [comment]
Based on the above feedback, UX improvements already happened.
