### ISSUE TITLE
Approval check doesn't work with more than 6 decimal places

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2380]
**Describe the bug**
When inputting an amount lower than 1e-6 the approval check keeps loading and gives an error.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Input amount lower than 1e-6
3. See error

**Expected behavior**
The approval check should allow up to 18 decimal places (or whatever the lower limit is for a given token)

**Screenshots**
![image](https://user-images.githubusercontent.com/84744304/200344481-5faf4215-dc14-4d92-9e28-8300bb556b4e.png)

**Comment by alexwhte** [comment]
not replicating anymore, clsoing
