### ISSUE TITLE
[EXPLORER] As a [end user], I want links to the on chain addresses for a given swap

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2409]
## Problem
Current explorer has links to the chain explorer's addresses (to and from) that are part of a given swap. Amarok explorer doesn't have this when viewing an address's history.

## Proposed Solution
Have the highlighted tx ids link to the addresses in the corresponding chain explorers 
![image](https://user-images.githubusercontent.com/84744304/200704012-f8f2c7a7-a4aa-41e0-85b9-ca6dac29a4c9.png)
 

## Acceptance Criteria
Self explanatory

**Comment by alexwhte** [comment]
@Tommy-R8 do you want us to link to each chain's explorer like this? 
https://optimistic.etherscan.io/address/0x6d91e35d502fb6f654992283e6e4f397fc23dc2c

**Comment by Tommy-R8** [comment]
@alexwhte Exactly

**Comment by alexwhte** [comment]
This makes sense also clicking these origin/des adderesses right now shows animation of reloading at top of the page but doesnt do anything which is strange. Instead we can link out to chain explorers (and should remove this animation) 

https://amarok.connextscan.io/address/0x29a519e21d6a97cdb82270b69c98bac6426cdcf9
