### ISSUE TITLE
Metamask/web3 wallet missing from wallet modal

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2460]
**Describe the bug**
The option to connect a Metamask/Rabby/similar wallet client is not present in some cases.

**To Reproduce**
Use chromium based browser (user used Chrome and Vivaldi) and Metamask.
1. Go to https://amarok-testnet.coinhippo.io/
2. Click on Connect
3. See error

**Expected behavior**
The connect wallet modal should show all the options. User had to manually connect to the site on metamask. 

**Screenshots**
https://discord.com/channels/454734546869551114/1041030558190420100/1041030919164792943
![image](https://user-images.githubusercontent.com/84744304/201485129-9a563f23-d466-4096-9cb5-6b083d2a0286.png)

**Comment by pjenviri** [comment]
I cannot reproduce. it works on my end.
<img width="1440" alt="capture" src="https://user-images.githubusercontent.com/87146398/201943409-4768df49-38cb-4aca-93f3-53e06b09f91e.png">

**Comment by just-a-node** [comment]
What version of Chrome was the user on? Can't seem to repro on my end either.
