### ISSUE TITLE
User can claim their own incentive rewards 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2539]
## Problem
Users will receive incentive rewards for LPing on individual pools. We need to show how much they have gained and allow them to claim rewards. 

## Proposed Solution
- [Preferred] if through multisig we can do it custodial. we would need claiming contract (just find one that exists). expose to coinhippo with SDK call
- [Alternative-riskier]  offchain send from hotwallet 

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] User can see their rewards in the UI
- [ ] User can claim their rewards to their wallet
- [ ] [TBD] Do we have any rewards lockup period?

**Comment by just-a-node** [comment]
Will re-craft this task for LP staking.
