### ISSUE TITLE
As a team, we need a watcher agent deployed to mainnet

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2626]
Spec: https://www.notion.so/connext/Watcher-v0-5ccc3c081bc647a9bc311e30860ba74e

**Comment by jakekidd** [comment]
1. create adapter: https://github.com/connext/nxtp/issues/2627
2. create agent (wraps the adapter): https://github.com/connext/nxtp/issues/2625
3. e2e for agent: https://github.com/connext/nxtp/issues/2629
4. deploy agent: https://github.com/connext/nxtp/issues/2628
