### ISSUE TITLE
Get supported chains and assets through SDK

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2636]
## Background

Expose utility to get supported chains and assets through SDK.

## Definition Of Done

SDK users should be able to grab currently supported chains and assets instead of hardcoding their own configs.

## Tasks

- [ ] SDK method for supported chains
- [ ] SDK method for support assets on each chain

**Comment by alexwhte** [comment]
Closing as dupe of https://github.com/connext/monorepo/issues/2939
