### ISSUE TITLE
Pool metrics are shown (daily volume + APR breakdown)

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2641]
## Background

In the pools view and for each individual pool page, show:
- daily volume
- current APR: show breakdown of pool APR, reward APR, and total APR. if there is no reward APR, just show the pool APR. each APR should be represented by the appropriate asset icon.

Volume and APR of the pool asset an be calculated using SDK method `getYieldData`. For incentive reward asset APR, see https://github.com/connext/nxtp/issues/2538. 

## Tasks

Following metrics are shown for each pool
- [ ] daily volume
- [ ] current APR (broken out by pool asset + reward asset if applicable)

**Comment by pjenviri** [comment]
We still get errors from `getYieldData` for some pools (https://discord.com/channels/454734546869551114/909827059373723648/1050497407948963960). It depends on which pool. Some get the error, and some don't. We also found infinite RPC requests when calling `getYieldData`.

**Comment by just-a-node** [comment]
We need to figure out which pools are erroring and when the infinite loop occurs. Initial tests using sdk-server have not been able to reproduce.

**Comment by pjenviri** [comment]
We have commented out the `getYieldData` part (https://github.com/CoinHippo-Labs/connext-bridge/blob/amarok/components/navbar/index.js#L840-L846). Can you try running it locally and inspect the network activity on the browser?

**Comment by just-a-node** [comment]
`getYieldData` should be fixed, once we release `v0.2.1-rc.12`

**Comment by sanchaymittal** [comment]
completed and released.
