### ISSUE TITLE
Unwrap/Wrap ETH feedback

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2642]
## Background

We have decided to abstract away the wrapping from the user entirely. This means we should show both "ETH" and "WETH" as selectable options for the bridge and display the correct user balances. 

If user selects ETH, we need to wrap it to WETH and bridge with WETH.

- Polygon ETH doesn't exist, don't include it as an option

**Comment by pjenviri** [comment]
Can you update the `xcall` to receive `addressZero` and support this case? IMO, it'd be better to support it rather than customizing it case by case. Please let me know your thought.

**Comment by just-a-node** [comment]
We only support `addressZero` as the asset if the `value` is also 0, basically for the use case of calldata-only transfers. We had some internal discussions about this and settled on not handling native asset transfers in the bridge contract. The contracts are frozen now, unfortunately, so wrapping WETH will have to be handled on UI side.

**Comment by pjenviri** [comment]
Ok, we can do that; by the way, I meant the xcall method on SDK. Nothing to do on the contract level. And if we proceed with this approach, other devs must manually wrap ETH on Ethereum before calling xcall on SDK. It will not be a friendly experience for them, IMO. Again, it's just my opinion, though.

**Comment by just-a-node** [comment]
Understood now, and agree this should be done in SDK.

**Comment by jakekidd** [comment]
added into SDK here https://github.com/connext/nxtp/pull/2771

**Comment by just-a-node** [comment]
@pjenviri See new params in `xcall` here: https://docs.connext.network/developers/reference/SDK/sdk-base#xcall

UI needs to set `wrapNativeOnOrigin=true` when we are sending ETH on origin.

**Comment by just-a-node** [comment]
Seeing one error:

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/36fad60d-00dd-4a9c-a145-4a855eb16781)

Also, when user sends ETH they should receive ETH.

**Comment by just-a-node** [comment]
One update / additional consideration: `unwrapNativeOnDestination` shouldn't be hardcoded to always be `true` if user is sending ETH from origin. If user selects "receiveLocal", then `unwrapNativeOnDestination=false`.
