### ISSUE TITLE
Countdown timer should be updated if transaction completes early

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2726]
**Describe the bug**
If transaction completes onchain early, the UI is still showing the countdown.

**Expected behavior**

Countdown should update correctly (note the latest transfers section already shows it completed so it's just a matter of making sure the rest of the UI responds).

**Comment by pjenviri** [comment]
Does the issue persist? Can you try to reproduce it again?

**Comment by just-a-node** [comment]
Yes, the transfer status gets updated and the countdown continues. Here's a screen recording, at the 16s mark the transfer shows complete on the right:

https://share.vidyard.com/watch/2ctrSChukNMJz5x4FAqqHN?

**Comment by just-a-node** [comment]
And it also just stays like this when it reaches 0:

![image](https://user-images.githubusercontent.com/16638982/208158319-2410def8-ec90-4c45-8b02-fd8096248903.png)

**Comment by pjenviri** [comment]
Can you please try it again? We have some updates that hope to fix it; however, we cannot reproduce the issue.

**Comment by alexwhte** [comment]
@pjenviri can we test in staging or locally with lower time like <1min? To confirm it works
I also cannot replicated atm

**Comment by just-a-node** [comment]
Some users have recently reported that the timer stays on the "Processing" screen after it completes. 

Can we try to repro this further?

**Comment by sanchaymittal** [comment]
Let's post the step to repro or the comment to understand this issue further. It seems to be happening infrequently. closing it for now.
