### ISSUE TITLE
Pools taking too long to load BUT not showing user there is a delay

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2783]
**Describe the bug**
We need to show the user that the UI is loading, or ideally which pools there are and that information is loading. Instead the Pools are popping onto the screen and loading is hidden from the user, which is misleading. 

TESTNET
Polygon appears after >30 seconds 
https://www.awesomescreenshot.com/video/13438556?key=b97d90fbfd5e24f0faf2f06f2d96537f

MAINNET
https://www.awesomescreenshot.com/video/13438597?key=a22411cfe29690afdef49f3ed0785648

**To Reproduce**
1. Go to https://testnet.bridge.connext.network/pools
2.  Wait

**Comment by just-a-node** [comment]
Can we also keep the token category position fixed while/after it loads? You can see here that the category jumps around a lot near the end of the load: https://share.vidyard.com/watch/4M54AveaKaFNfxMuyksPKL?
