### ISSUE TITLE
Review price impact calculation for pooling

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2896]
**Describe the bug**

Price impact needs to be validated. In some cases, the resulting percentage doesn't seem to make sense.

If an asset/nextAsset is overweight, supplying liquidity in mostly that asset should result in positive price impact (less LP tokens), and vice versa.

**Comment by alexwhte** [comment]
![image](https://user-images.githubusercontent.com/37959170/210640984-0f96d6a7-1dd1-4fbb-a7e6-5b9174de4123.png)

![image](https://user-images.githubusercontent.com/37959170/210641088-974b99af-6570-4939-9bfd-c44edbb63b05.png)

**Comment by alexwhte** [comment]
@just-a-node Some notes from today:
Currently we are showing positive price impact where user provides the underweighted asset (but per convo you mentioned negative is good, as it means more LP tokens)

We should do one or both of
1. Check if our current calculation logic is wrong
2. See how curve calculates, as they actually show a reward amount instead

https://www.awesomescreenshot.com/video/13740859

Separately: Im also seeing 100% price impact for providing USDC on BNB chain with any amount

**Comment by alexwhte** [comment]
@just-a-node @liu-zhipeng Im still seeing this for BNB

![image](https://user-images.githubusercontent.com/37959170/211974847-bc5cbae7-87ec-4a2a-85ca-f5a9bbca052f.png)
