### ISSUE TITLE
TVL should include both router liquidity and pool totals

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2899]
**Describe the bug**

Currently TVL on the overview page only shows total router liquidity. TVL should include both router liquidity *and* total amounts pooled (assets + nextAssets).

**Comment by alexwhte** [comment]
Would still be great to be able to toggle router and liquidity separately, but this might be an enhancement

**Comment by alexwhte** [comment]
@pjenviri @nrsirapop this is good to pick up. You can ignore my last comment for the sake of prioritization

**Comment by sanchaymittal** [comment]
@nrsirapop I can't see the required changes yet, can you link or add a screenshot?
Also, it would be great to tag the pr for better QA with some screenshots.

**Comment by pjenviri** [comment]
The TVL chart now includes both router liquidity and total amounts pooled (assets + nextAssets). You can hover to see the values.
![ss.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/e5686ea0-3984-41de-a33b-2d17b28ee747)

**Comment by sanchaymittal** [comment]
Got it! Nice work! closing it.

**Comment by alexwhte** [comment]
@sanchaymittal did this take 20 mins to load for you?  this is because we are calling from subgraphs maybe? 

https://www.awesomescreenshot.com/video/14068903?key=06d7546a6c89508f3be4e885c92751d8

@pjenviri not sure why you reopened but we should align on this

**Comment by pjenviri** [comment]
@alexwhte, sorry, I might misclick this. closing it.
