### ISSUE TITLE
Bridge UI button stuck on "Transfer in progress ..." after transfer is sent

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2902]
**Describe the bug**

Transfer gets initiated, pending txn shows up in the "Latest Transfers" side bar, but the button still says "Transfer in progress ..." until the page is refreshed.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/318adf89-308c-491f-9df4-81c5420a8208)

**To Reproduce**
1. Go to bridge UI
2. Use USDC as asset, BNB as origin chain, any chain as destination chain
3. Bridge the asset
4. Wait for transaction to go through, shows up on sidebar
5. Button stays on "Transfer in progress ..." until user refreshes

**Additional context**

**Comment by alexwhte** [comment]
@just-a-node I wasnt able to replicate. DId you see this often?
