### ISSUE TITLE
USDC Fastpath to BSC is not available on UI

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#2903]
**Describe the bug**
USDC Fastpath to BSC is not available on UI.

This however works via direct XCall.

**To Reproduce**
1. https://amarok.bridge.connext.network/USDC-from-polygon-to-binance?amount=0.01
![image.png](https://images.zenhubusercontent.com/633cc19244d069b42f3ce99e/af347a7a-7c05-4918-bb08-a248413553c7)

**Additional context**
This is most likely because of USDC decimals on BSC, and how the UI handles it.

**Comment by alexwhte** [comment]
@preethamr I dont think there is enough router liquidity right? Since we removed it
https://amarok.connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c

**Comment by just-a-node** [comment]
Per discussion in discord, BSC as destination never shows fast path even though there is sufficient router liquidity.

**Comment by alexwhte** [comment]
@pjenviri this is the estimate showing 90 mins (slow). Please take a look
