### ISSUE TITLE
Add handling to disallow receiving nextAsset on Ethereum

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2906]
Receiving nextAssets on Ehtereum should not be possible 

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/ae7a2061-6d21-45be-9568-4a180e66eb86)

Please add this handling
1. If receive NextAssets is true
then remove Ethereum from Destination selection 

2. If Ethereum is set as destination
then disable the 'Receive NextAssets' toggle in advanced

**Comment by alexwhte** [comment]
Two more changes
1. Grey it out (not hide) when destination is Ethereum. Add tooltip 'Unavailable on Ethereum.' This is  In case a user looks for it, because it's not self-explanatory. 
2. When you switch destination to Ethereum ensure state changes to False (if True). When you switch destination to other chains it should maintain state as it does today 

https://www.awesomescreenshot.com/video/13799275

**Comment by just-a-node** [comment]
This fixes 2.

For 1, it's behaving where you can switch to Ethereum but the "Receive NextAsset" toggle will automatically go off. IMO this is better than removing Ethereum from the destination select if you have "Receive NextAsset" on. But perhaps make it more obvious that the setting was toggled off- because when you switch between chains other than Ethereum, the toggle stays on. It should flash or do something special, wdyt? @alexwhte

**Comment by alexwhte** [comment]
yeah i think that makes sense sorry that part to hide Ethereum was bad idea actually

we can 
1. remove the new logic to hide Ethereum destination when this option is selected 
2. keep the logic to disable this setting when ethereum destination is selected
3. when #2 happens, flash a temporary message somehow that "Receive NextAsset setting turned off for Ethereum."

**Comment by alexwhte** [comment]
@nrsirapop Can we actually do a temporary message rather than below the amount? It feels like it's related to the amount and might confuse users because it's persistant

Doesnt need to be a banner, but something quick like this that is temporary
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/b6a51419-33d8-4b80-bb2b-1fe410c03115)

**Comment by alexwhte** [comment]
@nrsirapop Can we actually do a temporary message rather than below the amount? It feels like it's related to the amount and might confuse users because it's persistant

Doesnt need to be a banner, but something quick like this that is temporary
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/b6a51419-33d8-4b80-bb2b-1fe410c03115)

**Comment by alexwhte** [comment]
perfect thanks
