### ISSUE TITLE
Limit to 6 decimals or less throughout UI

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2911]
For any numbers with multiple decimal places, please round to max 6 digits 
-- For anything smaller, show anything less show "< 0.000001"
-- Add tooltips to show the full number 
ex
![image](https://user-images.githubusercontent.com/37959170/210474486-c5061c31-a094-4f2e-9a5c-43860efc0861.png)

Examples where numbers are too large
![image](https://user-images.githubusercontent.com/37959170/210474151-6557be30-734c-4b99-b323-9ce4886f6244.png)

![image](https://user-images.githubusercontent.com/37959170/210474099-d7ddd4d6-3c76-451d-b16d-7093e3328255.png)

This has scientific notation which feels inconsistent
![image](https://user-images.githubusercontent.com/37959170/210474179-53b07d52-d0b1-4f0d-87a1-9a5bc76b532f.png)

**Comment by just-a-node** [comment]
We need to do this for sidebar transactions as well, if the amounts are small there is overlap.
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/327e6f82-3f6b-4567-ab3d-bef0ddaa0b41)
