### ISSUE TITLE
"You Receive" for receiving nextAsset shouldn't max out at pool amount

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2913]
**Describe the bug**

When receiving nextAsset, the "You Receive" amount is inaccurate.

**To Reproduce**
1. Toggle "Receive NextAsset"
2. Attempt to bridge an amount > current pool balance of nextAsset in pool
3. Since "Receive NextAsset" is toggled, the amount received should not take into account the available balance of the pool on destination side since it's not swapped.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/fba76e1c-f17d-47dd-a757-6b00c6e98504)

**Comment by alexwhte** [comment]
Testing this, something looks off with the amounts. 

Is this a separate issue? 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/37959170/211120745-8c9c5218-9b86-4a6f-964b-664caaf039e0.png">

**Comment by pjenviri** [comment]
We check the balance in the user's wallet before checking the pool amount. So the UI immediately returns the `Insufficient Balance` before other error messages. Should we swap the checking order? @alexwhte @just-a-node

**Comment by pjenviri** [comment]
hey @alexwhte , wanted to follow up on my message above. Thanks!

> We check the balance in the user's wallet before checking the pool amount. So the UI immediately returns the Insufficient Balance before other error messages. Should we swap the checking order?

**Comment by sanchaymittal** [comment]
@pjenviri sorry for missing the message above.
The above is looking good to me. Probably decimals were messing it up. closing the issue, please re-open if required
cc: @alexwhte
