### ISSUE TITLE
Remove "NXTP"

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2915]
## Background

We are moving away from all things "NXTP".

User-facing interfaces have already been pruned. This task will cover the rest of the codebase.

## Definition Of Done

No references to NXTP exist in any of the offchain code, packages, etc.

**Comment by ArjunBhuptani** [comment]
Increasing priority on this as we should get it done ASAP for integrations

**Comment by just-a-node** [comment]
#3183 to tackle the user-facing portions. Let's keep this one open for updating the rest of the repo.

**Comment by rhlsthrm** [comment]
Reducing priority since all the user-facing stuff is done.

**Comment by rhlsthrm** [comment]
Adding to pri so we can just rip the bandaid.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/31) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 1**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/32) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 1**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/33) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/28) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
fixed by #3238

likely out of scope
