### ISSUE TITLE
Segment EOAs from Contracts in logged transfer data

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2927]
## Problem
At scale over time it will be hugely important to be able to segment where transfers come from EOAs (generally UI users) vs. from contracts (integrations)

Not sure if this is misleading, but afaik it's difficult and/or expensive to resolve this type using an Ethereum address alone 
https://ethereum.stackexchange.com/questions/132717/how-to-determine-whether-an-address-is-an-eoa-or-a-contract-address

## Proposed Solution
One idea is logging a new column in cartographer like `caller_source_ui` that is `true` whenever transfers are initiated through the Bridge UI

There might be better ideas. This is also not as helpful if you are using onchain data 

## Acceptance Criteria
- [ ] Able to segment out transfer data ideally between EOAs and contracts OR at least between UI users vs. non-UI users

**Comment by rhlsthrm** [comment]
I've mentioned before that we should have a "metadata" field in xcall that allows us to specify metadata that gets emitted in xcall and would let us add some extra info to the call, then that would let us add sources. Cc @LayneHaber

**Comment by alexwhte** [comment]
@rhlsthrm can we close this due to txorigin change?

**Comment by rhlsthrm** [comment]
We have the data to segment EOAs from contracts but we do not know UI vs non-UI. I will close this for now.
