### ISSUE TITLE
As a pool UI user, I want to see the accumulated fees (24H) per pool

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2929]
## Problem

Show 24H pool fees per pool.

![image](https://user-images.githubusercontent.com/16638982/210710691-bd9730a7-d94c-4dce-acfc-10b52d496779.png)

## Proposed Solution
- Show pool fees per pool

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Each pool shows the accumulated pool fee in last 24 hrs (`getYieldStatsForDay` has this data)

**Comment by just-a-node** [comment]
`getYieldData` should be fixed, once we release `v0.2.1-rc.12`

**Comment by sanchaymittal** [comment]
replicated #2930, closing it.
