### ISSUE TITLE
As a pool UI user, I want to see the accumulated volume / APY / fees

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#2930]
## Problem
_What problem are we solving and why does it matter, ser?_ 

Show 24H volume per pool.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Show 24H volume per pool

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Shows 24H volume per pool (`getYieldStatsForDay`)

**Comment by sanchaymittal** [comment]
This data need to come from the subgraph -> cartographer. I believe @liu is already working on stable swap subgraph. Let's spec this out once we have that task completed.

**Comment by sanchaymittal** [comment]
#2641 has `getYieldData` implementation done which has been released in latest version. we need to implement this on UI level now. Moving this under, Coinhippo's task.

**Comment by alexwhte** [comment]
@pjenviri @nrsirapop any issues with this one? it is higher priority

**Comment by pjenviri** [comment]
@alexwhte @sanchaymittal, still getting errors on `getYieldData`![error_getYieldData.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/5fbcd100-e53a-4676-9bd5-1e87b2be5c14).

**Comment by alexwhte** [comment]
This impacts Volume and APR

@pjenviri can we please show 'TBD' in UI for volume and fees until we get these metrics completed? 

![image](https://user-images.githubusercontent.com/37959170/214137205-fc8a783e-d617-4fef-8444-aa866012eb54.png)

**Comment by pjenviri** [comment]
updated it to show _TBD_.

**Comment by alexwhte** [comment]
back to connext for `getYieldData` impacting these metrics

**Comment by just-a-node** [comment]
Let's make sure the stats are all converted to the right $ amount. `getYieldData` returns fees, liquidity, and volume in 1e18 precision.

**Comment by liu-zhipeng** [comment]
![image](https://user-images.githubusercontent.com/57480598/216224475-8c43b6c7-d0aa-482d-95a8-0ce16d743a3f.png)

**Comment by liu-zhipeng** [comment]
These amounts are in usd? getYieldData api returns in ETH. I think we have to convert ETH to USD.

**Comment by just-a-node** [comment]
@pjenviri we need a double check on this conversion, the decimals are 1e18 returned from all `getYieldData` stats

**Comment by pjenviri** [comment]
@just-a-node , We display the data returned from `yieldData`. They are already converted. 

![Screenshot_2566-02-03_at_01.34.01.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/e2da99e3-fb83-47f3-9eb5-a7f7f221d0b7)

**Comment by just-a-node** [comment]
Awesome, confirmed with swap volumes from subgraph. TY
