### ISSUE TITLE
Move `calculateAmountReceived` from Pool class into Base class

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#2936]
The Pool class logically encapsulates functionality associated with onchain Pool facet methods on a given chain. Most developers integrating Connext will not interact with these methods directly as they represent single-chain interactions that are outside of the crosschain developer user stories that we are most interested in.

`calculateAmountReceived`, OTOH, calculates a value associated with two pools across chains (as well as network fees). In that respect, it is similar to methods such as `xcall` in the Base class that target crosschain functionality as a whole.

Consider moving the function into the Base class for cleanliness/consistency.

**Comment by sanchaymittal** [comment]
calculateAmountReceived is existing in the pool class because it uses the internal function for the AMM response. we can't move it to base class because of that reason

**Comment by ArjunBhuptani** [comment]
You could just expose the AMM function and move it into the shared class.
