### ISSUE TITLE
SDK API Reference should be more clear about optional params and defaults

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#2937]
For example, the SDK `xcall` documentation references optional params, but gives no information about them:

https://docs.connext.network/developers/reference/SDK/sdk-base#xcall

**Comment by alexwhte** [comment]
Chore: Annotate all types and funcitons to regenerate docs

**Comment by just-a-node** [comment]
We can potentially use https://github.com/SoftwareBrothers/better-docs for autogenerating better docs.
