### ISSUE TITLE
Improve SDK error handling for bad inputs

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#2940]
LiFi was tripped up for some time because of a bad RPC. We can cut down on integration time/cycles quite a bit by having some simple fail-fast param validation on SDK with descriptive error messages.

Things we can do:
- Convert objects to custom types and use ajv to validate schemas
- Validate all address inputs (checksums!)
- Define custom errors and throw them

**Comment by alexwhte** [comment]
We have this handling on transaction service side 

Requires more scoping

**Comment by just-a-node** [comment]
Convert objects to custom types, use ajv to validate.
