### ISSUE TITLE
Clarify fastPath vs slowPath distinction in developer docs

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#2941]
Currently there is 0 documentation on `fastPath` vs `slowPath` interactions in our documentation. This is the number 1 point of confusion we've seen developers have when integrating.

**Comment by just-a-node** [comment]
https://github.com/connext/documentation/pull/86/files

**Comment by alexwhte** [comment]
@ArjunBhuptani adding you for review

**Comment by ArjunBhuptani** [comment]
Oops - this was merged and closed in the docs repo. Closing this issue for now (though we will likely need to keep iterating on this based on feedback!)
