### ISSUE TITLE
Est received is showing small amounts and capping 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2942]
![image](https://user-images.githubusercontent.com/37959170/210847828-a3267824-050c-4c81-8626-21eb1b43a9d0.png)

I was attempting to replicate this user's complaint
https://discord.com/channels/454734546869551114/816982956684869654/1060580128134012958

But the Pools dont look empty

**Comment by pjenviri** [comment]
`calculateAmountReceived`: The `amountReceived` is always `0` when the destination chain is `Binance` and the token is `USDC` ![Screenshot_2566-01-06_at_12.32.08.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/89144e92-2d37-4f83-9f09-24d2fb795032).

**Comment by just-a-node** [comment]
*Current behavior*

ETH -> BNB receiving USDC: always returns 0

ETH -> BNB receiving nextUSDC: decimals are off

**Comment by pjenviri** [comment]
What asset does the decimals in the field: `amountReceived` (returned by `calculateAmountReceived`) belong to? The above image shows decimals = 6 for Binance NextUSDC.

**Comment by ArjunBhuptani** [comment]
Still seeing this issue in UI and it's now being replicated on Binance chain by LiFi team. Should prioritize getting this completed today as it's a blocker for both UI launch and integrations.

**Comment by ArjunBhuptani** [comment]
This may have been fixed here: https://github.com/connext/monorepo/releases/tag/v0.2.1-rc.12

**Comment by alexwhte** [comment]
@just-a-node please make a new release with destination address updates
