### ISSUE TITLE
Stuck transactions 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2944]
https://amarok.connextscan.io/tx/0x2400a43e32b0f3c1ce9ca63ce5e4b4ceaecbe4d5d386be68095db5cb965011ee
[tx] - TX | Connextscan
[[tx] - TX | Connextscan](https://amarok.connextscan.io/tx/0x2400a43e32b0f3c1ce9ca63ce5e4b4ceaecbe4d5d386be68095db5cb965011ee)
Explorer for the Connext protocol
Image
https://arbiscan.io/tx/0x827656a5189b0016bf5a25029239990d12df6afb604b8a94f2bd9ee42755a46e

**Comment by alexwhte** [comment]
1. https://amarok.connextscan.io/tx/0xd8c2ba525c7dddb60c7b690adb6c7b3196e000156ab84f70b8980e783ecfc387
2. https://amarok.connextscan.io/tx/0x5edacf21777235eb4a6da91b543545f544d5360d6eb0704110f92c1c361cd4c9
3. https://amarok.connextscan.io/tx/0x2400a43e32b0f3c1ce9ca63ce5e4b4ceaecbe4d5d386be68095db5cb965011ee

**Comment by jakekidd** [comment]
Blocking fast path currently: https://github.com/connext/monorepo/issues/2955

**Comment by preethamr** [comment]
This is now resolved.
Root cause insufficient funds, and #2955 `txOrigin` graphclient bug and transfers schema optionality.

https://github.com/connext/monorepo/issues/2955 is also fixed.
