### ISSUE TITLE
Add alerting when low on funds for relayer operations

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2952]
## Problem
Twice the past couple days we have run out of Relayer fees and transatctions are getting stuck as a result. It took a lot of debugging work to find this out

## Proposed Solution
Engineering please scope out a solution

My idea is that  the Bot should be updated to PUSH targeted alerts where balances are low

https://discord.com/channels/992549151134982234/1055884765716287540/1060641390587023450

## Acceptence Criteria
TBD depending on solution design

**Comment by rhlsthrm** [comment]
The bot does push alerts when its low, thats what it's meant for.

**Comment by rhlsthrm** [comment]
This seems to not be working, I am working with the bot developer to figure out what is happening.

**Comment by rhlsthrm** [comment]
Bot is fixed!
