### ISSUE TITLE
As a bridge user I can see intermediate messaging status while a transfer is "In Progress"

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#2961]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Users do not have any information into what step in the flow a message is.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] create status at hub subgraph and spoke subgraph to update messaging status: MessageSent, OriginRootSent, OriginRootReceived, HubRootSent, HubRootReceived
- [ ] update the existing message table at Carto to pull messaging status from the subgraphs

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Explorer shows statuses for slow path progress.

**Comment by rhlsthrm** [comment]
Moving this to ToDo, I think this will help a lot with observability for devs and us internally.

**Comment by rhlsthrm** [comment]
Testing against prod mainnet locally. Looking good so far. Missing RootPropagated actions/message status. Will be fixed and ready for review by EoD.

**Comment by rhlsthrm** [comment]
Under review, need help setting up ops side.
