### ISSUE TITLE
Add offchain logging events + SDK for slippage AND relayer fee failures

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2962]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Right now if a transfer fails to execute due to slippage revert it appears to the user as if it's stuck forever.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Add a status to cartographer to display the execute error.
- [ ] Sequencer parses out the revert message from the `estimateGas` call.
- [ ] If revert is due to slippage tolerance failure, update status in carto.
- [ ] Expose status in SDK and UI.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Explorer and bridge UI show error status if slippage exceeds tolerance.

Note: Soon we will add options for user to remedy the situation, but first step is simply showing the status. This is the first part of #2094

**Comment by alexwhte** [comment]
@rhlsthrm @wanglonghong Can/should we scope creep this to include relayer fee issues as well? If not I will open a new issue for this

**Comment by alexwhte** [comment]
bump on this question @wanglonghong !
