### ISSUE TITLE
Pool UI design updates 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2970]
https://amarok.bridge.connext.network/pools

Design changes - please make in staging:
1. Change the heading text to say "Add liquidity to earn rewards."
2. Pull the Pools tab at left of the My Positions tab (switch the order)
3. Update the the correct Manrope fonts laid out in here  https://www.figma.com/file/Z3iq2LOM12K1BeSGQc1Dal/Connext-Concept?node-id=289%3A10614&t=FIw9qWj6EU7gqJQR-0
4. Use the gradients and transparent boxes from here https://www.figma.com/file/Z3iq2LOM12K1BeSGQc1Dal/Connext-Concept?node-id=289%3A10614&t=FIw9qWj6EU7gqJQR-0
5. Round up to whole numbers unless a number is <1 (for example 'Liquidity' column. the 'pooled tokens' column in 'my liquidity' tab, tc)

**Comment by pjenviri** [comment]
@alexwhte, on (3) -- we are currently using the Manrop font. Do you want to change it?
![Screenshot_2566-01-09_at_09.37.58.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/1ed849ae-e65f-4785-a245-0a5f83921f4c)

**Comment by alexwhte** [comment]
nope! they just looked different to me. maybe it was font size or weight

for #4. have we tried some transparency/lower opacity yet? any complexities with this?
