### ISSUE TITLE
NaN for small amount in Pool Wrap ui

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2971]
after i wrapped .000001 it switched from 0 to NaN. 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/37959170/211119187-aa5bc064-d74e-4647-83a3-3ccba495c814.png">

it displayed correct after wrapping .00001 more
<img width="429" alt="image" src="https://user-images.githubusercontent.com/37959170/211119266-e852a116-e1c7-4f5e-91f3-b5fa7093ff2f.png">

**Comment by sanchaymittal** [comment]
fixed!
