### ISSUE TITLE
WETH pool LP token named wrong

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2975]
**Describe the bug**
See transaction from adding to WETH LP: https://polygonscan.com/tx/0x682b5f4a9a3fe3fad259f3ce95f942599e80dbc3d92abd623340b91e54125e6f

This is the token that was received: https://polygonscan.com/token/0x36955fb4ba3618d5a13701f9bb4c2d17436ca189

**To Reproduce**
1. Add pool liquidity for WETH.
2. Look at transaction data on block explorer.
3. See LP token name.

**Additional context**
Gnosis also: https://gnosisscan.io/tx/0xe15a54d430c1ff0859cbcb5e7102fd28f22313d4ad4ded32993a61ea7047c06b

**Comment by wanglonghong** [comment]
LP token name could never be updated. I guess we need to redeploy WETH lp token.

**Comment by rhlsthrm** [comment]
UH oh thats not good. Can we migrate the LP token somehow?

**Comment by liu-zhipeng** [comment]
I think we have to remove all current liquidity and remove swap. after that initialize swap again with correct name

**Comment by rhlsthrm** [comment]
In progress.

**Comment by sanchaymittal** [comment]
completed
