### ISSUE TITLE
As a responsible user, I want the watcher running on prod in order to practice safe bridging.

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#2987]
## Problem
_What problem are we solving and why does it matter, ser?_ 

Need to make sure watcher infra is deployed on production branch / contracts.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Configure ops
- [ ] Fund watcher on each chain
- [ ] Configure watcher to properly watch prod assets

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Watcher successfully deploys pointed at production infra

**Comment by LayneHaber** [comment]
blocked by #2986

**Comment by alexwhte** [comment]
p0
