### ISSUE TITLE
As a router operator, I want to remove liquidity from the UI in order to easily remove liquidity.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#2996]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Routers have no easy way to remove liquidity.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [x] Add SDK function for removing router liquidity.
- [ ] Add to Router Management UI.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] UI has a functioning way to remove liquidity.

**Comment by rhlsthrm** [comment]
There is already an SDK method to removeRouterLiquidity so we just need to add this to the UI.

**Comment by alexwhte** [comment]
@nrsirapop @pjenviri Can you please add this 
https://docs.connext.network/developers/reference/SDK/sdk-router#removerouterliquidity

Im thinking we have two tabs on the 'manage router' pane
Add Liquidity | **Remove Liquidity**

For removing the UI can look the same as adding (select chain, asset, enter amount with balance checking) but call this sdk function for removal

we can make it better in the future if we need

**Comment by pjenviri** [comment]
We added a Remove button. Please help test the functionality. Then we will reiterate to improve the UX/UI 
![Screenshot 2566-01-11 at 23.34.54.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/90c77331-49ba-47bf-8cd5-f29fd0dc052b)

**Comment by alexwhte** [comment]
Can we just steal UX from the AMM pools? Might as well be consistent

When removing we should display the TVL though, not your wallet balance

![image](https://user-images.githubusercontent.com/37959170/211968946-3fc746b3-41f4-4768-bf0e-dfca6e5fecd9.png)

**Comment by LayneHaber** [comment]
agree that it would be best to stay consistent. also, confusing when `balance` of signer is shown and you are trying to remove liquidity from the contract.

with the right permissions removing liquidity does work!

**Comment by sanchaymittal** [comment]
looks like this was completed last week, Already been tested by the new routers.
