### ISSUE TITLE
Invalid BigNumber string for a small slippage tolerance

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3000]
**Describe the bug**

Invalid BigNumber string error when using a custom, small slippage value.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/79353d17-5063-4fb8-8c12-1c551dc6aafc)

**To Reproduce**
1. Go to bridge
2. Input a value to bridge
3. Edit the slippage param to something small like 0.001%
4. Click "send", get error

Have a minimum value allowed for the slippage. The *smallest* possible increment for slippage is 0.01% (1 Basis Point). Technically 0 slippage is also possible for `xcall` but let's set a minimum at 0.01%.

**Comment by alexwhte** [comment]
@nrsirapop The issue looks fixed but im having a lot of issues trying to test entering slippage. Logic in there keeps changing the number for me. I can file another issue if needed but please fix as part of this if you can relatively easily
https://www.awesomescreenshot.com/video/13892110?key=0bf1988c7839129f1190405ee2ffaf7d

**Comment by alexwhte** [comment]
still seeing issues 
https://www.awesomescreenshot.com/video/13918575?key=66dcf1914715b75bd7ea51608ffe5ff3

**Comment by pjenviri** [comment]
> Logic in there keeps changing the number for me.

As Eddie mentioned above, the smallest possible increment for slippage is 0.01% (1 Basis Point). So we intend not to allow users to pass smaller values on the UI.

**Comment by sanchaymittal** [comment]
make sense, closing the above issue.
cc: @alexwhte
