### ISSUE TITLE
Remove Asset not handled in subgraph

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3006]
**Describe the bug**
Subgraph does not handle asset removal.

**To Reproduce**
1. See subgraph entities.
2. Observe removeAsset event is not handled.

**Additional context**

**Comment by alexwhte** [comment]
@rhlsthrm It's unclear what you mean is this for routers or AMMs? Youre seeing this in the UI?

**Comment by rhlsthrm** [comment]
This is for routers. The SDK function to get all supported assets is affected by this.

**Comment by sanchaymittal** [comment]
Started on this, running into issues with different primary keys. 
Asset uses `local_address` as the primary key but AssetRemoved doesn't have a local address in its event.
`AssetRemoved(indexed bytes32,address)`

Not sure about the way we can resolve this.
