### ISSUE TITLE
As a sequencer log viewer, I want to see which router a bid came from

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3018]
## Problem

Sequencer logs don't show which router has sent a bid. Will make it tough to debug version mismatches and other bid issues once more routers are approved.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Sequencer logs router address per bid

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Can see which router a bid came from in sequencer logs

**Comment by rhlsthrm** [comment]
We've removed the version check anyways, but we should add the log anyways.
