### ISSUE TITLE
Removing liquidity crashes the UI

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3023]
See video

https://www.awesomescreenshot.com/video/13920552?key=ea3978aa42c5c573461d540496558ebf

Go to pool, choose Withdraw, enter amount
Crash

![image](https://user-images.githubusercontent.com/37959170/211961355-71471fd8-fa95-4d95-bc57-e166cbaf67fc.png)

**Comment by pjenviri** [comment]
fixed the "symbol is not defined" error.

**Comment by sanchaymittal** [comment]
This is fixed based on the last comment, closing it.
