### ISSUE TITLE
Error transferring from Polygon to Gnosis

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3025]
**Describe the bug**
`[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32000,"message":"header not found"}}}'`

**To Reproduce**
1. Go to https://amarok.bridge.connext.network/USDC-from-polygon-to-gnosis?amount=1.106013
2. Send with these details
3.  See error

![image](https://user-images.githubusercontent.com/37959170/211972580-c83f8b86-d01b-4a2f-8b0a-93292919485f.png)

**Comment by pjenviri** [comment]
It's an RPCs error.

**Comment by pjenviri** [comment]
Updated RPCs.
