### ISSUE TITLE
More UI crashes

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3027]
At first the UI was blank and i was seeing 'network error' in the UI

this was in my console  ((same error i usually see) 
`Access to fetch at 'https://rpc.ankr.com/eth' from origin 'https://amarok.bridge.connext.network' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

AFTER refreshing, i saw this in the UI 

missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0xEE9deC2712cCE65174B561151701Bf54b99C24C8","data":"0xf1537686000000000000000000000000ff970a61a04b1ca14834a43f5de4533ebddb5cc8","accessList":null}, error={"reason":"missing response","code":"SERVER_ERROR","requestBody":"{\"method\":\"eth_call\",\"params\":[{\"to\":\"0xee9dec2712cce65174b561151701bf54b99c24c8\",\"data\":\"0xf1537686000000000000000000000000ff970a61a04b1ca14834a43f5de4533ebddb5cc8\"},\"latest\"],\"id\":43,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","serverError":{},"url":"https://rpc.ankr.com/arbitrum"}, code=CALL_EXCEPTION, version=providers/5.7.2)

![image](https://user-images.githubusercontent.com/37959170/211981442-d727b732-4a4b-4615-88ca-55e7e536ca4a.png)

**Comment by pjenviri** [comment]
It's an RPC error.

**Comment by pjenviri** [comment]
Updated RPCs.

**Comment by sanchaymittal** [comment]
Haven't supported this from past couple of days, closing this issue.
