### ISSUE TITLE
Updates to Liquidity providing UX

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3028]
## Problem
We've seen user confusion with this. Making some updates 
https://www.awesomescreenshot.com/video/13922284?key=4f245dfb6ce5a497c5b450afb721b3e7

## Proposed Solution
1. When price impact is positive, make the value amount text red. 
2. Add a tooltip to 'Price impact' that says "The adjusted amount you are paying for LP tokens above or below current market prices."
3. Update the text in the message popup
> USDC is currently overweighted in this pool. 
> Instead, balancing the pool out with additional nextUSDC may result in **bonus LP tokens**

4. The UX is confusing after you click to Bridge nextUSDC... because we use the same tab and UX as standard Bridge 
it's just different with options disabled, but it's unclear 
Are we sure that doing a popup instead of a new tab will not work? Is there significant engineering lift to test this in staging? Feel free to push back on it still. But Ill need to think move how to revamp this whole flow a bit

5. Whenever we have components that are unselectable, let's try a slightly darker outline 

![image](https://user-images.githubusercontent.com/37959170/211982286-db4f084d-6391-4d9b-8a65-d27e69957977.png)

Using the same consistent design as in the figma designs and #2337 

border: 1px solid #292929
border-radius: 3px;
vs. the Pay with
border: 1px solid #3E3E3E;
border-radius: 3px;

**Comment by pjenviri** [comment]
Done for 1, 2, 3, and 5. Please check them. We'll revisit 4.  

> Are we sure that doing a popup instead of a new tab will not work? Is there significant engineering lift to test this in staging? Feel free to push back on it still. But Ill need to think move how to revamp this whole flow a bit

From the engineering view, changing it to pop-up would take time. We must consider changing several UI handling if doing so, such as the current status tracking, etc. From (my) UX perspective, I think having it as a popup will ruin the overall UX flow.

**Comment by alexwhte** [comment]
for 1 - sorry meant this value 
![image](https://user-images.githubusercontent.com/37959170/212173609-4021324d-9caa-4f1a-94aa-1adfa5b7e8af.png)

for 2 - change "current market prices" to "the current market price."

for 3 - change "Instead, balancing the pool out with additional USDC may result in bonus LP tokens"
to "Providing additional nextUSDC to help balance the pool may result in bonus LP tokens."

New:  
Please remove the Bridge link if the recommendation is providding more USDC like in this screenshot (when amount of nextUSDC being supplied is > amount of USDC), it's less confusing because users know how to get USDC already. 
![image](https://user-images.githubusercontent.com/37959170/212174224-a1ccf936-05a5-49c1-9a17-ff2942839df8.png)

4/5 - Got it thanks. Ill think about it more

**Comment by sanchaymittal** [comment]
Done and Implemented.
