### ISSUE TITLE
Fall back to our own estimate fee calculation and share between sequencer and SDK

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3029]
## Problem
_What problem are we solving and why does it matter, ser?_ 
SDK and sequencer calculate the relayer fee separately. Also in some cases our external API returns 0.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] If the fee returned is 0 (or errors), fall back to using providers to get gas price.
- [ ] Ensure the logic is the exact same between SDK and sequencer.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Above issues are resolved.

**Comment by wanglonghong** [comment]
We were depending on our own price oracle contract but it looks like we don't use it on amarok

**Comment by rhlsthrm** [comment]
Since we only use gas tokens, we can use off the shelf APIs such as CoinGecko for this. Maybe we should have a few that we cycle between.
