### ISSUE TITLE
Sequencer gets Gelato errors when calling get relays endpoint

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3036]
## Problem
_What problem are we solving and why does it matter, ser?_ 
I'm seeing this error showing up randomly in logs: 
```
Error sending axios request to url https://relay.gelato.digital/relays/
```

However the CURL works when I try it. I can presume this call is getting rate limited.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Add retries to the calls. If they fail, wait a second and retry up to 5 times.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Call is retried.

**Comment by rhlsthrm** [comment]
Removed this call.

**Comment by wanglonghong** [comment]
anyway retry feature is done for conversionRate endpoint of gelato

**Comment by rhlsthrm** [comment]
> anyway retry feature is done for conversionRate endpoint of gelato

Yes, let's make a new issue or reuse this one.

**Comment by wanglonghong** [comment]
> > anyway retry feature is done for conversionRate endpoint of gelato
> 
> Yes, let's make a new issue or reuse this one.

already pushed the changes after load testing.
