### ISSUE TITLE
[LOW] UI Issue: Clicking MAX On Pool w/ No Tokens Engages Supply Button & Subsequent Error (USER REPORT)

### ISSUE THREAD

**Issue by Grraarrgghh** [connext/monorepo#3041]
**Describe the bug**
User reports in https://discord.com/channels/454734546869551114/1060692139245309983/1063067777767845918 that if you go to supply liq and click "Max", it will engage the Supply Button (and then error out if you click that), even if the user holds none of the token they attempt to supply.

**To Reproduce**
1. Go to Pools
2. Select a pool
3. Click "Max" on a token to supply liq for a token you have 0 of
4. Click "Supply"

**Comment by alexwhte** [comment]
mm i wasnt able to replicate this actually . @Grraarrgghh can you?

**Comment by Grraarrgghh** [comment]
Nope, @alexwhte , not occurring for me either. I'll ask the user if it still occurs/can they replicate it

**Comment by sanchaymittal** [comment]
Not happening for me as well, let's reopen if required.
