### ISSUE TITLE
[LOW] UI Issue: Send Button Remains Active After Send To BNB From [x] Txns (USER REPORT)

### ISSUE THREAD

**Issue by Grraarrgghh** [connext/monorepo#3042]
**Describe the bug**
When bridging to BNB from other networks (example provided is Polygon to BNB), the "Send" button remains Active/Blue even while the transfer is in progress, and the page has to either be reloaded or the network switched for the txn's "Executed" status to be visible and the Send button to become inactive.

Noted in ticket here: https://discord.com/channels/454734546869551114/1062443488303657110/1062443593614241822

**To Reproduce**
1. Go to Bridge
2. Send funds from Polygon (or other) to BNB

**Comment by pjenviri** [comment]
Unfortunately, I could not reproduce the issue.
