### ISSUE TITLE
Pool UI not loading balances or some other data

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3047]
Not loading my wallet balances
Also  loading these two metrics 
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/cb8e9c66-7bb0-423c-a54f-63cbb592a080)

My terminal is pretty angry. More of these RPC Ankr messages 
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/a05ba41a-15d2-46d7-8d76-eaee8850ffbe)

Also 
_app-cf4ba0b05ee7ef82.js:1 Uncaught (in promise) Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174","data":"0x70a082310000000000000000000000003a40064c2b0004ab594f44c24d29df1943108c73","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at y.makeError (_app-cf4ba0b05ee7ef82.js:1:2396737)
    at y.throwError (_app-cf4ba0b05ee7ef82.js:1:2396857)
    at _app-cf4ba0b05ee7ef82.js:1:2445434
    at Array.forEach (<anonymous>)
    at k.<anonymous> (_app-cf4ba0b05ee7ef82.js:1:2445249)
    at Generator.next (<anonymous>)
    at s (_app-cf4ba0b05ee7ef82.js:1:2437716)

**Comment by alexwhte** [comment]
update: it just fixed itself after refreshing a few times...

i had replicated this for polygon and gnosis before, not for BNB Chain

**Comment by pjenviri** [comment]
Updated RPCs.
