### ISSUE TITLE
Propagate task errors insufficient balance

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3051]
**Describe the bug**
Propagate task errors insufficient balance

**To Reproduce**
Lighthouse propagate task seeing this error:
https://dashboard.tenderly.co/Preetham/project/simulator/7ad8f7de-7261-4733-9e63-6da2ad78840b

https://app.datadoghq.com/logs?query=region%3Aus-east-2%20service%3Alighthouse-propagate&cols=host%2Cservice%2C%40taskId%2C%40requestContext.transferId&event=AQAAAYWoysIUbbi9BwAAAABBWVdveXNLNUFBQ3JMdlloWi1uaFpBQVg&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1673487911507&to_ts=1673574311507&live=true

**Additional context**
https://etherscan.io/address/0x935AaAe0f5b02007c08512F0629a9d37Af2E1A47

Sufficiently funded

**Comment by wanglonghong** [comment]
@preethamr  you just funded to the relayer address. the error is happening cause the [RelayerProxyHub](https://etherscan.io/address/0x75C6A865c30da54e365Cb5Def728890B3DD8BDC4) is out of funds

**Comment by rhlsthrm** [comment]
Yep this is a funding issue. Funded and closing.
