### ISSUE TITLE
Cannot bridge in testnet due to relayer fee error 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3057]
https://testnet.bridge.connext.network/TEST-from-goerli-to-polygon?amount=1

Cannot estimate the relayer fee at the moment. Please try again later.

![image](https://user-images.githubusercontent.com/37959170/212380057-0a6fda72-2fc8-495e-94f3-e1aab082fbce.png)

**Comment by pjenviri** [comment]
This was updated following https://github.com/connext/monorepo/issues/3009 and [this post on Discord](https://discord.com/channels/454734546869551114/909827059373723648/1062784320412061786).

**Comment by sanchaymittal** [comment]
closing it! after going through last comment.
