### ISSUE TITLE
Transfers stuck with 0 relayer fee

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3059]
Several user transfers are stuck, presumably due to 0 relayer fee

https://amarok.connextscan.io/tx/0xb251cd000718144573ee11c0ea92fb86917b146ae32b69e7c59dca7234121c95\

This one looks to have fixed 

https://amarok.connextscan.io/tx/0xac04d6a3f80f2fb52ee05d84153eb61ca78da3511197be45ee9fdc846a7be5e8

**Comment by alexwhte** [comment]
https://amarok.connextscan.io/tx/0xb773ed9226192cdcada9fdae9d2a85f52a37e5c66ca012e47b96cddc3f801843
https://amarok.connextscan.io/tx/0xe1a1b9c34c83b182761cf9edd7fc4b6e7798100bab19d8a533bb717b954578a7?_gl=1*39or6c*_ga*MTk5NTU0ODYxNS4xNjczNDU5MjUz*_ga_MPYZEDRVQ0*MTY3MzQ1OTI1Mi4xLjEuMTY3MzQ1OTM0MC4wLjAuMA
0x51b11230a9c3483a97f25662c1d1a609a861028ac4e41296b63dfd801d591af6
0x121AfA099A9F01bB0f434D147907b011e4Ee8d33
https://amarok.connextscan.io/tx/0x7f9b3bb374b39f19cfdc36423628536775f1a1631f71ec3c64ffec25e1e1017a?_gl=1*1o6ued7*_ga*ODI0MDExMTM5LjE2NzM1MjQzOTM.*_ga_MPYZEDRVQ0*MTY3MzUyNDM5My4xLjEuMTY3MzUyNTQ2My4wLjAuMA
https://amarok.connextscan.io/tx/0x95958988ea534cb35415c12cf8f7b67d2e3b63414b9e38b6cb88de669fe0b379
https://amarok.connextscan.io/tx/0xac04d6a3f80f2fb52ee05d84153eb61ca78da3511197be45ee9fdc846a7be5e8
Amarok scan : 0xbe1192c5c899b69939926916c0b8cb30b9e1dd1374a31a0fcb5e9d050bfa6333
Windows11 Chrome Metamask

**Comment by just-a-node** [comment]
Need to bump relayerFee for:

0x55f215785968a515de37cc681623a50abac59b2eeffebc3852646fbb7631340e
0x0ef3a90a63658b7a7b7c87581109efac28ceb828218cfc8b8de363f5c70efea1
0xb251cd000718144573ee11c0ea92fb86917b146ae32b69e7c59dca7234121c95
0xc15802c3ec8bd1fd40c4976c588ec063a3fd3e6e066cf4f261580f134d0482fd
0x5ef9098e7ce24105f3045edccf64856a283efbba6c7b18b19129b9d1272067ea
0xe44bddf77e0623b4e9a0027efececc3a6977c72df2e59eebb8ff54845c4e19db
0x6c0ce5b0460052365f25a285ee618ac262c730839b495acfec72cd2645e54066
0x75b5085e09e177a7517579b8474832e6a0283514152f6800b07cea182fcdab8f
0xb013baa22f8a842bb2de77ac6308361027a0975903581d20b3dd65e1b68f8b67
0xc3267ada8548115a5be8e4919248130a42c4a42c997fab45b1306aba2ac9f903
0xf4a0e30ec08d6cef1c44145fa77561d8dcfe22bfdf48c08c19fc4039380e7a5f
0x1ddaae570cef76c7b9a0b2b61cc2c0c35eb9866c69e5c789eb688db104c38728
0x9570553be6d2c0338e41b4a672db3a4620bd8632edb737c682a1ef84aae2b24b
0xe58a7768402a793b1d564ea2ca4afa9f88cc507ba54760dbedaf1eb9695532af
0xc19c9393e824a67670e78915f0698da33295833d5d713e8326462fffb28107cb
0x728fc76e20c2b940a3db5c25a941f63379fa7b8591eb134d9e5f48954fe3663c
0xdb2d761fdd02a2cbd4eab3b0e7300628a040ab5efaab9314f981496f81f6e4bd
0xb83c5e767391aac224570029072e07dab44a00b3ffc1480d55d85761803b1cde
0xa83843b1c44ffd690678c210aba3a1b22438ce497815298e3b5d02eb812060fe
0xb3bc1e4f940068a3f153667da0cd36158052caefb1aa1479bc3240ce18f0322b

**Comment by just-a-node** [comment]
Bumped all these transfers. Will wait and see if they get retried successfully

**Comment by sanchaymittal** [comment]
Was this resolved? @just-a-node

**Comment by just-a-node** [comment]
Closing this out. New stuck transfers with >0 relayerFee tracking in #3073

**Comment by sanchaymittal** [comment]
among above only one tx is left
https://amarok.connextscan.io/tx/0xb773ed9226192cdcada9fdae9d2a85f52a37e5c66ca012e47b96cddc3f801843
