### ISSUE TITLE
AddRouterLiquidity error

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3060]
**Describe the bug**

AddLiquidity errors:
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/a24cfb89-49db-4496-b424-7abd99317d23)

**To Reproduce**
1. Go to routers page
2. Manage router
3. Add liquidity

**Additional context**

**Comment by alexwhte** [comment]
Replicated for BWare router, but adding to our router works fine for me

**Comment by sanchaymittal** [comment]
It's an RPC issue, changing it should fix it. Going to close it, if required please open it again.
