### ISSUE TITLE
Sequencer-publisher is running out of memory 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3064]
**Describe the bug**
Sequencer-publisher is running out of memory in mainnet and prod testnet.

**To Reproduce**
Look for these logs:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1195648/212568695-b1b00e50-8438-4985-ad63-00d06c9d5657.png">
 

**Additional context**
Perhaps cache/data handling of transfer data, especially when posted repeated by `router-executor` on slowpath retries.

**Comment by preethamr** [comment]
Got the instrumentation on going for profiling sequencer:
Just before crash:
<img width="1758" alt="image" src="https://user-images.githubusercontent.com/1195648/213837547-30de8fc2-4fbd-4dbd-b1bc-5ec50e29afbc.png">

Just after startup:
<img width="1772" alt="image" src="https://user-images.githubusercontent.com/1195648/213837839-bd22253a-2584-4194-a1a4-aac01eab3f4e.png">

**Comment by preethamr** [comment]
Reopening, afaik fix for #3129 does not resolve this issue, will continue to monitor the env.

**Comment by alexwhte** [comment]
@preethamr keep #3182 in mind

**Comment by preethamr** [comment]
Removing `dd-trace` has helped.
Performed load test again after the fix and have not observed previous symptoms.

<img width="2268" alt="image" src="https://user-images.githubusercontent.com/1195648/214239139-e751027f-9b6a-44dd-a1ef-ba3b922ee74a.png">

**Comment by preethamr** [comment]
Will monitor prod once CI deploys the fix. And close if looks good.

**Comment by preethamr** [comment]
<img width="2137" alt="image" src="https://user-images.githubusercontent.com/1195648/214475790-7e226237-d4c0-4956-b3fa-0fa24b903157.png">

Confirmed fix is working in prod
