### ISSUE TITLE
Popup Explorer transaction link might become invalid

### ISSUE THREAD

**Issue by antonr-p2p** [connext/monorepo#3071]
**Describe the bug**
When we do some actions pop up panel with  Explorer transaction link occurs. It contains URL to some Explorer and transaction ID. It might become invalid in some cases.

**To Reproduce**
1. Open Routers page, find your router and click Manage router
2. Add some funds on a network A
3. You should get popup panel in top with link to blockchain Explorer
4. Change network to B - the link above is changed and becomes invalid cause Explorer address is changed inside of link URL

**Comment by alexwhte** [comment]
Thanks for filing @antonr-p2p  

Note to self 
![image](https://user-images.githubusercontent.com/37959170/212785156-8706d0d9-0f71-431c-ad08-1424237f5354.png)

**Comment by alexwhte** [comment]
@antonr-p2p can you explain step 4 more actually? I dont fully understand yet 

Change network to B - the link above is changed and becomes invalid cause Explorer address is changed inside of link URL

**Comment by antonr-p2p** [comment]
@alexwhte look at the screenshot above - in the window in front of you here is a line "Add Remove       on Arbitrum-One". If you change Arbitrum-One to any other network - "Arbiscan" in the top panel link would change to e.g. "Etherscan" (if you change to Ethereum). BUT, it should not happen for already generated link - cause if you change Explorer but leave the same ID of transaction - you would have broken link (e.g. you try to find Arbitrum transaction on Ethereum Explorer)

**Comment by just-a-node** [comment]
Still seeing the same behavior that Anton described above.

What I did:
- Add router liquidity on Polygon, this banner shows up:
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/942b118d-9e8b-4e03-b09b-880629bf7244)
- Switched networks here to any other network:
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/df862b20-cf7e-4745-a509-e9e77e60209d)
- Banner now gets updated with a link to the *same* transaction hash but on the new network's scanner site, which is invalid:
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/53ea23d5-5e1e-4179-8090-69a20078b413)
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/67fb8834-a1e4-4642-93e6-dee1d36f3006)
