### ISSUE TITLE
Stuck transfers (non-zero relayerFee)

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3073]
Stuck transfers on mainnet with >0 relayerFee/

Reconciled, not received:
- https://amarok.connextscan.io/tx/0x3bda6a0bb16cae4663dcdb7dd502f37fb1cab1655f72deb2a03cbbdb776583f1
- https://amarok.connextscan.io/tx/0x8313dea81814b9b9c70fd8773d7f93d3070e4d9b9e362a7c05190b9afc9e989e
- https://amarok.connextscan.io/tx/0x7f9b3bb374b39f19cfdc36423628536775f1a1631f71ec3c64ffec25e1e1017a
- https://amarok.connextscan.io/tx/0x378dd18bded3b3192bf7cf3833053ef15e30b1223872127c5c3f79f258d8526a
- https://amarok.connextscan.io/tx/0x924888b0b279bb3a445b15d94d14f76e94d7794bc6ce98b1642a9acef63065f2
- https://amarok.connextscan.io/tx/0xb773ed9226192cdcada9fdae9d2a85f52a37e5c66ca012e47b96cddc3f801843
- https://amarok.connextscan.io/tx/0xdc50b4ab8815dcbfffa988d511e3d9fa28844436bbc1610b2552610e16a75761
- https://amarok.connextscan.io/tx/0x67cc81c62603bf7c7c38d52a2e39a15e0bdb7ee81c1f36e36577b411f93f75ba

XCalled:
- https://amarok.connextscan.io/tx/0x7bd8dcff6d9087ec96fe774cefc9f01b97ca24e2d95e2722410d9f72f264d9c2
- https://amarok.connextscan.io/tx/0x0a2ee95579503ae4f9654b71fb28e26decd970921f1d9a09a3990a5ac7dc9ebd (and a BUNCH more of this same path: Polygon -> Optimism)
- https://amarok.connextscan.io/tx/0x6dea00e0a5f6f0c20e0bb6a9edebec6cf6b3400fe5d1f8debbf7f81941524487
- https://amarok.connextscan.io/tx/0xfaf04267fc95027b08882bbf62d4dc6f9ecf8d834a0a2fbeeeff147684ca5e9b
- https://amarok.connextscan.io/tx/0xb71d56f3adbd35d98e35ca4fc1bd5ca1b3fa4594e8ff2b77d132e1668a34760c

**Comment by alexwhte** [comment]
Note the reasons for stuck transfer are 
https://github.com/connext/monorepo/issues/3044
https://github.com/connext/monorepo/issues/3029
