### ISSUE TITLE
LH processFromRoot task logs incorrect transfer_id

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3076]
**Describe the bug**
LH processFromRoot task logs incorrect transfer_id, it logs `sent_transaction_hash` as transferId.

**To Reproduce**
Find logs like these:
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/1195648/212761750-12d3e72c-c575-4596-897c-fbd47b598d75.png">

**Comment by preethamr** [comment]
This data is not readily available in the context, and would need to fetched.

**Comment by LayneHaber** [comment]
not available in context, likely out of scope. closing
