### ISSUE TITLE
Add ability to see liquidity balance in Pools tab

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3077]
## Problem
We need a way to view pool imbalances at a glance. This will help us rebalance and monitor

## Solution
Using the same liquidity pair data that's in the individual pool UI 
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/6e42909b-68f8-44f8-95ad-db72cd18bcc9)

Add a column in the Pools overview to display this data. But ideally display it like a small progress bar, for example where below is USDC---nextUSDC

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/f02d04c3-bf98-4bae-a6d3-3d6ad740ce02)

This can go to the left of the existing Liquidity column
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/5bd1847b-fb08-459c-830d-0248f32b6fd2)

**Comment by pjenviri** [comment]
![Screenshot 2566-01-18 at 12.48.54.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/93a18905-b97a-4ca5-b859-1b7c9b324295)

**Comment by alexwhte** [comment]
This is awesome @pjenviri :)

To clean it up a bit can we remove the USDC and nextUSDC tokens underneath each bar?

We could have it where hovering over one side of the bar displays the asset

**Comment by alexwhte** [comment]
Looks better! Can we make the rows the original height? it is still stretched from this change
