### ISSUE TITLE
UI tweaks - collected feeedback

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3081]
I'm pulling out these from a longer list of user feedback https://github.com/connext/monorepo/issues/2321 

1
Too many timers are confusing, remove the one in the 'Latest transfers' pane
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/fe22c04d-6ac4-4f3e-baaf-b9f9918ecc0d)

Remove this one for now as it adds to user anxiety. User can look at timer in Explorer if needed
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/4d65af27-8158-43ed-b69a-2efd6e890f52)

2
Change to say "target recipient address" 
![image](https://user-images.githubusercontent.com/37959170/212778821-d972ac16-b081-4035-a2ab-60049ea5d4b0.png)

**Comment by pjenviri** [comment]
Done.
