### ISSUE TITLE
Bridge font consistency (design update)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3084]
The main callout is mixing 16pt and 18pt. 
Please try 16pt and 12pt fonts from the Figma design **in staging**? 
Let me know if you started with those sizes then updated to 18pt and 14pt on purpose though!

![image](https://user-images.githubusercontent.com/37959170/212783389-04667147-5149-4925-9295-d218fbba1690.png)

Remove the upper case in here and add a bit more spacing
![image](https://user-images.githubusercontent.com/37959170/212783707-a51f8620-fb02-4dd9-bdfa-494056ca4ee1.png)

upper case title 
![image](https://user-images.githubusercontent.com/37959170/212791976-b40943bb-936f-477a-b767-46c2a7c41d4f.png)

**Comment by alexwhte** [comment]
yeah thats fine

**Comment by alexwhte** [comment]
Let's revert @pjenviri , thanks for testing it for me. 

Let's just make these 18 for consistency 
![image](https://user-images.githubusercontent.com/37959170/213054217-e8875c7b-41fa-4a70-9f0c-688344af49a7.png)

**Comment by pjenviri** [comment]
Okay, updated.
