### ISSUE TITLE
Manage Router UX updates 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3085]
**Describe the bug**
It was hard for me to know here what was wrong https://amarok.connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c

![image](https://user-images.githubusercontent.com/37959170/212785476-59b27c4c-0067-4d25-80a5-5ee7b43c73c0.png)

Solution
1. Show the 'Add' button always, but disable or grey it out if user cannot select yet. 
2. When disabled, add text that says "Switch network" next to or inside the 'Add' button (whatever you think works better)

**Comment by alexwhte** [comment]
Looks great, please update tooltip to 

"Please switch to correct network."

**Comment by pjenviri** [comment]
Updated the tooltip message.![Screenshot 2566-01-18 at 12.45.22.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/2d96903c-26bf-4c9e-868c-b953e9537041)
