### ISSUE TITLE
Meta description of single pages of the amarok bridge

### ISSUE THREAD

**Issue by massimol** [connext/monorepo#3095]
Restore the meta description that existed before so that the text can appear when pasting a link and on search engines.

Ex: https://amarok.bridge.connext.network/USDC-from-gnosis-to-binance

Bridge USDC from Gnosis chain to Binance Smart Chain (BNB) with Connext, the most secure crosschain protocol

**Comment by alexwhte** [comment]
@coinhippo can you please update descriptoins for consistency across our UI pages? 
![image](https://user-images.githubusercontent.com/37959170/212976424-d275978b-553a-42f8-a406-c12f8cc2b788.png)

@massimol We should do this across others too. Can you please draft for Pool and Swap

Pool is wrong
![image](https://user-images.githubusercontent.com/37959170/212976641-e26569ae-4263-40a9-a98e-385834fd5008.png)

Explorer if needed? 
![image](https://user-images.githubusercontent.com/37959170/212977024-fae1cdbc-b9e3-4edb-a127-41234262c569.png)

**Comment by alexwhte** [comment]
@massimol assigned to you to test and make any further updates
