### ISSUE TITLE
Make sure the relayer fee calculated on the origin is greater than real tx cost on the destination.

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3097]
## Background

We might need to compare the calculated fee on the origin to real tx cost paid on the destination and correlate a couple of things like update hardcoded gasLimits, bump gasPriceFactor, etc.

**Comment by alexwhte** [comment]
@wanglonghong is this a duplicate of https://github.com/connext/monorepo/issues/3030 ?
Please close and comment/update the original if so?

**Comment by wanglonghong** [comment]
> @wanglonghong is this a duplicate of (or part of) #3030 ? Please close and comment/update the original if so?

I think yes.
