### ISSUE TITLE
[SDK] Default network configuration

### ISSUE THREAD

**Issue by brozorec** [connext/monorepo#3098]
**Describe the bug**
The docs state that the default network is "mainnet". However, when initiating the SDK and omitting the network, it actually defaults to "testnet".

![image](https://user-images.githubusercontent.com/9572072/212937046-c4e4b02e-2554-40da-aed3-b8119f4a581a.png)

**To Reproduce**
```
 const nxtpConfig = {
    chains: {
      [polygon]: {
        providers: [RPC_POLYGON],
      },
      [optimism]: {
        providers: [RPC_OPTIMISM],
      },
      [ethereum]: {
        providers: [RPC_MAINNET],
      },
    },
  };
  const { nxtpSdkPool } = await create(nxtpConfig);
  const d = await nxtpSdkPool.getAssetsData();
  console.log(d);
```

The above logs assets with domains 1735353714 and 9991 which are testnets.

Using `"@connext/nxtp-sdk": "^0.2.1-rc.13"`

**Comment by just-a-node** [comment]
Thanks! Docs updated to reflect the current version.
