### ISSUE TITLE
[nxtp-v1] Ethereum to Polygon (WETH) failing

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3104]
Coinhippo flagged this earlier and I missed it. 
https://discord.com/channels/454734546869551114/909827059373723648/1064938744106471536

Can anyone replicate?

https://bridge.connext.network/ETH-from-ethereum-to-polygon?amount=0.001

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/ecdcf121-4b33-4c7d-9bb6-aff637824240)

Error says 'No subgraphs available on this chain; unable to handle request.', conte

**Comment by rhlsthrm** [comment]
Arbitrum Nova subgraph seems fine, I'm seeing response on curl showing it's synced:
```
curl 'https://subgraph-ts-worker.connext.workers.dev/subgraph_health/?chainId=42170'
[{"data":{"network":"arbitrum-nova","chainHeadBlock":1843678,"latestBlock":{"number":"1843678"},"lastHealthyBlock":null,"syncedBlock":1843678},"url":"https://connext.bwarelabs.com/subgraphs/name/connext/nxtp-arbitrum-nova-v1-runtime"}]%
```
