### ISSUE TITLE
Gnosis L2 to L1 not processing

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3107]
**Describe the bug**
Seeing a processFromRoot message from Gnosis chain not processing. 

**To Reproduce**
1. Check database. 

**Additional context**

**Comment by rhlsthrm** [comment]
@wanglonghong has contacted Gnosis team about this issue, waiting to hear back from them for updates.

**Comment by wanglonghong** [comment]
Received their response and double checked! So root cause is that one of their validators is down. We should need to wait until it gets back.

**Comment by ArjunBhuptani** [comment]
Fixed! Closing
