### ISSUE TITLE
As an explorer user, I want to see error status in order to know why my transfer failed

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3108]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Transfer failures are unclear.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] SDK will fetch new field for `errorStatus` from transfers.
- [ ] This should be displayed in the explorer when a transfer is not getting executed.
- [ ] Also can be displayed in the bridge UI if a polled transfer returns this status.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Explorer and bridge UI display error status.

**Comment by pjenviri** [comment]
Could you share some URLs of the error transfers?

**Comment by rhlsthrm** [comment]
Here's one: 

```
curl --request GET \
  --url 'https://postgrest.testnet.connext.ninja/transfers?transfer_id=eq.0x0151a21d8c1c1718249b1e30f0210807591bec5ce8856a1455e69830146407ac' 
```

**Comment by alexwhte** [comment]
please also see #2044 (blocked) and #3115 related to this UX
