### ISSUE TITLE
Need to figure out exactly why we have failed txs on GnosisHubConnector

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3110]
**Describe the bug**

We have several failed txs on GnosisHubConnector which costed about $20. 
The reason why it happened is because the root has been processed already. 
IMO, it estimates gas before submitting a tx through the relayer. Gas estimation doesn't work properly???
We might need to dig into this so we will not lose tx fee for failed txs.

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5b67a142386aa6742a90bc34/3358911c-058f-4210-b947-b52ad4cf7ac2)

**Comment by alexwhte** [comment]
this was the closed thread https://discord.com/channels/992549151134982234/1065341508330459246

**Comment by jakekidd** [comment]
gnosis hub connector with failed txs: https://etherscan.io/address/0x245F757d660C3ec65416168690431076d58d6413

**Comment by jakekidd** [comment]
looks like it's already relayed message hash:
![image](https://user-images.githubusercontent.com/37907740/213574346-43bd51f3-b1cc-42c1-bf75-12dfe8230433.png)


tenderly link: https://dashboard.tenderly.co/tx/mainnet/0x04f413043890022a59f6e1df04a852c0cdeded169e3a2a34135bf3399893635c/debugger?trace=0.0.1.2.3

**Comment by rhlsthrm** [comment]
Going to close this for now, this was likely due to the issue Gnosis reported with their AMB.
