### ISSUE TITLE
Review all docs links, prune unused

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3112]
## Background

Generated report of broken links: https://docs.google.com/spreadsheets/d/1GpaMQ-Ch-IVVo_SLpmGYalPFABSzr9SIdnuqQ0sUr_0

Most of these are pointing to legacy docs. Deprecate those and fix all others.

**Comment by alexwhte** [comment]
@just-a-node you are likely talking to Matt already but in case not he is also looking at cleaning up bad links for SEO

**Comment by just-a-node** [comment]
And remove v1 docs after this coming Thursday when v1 will be sunsetted.
