### ISSUE TITLE
New driver animation for bridge transfers

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3115]
We worked with a designer on bridge transfer animation. This vaporwave design should be more fun and unique for users.
[V2 Animation without Network Logo.zip](https://github.com/connext/monorepo/files/10453668/V2.Animation.without.Network.Logo.zip)

Update: Use this below for just the START animation (fixes a misspelling)
[Start.gif (1).zip](https://github.com/connext/monorepo/files/10464190/Start.gif.1.zip)
![Start 2](https://user-images.githubusercontent.com/37959170/213643429-0eda582f-b0ab-4792-b19b-291a1a88851f.gif)

**Spec**
There are 5 states in the animation
1. Start --> Transfer has started
2. Error-Gas --> Relayer fee error (see https://github.com/connext/monorepo/issues/3011) 
3. Error-Slippage --> Slippage tolerance exceeded (see https://github.com/connext/monorepo/issues/2094)
4. Error-Generic --> Any other error 
5. Success-End --> Transfer has completed

This should replace existing animation in here. We do not need to say "Sending 1 USDC" as this is in Latest Transfers, but the other text below that can stay the same for now
![image](https://user-images.githubusercontent.com/37959170/213359414-6c56a46e-dc38-463b-8a20-008e56458172.png)

We do not need "Funds Received" text for Completed, as it says something in the animation 
![image](https://user-images.githubusercontent.com/37959170/213364555-4fb9784a-cb0a-44b2-8c2b-b1ef1af8da32.png)
![image](https://user-images.githubusercontent.com/37959170/213364638-74242481-d3a8-4592-8fc0-418d868fedb5.png)

**Comment by alexwhte** [comment]
Note we will have different versions for each destination chain, in case this impacts the way we code/implement 

![image](https://user-images.githubusercontent.com/37959170/213359905-7cf447b9-7201-4f0b-91c9-3f0a426351e3.png)

**Comment by pjenviri** [comment]
added.

**Comment by alexwhte** [comment]
@pjenviri thanks after it starts `Start.gif` completes and can you switch to `Processing.gif`?
It should continue at this state until it completes or has an error

**Comment by alexwhte** [comment]
per comment from @rhlsthrm maybe try it 30-50% larger as well 
![image](https://user-images.githubusercontent.com/37959170/215635991-5020867b-9ae0-41f3-bc04-e5773090569f.png)

**Comment by alexwhte** [comment]
@pjenviri so it actually replays the Start.gif and End.gif over and over right now...

Can we change it so that:

It only plays Start.gif ONCE
THEN Processing.gif on repeat
THEN, when complete, it only plays  End.gif ONCE
THEN it stays on this Image
![Success-End](https://user-images.githubusercontent.com/37959170/215910503-dfd8ca59-1fd0-4e22-a22f-6506af6ea4c2.jpg)

For the other 3 Errors, do the same as End.gif. And also play them ONCE and then switch to be paused on their final image 
![Error-Generic](https://user-images.githubusercontent.com/37959170/215910819-57f8b46e-e6bb-4de9-85fa-be4657cd7168.jpg)
![Error-Slippage](https://user-images.githubusercontent.com/37959170/215910823-2a9c035d-de51-4981-b3dc-1825042d9444.jpg)
![Error-Gas](https://user-images.githubusercontent.com/37959170/215910826-70352745-1c56-4a39-9db0-ee9b65330dff.jpg)

When slippage or relayer fee are bumped, switch to Processing.gif and back to before

**Comment by alexwhte** [comment]
This looks great. Last minor change. At this completed state add text below the image that says:

> Transfer completed.

![image](https://user-images.githubusercontent.com/37959170/216224529-45ae1ad3-c677-46a4-89fb-ddee3131f8c0.png)

Then we can just close it :)
