### ISSUE TITLE
explorer getTransferByUser isn't working for testnet

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3125]
**Describe the bug**

**To Reproduce**
2. 
3. 
<img width="1728" alt="Screenshot 2023-01-19 at 4 39 49 PM" src="https://user-images.githubusercontent.com/31698676/213427411-dddaa8f2-6111-4e04-8383-c1b1598f3001.png">
https://testnet.amarok.connextscan.io/address/0xfaa336d2aefdb7fc55ef4e3b14547d407223392f

And this address already has some transfers, ex:
https://testnet.amarok.connextscan.io/tx/0xd9851bf61eaf01e03facaf85042a5d2cc1d5887e3781855fe5b1cc3f54bdd76f

**Additional context**

**Comment by alexwhte** [comment]
@sanchaymittal This seems fixed i think?

**Comment by wei3erHase** [comment]
i believe the same error happens in mainnet?
https://amarok.connextscan.io/address/0xd4dfee43d46a66471a988f3785106ea87c8f9f25

xcalled for example in:
https://etherscan.io/tx/0x1e95c54134910cb44b6f59b77547d25662f4398deea22ea0774e360322680efd/advanced
