### ISSUE TITLE
[MED] High Relayer Fees For Small Txn - MATIC>BNB (User Reported)

### ISSUE THREAD

**Issue by Grraarrgghh** [connext/monorepo#3128]
**Describe the bug**
User bridged .1 USDC from Polygon to BNB and was charged 7.5 MATIC as a relayer fee:

https://amarok.connextscan.io/tx/0x507ef3ce94178ff794980af30ad40fc585df583447dbcae1c80d000fc04b131f

https://discord.com/channels/454734546869551114/1065625896578457630

**Comment by rhlsthrm** [comment]
I believe we fixed this. @Grraarrgghh please reopen if comes up again.
