### ISSUE TITLE
LH process from root for arbitrum throws

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3138]
**Describe the bug**
LH errors `Cannot read properties of undefined (reading 'bind')` for arbitrum

**To Reproduce**
1. Find these logs in DD
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/1195648/213585358-40c2d1a4-f8c3-497f-8591-f3fee0b17e97.png">

**Comment by alexwhte** [comment]
current impact
 origin_domain | count
---------------+-------
 1634886255    |    23
 1869640809    |    26

**Comment by preethamr** [comment]
Fails here:
https://github.com/connext/monorepo/blob/a1e10be0ede3cf4476e7d158998d3f036bf55806/packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts#L82-L91

**Comment by preethamr** [comment]
Throws here:
https://github.com/connext/monorepo/blob/a1e10be0ede3cf4476e7d158998d3f036bf55806/packages/agents/lighthouse/src/tasks/processFromRoot/helpers/arbitrum.ts#L101

**Comment by rhlsthrm** [comment]
Sent message to Arbitrum team, awaiting more info from them.

**Comment by rhlsthrm** [comment]
I am able to run the HH task directly for transfers that show this error on lighthouse. The HH task WORKS, indicating some difference in operation. However inspecting the code yields no differences in the implementation.

**Comment by sanchaymittal** [comment]
fixed
