### ISSUE TITLE
LH processFromRoot errors on 503 for OPT

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3140]
**Describe the bug**
LH processFromRoot errors on 503 for optimism RPC calls

**To Reproduce**
1. DD Logs:
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/1195648/213586545-7ee6185d-2423-4684-a6a8-4efbf6c7e173.png">

**Comment by alexwhte** [comment]
49 stuck transfers

**Comment by rhlsthrm** [comment]
Sent message to Alchemy team, waiting for response.

**Comment by sanchaymittal** [comment]
fixed

**Comment by just-a-node** [comment]
The public endpoint we switched to earlier (`https://endpoints.omniatech.io/v1/op/mainnet/public`) has the same issue as Alchemy's.

Infura works fine, so switching to that in https://github.com/connext/monorepo/pull/3166
