### ISSUE TITLE
ETH Pool liquidity is wrong

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3149]
See below 
![image](https://user-images.githubusercontent.com/37959170/213639092-7392b897-c3ce-463a-a438-ca46ef486558.png)

![image](https://user-images.githubusercontent.com/37959170/213639141-3dfa30ed-3324-43e3-8abc-c0e30e14e17a.png)

**Comment by sanchaymittal** [comment]
@alexwhte what's wrong here?

**Comment by alexwhte** [comment]
lol it's too late. i was reading in USDC like TVL
