### ISSUE TITLE
High Relayer Fee from * to Ethereum

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3160]
**Describe the bug**

high estimate relayer fee from any network to Ethereum, around 100 USD has been spotted multiple times.

https://cdn.discordapp.com/attachments/1065932269367337000/1065935838409666620/image.png

https://cdn.discordapp.com/attachments/1065932269367337000/1065932399449485372/2023-01-20_16-42-57.png

**Additional context**

**Comment by oswy-cpu** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/74738120/213695735-05ea99ed-f576-485e-b661-78505b6a4eb0.png">

Same with other chains. Dest. free will be the equivalent of 100 USD in the origin chain token.

**Comment by Grraarrgghh** [comment]
Adding another to the pile:

https://discord.com/channels/454734546869551114/1065933073042120745
https://cdn.discordapp.com/attachments/1065933073042120745/1065933253338472459/2023-01-20_16-46-39.png

**Comment by sanchaymittal** [comment]
release fix in latest release: https://github.com/connext/monorepo/releases/tag/v0.2.1-rc.15
