### ISSUE TITLE
Removing router liquidity in explorer should use `removeRouterLiquidityFor` and not approve

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3162]
The explorer UI for removing router liquidity has two issues in it:

1. The function asks for token approval, which should not be necessary here.

2. The function currently uses [`removeRouterLiquidity`](https://github.com/connext/monorepo/blob/main/packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol#L498) instead of [`removeRouterLiquidityFor`](https://github.com/connext/monorepo/blob/main/packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol#L476).

The consequence of (2) is that you are not able to remove router liquidity if you are a router `owner`, only if you use the router hotkey itself. This is bad because router operators should ideally secure their hotkeys in an isolated environment, and never use them for fund management operations like this.

The fix is simple/minimal. Update the function name + pass in `_router` address which should come from page context.

**Comment by pjenviri** [comment]
We don't see `removeRouterLiquidityFor` in the SDK.

**Comment by just-a-node** [comment]
Should be available in rc.16

**Comment by sanchaymittal** [comment]
reminder bump @pjenviri @nrsirapop

**Comment by pjenviri** [comment]
@sanchaymittal , yeah, it's in QA rn. :)

**Comment by alexwhte** [comment]
confirmed working by p2p
![image](https://user-images.githubusercontent.com/37959170/215300814-26d8c74b-609b-4e4e-b818-427077d4ae62.png)
