### ISSUE TITLE
Some transfers coming in with 0 relayer fee

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3164]
**Describe the bug**
All of these are 0 fee, why? Are they integrators? We should have error messages per https://github.com/connext/monorepo/issues/3009

![image](https://user-images.githubusercontent.com/37959170/213752146-a5df153b-54ac-4af7-90ec-68ccaa53e1cd.png)

**Comment by alexwhte** [comment]
Marking as critical untill/unless we can confirm this is a non-issue or user error

**Comment by alexwhte** [comment]
![image](https://user-images.githubusercontent.com/37959170/213936993-1865b5d7-c6cc-4f58-afc4-d388569b8ce6.png)

**Comment by sanchaymittal** [comment]
If relayer fee is zero, it shouldn't be coming from the sdk now. we have placed fallback in place.

**Comment by sanchaymittal** [comment]
not a bug, closing this
