### ISSUE TITLE
incorrect balance error bridging receive nextAsset 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3186]
I saw this error on every destination chain. It also didnt load certain fees.  When I refreshed and came back it went away
1. Choose Ethereum
2. Choose receive next asset
3. See error
4. Change destination chain
5. See error still

![image](https://user-images.githubusercontent.com/37959170/214135957-2d8a13a9-ec38-45df-872a-9cd3e401a887.png)

**Comment by jakekidd** [comment]
working for me, cannot seem to repro
![image](https://user-images.githubusercontent.com/37907740/214185669-1f053f1a-3f66-48c0-9a26-09d38f2125f5.png)

**Comment by jakekidd** [comment]
is your wallet connected? @alexwhte

**Comment by pjenviri** [comment]
This could be because of some issue on BSC RPC. Changed the RPC.

**Comment by just-a-node** [comment]
LGTM too, @alexwhte to confirm your side?
