### ISSUE TITLE
2 transfers pending execute with 0value 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3190]
0xe653204cf16eee0f01e4b74dccbf8a3f0930a19102974a65a7af8139b68f8539
0xe8c18eb5d620bc71272eba2140a2101fe87bdde359d6bbcfac582f6920ea24fe

https://amarok.connextscan.io/transfers

These are reconciled not executed from 5 days ago 
![image](https://user-images.githubusercontent.com/37959170/214165513-8a9bd08a-0650-4cbc-90dc-d98bbd55b1d7.png)

**Comment by alexwhte** [comment]
may be wonderland

**Comment by rhlsthrm** [comment]
Both completed, needed wonderland whitelisting.
