### ISSUE TITLE
Performance Tab in Explorer

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3192]
## Problem
We should monitor our health from a latency and performance perspective over time

## Potential solutions
Create a new tab in Explorer. Permission this at first just for Connext please. 

A) Topline
We will likely want 4 charts (comment 1 below) 
Two fast path charts over time in minutes
1. Topline Fast Path TTV 'avg(fastpath_avg_ttv_in_secs) / 60 ` 
2. Topline Fast Path TTR 'avg(fastpath_avg_ttr_in_secs) / 60 ` 

Two slow path chart over time in minutes
1. Topline Fast Path TTV 'avg(fastpath_avg_ttv_in_secs) / 60 ` 
2. Topline Fast Path TTR 'avg(fastpath_avg_ttr_in_secs) / 60 ` 

B) Drilling down 
For all charts
Have a toggle that allows the user to split out the topline to view all lines origin->destination chain (comment 2 below)
Have a filter to filter by origin chain
Have a filter to filter by destination chain

**Comment by alexwhte** [comment]
Topline averages
```
SELECT
	transfer_hour,
	avg(fastpath_avg_ttv_in_secs) / 60 AS TTV_fast_avg_mins_allchains,
	avg(fastpath_avg_ttr_in_secs) / 60 AS TTR_fast_avg_mins_allchains,
	avg(slowpath_avg_ttr_in_secs) / 60 AS TTR_slow_avg_mins_allchains,
	avg(slowpath_avg_ttv_in_secs) / 60 AS TTV_slow_avg_mins_allchains
FROM
	hourly_transfer_metrics
WHERE
	transfer_hour >= '2023-01-21 00:00:00+00'
	AND (slowpath_avg_ttv_in_secs IS NOT NULL
		OR slowpath_avg_ttr_in_secs IS NOT NULL
		OR fastpath_avg_ttv_in_secs IS NOT NULL
		OR fastpath_avg_ttr_in_secs IS NOT NULL)
GROUP BY
1
ORDER BY 1 DESC
```
![image](https://user-images.githubusercontent.com/37959170/217968082-f0e2b227-0700-44cd-8933-1a072f568fca.png)

**Comment by alexwhte** [comment]
Chain averages
```
SELECT
	transfer_hour,
	CASE 
		WHEN origin_chain = '6648936' THEN 'Ethereum' 
		WHEN origin_chain = '1869640809' THEN 'Optimism' 
		WHEN origin_chain = '6450786' THEN 'BNB' 
		WHEN origin_chain = '6778479' THEN 'Gnosis' 
		WHEN origin_chain = '1886350457' THEN 'Polygon' 
		WHEN origin_chain = '1634886255' THEN 'Arbitrum One'
		ELSE 'Error'
	END AS origin,
	CASE 
		WHEN destination_chain = '6648936' then 'Ethereum' 
		WHEN destination_chain = '1869640809' then 'Optimism' 
		WHEN destination_chain = '6450786' then 'BNB' 
		WHEN destination_chain = '6778479' then 'Gnosis' 
		WHEN destination_chain = '1886350457' then 'Polygon' 
		WHEN destination_chain = '1634886255' THEN 'Arbitrum One'
		ELSE 'Error' 
	END AS destination,
	avg(fastpath_avg_ttv_in_secs) / 60 AS TTV_fast_avg_mins_allchains,
	avg(fastpath_avg_ttr_in_secs) / 60 AS TTR_fast_avg_mins_allchains,
	avg(slowpath_avg_ttr_in_secs) / 60 AS TTR_slow_avg_mins_allchains,
	avg(slowpath_avg_ttv_in_secs) / 60 AS TTV_slow_avg_mins_allchains
FROM
	hourly_transfer_metrics
WHERE
	transfer_hour >= '2023-01-21 00:00:00+00'
	AND (slowpath_avg_ttv_in_secs IS NOT NULL
		OR slowpath_avg_ttr_in_secs IS NOT NULL
		OR fastpath_avg_ttv_in_secs IS NOT NULL
		OR fastpath_avg_ttr_in_secs IS NOT NULL)
	--AND origin_chain = '1869640809'
	--AND destination_chain = '1634886255'
GROUP BY
	1, origin_chain, destination_chain
ORDER BY 1 DESC
```

![image](https://user-images.githubusercontent.com/37959170/217968270-d3498d3c-11ea-4092-bbed-9c469ff6e1ae.png)

**Comment by pjenviri** [comment]
@alexwhte where can we get these above data? could you share us the endpoints?

**Comment by alexwhte** [comment]
no longer relevant, will handle another way
