### ISSUE TITLE
New Liquidity tab in explorer

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3198]
## Problem
We should better drill into the details of liquidity especially as we bootstrap and evaluate capital efficiency

## Proposed Solution
A few insight ideas:

**Topline**
See Topline Liquidity (TVL) as a time-series (split by chain, split by asset). Stacked bar chart is fine  like we have for Volume and Transactions in the Overview Tab
![image](https://user-images.githubusercontent.com/37959170/214207990-8fe9122b-10fa-4421-8035-0ea428c7833a.png)

**Router vs. AMM Topline**
Compare router vs. AMM liquidity as a time-series. 
I think a clustered bar chart might work best here as it's comparative
![image](https://user-images.githubusercontent.com/37959170/214206389-a37fd6d6-3d10-47e1-8b36-2c3447003e1a.png)
BONUS: Able to drill in further to see this by any chain AND/OR by asset
For example if we had dropdowns to drill down for both of these (chain, asset) 

**Router TVL**
We would like to view liquidity for all routers over time
The ability to filter down to a specific router
The ability to overlay a line like volume 
![image](https://user-images.githubusercontent.com/37959170/214207783-7de94c30-f8b3-48fe-bb64-d1bf7fdca9e3.png)

**AMM Liquidity**
The ability to see liquidity for all pools over time as a time-series
But also filter down to a pool to see the pooled assets split (assetA vs. nextAssetB)
![image](https://user-images.githubusercontent.com/37959170/214207268-e2ba5d34-b9c1-4c05-b65f-df2569d17c5e.png)

**Comment by pjenviri** [comment]
@alexwhte, we can't build it from the current data right now. However, it's similar to one discussed in this card: https://app.zenhub.com/workspaces/connext-6272a34e0368a200141cd949/issues/gh/connext/monorepo/3553. Please let me know if you can add a new data field or have other alternative ideas.
