### ISSUE TITLE
division-by-zero error 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3214]
`[calculateAmountReceived error] {originDomain: '6450786', destinationDomain: '6648936', originTokenAddress: '0x5e7d83da751f4c9694b13af351b30ac108f32c38', destinationTokenAddress: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', amount: c, …}
`
Divide by zero errror when bridging nextAssets from origin of an L2 origin

![image](https://user-images.githubusercontent.com/37959170/214450681-6eaf24b1-3f3a-456a-bb6a-8aadc3bd6bd6.png)

**Comment by pjenviri** [comment]
It's the exception returned by calling `sdk.nxtpSdkPool.calculateAmountReceived`.

**Comment by rhlsthrm** [comment]
We will need to look into this!

**Comment by just-a-node** [comment]
Dupe of #3219

**Comment by just-a-node** [comment]
Dupe of #3219
