### ISSUE TITLE
Native ETH to Arb/Opt is erroring

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3218]
**Describe the bug**
![Screenshot 2023-01-25 at 11.11.18.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/9300f8f2-f131-48b9-9cd6-7afd9ba5c175)

**To Reproduce**
1. Bridge Native ETH to Arb or Opt

**Additional context**

**Comment by just-a-node** [comment]
Check again after comment in https://github.com/connext/monorepo/issues/2642 is addressed

**Comment by rhlsthrm** [comment]
Worked! https://arbiscan.io/tx/0x1523391a5cf207b74e52adcf8c313b1313a1f4dcaf2c072d7dbe68ee7b5cc81b
