### ISSUE TITLE
As an explorer user, I want to search by xcall caller in order to find transfers with specific contract addresses..

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3223]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Integratoooors will call xcall through a contract. They want to be able to see transfers on the explorer based on the caller contract, not the tx origin.

Confusion ensued here: https://github.com/connext/monorepo/issues/3125

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Add method to SDK called `getTransfersByXCallCaller`.
- [ ] Design UI to search by xcall caller.
![image.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/86db7d8a-68b6-4852-af1a-e51a8303e10b)
(bad mockup, that's supposed to be a slider to allow searching by xcall caller)
- [ ] Implement new method.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Able to search by xcall caller.

**Comment by rhlsthrm** [comment]
Connext side is done. We will do a release now and you will have the ability to implement this.

**Comment by alexwhte** [comment]
@rhlsthrm  @pjenviri  When I search by one of my EOAs 0x6d91e35d502fb6F654992283e6E4f397fC23DC2c

I still see other random addresses
![image](https://user-images.githubusercontent.com/37959170/215388083-5dbc7e73-88c5-46ab-93d3-fb995208304a.png)

Where is the issue? 
![image](https://user-images.githubusercontent.com/37959170/215388121-189f4dc9-27be-4a51-953e-551793516bc0.png)

**Comment by rhlsthrm** [comment]
I get the correct transfers when I call using the API:
```
curl --request GET \
  --url 'https://postgrest.mainnet.connext.ninja/transfers?xcall_caller=eq.0x6d91e35d502fb6f654992283e6e4f397fc23dc2c' 
```

```
curl --request GET \
  --url 'https://postgrest.mainnet.connext.ninja/transfers?xcall_tx_origin=eq.0x6d91e35d502fb6f654992283e6e4f397fc23dc2c' 
```

**Comment by rhlsthrm** [comment]
In the explorer network requests I see that all transfers are being queried without a filter:

```
https://postgrest.mainnet.connext.ninja/transfers?limit=100&offset=0&order=xcall_timestamp.desc&select=transfer_id,nonce,to,call_data,origin_domain,canonical_domain,canonical_id,destination_domain,bridged_amt,normalized_in,origin_sender,origin_chain,origin_transacting_asset,origin_transacting_amount,origin_bridged_asset,origin_bridged_amount,xcall_caller,xcall_transaction_hash,xcall_timestamp,xcall_gas_price,xcall_gas_limit,xcall_block_number,xcall_tx_origin,destination_chain,receive_local,status,routers,delegate,slippage,destination_transacting_asset,destination_transacting_amount,destination_local_asset,destination_local_amount,execute_caller,execute_transaction_hash,execute_timestamp,execute_gas_price,execute_gas_limit,execute_block_number,execute_origin_sender,execute_tx_origin,reconcile_caller,reconcile_transaction_hash,reconcile_timestamp,reconcile_gas_price,reconcile_gas_limit,reconcile_block_number,reconcile_tx_origin,relayer_fee,error_status
```

Can you tell us exactly what params you are putting into the SDK call @pjenviri ?

**Comment by pjenviri** [comment]
@rhlsthrm 
Here it is https://github.com/CoinHippo-Labs/connextscan-ui/blob/a2c3a20f837a1ea1ca3950defb57529936bdf246/components/transfers/index.js#L172-L199.

The issue may be caused by this line: https://github.com/connext/monorepo/blob/main/packages/agents/sdk/src/sdkUtils.ts#L187.

**Comment by rhlsthrm** [comment]
Ah that looks like a bug!

**Comment by rhlsthrm** [comment]
https://github.com/connext/monorepo/pull/3263 Fix here, release coming soon.

**Comment by rhlsthrm** [comment]
Fixed!
