### ISSUE TITLE
As an explorer user, I want to search for transactions by xcall hash in order to find transactions easier.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3224]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Users want to search by tx hash.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
We can already do this through the API easily: 
```
curl --request GET \
  --url 'https://postgrest.mainnet.connext.ninja/transfers?xcall_transaction_hash=eq.0xbbc94ed8c302f803a2dfa9466976893b9da2b29a00118e3f76f2d8780f69c059' \
  --header 'user-agent: vscode-restclient'
```
- [ ] Create SDK method to expose this API.
- [ ] Add API to UI.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Search for txs by hash.

**Comment by rhlsthrm** [comment]
We already have the ability to do this! You can just use `getTransfers` with the `transactionHash` parameter! @pjenviri you guys can go ahead and add this search functionality already.

**Comment by alexwhte** [comment]
@rhlsthrm can you test?
i tried with https://etherscan.io/tx/0xabdd1a160073c495e472f01ede922e4e4b19b7fb6e4c61c22f8107d71a1ec8fe
but it's not retrieving anything. you would know best

**Comment by rhlsthrm** [comment]
It's still not working. I can withdraw that transfer from the API:

```
curl --request GET \
  --url 'https://postgrest.mainnet.connext.ninja/transfers?xcall_transaction_hash=eq.0xabdd1a160073c495e472f01ede922e4e4b19b7fb6e4c61c22f8107d71a1ec8fe' 
  ```
But it's not giving me anything on the explorer.

**Comment by pjenviri** [comment]
This is related to the issue we discussed [here](https://github.com/connext/monorepo/issues/3223#issuecomment-1408002655). I believe that the upcoming fix release should resolve this card as well.

**Comment by rhlsthrm** [comment]
Fixed!
