### ISSUE TITLE
Add multicall to SDK for rpc errors/optimization

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3226]
## Problem
Currently our RPC calls from UI/SDK side are inefficient and causing buggy behavior for end UI users 

## Proposed Solution
see discussion here https://discord.com/channels/992549151134982234/1062911678561386538

**Comment by jakekidd** [comment]
The most useful way to develop this feature would be to expand txservice (ChainReader) to include a method for making a "multi read" call. Pass in an array of readTxs, and then we do a static call under the hood to read all of them at once!

The SDK currently uses ChainReader, so it would just be a matter of finding cases in the SDK where we are doing multiple read calls in a `Promise.all` block and then instead invoking the `this.chainreader.multiread(...readTxs)` method. Ez

**Comment by alexwhte** [comment]
on hold for https://github.com/connext/monorepo/issues/3106
