### ISSUE TITLE
As a bridge user, I want have a toggle selector in order to choose if the given amount corresponds to the final amount I will receive, or the amount I'm going to send.

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#3228]
## ATTENTION
Please see Tommy's comment below on a better way to do this!

## Problem
_Users want to be able to chose the final amount they want to receive on destination, instead of doing an inverse caluclation to get the exact amount._ 

## Proposed Solution
_To solve this, the bridge has to calculate all the necessary fees so that the amount to be sent set by the user corresponds to the net amount that reaches the destination chain._
- For example: I want to receive $5 on the destination chain. I have to try and iterate with different values on the bridge to get to the $5 received net amount (because of all the fees), so in the end I will have to input something like "$5.2457" to cover the fees, which is quite annoying since I may have to input a lot of decimals to get to the exact number, a UX nightmare.
SOLUTION --> The bridge should have a toggle under 'Advanced' with something like "Received net amount" for option A, and "Sent amount" for option B, so that users can select which option fits them best.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] I set the toggle to the "Received net amount" setting and receive the exact amount I input on the Bridge UI, with the bridge calculating all necessary fees for it.

Problem pointed out in a Discord ticket by user **wooses15#5989**

**Comment by Tommy-R8** [comment]
I'd recommend to just let users fill in the "you receive" field. Great suggestion
![image](https://user-images.githubusercontent.com/84744304/214653163-66c42e9d-3986-4c5a-aec7-7e55869aff90.png)

**Comment by 0xanedi** [comment]
Tommy's solution is even better IMO. It produces far less clutter and complexity and is really intuitive. To be considered!

**Comment by rhlsthrm** [comment]
This is actually not possible for us to do right now because of the destination side AMM which makes it impossible to get an exact amount since we don't know exactly how much will be bridged over to begin with. Closing this for now until we have a better system to implement this.
