### ISSUE TITLE
Lighthouse propagate down? check

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3229]
](https://discord.com/channels/992549151134982234/994129054347317248/1067908708723609651)

https://betteruptime.com/team/40435/incidents/332778598

**Comment by alexwhte** [comment]
last transfer took longer than expected (fast path 5m 58s)

https://amarok.connextscan.io/tx/0xb3172803cb619c470f1fb482d4ff17d209ff262d349deff4a606d46bd6179cd4

**Comment by jakekidd** [comment]
closed as lighthouse was revived after 4 failed heartbeats
