### ISSUE TITLE
Improve scaling for this user's resolution

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3233]
17-inch LCD Monitor
1024*768

user has to scroll and/or zoom to see the bridge... not sure if there are easy options here

![image](https://user-images.githubusercontent.com/37959170/214757175-b766c8b3-ba44-4520-b2df-4194e5e2d199.png)

**Comment by pjenviri** [comment]
updated, please try and let us know.

![Screenshot_2566-01-26_at_14.22.25.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/7a84a88e-ae7d-46f9-a8f2-727644ba221e)

**Comment by alexwhte** [comment]
pinged user to verify
