### ISSUE TITLE
Retry heartbeats for critical agents 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3240]
## Problem
Missing a heartbeat is a critical failure but a retry function would allow us to more quickly assess urgency ie if it is temporary or more severe on the fly 

ex/ https://github.com/connext/monorepo/issues/3229 for lighthouse propogae

## Proposed Solution
Add retry heartbeats function

**Comment by preethamr** [comment]
This is not the case anymore as we now retry in the URL request handler.
https://github.com/connext/monorepo/blob/cb6f2b7dedb2aebfa7ae78af144fc252abfaa9ac/packages/utils/src/helpers/axios.ts#L13-L14
