### ISSUE TITLE
List of UI visual tweaks (color, buttons, etc.)

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3241]
## Problem
We are gathering feedback from users here. Please edit the description to list them out

## Feedback list

- The green color with the white background is a weird contrast
![image](https://user-images.githubusercontent.com/84744304/214919508-34007cd5-c7e9-430a-ad52-21ef2d1c99d4.png)

- The TVL section moves when hovering over the chain with the largest TVL
![Connextscan tvl bug](https://user-images.githubusercontent.com/84744304/225381400-e0332f91-e675-4768-b713-857f2f4506b2.gif)

**Comment by alexwhte** [comment]
I'm honestly surpised people use light mode we mostly designed it for dark mode. Backlog for now maybe we design light mode better in the future

**Comment by MinistroDolar** [comment]
Hi! I'm gonna paste an user bug report from discord (i've tested it and its happening with every browser i tried)

**Problem**

1. I'm on Pool page (https://amarok.bridge.connext.network/pools) and then move to Bridge page (https://amarok.bridge.connext.network/USDC-from-arbitrum-to-ethereum)
2. Then I am not able to go back (to pool page) 
<- - browser button doesnt work, it just updates the site but doesnt redirect me to previous page

![image](https://user-images.githubusercontent.com/26097731/215833670-5a70c9c9-e6e4-4e7d-a794-0fce4942ab46.png)

**Comment by oswy-cpu** [comment]
- After clicking on the arrow button, the network icons do not change.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/74738120/215979035-bfbaa88d-c46d-4386-ac1a-361907b5842d.png">
