### ISSUE TITLE
[EXPLORER] Filtering transactions by address doesn't work

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3242]
**Describe the bug**
When searching for an address on Amarok Connextscan the filter doesn't apply and the explorer shows all the latest transactions for all addresses.

**To Reproduce**
1. Go to amarok.connextscan.io
2. Use the search bar to search an address
3. Get taken to that address' url (amarok.connextscan.io/0x...)

**Additional context**
![image](https://user-images.githubusercontent.com/84744304/214925247-b62b0774-2329-4cb2-ba0a-97d8c41f327a.png)

**Comment by alexwhte** [comment]
fixed
