### ISSUE TITLE
[EXPLORER] As a user I want a link that takes me to my address' Amarok transactions

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3243]
## Problem
There's no link in Amarok Connextscan that takes me to my connext transactions. There are only links to the origin and destination chain's explorers.
![image](https://user-images.githubusercontent.com/84744304/214926027-f7b911f5-a539-4072-876f-b756a53569c7.png)

## Proposed Solution
Have the explorer be more like the old one, with separate links to Connextscan, and each chain's explorers.

## Acceptance Criteria
I can click on a link that takes me to amarok.connextscan.io/0xmyaddress

**Comment by alexwhte** [comment]
thanks @Tommy-R8 moving to backlog for now as you can copy+search still
