### ISSUE TITLE
User can't use Amarok with WalletConnect

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3244]
**Describe the bug**
When swapping or bridging (Polygon) the spinning circle icon on “Please Confirm” button continues to spin after the swap is complete. iPad Pro 12.9 with iOS 16.2 firmware installed (and later tried 16.3) using the latest Edge browser and the latest version of the Zerion app connected using WalletConnect.
![image](https://user-images.githubusercontent.com/84744304/214938907-1400ecfc-b213-4568-bf74-a77445d401bc.png)
![image](https://user-images.githubusercontent.com/84744304/214938993-683c5073-22d2-46b7-91c3-1da7019bca25.png)

**Comment by alexwhte** [comment]
havent been able to replicate yet

**Comment by LayneHaber** [comment]
closing, stale
