### ISSUE TITLE
daily_router_tvl not retaining historic data

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3254]
Not sure if a bug but this should be a updating with historic data but looks like it's overwriting each day (only has latest day's TVL values) 

![image](https://user-images.githubusercontent.com/37959170/215299507-8a1365c6-ea09-46fc-8f1d-aeedf92a4d6d.png)

**Comment by alexwhte** [comment]
@liu-zhipeng I'm still not seeing router tvl history, i only see 2023-02-10 in cartographer right now 

Sorry to add scope, but can we also add the chain/domain as a column? This will allow us to slice both passive and active liquidity by chain

**Comment by liu-zhipeng** [comment]
> @liu-zhipeng I'm still not seeing router tvl history, i only see 2023-02-10 in cartographer right now
> 
> Sorry to add scope, but can we also add the chain/domain as a column? This will allow us to slice both passive and active liquidity by chain

I can see. `daily_router_tvl` table on prod

**Comment by liu-zhipeng** [comment]
curl https://postgrest.mainnet.connext.ninja/daily_router_tvl
