### ISSUE TITLE
ttr_ttv table errors

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3255]
Per Sanchay
- not all the data is being analysed
- old standards for the fast and slow path classification are being used.
- we need to double check the views metrics against the existing data points in table

https://discord.com/channels/992549151134982234/1067993776657797120/1068048763370881096

trying to look at these metrics by chains and path type
![image](https://user-images.githubusercontent.com/37959170/215300674-ace274ef-e82c-466e-b8c6-67390997f2ea.png)

**Comment by preethamr** [comment]
Fixed query ttr, ttv query:
https://github.com/connext/monorepo/commit/67be68a200a6d976661a6d03b37994f1faa466d9

**Comment by alexwhte** [comment]
@preethamr is this fix shipped already?

**Comment by preethamr** [comment]
> @preethamr is this fix shipped already?

Yes

Can you verify/QA ?

**Comment by sanchaymittal** [comment]
is this update on staging or prod @preethamr?

**Comment by sanchaymittal** [comment]
looking good!! nice work 🎉
