### ISSUE TITLE
Slippage entry overwritten when we display warning

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3256]
**Describe the bug**
https://amarok.bridge.connext.network/USDC-from-ethereum-to-binance
Go to here
When I enter a small amount .000001 in slippage
I see the yellow text Warning, but it also changes the amount i entered to 0. It shouldnt overwrite my entry with 0

![image](https://user-images.githubusercontent.com/37959170/215300899-52966a06-7343-4a6f-8017-d3dee13a7469.png)

**Comment by pjenviri** [comment]
We override the amount due to the smallest possible increment for slippage is 0.01%  (discussed in this [card](https://app.zenhub.com/workspaces/connext-6272a34e0368a200141cd949/issues/gh/connext/monorepo/3000)). And already adjusted the amount to be overwritten to 0.01%. Please try it again.

**Comment by alexwhte** [comment]
@just-a-node let me know your thoughts on the minimum
If we have good reason im fine with it but it 
- prevents me from testing super low slippage (not sure how to test slippage UX well yet so we can have employee address override)
- Maybe we should just tell user in UI "Minimum slippage is 0.01%"
