### ISSUE TITLE
Cannot estimate relayer fee at the moment

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3257]
Unable to calculate relayer fee right now. I think we had this before? i cant find the issue

Steps
1. Go to https://amarok.bridge.connext.network/USDC-from-ethereum-to-binance?amount=1
2. Update slippage to small amount
3. Try to transfer. See error

![image](https://user-images.githubusercontent.com/37959170/215300999-8ae86545-7ffc-4ded-9bdc-d26602aa9575.png)

**Comment by alexwhte** [comment]
i cant see any error s in my terminal

**Comment by pjenviri** [comment]
We adjusted the UI to 
- force sending the `relayFee` showing on the _Destination gas fee_.
- add `[xcall setup]` to the console log. If you still see the error message, please send us the log you found.

**Comment by alexwhte** [comment]
![image](https://user-images.githubusercontent.com/37959170/215916728-49a84597-1845-496b-ab5b-010bea0a595a.png)

**Comment by pjenviri** [comment]
If you still encounter this error, please send us the console log: `[xcall setup]`. 

The UI usually submits the received estimated values shown on the screen to xcall. The error might happen when the user clicks the xcall button before the estimation is done. So, we handled it by disabling the button and waiting until all the parameter is set properly for xcalling.
