### ISSUE TITLE
Investigate testnet calldata carto logging

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3258]
All transfers on testnet have logged no calldata (0x). What is wrong here? 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/37959170/215305535-2a24f8c3-37cd-467c-93f6-fd9e4ca797da.png">

On mainnet we are capturing xcall calldata in the tables 
<img width="722" alt="image" src="https://user-images.githubusercontent.com/37959170/215305573-1c43fe52-59be-463e-a13d-36b80c6e45e6.png">

**Comment by rhlsthrm** [comment]
I see plenty of non-0x calldata transfers:

<img width="1433" alt="Screenshot 2023-01-30 at 16 38 43" src="https://user-images.githubusercontent.com/11512787/215479295-8552c310-cc29-4009-9377-144640777f39.png">
<img width="1433" alt="Screenshot 2023-01-30 at 16 39 58" src="https://user-images.githubusercontent.com/11512787/215479524-e635a80e-dd24-49a7-8674-045d2b108c28.png">

I think you were looking at testnet staging which might not have any calldata transfers.
