### ISSUE TITLE
Add 'destination_chain' column to tables transfer_count and transfer_volume

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3260]
## Problem
We may want to analyze inflows/outflows for Connext v2.  `destination_chain` may be as important as `origin_chain` to better understand where users are going and to help manage liquidity 

## Proposed Solution
Currently we are tracking #transfers and volume by day/origin_chain/asset/path

We should add `destination_chain`

## Acceptance Criteria
- [ ] This new column exists for tables transfer_count and transfer_volume

**Comment by alexwhte** [comment]
![image](https://user-images.githubusercontent.com/37959170/215361128-104bfc38-3ff8-4ae8-9695-74007b49f153.png)

ex it would be good to see here in transfer_count table

**Comment by LayneHaber** [comment]
closing
