### ISSUE TITLE
Add carto+SDK+Explorer information for bumped transfers

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3274]
## Problem
This transfer https://amarok.connextscan.io/tx/0x43a18ae34446cdb383951010cfda1caedce9bdb1b42efda81a6394603df5c4a1 had relayer fee bumped. I dont think there's any way to know this though?
We 
a) Want to see which transfers have been resolved in the case of an emergency
b) Want to meausure how much bumping is occuring (and ideally the difference from before/after) 

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] have column that stores if `hadSlippageBumped`
- [ ] have column that stores if `hadDestinationGasBumped`
- [ ] [OPTONAL- if too complex dont let this block the issue] Add columns that further store the amount bumped (or before and after)
- [ ] Expose in SDK
- [ ] Implement in Explorer so the same transfer above is able to be identified as bumped

**Comment by LayneHaber** [comment]
closing, stale
