### ISSUE TITLE
Upgrade to new WalletConnect modal

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3281]
## Problem
_What problem are we solving and why does it matter, ser?_ 
WalletConnect has updated their modal and it looks much nicer, is themable, and has new features.

https://github.com/WalletConnect/web3modal/tree/V2/examples/react

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Update package

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Package is updated.

**Comment by alexwhte** [comment]
would this fix #3244 by chance? 
im not sure how to test this well

**Comment by rhlsthrm** [comment]
> would this fix #3244 by chance? im not sure how to test this well

Quite possibly.

**Comment by alexwhte** [comment]
@pjenviri can you please blur the background on this? it is too noisy right now on top of the bridge

**Comment by pjenviri** [comment]
- adjusted the background color
- added the Connext logo
- the background appears blurred when the modal is active, 

FYI: [Here](https://docs.walletconnect.com/2.0/web3modal/theming) are the attributes supported by WalletConnect that can be customized.
