### ISSUE TITLE
"Back" button doesnt work (From Bridge site to previous site)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#3285]
Hi! an user detected a little bug related to our bridge site. He (and i) cant go back to pool/swap page from bridge site. I've tested it with desktop (firefox and chrome) and phone (safari and chrome).

1. When I am on Pool page (https://amarok.bridge.connext.network/pools) and then move to Bridge page (https://amarok.bridge.connext.network/USDC-from-arbitrum-to-ethereum)
2. I am not able to go back (to pool page) 
<- - button doesnt work, it just updates my page but doesnt redirect me to previous page

![CONNEXT AMAROK BUG](https://user-images.githubusercontent.com/26097731/215837164-38dd4210-ddc5-4643-9cab-176a1016ca77.jpg)

PD: it also happens if i want to go back to SWAP site.

**Comment by alexwhte** [comment]
replicated tthis, hanks @MinistroDolar 
passing to Coinhippo
