### ISSUE TITLE
Make pool asset balance more clear 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3290]
Feedback is pool balance is not clear to users, expecially on mobile 
![image](https://user-images.githubusercontent.com/37959170/215963239-01bb7007-141c-4ecb-a941-5f40fca6eb2a.png)

Can we please:
1. Make the bars slightly wider
2. Add a super subtle line or tick mark where the middle is 
3. Show % of each asset instead of values (these will become longer and clutter anyways)
canonical/(canonical+local)  <----->  local/(canonical+local) 

a. Also show the asset icon next to the percentage so that users dont need to use tooltip to see on mobile  
b. Move the amounts (which we are replacing with percentages) into the tooltips instead
![image](https://user-images.githubusercontent.com/37959170/215963387-3a4f3ac3-9974-42dc-9fed-dfd51bcaeeeb.png)

![image](https://user-images.githubusercontent.com/37959170/215913337-69a8b6fb-83ad-4167-8ca5-a8e1172da307.png)

**Comment by pjenviri** [comment]
Completed all requests except 2 (can't do it).
