### ISSUE TITLE
Investigate Destination gas fee

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3297]
**Describe the bug**
Is the observed changes in `Destination gas fee` quoted on bridge, in high and low gas conditions, as expected ?

**To Reproduce**
1. Go to https://amarok.bridge.connext.network/USDC-from-polygon-to-ethereum?amount=200

**Additional context**
Destination gas fee: 13.997755 MATIC when avg gas was 16 gwei
<img width="489" alt="image" src="https://user-images.githubusercontent.com/1195648/215969357-ef853184-e9e6-4c06-b9d1-d884c760ddbf.png">

Destination gas fee: 33.75 MATIC when avg gas was 27 gwei

![image](https://user-images.githubusercontent.com/1195648/215969620-b84f2376-e82a-4149-b732-2af9b08f2aa5.png)

**Comment by alexwhte** [comment]
@preethamr please make sure to move this

**Comment by preethamr** [comment]
Need more info.
