### ISSUE TITLE
Gelato tasks reverting

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3318]
From Gelato: 

here are the taskIds for the gas issues on Arbitrum we've just talked about:

0xef9c28513f78fddb8a8b79d8714f3ca4b3e4b4fa53ed1818191bf216051bed79
0xd9a858db3ce5f08d089bddb084ad1a897b05f5710a6ff09240f4683959b30c16
0xafc02ac4b3ed160c21649f3bfe66e22602c28f7354d8d5f7ee0af394da3415d3
0xd9606c9783ad2cd46a7d07b5eaa7cb5ebd5adec7144210f6abb56db562541944

They were all reverted with !gas, e.g. for the taskId 0xd9606c9783ad2cd46a7d07b5eaa7cb5ebd5adec7144210f6abb56db562541944 it happened on block 56987956.
I think this is where it's happening: https://dashboard.tenderly.co/denis-gelato/project/simulator/45561f2e-4fc3-4a24-8e7a-01a57a8039fe

In this Tenderly simulation I reduced the gas limit from 10M to 8.4M to account for Relay overhead, which might be this high on Arbitrum because of it's broken gas calculations.

In our experience even the simplest counter contract call on Arbitrum could consume 1.8M gas, as we see in this example: https://arbiscan.io/tx/0x95e5b2397f22b088be467fad93479b79f1989eee8ad4b6dacc85d2d946774ddf

So to mitigate these issues we would recommend to set higher gas limits on Arbitrum and take into account, that the Relay overhead could be up to 2M gas.

**Comment by preethamr** [comment]
Will update the limit to 20M

Current arbitrum block gas limit: `1,125,899,906,842,624`
