### ISSUE TITLE
Have more granular stableswap pool data over time

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3321]
## Background

We dont have great insight into 
- How is TVL changing over time in these pools? (by chain+asset) at a topline. This will be important to analyze over time how the pools are changing 
- Which users are adding the most? removing hte most? To which pools? This will be important to analyze over time who are our power users, for example. We can also join this to bridge transfer data based on the address 

### Proposed solution 
Have logging that enables the below types of queries 

- Query to see Pool events for users (deposits and withdrawels) so that we can A) see how users are using our Pools and B) join this information to the `transfers` table based on address (users) 
We _might_ need these columns for this
_timestamp, address, pool (chain+asset), action (add/remove), amount_asset_A, amount_asset_B, LP_token_amount_
![image](https://user-images.githubusercontent.com/37959170/216247631-c6ef62b4-11ab-47db-9ada-e6e01b33e130.png)

- Query to see Pool metrics over time at a top-level. So we can build charts in a dashboard similar to analysis in here https://docs.google.com/spreadsheets/d/1QtR61roh7-JCJ2BtYG5bYMtWN9CWV5VxlRMcGh7d3P8/edit#gid=221250395
We _might_ need these columns for this
_day, pool (chain+asset), TVL_total, TVL_asset_A, TVL_asset_B, APY, Fees(24H)_
![image](https://user-images.githubusercontent.com/37959170/216247582-97814c8e-ba91-4dfd-902a-d5ba5a75e72b.png)

- Query to see user positions over time at a top-line
We _might_ need these columns for this
_day, address, pool (chain+asset), LP_token_amount, pool_share_
![image](https://user-images.githubusercontent.com/37959170/216247459-eeb5fdab-01b2-4be6-b359-f18bb25d533d.png)

NOTE:  This is just a quick mockup of what would be helpful. Please feel free to come up with your own design or recommendations and let me know if you need more info on the insights we are seeking

**Comment by alexwhte** [comment]
moving to QA, just need to test from user perspective

**Comment by alexwhte** [comment]
@liu-zhipeng I missed something in testing. Are we able to add these metrics to `daily_swap_tvl`? This will support downstream dashboards
- TVL total (sum of balances)
- APY (24h)
- APY (7d)
- Fees

From original
> Query to see Pool metrics over time at a top-level. So we can build charts in a dashboard similar to analysis in here https://docs.google.com/spreadsheets/d/1QtR61roh7-JCJ2BtYG5bYMtWN9CWV5VxlRMcGh7d3P8/edit#gid=221250395
> We might need these columns for this
> day, pool (chain+asset), TVL_total, TVL_asset_A, TVL_asset_B, APY, Fees(24H)

**Comment by liu-zhipeng** [comment]
> 

Yep

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/3533

**Comment by liu-zhipeng** [comment]
@alexwhte  please review above pr
