### ISSUE TITLE
Slow paths from PlanetIX (0-value) appear fast

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3322]
These are all slow path transfers from an integration. What is current logic for displaying as fast/boosted? These should not display boosted lightning bolt

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/37959170/216131642-3014300f-b8fa-433b-a424-0cf97229eff3.png">

**Comment by wanglonghong** [comment]
I guess @pjenviri  is right here because the transfer hasn't been reconciled/executed yet.

**Comment by just-a-node** [comment]
Let's change the logic for displaying lightning bolt:
- only show the lightning bolt after it's executed AND if that occurs before reconcile

**Comment by alexwhte** [comment]
@pjenviri actually see below changes. talked with Eddie a bit today
1. Dont show lighting bolt after xcall anywhere. The time estimate for now will be sufficient. 
2. Show lightning bold in dark grey color OR in yellow based on below logic
![image](https://user-images.githubusercontent.com/37959170/216479203-173284d4-d276-4df7-98fc-0673117debe0.png)
3. Change the tooltip to say "Boosted by router network"

NEW (scope creeping here sorry): Add a new icon for calldata. Feel free to use whatever icon looks best for this 
- Grey or Yellow using the below logic. 
- This can appear immediately after xcall
- BUT should only appear in Explorer NOT in the bridge UI 
- Tooltip says "Transfer has custom calldata"
![image](https://user-images.githubusercontent.com/37959170/216480612-ceb4febf-4b12-4335-bd97-34b104eb64d8.png)

**Comment by just-a-node** [comment]
Small nit: change tooltip to "Not boosted by router network."
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/29c99969-9787-4fed-b69e-e4b10d2351bd)

**Comment by alexwhte** [comment]
@pjenviri From user review, the grey icons were confusing. Can we do this instead

![image](https://user-images.githubusercontent.com/37959170/217975440-816f5f34-ba69-42d5-8342-e03ae12ff6cd.png)
