### ISSUE TITLE
On Pools site, UI starts showing "No liquidity" for Assets and all fields turn to 0/TBD.

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#3323]
**Describe the bug**
When on [Pools](https://amarok.bridge.connext.network/pools), with a wallet connected, I wait around 30secs and suddenly the whole Liq table throws "No liquidity", 0s and TBDs (see screenshot). After some time (about 3mins), site goes back to normal, but breaks again after waiting another 30secs. This appears to be an issue with updating data and sometimes getting no response for whatever reason.

**To Reproduce**
1. Go to 'amarok.bridge.connext.network/pools'
2. Make sure a wallet is connected (not sure if this is related)
3. Stay on the Pools tab and observe mentioned behaviour without interacting with anything on site.

**_SEE ATTACHED CONSOLE LOG PLS_**
[amarok.bridge.connext.network-1675279103414.log](https://github.com/connext/monorepo/files/10560857/amarok.bridge.connext.network-1675279103414.log)

**Additional context [IMAGE]**
![image](https://user-images.githubusercontent.com/89958919/216139356-3f2e05d4-cb0a-41bf-8111-dba9f2db7efb.png)

**Comment by alexwhte** [comment]
Notes from testing
I see it works then i go back 20s later and it's like this
![image](https://user-images.githubusercontent.com/37959170/216213364-a4219b2e-8183-4e39-90cb-797f5daa6bd6.png)

per @just-a-node  ok there's a bit more we can do here actually. the requests to carto added recently aren't being cached
