### ISSUE TITLE
As an integrator, I want to send nested xcalls and have users pay relayer fees from origin

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3330]
## Problem

Sending nested xcalls assumes the receiver contract has access to gas funds. This can be tackled with a gas tank filled by users or the protocol sponsors gas costs itself. But this is either bad UX for users (must send txns to fill the tank, assumes they have gas on destination) or an additional cost for protocols.

## Proposed Solution

In order to allow the entire xcall chain to be funded with relayer fees from origin, we’d have to make the sequencer check for that somehow.

## Acceptance Criteria
- [ ] User's relayerFee on origin covers the entire xcall chain

**Comment by alexwhte** [comment]
needs discussion/research

**Comment by just-a-node** [comment]
Maybe do this custodially with Gelato?

**Comment by rhlsthrm** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/17) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Complexity: 34**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/17) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 2**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/32) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
out of scope, closing
