### ISSUE TITLE
Improve slippage UX for LP users 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3335]
## Problem
User feedback (chompk.eth)
> I just talked with Thai community members about providing the liquidity, the got some feedbacks to the current pool status
> - Most community member are confused on how to get 1:1 nextAsset without slippage from swapping
>   >One of the community member having a hard time trying to provide a nextAsset LP to the pool when they're holding a large amount of money on the destination chain
>   >this guy say that he deposit half nextAsset (from swapping canonical asset to nextAsset) and half canonical asset
>   >he didn't aware of the slippage when depositing, thinking that it should be half-half like x * y = k equation
>   >he said that he's a bit not happy about how he deposit 1000 usd and can't redeem 1000 usd back full (it's 998.4 to be exact) as he doesn't know about the slippage before
>   >he's quite confused if this mechanism will be secure (although it's clearly secure if they understand how mint/lock + AMM works,  we can't expect everyone to understand this as it's quite complex)
> The point is that most people still don't understand how this mint/lock + AMM mechanism works. Here's some of the thing i found people misunderstanding:
> 1. how stablepools work, most people still have a perception that providing one asset = auto swap 50-50 to the pool like x*y = k
> 2. how slippage on stable pools works (they have a thought that for stable asset, providing 100 should get back 100 full)
> 3. A lot of people THINKING that nextAsset SHOULD be obtained from swapping canonical asset only (which is false, the best way is to bridge through Connext from mainnet)

## Proposed solution

1. Add 'Pool Balance' field and show the same bar as the Pools Overview page
Show percentages with their respective token assets

2. Change `Price Impact` to `Slippage` when the number is <0
When >=0, change the field title to `Bonus`

3. When `Slippage` <0, then show the warning (same behavior as before). 
Change the text to say
> Warning

> You may have **-0.00765%** slippage because USDC is currently overweighted in this pool. 
> If you provide additional nextUSDC instead, you may receive **bonus** tokens.
use logic for the amount and the asset names 

4.  Add a link to our LP guide here 
Stuck? Click here for our **LP guide** -> 
Clicking LP Guide links to https://blog.connext.network/providing-liquidity-on-connext-f7aa3f2bc7b8#a940

![image](https://user-images.githubusercontent.com/37959170/216233632-8c864ff6-18ff-4191-8812-99e5b9c1354c.png)

**Comment by alexwhte** [comment]
just made slight update to the wording again

**Comment by Tommy-R8** [comment]
Sort of related to this: make arbitrary amount withdrawals of each pooled token possible

**Comment by alexwhte** [comment]
@Tommy-R8 Please track this in the backlog and feel free to comment if you hear more https://github.com/connext/monorepo/issues/3369

**Comment by Tommy-R8** [comment]
https://discord.com/channels/454734546869551114/1053026258021257316/1071084455239888966
