### ISSUE TITLE
Update GTM in all Connext UIs

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3338]
## Problem
The current tags are not logging correctly 

## Proposed Solution
Please - remove google tags that are not **GTM-MLX9QD8**	. For example in the Pool I see an old one
![image](https://user-images.githubusercontent.com/37959170/216210449-ff72512f-6345-45d7-961f-e083a717ce96.png)
we can remove that

**Make sure GTM is set up correclty in all v1 and v2 UIs** 
Paste this code as high in the **head** of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MLX9QD8');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening **body** tag:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MLX9QD8"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by alexwhte** [comment]
I think this might be in here twice? https://amarok.bridge.connext.network/USDC-from-polygon-to-ethereum

![image](https://user-images.githubusercontent.com/37959170/216357432-ec1db773-2675-453c-a4ec-51c7fc0b1858.png)
![image](https://user-images.githubusercontent.com/37959170/216357601-e03ee46f-ac96-4e90-b862-08f19ca0bb57.png)

**Comment by alexwhte** [comment]
@pjenviri mmm so our analytics are not working at all now for some reason

Letls revert back to last night (original issue)? Just so we can check if it's related  

So add this back in 
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-MPYZEDRVQ0"></script>

![image](https://user-images.githubusercontent.com/37959170/216448329-0fdad7f0-ace7-42d5-b7c7-7139523824aa.png)

**Comment by alexwhte** [comment]
tag assistant isnt working for bridge.connext.network but works for connext.network
![image](https://user-images.githubusercontent.com/37959170/216505856-5e690d77-468c-4f85-9d1c-ec39567ea242.png)
maybe inspecting the elements on connext.network will show the issue? im not super experienced with GA so im not sure :/

**Comment by pjenviri** [comment]
@alexwhte we're investigating but it looks similar to me when comparing `bridge.connext.network` with `connext.network`![Screenshot_2566-02-03_at_22.51.50.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/568a3ebe-5b34-426f-9ad5-7952e5b08aa2).![Screenshot_2566-02-03_at_22.53.31.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/8b6433d3-4fe4-470f-9cd3-19f002fa95d8)

**Comment by alexwhte** [comment]
this is all set! i was wrong
