### ISSUE TITLE
Stop fetching api / rpc calls while tab is non-active

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#3348]
## Problem
UI keeps calling rpc and API while bridge UI tab is not active. After few hours, tab is crashed.

![image](https://user-images.githubusercontent.com/57480598/216276551-685c8b7b-e4bd-43d5-a0fa-11b7785a10cc.png)

## Proposed Solution
- [ ] Get pool data, chain data, balances... just in case of active tab.

https://github.com/Uniswap/interface/blob/b74fb8174d00ddf635e75b6f50fe50317fddb730/src/hooks/useIsWindowVisible.ts#L14

**Comment by alexwhte** [comment]
@liu-zhipeng  can you test?

**Comment by liu-zhipeng** [comment]
> @liu-zhipeng can you test?

Yep, i can
