### ISSUE TITLE
Yet another bump issue. 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3352]
**Describe the bug**
Tx was bumped by the user two times, still pending. 

![image](https://user-images.githubusercontent.com/74738120/216357951-dafe796a-2d4d-4118-a9b3-0109768207da.png)

![image](https://user-images.githubusercontent.com/74738120/216358205-40980fc3-16bf-464b-b11d-9f0c69346d50.png)

**Additional context**
txid: https://amarok.connextscan.io/tx/0x54337ba4e48ff701a25f7d10c7db6ee748f2288ef1694abfb7d8ebe5f34fc802

**Comment by ValerywArz** [comment]
one more 
![image](https://user-images.githubusercontent.com/93597601/216366182-9246ddac-6153-462b-bf1e-88ccaae205b1.png)
![image](https://user-images.githubusercontent.com/93597601/216366314-d42d3c3c-b319-4b18-9ee1-fd8ab1d926b1.png)

https://amarok.connextscan.io/tx/0xed87b24c1c4bd5f9063b2eea77655684998f6bec042521b68d0e417bbe2bbb09

**Comment by dangzemin** [comment]
https://amarok.connextscan.io/tx/0xbccc5fc11674973c2201d43e10cee7bfe1bd18e621de6014834de407bcf38091?src=search
![image](https://user-images.githubusercontent.com/92560156/216376427-932d6c2a-8fc6-4e3c-8f35-ae4c60738137.png)
![image](https://user-images.githubusercontent.com/92560156/216376513-0d542e14-377f-4f04-b9b6-162b62fc1b6f.png)

**Comment by QQHHUH** [comment]
one more
https://amarok.connextscan.io/tx/0x9439ca342a02df02fdcafa783a880de2470925516c339fb750e07225088cde44?src=search
![image](https://user-images.githubusercontent.com/92560156/216378029-8ef79baa-bcab-4810-9656-1f31c2da2975.png)
![image](https://user-images.githubusercontent.com/92560156/216378153-20ec7b4b-cff6-4d05-87ea-daa8d5a59e74.png)

**Comment by just-a-node** [comment]
We'll be fixing this in https://github.com/connext/monorepo/issues/3360
