### ISSUE TITLE
Sequencer and Router should have different admin keys

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3368]
**Describe the bug**
Sequencer and Router should have different admin keys

**To Reproduce**
1. Compare and router and seq admin keys

**Additional context**
Have separate keys and config for both

**Comment by LayneHaber** [comment]
**Complexity: 3**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/21) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Impact: 2**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/41) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Urgency: 2**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/42) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Complexity: 2**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/10) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
