### ISSUE TITLE
Router balance on subgraph showing negative amount

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3377]
**Describe the bug**
Title

**Additional context**
https://app.datadoghq.com/logs?query=host:ip-172-17-1-251.us-east-2.compute.internal%20service:router-subscriber%20container_id:cb8e185d039d4e6580463d50f23bda1e-1601799034&cols=service&context_event=AYYW5bcQAAD53pIdvJ9A9AAH&event=&index=mainnet-production&messageDisplay=inline&saved-view-id=1285114&stream_sort=time,desc&to_event=AgAAAYYW5fJh6hplbwAAAAAAAAAYAAAAAEFZWVc1ZldGQUFCakJaRDRYQkM5VHdBRAAAACQAAAAAMDE4NjE2ZTUtZmE3OC00ZWRkLWEzMzQtMjIxMzAxN2JmNDdj&viz=&from_ts=1675421098800&to_ts=1675421458800&live=false

DataDog log snippet above. This might not still be the case when others look but this is context-specific log.

![Screenshot 2023-02-03 at 15.07.59.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/785244f8-6cdf-4674-8a67-b88f7d524137)

**Comment by rhlsthrm** [comment]
<img width="950" alt="Screenshot 2023-02-03 at 15 19 28" src="https://user-images.githubusercontent.com/11512787/216590807-44a47b44-b20e-4c1a-855f-2fde4542c231.png">

While subgraph showed -6, onchain shows 0.

**Comment by jakekidd** [comment]
Possibly linked to https://github.com/connext/monorepo/issues/1429

**Comment by rhlsthrm** [comment]
Backlogging this one. Impact seems minimal.

**Comment by LayneHaber** [comment]
this could reasonably happen if router withdraws all of liquidity + earned fees
