### ISSUE TITLE
Add support for paying relayer fee in transacted asset

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3378]
## Background

Socket has reported our system of sending relayer fees in sending side gas does not work for their integration. We need to collect some information from other partners about this and see if we have consensus around allowing relayer fees to be paid in sending asset.

On our side this would require changes:
- Add an override for `xcall` that takes in `relayerFeeAsset` and `relayerFee`.
- If user calls `xcall` with the extra params, transfer the asset to our vault.
- Sequencer checks relayer fee sufficiency in the provided asset.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

We have enough answers from partners to make a go/no-go decision since this affects contracts and would require an upgrade.

## Tasks

1. Let's go ask LiFi about this. We should figure out from them how this affects their integration with other folks as well, bc most important thing is to simplify integration path for other projects.
2. Let's go ask a few more projects about this, especially those that are sending ERC20 tokens through our system. 
3. Let's go ask some end users who are using the bridge.

**Comment by rhlsthrm** [comment]
Update: Posed question to Lifi, Keep3r, and Unlock. Question text:

> Hi Keep3r team! We are trying to gather feedback on something:

We have received feedback that some users/integrations do not like the mechanism of paying relayer fee using msg.value (i.e. native asset). We want to ask around and find out if we should work towards enabling a mechanism to pay for relayer fees using the sent asset instead.
> 
> What would you guys prefer? And any reasoning behind this preference?

**Comment by rhlsthrm** [comment]
Quick mockup of required contract changes: https://github.com/connext/monorepo/pull/3380

**Comment by rhlsthrm** [comment]
From LiFi:

> The same flow for all assets would be important, it would be difficult to communicate that sometimes the bridge fees are deducted from the sent token and sometimes some additional funds have to be sent along.
>
> A solution were the user has to sent multiple ERC20s should be avoided (e.g. sending AAVE, but pay fees with USDC).
>
> I prefer the NXTP flow where fees are payed with the transferred asset, conversion of the amounts based on current gas costs on the chains have to be made in any case so the native asset is no advantage here.

**Comment by just-a-node** [comment]
@ArjunBhuptani @LayneHaber to figure out how much effort this would require

**Comment by ArjunBhuptani** [comment]
Spec: https://www.notion.so/connext/Protocol-d7d760166c3d4b848ac7f53e9b040803?p=d5f331c61beb44b6b06d289c0c03f660&pm=c

**Comment by LayneHaber** [comment]
Contract changes in #3380
