### ISSUE TITLE
Pool withdraw amounts incorrect

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3395]
These calculations appear incorrect . Please confirm if this is on Connext SDK side

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/37959170/216743718-3fffac6f-bad1-4f37-a1e9-141a1fac437e.png">

**Comment by alexwhte** [comment]
please also make the withdraw button blue?
this is not a negative action 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/37959170/216744050-58f90e11-60ca-4fa5-b9b7-c216cc42b3e5.png">

**Comment by Tommy-R8** [comment]
User report: https://discord.com/channels/454734546869551114/1053026258021257316/1071225486958657656

**Comment by pjenviri** [comment]
fixed.

**Comment by 0xanedi** [comment]
Props to this one for actualy discovering it a long time ago🙌, though somehow it was never filed https://discord.com/channels/454734546869551114/1062668958211252234/1062669551063547904

Working fine now!
