### ISSUE TITLE
Lighthouse propagate should run at configured rate

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3397]
**Describe the bug**
Lighthouse propagate should run at configured rate

**To Reproduce**
1. LH propagate task is configured to run every 30 mins
2. Check DD logs to find that recent runs have been in clusters of 3 runs, separated by ~30 mins

**Additional context**
Determine the if task configuration is working as intended.

**Comment by wanglonghong** [comment]
went through `RootPropagated` events emitted on [RootManager](https://etherscan.io/address/0xd5d61E9dfb6680Cba8353988Ba0337802811C2e1#events)
Its working as configured

![image](https://user-images.githubusercontent.com/30057497/221735590-66c5e5cd-f1e2-49a2-bcb9-8550448898f0.png)
