### ISSUE TITLE
Missing root on cartographer side

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3401]
**Describe the bug**
Cartographer missed a root record even if its in subgraph. 

**To Reproduce**

1. Missing arbitrum root on carto db.
![image.png](https://images.zenhubusercontent.com/5b67a142386aa6742a90bc34/4024b37a-d2b5-4836-b470-7033ff25bf1d)

spoke_domain: `1634886255`
root: `0xd9bc7000fe24a3bf2a36ef48636b379c1e9c423a886ce027198c36c4390d9b5a`

2. Subgraph record

![image.png](https://images.zenhubusercontent.com/5b67a142386aa6742a90bc34/84f55c95-3c92-488c-979d-ce035024b546) 

**Additional context**

**Comment by preethamr** [comment]
Did we clear/modify carto db manually ?
rn the it says processed:
```
-[ RECORD 1 ]--------------+------------------------------------------------------------------------------
id                         | 0xd9bc7000fe24a3bf2a36ef48636b379c1e9c423a886ce027198c36c4390d9b5a-1634886255
spoke_domain               | 1634886255
hub_domain                 | 6648936
root                       | 0xd9bc7000fe24a3bf2a36ef48636b379c1e9c423a886ce027198c36c4390d9b5a
caller                     | 0xeba8f39400fa84b4ef73a6056ae36d3d25c6fd86
sent_transaction_hash      | 0x26e546265145bcb7f8c71f0eea978d04434e25cc325506f914871e7827b2c768
sent_timestamp             | 1674540612
gas_price                  | 110000000
gas_limit                  | 6000000
block_number               | 55074681
processed                  | t
processed_transaction_hash | 0x70f6e4a73b0f328587372715524c39430ba76bd5d53c6b4d13d0db2a342e0fc7
leaf_count                 | 613
```

**Comment by wanglonghong** [comment]
I've reset checkpoint of processed_root_message table and it has been processed. 
Right now, I want to close this issue
