### ISSUE TITLE
As a balance bot user, I want to update the min balance

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3402]
## Problem
Multichain uses 0.14 BNB, but balance alerts don't fire if the balance is >0.1

## Proposed Solution
We should make these minimums chain- / address-configurable

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] I can set alerts at a higher balance for BNB relayer
- [ ] I get alerts at a higher balance for BNB relayer

**Comment by rhlsthrm** [comment]
We can already do this.
