### ISSUE TITLE
Visualize router liquidity utilization

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3406]
Please in mode=test so we can view it first 
## Problem
1) we don’t know how to view ways to distribute liquitidy as a whole based on end user bridging changes 
2) how routers are allocating individually
We need this urgently to support bridging experience and reach out to routers 

## Ask
Visualize this in the main router page? 
https://connextscan.io/routers

volume/router_tvl  = router utilization 
able to view this split by (chain(destination) + asset)
Ideally view this as a time series, latest state works as a fallback if needed 

## Notes
From Arjun:
> This should be easy to get an idea of based on onchain metrics. Basically, just need to sum up value of all transfers that are in the Executed state at any time and then divide that by router liquidity for a given chain
> if you plot a time series of this^ we would get a % over time of router liquidity that's being used

## Definition Of Done

Router liquidity is measured.

- [ ] Need some more discussion around how to show this info.

**Comment by alexwhte** [comment]
need to spec this out better tomorrow

**Comment by alexwhte** [comment]
We may be able to combine this all as part of hte same tab, but we can iterate https://github.com/connext/monorepo/issues/3198

**Comment by sanchaymittal** [comment]
spec:

Created a new view of total router liquidity to show active liquidity available per asset for each destination:
```
SELECT 
        r.router_address,
        r.domain,
        r.local,
        SUM(
            r.balance
        ) As total_balance
    FROM public.routers_with_balances r
    GROUP BY 1,2,3
```
