### ISSUE TITLE
LP withdrawal shows amounts flipped

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3410]
**Describe the bug**

UI shows withdraw amounts
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/73830c8c-86f2-48ab-9dfa-753ed236f758)

But actual transaction completes with the amounts flipped
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/ccef275e-cb97-49a3-b50f-080f8f52dd9d)

**To Reproduce**
1. go to pool
2. withdraw LP tokens
3. see that the withdraw estimates don't match the actual amounts withdrawn

**Additional context**

**Comment by rhlsthrm** [comment]
I just tried this and it worked properly, closing for now.
