### ISSUE TITLE
Analyze 1Balance Usage

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3429]
## Background

Our relayer usage is high. We should analyze to make sure we aren't sending unnecessary txs.

### Linked Issues & Documentation

https://docs.google.com/spreadsheets/d/1q2W5GnjRTeZQVd28jovffWk6hNAbyIgp/edit#gid=1033217453

## Definition Of Done

We are confident that the costs line up with expectations.

**Comment by wanglonghong** [comment]
https://docs.google.com/spreadsheets/d/1b5NhSdq1giauO27PdCMV_C4ZDwnS6aK1/edit#gid=796871664

basic analytics here
