### ISSUE TITLE
Weirdness in paginating through router assets.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3430]
**Describe the bug**
Seeing weird issues when going through the pages of the assets.

![ab37c06ef98f72615b581ba638f7d40d.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/1d26148a-83c2-4855-9f0b-13c9f51242b2)

NEXT button is greyed out, makes me feel like I can't click it but I can.

![80b3d5bc2ecbcf59d85d1363caf6e531.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/5d9c2e98-0c6d-4069-801a-dcc3f4ac06ac)

Once next is clicked, seeing weird stacking order with buttons, also same greyed out issue.

**To Reproduce**
1. See above.

**Additional context**

**Comment by alexwhte** [comment]
@rhlsthrm can you QA this one? not sure what it was like before

**Comment by rhlsthrm** [comment]
Confirmed!
