### ISSUE TITLE
As a connextscan user, I want to filter transactions by status (not xcall status)

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3431]
## Problem

Want to sort and see all the xcalls with error statuses. 

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
Add filter for "status" column 

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Should be able to see all xcalls with "LowRelayerFee" or "LowSlippage" errors

**Comment by pjenviri** [comment]
@just-a-node understand that `getTransfers` only support `XTransferStatus`. Could you please confirm? https://github.com/connext/monorepo/blob/main/packages/agents/sdk/src/sdkUtils.ts#L173

**Comment by rhlsthrm** [comment]
This is correct @pjenviri. I have added this fix here: https://github.com/connext/monorepo/pull/3498

We will update and assign to you when this is available in the SDK.

**Comment by just-a-node** [comment]
This will be available in `v0.2.7-alpha.0`

**Comment by alexwhte** [comment]
@pjenviri can we create a new column for these? we can call it Error Status. it's a separate field than xcall status

**Comment by just-a-node** [comment]
@alexwhte Auth'd calls will have `Error Status = ExecutionError` even after they reconcile. This is technically correct but if we show it in the UI it might be confusing to a user to see both `Status = Success` and 
`Error Status = ExecutionError`. 

I suggest we have the UI do something like check if the transaction is `XCall Status == CompletedSlow` AND `Error Status == ExecutionError` then change `Error Status == AuthenticationCheck`.


![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/1600fb7e-f5fc-47dd-b4fd-f9259403de55)

**Comment by just-a-node** [comment]
@pjenviri The column filters for Xcall Status and Error Status are combined and the default "Any" selection make it look like a filter for Xcall Status only until you click it.

Could we separate out the filters?

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/08f339cf-e34a-45f8-aebd-405f2a1e57c3)

**Comment by just-a-node** [comment]
Okay actually let's just show no error status if it completedFast/Slow since this field should indicate current error.
