### ISSUE TITLE
Router-executor revert errors not bubbled up to users

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3433]
**Describe the bug**
Router-executor revert errors not bubbled up to users.

**To Reproduce**
1. Send a transfer that will fail in slow path, due to slippage error.
2. Notice error seen in Router-executor is not seen on UI

**Additional context**
Router-executor should send to sequencer even on errors, especially in the case of relayer fee or slippage errors, so that sequencer can parse the revert, and update transfer error status on carto db, so that the execution error is user visible.

**Comment by sanchaymittal** [comment]
Proposed solution:
- Don't run the estimate on the router side.
- Send bids from router to sequencer
- At sequencer, if the selected bid from the auction estimate fails;
  - if it errors, log the error at DB & run the auction again to select a new bid.
  - else if `Error` is related to bump slippage or relayer fee exponentially bump the time to run the auction for the transfer.
  - Also mark the bid with the error it fails at the cache.
- Stop running the cycle for all the bids before we run the auction, that just increases the computation(not sure if we are doing this though)
