### ISSUE TITLE
Run integration tests using Harbor SDK

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3434]
## Problem
Integration tests are not using Harbor SDK to run tests.
E2E tests right now are very basic.

## Proposed Solution
Upgrade current e2e test infra to use test infra setup by Harbor
- [x] Configure testnet
- [x] Bring up (or reconnect with) testnet as part of integration test bringup
- [ ] Implement basic xcall e2e test as a test scenario
- [ ] Merge Harbor PR to make testnet builds part of CI 

## Acceptance Criteria
- [ ] Testnet on Harbor comes up successfully
- [ ] Integration test scenarios are run on the testnet

**Comment by alexwhte** [comment]
Blocked, @jakekidd follow up with @preethamr
