### ISSUE TITLE
Subgraph checkpoints for cartographer queries won't work at scale

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3437]
**Describe the bug**
In a lot of the cartographer checkpoints, we are relying on timestamp. However if we have multiple transactions in the same block, they will have the same timestamp. This is a problem because we could miss events.

**To Reproduce**
Not reproducible yet, but if we reach high high scale, it will happen.

**Additional context**
The main solution for this is to use substreams.

**Comment by liu-zhipeng** [comment]
Yes. correct. Just in case of there are more than 100 events in the same block. because the default limit of the graph-client is 100. and we didn't specify `first` option while querying.  oh, right! in this case poller can't go forwards!. Otherwise I believe it will not miss eny events. because next polling includes previous max timestamp as well.

```typescript
return `${prefix}_swap_${addOrRemove === "add" ? "stableSwapAddLiquidityEvents" : "stableSwapRemoveLiquidityEvents"}(
    where: {
      timestamp_gte: ${fromTimestamp},
      ${maxBlockNumber ? `, blockNumber_lte: ${maxBlockNumber}` : ""}
    },
    orderBy: timestamp,
    orderDirection: ${orderDirection}

```

**Comment by rhlsthrm** [comment]
Not even just 100 events in the same block. Think about the case where you get 99 events from previous blocks, then the single block has 2 events (definitely possible with high transfer volume). Then one of these will be missed and the next iteration would skip one.

**Comment by rhlsthrm** [comment]
But don't we skip the current checkpoint? Or it includes it and gets duplicate events?

**Comment by liu-zhipeng** [comment]
I took around all queries. All of them include the previous max block.

**Comment by rhlsthrm** [comment]
OK that's good in the sense that we don't lose events except in the case you bring up, but that's bad that we process duplicate events and need to always think about that case.

**Comment by liu-zhipeng** [comment]
Yep, that is good for not missing events, but I might cause some other bad things, for example calculating sum or count ...

**Comment by alexwhte** [comment]
Order by transaction id within
use secondary ordering mechanism of transfer id

**Comment by rhlsthrm** [comment]
Testing on local, ready by EoD.

**Comment by rhlsthrm** [comment]
Works without Linea, waiting on Linea to get subgraph updated.

**Comment by rhlsthrm** [comment]
Linea subgraph deployed, looking good, need to deploy Graph mainnet decentralized subgraphs, and update all Bware backups. Merge to testnet in meantime.
