### ISSUE TITLE
Code 429 swap error. 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3438]
**Describe the bug**
<img width="451" alt="image" src="https://user-images.githubusercontent.com/74738120/217464623-58645f3e-9c30-49c5-b5a4-0a6305426147.png">
upd: same with usdc opti pool. 

**Additional context**
[bridge.connext.network-1675841828523.log](https://github.com/connext/monorepo/files/10682981/bridge.connext.network-1675841828523.log)

**Comment by alexwhte** [comment]
@coinhippo i cant replicate this but can you see the error from the code and logging?

**Comment by pjenviri** [comment]
@alexwhte error 429 is the RPC rate limit on the user's wallet. I don't think we can do anything about this.
