### ISSUE TITLE
Sequencer error: value "2212733696" is out of range for type integer

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3443]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/2e5ead7e-17ed-4913-b30b-a47370882aa6)

**To Reproduce**
1. Go to DataDog
2. Look at sequencer logs

**Additional context**

**Comment by LayneHaber** [comment]
likely from backoff being incremented. pushed hotfix to prod here: https://github.com/connext/monorepo/commit/006433a7ed929d2106eb87d27b658b89e851c47a

but still seeing the error on datadog
