### ISSUE TITLE
Sent nextUSDC, transfers show sent USDC

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3444]
**Describe the bug**

Sent nextUSDC, UI shows sent USDC.

Transfer: https://connextscan.io/tx/0x5d51588b61d7442e1e4aed32c1237683c9a2c993e89b468122c061c66e5931d2

Send tx: https://polygonscan.com/tx/0x17b4ce31209df70c607fb2b65cd7beb46214e65168ad11f8f400840f8475b735

**To Reproduce**
1. Send with nextUSDC
2. See transfers sidebar and connextscan both show sent USDC

**Additional context**

This tx is Gnosis [nextUSDC] -> Arbitrum [nextUSDC] but explorer shows USDC sent on Gnosis: https://connextscan.io/tx/0x82a283ccaff18524e246f78422c33ebd585d82f761fbac43315edc12a5abb685
- `origin_transacting_asset` in DB is incorrect:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/16638982/220745489-ea18a710-4f61-48e3-b5f9-97da755b0539.png">

- `destination_transacting_asset` in DB is incorrect too (but somehow showing nextUSDC in explorer):

<img width="642" alt="image" src="https://user-images.githubusercontent.com/16638982/220747425-f31287d2-ea97-4149-b022-9e629ec9bfc5.png">

Another example tx for Arbitrum [WETH] -> Polygon [nextWETH]: https://connextscan.io/tx/0xaa58bb123fc8c5eaa2e57615a18b4dc4ff122ca5bd60b96e2288c4f4df361693
- For this one, origin side is correct for everything bc it's sending adopted. But in DB, `destination_transactin_asset` is still wrong.

**Comment by pjenviri** [comment]
we use the value in `origin_transacting_asset`
![Screenshot_2566-02-10_at_01.02.40.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/ee209297-cd45-4012-aaca-3148686cfbf1)
