### ISSUE TITLE
Update xapp-starter contracts

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3455]
## Background

Review example contracts and improve tests. 
- use mocks 
- add domain references into test helpers
- add foundry scripts for running examples

**Comment by rhlsthrm** [comment]
One thing we should do is move (duplicate) the contracts you need imported from monorepo into its own repo so that the forge installation is super lightweight and we don't need the entire monorepo. Also this should be in docs.

**Comment by just-a-node** [comment]
Will handle separating out interfaces into its own module in #3457
