### ISSUE TITLE
Export an interface-only module so it's easier to dev with

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3457]
When importing Connext modules, you are forced to import 60+ contracts. We should create a repo to export only the core contracts needed for integration

**Comment by just-a-node** [comment]
Export only what needs to be imported for contracts. Maybe new interface with needed functions.

Library modifier for auth? Abstract contract for integrators to inherit easily.

Forge installable npm package (rn needs to grab the whole monorepo).

Connext
- monorepo
-connext-interfaces

**Comment by rhlsthrm** [comment]
This sounds good to me!

**Comment by ArjunBhuptani** [comment]
Looks good, should also potentially include a Mock.sol (talk to Derby Finance team as they have already written this)

**Comment by just-a-node** [comment]
Closing this out as `@connext/interfaces v1.0.0` is set up now.

Extracting abstract patterns into #3638 and mocks into #3640.
