### ISSUE TITLE
nextUSDC transfer marked as USDC

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3459]
**Describe the bug**
A transfer originating with nextUSDC was flagged by a user as showing up in the explorer as USDC.

**To Reproduce**
1. Go to https://connextscan.io/tx/0xf8237a737b23b8571b7c4a47b464b2f44edeca9c390bd233d27ad5dc589e5c11
2. See that it says USDC.
3. Click on xcall link. View that transfer was actually made using nextUSDC.

**Additional context**

**Comment by pjenviri** [comment]
we use the value in `origin_transacting_asset`. could you verify whether it is the correct value?

![Screenshot_2566-02-10_at_01.02.40.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/82accc5d-4bac-4d49-bd54-0d048daef5d2)

**Comment by rhlsthrm** [comment]
Duplicate of #3444
