### ISSUE TITLE
In the pools page, specify that the APR comes from organic fees

### ISSUE THREAD

**Issue by massimol** [connext/monorepo#3463]
In the section for LPing, add a note (maybe a small ?  near APR) that says that APR comes from organic fees.

People are confused whether they are farming $NEXT or not (srouce: DIscord)

**Comment by alexwhte** [comment]
Add tooltip that says "Returns from 0.04% user swap fees"

**Comment by alexwhte** [comment]
instead of 'Returns' please say 'Yield'
