### ISSUE TITLE
Swapping in the underweighted asset showing negative price impact 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3465]
**Describe the bug**
I believe this should be a favorable price impact. The Amount of nextUSDC I put to swap is less than the difference in weighting

![image](https://user-images.githubusercontent.com/37959170/217959998-f5139e65-773c-4ce8-8edd-21f31567d5f2.png)

**Comment by alexwhte** [comment]
logs example https://bscscan.com/tx/0x86d2e7e4f402df6c1a9303c87b1948fc547ea8c710a4e1f92eab89f5d3d092af

**Comment by liu-zhipeng** [comment]
![image](https://user-images.githubusercontent.com/57480598/218767573-1fba599d-b0f6-40d5-be85-b9dfd11df86f.png)
![image](https://user-images.githubusercontent.com/57480598/218767616-3fc1d003-1b7c-48d6-9720-4c078bf1f429.png)

**Comment by liu-zhipeng** [comment]
already fixed?

**Comment by liu-zhipeng** [comment]
https://lab.miguelmota.com/stableswap-curve-example/?hide-fork-button

**Comment by liu-zhipeng** [comment]
That might be due to the fee percentage of the swap. Let me simulate the result

**Comment by liu-zhipeng** [comment]
![image](https://user-images.githubusercontent.com/57480598/218905995-09102ea2-64a4-427a-9465-b79119ee1581.png)

**Comment by liu-zhipeng** [comment]
Token A: 144k, Token B: 156K, A : 200, Fee: 0.004%
Token A 1000 -> Token B 999.95 - negative price impact

**Comment by liu-zhipeng** [comment]
![image](https://user-images.githubusercontent.com/57480598/218907795-9fccd099-5855-4860-9f39-a10c978459ba.png)

Token A: 144k, Token B: 156K, A : 200, Fee: 0%
Token A 1000 -> Token B 1000.05 - positive price impact

**Comment by liu-zhipeng** [comment]
So above calculation is correct, and we can close this issue! @alexwhte
