### ISSUE TITLE
Disable public access to Cartographer to avoid DDoS

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3466]
## Problem
 Also as a security and performance concern (to avoid PostgreSQL's DDoS) I'd better disable public access to the Cartographer and enabled IP whitelist for it.

## Proposed Solution
We have public read-only version of our cartographer postgrest API but this doesnt address it fully. you could still DDoS the carto with read queries. i think we need a read replica or some other db cache mechanism

**Comment by preethamr** [comment]
We now have a read replica.
