### ISSUE TITLE
invalid date in explorer 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3476]
I think it's trying to pull from tomorrow's date

![image](https://user-images.githubusercontent.com/37959170/218116814-08e2bdec-8537-41b3-9bd1-524b41c580c3.png)

![image](https://user-images.githubusercontent.com/37959170/218116934-a560f65b-425a-4ec0-877e-7b66cac47713.png)

**Comment by pjenviri** [comment]
There are null values in the response data. Filtered them ou![Screenshot_2566-02-10_at_22.20.58.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/70246ede-3b55-4e96-841f-d3e951fdf3da)t.
