### ISSUE TITLE
Slippage errors not accurately captured

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3489]
**Describe the bug**
Transfer: https://connextscan.io/tx/0xc1828c7570c0126cec7800857387057e38cf30b568dd00e1776899eb9e2ce5b0 failing due to slippage but stored as `ExecutionError` in db

**Comment by LayneHaber** [comment]
simulation in tenderly: https://dashboard.tenderly.co/lhaber/project/simulator/d8a669b2-cc3c-4c04-9093-8d84a0db7d7c/debugger?trace=0.0.0.0

**Comment by rhlsthrm** [comment]
This should be fixed with latest updates.
