### ISSUE TITLE
ETH transfer to destination shows WETH at explorer

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3490]
**Describe the bug**
When the user selects native ETH to receive in chains like Arbitrum, Optimism, Ethereum, they end up getting WETH.

**Additional context**
https://discord.com/channels/454734546869551114/1073505315515023381/1073505467101360180 - first case
https://discord.com/channels/454734546869551114/1073887031308075058/1073887785263579166 - second case

**Comment by sanchaymittal** [comment]
it sent ETH to user wallet, it just shows WETH on explorer.

**Comment by pjenviri** [comment]
@sanchaymittal We're currently using the transacting asset. How to know whether it is WETH or ETH?

**Comment by pjenviri** [comment]
@sanchaymittal do you have any idea on this?

**Comment by just-a-node** [comment]
`transacting_asset` alone won't be able to differentiate between ETH/WETH as the "final delivered asset" for users. I think you'll have to check if the `xcall` params included an `Unwrapper` contract as the `to` address.

**Comment by pjenviri** [comment]
@just-a-node Can you please provide/point me to the list of contracts for each chain/network?

**Comment by rhlsthrm** [comment]
On each chain there is an Unwrapper contract. For example, here for BNB: https://github.com/connext/monorepo/blob/main/packages/deployments/contracts/deployments/bnb/Unwrapper.json

**Comment by pjenviri** [comment]
pushed it on testnet. (will need to upgrade the SDK version before rolling it out on mainnet)

**Comment by sanchaymittal** [comment]
verified and looking good
