### ISSUE TITLE
Transfer data is being updated for old transfer

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3492]
**Describe the bug**
Transfer ID 0x7e5f0712a2f25b9160439fdd05be3b212e65f7ae5a03980947be1ce576ae4869 keeps changing slippage back to 300 even though it was manually set to 100 in the DB. Since the checkpoint passed, there should be no further updates on this transfer. 

Need to check on the checkpoint logic and make sure we are properly setting the checkpoint.

**Comment by rhlsthrm** [comment]
In DB:
`destination_reconcile_timestamp_6778479` - `1676203740`

In subgraph:
```
query MyQuery {
  destinationTransfer(
    id: "0x7e5f0712a2f25b9160439fdd05be3b212e65f7ae5a03980947be1ce576ae4869"
  ) {
    slippage
    status
    reconciledTimestamp
  }
}

{
  "data": {
    "destinationTransfer": {
      "slippage": null,
      "status": "Reconciled",
      "reconciledTimestamp": "1676061685"
    }
  }
}
```

**Comment by rhlsthrm** [comment]
Checkpoint is clearly ahead of `reconciledTimestamp` so something weird is going on.

**Comment by rhlsthrm** [comment]
On the origin side, the checkpoint nonce is way ahead of the transfer nonce as well.

**Comment by rhlsthrm** [comment]
Suggestion: Log and verify all subgraph queries to ensure we are properly using checkpoints.

**Comment by preethamr** [comment]
This is not reproducible in local.
