### ISSUE TITLE
processFromRoot should only process latest root message

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3497]
## Problem
_What problem are we solving and why does it matter, ser?_ 
If there are multiple root messages from the same domain, they all get processed. These are EXPENSIVE txs and we need to cut down on them.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] In each processFromRoot loop, check if there are multiple messages for a domain.
- [ ] Only process the latest indexed message.
- [ ] Mark the older ones as processed.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] If more than 1 message for a domain needs to be processed, only the latest is processed and the others are marked as processed = true in the database.

**Comment by wanglonghong** [comment]
I like this idea. processFromRoot is really EXPENSIVE between all types of transfers. I also want to jump in here
