### ISSUE TITLE
Call to action for relayerFee shows ExecutionError instead

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3504]
**Describe the bug**

This is for a testnet txn: https://testnet.connextscan.io/tx/0xe678f5823a03062e7aba285fd4ada655b4363a38d743a7d617bceac4c9697471?src=search

DD logs show relayer fee error: 
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/74ae1237-9d15-4d1e-a81c-4255da630cf5)

But UI shows this empty CTA:
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/2b805abc-ef15-4cbc-8c74-9a7c0f225d25)

**To Reproduce**
1. Send a transfer with 0 relayerFee
2. See the incorrect CTA

**Additional context**

**Comment by pjenviri** [comment]
@just-a-node @alexwhte, the UI never handled the `ExecutionError` before. So how should we handle it when getting the error status?

![Screenshot_2566-02-14_at_11.55.50.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/c8d81fcb-80c0-48c2-b94e-9e6405fa1ba8)

https://postgrest.testnet.connext.ninja/transfers?transfer_id=eq.0xe678f5823a03062e7aba285fd4ada655b4363a38d743a7d617bceac4c9697471&limit=10&offset=0&order=xcall_timestamp.desc&select=transfer_id,nonce,to,call_data,origin_domain,canonical_domain,canonical_id,destination_domain,bridged_amt,normalized_in,origin_sender,origin_chain,origin_transacting_asset,origin_transacting_amount,origin_bridged_asset,origin_bridged_amount,xcall_caller,xcall_transaction_hash,xcall_timestamp,xcall_gas_price,xcall_gas_limit,xcall_block_number,xcall_tx_origin,destination_chain,receive_local,status,routers,delegate,slippage,destination_transacting_asset,destination_transacting_amount,destination_local_asset,destination_local_amount,execute_caller,execute_transaction_hash,execute_timestamp,execute_gas_price,execute_gas_limit,execute_block_number,execute_origin_sender,execute_tx_origin,reconcile_caller,reconcile_transaction_hash,reconcile_timestamp,reconcile_gas_price,reconcile_gas_limit,reconcile_block_number,reconcile_tx_origin,relayer_fee,error_status

**Comment by alexwhte** [comment]
Why is this not a relayer fee error? @connext

**Comment by wanglonghong** [comment]
[{"transfer_id":"0xe678f5823a03062e7aba285fd4ada655b4363a38d743a7d617bceac4c9697471","nonce":1070,"to":"0x3b7352c9c9b0f28fd3b4fa4464f2bd48491a0afa","call_data":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001970696e67496e6372656d656e742073616d706c65207465787400000000000000","origin_domain":"1735353714","canonical_domain":"1735353714","canonical_id":"0x0000000000000000000000007ea6ea49b0b0ae9c5db7907d139d9cd3439862a1","destination_domain":"9991","bridged_amt":"1000500300000000000","normalized_in":"1000500300000000000","origin_sender":"0x2139eafdd29e812ce29512a4ffa0652f831bb030","origin_chain":"5","origin_transacting_asset":"0x7ea6ea49b0b0ae9c5db7907d139d9cd3439862a1","origin_transacting_amount":"1000500300000000000","origin_bridged_asset":"0x7ea6ea49b0b0ae9c5db7907d139d9cd3439862a1","origin_bridged_amount":"1000500300000000000","xcall_caller":"0x2139eafdd29e812ce29512a4ffa0652f831bb030","xcall_transaction_hash":"0x78544ae00e140a4811c24a24c48052a8b10aa397a7ec7f1cf4df040992b61efb","xcall_timestamp":1676234976,"xcall_gas_price":"2500964264","xcall_gas_limit":"298865","xcall_block_number":8481110,"xcall_tx_origin":"0xbfd232cebe066d048bdd042d285cc7924171323f","destination_chain":"80001","receive_local":null,"status":"Reconciled","routers":[],"delegate":"0x2139eafdd29e812ce29512a4ffa0652f831bb030","slippage":0,"destination_transacting_asset":null,"destination_transacting_amount":null,"destination_local_asset":"0xedb95d8037f769b72aaab41deec92903a98c9e16","destination_local_amount":null,"execute_caller":null,"execute_transaction_hash":null,"execute_timestamp":null,"execute_gas_price":null,"execute_gas_limit":null,"execute_block_number":null,"execute_origin_sender":null,"execute_tx_origin":null,"reconcile_caller":"0x8d2690fdc417a231d6d919f9cb1f2fb317b36af5","reconcile_transaction_hash":"0x69e17c6995b8a823c63d30c5ee9a8a255aef94e7523289e814c3b9c7dcd827cc","reconcile_timestamp":1676237247,"reconcile_gas_price":"60945953010","reconcile_gas_limit":"6000000","reconcile_block_number":31988051,"reconcile_tx_origin":"0x94d39db37b6f18fdea7c6d730e4e6502c7d27700","relayer_fee":"0","error_status":"LowRelayerFee"}]

**Comment by wanglonghong** [comment]
It says "error_status":"LowRelayerFee"

**Comment by rhlsthrm** [comment]
@wanglonghong any need to reopen this? Seems like it's as expected?

**Comment by wanglonghong** [comment]
> @wanglonghong any need to reopen this? Seems like it's as expected?

yes its as expected. but I wanted for the confirmation of @just-a-node.
