### ISSUE TITLE
As a explorer user, I want to see the more info for callData based transfer.

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3507]
## Problem
_What problem are we solving and why does it matter, ser?_ 

- CallData-based transfer being marked on explorer using custom target and source contract addresses
- for NFT, and other use cases
- helpful for monitoring, debugging, UX, etc

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] create a new JSON or dir at ChainData, And whitelist the source and target contract address.
```json
{
"domainId": { "source": {}, "midway": {}, "target": {} },
}
```
- [ ] add the above JSON reference to Carto into transfers view.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens

**Comment by alexwhte** [comment]
@sanchaymittal is this ready for coinhippo? or needs our resources
