### ISSUE TITLE
DAO workshop for gnosis

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3512]
## Background

Create a follow-up workshop to https://www.youtube.com/watch?v=BsDWR2lCk-E&list=PLtEvcs3JL22PKZu0O53Mmp0p-21OxlYoa.

Ideas:
https://www.notion.so/connext/DAO-Workshop-ft-Gnosis-Builders-External-46017139faf949318b0da802d675298c

**Comment by alexwhte** [comment]
Not urgent but potential good first thing for Prathmesh to take on

**Comment by LayneHaber** [comment]
stale, closing
