### ISSUE TITLE
Error when starting up carto in local

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3514]
Carto startup in local throws a non-fatal error

```{"level":"ERROR","time":1676418621928,"pid":58294,"hostname":"studioPR.local","name":"cartographer-transfers","requestContext":{"id":"rEunpb69REi+9FNH4mpjmA/2","origin":"Logger.print"},"methodContext":{"id":"rEunpb69REi+9FNH4mpjmA/3","name":"Logger.print"},"msg":"exec error: Error: Command failed: dbmate --url postgres://postgres:qwerty@localhost:5433/connext?sslmode=disable -d packages/adapters/database/db/migrations up\nError: could not find migrations directory `packages/adapters/database/db/migrations`\n"}```

**To Reproduce**
1. Run carto locally

**Additional context**
This works fine in live env

**Comment by wanglonghong** [comment]
This looks like path issue. To make it working on both live and local, we can use relative path.
