### ISSUE TITLE
Improve search UI

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3521]
## Background

The search UI can be vastly improved. If you look at platforms like Tenderly (https://dashboard.tenderly.co), they pop up a large modal when you click the search dialog and it contains a lot of cool information and helpful dialog:

![image.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/20e0a640-055d-40b7-9a56-987f6b588b90)

We iterate on the contents later, but for now autocompleting pasted addresses or tx hashes (or chain names) should indicate to the user if they are going to an address, transfer, router, etc.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Search is improved by using a modal.

**Comment by pjenviri** [comment]
Can you give us more examples? We have no idea how to start with. The attached image shows the recent search.

**Comment by rhlsthrm** [comment]
The first step would be a very simple UI change. I would say:
- User focuses into search box on the corner.
- Large modal pops up in the middle like the screenshot.
- Don't need to populate recent searches, can just say "Search for wallet address, transaction hash, transferId, router address, chain (etc)."
- Then when user for example searches a wallet address, it will give an indication that it is a wallet address and prompt them to click it to go to the address. For example when i search my wallet in Tenderly: <img width="917" alt="Screenshot 2023-03-15 at 13 57 11" src="https://user-images.githubusercontent.com/11512787/225274139-6904c55f-73cd-4004-8766-89a4991b5a56.png">
- This is a minor change in functionality but a major UX improvement IMO, and sets us up to be able to create more advanced search options in the future. 

The explorer will be a very important analytics tool for our network so I want the UX to be as slick as possible.

**Comment by alexwhte** [comment]
@pjenviri does the latest comment from Rahul sufficient to start testing? I will spec out more from here

**Comment by pjenviri** [comment]
updated in this PR: https://github.com/CoinHippo-Labs/connextscan-ui/pull/68

**Comment by alexwhte** [comment]
can you please move this to prod?

**Comment by pjenviri** [comment]
merged and deployed to prod.

**Comment by rhlsthrm** [comment]
Closing, can iterate.
