### ISSUE TITLE
Reducing the frequency of slow path based on gas fee and other factors

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3531]
## Problem
_What problem are we solving and why does it matter, ser?_ 

Slow path frequency for `processFromRoot` and `propagate` can be reduced or increased based on factors like volume, transfers, GasFee(On Mainnet) etc.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens

**Comment by LayneHaber** [comment]
out of scope
