### ISSUE TITLE
chainData link fails at some geolocations & internet service provider 

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3532]
## Problem
_What problem are we solving and why does it matter, ser?_ 

chainData link from GitHub fails at some geolocations. 
- This happened to me personally in India while using Jio(an internet provider). Replicated by eng at socket too.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Hosting a ci/cd steam and hosting the file at lambda.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens

**Comment by wanglonghong** [comment]
It also happened to me rarely. I guess its kind of network issue of the end user. That user with a bad internet provider will also have a problem even if we move it to lambda or somewhere.
I am not sure what's the right solution for this issue.

**Comment by wanglonghong** [comment]
but yeah, i think its a low priority task
