### ISSUE TITLE
503 Error to staging relayer

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3535]
**Describe the bug**

New 503 error seen:
https://app.datadoghq.com/logs?query=%40requestContext.transferId%3A0xcd474adb00cd013f78c859bfb921ee37d21865b1c96e56efe73e9eebda74714f&cols=%40params.transferId%2C%40requestContext.origin&event=AQAAAYZWaS55FPVKMwAAAABBWVpXYVM4Y0FBRGU0TnBXaGdRTXN3QU0&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1676402999910&to_ts=1676489399910&live=true

Snippets of the error:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/16638982/219133627-2b1cf5ea-9d3a-47f2-8ccf-584573779d36.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/16638982/219133680-ac9fb180-5a4d-43f1-89fe-ef5f83126e06.png">

**To Reproduce**
1. Transfer created for Goerli -> Opt-Goerli using local and receiving adopted WETH. Slippage set to 0.
2. See ex transfer: https://staging.testnet.connextscan.io/tx/0x76fb71fc852dd2efdfcf948fb55678fc379eb9c124ce2babe7e3b0212fbf0227?src=search
3. Check DD logs for this transfer 

**Additional context**

**Comment by just-a-node** [comment]
In some cases, it's a 504:
https://app.datadoghq.com/logs?query=%40requestContext.transferId%3A0x9faedcd69d857ad09d2c4d85186e56370a39372877b057c2fac81e8198de49b8&cols=%40params.transferId%2C%40requestContext.origin&event=AQAAAYZW58EMpjHUuQAAAABBWVpXNThMa0FBQVNqRUNmUXlJdXFBQUE&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1676495270000&to_ts=1676495275000&live=false

<img width="540" alt="image" src="https://user-images.githubusercontent.com/16638982/219215476-08e87226-93c9-40ea-a2af-955f163355b9.png">

<img width="620" alt="image" src="https://user-images.githubusercontent.com/16638982/219215505-84a329e7-0d24-4387-8334-42e77fa9cd33.png">

**Comment by rhlsthrm** [comment]
![image](https://user-images.githubusercontent.com/11512787/219273080-74e18b8d-a404-461a-a9a0-27543b1203b8.png)

Seeing this on relayer.

**Comment by preethamr** [comment]
Not seen anymore
