### ISSUE TITLE
Establish patterns for cross chain tokens

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3541]
We need to provide standard patterns for building cross-chain tokens.

Scenarios:

1) Token can be changed by the team
 
- this is the easiest path: register token and give minting rights to Connext bridge

2) Token can't be changed by the team

- token is migrated using default canonical bridge flow
- Connext cannot mint and team would have to decide which token is considered "official"
  - if canonical bridge token is official, then we need a nextAsset/Asset pool
  - if Connext token is official, canonical bridge must be able to register external assets (e.g. Optimism allows you to add custom bridge: https://community.optimism.io/docs/guides/bridge-dev/) 

3) Token not yet deployed on other chains - should just deploy by minting through our bridge

**Comment by just-a-node** [comment]
Follow up with Liquity on this

**Comment by LayneHaber** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/20) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/40) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/39) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by just-a-node** [comment]
Dupe of #3979
