### ISSUE TITLE
Show Pool TVL and volume as a time series 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3546]
Please change to review in staging. Starting with one pool is fine to prototype
For all pools https://bridge.connext.network/pool/USDC-on-binance

Show TVL in a time-series 
https://postgrest.mainnet.connext.ninja/daily_swap_tvl

Allow user to toggle to volume
https://postgrest.mainnet.connext.ninja/daily_swap_volume

We do not need a date toggle, you can show it for all time to start. 

EXAMPLE: 
Balancer ![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/aa68df46-5bdc-4bc0-8bec-a4d6cca18dd6)
https://app.balancer.fi/#/ethereum/pool/0x5c6ee304399dbdb9c8ef030ab642b10820db8f56000200000000000000000014

This was also in the original Figma 
https://www.figma.com/file/Z3iq2LOM12K1BeSGQc1Dal/Connext-Concept?node-id=0%3A1&t=yw2M1KZ8HHDxCzP9-0

**Comment by pjenviri** [comment]
https://bridge.connext.network/pool/USDC-on-binance?mode=test

**Comment by alexwhte** [comment]
This is great! Ship it
