### ISSUE TITLE
Locally testing interface function calls [Derby] 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3552]
## Problem
We should make this easier for devs

> We have set up a local test setup where we Mocked the "Connext.sol" contract. The goal was that we can just use the exact same interfaces if we deploy to test/mainnet but can test all function calls locally.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Subtask 1

**Comment by ArjunBhuptani** [comment]
Potentially duplicate #3640

**Comment by just-a-node** [comment]
Closed as dupe
