### ISSUE TITLE
Follow up on transfer_volume / price feeds [Token Terminal]

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3553]
**Describe the bug**
Filing off of conversation 'Token Terminal <> Connext' . This is a placeholder to ensure we look into their question and respond. It may be enough to confirm what price feeds or timing we use in Explorer. Please reach out to discuss if complexity/scope is expected to be a lot higher to investigate 

> On the screenshot below you can find our transfer volume values from the week of 2023-02-05 - 2023-02-11. Most of the values benchmarked with your analytics page (difference between 0-5% caused by the different price feeds). 
> 
> However, on Arbitrum the difference was a bit larger of around 7%. Would be great to understand whether that is also caused by the price feeds. [Here](https://docs.google.com/spreadsheets/d/1nU_BfrUP69UyOc7BZ-KkmShGwehVFOGVaG1Pjlx34vU/edit#gid=1728913204) you can see a break down of the Arbitrum transfer volumes during that week. Are you able to tell where the biggest difference comes from? Once this issue has been sorted, we are happy to publish the updated values!

![telegram-cloud-photo-size-4-6017228360150793388-x](https://user-images.githubusercontent.com/37959170/220162584-e39e384f-3896-42f5-a240-c41d2053a42a.jpg)

**Comment by just-a-node** [comment]
CH: can we double check the aggregation for transfer volume? based on some external analysis, our numbers are slightly off.

**Comment by pjenviri** [comment]
@just-a-node, if you meant the 7-day volume of each pool, we get it from getYieldData 7 day and then multiply it by the current token price. Please suggest if there's something off in the calculation logic.

**Comment by pjenviri** [comment]
@alexwhte @just-a-node  sorry, I reread it. We use the data from https://postgrest.mainnet.connext.ninja/daily_transfer_volume and then multiply by the current price. So, that would be the root cause. However, could you add a new data field: `token_price`, that indicates the price for each day? So, we can use it for multiplying. It's not practical to let UI always get the token price and calculate it each time it loads.

**Comment by just-a-node** [comment]
Hey PJ what price feed are you using now?

**Comment by alexwhte** [comment]
We should be able to use a public API for pricing (assuming we use one in other parts of the UI)

**Comment by pjenviri** [comment]
@alexwhte , we don't collect the daily price information of each asset, and we don't think it'd benefit from doing it on the frontend. In our opinion, it should be done in the backend. Any frontend must be able to retrieve this info and visualize it on their UI, not only exclusively for only one frontend.

**Comment by pjenviri** [comment]
Hey @just-a-node, we get real-time asset prices from CoinGecko API, but it would be better if we could get it from the SDK.

**Comment by alexwhte** [comment]
will file separate enhancement request for pricing in API/SDK for discussion
