### ISSUE TITLE
ETL carto data into BigQuery data warehouse

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3565]
## Problem
Data in cartographer DB is not available in BigQuery, to serve analytics and dashboard type use-cases

## Proposed Solution
- [x] As a first step, ETL manually to ensure it serves the need
- [x] Implement an ETL pipeline that automates the manual steps
- [x] Host this on AWS with the required credentials, setup to run periodically

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [x] Data is available for queries on BigQuery
- [x] Updates to data overtime are also available, and queries show new data.

**Comment by alexwhte** [comment]
`then we can script the ETL, and run it reliably as a service, prob a 13 point task if this was sprint poker`

**Comment by preethamr** [comment]
Made some progress on this setting this up, more steps to go.

https://cloud.google.com/datastream/docs/quickstart-replication-to-bigquery#sourceCP4PostgresDb

80% through the setup realized, I need to make some changes to DB itself.
Researching the implications of this.

**Comment by preethamr** [comment]
Completed steps for staging.
Want to test this out in staging, and gather any further changes, before I do the same or mainnet.

https://console.cloud.google.com/bigquery?project=mainnet-bigq&ws=!1m5!1m4!4m3!1smainnet-bigq!2sstaging_public!3stransfers

@alexwhte and @mchammond should have access to this, added them as admin on the big query.

**Comment by preethamr** [comment]
Mainnet Big Query is live !

https://console.cloud.google.com/bigquery?project=mainnet-bigq&ws=!1m5!1m4!4m3!1smainnet-bigq!2spublic!3stransfers
