### ISSUE TITLE
Buggy bump fees UX [ LiFi]

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3568]
Per LiFi, 

We tried to bump it in the UI (which was quite buggy UX: screen turns black, suggested fees are very high), but nothing happens with the transfer.
https://connextscan.io/tx/0x10b611db8bc036318396877d93f756c474abfe974f735ed2f42bc917cc3e0daa

After bumping it myself I saw the application crash
![image](https://user-images.githubusercontent.com/37959170/220638499-6ff3b9b3-74c7-4fbd-9442-5a4d2bd564e9.png)

**Comment by alexwhte** [comment]
Update: We have major bugs at sequencer and cartographer

it's something related to `split` at your end

**Comment by just-a-node** [comment]
Need to follow up on the conversation once this is resolved on sequencer side.

**Comment by alexwhte** [comment]
@just-a-node can you write a summary or any action items here?
we need this out of QA

**Comment by just-a-node** [comment]
We can close this out!
