### ISSUE TITLE
Missing polygon transfer [LiFi]

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3582]
https://polygonscan.com/tx/0x8735122bb46cd43e229f7b4b85d9a8dd073dcc12e590a7d8cf4386f9eb5c6954

Polygon Transaction Hash (Txhash) Details | PolygonScan
Polygon (MATIC) detailed transaction info for txhash 0x8735122bb46cd43e229f7b4b85d9a8dd073dcc12e590a7d8cf4386f9eb5c6954. The transaction status, block confirmation, gas fee, MATIC, and token transfer are shown.

We have another issue with a transfer using NXTP, it does not appear in the explorer and is not executed for 17 Hours, can you please look into that as well:
https://polygonscan.com/tx/0x8735122bb46cd43e229f7b4b85d9a8dd073dcc12e590a7d8cf4386f9eb5c6954

**Comment by wanglonghong** [comment]
![image](https://user-images.githubusercontent.com/30057497/221469319-b627be1f-8608-4ed8-aa24-1b153c19dcb9.png)

I think it was not showing anything because of subgraph sync issue.
