### ISSUE TITLE
Autopopulate ETH not WETH when generating nextWETH from Ethereum

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3584]
When clicking "generate nextWETH by bridging from Ethereum" the UI automatically populates WETH as the sending asset from Ethereum. It's not immediately apparent that native ETH is even supported. I found myself going to a wrapping UI before remembering that we should have this functionality built in. We should start with the ETH field populated as opposed to WETH.

**Comment by just-a-node** [comment]
LGTM
