### ISSUE TITLE
Expose functionality to estimate available fast-path liquidity in SDK

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3585]
Right now, the UI and integrators have to estimate fast-path liquidity simply by querying the total router liquidity on each chain. 

This doesn't actually work because that liquidity may be actively locked up in transfers and forcing users into a slow path flow when they expect a 4 minute transfer is **very** bad UX. This is currently a problem in the bridge UI as well.

We need to add support for figuring out how much fast-path liquidty is _actually_ available for a given route.

**Comment by alexwhte** [comment]
Even if we start with largest router for now it's a good stopgap

**Comment by just-a-node** [comment]
80% solution: look at n largest routers and see if there's avail liq

**Comment by rhlsthrm** [comment]
I think what we should do here is create a new SDK function called `checkRouterLiquidity(domain: string, asset: string)`

This function should query all the routers through the `routers_with_balances` endpoint and apply our splitting logic (which can be updated as we optimize this).

The current logic is to have routers send sigs for `amount`, `amount / 2` and `amount / 4`. So this function will have logic to see if at least 4 routers have 1/4 of the amount.

**Comment by just-a-node** [comment]
Also return time estimate of fast/slow path.

**Comment by just-a-node** [comment]
Keep open for `calculateAmountReceived`
