### ISSUE TITLE
Unable to send transaction "any chain -> gnosis"

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3593]
**Describe the bug**
"Could not detect network" message when pick gnosis chain as destination from any network.

**Additional context**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/74738120/221027501-04ce55f7-ee43-424e-ae24-5abec8834816.png">

**Comment by oswy-cpu** [comment]
[bridge.connext.network-1677185558267.log](https://github.com/connext/monorepo/files/10818393/bridge.connext.network-1677185558267.log)

**Comment by just-a-node** [comment]
Resolved in https://github.com/CoinHippo-Labs/connext-bridge/pull/98
