### ISSUE TITLE
Pool updates (Arjun feedback)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3596]
(2) When on the chain-specific pooling page, the first thing the UI does is prompt you to switch chains to the target pool chain. But this is weird because in many cases you want to actually bridge from Ethereum. Super annoying to change back and forth

--> Dont prompt immediately. Have user do this with the add/remove liquidity button 

(4) Oftentimes, the destination gas fee field will just stay loading for a really long time. It's long enough (>30s) that most people will tab away during that time. When tabbing back, the fee is populated, but may once again refresh. This leads to a frustrating experience where you're just waiting a long time to even be able to send the tx.

--> Do you have any suggestions?

**Comment by pjenviri** [comment]
(2) Adjusted the UI not to show the `switch chain` button immediately if the amount has been filled. Then, if enough amount has been filled but is overweight, the UI shows 2 buttons.
-  1)  the `click here to get next asset`, if the user wants to keep using that amount to add/remove.
-  2)  the `switch chain` button

(4) it would be helpful if the sdk could _memonize_ each paired chain for a short period e.g., 30sec or 1min. (similar to what have done for getPool)

**Comment by alexwhte** [comment]
@alexwhte test today
