### ISSUE TITLE
Chain-specific analytics page shows only router liquidity and lots of unnecessary assets

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3613]
Chain specific pages, (e.g.: https://connextscan.io/arbitrum) don't show user/pooled liquidity and also show LOTS of unnecessary nextAssets.

Low priority.

![image.png](https://images.zenhubusercontent.com/5ab81e2b4b5806bc2bcc4bb1/7c3f9ba0-4120-42a4-bb00-9ed4898979ea)

**Comment by pjenviri** [comment]
added the Pools Liquidity section
![image.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/e60471ea-221a-411b-b1d2-f5f6a6eb0168)

**Comment by alexwhte** [comment]
assignging to think more about visualization in these pages
