### ISSUE TITLE
Add mava into docs

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3621]
Add into head

```
<!-- Mava Widget -->
<script src="https://widget.mava.app" id="MavaWebChat" data-token="ff5a4a8ae57d4369888eaa4f81cfcee411c25ab31fa74d0ac47c105bfd2086a3"></script>
```

**Comment by alexwhte** [comment]
**Complexity: 2**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/31) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 2**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/15) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/27) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/28) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
https://github.com/connext/documentation/blob/main/src/pages/index.jsx#L255
