### ISSUE TITLE
Toggle to slice volume and transfers by asset (vs chain) 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3622]
We saw a big dropoff in volume recently, but realized we dont know if the spike was ETH or USDC
Ideally we can slice by asset. We can start with a toggle to view by chain or by asset

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/37959170/222001707-771570a8-5ca2-4687-bd8c-a844a79ee835.png">

**Comment by pjenviri** [comment]
@alexwhte , we can't do this if there is no daily $ value of each asset provided, as mentioned in https://github.com/connext/monorepo/issues/3553#issuecomment-1469246991.
