### ISSUE TITLE
Miainnet LH sendOutboundRoot errors

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3626]
**Describe the bug**
Miainnet LH sendOutboundRoot errors

<img width="738" alt="image" src="https://user-images.githubusercontent.com/1195648/222043616-8b21f044-7216-42a6-a31e-135a91b303c9.png">

**To Reproduce**
1. https://app.datadoghq.com/logs?query=region%3Aus-east-2%20service%3Alighthouse-sendoutboundroot&cols=host%2Cservice&event=AQAAAYaa7YjffK_UwwAAAABBWWFhN1kyRUFBQjBXT3JkaUZ2Vm1BQUs&index=%2A&messageDisplay=inline&stream_sort=time%2Casc&viz=stream&from_ts=1675722784217&to_ts=1675809184217&live=true

**Additional context**
Found to work in staging-testnet

**Comment by wanglonghong** [comment]
https://github.com/connext/monorepo/pull/3665

fixed with above PR

**Comment by wanglonghong** [comment]
oh my bad. the PR was for bsc sendOutboundRoot task lol

**Comment by wanglonghong** [comment]
Went through the logs on LH sendOutboundRoot task. it seems fixed.
