### ISSUE TITLE
Connextscan/Bridge eternal loading. 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3628]
**Describe the bug**
Bump isn't working now, connextscan search is in eternal loading. Same with route search

**Additional context**
<details>
  <summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/74738120/222114464-e2d2933a-63a8-46da-ac37-c4debf3e749e.png)
![Screenshot 2023-03-01 at 13 29 54](https://user-images.githubusercontent.com/74738120/222114576-a950d083-9d02-43c9-aa9a-950de8574385.png)
![image](https://user-images.githubusercontent.com/74738120/222114642-5d2f1aaa-47b5-431a-af73-883a4e44765d.png)

</details>

---
[bridge.connext.network-1677666835506.log](https://github.com/connext/monorepo/files/10859974/bridge.connext.network-1677666835506.log)

**Comment by oswy-cpu** [comment]
upd bump issue tx: 0x3fc169bfec01f4a6e49bcd3b99a84cfaaf2f72a5dd1a2111ebb183cbed78ea8d

**Comment by wanglonghong** [comment]
should be fixed here https://github.com/connext/monorepo/issues/3630
