### ISSUE TITLE
LowRelayerFee for ANY -> Arbitrum txs

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3630]
**Describe the bug**
RelayerFee tolerance configured on the sequencer is 60%. but sometimes txs from any chain to arbitrum have lowRelayerFee issue. We should figure out why this happens for arbitrum txs.  

**To Reproduce**

https://connextscan.io/tx/0xc2532f5e8d8cfd689a201ad10693a18962f803d2241a59ab06500e4a056e7111

![image](https://user-images.githubusercontent.com/30057497/222135118-d0377e0d-65d0-4178-9a7e-5d08ea289dc4.png)

**Comment by alexwhte** [comment]
@wanglonghong do you have updates from work on this? 

we are seeing Arbitrum fee issues with LiFi integration but havent dug into it yet
