### ISSUE TITLE
Unwrap WETH error

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3633]
**Describe the bug**

Unwrap WETH error: "parseUnits is not defined".

![image](https://user-images.githubusercontent.com/16638982/222208855-19bca568-b3a9-43b6-a468-9bc40fb7469f.png)

**To Reproduce**
1. Go to Optimism WETH pool
2. Try to unwrap WETH 
3. See error

**Comment by just-a-node** [comment]
Not sure if related to the fix but Wrap/unwrap buttons are no longer showing up:

![image](https://user-images.githubusercontent.com/16638982/223322150-520ee0d4-6942-41f3-a9fc-70dfcc7fd1f4.png)

**Comment by alexwhte** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/37959170/223590095-b1db3686-a39c-4e30-aa5b-a3f1db549f01.png">
https://arbiscan.io/tx/0x49dde3b4f68a8c473f47283bba574ca559d9fb52e91499e391e7f95398403346
