### ISSUE TITLE
Create abstract contract for OnlySource authentication

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3638]
## Background

In the `@connext/interfaces` package we want to have an abstract contract that can be inherited by integrators to easily kick-start the implementation of an authenticated receiver.

Currently, examples assume there is only 1 origin sender and origin domain while it would be most useful to support any number of origins. There should probably be a mapping of origins and the registration of those origin values would be set in the constructor and/or through setter functions. 

We need to think through this pattern and determine if prescribing a specific way to register origins is too limiting for integrators.

Non-authed template is being worked on in #3885 (https://github.com/connext/connext-integration/tree/main/contracts/.Template). See if the template pattern here can be extended for auth'd.

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/41) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 5**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/42) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/4) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
update: needs errors to be moved to named errors + other review comments

**Comment by rhlsthrm** [comment]
Updated, ready for re-review.

**Comment by just-a-node** [comment]
https://github.com/connext/connext-integration/pull/3

**Comment by LayneHaber** [comment]
`abstract-auth` ready for rereview
