### ISSUE TITLE
Optimize RPC calls

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3650]
## Background

We are using our hosted Alchemy RPC way too much. We are using 1M requests a day.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

RPC requests on UI are greatly reduced.

## Tasks

The way it should work is:
- Use cartographer for "all chains" view data (it's okay if this is slightly latent).
- When we drill into a specific chain, then we can use the user's wallet RPC to run RPC calls.

**Comment by alexwhte** [comment]
@coinhippo Can you check if the UI is spamming the RPCs or if we have ability to reduce RPC calls, or if it's at SDK layer?
