### ISSUE TITLE
Integrate Keep3r jobs

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3651]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Keep3r has an interesting system where you can pay for keeper jobs through staking tokens rather than paying directly for executions.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Implement Keep3r jobs: https://keep3r-network-v2-gu2ybr7cp-yunoek.vercel.app/docs/tutorials/create-a-job-step-by-step
- [ ] Implement offchain scripts: https://github.com/defi-wonderland/phuture-keeper-scripts/blob/main/src/deposit-manager-job.ts
- [ ] Stake K3PR LP to generate credits.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] `processFromRoot` and `propagate` go through Keep3r network.

**Comment by rhlsthrm** [comment]
Need to make more contract changes. Will have it ready to test on testnet today.

**Comment by rhlsthrm** [comment]
Working on testing on Goerli with DeFi Wonderland.

**Comment by rhlsthrm** [comment]
Deployed new RelayerProxyHub to Goerli and Mainnet. Working on getting keepers up on testnet. Created task #3878 to make our lighthouse a backup.

**Comment by rhlsthrm** [comment]
Keepers already sending transactions on testnet, mainnet, and staging. Next step: Get lighthouse working as backup, merge branch to all environments.

**Comment by liu-zhipeng** [comment]
https://goerli.etherscan.io/tx/0xeac02665fac923a1919056eed2e96030b05b19c26875e9ccff9aa21e5f9e7402

Propagate via Keep3r is not working for some domains.

![image](https://user-images.githubusercontent.com/57480598/228706896-b4c5ef2f-9947-4349-9e15-0e02c57b1f70.png)

I believe that is due to encoded data. It should be bytes32!

**Comment by liu-zhipeng** [comment]
Propagate via LH + gelato works properly after ZkSync L2TxCost issue fixed

**Comment by rhlsthrm** [comment]
> https://goerli.etherscan.io/tx/0xeac02665fac923a1919056eed2e96030b05b19c26875e9ccff9aa21e5f9e7402
> 
> Propagate via Keep3r is not working for some domains.
> 
> ![image](https://user-images.githubusercontent.com/57480598/228706896-b4c5ef2f-9947-4349-9e15-0e02c57b1f70.png)
> 
> I believe that is due to encoded data. It should be bytes32!

We're using this script: https://github.com/connext/connext-keeper-scripts

Can you help debug?

**Comment by alexwhte** [comment]
**Complexity: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/25) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
