### ISSUE TITLE
Incorrect total volume on connextscan

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3654]
**Describe the bug**
Total volume broken on connextscan. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/30057497/222316513-20ae7d9f-a844-4668-afb9-b8f17273c6a9.png)

**Additional context**

**Comment by pjenviri** [comment]
@wanglonghong 
It’s due to the wrong data provided.

https://postgrest.mainnet.connext.ninja/daily_transfer_volume

nextUSDC volume stats wrong decimals
https://www.bscscan.com/token/0x5e7d83da751f4c9694b13af351b30ac108f32c38

**Comment by wanglonghong** [comment]
digging our end. cc: @sanchaymittal

**Comment by wanglonghong** [comment]
it was decimal issue on backend. fixed now
