### ISSUE TITLE
User is given execution error when no valid bids

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3673]
**Describe the bug**
User is given execution error when no valid bids
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/1195648/222832666-fa63a2f8-7cdc-42b2-a951-1519c9e9f123.png">

https://connextscan.io/tx/0x9bc26e5feb92fa8f20ec96ed8870ad3ac78e4a09f268e6718d81626aa6f1a3e4

Sequencer received bid from connext router:
https://app.datadoghq.com/logs?query=region%3Aus-east-2%20%40requestContext.transferId%3A0x9bc26e5feb92fa8f20ec96ed8870ad3ac78e4a09f268e6718d81626aa6f1a3e4&cols=host%2Cservice&event=AQAAAYapSQHVjZZsmAAAAABBWWFwU1FOQUFBQ2RQd3lPdmpPME9BQUI&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1677874855124&to_ts=1677878455124&live=true

But execution errors with:
https://app.datadoghq.com/logs?query=region%3Aus-east-2%20%40requestContext.transferId%3A0x9bc26e5feb92fa8f20ec96ed8870ad3ac78e4a09f268e6718d81626aa6f1a3e4&cols=host%2Cservice&event=AQAAAYapSYJjkMQHqAAAAABBWWFwU1lWT0FBQ3RueHU1MklYVExBQUM&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1677874855124&to_ts=1677878455124&live=true

**To Reproduce**
1. DD https://app.datadoghq.com/logs?query=region%3Aus-east-2%20%40requestContext.transferId%3A0x9bc26e5feb92fa8f20ec96ed8870ad3ac78e4a09f268e6718d81626aa6f1a3e4&cols=host%2Cservice&event=AQAAAYapSYJjkMQHqAAAAABBWWFwU1lWT0FBQ3RueHU1MklYVExBQUM&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1677874855124&to_ts=1677878455124&live=true

**Additional context**

**Comment by alexwhte** [comment]
P2 as we implemented better UI UX for now

**Comment by alexwhte** [comment]
i was wrong about better UX

we need to identify at UI level when NoBidsSent. Per @rhlsthrm this is in DB

need light spec on how to handle at the UI level
