### ISSUE TITLE
Comma-to-dot replacement in UI.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3682]
## Problem
It becomes unclear to users how much they will receive, since they use a dot to separate decimals, and not to separate tens in a number.
i.e. here 20,001 is perceived by the user as 20 USDC, since he used a comma to separate decimals.
![image](https://user-images.githubusercontent.com/74738120/223060867-2290224c-ff75-4ee1-b45d-408482b4bcf6.png)

## Proposed Solution
Add automatic comma-to-point replacement when decimals are separated in the **"you send"** input field (preffered)
_or_
Block the possibility of using a comma by the user in this field.

## Source 
User-problem: https://discord.com/channels/454734546869551114/941007434900721714/1082219996714913853

**Comment by just-a-node** [comment]
Simplest here is to block comma input IMO.

**Comment by pjenviri** [comment]
UI currently doesn't allow comma input.
