### ISSUE TITLE
Problems with the VPN and the country

### ISSUE THREAD

**Issue by doxe1** [connext/monorepo#3684]
**Describe the bug**
The user, when using the Nord VPN with Brave browser, which is directed to the country Switzerland, does not work places and gets this error. But when selecting another country everything works.

Browser version and link: V.1.48.171 - https://brave.com/
VPN: https://nordvpn.com/vpn-site/

![image](https://user-images.githubusercontent.com/84589100/223112940-d645bc88-566d-4b34-b0a9-33b979e7fc1c.png)

**Additional context**
Link on the ticket - https://discord.com/channels/454734546869551114/1082273214471876669.

**Comment by rhlsthrm** [comment]
Possibly related to https://github.com/connext/monorepo/issues/3532
