### ISSUE TITLE
Gnosis failing on forge forks

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3687]
**Describe the bug**
Forking from gnosis mainnet gives this internal forge error:
```  
    ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38,
    (code: -32002, message: No state available for block 0x0ba985b09fec8fd02467a9dbfe0cbd6546a96e897c0576125e17896641b29b8d,
     data: None)) address=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
```
   
where the `0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38` is the `DEFAULT_SENDER` forge address found in `Base.sol`. Need to debug/report to figure out why this is failing.

**To Reproduce**
1. Remove the gnosis-ignoring code from `MotherForker.sol`
2. Run `ywc test:upgrade`

**Additional context**
This has reproduced across multiple block heights and paid / public RPCs

**Comment by alexwhte** [comment]
@LayneHaber moved to backlog please comment if this should be addressed more urgently

**Comment by LayneHaber** [comment]
not urgent

**Comment by LayneHaber** [comment]
still a problem, still not urgent
