### ISSUE TITLE
Update vendor SDKs

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3692]
## Background

We use vendor SDKs in lighthouse, carto, etc from Arbitrum, Optimism, Polygon, etc. We are outdated on some of them and need to update our usage to get to the latest version.

## Definition Of Done

All versions to vendor SDKs are updated.

## Tasks

- [x] Find out which SDKs are used.
- [x] Update SDKs.
- [ ] Verify everything still works.

**Comment by alexwhte** [comment]
Done but waiting on merging because it will have conflicts with Bedroock
Waiting for after Bedrock, and do some testing

**Comment by alexwhte** [comment]
@rhlsthrm what's status of this?

**Comment by rhlsthrm** [comment]
PR is in and approved. Will wait for @LayneHaber to indicate it can be merged.
