### ISSUE TITLE
Data not yet available on hub network 5 from spoke 420

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3695]
**Describe the bug**
Roots from Optimism goerli are not getting processed. ERROR: `Data not yet available on hub network 5 from spoke 420`

https://app.datadoghq.com/logs?query=region%3Aus-west-1%20%40requestContext.transferId%3A0x609a4967c5cf8b6eb0f7d3cc8549930a6dd20fa7e4481fbcbf0e08f2eb39e745&additional_filters=%5B%7B%7D%5D&cols=host%2Cservice&event=AQAAAYaqnx2gKniV5wAAAABBWWFxbnloNkFBQ3JHY2Z2NWFiVnlBQUQ&index=%2A&messageDisplay=inline&stream_sort=time%2Casc&viz=stream&from_ts=1677869776581&to_ts=1678128976581&live=true

This example transfer is stuck because of this.
https://testnet.connextscan.io/tx/0x2df1d67d4fedf74f83521f09209f60273a8532cf4e9571af03023567216fcc40?src=search

**To Reproduce**
1. https://app.datadoghq.com/logs?query=region%3Aus-west-1%20%40requestContext.transferId%3A0x793626b6b6335dce76c144d16f65ee7d8906fb09fe627f77250b26858841aed0&additional_filters=%5B%7B%7D%5D&cols=host%2Cservice&event=AQAAAYa2rToWQAvUVAAAAABBWWEyclQzSUFBQ2wwQUJhNk1qcFd3QUc&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1677869776581&to_ts=1678128976581&live=true

**Comment by LayneHaber** [comment]
Detailed writeup on issue and fix [here](https://www.notion.so/connext/Optimism-Bedrock-Impacts-8dd6957ad08c4dfaa37ce78c9e623288).

Will need to redeploy the testnet hub connector contract for optimism to resolve.

**Comment by LayneHaber** [comment]
https://github.com/connext/monorepo/pull/3782#issuecomment-1478707523

^^ remaining status on last bit of PR
