### ISSUE TITLE
Warning popup when destination gas fee exceeds x% of swap

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3711]
## Problem
Users are taken by surprise by high gas fees (despite clearly showing them in the UI and them having to accept a transaction transferring said fees).

## Proposed Solution
Implement a warning popup that shows whenever the destination gas fee is higher than x% of the swap (in $ terms). Message could be something like "Warning: The estimated destination gas fee is higher than x% of the swap you're trying to make". An "Accept and continue" button must be clicked to hide the popup.

x% could be 5%? Accepting feedback on exact wording and percentage

**Comment by alexwhte** [comment]
looking tomorrow thanks ser

**Comment by alexwhte** [comment]
@pjenviri can you revert this? I'm not confident users will understand what it means and we should test impact better

**Comment by pjenviri** [comment]
@alexwhte , reverted and commented code of this part.

**Comment by alexwhte** [comment]
handling in other issues
