### ISSUE TITLE
Sending USDC shouldn't include calldata

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3719]
**Describe the bug**

See:
- https://connextscan.io/tx/0xef71ce44b1c85f3a0b7ab4810225e38f7bacd50803ae0baa999aa03165d5de1e
- https://connextscan.io/tx/0x99b97da136743b8cf105837121bccd3151b84f48c575a936629fb9e29f97237a

These transfers should not include calldata.

**To Reproduce**
1. Go to Bridge UI
2. Send USDC
3. See there's calldata included in the xcall

**Additional context**

**Comment by pjenviri** [comment]
@just-a-node, We never set calldata. We always submit 0x.

**Comment by alexwhte** [comment]
@nrsirapop  what did you find?

@just-a-node im not seeing this everywhere... are you sure? 
there's still calldata on the examples

**Comment by pjenviri** [comment]
@alexwhte @just-a-node, the xcall's unwrapped param was set as `true` when the destination chain is either ethereum, optimism, arbitrum but the asset is not ETH. We have fixed it.
