### ISSUE TITLE
A lot of failed tx while `execute` & `propagate` using Connext Relayer.

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#3733]
**Describe the bug**
https://etherscan.io/txs?a=0x935aaae0f5b02007c08512f0629a9d37af2e1a47

![image.png](https://images.zenhubusercontent.com/63331283a97e6555fde71ad4/f987b0d1-447f-475e-b79e-a159c3c18c52)

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by preethamr** [comment]
Gelato fails:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/1195648/224192785-4f15741b-c681-47bf-9c07-b3b099f4a71f.png">

Connext relayer passes estimate check and tries it on chain:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/1195648/224192921-f3cd7e8e-f2cd-4063-97b5-540644473bfd.png">

And the task is then cancelled.

**Comment by preethamr** [comment]
The timestamps line up with the failures on chain:

https://app.datadoghq.com/logs?query=region%3Aus-east-2%20service%3Alighthouse-propagate%20Sent%20tx%20to%20Connext&additional_filters=%5B%7B%7D%5D&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1673810905780&to_ts=1673897305780&live=true

**Comment by liu-zhipeng** [comment]
LH tries to send tx via connext relayer if gelato fails. It seems Gelato estimated gas correctly and canceled if tx will be reverted. but sometimes Connext relayer doesn't do so and executes tx which will be reverted. So it sends a lot of gas for failed txs
