### ISSUE TITLE
Unable to withdraw LP [Optimism]

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3737]
**Describe the bug**
![image](https://user-images.githubusercontent.com/74738120/224053660-d7d6feb6-ce34-42a0-a591-a8b57785758f.png)

**Comment by oswy-cpu** [comment]
upd: user is out of eth. 

Maybe it's worth changing the error text to a more understandable one? cc @alexwhte

**Comment by sanchaymittal** [comment]
This comes from metamask, so we can't really do any better actions for it imo.
