### ISSUE TITLE
Instadapp dev

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3740]
## Background
Goal: Enable crosschain spells within Instadapp’s **Defi Smart Account (DSA)** connector framework

Instadapp doesnt have capacity (and/or priority) to implement without Labs engineering assistance 

## Impact
Instadapp is a top ~10 defi app by TVL (https://defillama.com/) 
43K Twitter followers 

Their new smart contract wallet Avocado implements account abstraction with DSAs. This is a huge future lever for partnership that aligns with our overall infrastructure abstraction vision. 

## Proposed Solution
Spec here https://www.notion.so/connext/Instadapp-Integration-8d9d3aca004141c89e54a5f529ce2cd8

_**Update: 3/29 -- Remaining:**_
Still in review. Will be whitelisted after review.
Receiver side auth needs to be finalized:
How to collect funds from user and forward to DSA address.
Waiting for info from them for where to add contracts. Finish unit tests and ready for audit.
Everything has been asked to them, need to bump them to get answers.

## Additional info 
DSAs are smart contract wallets that Instadapp users can deploy which give them the following benefits:
1. Security: DSAs can have multiple signing authorities for granular access control + recovery.
    1. As part of the DSA framework, instadapp can also do things like enable pre-built vaults/strategies for investors or utilize idle liquidity to generate additional value
2. Composability: users can bundle many DeFi protocol interactions into a single onchain transaction
Users can have many DSAs with many authorities assigned to them. Users will also have multiple DSAs across chains.

DSA vs. Avo: they are different infra but Avo will be marketed as DSA v3
    - DSA: doesn’t do signature verification right now. requires an authority to interact with the DSA
    - Avo: by default there is a metaTx available (no need for sig verification!), only need to give Avo wallet the signature
        - xReceive would just send Avo wallet signature (user must be on Avo chain 634), no need for metaTx contract

**Comment by rhlsthrm** [comment]
Instadapp connector is done and ready for review. Working on Instadapp receiver contract on the signature verification part.

**Comment by rhlsthrm** [comment]
Signature part is fixed. Review comments on connectors PR. Update with fallback address. @sanchaymittal to share contract with Thrilok and do review.

**Comment by rhlsthrm** [comment]
Updated changes for pull request review. Still in review. Waiting on review.

**Comment by sanchaymittal** [comment]
- Auth contract has been reviewed by instadapp, finalyze contract and share for final review. @sanchaymittal 
- waiting for connector's pr final review, it will whitelisted on their end afterwards.

**Comment by alexwhte** [comment]
Follow up with Instadapp @ArjunBhuptani 
- How do they typically handle audits
- What would they recommend
- What do other projects do

**Comment by rhlsthrm** [comment]
Still in review. Will be whitelisted after review.

Receiver side auth needs to be finalized, waiting for info from them for where to add contracts. Finish unit tests and ready for audit.

**Comment by rhlsthrm** [comment]
Contract needs final update for fallback address.

**Comment by alexwhte** [comment]
**Impact: 5**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/2) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/3) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by sanchaymittal** [comment]
- [ ] Finalized the Contract
- [ ] Add NatSpec comments on the contract
- [ ] Create documentation for Contracts
- [ ] follow up on Instadapp connectors
- [ ] Share the Target contract with Instadapp and further action plan for deployment & unit testing.

**Comment by rhlsthrm** [comment]
Feedback from Instadapp review. Suggested changes in review. Changes have been added.

@wanglonghong and @sanchaymittal to coordinate about remaining tasks.

**Comment by alexwhte** [comment]
Note: Clarify if they will update docs for connectors?

**Comment by rhlsthrm** [comment]
Contracts completed, signature replay protection added. Cast data needs to be verified with current implementation. Working on documentation.

**Comment by just-a-node** [comment]
Connector already deployed on OP. We need to deploy our contracts and see if everything works on OP. Then let Instadapp team know that they can deploy connectors to the rest of the chains.

**Comment by rhlsthrm** [comment]
Need update from @sanchaymittal, can we close this out as done and open issues as needed for next steps?

**Comment by rhlsthrm** [comment]
Last message from Instadapp.

> Hey @justanode! Just in case, whenever the connectors are ready for other chains. We will enable them all at once.

Let's get this pushed over the finish line. Will assign back to @just-a-node and @sanchaymittal to wrap up.

**Comment by rhlsthrm** [comment]
Auth stuff: @sanchaymittal speaking to Thrilok about the details and docs.
Connector stuff: Replicate for other chains.

**Comment by just-a-node** [comment]
- connectors ready for other chains in [this PR](https://github.com/Instadapp/dsa-connectors/pull/286)
- integration test in progress in [this branch](https://github.com/connext/connext-integration/compare/main...instadapp-deploy-and-test). see TODOs and Instadapp TG chat for updates

**Comment by rhlsthrm** [comment]
Fixed bugs, updated docs on Notion. Need to check out connectors PR.

**Comment by rhlsthrm** [comment]
Shared docs and contracts with Thrilok and asking about connectors, who will deploy. Posted query about audit stuff. Post in group about next steps.

**Comment by rhlsthrm** [comment]
Pushed docs and messages with next steps. Waiting for response from team.

**Comment by just-a-node** [comment]
Outlined in group chat remaining steps:

1) [Insta] Review, deploy, and enable remaining connectors
2) [Insta] Release alpha version of SDK
3) [Connext] Deploy Instadapp adapter contracts to all chains
4) [Connext] Test the e2e flow on live contracts using SDK + fork tests
5) [Insta] Public-facing documentation on the Connext connector 
6) [Connext] Toolkit to generate EIP712 signatures required in the xcall calldata (https://github.com/connext/monorepo/issues/3857)
7) [Both] Co-marketing and potentially a blog post of some sort describing how the connector works and how a user would actually use it

**Comment by just-a-node** [comment]
Working on fork test in [this branch](https://github.com/connext/connext-integration/compare/main...instadapp-deploy-and-test). Registered Connext connector in the test to move forward. Currently test is reverting on the ConnextConnector's xcall.

**Comment by sanchaymittal** [comment]
@just-a-node I think we should only do unit testing in Instadapp repo environment.
Also pinged thrilok, and proposed jumping on a call to finalize the steps for it.

**Comment by just-a-node** [comment]
Ok pls post results of the call if anything is finalized. This is relevant for 3) because if the insta team wants audit and/or ownership over the target contracts, then they should do the deployments and keep deployment artifacts in their repo.

The connectors PR is done being reviewed but there is one uncertainty I have with Matic on Polygon since we don't support it yet.

**Comment by just-a-node** [comment]
Connectors are deployed and enabled, alpha SDK is ready for us to use.

Next steps:
- Sanchay to call with Thrilok
- Connector contract updates from latest feedback (safeTransfer + signature validity time)
- Spec out xchain loan migrations for Avo

**Comment by rhlsthrm** [comment]
A lot of discussion from yesterday. @just-a-node to send next steps.

* Connectors are done and deployed.
* Target contracts are reviewed, updates made and need response from them.
* Move contracts into their repo and do unit tests.

**Comment by rhlsthrm** [comment]
Still waiting for answers.

**Comment by sanchaymittal** [comment]
Updates:

- Added timebased lock for signature based on new comments
- finalized contract are added as pr to instadapp repo, https://github.com/Instadapp/dsa-periphery-contract/pull/1
- unit test to be written in Hardhat env for Instadapp repo.
- further steps related to auditing deployment, marketing and testing...

**Comment by sanchaymittal** [comment]
- latest update: PR is ready for review for Instadapp
https://github.com/Instadapp/dsa-periphery-contract/pull/1

**Comment by rhlsthrm** [comment]
Updated contracts with both xcall types. Pushed and deployed on Opt. Review is ongoing on their side. After, will see how to move ahead with SDK.

**Comment by rhlsthrm** [comment]
Connector PR merged. Other PR has some comments to be fixed. Once that's done, we can move forward.

**Comment by sanchaymittal** [comment]
both the pr merged, they are running excess memory issue. Need to take a look for next step of deployment

**Comment by rhlsthrm** [comment]
Stack too deep errors when compiling.

**Comment by rhlsthrm** [comment]
Resolved and created PR, waiting for further review.

**Comment by rhlsthrm** [comment]
Waiting for review still.

**Comment by LayneHaber** [comment]
who are the reviewers here?

**Comment by sanchaymittal** [comment]
Instadapp devs

**Comment by alexwhte** [comment]
PR merged. Need next steps clearly mapped out (testing, adding to instadapp docs, marketing campaign)
Options for implementation
- 1-click deposits
- crosschain lending
- 
@sanchaymittal can you please follow up separately
