### ISSUE TITLE
Review and overhaul docs (placeholder) 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3743]

**Comment by LayneHaber** [comment]
**Complexity: 1**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/16) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/31) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/32) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
No relevant/unspecific, closing
