### ISSUE TITLE
Multiple assets in a relayer fee for single transfer

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3751]
## Background

Need to be able to handle a transfer with relayer fees paid in multiple assets.

Blocking #3380

### Linked Issues & Documentation

Blocking #3378

## Definition Of Done

Transfer relayer fee is tracked by asset and summed on display.

## Tasks

- [x] Update subgraph
- [x] Update carto
- [x] Update Sequencer
- [ ] Update UI
- [x] Update sdk for returning relayer fee

**Comment by ArjunBhuptani** [comment]
Wait why do we need this?

**Comment by LayneHaber** [comment]
likely mislabeled -- its captured in the DB
