### ISSUE TITLE
Add performance tests for core SDK methods

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3753]
## Background

SDK methods used by all integrators need to be as fast as possible. Write performance tests that benchmark the speed of these core methods:

- estimateRelayerFee
- calculateAmountReceived

Add tests in npm `scripts` as a way to check latency manually before we push changes. The methods above should be <1000ms. As these can be flaky in CI, don't include them there.

**Comment by alexwhte** [comment]
We need clear design and acceptance criteria first
