### ISSUE TITLE
bridge load latency / awkward intermediary state

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3767]
**Describe the bug**
Can we preload this better? This partially loaded image looks bad when we are waiting for things to load
Are we waiting on some SDK calls? 
![image](https://user-images.githubusercontent.com/37959170/224232996-d708e0d1-1b48-4335-b135-4b4be71fae5c.png)

**Comment by alexwhte** [comment]
This looks better @pjenviri , but why is there a loading state at all? 

for example this loads intantly https://jumper.exchange/

would be good to identify the delays

**Comment by pjenviri** [comment]
There was a short period (when getting/setting the chains & assets information). So, we updated it to check whether the needed information was all set before showing up on the UI.
