### ISSUE TITLE
Highlight pool rows when hovering 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3774]
Received some feedback that this UI wasnt clear, I'm thinking more responsive design to help show these rows are clickable might help. Can we highlight the rows as the user hovers?
is this complex or will it negatively impact performance? 

https://bridge.connext.network/pools

**Comment by pjenviri** [comment]
@alexwhte we can't do it with the current implementation. It's because the asset UI of each asset is actually a collapsable UI.

**Comment by alexwhte** [comment]
@pjenviri can we do this with a different implementation?

**Comment by alexwhte** [comment]
@pjenviri this came up again today in here at 9:20 https://www.loom.com/share/107663d1724c40bf9924cba7bf5c9151

**Comment by 0xanedi** [comment]
We don't want to copy everything, but inspiration on this one might help! It features highlight + Button on the right for mobile.
ONLY inspiration material.  Happy to look for further options if necessary.
https://app.hop.exchange/#/pools?token=USDC&sourceNetwork=ethereum&destNetwork=optimism

**Comment by pjenviri** [comment]
PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/137
Preview: https://connext-bridge-mainnet-git-feat-update-pools-table-coinhippo.vercel.app/pools

**Comment by alexwhte** [comment]
this is better. we can do topline values and metrics another way

can we please try the asset icon pairs next to each token? 

for example for WETH pools show these two tokens 
![image](https://github.com/connext/monorepo/assets/37959170/7dfb19bb-23ac-492e-a077-2d92c50e641f)

**Comment by pjenviri** [comment]
updated.

**Comment by alexwhte** [comment]
LGTM! let's ship it

**Comment by pjenviri** [comment]
Deployed. :)

**Comment by alexwhte** [comment]
@pjenviri  i dont see this in prod yet!

**Comment by pjenviri** [comment]
https://bridge.connext.network/pools. It has already been deployed. Please try a hard refresh. 

![Screenshot 2566-06-25 at 12.22.15.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/bb54eeec-6486-4ad2-b460-e80fa373dec3)
