### ISSUE TITLE
no dest gas fee shown, Mulitple errors in console 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3784]
![image](https://user-images.githubusercontent.com/37959170/224718554-ac115cad-d058-4302-b633-6eb938b74387.png)

after a while i got it but see these errors
![image](https://user-images.githubusercontent.com/37959170/224718794-98162b49-6ed4-44c4-8b23-002e668c6daa.png)

**Comment by alexwhte** [comment]
logs
[bridge.connext.network-1678714851439.log](https://github.com/connext/monorepo/files/10957966/bridge.connext.network-1678714851439.log)

**Comment by pjenviri** [comment]
We have reduced the number of unnecessary requests. It looks good on my end now. Please test it.
