### ISSUE TITLE
Staging connextscan broken

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3790]
**Describe the bug**
connextscan on staging testnet seems broken (https://staging.testnet.connextscan.io/). This is related to new rollout on sdk side recently. 

That would be ideal if we have a way to upgrade sdk version only on staging testnet because it should be happening in the future as well and it doesn't make sense to visit [temporary link](https://connextscan-testnet-staging-git-feat-update-sdk-coinhippo.vercel.app/transfers) until it gets merged to prod.

**To Reproduce**
1. Go to 'https://staging.testnet.connextscan.io/transfers'
2. 
3. 

**Additional context**

**Comment by pjenviri** [comment]
@wanglonghong @alexwhte , Now, we can separate only logic. We cannot separate the SDK version on each different URL; we can only do it via the Vercel predeployment.

**Comment by pjenviri** [comment]
updated, please try it at: https://staging.testnet.connextscan.io.
