### ISSUE TITLE
Expose chain to domain mapping utils in SDK

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3793]
## Background

During SDK integration we found that it is convenient to have access to the domain/chain mappings. We can easily expose this in the SDK as a static method.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

SDK has a export for the chainIdToDomain and vice versa functions.

**Comment by alexwhte** [comment]
Maybe in scope of #3732

**Comment by rhlsthrm** [comment]
I don't think it's in scope actually, it is a separate thing.
