### ISSUE TITLE
Pool UI visuals updates (test mode)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3794]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/37959170/225454730-38c9957a-8aba-441b-8731-e8070d6a420f.png">

**1- Update the  TVL/Volume**
Remove these, show the same values by default in the top right number of the charts until the user hovers over the chart
![image](https://user-images.githubusercontent.com/37959170/225445155-1ffae291-158c-4cfd-a4cf-9e1df85038b6.png)
See Balancer UX for this interaction design https://app.balancer.fi/#/ethereum/pool/
Move the TVL/Volume chart to the top of the page (where the existing boxes are)

2- Change 'Liquidity provided' to say 'Pool Composition'
Show the Pool Ratio inside of this pane
_Remove Pool Ratio entirely from the 'Manage Balance' pane_

3- Update 'My Position' 
Show Current value in USD (if user were to withdraw the amount, add up to net asset equivalent)
In above I added up from here
<img width="396" alt="image" src="https://user-images.githubusercontent.com/37959170/225452358-531784f7-6565-4ea6-a9c8-a4fc3158e70b.png">

**Comment by pjenviri** [comment]
PLease test it at: https://connext-bridge-mainnet-git-feat-update-pool-ui-coinhippo.vercel.app/pool/USDC-on-polygon.
If everything goes well, please approve it at https://github.com/CoinHippo-Labs/connext-bridge/pull/114.

**Comment by alexwhte** [comment]
@pjenviri can you add me to the repo to approve? https://github.com/alexwhte
You can remove this warning as well
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/ea22734e-6e2e-4044-a02d-54fcb267f67a)

**Comment by pjenviri** [comment]
@alexwhte 
- added you to the repo
- removed

**Comment by alexwhte** [comment]
approved
