### ISSUE TITLE
As an SDK user, I want to retrieve all multi-chain assets addresses on other chains in order to make integrations easier.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3805]
## Problem
_What problem are we solving and why does it matter, ser?_ 
Addresses for assets have to be manually looked up and inserted into the SDK implementation code. This is annoying for integrators.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Add exposed util function exposed to get asset addresses on other chains.

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] SDK util exists and works.

**Comment by alexwhte** [comment]
maybe in scope of https://github.com/connext/monorepo/issues/3732

**Comment by rhlsthrm** [comment]
Not in scope of the other issue, that one is about minimizing SDK, this is about adding features.
