### ISSUE TITLE
Using SDK in frontend : "Can't resolve 'fs'"

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3808]
**Describe the bug**

SDK imports utils which uses the node module `fs`. This causes some issues for frontend integrations.

Current solution is to put the following in `package.json`:
```
  "browser": {
    "fs": false,
    "path": false,
    "os": false
  },
```

We need to see if we can shake this dependency from the SDK.

**Comment by alexwhte** [comment]
closing as dupe
