### ISSUE TITLE
Update ToS and add hamburger index to UI

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3814]
### Legal links
Apparent our legal links aren't visible enough

Remove the 3 icons in the middle of the footer and include text links  instead
[Terms of Service](https://www.connext.network/terms-of-service-connext-network) | [Privacy Policy ](https://www.connext.network/privacy-policy)

Formatted like this example 
https://synapseprotocol.com/?inputCurrency=USDC&outputCurrency=USDC&outputChain=42161
![image](https://user-images.githubusercontent.com/37959170/226490723-0a7fe4ed-27fb-4617-9e8b-039035b67899.png)

Change all footer text to the same grey Manrope font as in the bridge UI
![image](https://user-images.githubusercontent.com/37959170/226490914-03d2199a-8a87-4acd-8000-b9e01916b190.png)

### Hamburger dropdown

At the top right add a hamburger dropdown and include the below 
1. Developers  [dropdown]
[Documentation](https://docs.connext.network/)
[Connext Github](https://github.com/connext) 
[Coinhippo Github](https://github.com/CoinHippo-Labs/connext-bridge)
4. [About Connext](https://www.connext.network/)
5. [Twitter](https://twitter.com/ConnextNetwork)
6. [Discord](https://discord.gg/connext)

Example: https://jumper.exchange/
![image](https://user-images.githubusercontent.com/37959170/226489959-8090f9b7-bbd8-4faa-9587-e75614d23d57.png)

**Comment by alexwhte** [comment]
Please make this more visible.. maybe slightly lighter 

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/9a31a8e4-eeed-4b31-a1d4-0d347205d921)

Also same manrope font might look better

**Comment by pjenviri** [comment]
We have updated the menu color to be slightly lighter. Regarding font, it's currently set as `Manrope`. Please try it.

**Comment by alexwhte** [comment]
i think it could be improved these ways 

- spacing around the text could be larger
- dropdown could be placed slightly lower (it's crowded against 'Disconnect' button)
- try a slightly more bold version of the text

im somewhat using this for reference 
![image](https://user-images.githubusercontent.com/37959170/229684215-7bc066a6-08f3-4196-bdad-913be388f5a0.png)
