### ISSUE TITLE
Connect wallet UI/UX update

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3815]
At the top right of this UI
https://bridge.connext.network/pools 

Can we update to this? 
https://monosnap.com/file/JJAutwOJhkIFv06dWN81ZgQcp3zHOE

![image](https://user-images.githubusercontent.com/37959170/226492431-1f890f2b-d11a-403d-a31a-db71a2102ad4.png)

To this that the designer made

![image](https://user-images.githubusercontent.com/37959170/226492360-7ffb3909-1c30-4c4c-bcd7-a7dfc68bdadd.png)
https://www.figma.com/file/Z3iq2LOM12K1BeSGQc1Dal/Connext-Concept?node-id=190-500&t=Kw1CyUhsDswPZKbh-0

![image](https://user-images.githubusercontent.com/37959170/226494778-81de75a3-716f-4e8d-b616-517dd28fd8a7.png)

**Comment by pjenviri** [comment]
We enhanced it and pushed these updates to testnet. Btw, we cannot add all animation shown in the video. Please try it out.

**Comment by alexwhte** [comment]
interesting, mind expanding on why we cant do the animation?

I do think the rounded tighter design looks a bit cleaner 
![image](https://user-images.githubusercontent.com/37959170/229682153-c9ada441-9dab-4001-b993-6a553e3dcd84.png)

Is font is the same?
![image](https://user-images.githubusercontent.com/37959170/229681979-0c267495-f162-4f95-ad3b-48df386d22cc.png)

And border?
![image](https://user-images.githubusercontent.com/37959170/229682066-448f753b-7b88-40d8-a2e2-8d76c7b4230c.png)

**Comment by alexwhte** [comment]
this should not be in prod it's still buggy please revert
