### ISSUE TITLE
Reduce RPC requests by using injected wallet

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3817]
## Background

We need to send as many calls through the user's wallet as possible.

### Linked Issues & Documentation

See Alchemy dashboard for RPC usage stats. Currently around 1M per day per chain.

## Definition Of Done

SDK uses injected wallet as much as possible for RPC calls.

## Tasks

- [ ] Allow optional parameter to take in user's injected provider.
- [ ] If injected provider is available, use that to send requests.

**Comment by just-a-node** [comment]
While Metamask is connected to Polygon, on Pools page:

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/0c66a272-906d-443d-897d-ee87d59c15ce)

**Comment by alexwhte** [comment]
@just-a-node i tested polygon and dont see these in the console, good to close?

**Comment by just-a-node** [comment]
This needs to go into next SDK release and updated in mainnet

**Comment by rhlsthrm** [comment]
Have we tested this properly? I'm not sure this is addressing the root issue.

**Comment by just-a-node** [comment]
Screenshot above is showing the browser provider being used on the user's connected chain. This will cut down on a portion of the usage by the frontend's RPCs. The major improvement should come from the completed lazy loading task.

Quick comparison of before and after wrt to these changes:

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/8270d869-2cb3-46e6-b033-88b4b9de7605)
