### ISSUE TITLE
Disable ETH pools in testnet

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3827]
## Problem

Because Goerli ETH now has value, our testnet WETH pools can easily be drained (nextWETH is mintable). Course of action here is to disable WETH pools and set up TEST to have an adopted/local pair + pool.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] Remove WETH pools from UI
- [ ] Set up TEST to have adopted/local
- [ ] Set up TEST pools on testnets
- [ ] Add TEST pools to UI

**Comment by alexwhte** [comment]
**Impact: 2**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/65) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 2**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/66) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/66) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/25) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/11) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/21) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by just-a-node** [comment]
Don't need this.
