### ISSUE TITLE
swap adapter standard implementation

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3842]
## Background

Support for Swap, dexs to make any to any token support for connext bridge.
This includes the Mean, Midas and some more integrations.

### Linked Issues & Documentation

- List of linked issues, external links, etc

Spec: https://www.notion.so/connext/Swap-Adapter-33d91cd69d2c4386bea52dbe5c260ac2?pvs=4

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by rhlsthrm** [comment]
Finalize contract. Document contract. Get PR reviewed.

**Comment by rhlsthrm** [comment]
Finalizing contract, needs review from @LayneHaber.

**Comment by rhlsthrm** [comment]
Finalize swap adapter after target and source.

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/10) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/11) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 5**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/12) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
@wanglonghong finish unit tests and make repo CI work.

**Comment by rhlsthrm** [comment]
Got more info from @sanchaymittal on implementation, will revise based on this.

**Comment by rhlsthrm** [comment]
E2E set up, failing on external call to swap. Need to debug this.

**Comment by rhlsthrm** [comment]
E2E fork mainnet test working for swap adapter. @rhlsthrm pivot to spec. @wanglonghong to work on tests and adding extra adapters for swappers.

**Comment by rhlsthrm** [comment]
Issue is complete, will continue to improve as we build integrations.
