### ISSUE TITLE
Adjust spacing and font

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3846]
There's two much spacing before the polygon symbol
font is inconsistent Switch to vs Polygon
![image](https://user-images.githubusercontent.com/37959170/227257218-a3ac771b-73cc-48df-a834-28bde720fdb4.png)

**Comment by pjenviri** [comment]
Updated it in staging - not on mainnet. We will need to update the SDK version on mainnet before rolling this out.

**Comment by alexwhte** [comment]
please feel free to close assuming this is updated @pjenviri
