### ISSUE TITLE
UI checks liquidity with new isFastPathAvailable function 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3847]
## Problem
Currently we say that fast liquidity is always available as a default 

## Proposed Solution
Add a way to estimate if there is enough liquidity as it's own function in the SDK

> the last optimization for calculation we did fetches the total of router liquidity available for an asset at provided destination network.
> And then compares to it's 70%
> But cause routerLiquidity call to carto was adding time to calculatRelayerFee calculation time, we removed it from the code and made true as default

**Comment by just-a-node** [comment]
https://github.com/connext/monorepo/tree/fast-path

**Comment by just-a-node** [comment]
Needs UI update to use optional `checkFastLiquidity: true` flag in `calculateAmountReceived`.

**Comment by just-a-node** [comment]
For ref:

```
  async calculateAmountReceived(
    originDomain: string,
    destinationDomain: string,
    originTokenAddress: string,
    amount: BigNumberish,
    receiveLocal = false,
    checkFastLiquidity = false,
  ): Promise<{
    amountReceived: BigNumberish;
    originSlippage: BigNumberish;
    routerFee: BigNumberish;
    destinationSlippage: BigNumberish;
    isFastPath: boolean;
  }> {
```

**Comment by pjenviri** [comment]
pushed it to testnet. (for mainnet, will have to update the SDK version before rolling it out.)

**Comment by just-a-node** [comment]
Please use `v2.0.0-alpha.4` to test mainnet locally. We will be releasing `v2.0.0` stable soon.

**Comment by pjenviri** [comment]
PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/116
Preview: https://connext-bridge-mainnet-git-feat-update-sdk-v20-396b12-coinhippo.vercel.app/
