### ISSUE TITLE
As a integrator, I want a sdk function to generate signature for EIP712 verification on xReceive contracts.

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#3857]
## Problem
The origin sender needs to put the signature into calldata to create a xcall so it can be verified on the destination side by our own EIP712 verification system. It could be annoying sometimes to figure out verification version and implement it themselves.  

## Acceptance Criteria
- [ ] Create a sdk function to generate signature

**Comment by wanglonghong** [comment]
This issue would be included in https://github.com/connext/monorepo/issues/3971 as a subtask. closing

**Comment by just-a-node** [comment]
Reopen to keep separate

**Comment by rhlsthrm** [comment]
PR created, tested against integration repo.
