### ISSUE TITLE
Scaling is off for UIs

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3858]
From team

Sarah
still super tiny but i suppose better!
why is everything so small and spaced out?
![image](https://user-images.githubusercontent.com/37959170/227600768-97ee7cfe-29ef-471c-ae81-f2e0dc389615.png)

Matt
5120x1440 (fwiw, generally size the window to 1440x1440)
we should be able to largely fix this by enforcing better min/max size constraints on the UI
ideally the constraints should be in vh and vw, not px or %
![image](https://user-images.githubusercontent.com/37959170/227600600-998f7e1f-b26d-4cfe-9085-6b4667d92877.png)

**Comment by pjenviri** [comment]
Deployed to testnet.

**Comment by alexwhte** [comment]
Scale looks strange for me on Testnet now (font sizing + spacing seems off / need to scroll)
![image](https://user-images.githubusercontent.com/37959170/229683092-be552030-280e-4693-8a88-f825a28caa11.png)

monitor is 2560x1440

**Comment by alexwhte** [comment]
please revert if changed

**Comment by pjenviri** [comment]
removed the new styling out of the mainnet ver.

**Comment by alexwhte** [comment]
My screen looks weirdly zoomed... this is still an issue? 'Connect Wallet' is also super small for some reason

2560x1440

![image](https://user-images.githubusercontent.com/37959170/234166153-38597965-734a-4a7b-82f7-481c73bd311b.png)

**Comment by alexwhte** [comment]
mmm so the zoom is strange here. i shouldnt need to scroll i dont think, and it looks a bit blurry / out of proportion compared to other websites. 

![image](https://user-images.githubusercontent.com/37959170/234349554-98710112-a911-4224-98a1-3a298ef153e7.png)

**Comment by pjenviri** [comment]
Updated the scaling.

**Comment by alexwhte** [comment]
I'm still seeing some of it zoomed 

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/44575be3-68ac-4460-b149-7c409995b3e9)
