### ISSUE TITLE
Transfer CTA to switch network unresponsive

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3866]
**Describe the bug**
Transfer CTA to switch network on one tab does not recognize, if network got switched in another tab. And the switch button becomes unresponsive.

<img width="1746" alt="image" src="https://user-images.githubusercontent.com/1195648/227647015-93f9d379-13a1-4937-8e55-902863b67276.png">

**To Reproduce**
1. Open multiple transfers that require the same network switch
2. Switch network on one of the tabs
3. Find this behavior on the other tabs

**Additional context**
Dialog can be closed, and does not happen on hard refresh.

**Comment by pjenviri** [comment]
Updated on testnet. (for mainnet, we need to update the SDK version before rolling this out.)

**Comment by pjenviri** [comment]
We couldn't reproduce it. The network has been switched for all pages according to our tests. Can you confirm that the issue persists?
