### ISSUE TITLE
Transfers shows execution error after successful execution

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3872]
**Describe the bug**
Transfers shows execution error after successful execution.

![image](https://user-images.githubusercontent.com/1195648/227652492-74fd3f1f-2bde-4d5f-bd49-9181a44cda4f.png)

**To Reproduce**
1. [DD](https://app.datadoghq.com/logs?query=region%3Aus-west-1%20%40requestContext.transferId%3A0x010882bf31b167f4d2e58c9a18f20a5ca2e81d1e8bccb2073633d82874498e24&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1679687887398&to_ts=1679691487398&live=true)

**Additional context**
```
"host": "ip-172-17-1-222.us-west-1.compute.internal",
"service": "sequencer-subscriber",
"message": "Sent to Gelato network",
"attributes": {
"hostname": "ip-172-17-1-222.us-west-1.compute.internal",
"requestContext": {
"origin": "execute",
"id": "y+vh45hvRWuohh+6dUDi8w/1",
"transferId": "0x010882bf31b167f4d2e58c9a18f20a5ca2e81d1e8bccb2073633d82874498e24"
},
"level": "INFO",
"methodContext": {
"name": "send",
"id": "y+vh45hvRWuohh+6dUDi8w/43"
},
"service": "sequencer-subscriber",
"pid": 272,
"source": "stdout",
"time": 1679691969877,
"taskId": "0xc5259cbff6f36fd3715ac9f267e39cca179b51ca7a2926758fc5c4f5ebd90370",
"timestamp": 1679691969878
}
}
```
Executed via Gelato
```
{
    "task": {
        "chainId": 420,
        "taskId": "0xc5259cbff6f36fd3715ac9f267e39cca179b51ca7a2926758fc5c4f5ebd90370",
        "taskState": "ExecSuccess",
        "creationDate": "2023-03-24T21:06:12.298Z",
        "executionDate": "2023-03-24T21:06:17.631Z",
        "transactionHash": "0x2790c8e5d14cc2eb77c565746b7d5e7c53b52cdca50f3ec4dcfb323ebe6d2688",
        "blockNumber": 7131954
    }
}
```
Then a subsequent attempt at execution, marks the transfers as `ExecutionError` for the user:
![image](https://user-images.githubusercontent.com/1195648/227652712-2dc8e66d-4af0-4b8a-b5e3-f1a129d55544.png)

**Comment by pjenviri** [comment]
The error icon is displayed when there's `error_status` and no execute txhash provided.

**Comment by liu-zhipeng** [comment]
I can't reproduce this issue anymore.
