### ISSUE TITLE
Process for automatically generating SDK docs when src updated

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3876]
## Problem

Docs should be automatically updated when SDK source changes.

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [ ] On merge to relevant branches, CI recognizes `alpha` | `beta`| `latest` tags and generates docs version using `typedoc-plugin-markdown`
- [ ] GH action clones the `/documentation` repo, replace old docs with new, pushes commit
- [ ] Update docs site to have versions for the different tags

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] User can reference up-to-date docs for `alpha`, `beta`, and `latest` SDK releases

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/56) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/57) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/16) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
