### ISSUE TITLE
[Tetsnet] Bridge token approval transaction skipped

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3880]
**Describe the bug**

Trying to send TEST:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/16638982/228064938-62d9b1f2-c29a-4684-804e-0026611be7c2.png">

Button changes to "Checking approval", then "Please confirm", then immediately errors with the above.

**To Reproduce**
1. Go to Bridge UI
2. Try to bridge a token without approval
3. See error

**Additional context**

**Comment by pjenviri** [comment]
Hey @just-a-node, I couldn't reproduce it. Did you use https://testnet.bridge.connext.network?

**Comment by just-a-node** [comment]
Yes, I did but also unable to repro now. Closing out
