### ISSUE TITLE
Template for Source and Target contracts 

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3885]
## Problem
_What problem are we solving and why does it matter, ser?_ 
We want well defined templates for source and target contracts for integrations 

## Proposed Solution
_Thoughts on solution design. We should do <insert idea> to solve this problem._
- [x] Source Template
- [x] Target Template
- [x] Add fallback strategy
- [ ] docs for above

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] X happens

**Comment by sanchaymittal** [comment]
- [ ] source template ready
- [ ] target template ready
- [ ] unit test for both
- [ ] documentation

**Comment by rhlsthrm** [comment]
@sanchaymittal  to fill out scope, spec, and subtasks.

**Comment by rhlsthrm** [comment]
Contracts done, reviewed with Eddie.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/19) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 5**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/20) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by sanchaymittal** [comment]
- [ ] update contracts based on initial feedback
- [ ] add natspec comments
- [ ] create documentation for each contract and design pattern

**Comment by rhlsthrm** [comment]
Reviewed Layne's comments, made some changes, added doc strings.

**Comment by rhlsthrm** [comment]
@rhlsthrm to continue with doc strings and other fixes.

**Comment by rhlsthrm** [comment]
Done for now.
