### ISSUE TITLE
Chain Abstraction MVP

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3892]
**Vision doc:** https://www.notion.so/connext/Chain-Abstraction-761e0445ebf74565a3a8aaaeb6a949b0

Goal is to create reusable contracts+SDK+docs for simple and easy chain abstraction integrations

**Comment by alexwhte** [comment]
1- UI Example  
We are evaluating building a barebones example for devs, since integrations have struggled on how to design cross-chain UX, there are gaps to fix, and we should overall be leading this vision of improving UX 

Spec https://www.notion.so/connext/Spec-Chain-Abstraction-UI-Template-aff9ad1877c54e12a2a4edca407c1686
Epic  https://app.zenhub.com/workspaces/connext-6272a34e0368a200141cd949/issues/gh/connext/monorepo/4249
Wireframe  https://lucid.app/lucidchart/f9542edb-092d-498c-a8c0-140bf3312beb/edit?viewport_loc=-120%2C-226%2C4608%2C2340%2C0_0&invitationId=inv_06307e91-3cdc-4511-b590-e3bce34906c4

**Comment by preethamr** [comment]
Not deploying Mean.
Will pick this up later.
