### ISSUE TITLE
UI: The recipient address gets reset after I input the amount to bridge

### ISSUE THREAD

**Issue by 0xGorilla** [connext/monorepo#3899]
**Describe the bug**
If I set the recipient address in Connext's UI and after that, I do set the amount: the recipient disappears.

**To Reproduce**
![Screen_Recording_2023-03-29_at_15_43_45_AdobeExpress](https://user-images.githubusercontent.com/84932007/228558650-1040e653-ab87-434f-8e88-1357a987074f.gif)

**Comment by pjenviri** [comment]
Updated on testnet. (for mainnet, we need to update the SDK version before rolling this out.)

**Comment by just-a-node** [comment]
@pjenviri Why does this fix need an SDK update in mainnet?

**Comment by pjenviri** [comment]
@just-a-node There're more than 10 cards that possibly conflict if we deploy on mainnet (that use an older sdk version). So, it would be easier if we could update the SDK version on mainnet. So we can deploy them once. However, this is not a big issue. We have already deployed them separately.

**Comment by alexwhte** [comment]
@pjenviri @just-a-node what's the status of this?
