### ISSUE TITLE
Add USD equivalent values as new columns in Carto to enable internal volume reporting

### ISSUE THREAD

**Issue by mchammond** [connext/monorepo#3901]
## Problem
Currently, carto only stores the amount of a given token that's transferred, received, etc. As a result, internal volume reporting + an array of other dashboards are blocked without this information.

## Impact
Without this data, we are limited in all of our internal reporting. This impacts the entire org.

## Proposed Solution
Add USD value equivalents (calculated using the CH crypto price feed) to Carto (not SDK) for any value that is currently denoted in token amts (gas, amt sent, amt received, etc.)

## Acceptance Criteria
- [ ] add USD-denominated columns for every value currently denominated in tokens
- [ ] keep current fields intact, adding new ones for the USD vals

**Comment by alexwhte** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/59) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/60) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
@mchammond is it ok to start with scope of `tables` table only?

Notes from pointing:
1. How do we handle if API fails? 
2. We call API while logging?
3. Check does Coingecko API support timestamp based pricing? Or is it only realtime? (can we backfill or reset?)

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/m1gPDfcYUg/estimate/7) in Sprint Poker #​​22

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
@liu-zhipeng if easier, we can start with `transfers` table for testing but we should design it to be applied to all of our tables or views that contain balances/volumes/etc that would need conversion

**Comment by rhlsthrm** [comment]
Get price from APIs. Need to consider impact of resetting cartographer.
- Split price into separate table which joins to transfers and other tables.
- Allows deletion of other tables but not price table.

Create separate poller that stores price every hour (or so) to create an entry. Potentially can use API to get historical prices to allow data refresh.

**Comment by rhlsthrm** [comment]
Today: @liu-zhipeng continue with ^^ today.

**Comment by rhlsthrm** [comment]
Cartographer side is done, tested against prod testnet. Transfers table migration created. Asset prices in another view. Need to add db migrations for other tables like router liquidity, swap events, remove liquidity.

**Comment by rhlsthrm** [comment]
Modify view to calculate properly.

**Comment by alexwhte** [comment]
some of the prices look wrong in here, can we please fix?

ex/ `select transfer_id, origin_transacting_asset, asset_usd_price, update_time from transfers_with_price where transfer_id = '0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f'`

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2299.4">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
</style>
</head>
<body>


0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f | 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 | 1.001 | 2023-04-16 00:35:15.019869
-- | -- | -- | --
0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f | 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 | 1 | 2023-04-16 00:35:15.019869
0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f | 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 | 2095.33 | 2023-04-16 00:35:15.019869
0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f | 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 | 1.002 | 2023-04-16 00:35:15.019869


</body>
</html>
