### ISSUE TITLE
Add Cronos Mainnet Support 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3903]
## Problem
Supporting the ability to Bridge to and from Cronos chain

## Impact
Primarily impacts end users. We may see Cronos DeFi projects build on this. 

Per Ella @ Cronos
- **Cronos trading volume:** while there has been a decline for simple swap volume, new perp protocols such as Fulcrom (https://fulcrom.finance/) has been gaining organic traction, breakiing $2.6m TVL within 1 month launch. More Cosmos/Cronos unique tokens will be added to their asset mix which is expected to drive more volume. Their trading volume is not currently captured on defillama.
The approach has been shifted where we prefer working with 1-2 bridge partners to funnel cross-chain traffic. We are also more than happy to introduce top Cronos DeFi projects if they would like to add bridge interface.

- **Cronos trading volume:** while there has been a decline for simple swap volume, new perp protocols such as Fulcrom (https://fulcrom.finance/) has been gaining organic traction, breakiing $2.6m TVL within 1 month launch. More Cosmos/Cronos unique tokens will be added to their asset mix which is expected to drive more volume. Their trading volume is not currently captured on defillama.

- **Gas fee subsidy:** understanding mainnet gas cost is also a concern if tx volume doesn't cover the cost. We're also **happy to discuss gas subsidy arrangement** until Connext upgrade to the more cost effective mechanism in the next few months.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] End users can bridge to/from Cronos in our UI
- [ ] Liquidity (from Cronos) is added in routers AND AMMs
- [ ] Docs are updated
- [ ] Integrations can call xcall to Cronos

**Comment by alexwhte** [comment]
**Urgency: 2**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/54) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/9) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/17) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 2**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/18) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/14) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
blocked

**Comment by just-a-node** [comment]
When we move ahead with Cronos, we'll have other tasks for the process. Closing this.
