### ISSUE TITLE
Reduce calculateAmountReceived latency 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3905]
## Problem
Connext is not even showing in results 30% of the time (est) because our API takes too long
See analysis in here https://github.com/connext/monorepo/issues/3895

Based on these initial profiling results, calculateSwap is the biggest contributor of latency. We call it (up to) 2 times per call, once to calculate origin swap and once to calculate destination swap.
In the calculateSwap function, the direct contract call here contains the majority of the latency:
    const minAmount = await connextContract.calculateSwap(key, tokenIndexFrom, tokenIndexTo, amount);

## Impact
**25%** of our volume last week came from LiFi alone. 
We are recommended **40%** of the time **when shown**, but only even a shown option **70%** of the time 

CalculateSwap is involved in 1665 ms (63%) of the latency 

> TOTAL for calculateAmountReceived: 2642.678041934967 ms
> awaited promises (getPool, getCanonicalTokenId, isNextAsset): 677.4156659841537 ms
> calculateCanonicalKey: 3.511583924293518 ms
> getAssetsDataByDomainAndKey: 0.15845799446105957 ms
> origin-calculateSwap: 722.9010410308838 ms
> destination-getPool: 293.92433309555054 ms
> getActiveLiquidity: 0.01979196071624756 ms
> awaited promises (calculateSwap, getActiveLiquidity): 942.6627079248428 ms

## Proposed Solution
How well do you think a cache would do here, that updates by reading the contract multiple times a second?
NOTE: Need to decide which calls we optimize for if not just `calculateSwap`

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Connext is always

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/lUA9WjpFoA/estimate/28) in Backlog Prio 1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/8) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/15) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/16) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/13) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/26) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by just-a-node** [comment]
@liu-zhipeng I used [performance.mark()](https://developer.mozilla.org/en-US/docs/Web/API/Performance/mark) API to get these splits within the function.

**Comment by rhlsthrm** [comment]
Working on bypassing RPC call for calculating amount received.

**Comment by liu-zhipeng** [comment]
![image](https://user-images.githubusercontent.com/57480598/232790998-d19ed8a4-73ee-4091-a083-ef9ae7a488ba.png)

Calculated receive amount in 2ms in locally based from pool information instead of calling rpc

**Comment by rhlsthrm** [comment]
Fixing coverage of tests.

**Comment by rhlsthrm** [comment]
Ready for merge into main.
