### ISSUE TITLE
Linea zkEvm not working on testnet

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3906]
**Describe the bug**
See title.

**To Reproduce**
1. Go to https://testnet.bridge.connext.network/TEST-from-optimism-to-linea?amount=1
2. See console errors.

**Additional context**
Check docs to make sure everything is set up right.

https://docs.linea.build/developers/use-message-bridge

**Comment by alexwhte** [comment]
Will fix with #4014
