### ISSUE TITLE
[L-1] Lack of check regarding ERC721 standard compatibility

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3914]
Currently, there are no checks in NFT Hashi contracts to verify whether an NFT being transferred follows the ERC721 standard or not. This could have adverse effects if someone mistakenly passes a non-compatible NFT.

**Resolution To Consider:**

One possible resolution is to add a check in `xCall` to verify if the passed asset follows the ERC721 standard using the [supportsInterface](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ca822213f2275a14c26167bd387ac3522da67fe9/contracts/token/ERC721/ERC721.sol#L52) function.

**Comment by taijusanagi** [comment]
I modified the code here.
https://github.com/nfthashi/monorepo/pull/140/commits/ec3db2aef5f08d811adde2e53c4cd325240251d9

- Contract now checks if the transferring asset supports the ERC721 interface
- Added unit testing for the changes
