### ISSUE TITLE
[L-2] Lack of check for tokenURI length 

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3915]
One concern NFT Hashi team themselves brought up is what if `tokenURI` length is so huge that decoding on the destination goes beyond the gas limits of the associated destination, and NFT remains locked on the source.

It is a valid concern given gas limits on the destination can differ from the source but is not likely to occur.

**Resolution To Consider:**

Consider determining the maximum acceptable length based on the maximum gas limits of all chains you intend to support and explicitly checking it in all xCalls.

**Comment by taijusanagi** [comment]
I modified it here.
https://github.com/nfthashi/monorepo/pull/140/commits/f02f2e1f2b07ad5a3e2aa688bf72457cda3f6014

- Added token URI length limit in the initializer
- Added token URI length limit set function with onlyOwner
- Added unit testing for the change
- Set initial length as 1000

The desired token URI length is not defined, but for testing purposes, I set it as 1000 for now.
