### ISSUE TITLE
[Q-1] There is no need to use OZ's _msgSender().

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3916]
The NFT Hashi contracts currently use OZ's _msgSender() function instead of msg.sender. As there are no plans to enable meta transactions, consider using vanilla msg.sender.

**Comment by taijusanagi** [comment]
I modified it here
https://github.com/nfthashi/monorepo/pull/140/commits/54638bfad3ac6a402afd17fc1283fe9a37cf3fb4

- Replace all _msgSender() to msg.sender
- Unit test works fine without script change
