### ISSUE TITLE
[Q-2] There is no need to pass slippage parameters inside xCall

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3917]
Since no assets are being transferred, the slippage parameter is redundant. Consider defaulting it to a constant, as is done for assets and amounts.

**Comment by taijusanagi** [comment]
I modified it here.
https://github.com/nfthashi/monorepo/pull/140/commits/a229c661ac9ad908105261713898a90b4af86223

- remove slippage from the parameters.

Also updated integration test
https://github.com/nfthashi/monorepo/pull/140/commits/f4c4c4f15f75b53c7fa5f8ad4df1847832f96d49

Also update frontend 
https://github.com/nfthashi/monorepo/pull/140/commits/1243a4bb97c9809cefe1cb95f0b87710474090a3
