### ISSUE TITLE
[I-1] Using setBridge enables the owner to access all locked NFTs.

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3918]
NFT Hashi contracts allow owners to configure the bridge contract address of their project on different destinations with `setBridge`. However, this exposes all NFTs locked on that contract if the owner's key is compromised.

The owner can set the bridge contract as themselves and perform a dummy `xReceive`. 
This will convince the source contract that the NFT on the destination is burned and would allow the owner to release NFT to any address.

**Comment by rhlsthrm** [comment]
**Complexity: 3**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/7) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/13) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/14) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Complexity: 3**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/12) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/23) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/24) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
