### ISSUE TITLE
[I-2] If bridges mapping is not in sync across all supported chains, it can lock NFTs on the destination chain.

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3919]
The xReceive function includes a check to verify if the origin sender is allowed the bridge of the source domain. However, if the NFT Hashi team misses updating or adding a bridge for a particular origin at the destination, this check will fail and potentially lock the NFT at the source.

**Comment by rhlsthrm** [comment]
**Complexity: 5**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/6) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/11) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/12) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Complexity: 3**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/11) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/21) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/22) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
