### ISSUE TITLE
Seeing ETH NoBidsReceived

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3921]
**Describe the bug**
I see this status on ~~5~~ 4 transfers. 

20 eth Ethereum to Optimism
https://connextscan.io/tx/0x02d129f8367522d0d9fe2d1265f885fa7e341424595f9d31feeff47bf36653bc

21 nextETH local Ethereum to BNB
https://connextscan.io/tx/0xf46a508546628d7d716b0d42abe7ef87ae4f7ec18854c25ef034bf093a313ebb

2 of them are 0-value so im assuming a UI issue maybe  (edit: long running so maybe something else)

[Completed] This was low value Polygon to BNB... it was temporary and i dont have a screenshot as it just resolved itself though...
https://connextscan.io/tx/0x63725ca91c99e025e2721a34735dd22ef9db0b877ae5f6e28ff60bfb46194b43

**To Reproduce**
1. Go to https://connextscan.io/transfers
2. Filter by NoBidsReceivedError

**Additional context**
![image](https://user-images.githubusercontent.com/37959170/229644260-6528f0c0-1df0-4f5e-9576-6e18b0e769d4.png)

**Comment by alexwhte** [comment]
not sure if related https://github.com/connext/monorepo/issues/3863

here's another 
https://connextscan.io/tx/0x9801a22e9d5ed5ebced57c84f4e66babe9c30821e4d72d84998160fb4f904e80

i found one that was like .0011 ETH with this error that then completed the next time i looked
![image](https://user-images.githubusercontent.com/37959170/229646079-70273c25-82f5-4aa6-9e20-2f7ff6070f6f.png)

**Comment by alexwhte** [comment]
Main questions for this bug
1. Are we showing this error in carto incorrectly? in what cases? let's fix this
2. Are we showing it correctly for any of the transfers? ie this would not have slippage because it is a local receive. In this case - if correct - why is it not receiving bids?  https://connextscan.io/tx/0xf46a508546628d7d716b0d42abe7ef87ae4f7ec18854c25ef034bf093a313ebb

**Comment by liu-zhipeng** [comment]
https://app.datadoghq.com/logs?query=service%3Alighthouse-sendoutboundroot&cols=container_name&event=AgAAAYdKIW-L-gmjHwAAAAAAAAAYAAAAAEFZZEtJWHlnQUFCQ1JoaUJ1OGxMbEFBSgAAACQAAAAAMDE4NzRhMjktNjA3NS00ZTE3LWIzMDQtYjdjZmZkMDc3ZTFl&index=mainnet-production&messageDisplay=inline&saved-view-id=1288966&stream_sort=time%2Cdesc&viz=stream&from_ts=1680489788666&to_ts=1680576188666&live=true

**Comment by liu-zhipeng** [comment]
SendOutboundRoot is not working on mainnet. Sending tx to gelato is failing.

**Comment by liu-zhipeng** [comment]
https://etherscan.io/tx/0xd8d036bbac335f2941cf089973dcc28b52785bb41d53d21064399f514d872940

Tried to sendoutboundroot via our connext relayer on local and worked

**Comment by liu-zhipeng** [comment]
https://connextscan.io/tx/0x02d129f8367522d0d9fe2d1265f885fa7e341424595f9d31feeff47bf36653bc

https://connextscan.io/tx/0x63725ca91c99e025e2721a34735dd22ef9db0b877ae5f6e28ff60bfb46194b43

Processed!

**Comment by liu-zhipeng** [comment]
https://connextscan.io/tx/0xf46a508546628d7d716b0d42abe7ef87ae4f7ec18854c25ef034bf093a313ebb

Processed!

**Comment by rhlsthrm** [comment]
This issue was because the RelayerProxyHub wasn't configured properly and was trying to send funds (0) back to the Gelato address which can't accept funds. Even if it's 0 funds, the TX reverts.
