### ISSUE TITLE
Visualize router TVL distribution + Utilization in Explorer

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3922]
## Problem
We don’t know how to view ways to distribute liquitidy as a whole based on end user bridging changes
how routers are allocating individually

## Impact
We need this urgently to support bridging experience, debugging, and support routers to improve liquidity distribution ( #3921)

## Proposed Solution
Visualize this in the main router page
https://connextscan.io/routers

1. Show Liquidity Distribution 
net liquidity by asset + by chain with `routers_with_balances` table
2. Show Liquidity Utilization
volume/router_tvl_balance = router utilization
able to view this split by (chain(destination) + asset)
Current state is acceptable over a time series, but we will look into this  

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- Able to see 1 and 2 above in Explorer routers page. 
- This is in a TEST UI version before we make public

**Comment by alexwhte** [comment]
@pjenviri please visualize these in charts at the top of the view under the topline data we have already. 
![image](https://github.com/connext/monorepo/assets/37959170/4792516e-112b-46da-8e4a-679646a44d2b)

I immediately think of pie charts but please do what you think makes sense 
Visualize net Active TVL
- by asset
- by chain
- by router

and capital utilization (volume/TVL) by chain by asset

**Comment by sanchaymittal** [comment]
we can use daily_transfer_volume to fetch the above required data.

**Comment by pjenviri** [comment]
added charts by asset and by chain, and also added the `cumulative share%` column for each router. They are in _test_ mode
https://connextscan.io/routers?mode=test

**Comment by alexwhte** [comment]
Thanks this is getting better. Can we please try these? 
1. Show TVL by chain + by asset as a horizontal stacked bar chart? By asset on the Y axis, segmented by chain in each bar
2. Show topline Utilization as a different horizontal stacked bar.  By asset on the Y axis, segmented by chain in each bar
3. The cumulative visualization is cool, but I think a 'Relative Share %' metric  is more interesting. 
So we can still show the same visual but the % value would be bettter as 22.9% and 20% (individual vs cumulative) 
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/12c2a345-84c4-486e-8a24-801814c9d817)

**Comment by pjenviri** [comment]
1 done
2 done (we added the Utilization section)
3 done
