### ISSUE TITLE
Infinite approval updates 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3923]
## Problem
Users are turning off `infinite approval` each time they transfer 

## Impact
Users are complaining and it could make Connext look bad / dismissive.

## Proposed Solution
A few things we will test
1. Change infinite approval default to 'FALSE'
2. Move infinite approval to the main screen under slippage https://bridge.connext.network/USDC-from-ethereum-to-binance

## Acceptance Criteria
- [ ] See proposed solution

**Comment by alexwhte** [comment]
@pjenviri can you do #2?

**Comment by pjenviri** [comment]
@alexwhte , We have already updated the infinite approval feature but limit its appearance to only when necessary. It will now only appear on the main screen when the user needs to approve a particular token. Always showing it may lead to confusion that they can revoke it on the UI and start finding where to click it.
