### ISSUE TITLE
Determine gas costs for month of March 

### ISSUE THREAD

**Issue by sarahb1234** [connext/monorepo#3924]
## Problem
Protocol is expensive to operate and we don't know exactly how much we're spending 

## Impact
Runway 

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/5) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/10) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/19) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/20) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
stale, closing
