### ISSUE TITLE
Add support for DAI

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3928]
Add support for transferring DAI in the protocol.

After discussion with Maker, it looks like there isn't a meaningful pathway for us to be able to do 1:1 DAI mint/burn for realistically another 6+ months. Given that there is a lot of demand for DAI from GnosisChain and other partners, we cannot afford to wait to support it. So instead, I think we should support DAI using the normal nextDAI-DAI stableswap flow.

Steps to add support:
- [ ] Whitelist DAI in the protocol
- [ ] Deploy nextDAI-DAI pools on each chain
- [ ] Add support for DAI in SDK, docs, and other supplementary tooling
- [ ] Add DAI as an asset on ConnextScan
- [ ] Add DAI as an asset on the Bridge UI
- [ ] Onboard routers to supply DAI liquidity
- [ ] Prepare and publish a community announcement about the new asset listing
- [ ] Add DAI to liquidity bootstrapping campaign

**Comment by rhlsthrm** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/4) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/7) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/8) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
@LayneHaber to start on this task.

**Comment by rhlsthrm** [comment]
Signed multisig txs.
