### ISSUE TITLE
Add support for USDT

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3929]
Add support for transferring USDT in the protocol.

Steps to add support:

- [ ] Whitelist USDT in the protocol
- [ ] Deploy nextUSDT-USDT pools on each chain
- [ ] Add support for USDT in SDK, docs, and other supplementary tooling
- [ ] Add USDT as an asset on ConnextScan
- [ ] Add USDT as an asset on the Bridge UI
- [ ] Onboard routers to supply USDT liquidity
- [ ] Prepare and publish a community announcement about the new asset listing
- [ ] Add USDT to liquidity bootstrapping campaign

**Comment by rhlsthrm** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/3) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/5) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/6) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Signed multisig txs.
