### ISSUE TITLE
Improve ToS design

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3930]
## Problem
Improve image 
![image](https://user-images.githubusercontent.com/37959170/230136094-2aa9b2e6-9450-4f2f-8f93-4f64825de7e0.png)

## Proposed Solution
We should make the design better here 
- Make the box lighter, or the background lighter, so there's clear contrast
- Increase margins maybe, it's too squeezed? 
- Increase size of the font for 'Welcome to Connext Bridge.' (capitalize 'B') 
- Put in a test mode

**Comment by pjenviri** [comment]
Adjusted and updated it on testnet. Let us know if you want to deploy this update to mainnet.

**Comment by alexwhte** [comment]
This looks better! Can we make it look like this? 

<img width="730" alt="image" src="https://user-images.githubusercontent.com/37959170/230707687-a0d8d2b9-8205-4b97-b593-d012d84c77c9.png">

We will never ask you for your private keys or seed phrase.

This is beta software subject to change. For guidance, please refer to our [documentation](https://docs.connext.network/).

I am requesting a figma file  for this as well.

**Comment by alexwhte** [comment]
is this still working?  i tried in 3 browsers with data cleared and VPN but seem unable to test it

https://bridge.connext.network/USDC-from-ethereum-to-binance

**Comment by pjenviri** [comment]
The styling has been updated, except for the URL of the _security model_. Can you share the URL? So we'll add it to the modal. 

The modal is only on testnet, as mentioned in https://github.com/connext/monorepo/issues/3930#issuecomment-1498597061. So please let me know if you are okay with pushing it to mainnet.

**Comment by pjenviri** [comment]
Updated.
