### ISSUE TITLE
Deploy optimistic roots to staging

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3934]
## Problem
Need to deploy optimistic roots branch `optimistic_roots` to staging

## Impact
Transfer cost reduction.
Quality of the upgrade depends on testing on staging

## Proposed Solution
Merge onchain and offchain PRs
Tie all loose ends, getting the merged brand to build and deploy

Subtasks:
- [ ] https://github.com/connext/monorepo/issues/3976

## Acceptance Criteria
- [ ] Fast path transfers are successful in op mode
- [ ] Slow path transfers are successful in op mode

**Comment by rhlsthrm** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/2) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 5**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/3) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Close this task out, rewrite task to reflect the actual task that is being done this sprint @preethamr .

**Comment by preethamr** [comment]
The Connext side of the task is tracked here:
https://github.com/connext/monorepo/issues/4010
