### ISSUE TITLE
NFT Hashi mainnet deployment

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3935]
## Background

Deploy NFT Hashi to mainnets after post-audit changes.

## Tasks

- [ ] Determine deployer ownership
- [ ] Setup multisig
- [ ] Deploy to mainnet chains and set up

**Comment by rhlsthrm** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/m6kwOazA4M/estimate/1) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/1) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/m6pgrIxPdS/estimate/2) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/9) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/17) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
**Urgency: 3**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/18) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
