### ISSUE TITLE
[UI] Destination gas fee selector improvement

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#3954]
## Problem
- The dropdown list looks very HTML-default-y
- Users might not notice that they can select the token to pay for the fee

## Impact
General UX improvement to show flexibility to the user

## Proposed Solution
- Change the dropdown list to something that looks more polished, more rounded like the rest of the UI
- Maybe add some light glow or something that indicates to the user that they can select the asset they want to pay the relayer fee with
- Make the relayer fee bigger and more noticeable when paying with the token that's being sent
![image](https://user-images.githubusercontent.com/84744304/230959023-15b576f0-8cbd-4c6e-84f3-3d83a52d36f2.png)

**Comment by alexwhte** [comment]
Can we please remove this being displayed inside the box like this? Agree it looks bad
