### ISSUE TITLE
Sdk method to generate `swapData` for chain abstraction support

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#3971]
## Background

Difficult to format `swapData` used in`SwapAdapter` template. Sdk should provide a method to generate `swapData` given the protocol, the input token, amount, and the output token.

## Definition Of Done

Sdk has a method to generate `swapData` given user inputs.

## Tasks

- [ ] Generic method to generate `swapData`
- [ ] Method takes in protocol designation, input token, amount, and output token

**Comment by LayneHaber** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/mhZ41q7j3O/estimate/4) in Sprint Poker #​​29

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Impact: 4**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/7) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
**Urgency: 4**
  [See the discussion](https://action.parabol.co/meet/mi1RgQ7yzS/estimate/8) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Tasks here:

- Create a separate package called @connext/chain-abstraction that has a separate base class.
- Base class should have a top-level method called `getXcallCalldata` which takes in `forwardCallData`, `inputToken`, `inputAmount`, and `slippage`.
- We then will query appropriate DEXs and generate the swaps.
- Return fully encoded data which user can directly input into `xcall`.

**Comment by rhlsthrm** [comment]
In progress.

**Comment by rhlsthrm** [comment]
Still in progress. No blockers.

**Comment by rhlsthrm** [comment]
SDK MVP is basically done, dealing with complexities, will get review.

**Comment by rhlsthrm** [comment]
@rhlsthrm to focus on integration docs. 
Everything done except unit tests.

**Comment by rhlsthrm** [comment]
Closing as completed.
