### ISSUE TITLE
[Bridge UI] Gnosis/Karpatkey feedback

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#3973]
"After approving the first transaction in safe, it took us some time to realize the tx was to approve Connext to move funds. There was no pop up to signal it. This oc generated some anxiety on the other person because he wasn’t sure whether funds were sent or not. On top of it, the CTA got stuck on loading and never reacted to the tx success nor let us actually send the amount. We had to reload the site and click on “Send” again for it to trigger the second tx (actually sending the tokens).

We followed the tx status from connextscan. It has really good info. One minor UX glitch is that the tx never moves from “in progress” to “success” on its own. A site refresh is needed. This is kind of also generates a bit of anxiety when several minutes pass and the tx is still progressing. Once reloaded, the site shows the tx passed several min ago."

**Comment by pjenviri** [comment]
I understand that the current UI is similar to the above post from Arjun. I couldn't reproduce both issues. Please let me know if you find them.
