### ISSUE TITLE
Document Optimistic Roots OffChain Infra

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3997]
## Problem
Document the architecture, message flow, and contract interactions of off-chain infra.

## Impact
Help with audit. Serves as a reference for how off-chain infra will interact with the contract changes

## Proposed Solution
Gather finalized core logic and describe the mechanics, extend existing tech spec, and add a visual the provides a full view

## Acceptance Criteria
- [ ] Document that is public
- [ ] Message flow diagram

**Comment by rhlsthrm** [comment]
Syncing with @LayneHaber to figure out what docs are needed here.

**Comment by rhlsthrm** [comment]
Found out what is needed, will add to Notion docs.

**Comment by rhlsthrm** [comment]
Documented offchain docs and hand off to @LayneHaber.

**Comment by preethamr** [comment]
Provided the needed input to audit.

https://www.notion.so/connext/Messaging-Layer-Audit-Scope-826b9ac2d43d47bf9f46bb4145aa6527?pvs=4#4c238bb58d6844c6a5b4e65171aa7e6f
