### ISSUE TITLE
Defi Wonderland Task List

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3998]
## Problem
Get optimistic roots working on staging testnet. Off-chain changes for optimistic roots, needs to reviewed, improved, and finalized.

This is a task for tracking and coordinating with Defi Wonderland, the work that needs to be done on staging.

This will span multiple Connext weekly sprints.

## Impact
Quality and performance of the optimistic roots release. This is a prerequisite for running all test scenarios, and going through the contract upgrade checklist.

## Proposed Solution
Complete https://www.notion.so/defi-wonderland/Off-Chain-Task-List-f2246a5ec509447a97a0f13900995115

## Acceptance Criteria
- [ ] [Task List](https://www.notion.so/defi-wonderland/Off-Chain-Task-List-f2246a5ec509447a97a0f13900995115) is completed

**Comment by LayneHaber** [comment]
@preethamr this looks like its getting broken out into other issues, do we want to keep this or close it in favor of the constituent tasks?

**Comment by alexwhte** [comment]
closing in favor of epic
