### ISSUE TITLE
Coordinate with DW on the staging bring up

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4010]
## Problem
Bring up `staging` testnet and off-chain agents.
Resolve this [task list](https://www.notion.so/defi-wonderland/Off-Chain-Task-List-f2246a5ec509447a97a0f13900995115) 

## Impact
A working staging environment is a perquisite for completion of work on optimistic roots enhancement. 

## Proposed Solution
Act on any requests from DW, regarding staging infra, dev-ops, tests, business logic, and code base.
Review PRs from DW

## Acceptance Criteria
- [ ] DW handing off completed off-chain for optimistic roots

**Comment by rhlsthrm** [comment]
Bring back task to do lighthouse implementation.

**Comment by rhlsthrm** [comment]
Finalized PR merged to staging. Deploy contracts. Getting input from @LayneHaber.
