### ISSUE TITLE
Unable to access My Positions in the pools page

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4011]
**Describe the bug**
![image](https://user-images.githubusercontent.com/84744304/233177873-b65882ee-ac89-43fa-9cdc-1ecbc1fb6a67.png)

**To Reproduce**
1. Go to the Pools page and select My Positions

**Additional context**
The past couple of weeks we've had people with random Alchemy CORS policy issues so pools wouldn't load for them. This doesn't look like that

**Comment by pjenviri** [comment]
The issue is on the SDK side. Eddie already [fixed](https://discord.com/channels/992549151134982234/1032671441084235828/1098398652709474334) it.
