### ISSUE TITLE
Transfers asset_usd_price column errors

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4012]
Price is being logged multiple times I believe. For example transfer `0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f` is USDC but has 4 prices including ETH in the table. 

```select transfer_id, origin_transacting_asset, asset_usd_price, update_time from transfers_with_price where transfer_id = '0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f'```

Result

| transfer\_id |origin\_transacting\_asset |asset\_usd\_price |update\_time |
| --- | --- | --- | --- |
| 0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f |0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 |1.001 |2023\-04\-16 00:35:15.019869 |
| 0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f |0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 |1 |2023\-04\-16 00:35:15.019869 |
| 0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f |0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 |2095.33 |2023\-04\-16 00:35:15.019869 |
| 0xe5323be52c1d29ac02e3da78e7393d36cef13af545e0d1625fc5412d422caa9f |0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 |1.002 |2023\-04\-16 00:35:15.019869 |

**Comment by alexwhte** [comment]
any chance i am writing this query wrong?

**Comment by rhlsthrm** [comment]
Transfers side completed, router liquidity still in progress.

**Comment by rhlsthrm** [comment]
Fixed double volume issues on explorer and DB.
