### ISSUE TITLE
Create fallback for Gelato price API failure

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4014]
## Background

If the Gelato price API fails or doesn't support a chain, the UI fails and we are unable to send a transfer to or from that chain.

Unblocks Linea zkEVM.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Gelato API has a fallback. 

## Tasks

- [ ] Create mechanism to use "mainnet equivalent" assets from chainData.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/mtALUnLIaI/estimate/6) in Sprint Poker #​​31

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by just-a-node** [comment]
Adding to new sdk spec.
