### ISSUE TITLE
Remove deprecated commands from GitHub CI

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4015]
## Background

We are using some commands that are deprecated and our CI will stop working in a few weeks.

### Linked Issues & Documentation

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

## Definition Of Done

GitHub CI does not show errors for deprecated commands anymore.

## Tasks

- [ ] Replace deprecated commands.

**Comment by alexwhte** [comment]
**Complexity: 5**
  [See the discussion](https://action.parabol.co/meet/mtALUnLIaI/estimate/5) in Sprint Poker #​​31

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
