### ISSUE TITLE
LH Propose task on staging

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4017]
## Problem
LH Propose pending tasks for optimistic roots functionality

## Impact
Part of the optimistic roots testnet bring up, needed to unblock further steps to lowering costs.

## Proposed Solution
- [x]  LH Propose  (70 % done)
    - [x]  Implement virtual merkle tree to get the the virtual aggregate root for proposal, using existing db backed SMT
    - [x]  Implement call to contract using relayer
        - [x]  Prepare params needed for propose calls
        - [x]  Bind `proposeAggregateRoot` to encode function `encodeFunctionData`
    - [x]  Update DB state to `processed`  for all snapshot roots with ID <= this snapshotId

## Acceptance Criteria
 - [ ]  Reviewed and approved business logic

**Comment by rhlsthrm** [comment]
Later today continue with progress.

**Comment by rhlsthrm** [comment]
Still in progress. Need to deploy on staging.

**Comment by rhlsthrm** [comment]
Currently blocked by contract deployment. Bring contracts into staging. Everything else is done.

**Comment by preethamr** [comment]
This was unblocked thanks @rhlsthrm !
