### ISSUE TITLE
LH ProveAndProcess task on staging

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4018]
## Problem
Complete LH ProveAndProcess pending tasks for optimistic roots functionality

## Impact
Part of the optimistic roots testnet bring up, needed to unblock further steps to lowering costs.

## Proposed Solution
- [x]  Review logic to detect system mode
- [x]  `proveAndProcessOpMode`
    - [x]  Should get the latest snapshot for which the aggregate was received on the destination domain
- [x]  `processMessages`
    - [x]  Improve core logic
    - [x]  Improve DB queries
    - [x]  Implement virtual merkle tree to get the the virtual aggregate root for proposal, using existing db backed SMT
   
## Acceptance Criteria
- [ ] Reviewed and approved business logic

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/mtALUnLIaI/estimate/4) in Sprint Poker #​​31

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Finished, will QA with new contracts on staging.

**Comment by preethamr** [comment]
To be integration tested.
