### ISSUE TITLE
Integrate chain-abstraction sdk on midas repo

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4035]
## Problem
Once we have @connext/chain-abstraction package published on npm, we need to integrate it into midas UI stuff.

**Comment by rhlsthrm** [comment]
In progress by @liu-zhipeng.

**Comment by rhlsthrm** [comment]
First step: Integrate SDK into Midas UI origin side.

**Comment by rhlsthrm** [comment]
This is done, working on UI
