### ISSUE TITLE
Doc updates for Chain Abstraction

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4037]
## Problem
_What problem are we solving?_ 

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by alexwhte** [comment]
@just-a-node who should QA? or do you need me to?

**Comment by just-a-node** [comment]
Waiting for audit changes that may need updating these docs:

https://documentation-git-revert-103-revert-101-3-31d64b-connextproject.vercel.app/
