### ISSUE TITLE
Optimistic-v1 Manual Testing - Happy Path

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4042]
## Definition Of Done

The below tests have been run and pass successfully (note that they do not have to run within CI/CD).

Successful test metrics:

- User receives funds before slow path reconcile event
- User funds are the correct amount
- Relayer fee in transacting asset
- Relayer fee in native asset
- Router get paid back through slow path, the correct amount

## Tasks

- [ ]  Successful message sending in fast mode from all spokes
- [ ]  Successful message sending in slow mode from all spokes

**Comment by alexwhte** [comment]
@LayneHaber please close and replace

**Comment by LayneHaber** [comment]
edited the issue to more accurately reflect needs.

**Comment by alexwhte** [comment]
@rhlsthrm plesae break this up 
in scope this sprint
 Successful message sending in fast mode from all spokes
 Successful message sending in slow mode from all spokes

**Comment by alexwhte** [comment]
Trying to resolve staging first and then we can tackle it again. Not currently in progress until we fix this

**Comment by sanchaymittal** [comment]
This task only covers happy path testing for OptMode v1

**Comment by sanchaymittal** [comment]
done.
