### ISSUE TITLE
Midas UI Updates 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4045]
## Problem
Once we have the basic integration done, we will need to update the Midas UI 

## Proposed Solution
Do not require user to be on the pool’s chain when clicking ETH asset.
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/f0fade1b-5eae-4380-8883-23a00629b939)

Add ability to choose a chain to supply from. Choosing a different chain will go through the xcall path.
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/ad64a3c9-681c-413e-8735-475514c8daa3)

## Acceptance Criteria
- [ ] As a user I can supply ETH to pools from any chain
- [ ] Slippage and estimated amounts are clear to me
- [ ] Fees are clear to me

**Comment by rhlsthrm** [comment]
Updating target contract and integrating into SDK/UI now.

**Comment by rhlsthrm** [comment]
Released new chain-abstraction SDK for changes. Basically done, debugging and testing.

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/releases/tag/chain-abstraction-v1.0.2-alpha.8
- Pancake V3 SwapRouter issue fixed.
- A bug fixed in SwapAndXcall.sol
- Redeployed both of bnb and polygon chain 
- Relesed new chain-abstraction SDK

Finally midas UI is basically working with chain-abstraction sdk

**Comment by rhlsthrm** [comment]
* Add functions to chain abstraction SDK to estimate swap outputs.
* https://github.com/connext/monorepo/issues/4077

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/issues/4098

**Comment by rhlsthrm** [comment]
Working on estimate amount.

**Comment by liu-zhipeng** [comment]
[Estimate ](https://github.com/connext/monorepo/issues/4098)

Estimating swap output is done and tested.
I created an issue on connext-integration repo and once merged and deployed, we can complete Midas integration.

**Comment by liu-zhipeng** [comment]
https://64585fdc792bc95922748ced--preview-midascapital.netlify.app

**Comment by alexwhte** [comment]
Moving as done. We will file new individual needs as the ycome up
