### ISSUE TITLE
UI not working in Safari

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4046]
in Safari browser I only see this 

![image](https://user-images.githubusercontent.com/37959170/234167834-42ac4942-512c-45b2-a400-a0715bfb2b67.png)

Pools not loading 
![image](https://user-images.githubusercontent.com/37959170/234167850-82af0a63-3cbf-41c3-9c46-9864b42fff2e.png)

**Comment by alexwhte** [comment]
If we can't get this to work we should display an error "Sorry, the UI is not currently supported in Safari browser."

**Comment by alexwhte** [comment]
Layne was unable to replicate... if you have Safari can you check? We can probably close if it's just me

**Comment by pjenviri** [comment]
I tested with 3 laptops, but I could not reproduce the issue.  ![safari.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/735ecd63-f379-4ff0-9772-5bed4b0e68f4)
