### ISSUE TITLE
Enable USDT and DAI in Mainnet UIs (closed beta tester version)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4047]
See spec https://www.notion.so/connext/Spec-Add-USDT-and-DAI-Support-66cc3c232582420e858bdfef98fe5606

## Proposed Solution
1. Create a test version of our current UI that is not for the public, but for our beta tester community. 
Add the new asset addresses for USDT and DAI
3. Add a banner that says "WARNING: This an early alpha release for testing only. Use at your own risk."

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] I can bridge USDT between chains
- [ ] I can bridge DAI between chains
- [ ] I can receive local for both
- [ ] I can add USDT and DAI liquidity
- [ ] I can remove USDT and DAI liquidity
- [ ] I can swap USDT and DAI
- [ ] I can see these assets in the Explorer pages
- [ ] I can add and remove router liquidity for USDT and DAI

This will enable a future public launch next week

![image](https://user-images.githubusercontent.com/37959170/234169619-34821003-cdc6-4e5d-9741-35abc155ba47.png)

**Comment by pjenviri** [comment]
@alexwhte I cannot access the page: https://www.notion.so/connext/Spec-Add-USDT-and-DAI-Support-66cc3c232582420e858bdfef98fe5606

**Comment by rhlsthrm** [comment]
Arbitrum:
nextDAI - https://arbiscan.io/address/0xfde99b3b3fbb69553d7dae105ef34ba4fe971190
nextUSDT - https://arbiscan.io/address/0x2fd7e61033b3904c65aa9a9b83dcd344fa19ffd2

Optimism:
nextDAI - https://optimistic.etherscan.io/address/0xd64bd028b560bbfc732ea18f282c64b86f3468e0
nextUSDT - https://optimistic.etherscan.io/address/0x4cbb28fa12264cd8e87c62f4e1d9f5955ce67d20

Polygon:
nextDAI - https://polygonscan.com/address/0xadce87b14d570665222c1172d18a221bf7690d5a
nextUSDT - https://polygonscan.com/address/0xe221c5a2a8348f12dcb2b0e88693522ebad2690f

Gnosis:
nextDAI - https://gnosisscan.io/address/0x0e1d5bcd2ac5cf2f71841a9667afc1e995caaf4f
nextUSDT - https://gnosisscan.io/address/0xf4d944883d6fddc56d3534986fef82105cadbfa1

BNB:
nextDAI - https://bscscan.com/address/0x86a343bcf17d79c475d300eed35f0145f137d0c9
nextUSDT - https://bscscan.com/address/0xd609f26b5547d5e31562b29150769cb7c774b97a

**Comment by pjenviri** [comment]
PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/121. Please test it out at https://connext-bridge-mainnet-git-feat-add-usdt-dai-coinhippo.vercel.app.
