### ISSUE TITLE
Coldstart USDT and DAI active and passive TVL 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4048]
## Problem
For the beta tester community to help us test USDT and DAI in our UIs, we need to source the initial liquidity

## Proposed Solution
Add 4K/chain/asset (?) into passive liquidity 
Add 1K/chain/asset (?) into active liquidity
Users will be instructed to test with small amounts ONLY

## Acceptance Criteria
Add initial liquidity to coldstart for testing 
Users have suffiicent to perform basic test actions

**Comment by rhlsthrm** [comment]
@rhlsthrm working on this today.

**Comment by rhlsthrm** [comment]
Got USDT and DAI bridged, need to add LPs and router liquidity.
