### ISSUE TITLE
Integrate chain abstraction SDK in Mean 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4052]
## Problem
_What problem are we solving?_ 

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by sanchaymittal** [comment]
Here is the mean UI repo: https://github.com/Mean-Finance/dca-fe

- [ ] create a repo fork under Connext and install sdk dependencies under repo.
- [ ] https://github.com/Mean-Finance/dca-fe/tree/main/src/services, Under services kickstart connext sdk setup.
- [ ] move preparing functions like preparing params under utils to keep functional and modular approach to integration, https://github.com/Mean-Finance/dca-fe/tree/main/src/utils
- [ ] test out the sdk setup by intiating UI and logging out the responses to some getter functions.

**Comment by sanchaymittal** [comment]
pr: https://github.com/connext/dca-fe/pull/1

**Comment by rhlsthrm** [comment]
Updated SDK, need to pull into app and set up.
