### ISSUE TITLE
Update Mean UI

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4053]
## Background

Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by rhlsthrm** [comment]
Most UI is completed. Need to deploy contracts.

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/dca-fe/pull/3

**Comment by prathmeshkhandelwal1** [comment]
Still need testing for deposit on hub contract

**Comment by rhlsthrm** [comment]
Fixed config issues, did not need cracow. Remaining testing.

**Comment by prathmeshkhandelwal1** [comment]
- `swapandxcall` deployed on arbitrum
- Have to add `uniV3` swapper to the contract, getting error because of that. 
- next steps would be final testing without above dependencies and few UX changes

**Comment by alexwhte** [comment]
@prathmeshkhandelwal1 @rhlsthrm Do i need to QA this? Can you share the beta link

**Comment by alexwhte** [comment]
Marking as done. We will file new individual needs as they come up
