### ISSUE TITLE
 Destination gas fee selector confusing when bridging to/from ETH-native chains

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#4054]
## Problem
_Destination gas fee selector is giving the user the option to use "aETH" or "ETH" in an ETH<->ETH transaction (see img) to pay for gas. This isn't necessary since it's the same to pay in ETH from "sent asset" or from "wallet gas" on ETH-native chains ARB, OP and Mainnet._ 

## Impact
_Users may find it confusing, since they may think one of the options means they can pay the fee on the destination chain, or some other alternative. 👉 Happened to a friend of mine._

## Proposed Solution
_Only showing one option: "ETH". 👉 With **no** selector._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] I can understand in which asset i'm going to pay for the destination gas fee.

![image](https://user-images.githubusercontent.com/89958919/234177816-304c6f11-9479-4e9f-940c-1f0c5668e8c8.png)

**Comment by alexwhte** [comment]
Closing in favor of the #4093
