### ISSUE TITLE
Create xreceiver contract for Mean

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4055]
## Problem
_What problem are we solving?_ 
Creating contracts for Mean Finance.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
Need to build chain abstraction use cases to test our assumptions.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
Create xReceiver contract that follows the SwapAndForward template.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] xReceiver contract is completed.

**Comment by sanchaymittal** [comment]
Next steps:
- [ ] create target contracts for mean finance ( deposit function for mean finance)
- [ ] write unit test and push for 100% coverage

**Comment by sanchaymittal** [comment]
pr: https://github.com/connext/connext-integration/pull/10

**Comment by rhlsthrm** [comment]
Started on unit tests.
