### ISSUE TITLE
Default wallets for WalletConnect's selector

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#4056]
## Problem
_The new version of WalletConnext's selector shows only 3 default wallets._ 
![image](https://user-images.githubusercontent.com/89958919/234198053-14af33aa-e10e-4d91-9287-e1b092518b3b.png)

## Impact
_To provide better UX, let's focus in showing the most used wallets first._

## Proposed Solution
_Let's pick the top 3 wallets to be shown at start. My suggestion:_
1. Metamask
2. Rabby
3. Brave Wallet

Other possibilities that come to mind are Coinbase Wallet, Rainbow, Trust, etc.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Most of the time I can quickly find the wallet I use to connect to the site.

**Comment by pjenviri** [comment]
Updated the first 3 wallets and set the order of other wallets following the suggestion above.

**Comment by 0xanedi** [comment]
![image](https://user-images.githubusercontent.com/89958919/234347478-dc2304cc-ebcb-40a5-add8-31cfbe2a84bf.png)
Getting this error. I'm using Rabby. I works when clicking on Metamask, but no luck when clicking on Rabby, which is odd. 
Generally iti is known that, since Rabby is based on MM, you can click on both and it will still work.

**Comment by alexwhte** [comment]
Can we do Ledger in the main 3 instead of Rabby?

**Comment by 0xanedi** [comment]
> Can we do Ledger in the main 3 instead of Rabby?

Yeah there's no need to have rabby when everyone knows you can just click MM and have it open eitherway.
Is ledger TOP 3 in use?

**Comment by pjenviri** [comment]
updated to display Ledger in the 3 main wallets.
