### ISSUE TITLE
Dai and USDT bridging not working on UI

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4062]
**Describe the bug**
Title.

**To Reproduce**
1. Go to https://connext-bridge-mainnet-git-feat-add-usdt-dai-coinhippo.vercel.app/DAI-from-ethereum-to-binance?amount=1&symbol=DAI&receive_next=true
2. Try to bridge either DAI or USDT from any chain.

**Additional context**
Might need SDK release.

**Comment by liu-zhipeng** [comment]
I updated xdai address of gnosis and tested on my local. Bridging DAI/USDT is working
![image](https://user-images.githubusercontent.com/57480598/234447902-6ec76dfe-b02a-40cd-9d6e-5b61c309e981.png)

![image](https://user-images.githubusercontent.com/57480598/234447944-71e59a5f-74a0-4cb2-bdf6-24a52a7905db.png)

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/issues/4063 will fix this issue as well. @pjenviri

**Comment by rhlsthrm** [comment]
Found the issue in our SDK, working on it now.

**Comment by rhlsthrm** [comment]
Fixed.
