### ISSUE TITLE
DAI Gnosis pool API errors

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4063]
Not loading https://connext-bridge-mainnet-git-feat-add-usdt-dai-coinhippo.vercel.app/pool/DAI-on-gnosis

![image](https://user-images.githubusercontent.com/37959170/234440933-336b799f-c7e0-49fb-aeb9-4bfb1de516e4.png)

![image](https://user-images.githubusercontent.com/37959170/234441080-2af1d11c-eddf-4807-bd05-8db7b5ebbeea.png)

**Comment by liu-zhipeng** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/blob/92fbdbedc084e9d115099efb7006b9b53b26b7cf/config/mainnet/assets.json#L232

dai contract address wrong

**Comment by liu-zhipeng** [comment]
https://gnosisscan.io/address/0xe91d153e0b41518a2ce8dd3d7944fa863463a97d

**Comment by pjenviri** [comment]
Note: USDT and Dai in `local` asset don't have `symbol` and `name`. 

![response.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/08065eee-1bcd-4982-a9d2-abb71a10ff8b)

**Comment by rhlsthrm** [comment]
They should be nextUSDT and nextDAI.

**Comment by alexwhte** [comment]
closing for #4094 cc @rhlsthrm looks like we need to fix this
