### ISSUE TITLE
End user can receive xDAI on Gnosis destination

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4065]
## Problem
End users are most often going to look for xDAI the native asset on Gnosis. We are currently providing wxDAI on Gnosis destination

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Receive xDAI by default on Gnosis
- [ ] Able to receive wxDAI if desired

## Proposed Solution
Insert add any changes to enable a similar end user flow to ETH 
![image](https://user-images.githubusercontent.com/37959170/234446913-cee6f906-5145-4527-a847-4a6d2d5a9f52.png)

**Comment by wanglonghong** [comment]
should be fixed by the commit https://github.com/CoinHippo-Labs/connext-bridge/pull/121/commits/eef279d1030bef963c1d0180571c1315c20a7cfd
