### ISSUE TITLE
Filtering transfers by asset not working

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4070]
for dai and usdt
https://connextscan.io/transfers

![image](https://user-images.githubusercontent.com/37959170/234660553-a0dbed87-39b2-437f-914f-0e302f7fe98b.png)

**Comment by pjenviri** [comment]
The filter function filters the results returned by the SDK. (UI requests data, then filters to display only data of the specific assets). Sometimes, it shows nothing if there's no relevant record return from the SDK.

To address this issue, we have increased the number of pagination from 100 to 750 when filtering by an asset.
