### ISSUE TITLE
Slippage updates not showing up in explorer

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4076]
**Describe the bug**
Even though the slippage updates show up on our backend, it seems like the explorer does not update the value.

**To Reproduce**
1. Bridge with low slippage.
2. Bump slippage from connextscan.
3. Observe slippage does not change.

**Additional context**

**Comment by pjenviri** [comment]
- UI shows the information retrieved in the`error_status` field. 
- We pass `domainId`, `transferId`, `slippage` to `updateSlippage` to update the slippage value.

**Comment by just-a-node** [comment]
Can't repro this - sent a txn with 0 relayerFee, bumped it, and it got updated in UI.

![image](https://github.com/connext/monorepo/assets/16638982/9acd9583-9175-4793-8ede-6e2d9a8044b5)
![image](https://github.com/connext/monorepo/assets/16638982/b69f7da8-1558-4258-a719-00a02778942f)

**Comment by just-a-node** [comment]
However, did notice that the "Update slippage successful" link points to origin-side explorer. Filed https://github.com/connext/monorepo/issues/4210

**Comment by rhlsthrm** [comment]
Let's close this then, will reopen if we see it again.
