### ISSUE TITLE
DAI-USDT Testing: Bridge UI "Latest Transfer" Window general value and asset display issues

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#4078]
**Describe the bug**
Bridge UI Latest Transfer Windows showing WXDAI instead of XDAI when Bridging to Gnosis when using the [testnet link] (https://connext-bridge-mainnet-git-feat-add-usdt-dai-coinhippo.vercel.app/DAI-from-polygon-to-gnosis?symbol=DAI)

**To Reproduce**
1. Go to [testnet link] (https://connext-bridge-mainnet-git-feat-add-usdt-dai-coinhippo.vercel.app/DAI-from-polygon-to-gnosis?symbol=DAI)
2. Bridge 1$ worth of DAI from any chain (I used Polygon) to Gnosis. → 'You Receive' set to DAI.
3. See that the 'Latest Transfers' window shows that you are going to receive WXDAI [see attached]. Explorer showing [correct info](https://connextscan.io/tx/0xbd6c25957d7a98cd75f6f52f847684f58a98969ee904968167731ccbb170cf96):

**Additional context**
![image](https://user-images.githubusercontent.com/89958919/234952651-7e36d315-63a0-4d90-bfda-ddf53b889bb3.png)

**Comment by onursarayli** [comment]
I would like to share a similar subject but with different details.

The estimated **DAI** amount I will receive showed 0.998625 **DAI** before the transaction. While waiting for transaction confirmation, it first showed still 0.998625 _XDAI_, then changed to 0.995 _XDAI_. And when the transaction was completed, it was transferred to my wallet as 0.998625 **DAI**. I have added the step-by-step process at the bottom.

**Related image:** https://imgur.com/zZCgSCM

In general, outgoing transactions from Gnosis seem to be faster. There is a similar situation when sending **USDT**; the numbers shown at the beginning, during the transaction and at the end of the transaction are different (the ones at the beginning and the end of the transaction are usually the same, the displayed while waiting for the transaction is not correct).

In addition; After waiting a few minutes in the Polygon to Gnosis (usdt) process, it showed an error. It fixed itself after a few minutes (so total processing time was around 5min, not 3.27min).

**Related image:** https://imgur.com/EtGDB4P

**Comment by alexwhte** [comment]
@pjenviri  I see 2 issues 
1. While pending, it shows you will receive wxDAI (the unwrapper contract will, but you as the user will receive xDAI)
2. It shows assets sent to a different address, when that's not true from the end user perpsective

<img width="298" alt="image" src="https://user-images.githubusercontent.com/37959170/235828095-aad10739-8bf6-4073-9397-d17b7544a0f7.png">

**Comment by alexwhte** [comment]
> I would like to share a similar subject but with different details.
> 
> The estimated **DAI** amount I will receive showed 0.998625 **DAI** before the transaction. While waiting for transaction confirmation, it first showed still 0.998625 _XDAI_, then changed to 0.995 _XDAI_. And when the transaction was completed, it was transferred to my wallet as 0.998625 **DAI**. I have added the step-by-step process at the bottom.
> 
> **Related image:** https://imgur.com/zZCgSCM
> 
> In general, outgoing transactions from Gnosis seem to be faster. There is a similar situation when sending **USDT**; the numbers shown at the beginning, during the transaction and at the end of the transaction are different (the ones at the beginning and the end of the transaction are usually the same, the displayed while waiting for the transaction is not correct).
> 
> In addition; After waiting a few minutes in the Polygon to Gnosis (usdt) process, it showed an error. It fixed itself after a few minutes (so total processing time was around 5min, not 3.27min).
> 
> **Related image:** https://imgur.com/EtGDB4P

Will need to follow up on this separately i think

**Comment by pjenviri** [comment]
Updated. Please review the data shown for your wallet.
