### ISSUE TITLE
Router balances not correctly displayed (USDT)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4083]
Hi team I'm not seeing balances correctly displayed in here
https://connextscan.io/router/0x048a5ecc705c280b2248aeff88fd581abbeb8587

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/92a444d0-9298-4644-b3a8-be733fb9a5dd)

Shows 500K here
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/3f8e0543-b962-4388-9793-c57b0226c514)

**Comment by pjenviri** [comment]
500k nextUSDT on gnosis is from `sdk.sdkUtils.getRoutersData()` at the address = `0x048a5ecc705c280b2248aeff88fd581abbeb8587`. Currently, the data are ranked by assets and chains.
