### ISSUE TITLE
User can use CreateReactApp with our SDK

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4084]
## Problem
Currently not possible

## Impact
Our partner devs will need this for best UX

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by just-a-node** [comment]
Initial analysis: https://www.notion.so/connext/SDK-Compatibility-d5827dee2f6c4b839507a99fc7fa7e61

Repackaging static elements (ABIs, etc) separately shouldn't be difficult but stripping out all Node-specific modules (`fs`, etc) will be a larger effort.

**Comment by rhlsthrm** [comment]
@prathmeshkhandelwal1 to investigate how to remove breaking dependencies.

**Comment by just-a-node** [comment]
https://github.com/connext/documentation/pull/108

**Comment by rhlsthrm** [comment]
Easy solution: Install cracow package and modify CRA config.
