### ISSUE TITLE
Chain Abstraction UI Assets

### ISSUE THREAD

**Issue by mchammond** [connext/monorepo#4086]
## Request
As part of the marketing campaigns announcing the Chain Abstraction use case, we will launch a landing page and supplemental content (twitter thread, blog posts, co-marketing, etc.). One of our main value propositions is the ability to drastically simplify the user interface/experience through an improved (and hopefully simplified) UI.

As a result, we would like to get high-resolution before and after screenshots of the UI and, ideally, screen recordings comparing the user flow of transacting between chains both before and after the CAT integration.

## Acceptance Criteria
_From an end-user perspective, the below criteria must be met to consider this done:_
- [ ] High-Resolution before and after screenshots of **at least one** integration to highlight changes to the UI.
- [ ] Screen recordings showing the difference in UX (transacting, LPing, etc.) before and after integration.

**Comment by alexwhte** [comment]
**Complexity: 3**
  [See the discussion](https://action.parabol.co/meet/mQPBn1nCxO/estimate/1) in Sprint Poker #​​33

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by just-a-node** [comment]
We need to make the user flow better for mean/midas before we can showcase them for the CA announcement.

**Comment by alexwhte** [comment]
closing, handled
