### ISSUE TITLE
Use transacted asset for fees by default in the bridge UI

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#4090]
The number 1 feedback we are getting from users is that our gas fees are too high.

After some investigation, it seems as though this perception is largely coming from the fact that fees are charged in the source chain gas asset instead of the transacted asset. Users don't understand the difference between these two options and simply see it as Connext itself being super expensive.

We need to *urgently* start using transacted asset for fees by default in the UI

**Comment by alexwhte** [comment]
closing in favor of #4093
