### ISSUE TITLE
Fee display / interaction UX updates

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4093]
## Problem
Users are complaining that fees are too high/confusing and have suggested our UI could be more simple 

## Proposed Solution
Test this in a test mode:
1. Default 'Destination Gas fee' to be in the 'Transacting Asset' vs. the native asset like today
2. Move the below into the advanced toggle
- Slippage tolerance
- Relayer Fee Asset toggle (NEW) --> It's just the below asset dropdown  
![image](https://user-images.githubusercontent.com/37959170/235812948-c42bbcb0-f2c6-4500-95fd-b924b7a3ae1d.png)
IF user toggles this to native asset, then it should change what we display below in both the 'Estimated amount received' and 'Transaction details'
3. Update calculation: estimate amount received  = `Transacting amount` - `sum(router fee, relayer fee, est.slippage)`
4. Have `Transaction details` as a line underneath Estimate Received that can collapse and expand.
This is simliar to before
![image](https://user-images.githubusercontent.com/37959170/235813763-d57fc551-d7be-4661-b2b0-1254ea16f37e.png)

When you expand we show the below:
- Router fee
- Relayer fee
- Slippage Toggle
- Minimum received after slippage

This is simliar to Uniswap https://app.uniswap.org/#/swap
![image](https://user-images.githubusercontent.com/37959170/235813940-956b1ce5-e569-4f41-981e-7bedc3a8373a.png)

**Comment by pjenviri** [comment]
Here's the preview of the update: https://connext-bridge-mainnet-git-feat-transfer-details-coinhippo.vercel.app/
PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/122

> 3. Update calculation: estimate amount received = Transacting amount - sum(router fee, relayer fee, est.slippage)

However, UI generally doesn't calculate it. The value shown in "You will receive" is retrieved from `calculateAmountReceived`, while the value is shown in "Min amount received after slippage" is the `calculateAmountReceived` - `slippage`

**Comment by alexwhte** [comment]
Per discord please update to 
1. Remove the '+Relayer Fee' from 'You send' UI subtext
2. Subtract the Relayer fee from the 'You Receive' amount estimate

**Comment by alexwhte** [comment]
Please make the below edits:
1. Change 'Relayer fee' to 'Gas on destination', and 'Relayer fee asset' to 'Asset for Gas on destination'
2. Do not show negative 'Estimate received', show 0 instead 
and an error 'Fees greater than estimate received.'

**Comment by pjenviri** [comment]
updated.
