### ISSUE TITLE
nextDAI asset display in pools is off

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4094]
**Describe the bug**
Couple issues
1. the text 'nextDAI' should show
2. the asset icon for nextDAI is not being used in the 'Manage Balance' section 

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/37959170/235828654-4068c210-86a3-48e2-8e11-5a6f30b40950.png">

**Comment by alexwhte** [comment]
Also:
1. Balance should say nextDAI in here 
2. Gas Icon is empty
<img width="413" alt="image" src="https://user-images.githubusercontent.com/37959170/235828885-1822f307-a949-47f3-b6b0-c71a5ee0d530.png">

**Comment by pjenviri** [comment]
@alexwhte No `name` & `symbol` returned by the SDK as mentioned [here](https://app.zenhub.com/workspaces/connext-6272a34e0368a200141cd949/issues/gh/connext/monorepo/4063) and [here](https://discord.com/channels/992549151134982234/994389387834032198/1101055351043936266).
