### ISSUE TITLE
Incorrect api call to gelato in getConversionRate

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4096]
**Describe the bug**
The gelato API is being used to get conversionRate. The mainnetEquivalent is also used for unsupported chains. Even if we get the corresponding chainId for a given chain, we're not mapping the `to` address. It would definitely make an error in the gelato response.

**To Reproduce**
1. Go to 'https://github.com/connext/monorepo/blob/main/packages/agents/sequencer/src/lib/helpers/relayerfee.ts#L65'

```tyescript
    if (asset === constants.AddressZero) {
      const nativeFee = BigNumber.from(origin.relayerFees[asset]);
      const relayerFeePaid = nativeFee.mul(Math.floor(prices[asset] * 1000)).div(1000);
      relayerFeePaidUsd = relayerFeePaidUsd.add(relayerFeePaid);
    } else if (asset.toLowerCase() === origin.assets.transacting.asset.toLowerCase()) {
      // origin native token to asset price
      const originNativePriceAsset = await getConversionRate(originChainId, asset, logger);
      prices[asset] = originNativePriceAsset === 0 ? 0 : prices[constants.AddressZero] / originNativePriceAsset;
      const relayerFeeDecimals = await getDecimalsForAsset(asset, originChainId, undefined, chainData, () =>
        chainreader.getDecimalsForAsset(+originDomain, asset),
      );
      const relayerFeePaid = BigNumber.from(origin.relayerFees[asset])
        .mul(Math.floor(prices[asset] * 1000))
        .div(1000)
        .mul(BigNumber.from(10).pow(18 - relayerFeeDecimals));
      relayerFeePaidUsd = relayerFeePaidUsd.add(relayerFeePaid);
    }
```
2. If we assume originChainId=59140, to=0xB706319D37b945727E71ae0d4353699d19112576, the endpoint would be 
https://api.gelato.digital/oracles/42161/conversionRate?to=0xB706319D37b945727E71ae0d4353699d19112576

**Additional context**
We're currently using mainnetEquivalents for testnets so its not happening on mainnet prod.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/nBkwGMURd6/estimate/6) in Sprint Poker #​​37

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by LayneHaber** [comment]
closing, stale
