### ISSUE TITLE
Relayer fee UX needs improvement

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4110]
**Describe the bug**
Relayer fee UX is confusing and has a few problems:

1. When the error changes (i.e. from low relayer fee to not enough balance for fast transfers), the CTA on the UI remains as "LowRelayerFee" and the prompt has the additional required fee as 0

![Screenshot 2023-05-04 at 2 55 03 PM](https://user-images.githubusercontent.com/12769011/236326990-62cb0960-c3ec-4037-9a1f-da8169b642b5.png)
<img width="1014" alt="Screenshot 2023-05-04 at 2 55 25 PM" src="https://user-images.githubusercontent.com/12769011/236327121-b35ca9db-3776-4483-84a7-06871f5ad0bc.png">

2. Relayer fees do not properly account for the value of next assets when the transacting asset is the local asset.

3. Doesn't handle the period between a bump and an execution retry well -- the CTA will remain and will not be removed if a transfer has been bumped, even if the bump value is sufficient. This makes users wonder if it has even picked up the fee

**Comment by alexwhte** [comment]
I tested here 
https://www.awesomescreenshot.com/video/17117142?key=a70b06ca1ca4e60b02c428591e8ddfcc
After it says 'Bump successful', the header says 'Waiting for bump' in red, it should show 'Processing' or similar 
Then it says 'Execution error' in red, but when i refresh it says 'SUCCESS'. 

The user should just see 'Bump successful' --> Processing --> SUCCESS

Can we fix this on UI side?

I dont think this adddressed @LayneHaber 's issues above so I might be adding on scope here

**Comment by alexwhte** [comment]
@pjenviri @nrsirapop passing to you to take these (Layne's feedback and mine) 
Please fix what you can and let us know if any of this is unclear / pass it back if needed?

**Comment by Tommy-R8** [comment]
A user had an issue when paying for the relayer fee with next Assets. Bumps are not working. https://discord.com/channels/454734546869551114/1104549950177681550/1104625087442866236

**Comment by alexwhte** [comment]
for me to QA

**Comment by alexwhte** [comment]
still testing and finding new issues, filing separately
