### ISSUE TITLE
Erroring with "execution reverted" when sending native from canonical domain

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4111]
**Describe the bug**

Send ETH from Ethereum -> Polygon errors with "Execution reverted".

This is also the case for testnet if you try to send ETH from Goerli -> Mumbai or MATIC from Mumbai -> Goerli.

**To Reproduce**
1. Go to bridge
2. Send native assets from the canonical chain
3. See execution reverted

**Additional context**

**Comment by alexwhte** [comment]
unable to repro
