### ISSUE TITLE
MessageVerification on offchain needs to be improved

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4112]
## Problem
We really had bad experience from mumbai to linea recently. There were a couple of blockers like RPC issue, carto loop issue, etc. 

But there is another thing to speed up the message processing --- MessageVerification is so slow. 
It takes about 1 min to verify 1 message in proveAndProcess. This will get increased as much as we have more leaves in tree.

| Log from DD | Timestamp(secs)|
|:---------------:|:---------------:| 
| Got unprocessed message  | 1683257458 |
| Message verified successfully | 1683257507 |
| MessageRoot verified successfully | 1683257511 |

## Impact
In case we have high load, this affects the completion time of slow path

**Comment by preethamr** [comment]
Where would the actual improvement be @wanglonghong

**Comment by rhlsthrm** [comment]
Pushing more improvements here.

**Comment by rhlsthrm** [comment]
PR is in, small fixes to get pushed.
