### ISSUE TITLE
User transaction wasn't stopped by high fees

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4115]
**Describe the bug**
A user's transaction (https://connextscan.io/tx/0x642cb5298ac6ded14f8420dbfc750c7b6380bd7a49b00233b27461114ad198fa) (https://discord.com/channels/454734546869551114/1104043044992471094/1104044697397231658) going from Polygon to Optimism took more than 90% of the sent funds in fees, without showing the "Fees are greater than the estimate received" error. The user believes the fees and amount sent were inverted so he received the fees. I don't believe this is the case because the amount taken is in line with the high gas fees we're seeing on Optimism caused by high gas prices on L1.

**Additional context**
Example screenshot of the error that should prevent user from bridging 
![image](https://user-images.githubusercontent.com/84744304/236495866-743f7f2d-d413-483c-a903-9e7f0c1ea56c.png)

**Comment by ArjunBhuptani** [comment]
User ticket: https://discord.com/channels/454734546869551114/1104043044992471094/1105449169939869777 (1140-keroe)

**Comment by alexwhte** [comment]
@pjenviri There are two things we should update here please
1. When fees are >20% of Sending amount, display a Warning 
"Warning: Fees are >20% of the sending amount. Please ensure you would like to proceed." 
underneath the 'Send' button

2. In Explorer, we should show the sent amount _before_ relayer fee is deducted. This should show '0.005' 
![image](https://github.com/connext/monorepo/assets/37959170/88f72d45-45cc-41ae-aaed-7264ecff026a)

https://connextscan.io/tx/0x642cb5298ac6ded14f8420dbfc750c7b6380bd7a49b00233b27461114ad198fa
https://polygonscan.com/tx/0x0cdbf734d55cb100c4e30933a3092d05e662791aa69ae11c39ca7af9364cd129

**Comment by alexwhte** [comment]
https://www.awesomescreenshot.com/video/17320181?key=068ea98b0c0eb1d819881024b160b917

i dont see this yet

**Comment by pjenviri** [comment]
updated. please try it again.

**Comment by alexwhte** [comment]
Please update the text to be under the 'Fees' section? (above Send)

And say "Warning: Fees are >20% of the sending amount."

**Comment by alexwhte** [comment]
Update to "Warning: Fees are >50% of the sending amount. Please ensure you would like to proceed."

**Comment by pjenviri** [comment]
updated
