### ISSUE TITLE
[cartographer] Limit needs increase when assigning messagestatus

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4121]
**Describe the bug**
This query:

```ts
export const getMessageRootsFromIndex = async (
  spoke_domain: string,
  index: number,
  _pool?: Pool | db.TxnClientForRepeatableRead,
): Promise<RootMessage[]> => {
  const poolToUse = _pool ?? pool;
  // Find the first published outbound root that contains the index, for a given domain
  const root = await db.sql<
    s.root_messages.SQL,
    s.root_messages.Selectable[]
  >`select * from ${"root_messages"} where ${{
    spoke_domain,
  }} and ${{ leaf_count: dc.gte(index) }} order by ${"leaf_count"} asc nulls last limit 10`.run(poolToUse);
  return root.length > 0 ? root.map(convertFromDbRootMessage) : [];
};
```

will fail to pull sufficient `root_messages` for a given transfer to be assigned the correct status at load, specifically because one of those messages will not have an aggregate root.

Generally we need to make sure these queries are more scale tolerant, and oftentimes these embedded limits cause status problems that act as red herrings.

**Comment by LayneHaber** [comment]
FYI this limit was increased to 75 during linea from 10, if it's still coming up we may need to be more precise here

**Comment by rhlsthrm** [comment]
Finding most efficient for defining limit.

**Comment by liu-zhipeng** [comment]
![image](https://github.com/connext/monorepo/assets/57480598/4e4f713f-2def-42bf-8623-d07e36615f1b)

Process time compared!

**Comment by liu-zhipeng** [comment]
![image](https://github.com/connext/monorepo/assets/57480598/0ff329a5-5768-42a3-9387-b874efdcea46)

Message Status compared

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/issues/4362
Found an issue!
