### ISSUE TITLE
UI should query with filters

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4124]
**Describe the bug**

The `daily_transfer_metrics` is huge! We should apply filters in the query, instead of filtering in the post-processing steps with the full table results.

E.g. https://github.com/CoinHippo-Labs/connextscan-ui/blob/main/components/dashboard/index.js#L63
- here we are getting the full table results and filtering by `transfer_date`
- instead we can use `https://postgrest.mainnet.connext.ninja/daily_transfer_volume?transfer_date=eq.2023-05-04` to filter by a specific date (or `=gt.2023-05-04` and `=lt.2023-05-04` for > and < comparisons).

All queries to DB should use filters the query instead of processing the full table. This applies to all tables used in https://github.com/CoinHippo-Labs/connextscan-ui/blob/main/lib/api/metrics/index.js#L9.

**Comment by pjenviri** [comment]
We are unable to filter the data by a specific period as the statistics displayed are based on all-time data. Therefore, it would be helpful if API routes provided aggregated data by chain or router, depending on the desired page or data to be shown.

**Comment by pjenviri** [comment]
Update: we have updated the UI to allow for requesting data for a specific number of days.
- https://github.com/CoinHippo-Labs/connextscan-ui/commit/b0baf8c76c510969bc44ce5143ccfaf7b021082c
- https://github.com/CoinHippo-Labs/connextscan-ui/commit/a3bb86bc7519eba944102a3588a878ce137c1d44

**Comment by alexwhte** [comment]
@just-a-node can you QA?
