### ISSUE TITLE
Performance Overview of FastPath Processing

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4136]
## Problem
A lot of txs are still getting bridged from mumbai to linea and the agents don't catch up the fast path processing.
The captured avg speed of xcall is about 150txs per minutes (maybe not accurate at the moment)  

The latest status of `Execute` shows `XCall` generation is about 3 times faster than its processing. 

![image](https://user-images.githubusercontent.com/30057497/236778917-8bbd4e5b-dec0-494a-89eb-7adfce95812f.png)

## Where is the bottleneck?
Here are some metrics related to the processing speed. 

**Consumer ACK rate**
![image](https://user-images.githubusercontent.com/30057497/236814361-1d95ec07-e2a8-46dd-bc07-693b16553b5a.png)

**DD log**
https://app.datadoghq.com/logs?query=index%3Atestnet-production%20service%3A%28sequencer-subscriber%20OR%20sequencer%29%20%40requestContext.transferId%3A0x6052a0d33bda051f458d1e7bfdc3f3842d0b301a6d1ad7f1a54044fd957a0af0%20&cols=service&index=testnet-production&messageDisplay=inline&saved-view-id=1439527&stream_sort=desc&viz=stream&from_ts=1682942200190&to_ts=1683547000190&live=true

![image](https://user-images.githubusercontent.com/30057497/236818031-ebd59c47-26f8-4489-96cf-837d839dab6f.png)

So I guess the bottleneck is the low processing time in sequencer-subscriber.

## Proposed Solution

- [ ] Increase the number of sequencer-subscriber.
- [ ] Reduce the processing time in executer of seq-sub. 
...
## Acceptance Criteria

- [ ] The sequencer should process all the XCalled txs in the backlog
- [ ] After getting through the backlog, it should execute the xcall txs within normal processing time. 
- [ ] That would be ideal to make it 5 times faster than now.

**Comment by wanglonghong** [comment]
https://github.com/connext/monorepo/issues/4163

**Comment by preethamr** [comment]
Further improvement in scaling is to implement better auto scaling.
-  Increase the number of sequencer-subscriber.

**Comment by preethamr** [comment]
Addressed by:
https://github.com/connext/monorepo/issues/4163
