### ISSUE TITLE
conversion rate null for NextAssets at sequencer

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4140]
**Describe the bug**
https://discord.com/channels/454734546869551114/1104549950177681550/1104550047179358301

After digging through more few observations were made:
- calculate relayer fee is working as it only requires input where we mention the pricing requirement under native or usd prices.
- The issue is coming at sequencer where we are calculating the relayerfee paid in both transacting and native asset. For this we fetch the pricing of the transacting asset, which isn't supported by gelato and we don't have any backup pricing calculator.

Solution: 
- if transacting asset is nextAsset, fetch the adopted asset and request the pricing for it.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by Tommy-R8** [comment]
https://discord.com/channels/454734546869551114/1105479109464825876/1105479288020533349 Another case going for ~70 hours
