### ISSUE TITLE
[UI] Pool deposit decimals error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4143]
**Describe the bug**
When depositing into the pools and choosing an amount with too many decimals, the site gives an error "missing revert data in call exception; Transaction reverted without a reason string"
![image](https://user-images.githubusercontent.com/84744304/236859312-48f774f0-ca96-40d7-825b-368f8f825567.png)

**Comment by LayneHaber** [comment]
sdk including this https://github.com/connext/monorepo/pull/4194 fix may improve decimal handling in the pools

**Comment by alexwhte** [comment]
@Tommy-R8 can you QA?

**Comment by Tommy-R8** [comment]
When inputting the amount, it gets correctly truncated to 18 decimals after like .2s. It seems to work correctly
