### ISSUE TITLE
Integrate any->any asset transfers/swaps in bridge UI

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#4149]
Now that we have the chain abstraction toolkit done, we can use it to pretty easily add support for any->any swaps in the bridge UI. 

Not supporting enough assets was one of the top complaints from users in the past

**Comment by rhlsthrm** [comment]
This is a UI task. We need to break down how CoinHippo needs to integrate the chain abstraction SDK and use it. Scoring based on providing the instructions to CoinHippo.

**Comment by alexwhte** [comment]
### Ideal state:
We add a combined chain+asset selection modals that replace separate chain and asset selections. 
We never grey out selections, we only show what is available with a given chain. 
Take https://playground.mean.finance/create/137
![image](https://github.com/connext/monorepo/assets/37959170/cc8be6b4-86c1-4877-a50b-827deed4da21)
- The user selects an asset AND chain in the same selection. Depending on their selection, origin chain network is automatically switched for the user. 
- Say a user is connected to Ethereum, then selects $XOC+Polygon origin, then Polygon is automatically set as their network, the user is prompted to switch in their wallet, and destination is automatcially set as BSC
- Say the user changes destination asset to $USDT+Arbitrum, then origin networks remains as Polygon, but the asset is changed to $USDT
- Say the user then selects $XOC+Polygon on destination, then the origin chain is changed to BSC, and the user is prompted to change their network
- Destination and origin chain can obviously never be the same, so if you select $XOC+Polygon as origin, then every asset + Polygon is hidden in the destination dropdown 

### Longer term
We want to combine with #4149 
So we have the chain+asset modals AND users can swap between assets across chains

**Comment by just-a-node** [comment]
Closing this for now.
