### ISSUE TITLE
Execution error for Binance origin transfers

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4152]
**Describe the bug**
A user got an "ExecutionError" for a bridge going from BSC DAI to Gnosis xDai https://connextscan.io/tx/0x68c75773b45bc47dbe64e318b089bd2a30da6d36941439576d1ca3839477b9d6?src=search

**Additional context**
https://discord.com/channels/454734546869551114/816982956684869654/1105178043699437588

**Comment by alexwhte** [comment]
Other example https://connextscan.io/tx/0xe7b9b4065259ff1cbe511c996af9ada44dadf8baa3c6751c846d057fb44120ba

Testing to arbitrum
https://connextscan.io/tx/0x4e107c763763a7919573a0943daa6269b3b63bc7d5f38aacab6edca847f69e3a?_gl=1*97pgoo*_ga*MTMyNTk5MzgwOS4xNjc1NDcyODgx*_ga_MPYZEDRVQ0*MTY4MzU2NjE0Mi4xMy4xLjE2ODM1NjY3OTEuMC4wLjA.

This is specific to BNB origin (i think)
