### ISSUE TITLE
Can't see DAI in selection when BNB is origin

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4157]
**Describe the bug**

**To Reproduce**
1. Go to Bridge UI
2. Select BNB as origin
3. Try to select DAI asset to bridge

DAI doesn't show up as an asset:
![image](https://user-images.githubusercontent.com/16638982/236916577-919220fe-9753-473c-b7ac-b4b8308f46f5.png)

It does appear when Gnosis is origin:
![image](https://user-images.githubusercontent.com/16638982/236916649-589e9d57-1ee5-4719-a7b7-9a3bfb9d1590.png)

If you select WXDAI on Gnosis as origin and BNB as destination, then switch the chains, you get DAI selected on BNB:
![image](https://user-images.githubusercontent.com/16638982/236916711-2d9fdf68-8acf-4955-8025-ac70574e5c8a.png)

**Additional context**

**Comment by Tommy-R8** [comment]
https://discord.com/channels/992549151134982234/1105214439629783040/1105251528496918608 BSC DAI was disabled by CoinHippo per Alex's request
