### ISSUE TITLE
Batch process in sequencer executer 

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4163]
## Problem
![image](https://user-images.githubusercontent.com/30057497/236983385-ba48449b-9332-4f12-aa6d-8c998d04de34.png)

It takes about 12s to process an individual transferId but `setupContext` takes about 6 seconds which is the half of the whole processing time --- this doesn't make sense. If we can process transferIds in batch in the executer we can increase its performance about 2 times than now

## Impact
It's needed to catch up the xcall processing. 

## Proposed Solution
Processing a bunch of transferIds in the executer at once.

## Acceptance Criteria
Once it gets done, seq-executer should process the transferId 2 times faster than now.

**Comment by rhlsthrm** [comment]
Need to test this, blocked by cartographer sync on testnet.

**Comment by rhlsthrm** [comment]
PR created for review.
