### ISSUE TITLE
Bump isn't working on Gnosis. 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#4170]
**Describe the bug**
Bump function isn't working properly for Gnosis chain. 
Bug: `Requested data is not available.`

**Additional context**
TX ID: https://connextscan.io/tx/0x857bacaff6c8be712cf3f5f2eac52c8470d539aeef0d74660bd6379c39a44d44
![image](https://github.com/connext/monorepo/assets/74738120/3ae4c76a-966d-495c-967d-e5076a191b2d)

**Comment by MinistroDolar** [comment]
**Describe the bug**
Bump function isn't working properly for Gnosis chain. (wrong relayer fees)
Bug: Reverted 0x5361666545524332303a206c6f772d6c6576656c2063616c6c206661696c6564 - cannot estimate gas; txn may fail or may require manual gas limit

Relayer fee was underrated and now he cant bump it

**Additional context**
TX ID: https://connextscan.io/tx/0xf60031bd699a6e133e71fd6def38bd11a138f080548c4ad3cd4a3f8dae670631

(ticket 1186)

User sent more txns after that one and they were successful.

https://connextscan.io/address/0xbd73cf5baf12f120ee3f6c4ad82df9a12649e578

**Comment by alexwhte** [comment]
Can the user bump USDT?

**Comment by MinistroDolar** [comment]
> Can the user bump USDT instead of xDAI?
> 
> 
> 
> The first user (slippage) looks to have completed

Sorry forgot to attach the snapshots![image](https://github.com/connext/monorepo/assets/26097731/9d6f5f35-1159-4514-b4c0-d68480721c4b)![image](https://github.com/connext/monorepo/assets/26097731/8bd9cc94-6577-49dd-a93d-d77e3a3e78f9)

He is trying to bump USDT

**Comment by 0xanedi** [comment]
Worth mentioning one more issuen that me and user sdraste noticed: when choosing xDAI for increasing the fee, it's showing 0, but for USDT it's ~0.8

Txid:
https://connextscan.io/tx/0xf60031bd699a6e133e71fd6def38bd11a138f080548c4ad3cd4a3f8dae670631

<img width="435" alt="image-2" src="https://github.com/connext/monorepo/assets/89958919/f379157d-ec86-4b66-9589-dbe6b7e5f3a4">
<img width="444" alt="image-1" src="https://github.com/connext/monorepo/assets/89958919/ec1f5c46-7d39-42bb-947d-e23595caab5e">

**Comment by alexwhte** [comment]
yea 

> > Can the user bump USDT instead of xDAI?
> > The first user (slippage) looks to have completed
> 
> Sorry forgot to attach the snapshots![image](https://user-images.githubusercontent.com/26097731/237198061-9d6f5f35-1159-4514-b4c0-d68480721c4b.png)![image](https://user-images.githubusercontent.com/26097731/237198088-8bd9cc94-6577-49dd-a93d-d77e3a3e78f9.png)
> 
> He is trying to bump USDT

replicating this with the transacting asset.... mm

**Comment by LayneHaber** [comment]
fee bumps were refactored on the backend for all transacting assets here: https://github.com/connext/monorepo/actions/runs/4931773952

this looks like a frontend problem, let me see if I can repro

**Comment by alexwhte** [comment]
@pjenviri do you have more context on this one? this looks to be more frontend

**Comment by LayneHaber** [comment]
closing, stale. 

can reopen if issue persists
