### ISSUE TITLE
DAI Transactions from Gnosis to Polygon with positive slippage not working

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4171]
**Describe the bug**
DAI Pool on Polygon is heavily unbalanced towards DAI. Incoming transactions from Gnosis Chain should be receiving high positive slippage.
![image](https://github.com/connext/monorepo/assets/84744304/64698b3f-a6ab-4062-9ff1-64812c1fe146)
![image](https://github.com/connext/monorepo/assets/84744304/64583c45-13dd-4483-80ee-e2ce3f60088b)
![image](https://github.com/connext/monorepo/assets/84744304/addb8de1-c9bd-4476-abd9-c8dcdb37fb60)
![image](https://github.com/connext/monorepo/assets/84744304/926e1a21-e94d-4119-9930-125d8598fb20)
However, people are getting `LowSlippage` error when trying to arb this. For some reason, it seems that the system isn't allowing users to receive positive slippage.

**To Reproduce**
1. Go to bridge.connext.network
2. Select xDai or WXDAI on Gnosis Chain to DAI on Polygon
3. See that the amount received will be much higher than the amount sent (correct because of positive slippage)
4. Start bridge
5. See error

**Additional context**
https://discord.com/channels/454734546869551114/1105458360238747678/1105458535602601984
https://discord.com/channels/454734546869551114/1105446247109775470/1105446723775639682
https://discord.com/channels/454734546869551114/1105444722719326239/1105444739081318560

**Comment by Tommy-R8** [comment]
Slippage stuff seems to work correctly. The swap is failing because of a check https://discord.com/channels/992549151134982234/1032671441084235828/1105529872023044116 that prevents users from putting in a greater amount of an asset than there is in the pool (of that same asset).
As the pool gets rebalanced by smaller transactions, the larger ones are able to go through (for example: https://connextscan.io/tx/0xe792f1783b255e7dcb87b4b7c3540a424615f3e50518912d182994f6a6c99bbb).

The solution when opening up new pools is put warnings on the UI for this problem, telling users not to bridge too large amounts.

**Comment by alexwhte** [comment]
@Tommy-R8 is this still ongoing?
