### ISSUE TITLE
[sequencer] Sequencer cache nullifying router bids

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4174]
**Describe the bug**
Depending on what is populating the cache, `sequencer-subscriber` will not respond to new bids from the `router-executor`s.

**To Reproduce**
1. Find a transfer that has been pending for a while
2. Clear out execution error and backoff from cartographer for that transfer
3. Watch routers send bids to sequencer with no result
4. Clear cache and sequencer responds

**Additional context**
Not sure if this is intentional, and the transfer I looked at was >50h old.

**Comment by LayneHaber** [comment]
The following transfers are presenting as `ExecutionError` and have routers submitting bids (specifically, show logs from the `router-executor` service) but no sequencer activity in response:

https://connextscan.io/tx/0x3389353796b337556bae5733a76a8a9b94616119a16aaa06c65430aa11a11785
https://connextscan.io/tx/0xf60031bd699a6e133e71fd6def38bd11a138f080548c4ad3cd4a3f8dae670631
https://connextscan.io/tx/0x1575102a4ae4ee6a06d8780bdc4d099f91020b878a18d4fdc537ce224c6bf819
https://connextscan.io/tx/0x1e0550f1b5931f836209a59206b340c028a4cbf66bce8aa2826d580c9c9f878a
https://connextscan.io/tx/0x3b564be30297bafb8bea0ca1b371518571ecbe74df58b0852c7de19e284369bf
https://connextscan.io/tx/0x11bed024d9f0b162532f92e0e55d7d0dcf345c2277f5518a2f12cee234576270
https://connextscan.io/tx/0x342be68a01905a5f6bb40a5d474090a9ab37ab679db5a807c0ac04ef37906930
https://connextscan.io/tx/0xd803227b0d1516ebe6dc07982da7686703f63ba0eb273ffd580927a6b6ff809d

**Comment by rhlsthrm** [comment]
Bug in sequencer cache if there is an execution error. Hotfix will be pushed.
