### ISSUE TITLE
Execution reverted from Polygon (DAI) to Arbitrum (DAI)

### ISSUE THREAD

**Issue by doxe1** [connext/monorepo#4180]
**Describe the bug**
Cannot move funds from Polygon (DAI) to Arbitrum (DAI)
Bug: `Execution reverted: dy < minDy`

**Additional context**
He has allowance for 2209 DAI, but can't swap even less amounts like 2000.
![image](https://github.com/connext/monorepo/assets/84589100/c7fe51e1-d472-4554-8f93-5f3b674a214b)

**Comment by alexwhte** [comment]
@doxe1 can you please provide the transaction ID with bugs? 
so we can dig in futher

Note we should improve message to `Slippage tolerance exceeded.`

**Comment by rhlsthrm** [comment]
This is a slippage issue on the sending side. Will close this as "expected behavior". We can open another one for improving the error message.
