### ISSUE TITLE
Gas bumps do not reflect properly on UI for a long time

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4184]
**Describe the bug**
We use the carto to reflect gas bumps but the Connextscan UI should optimistically store the bumps and show it on the UI.

**To Reproduce**
1. Go to Connextscan for a low relayer fee tx.
2. Try to bump it.
3. Observe that it does not reflect right away which is very confusing.

**Additional context**

**Comment by sanchaymittal** [comment]
What's the latency here? Wondering if it's the time between update at subgraph, then cartographer, and following these last steps only. We will see the changes in UI.

**Comment by rhlsthrm** [comment]
Well this is what I'm saying. We should update the UI immediately before it's reflected in carto.

**Comment by sanchaymittal** [comment]
Ahh i see! yeah that make sense.

**Comment by pjenviri** [comment]
Updated.
