### ISSUE TITLE
LowRelayerFee coming up

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4185]
**Describe the bug**
Seeing some transfers not processing due to LowRelayerFee. This should be a very rare occurence.

**To Reproduce**
1. Example: https://connextscan.io/tx/0x0c24bd10199b89da24956575cd793a57386471a775ba9c2605b8751835fa624c
2. Logs link: https://app.datadoghq.com/logs?query=@requestContext.transferId:0x0c24bd10199b89da24956575cd793a57386471a775ba9c2605b8751835fa624c&cols=service&index=mainnet-production&messageDisplay=inline&saved-view-id=1285114&stream_sort=desc&viz=stream&from_ts=1683698410356&to_ts=1683712810356&live=true

**Additional context**

**Comment by alexwhte** [comment]
More issues having trouble, @LayneHaber please check if related or file a new bug? 
![image](https://github.com/connext/monorepo/assets/37959170/6e241c69-ebcc-4342-81fa-dfede857e1bd)
