### ISSUE TITLE
[qa] Ability to test against mainnet-like environment

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4190]
## Problem
_What problem are we solving?_ 
Our only non-production mainnet environment where things like relayer fee endpoints could get caught is running locally, which is difficult to evaluate because the logs are difficult to pars, hard to isolate (i.e. cant really point ch UI at it in a way where you know its only the local agents interacting), and requires a prod-like configuration which is unrealistic to share amongst the team.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
This impacts the entire team, as not having this increases the likelihood of bugs making it to production.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
Use the tenderly fork endpoints and a local test setup to ensure we are able to simulate mainnet environments in a constrained way.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Can test mainnet environments without it pointing to mainnet and prior to release

**Comment by alexwhte** [comment]
**Complexity: 21**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/6) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by preethamr** [comment]
Should be turned into an epic, has broad scope.

**Comment by LayneHaber** [comment]
mainnet staging shipped, closing
