### ISSUE TITLE
[qa] Ability to isolate single transfers locally

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4191]
## Problem
_What problem are we solving?_ 

When you are testing changes, there is no easy way to test a single transfer. If you are trying to debug something on testnet or mainnet locally, it is difficult to parse and isolate all logs related to the transfer in question.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

Without the ability to easily debug single transfers, you risk pushing incomplete solutions, and it increases dev time substantially as there is no quick way to debug.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

lambda-izing the stack may help with running operations for a single transfer. alternatively, an admin UI that triggers certain actions for a given transfer only could be helpful, but in isolation would not mute the logs (since you need to ensure nothing else happens in that time frame)

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] I can trigger a single operation in a single transfer for router
- [ ] I can trigger a single operation in a single transfer for sequencer
- [ ] I can trigger a single operation in a single transfer for relayer

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/7) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
