### ISSUE TITLE
`ExecutionError` preventing completion of some transfers

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4193]
**Describe the bug**
Transfers are failing with `ExecutionError` and it is unclear why.

**To Reproduce**
Impacted transfers will show this error on the UI, and there are logs in the sequencer that could provide more insight.

**Additional context**
Impacted transfers:

https://connextscan.io/tx/0xf60031bd699a6e133e71fd6def38bd11a138f080548c4ad3cd4a3f8dae670631
https://connextscan.io/tx/0x1575102a4ae4ee6a06d8780bdc4d099f91020b878a18d4fdc537ce224c6bf819
https://connextscan.io/tx/0x1e0550f1b5931f836209a59206b340c028a4cbf66bce8aa2826d580c9c9f878a
https://connextscan.io/tx/0x3b564be30297bafb8bea0ca1b371518571ecbe74df58b0852c7de19e284369bf
https://connextscan.io/tx/0x11bed024d9f0b162532f92e0e55d7d0dcf345c2277f5518a2f12cee234576270
https://connextscan.io/tx/0xca0a61ef845ce4788d4924cc5da3196264bc71e3656089a2b95286f5ae4c47a8
https://connextscan.io/tx/0x34984d7a9b9a3bd9b79887a3006173b1a36a2acd447bed7892792b6a04db7b09

**Comment by just-a-node** [comment]
https://connextscan.io/tx/0x34984d7a9b9a3bd9b79887a3006173b1a36a2acd447bed7892792b6a04db7b09
https://connextscan.io/tx/0x1e0550f1b5931f836209a59206b340c028a4cbf66bce8aa2826d580c9c9f878a
https://connextscan.io/tx/0xf60031bd699a6e133e71fd6def38bd11a138f080548c4ad3cd4a3f8dae670631

These 3 are still in ExecutionError state with the following sequencer log:
![image](https://github.com/connext/monorepo/assets/16638982/103457c1-4241-4ae3-9227-f49c6e9a7798)

**Comment by rhlsthrm** [comment]
Looks like a couple of these are LowRelayerFee and I think the other one is a case of #4174

**Comment by rhlsthrm** [comment]
Cleared sequencer cache and this went through. Will close this in favor of separate issues.
