### ISSUE TITLE
Change NoBidsReceived error

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4204]
## Background

This is very jarring and does not give the user any more information.

### Linked Issues & Documentation

- List of linked issues, external links, etc
- 
![image.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/2675d785-b0a8-42b1-8f96-8d5d8d10c4c4)

## Definition Of Done

Change the error to an "Info" type alert. It should say "Boost liquidity not available". Hovering over the tooltip should say "The transaction will complete within 120 minutes".

## Tasks

**Comment by alexwhte** [comment]
@rhlsthrm Can you QA?

**Comment by rhlsthrm** [comment]
@pjenviri can we also make it so this tooltip shows up after 5 minutes of inactivity if there is no other error? When you view a transfer page it can check if `time_now > xcall_timestamp + 5 minutes` and if so and no other errors, it can show the same info tooltip.

**Comment by pjenviri** [comment]
@rhlsthrm  In the current UI, the status and tooltip are immediately shown whenever there is an error status. 
To clarify, do you want the UI to show the `NoBidsReceived` status for any inactive transactions for more than 5 mins (even if they do not have an error status)?

**Comment by pjenviri** [comment]
Okay, updated to prod.
