### ISSUE TITLE
Incorrect "Insufficient Balance" errors

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4207]
**Describe the bug**
When dealing with native assets especially (but not limited to it) some users get "Insufficient Balance" despite having like, at least 10x the amount needed to cover the funds that need to be sent and the gas fee on the chain they're transacting on.

**To Reproduce**
2. 
3. 

**Additional context**
Here's an example of a user that has to pay 0.67 xDai for a relayer fee. Fees on Gnosis are extremely cheap, and yet despite having more than 4 xDai, the site gives an "Insufficient Balance" error. https://discord.com/channels/454734546869551114/1105444722719326239/1106026380669501522

**Comment by just-a-node** [comment]
Not able to repro this on my side. Will close this for now til we get a report of a similar issue.
