### ISSUE TITLE
Unable to withdraw / doesnt show my balance

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4217]
BSC didnt show my balance for a while it eventually corrected itself

[bridge.connext.network-1683902295481.log](https://github.com/connext/monorepo/files/11465230/bridge.connext.network-1683902295481.log)

Then I switched networks and it said 'Could not detect network'

![image](https://github.com/connext/monorepo/assets/37959170/02876c20-a177-4a23-a402-b607a19c52d6)

**Comment by pjenviri** [comment]
Cannot reproduce the issue.
