### ISSUE TITLE
Can't search txn after having performed a search for another transaction

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#4220]
**Describe the bug**
When i try to search a txn by hash, after having performed a search for another transaction, i put enter and website doesn't updates. 
Even the link in the browser is updated, with the new hash, but the new txn doesn't show up.

<img width="1918" alt="image" src="https://github.com/connext/monorepo/assets/26097731/2d65aa48-87ee-4281-9e15-c3c8ad0dd3f5">

**To Reproduce**

1. Go to connextscan.io
2. Search a txn A
3. After that, search another txn (call it B).

**Additional context**
It happens with every browser i've tried, mobile and desktop.

**Comment by pjenviri** [comment]
Fixed. Please try it again.

**Comment by MinistroDolar** [comment]
> Fixed. Please try it again.

fixed on my side :) thanks!!
