### ISSUE TITLE
Execution error - Dai From Ethereum to Gnosis

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#4221]
**Describe the bug**
93k bridge got execution error in 1st instance.

![image](https://github.com/connext/monorepo/assets/26097731/7959c873-6c65-4b3a-b2f9-f6d0f5b32ab5)

Then it changed to "Boost Liquidity not available"

![image](https://github.com/connext/monorepo/assets/26097731/5e4abe6c-fcea-4463-a89e-d1e807367c93)

Finally, after the reconcile got completed execution error came back.
Ive checked there is a lot of liquidity and has more xdai than nextdai.

![image](https://github.com/connext/monorepo/assets/26097731/cf995f70-969d-4f15-98fd-53a87a2c23a9)

**To Reproduce**
Specific case.

**Additional context**

https://connextscan.io/tx/0x1a7471b5668e6e4dfca75bb819d5a8ca1419fd4d744ad51c3de9feb2fa18a9ba

Ticket: https://discord.com/channels/454734546869551114/1106733283737337946

**Comment by wanglonghong** [comment]
fixed after clearing cache. will be finally fixed here https://github.com/connext/monorepo/issues/4174
