### ISSUE TITLE
Host sdk-server on AWS

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4223]
## Problem
_What problem are we solving?_ 

Our current SDK is heavy and is not possible to use in some front-end applications. If we deploy a hosted SDK server that can generate the appropriate transactions data then we can have a highly optimized front end SDK that simply queries this server.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

We have anecdotal evidence that users are churning due to our SDK bundle size.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

### App Layer
* Containerize [sdk-server package](https://github.com/connext/monorepo/tree/main/packages/examples/sdk-server)
* Host on ECS to expose HTTP endpoints
* Set up autoscaling groups in multiple regions
* [Optional] Configure multiple availability zones per region

### Cache Layer
* Set up ElastiCache (Redis) clusters in multiple regions
* [Optional] Enable cross-region replication (probably not necessary)
* [Optional] Configure multiple availability zones per region
* Implement middleware in `sdk-server` to cache requests in Redis

### Load Balancer
* Set up ALB to distribute traffic across ECS instances in each region
* One ALB per region

### DNS
* Geolocation routing of requests to different regional ALBs with Route 53

### [Optional] API Gateway
* First-class support for OpenAPI/Swagger specification
* Generate SDKs for multiple platforms using the OpenAPI spec (these are just client SDKs that help with hitting the API)
* Anti-DDoS vectors using rate limiting, throttling, API keys

### [Optional] Analytics
* This depends on what we want to capture. If we set up API Gateway, we can get metrics like API call count, latency, cache hits/misses. This should be possible to collect from logs without API Gateway as well but slightly more difficult.

### Other Notes
* Use Terraform to define all the infrastructure pieces
* Replicate for each environment (`testnet-staging`, `testnet-prod`, `mainnet`)

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] SDK Server is hosted and publicly accessible
- [ ] API requests have low latency from multiple regions
- [ ] Can handle scaling requirements (TODO)

**Comment by alexwhte** [comment]
test this when completed https://github.com/connext/monorepo/issues/4208
