### ISSUE TITLE
Wrapper SDK-Server with new versioning

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4228]
## Problem

SDK pains:
- Large bundle size
- Compatibility issues with UI frameworks (CRA)
- Additional package downloading issues (what are some examples?)

## Impact

We have a few integrations which are blocked by the above and future integrations will experience friction without changes.

### SDK Wrapper Package 

*MUST:*
- Be published as a new version to `@connext/sdk`
- Match *exactly* the current function signatures and be backwards-compatible

*SHOULD:*
- Call the hosted `sdk-server` routes
- Include a minimal subset of core functions (`xcall`, `estimateRelayerFee`, `bumpTransfer`, `calculateAmountReceived`, `updateSlippage`)

### SDK Test Harness

*MUST:*
- Include unit tests with coverage abiding by the [global monorepo thresholds](https://github.com/connext/monorepo/blob/8ad4c909df849bec4b1122b442ec1512f6d8298a/.nycrc.json) such that this package's tests can be included in all CI runs

*SHOULD:*
- Include integration tests with a local `sdk-server` that validates correctness of routes and error response codes (note: might be combined with unit tests since this wrapper SDK will be a thin layer on top of the server routes)

### Package Structure

*SHOULD:*

 Involve the following:
    - `packages/agents/sdk`: existing sdk core classes
    - `packages/agents/sdk-wrapper`: package with wrapper classes exposed for clients to use, published to `@connext/sdk` under a new version
    - `packages/examples/server`: sdk-server routes that will be hosted on AWS

### Transition Strategy

*MUST:*
- Be seamless for clients during the transition to the wrapped SDK version
- Be seamless for clients during the transition from the wrapped SDK version to the original architecture of client-side-only operations
- Be able to eliminate dependency on the hosted server at some point

### Hosted SDK Server
- Tasking tracked separately in #4223
- Exposes API routes for all core SDK functions
- Will include rate limiting and analytics

## Acceptance Criteria
- [ ] Clients installing `@connext/sdk@<new_version>` will not need to change any existing implementations
- [ ] Latency for calls should fall under 1000ms (this will depend on server caching, geo, and scaling)

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/12) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
test this when completed https://github.com/connext/monorepo/issues/4208

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/monorepo/tree/wrapper-sdk

**Comment by rhlsthrm** [comment]
Need to write tests.

**Comment by rhlsthrm** [comment]
Debugging import errors, etc.

**Comment by rhlsthrm** [comment]
Added most of the tests, working on SDK pool.

**Comment by rhlsthrm** [comment]
Finish up tests, figure out why some are being skipped.

**Comment by LayneHaber** [comment]
Need to 
- [ ] up the coverage on tests
- [ ] take passed-in provider

**Comment by rhlsthrm** [comment]
Review and merge provider PR. Fix tests and coverage.

**Comment by just-a-node** [comment]
@sanchaymittal last steps here:
- release @connext/sdk-core 
- release @connext/sdk 
- test all functionality in bridge UI again
