### ISSUE TITLE
Bridge UI's Router Fee tab should specify which percentage of Sent amount will go to Router Fees.

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#4234]
## Problem
_Gas Fee dialogue's tooltip isn't displaying the actual percentage substracted due to Router Fees_ 

## Impact
_Users need to know quickly how much they will be paying in case there's a non-variable fee. It hink this is much more transparent._

## Proposed Solution
_Include "Liquidity providers receive a .05% fee for supporting fast transfers" to the current Router Fee tooltip text. See attached._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] I can understand how much I will be charged of the total amount for any non-variable Fee.

![image](https://github.com/connext/monorepo/assets/89958919/2b68d9bc-ec24-400b-a2e3-6d82b7380105)

**Comment by alexwhte** [comment]
please say "Liquidity providers receive a .05% fee for supporting fast transfers"
