### ISSUE TITLE
Gelato 1balance contracts

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4240]
Tasks - 
- [x] Create 1balance Target contracts and unit test

**Comment by rhlsthrm** [comment]
@prathmeshkhandelwal1 to request review from @sanchaymittal @liu-zhipeng @rhlsthrm .

**Comment by alexwhte** [comment]
@sanchaymittal why did you move

**Comment by sanchaymittal** [comment]
> @sanchaymittal why did you move

Cause we did code review and there are changes to be done.
