### ISSUE TITLE
Db connection shouldn't block fast path completion

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4244]
**Describe the bug**
If there an DB error, sequencer can't complete the transfer. It reverts with `execution error`.

Solution:
- Try/catch DB error and log it, instead of throwing it.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by rhlsthrm** [comment]
Working on figuring out where to add try-catch.

**Comment by rhlsthrm** [comment]
Need to fix unit tests.

**Comment by rhlsthrm** [comment]
In review.

**Comment by sanchaymittal** [comment]
done
