### ISSUE TITLE
Why did this transfer take 19 minutes?

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4248]
https://twitter.com/BeamerBridge/status/1658510652812701698?s=20

Can we check this easily? (in like 10 mins?)
https://connextscan.io/tx/0x097d98b6c6248637701ef57a35f67ea3136b090e7761c776f7d0c82bf63a73f1

**Comment by preethamr** [comment]
Not enough info, can reopen if we see this happen again.
