### ISSUE TITLE
Developers can display available assets to end users 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4250]
**Problem**
As an end user, I should only be allowed to use available assets (from UI + connext/uni infra).

**Solution**
    - Most applications have a hardcoded list of assets they support. We can rely on them to limit to assets they support.
        - For chain abstracted workflows, we can add SDK method like `getSupportedAssets`using whatever is available in Uniswap

**Comment by alexwhte** [comment]
**Complexity: 5**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/1) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
Already done on Midas side,just need to put in our SDK

**Comment by rhlsthrm** [comment]
PR is open. Local tests are working, but still seeing issues and CI/CD failed.

**Comment by rhlsthrm** [comment]
Merged.
