### ISSUE TITLE
Developers can show price impact for chain abstraction

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4251]
**Problem:**
Developers should know what fees they can display and have easy endpoints. 

**Solution:**
All the same fees AND add price impact for swaps. 

- **Relayer fee**
    - **Router fee**
    - **Estimated time to complete**
    - **Slippage tolerance**        
    - **Est. price impact from swaps [new]**

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/2) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by liu-zhipeng** [comment]
How can we estimate the time to complete ?

**Comment by rhlsthrm** [comment]
Add SDK to chain abstraction SDK.

**Comment by alexwhte** [comment]
depri for stability and token

**Comment by alexwhte** [comment]
closing in favor of #4395
