### ISSUE TITLE
Users have their slippage tolerance respected with added swaps

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4252]
**Problem:**
There can be up to 4 swaps now with uniswap + connext AMMs, but only a single slippage tolerance.
Applications need a clear way to handle this for the user. 

Example in worst case: 1% uniswap origin + 1% connext origin + 2% connext dest + 2% uniswap dest = 6% total
Account where slippage tolerance = 3%
Account where slippage tolgerance = 5%

**Acceptance Criteria**
 Some of these might already be possible today. Please just note 'how' we handle this today so that we can help inform integrating apps
- [ ] user can input a single slippage parameter that is respected by all swaps (up to 4)
- [ ] if slippage fails on origin swap, the end user is alerted by the applicaiton
- [ ] after an additional external origin swap, current Connext slippage handling is still respected, where that additional origin slippage is deducted from their 'minimum amount received', and they can still bump tolerance within Connext
- [ ] bumping tolerance in Connext local swaps also bumps their overall tolerance for the subsequent external slippage
- [ ] if slippage fails on destination, we immediately alert the user and tell them exactly what happened, for example
> "ERROR: Swapping into <$PEPE> failed on the destination chain due to <5%> slippage exceeding your <3%> tolerance. The protocol instead sent <9999 $USDC> to destination address <jaredfromsubway.eth> on <Arbitrum>"

We recommend slippage setting for the user
- [ ] we MUST not make slippage too low or else tx will fail. particularly problematic on destination side, where the failure will trigger the fallback and completely fuck up the UX.
- [ ] we MUST not make it too high or else user will be exposed to MEV attacks

**Proposed design**
Per https://discord.com/channels/992549151134982234/1110523488311197706
we want to have 1 "slippage" that they can enter and it is respected by all swaps
expose a single "slippage" param from the SDK for the SwapAndXCall flow
query instantaneous price impact for origin and destination swap
set slippage on those swaps to a safe tolerance where user wont get sandwiched but tx will complete
xcall slippage = input slippage - origin slippage - destination slippage

**Comment by alexwhte** [comment]
**Complexity: 13**
  [See the discussion](https://action.parabol.co/meet/ne6bRdr87m/estimate/3) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
depri in favor of stability #4326

**Comment by rhlsthrm** [comment]
The easiest way to do this for now:
- Get price impact for origin and destination swaps.
- Add a buffer for slippage tolerance (20%?).
- Use the rest of the inputted slippage as the Connext slippage.

Example:
- User sets 3% slippage.
- Price impact for origin swap is 0.5%
- Price impact for destination swap is 1%

Set slippages to:
- Origin: 0.6%
- Destination: 1.2%
- Connext: 3 - 0.6 - 1.2 = 1.2%

**Comment by prathmeshkhandelwal1** [comment]
Slippage

- so there are three things we might need to consider for slippage on swaps
1. OneInch swaps price impact 
2. UniV3 price impact
3. UniV2 price impact
we might need a way to calculate that

Possible approach: 
1. Take uniswap SDK and use it for calculation
2. Discussed in scrum we can use estimateAmountMethod for this, but how? Checked uniswap docs didn’t find a way though
3. For uniswap different ways to calculate price impact for v2 and v3 , v2 is pretty easy but for v3 we have to consume uniswap sdk and fetch their subgraphs to get the pool reserve details. 
4. Better approach?

**Comment by rhlsthrm** [comment]
> Discussed in scrum we can use estimateAmountMethod for this, but how? Checked uniswap docs didn’t find a way though
https://docs.uniswap.org/sdk/v3/guides/quoting#referencing-the-quoter-contract-and-getting-a-quote

We simply need to get a quote and get the amount out. We don't need to do anything with subgraphs directly.

**Comment by rhlsthrm** [comment]
Testing various use cases to see if works.

**Comment by LayneHaber** [comment]
testing still in progress

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/monorepo/pull/4542
