### ISSUE TITLE
Track Stable swap LP token balance on subgraph and carto

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#4270]
## Problem
We need to track the balance of LP token for each providers.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

## Proposed Solution
Deploy a subgraph to track balance of ERC20 token. and pull data from carto.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Subgraph
- [ ] Poller

**Comment by alexwhte** [comment]
@liu-zhipeng is this ready for review? can you please commetn with updates as you go on these

**Comment by liu-zhipeng** [comment]
Ready for review now
