### ISSUE TITLE
Mechanism for router to send liveness updates to sequencer

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4271]
## Problem
_What problem are we solving?_ 
We had some issues where routers were offline and did not respond for fast liquidity. This degraded user experience since users expected fast liquidity but did not receive it.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
User experience issue, we may be churning users who don't receive funds in a timely manner when they expect them. We had some angry users in our Discord who sent high value transfers that took hours to complete.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
This only covers the backend side, additional work is required on the SDK and UI.
- Create endpoint on sequencer to receive router liveness updates. This should check for a signed message from the router to avoid spoofing.
- Endpoint handler should store last router liveness timestamp in the DB.
- At the end of router publisher loop, send liveness update to sequencer.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Router liveness is available on DB and populated with updated routers.

**Comment by preethamr** [comment]
Wont fix
