### ISSUE TITLE
SDK `checkFastLiquidity` should take into account router liveness

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4272]
## Problem
_What problem are we solving?_ 
We have an SDK method for checking if fast liquidity is available. However this does not take into account that routers may not be live.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
User experience is degraded if we get a false positive on checking fast liquidity.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
Blocked by #4271
- Query router liveness from cartographer API in SDK.
- Remove non-live routers from the available fast liquidity.
- IMPORTANT: Must not be enabled until most routers update to the latest version.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] SDK method `calculateAmountReceived` considers router liveness, and removes non-live routers from calculation.

**Comment by just-a-node** [comment]
Wont fix
