### ISSUE TITLE
Connextscan UI displays stale `NoBidsReceived` transfers error_status 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4284]
**Describe the bug**
It was found in the recent past that the default transfers view : https://connextscan.io/transfers, has incorrect `error_status`

**To Reproduce**
1. https://connextscan.io/transfers
2. Pick a couple of random transfers with `NoBidsReceived`

4. Compare that with the result sent to UI:
https://postgrest.mainnet.connext.ninja/transfers?limit=250&offset=0&order=xcall_timestamp.desc&select=transfer_id,nonce,to,call_data,origin_domain,canonical_domain,canonical_id,destination_domain,bridged_amt,normalized_in,origin_sender,origin_chain,origin_transacting_asset,origin_transacting_amount,origin_bridged_asset,origin_bridged_amount,xcall_caller,xcall_transaction_hash,xcall_timestamp,xcall_gas_price,xcall_gas_limit,xcall_block_number,xcall_tx_origin,destination_chain,receive_local,status,routers,delegate,slippage,updated_slippage,destination_transacting_asset,destination_transacting_amount,destination_local_asset,destination_local_amount,execute_caller,execute_transaction_hash,execute_timestamp,execute_gas_price,execute_gas_limit,execute_block_number,execute_origin_sender,execute_tx_origin,reconcile_caller,reconcile_transaction_hash,reconcile_timestamp,reconcile_gas_price,reconcile_gas_limit,reconcile_block_number,reconcile_tx_origin,relayer_fees,error_status,execute_simulation_input,execute_simulation_from,execute_simulation_to,execute_simulation_network
<img width="755" alt="image" src="https://github.com/connext/monorepo/assets/1195648/a4221ad8-815d-4e70-82be-cffcae44c4ca">

**Additional context**
Need to investigate why UI does not update the view with the latest data received from the postgrest API.

**Comment by preethamr** [comment]
Related to: https://github.com/connext/monorepo/issues/4278

**Comment by pjenviri** [comment]
It's because of this ticket https://app.zenhub.com/workspaces/connext-6272a34e0368a200141cd949/issues/gh/connext/monorepo/4204

https://github.com/CoinHippo-Labs/connextscan-ui/blob/ee3abb691712976467fc326efa95559b40de9d90/components/transfers/index.js#L208

**Comment by rhlsthrm** [comment]
@pjenviri it should not show "NoBidsReceived" in the transfers view either, it should show the same "Processing..." view.

**Comment by pjenviri** [comment]
updated. please check it once again.
