### ISSUE TITLE
Tighten Up Deployment Process

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4303]
Off of the discussion with Wonderland 

https://docs.google.com/presentation/d/1GNY9MxbyIyHl2XUuCQ6lHmdBH88U_7v1xA5vbb-8Vew/edit?usp=sharing

https://discord.com/channels/992549151134982234/1108087126907682866

**Comment by alexwhte** [comment]
Objective
- do no keep private keys or mneumonics in configs 

Two ways: 
1. Only use encrypted keystores (encrypted json)
2. Have employer key used only during deployment process, then key has no impact on system

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/nBkwGMURd6/estimate/8) in Sprint Poker #​​37

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by alexwhte** [comment]
potentially redo all in forge

**Comment by preethamr** [comment]
Will happen as part of Chimera upgrade.
