### ISSUE TITLE
Always use encrypted keystores

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4304]
Should ensure no configs require a plaintext mnemonic or private key when running locally without web3signer

From convo with Wonderland

https://discord.com/channels/992549151134982234/1108087126907682866

https://docs.google.com/presentation/d/1GNY9MxbyIyHl2XUuCQ6lHmdBH88U_7v1xA5vbb-8Vew/edit?usp=sharing

**Comment by preethamr** [comment]
This improves our security hygiene
