### ISSUE TITLE
Relayer fee collected way too low to mainnet

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4306]
**Describe the bug**
Relayer fee bump is asking for $30, it looks like we took $0.60 originally. Why was this possible? It also shows the user receiving 0 USDC, even though they sent 51 USDC. So the math is off here

https://connextscan.io/tx/0x0834afc56fd12f46e73d1ecd0a1660077ed0c24409e9a3907131790206d6a66d

![image](https://github.com/connext/monorepo/assets/37959170/96f9f847-4622-4851-b4cd-5fec089a6215)

**To Reproduce**
1. Go to https://connextscan.io/tx/0x0834afc56fd12f46e73d1ecd0a1660077ed0c24409e9a3907131790206d6a66d
2. See detials https://bscscan.com/tx/0xd91765dc1a3c87971476370eb6ea0eb65206994b17cec304af7d2b6b38e2eb75
3. 

**Additional context**

**Comment by rhlsthrm** [comment]
Closing unless we get more examples.
