### ISSUE TITLE
Stableswap Lp Poller stop working due to 500+ transfers in single tx.

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#4313]
**Describe the bug**
https://gnosisscan.io/tx/0x7ab7af7e4cca79a3919a3d4e808fed198ed405ed44ed8f98d666b86963ff3e17

![image.png](https://images.zenhubusercontent.com/63331283a97e6555fde71ad4/48448cfa-4977-482f-9468-0c19dd89e9aa)

This tx has 500 transfers and poller is fetching only 100 events at once. So checkpoint is not updated.

**To Reproduce**

**Additional context**

**Comment by rhlsthrm** [comment]
Caused by https://github.com/connext/monorepo/issues/3437

**Comment by rhlsthrm** [comment]
Need prod merge and verification.
