### ISSUE TITLE
Unable to send any transfers

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4314]
**Describe the bug**
Any route, any amount is not working:

![Screenshot 2023-05-23 at 08.57.29.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/a053ef1a-145f-41cf-a12c-8c54a0344fd2)

**To Reproduce**
1. Go to Bridge UI.
2. Try to bridge any amount of USDC.
3. 

**Additional context**

**Comment by pjenviri** [comment]
It errors when a value is undefined. It's from this pr: https://github.com/CoinHippo-Labs/connext-bridge/pull/123/files#diff-4a555b87df06c7dc14e65b56350b336961db144616109c475d88aefea169d2efR1329. 

Fixed by adding 0 if the value is undefined.
