### ISSUE TITLE
If sequencer is down, router stops retrying transfers

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4315]
**Describe the bug**
Sequencer unavailability affects router. Router does not retry transfers if it fails to reach sequencer 3 times, until it's restarted.

**To Reproduce**
1. Start router.
2. Make sequencer unavailable.
3. See router is unable to execute more transactions.

**Additional context**

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/nBkwGMURd6/estimate/3) in Sprint Poker #​​37

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by rhlsthrm** [comment]
Checking this today, need to make sure router does not just stop working completely if sequencer reboots.

**Comment by sanchaymittal** [comment]
router didn't get stuck
