### ISSUE TITLE
Instadapp Integration

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4317]
So far:
- we have dsa contracts where connext is enabled
- target contracts for instadapp are deployed
https://github.com/Instadapp/dsa-periphery-contract

Next steps
- test out the flow of target addresses, with dsa contracts
- create an integration test to check the flow and write next steps required for sdk

Need next steps clearly mapped out (testing, adding to instadapp docs, marketing campaign)
Options for implementation

1-click deposits
crosschain lending

**Comment by alexwhte** [comment]
close but we need to align on next /final steps
