### ISSUE TITLE
[sequencer] Testnet prod `ping` failures

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4322]
**Describe the bug**
Seeing many axios failures in data dog, and the `ping` endpoint on the sequencer is not responding.

**To Reproduce**
1. Go to https://sequencer.testnet.connext.ninja/ping
2. Cry

**Additional context**
Also seeing errors on storing data / posting slow to sequencer: https://app.datadoghq.com/logs?query=&cols=service&event=AgAAAYhJWUU2rGkc0AAAAAAAAAAYAAAAAEFZaEpXVWIyQUFBRTBJYTZJbVBjMUFBRgAAACQAAAAAMDE4ODQ5NTktNDhhMy00MTM3LWE2NTktMzlhM2QxYjAzNzBm&index=testnet-production&messageDisplay=inline&saved-view-id=1439527&stream_sort=desc&viz=stream&from_ts=1684853957766&to_ts=1684857557766&live=true

**Comment by preethamr** [comment]
The known cause is this strange error from the graph api:
<img width="512" alt="image" src="https://github.com/connext/monorepo/assets/1195648/1254fd50-a57a-4055-b4e0-07440c3ee707">

**Comment by LayneHaber** [comment]
would that impact the ping endpoint?

**Comment by preethamr** [comment]
> would that impact the ping endpoint?

Indirectly, as seq is very busy handling lots of slow path requests, that eventually all fail. HTTP server and seq publisher are on the same process.

**Comment by LayneHaber** [comment]
Has not yet been deployed to mainnet -- there are likely non-terraform dependencies on rabbitmq and that is a bit of a blindspot. Issues could be caused by changing deployment but not service name

Next steps: deploy to mainnet and debug there. Syncing testnet-prod is the next step.
