### ISSUE TITLE
[UI] Swap and Pool UI errors

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4323]
**Describe the bug**
A user tried to swap USDT to nextUSDT on Polygon and an "index is not defined" error appeared.
![image](https://github.com/connext/monorepo/assets/84744304/a4c17919-57a7-40fb-9e70-b50421ddfc71)
Then when adding liquidity to the pool, they got a call revert error similar to this one https://github.com/connext/monorepo/issues/4231
![image](https://github.com/connext/monorepo/assets/84744304/607472fd-8de3-4e79-8ce3-b8ea93801041)

**Additional context**
User is running metamask on chrome. https://discord.com/channels/454734546869551114/816982956684869654/1110622685635018792

**Comment by pjenviri** [comment]
Fixed the "index not defined" error, but it still reverts.  @sanchaymittal do you have some insight on this issue?

**Comment by Tommy-R8** [comment]
A user is getting `missing revert data in call exception` error when trying to deposit in a pool.
![image](https://github.com/connext/monorepo/assets/84744304/e34f0ecc-8616-4d9d-97e1-d2d13a941305)

Context:
https://discord.com/channels/454734546869551114/1120292771585065051/1120292911867764928

**Comment by just-a-node** [comment]
Could not repro with USDC on any chain - will get more details from the user in discord

**Comment by LayneHaber** [comment]
closing, stale.
