### ISSUE TITLE
[ui] Intermittent Gnosis <> BSC Errors

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4325]
## Background

Gnosis team reported errors on the UI. Screenshots provided

### Linked Issues & Documentation

Screenshots:

![IMG_2357.JPG](https://images.zenhubusercontent.com/5ac530304b5806bc2bcdaed0/7b51fbda-57f1-4b4b-ad8b-737bb490e053)

![IMG_2356.JPG](https://images.zenhubusercontent.com/5ac530304b5806bc2bcdaed0/25d1e7c9-d15c-488e-ba5a-c1cd854763f1)

## Definition Of Done

Consistently able to transfer from Gnosis to BSC

**Comment by pjenviri** [comment]
I cannot reproduce it. Could you try it again? If the issue persists, please share the error messages shown in the console log (begin with `[xcall]` & `[xcall error]`) . Thank you.

**Comment by LayneHaber** [comment]
closing, stale
