### ISSUE TITLE
[router-executor] Hitting CPU limits under load

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4328]
**Describe the bug**
Router continues to crash on testnet-prod when under high (2K requests / minute) load from processing many reconciled transfers.

**To Reproduce**
CPU load on router:

![image.png](https://images.zenhubusercontent.com/5ac530304b5806bc2bcdaed0/416dd037-b1dc-46c4-acd1-53d3a9248099)

**Comment by preethamr** [comment]
Can be resolved, by increasing the EC2 instance size.

**Comment by preethamr** [comment]
Monitor testnet after the bump up. Seems stable now.

**Comment by rhlsthrm** [comment]
Stabilized with a bigger box. We should never see it increasing with load. Closing.
