### ISSUE TITLE
The processing shouldn't scale with load on router-publisher

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4340]
**Describe the bug**
Router-publisher tries to process all the pending txs by getting from the redis-cache. 
This would definitely increase the cpu/mem usage as the number of pending txs increases leading to prod agent keep exiting

**To Reproduce**
1. Lots of pending txs stored in the cache
2. Router-publisher keeps reading/sending the txs to the sequencer
3. The more we have pending txs in the cache, the cpu/mem usage will also increase

**Additional context**

**Comment by preethamr** [comment]
This is not seen in latest.
