### ISSUE TITLE
Expose the testnet cache to analyze the cache usage

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4344]
## Background

What we want here is to make the management tool/management service connected to the testnet redis instance. 
Sometimes we're seeing `maxmemory` issue in the sequencer cache which will definitely increase the mem usage. but don't know the root cause. 

I hope we can figure it out using like management/analyze tools easily. We don't need to expose mainnet ones

**Comment by rhlsthrm** [comment]
Will be necessary, working on getting this done.

**Comment by rhlsthrm** [comment]
Getting this working on ops side.

**Comment by LayneHaber** [comment]
"blocked" because we are running terraform to push images from feature branch to testnet prod

**Comment by LayneHaber** [comment]
Need to add credentials, returning to in progress. Requires changing how all agents connect to cache

**Comment by rhlsthrm** [comment]
This is quite difficult to implement properly and will change Redis connection details. I propose that we remove this from the task list.
