### ISSUE TITLE
Allow horizontal scalability of LH prover

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4345]
## Problem
_What problem are we solving?_ 
LH prover can go very slowly through big tx backlog.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
Need to scale this up before getting lots of traffic from campaigns.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
- Create prover publisher that reads DB and puts messages into a queue structure. Prover can do basic checks and figure out which messages are provable on certain roots, but it should not do too much processing in order to stay lightweight.
- Subscribers read from queues based on what messages they can batch and prove.
- Subscribers can be set up as lambdas. This will help us validate this strategy and potentially implement it on sequencer subscriber as well: https://aws.amazon.com/about-aws/whats-new/2021/07/aws-lambda-now-supports-amazon-mq-for-rabbitmq-as-an-event-source/
- Subscribers submit batches to chain.
- Add ops.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Lighthouse is set up as a pub/sub structure and deployed.

**Comment by rhlsthrm** [comment]
Rahul working on ops side to get lambdas set up properly, getting PR: https://github.com/connext/monorepo/pull/4372/files running.

Ready to test with AWS setup.

**Comment by rhlsthrm** [comment]
AWS setup is up, working on testing this on testnet.

**Comment by rhlsthrm** [comment]
Remaining, writing unit tests and deploying ops.

**Comment by rhlsthrm** [comment]
Debugging on AWS.

**Comment by LayneHaber** [comment]
Status: Currently not processing any messages on testnet.

- Lambdas connected
- Application error on the lambda side -- not getting the correct data
- May have to change how the docker image is built / getting created

@preethamr can try take a look -- @wanglonghong to leave update

**Comment by rhlsthrm** [comment]
Need to make sure it's working, currently testing on testnet.

**Comment by LayneHaber** [comment]
Need to connect lambda to redis

**Comment by rhlsthrm** [comment]
Fixing ops, ready for merge after fixes and final local testing.

**Comment by rhlsthrm** [comment]
Ready for review and merge into testnet-prod.

**Comment by rhlsthrm** [comment]
Monitoring on testnet prod, seems good so far, waiting for a while longer until we merge to mainnet.
