### ISSUE TITLE
Unnecessary processing in sequencer for slow path executions

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4348]
**Describe the bug**
For slow path, the sequencer does not need to store stuff in cache. It can simply just send anything it receives to Gelato, after checking the subgraph to see if it's valid.

**To Reproduce**
1. Check sequencer logs.
2. See lots of logs related to slow path caching stuff.

**Additional context**

**Comment by sanchaymittal** [comment]
To cut down unnecessary processing in sequencer:

- [ ] we can cut down the data required via cache
       - rmv TransferCache: query transfers data via subgraph, instead of storing, updating and querying from cache.
       - we probably can't strip down it entirely, cause we still need saveError, getPending and bidStatus. (Note: during implementation go through code and simply these actions more)
 
- [ ] simplify the cache storage schema (Note: implementation of simplifying storage should directly result in reducing the number of queries made to cache)
