### ISSUE TITLE
[sequencer] Failure to execute transfers in queue

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4350]
**Describe the bug**
Transfers getting held up, repeating the `Already enqueued log`:

https://app.datadoghq.com/logs?query=service:sequencer%20@requestContext.transferId:0x877f286249b598d4c2803cf70c4f3a202598762a878a67dafbbeb9422b50e79d&cols=service&index=mainnet-production&messageDisplay=inline&saved-view-id=1285114&stream_sort=desc&viz=stream&from_ts=1685104345776&to_ts=1685118745776&live=true

**To Reproduce**

**Additional context**

**Comment by rhlsthrm** [comment]
Should be fixed after prod merge.
