### ISSUE TITLE
[UI] Approval and Insufficient Balance errors

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4351]
**Describe the bug**
I have 29.998133213170503056 DAI on Polygon and wanted to bridge to Gnosis xDai. Selected my balance and the input field was filled correctly with 29.998133213170503056. As I didn't have the token spending approval, it prompted this transaction, but with the approval amount set as 29.998133213170505 (ends in 505 instead of 503056), a higher approval than my balance. Despite me manually changing the token approval amount to my exact balance, when I try to bridge it detects that I lack sufficient approval and it prompts me to make an approval tx again. There seem to be discrepancies between the numbers shown in the UI, in my wallet, and those seen in the console. After doing the approval with the amount prompted by the site, it gives me a transfer amount exceeds balance error.

**Additional context**
`[approveIfNeeded before xcall] {domain_id: '1886350457', contract_address: '0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063', amount: '29994752891460308319', approve_amount: '29998133213170504459', infiniteApprove: false}amount: "29994752891460308319"approve_amount: "29998133213170504459"contract_address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"domain_id: "1886350457"infiniteApprove: false`
![image](https://github.com/connext/monorepo/assets/84744304/8b567551-95b8-4cd8-98f2-4d6ea9626d27)
![image](https://github.com/connext/monorepo/assets/84744304/47bf9ecc-b52e-4116-b145-5cb1e7fb9afb)

**Comment by Tommy-R8** [comment]
https://discord.com/channels/454734546869551114/1114792253005766706/1114792313378586694 Another case

**Comment by Tommy-R8** [comment]
https://discord.com/channels/454734546869551114/1114978846459035842/1114979081306525726 Another case but this time it has only 1 decimal

**Comment by pjenviri** [comment]
I remembered the issue was resolved; Tommy/Andy pinged me on Discord regarding this. 
I also couldn't reproduce it.
