### ISSUE TITLE
getTransfers method in SDK 

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4369]
**Describe the bug**
`getTransfers method in sdk(sdkUtils) returns `any` type as a response which can create TS error in strict TS repositories`

**To Reproduce**
1. `const transferStatus = await sdkUtils.getTransfers(params)`
2. Paste this in TS repo with strict `tsConfig`

**Additional context**

**Comment by prathmeshkhandelwal1** [comment]
```
 async getTransfers(params?: {
    userAddress?: string;
    routerAddress?: string;
    status?: XTransferStatus;
    errorStatus?: XTransferErrorStatus;
    transferId?: string;
    transactionHash?: string;
    xcallCaller?: string;
    range?: { limit?: number; offset?: number };
  }): Promise<any>
```

Signature of method defined in SDK

**Comment by alexwhte** [comment]
**Complexity: 5**
  [See the discussion](https://action.parabol.co/meet/nBkwGMURd6/estimate/1) in Sprint Poker #​​37

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
