### ISSUE TITLE
Message verification fails bc of duplicated/missing leaves in the message table

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4376]
**Describe the bug**
MessageVerification fails due to the both reasons recently

1. Duplicated leaves
  It was happening sometimes on polygon bc of the block reorganization. 
2. Missing leaves
  It was happening on arbitrum. 
![image.png](https://images.zenhubusercontent.com/5b67a142386aa6742a90bc34/8a113f44-d6e1-4290-af5b-758ed419794f)

**Comment by sanchaymittal** [comment]
#4413 had the same issue, due to a reorg single transfer record at Message table under cartographer, the whole network had downtime at the polygon.

**Comment by sanchaymittal** [comment]
Scope and Solution:
**Save messsages with re-org protection**

- add safe blocks check at poller of messages under cartographer

**Comment by wanglonghong** [comment]
> what about Arbitrum?

I don't think we have the reorg issue on arbitrum but just saw a couple of leaves are missing when I was fixing. Tbh, this is the first time I've seen the missing leaves on arbitrum.

**Comment by LayneHaber** [comment]
> I don't think we have the reorg issue on arbitrum but just saw a couple of leaves are missing when I was fixing. Tbh, this is the first time I've seen the missing leaves on arbitrum.


Were they attached to polygon at any point?

**Comment by sanchaymittal** [comment]
created another issue: #4449
