### ISSUE TITLE
[eng workflow] Dynamic oncall role bot

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4391]
## Problem
Mods don't know who to ping from the engineering side when faced with a user issue in a ticket. Tickets don't get assigned quickly and it delays their solution.

## Impact
More scalable and quicker resolution of user issues. Better workflow around tickets and reduces churn from users.

## Proposed Solution
This is part of a broader solution, but we need a Discord bot that's able to assign and remove an `oncall` role to the correct engineers based on a schedule we feed it.

## Acceptance Criteria
Tagging @oncall always pings the correct people at a certain moment.

**Comment by alexwhte** [comment]
**Complexity: 8**
  [See the discussion](https://action.parabol.co/meet/nBkwGMURd6/estimate/10) in Sprint Poker #​​37

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
