### ISSUE TITLE
calculateAmountReceived Failing

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4393]
**Describe the bug**
calculateAmountReceived method in SDK is failing with few params.

**To Reproduce**
Call this method with mentioned params.
```
const originDomain = "1634886255";
const destinationDomain = "1886350457";
const originAsset = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1";
const amount = "1000000000000000000";
sdkBase.calculateAmountReceived(
  originDomain,
  destinationDomain,
  originAsset,
  amount
);
```

**Additional context**
Works with testnet params

**Comment by prathmeshkhandelwal1** [comment]
throw new Error("Origin token cannot be bridged to any token on this destination domain");

**Comment by rhlsthrm** [comment]
This actually works, was a misconfiguration on SDK.
