### ISSUE TITLE
Chain abstraction SDK estimateAmountReceived

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4395]
## Problem
_What problem are we solving?_ 

With origin/destination swaps included in the chain abstraction flow, the core SDK's `estimateAmountReceived` function does not sufficiently provide the final amount received.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

Chain abstraction integrators need a way to estimate the final amount received after all 4 potential swaps: 
1) [origin] DEX swap
2) [origin] Connext AMM swap 
3) [destination] Connext AMM swap 
4) [destination] DEX swap

Core SDK's estimate only covers 2) and 3).

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

Add an `estimateAmountReceived` function in the chain abstraction SDK that accounts for 1) and 4) as well.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] `estimateAmountReceived` function in CA SDK provides final amount after the full  CA flow

**Comment by LayneHaber** [comment]
Fairly important -- need @prathmeshkhandelwal1 and @just-a-node to fix once #4223 is done

**Comment by rhlsthrm** [comment]
* Add SDK as dependency.
* Calculate bridging route by using USDC for now, later we will query for best route.

**Comment by rhlsthrm** [comment]
Added 1inch and Uniswap V3 swappers. Remaining is to add Uni V2.

**Comment by rhlsthrm** [comment]
Ready for review, needs review.
