### ISSUE TITLE
Create a view to see routers by asset

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4403]
## Problem
_What problem are we solving?_ 
It's not very easy to see router liquidity by asset. For example, I want to see which routers hold ETH.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
We are seeing txs where routers should have enough liquidity to complete but they do not go through fast path. This would help us debug better.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
- Router view should display assets they hold, in addition to chains.
![Screenshot 2023-06-05 at 16.52.34.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/c3112a05-adc4-4fac-aa3c-81d7c658c7cf)
- Clicking on an asset should filter router and liquidity by that asset.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Page operates as described above.

**Comment by sanchaymittal** [comment]
`router_with_balances` has active liquidity available under locked, if we put the DB data under time series we can get a graph of router interaction and active bids action. Can compare with the transfers graph to see the winner of the bids and more insightful data.

**Comment by rhlsthrm** [comment]
At this point we don't need all that I just want to know which routers to click on when I'm looking at a particular asset.

**Comment by Tommy-R8** [comment]
related to https://github.com/connext/monorepo/issues/3922

**Comment by pjenviri** [comment]
We've added a list of routers with each asset shown under the RouterLiquidity table: https://connextscan.io/ethereum.
