### ISSUE TITLE
[all] Bedrock Upgrades

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4404]
**Describe the bug**
Need to upgrade the optimism connectors to account for the bedrock upgrade. Will also require an update to the offchain (lighthouse specifically) code.

Bedrock upgrade is scheduled for Wednesday at 1600 UTC

**Additional context**
Optimism Bedrock connectors have been running on testnet for a while.

**Comment by alexwhte** [comment]
Need to 
- redeploy connector
- update subgraph to point at new connector
- update lighthouse

in parallel: 
- notify ecosystem to assist community comms

**Comment by LayneHaber** [comment]
current status:

- monitoring these two transfers for reconciliation prior to reenabling:

https://connextscan.io/tx/0xd60d8d65e6128da5178ec7a4cd31a22d30307565024e2418df523d527611be49?src=search

https://connextscan.io/tx/0x21d4a80c6fd98f8acef2e1eb436594ff783ee6009ca20908e3ccc96afdc2ab24?src=search

Once those reconcile without manual intervention (i.e. through normal offchain processes), we can reenable on coinhippo UI and announce on discord

**Comment by LayneHaber** [comment]
worked, reenabled + announced
