### ISSUE TITLE
Mainnet issues generating subtree

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4405]
**Describe the bug**
https://app.datadoghq.com/logs?query=%22RangeError%3A%20Invalid%20array%20length%22%20&cols=host%2Cservice&event=AgAAAYiMQlsLGxEQiQAAAAAAAAAYAAAAAEFZaU1RbTRGQUFCRllHb3dWUURNOHdDWQAAACQAAAAAMDE4ODhjNDItODRjNC00MzEwLTk5MDMtOTdjMzU3N2U4MTY4&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1685979427339&to_ts=1685980327339&live=true

`RangeError: Invalid array length` in lighthouse prover

**Comment by sanchaymittal** [comment]
resolved, after deleted duplicates under messages table. #4376 issue to resolve the issue in future.
