### ISSUE TITLE
Optimism bedrock notice and UI updates

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4412]
## Problem
Optimism will be offline tomorrow for their hardfork (bedrock)

## Solution

1. Replace the banner above Connext bridge with below
> Notice: On June 6 16:00 UTC the Optimism chain will be unavailable for up to 4 hours as the Optimism network completes their [bedrock upgrade](https://oplabs.notion.site/Bedrock-Mission-Control-EXTERNAL-fca344b1f799447cb1bcf3aae62157c5). 

2. Disable Optimism from all UIs temporarily

3. Have a change to re-enable ready to go for when we can give the greenlight

**Comment by pjenviri** [comment]
Here's the [PR](https://github.com/CoinHippo-Labs/connext-bridge/pull/127) & [Preview](https://connext-bridge-mainnet-git-feat-disable-optimism-coinhippo.vercel.app/USDC-from-ethereum-to-binance). Please confirm so that we can merge or you can merge it directly.

**Comment by pjenviri** [comment]
This is the pr to re-enable Optimism: https://github.com/CoinHippo-Labs/connext-bridge/pull/128; feel free to merge it when everything is ready.
