### ISSUE TITLE
Re-Org non-existent transfers under Transfer table

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4449]
**Describe the bug**

Due to re-org at network especially at Polygon, we sync the data at transfer table without safe blocks protection to reduce data latency. A solution has already been implemented for Messages Table under issue(#4376). We need similar solution for transfer table.

Another assumption as of now is related to relational data mapping, i.e for single nonce and message entry two transfers pointing at one message entry. Considering it's a foreign key, there could be a possible error(not 100% sure about it).

Solution:
- upsert entry in transfer table with (index,domain) combo.

**Additional context**

**Comment by rhlsthrm** [comment]
Working on this now, similar to other issue.

**Comment by rhlsthrm** [comment]
Need to handle reconcile/destination.
