### ISSUE TITLE
Stuck Transactions on No Bids Received

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#4462]
**Describe the bug**
We're having issues again with a lot of txns in no bids received status.

<img width="1138" alt="image" src="https://github.com/connext/monorepo/assets/26097731/9ac097ee-dca7-4d65-b4ca-6729c2bc4805">

<img width="1115" alt="image" src="https://github.com/connext/monorepo/assets/26097731/df1a74dc-1f03-47e5-be99-a5b336b79dea">

<img width="1229" alt="image" src="https://github.com/connext/monorepo/assets/26097731/156573aa-5c0a-4cf8-886c-e9fd664506ac">

<img width="1184" alt="image" src="https://github.com/connext/monorepo/assets/26097731/e052496d-8149-4b59-8729-7dadaba05cfd">

<img width="1160" alt="image" src="https://github.com/connext/monorepo/assets/26097731/fe433db2-0968-4cc2-bfe1-bee640dfaffb">

https://connextscan.io/tx/0xbf18fafea98ce7bfd6e9e77649e97a8a2fe5c14b272ab0f908d373b6115e3834

https://connextscan.io/tx/0xf0b913734cd270fb0f8b5bdd642a1ca4390a4f67042c51c484ac46f47910dcad

https://connextscan.io/tx/0x6dc4d765d635cbe9178050e20b40adbcbb34f0824e50af21a99aec5be629c51c
**Additional context**

Previous issue: https://github.com/connext/monorepo/issues/4417

https://discord.com/channels/454734546869551114/1117301972672974889
https://discord.com/channels/454734546869551114/1117301460846252063
https://discord.com/channels/454734546869551114/1117300740575215739

**Comment by sanchaymittal** [comment]
As of now, the solution was resolved by reset at sequencer.
