### ISSUE TITLE
xToken whitelisting improvements 

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#4473]
Not a high priority, but making a note of small things that would improve the xToken whitelisting process on our end.

- [ ] Consolidate configs across repositories to one single JSON (maybe in chaindata?)
- [ ] Default to `address(0)` if no mapping is provided for a given domain
- [ ] Restructure config to make it forward compatible with potentially 100s of assets and chains
- [ ] Add sanity checks into whitelisting script for duplicates and other potential human errors
- [ ] Simplify object names to make them more self-explanatory for projects to contribute to

**Comment by LayneHaber** [comment]
Would be good to be able to specify which assets as part of the init script as well

**Comment by LayneHaber** [comment]
likely out of scope
