### ISSUE TITLE
Some messages in LH prover fail verification

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4482]
**Describe the bug**
Some messages in LH prover fail verification

**To Reproduce**
1. Go to '[...](https://app.datadoghq.com/logs?query=region%3Aus-west-1%20service%3Alighthouse-prover-subscriber%20Message%20verification%20failed%20&cols=host%2Cservice&event=AgAAAYizbmhd2vvtHwAAAAAAAAAYAAAAAEFZaXpibWlwQUFDbmJrVW5SZzc4X0FBRgAAACQAAAAAMDE4OGIzNmUtNmYzOC00ZjQ1LTlhN2EtZjY3NTJlMjRiNzc3&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1686636688218&to_ts=1686637588218&live=true)'
<img width="1110" alt="image" src="https://github.com/connext/monorepo/assets/1195648/24893b53-caf0-4105-856a-cddf60211444">

**Additional context**

**Comment by alexwhte** [comment]
@wanglonghong is this in QA? can you move and try to complete before next sprint?
