### ISSUE TITLE
Sequencer subscriber queue is not as per the config

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4484]
**Describe the bug**
Sequencer subscriber queue is not per the config

**To Reproduce**
1. User production like config
2. Find seq subscriber uses fallback config as primary does not work

**Additional context**
From discord:
https://discord.com/channels/992549151134982234/1111186796441772032/1118059500864282674

seems like currently, prefetch is defaulting to 100 per instance:
https://github.com/connext/monorepo/blob/33cea659e923866dff213e113f2e996aa8d7b5ae/packages/agents/sequencer/src/sequencer.ts#L169
and it takes the else path:
https://github.com/connext/monorepo/blob/33cea659e923866dff213e113f2e996aa8d7b5ae/packages/agents/sequencer/src/sequencer.ts#L197-L212

**Comment by sanchaymittal** [comment]
replicated locally, it's looking good so far. closing it for now
