### ISSUE TITLE
Changelog: track every change and summarise code updates

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4486]
## Problem
_What problem are we solving?_ 

we need a summary of each pr and commit being merged to the Main, Testnet-prod, and Prod branches. Gives us context of recent changes to the code base.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

[ ] Create file at root Release_Changelog
[ ] Design format for the changelog updates for PRs and merge

An example here:
```
...
- [#pr/commit](link/) TLDR
summary of changes that were done with the above pr to the code base. This means even if we are doing prod sync, it should include the files which were affected by this update.
ps: will be creating a more defined format to summarize the changes and files affected by it.
...
```

## Acceptance Criteria
_From an end-user perspective, the below criteria must be met to consider this done:_
- [ ] engineers are able to identify the changes which have been made to the code.
- [ ]

**Comment by LayneHaber** [comment]
this is happening
