### ISSUE TITLE
[UI] Change USDC name on Arbitrum

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4494]
**Describe the bug**
Since June 8th there's native USDC on Arbitrum. USDC bridged from Ethereum is now called USDC.e and we need to reflect that in our UI so that users don't get confused (it happened once already). The name should only change on Arbitrum and nowhere else. It should also be changed in the explorer UI.

**Comment by pjenviri** [comment]
updated to `USDC.e`.
![Screenshot 2566-06-14 at 00.53.32.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/d2ebae8e-86c0-47fd-adaf-5a82b7ec96d2)

**Comment by alexwhte** [comment]
adding myself to do tool tip or something

**Comment by alexwhte** [comment]
Please add tooltip 'Circle has renamed bridged USDC to USDC.e on Arbitrum network. For more information please see [this link](https://www.circle.com/blog/arbitrum-usdc-now-available).'

**Comment by pjenviri** [comment]
display the message when hovering on `USDC.e`.
![Screenshot 2566-06-20 at 23.02.30.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/710a1a11-caf4-4888-84da-68839f7a3740)
