### ISSUE TITLE
Connextscan missing Optimism events.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#4503]
**Describe the bug**
Optimism [TX ](https://optimistic.etherscan.io/tx/0x66d4fdd12c720b9be9a308937b9cef2dc6eda87c73f56c9a9be5fcd4137474b5) is not shown in scan.
Relying on user [wallet](https://connextscan.io/address/0xad997638331eab4eb8518cf299c11175696a249d): `0xad997638331eab4eb8518cf299c11175696a249d`

**Additional context**
[Discord Link](https://discord.com/channels/454734546869551114/1118572916787925084/1118574066601840680)

**Comment by Tommy-R8** [comment]
Update: Optimism subgraphs fell behind

**Comment by LayneHaber** [comment]
a few hosted service subgraphs are behind:

https://status.thegraph.com/

following up with their team

**Comment by rhlsthrm** [comment]
Graphs are back up.
