### ISSUE TITLE
xCalled transactions piling up

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4504]
**Describe the bug**
At least 31 transactions stuck in xcall as long as 2.5hs. The amount is increasing. It doesn't seem to be chain or amount specific.
![image](https://github.com/connext/monorepo/assets/84744304/c6012c86-362c-4886-b0f8-561c6cf9d243)

**Comment by LayneHaber** [comment]
a few hosted service subgraphs are behind:

https://status.thegraph.com

following up with their team

**Comment by rhlsthrm** [comment]
Very low amount of XCalls now. Subgraph service is restored. Closing.
