### ISSUE TITLE
Executed txs piling up

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4511]
**Describe the bug**

Seeing more executed txs than usual.

**To Reproduce**
![Screenshot 2023-06-15 at 08.55.50.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/294278a2-23b5-4cbd-aa29-4e35c6be12d6)

**Additional context**

**Comment by alexwhte** [comment]
![image](https://github.com/connext/monorepo/assets/37959170/14a60ccd-4e0c-4bcf-af38-c21fe97b6061)

**Comment by rhlsthrm** [comment]
We have disabled BSC on UI and announced to partners to disable for now. This requires Multichain replacement.

**Comment by rhlsthrm** [comment]
#4517 will close this.

**Comment by sanchaymittal** [comment]
EPIC has been desgined, closing this issue.
