### ISSUE TITLE
Spec out integration tester environment

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4514]
## Problem
_What problem are we solving?_ 
We still do not have integration tests.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
This is required for Op Roots. This is also a must for us to improve code quality and stability.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Spec exists.

**Comment by rhlsthrm** [comment]
https://www.notion.so/connext/spec-Integration-Tester-Environment-7a21670935ef44b9a4091b633a11164e?pvs=4

**Comment by rhlsthrm** [comment]
Collecting final feedback before initial task breakdown.

**Comment by sanchaymittal** [comment]
spec is ready with basic scope, we will be breaking down sub task and design the epic this week.
