### ISSUE TITLE
Stuck Transaction on No Bids Received

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#4516]
**Describe the bug**
14k txn went through the slow path, but routers liquidity on BNB Chain is more than enough to deal with it.

https://connextscan.io/tx/0x4ef5ee8733d9df5bc66d0e3127866bab98682b9122630be4ada302384ed99e74?src=search

<img width="1208" alt="image" src="https://github.com/connext/monorepo/assets/26097731/87279785-fbf6-4446-bb94-0567f48df431">

<img width="1580" alt="image" src="https://github.com/connext/monorepo/assets/26097731/ab43e3fa-7da7-4ce1-a085-c1e228ff5742">

I don't see more stuck txns, just this one

**Additional context**
https://discord.com/channels/454734546869551114/1118948369704943666

**Comment by rhlsthrm** [comment]
It depends how this is split. We split things in very specific ways. /2, /4, /6 only so if there wasn't enough for that it won't work.
