### ISSUE TITLE
Don't round up token amount

### ISSUE THREAD

**Issue by maxlomu** [connext/monorepo#4519]
If you round up token amount by default in the bridge UI, it will try to send more tokens than the user has

![image](https://github.com/connext/monorepo/assets/57088593/e8c295c7-cfab-4c59-a562-8c585d3d24ba)

**Comment by massimol** [comment]
![image](https://github.com/connext/monorepo/assets/57088593/e8f2780d-d654-4b78-a337-2ff0ef40daed)
