### ISSUE TITLE
CI at terraform plan step failing

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4530]
**Describe the bug**

CI has been showing green for `testnet-prod` merges but the step at "Terraform Plan" has actually been failing for the last week, skipping the steps for prod testnet.

<img width="1434" alt="image" src="https://github.com/connext/monorepo/assets/16638982/7a056f95-aef7-4108-8229-04cb2002d538">

**To Reproduce**
1. Check GH actions history for `testnet-prod` branch
2. See that recent actions have been green but actually failing at the Terraform Plan step

**Additional context**

**Comment by preethamr** [comment]
Not is affecting prod testnet
