### ISSUE TITLE
Run successful internal load test

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4535]
## Background

We must have a successful internal load test over 12 hours with 0 failures.

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Load is successful.

**Comment by rhlsthrm** [comment]
1. Gelato balance, needs 500 gETH per day.
2. CPU/mem and DB operations are hitting limits.

**Comment by LayneHaber** [comment]
Subtasks: #4575 #4565

**Comment by preethamr** [comment]
We have not seen any failure of infra, and stuck transfers that were not expected, over a 24 hour period.

Pending messages on testnet:
```
 count | origin_domain |              now              
-------+---------------+-------------------------------
    47 | 2053862260    | 2023-06-30 17:33:40.826955+00
     2 | 9991          | 2023-06-30 17:33:40.826955+00
```
We generated and reconciled, ~550K tansfers over the last few days.
~10% of them are not fully completed  (yet) coz of low relayer fee

Total number of transfers in testnet rn: ~1.73M
