### ISSUE TITLE
Onchain task for BNB AMB

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#4538]
## Problem
Replace BNB multichain connector

## Context
- https://github.com/connext/monorepo/issues/4517
https://connext.notion.site/Pre-Spec-for-BSC-Amb-3578aea3d7a4485eb63498ece0b22fbd

## Action Items
- [x] HubConnector for Wormhole 
- [x] SpokeConnector for Wormhole
- [x] Forge Tests: Unit test covering all fuzz cases
- [x] E2E testing 
- [x] HH tasks for deployment and test
- [x] Init script
- [x] deployment at Testnet for initial testing for the Wormhole contracts
- [x] Deploy Connector for Mainnet
- [x] Deploy Connector for spoke

## Acceptance criteria

- [ ] E2E working at `BNB`, `ARBITRUM`, and `ETHEREUM` (Fork Mainnet).
- [ ] Succesful xcall() via HH tasks
- [ ] Succesful sendMessage() via HH tasks
- [ ] Succesful propagate() via HH tasks
- [ ] Succesful proveAndProcess() via HH tasks
- [ ] Does not double-reconcile transfers ( `MessageStatus` checks are overridden on new spoke deploy)
- [ ] Does not double-process transfers (should not cause many transfers to be `proveAndProcess`ed again. this will require offchain verification against newly deployed subgraphs)

Fixes #4623

**Comment by rhlsthrm** [comment]
Verified that old message cannot be processed by new connector, so double spend is not an issue.

**Comment by rhlsthrm** [comment]
Created forge test, requested review, R4R.

**Comment by rhlsthrm** [comment]
Contract is done, need to test on testnet, but Wormhole does not support Goerli. Need to either test on other testnets or mainnet.

**Comment by rhlsthrm** [comment]
Verified messaging from BNB to ETH, still verifying ETH to BNB.

**Comment by LayneHaber** [comment]
txs + costs:

```md
ETH -> BSC 
 - 0.000254019196160768 ETH ($0.48) paid on ETH 
 - 0.000713894285678591 BNB ($0.17) refund
 - total: $0.31 paid
- txs:
https://etherscan.io/tx/0x580a3dcec415417b949e947e1335b58b6eeb31f128136b48a3b0c35e0570cbfa
https://bscscan.com/tx/0xc5478c6cacb5fffc2ced78201dd1d6e5d7f6e2b3ab41f89c5b30cc4788e51790

BSC -> ETH
 - 0.096724973432518598 BNB ($23.07) paid on BSC
 - 0.00510868 ETH           ($9.7) refund
 - total: $13.37
 ```

**Comment by rhlsthrm** [comment]
Ready for audit, will not deploy and init as part of this task.

**Comment by alexwhte** [comment]
we are moving deployment and testing into separate issue

 Deploy Connector for Mainnet
 Deploy Connector for spoke
**Acceptance criteria**
 Does not double-reconcile transfers ( MessageStatus checks are overridden on new spoke deploy)
 Does not double-process transfers (should not cause many transfers to be proveAndProcessed again. this will require offchain verification against newly deployed subgraphs)
