### ISSUE TITLE
[UI] Don't allow paying gas in long tail assets

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/monorepo#4554]
UI should only allow paying gas in transacting asset for blue chip assets like ETH and major stables.

As we're starting to onboard more long tail xTokens, we need to be careful that we don't accidentally prompt users to pay fees in the xToken as this is not going to be supported by sequencer and their txs will get stuck.

**Comment by alexwhte** [comment]
@coinhippo please have a config where we can set which assets are possible to be transacting asset 

The assets we should allow for are USDC, USDT, DAI, and ETH only

If the user is sending any other asset, then default to the native gas token for now (not transacting asset)

**Comment by pjenviri** [comment]
updated: https://github.com/CoinHippo-Labs/connext-bridge/commit/f838eab352de4fbb690c1627b119a595e749a292
