### ISSUE TITLE
DB is running too high on CPU during prover operation

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4565]
**Describe the bug**
DB CPU is getting maxed out.

**To Reproduce**
![Screenshot 2023-06-21 at 17.05.06.png](https://images.zenhubusercontent.com/5ab95b244b5806bc2bcc7b6a/b1cf046f-5ce2-4d90-9604-7b74c3953083)

**Additional context**
https://use-the-index-luke.com/sql/where-clause/searching-for-ranges/greater-less-between-tuning-sql-access-filter-predicates

Can filter by domain first to get some performance increases.

**Comment by LayneHaber** [comment]
retry mechanism is not always robust enough and we self-dos sometimes. still working, but slower

fixing this to meet throughput goals
