### ISSUE TITLE
ProverX queue messed up by LH prover publisher

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4568]
**Describe the bug**
Tons of same messages enqueued repeatedly because of lh prover.

**To Reproduce**
1. LH prover publisher starts every 5mins and tries to enqueue messages, but never completes if the backlog is huge.
2. Even if we have a sanitation check to get the message status from onchain, it wouldn't work because the next instances will publish the same messages in parallel
3. Result in the mess in proverX and lower the processing speed

**Additional context**

**Comment by preethamr** [comment]
Potential solution:
Set a max limit on the number of batches submitted by LH pub, in one iteration.
Expected behavior: It submits up to max, and ends iteration with proper exit code. Next iteration, triggered via lambda, will continue from where the previous iteration ended.

**Comment by rhlsthrm** [comment]
Closed with retry mechanism.
