### ISSUE TITLE
Lighthouse should use read replica when possible

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4571]
**Describe the bug**
LH Provers should use read replica end point for db operations that don't write.

**To Reproduce**
1. Go to:
![image](https://github.com/connext/monorepo/assets/1195648/ebe3592d-5a1f-4ba6-8b70-a5df5ef0cfc7)

**Additional context**
https://discord.com/channels/992549151134982234/1119294499659714602/1121065767291584552
This query is a read only query and should go to read replica

**Comment by preethamr** [comment]
Changes in branch: `4571-lighthouse-should-use-read-replica`

**Comment by rhlsthrm** [comment]
This is merged to testnet.
