### ISSUE TITLE
LP removals exceed additions

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4573]
**Describe the bug**

trying to turn around a list of lpers (sorted by lp amt) for OptyFi by EoD, if possible.
see https://docs.google.com/spreadsheets/d/1rD15iNKVWiMSccBBpvPkLUnas-tMIDOc671oJIHer-Y/edit#gid=822511116

- several addresses have more withdrawal events than deposit (possibly missing lp deposit events?)
- in one case, we have a line item that claims that a negative amount of ETH was deposited into the pool

**To Reproduce**
Using ```SELECT
	sum(lp_token_amount),
	action,
	provider,
	CASE WHEN pooled_tokens IN ('{0x2fd7e61033b3904c65aa9a9b83dcd344fa19ffd2,0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9}', '{0xe221c5a2a8348f12dcb2b0e88693522ebad2690f,0xc2132d05d31c914a87c6611c10748aeb04b58e8f}', '{0x4cbb28fa12264cd8e87c62f4e1d9f5955ce67d20,0x94b008aa00579c1307b0ef2c499ad98a8ce58e58}', '{0xd609f26b5547d5e31562b29150769cb7c774b97a,0x55d398326f99059ff775485246999027b3197955}', '{0xf4d944883d6fddc56d3534986fef82105cadbfa1,0x4ecaba5870353805a9f068101a40e0f32ed605c6}') THEN
		'USDT'
	WHEN pooled_tokens IN ('{0x0e1d5bcd2ac5cf2f71841a9667afc1e995caaf4f,0xe91d153e0b41518a2ce8dd3d7944fa863463a97d}', '{0xadce87b14d570665222c1172d18a221bf7690d5a,0x8f3cf7ad23cd3cadbd9735aff958023239c6a063}', '{0x0e1d5bcd2ac5cf2f71841a9667afc1e995caaf4f,0xe91d153e0b41518a2ce8dd3d7944fa863463a97d}', '{0x86a343bcf17d79c475d300eed35f0145f137d0c9,0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3}', '{0xd64bd028b560bbfc732ea18f282c64b86f3468e0,0xda10009cbd5d07dd0cecc66161fc93d7c9000da1}',
	'{0xfde99b3b3fbb69553d7dae105ef34ba4fe971190,0xda10009cbd5d07dd0cecc66161fc93d7c9000da1}') THEN
		'DAI'
	WHEN pooled_tokens IN ('{0x5e7d83da751f4c9694b13af351b30ac108f32c38,0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d}', '{0x8c556cf37faa0eedac7ae665f1bb0fbd4b2eae36,0xff970a61a04b1ca14834a43f5de4533ebddb5cc8}', '{0xf96c6d2537e1af1a9503852eb2a4af264272a5b6,0x2791bca1f2de4661ed88a30c99a7a9449aa84174}', '{0x67e51f46e8e14d4e4cab9df48c59ad8f512486dd,0x7f5c764cbc14f9669b88837ca1490cca17c31607}', '{0x44cf74238d840a5febb0eaa089d05b763b73fab8,0xddafbb505ad214d7b80b1f830fccc89b60fb7a83}') THEN
		'USDC'
	WHEN pooled_tokens IN ('{0x2983bf5c334743aa6657ad70a55041d720d225db,0x82af49447d8a07e3bd95bd0d56f35241523fbab1}', '{0x4b8bac8dd1caa52e32c07755c17efaded6a0bbd0,0x7ceb23fd6bc0add59e62ac25578270cff1b9f619}', '{0x538e2ddbfdf476d24ccb1477a518a82c9ea81326,0x6a023ccd1ff6f2045c3309768ead9e68f978f6e1}', '{0xa9cb51c666d2af451d87442be50747b31bb7d805,0x2170ed0880ac9a755fd29b2688956bd959f933f8}', '{0xbad5b3c68f855eaece68203312fd88ad3d365e50,0x4200000000000000000000000000000000000006}') THEN
		'ETH'
	END AS asset--,
	--date(to_timestamp(timestamp))
FROM
	stableswap_pool_events
GROUP BY
	2,
	3,
	4--,5--,6
ORDER BY
	1,3,2 ASC```

**Comment by just-a-node** [comment]
Confirmed some of these providers have consolidated LP tokens from other wallets for larger withdrawals.
