### ISSUE TITLE
LH messages can get retried indefinitely

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4575]
**Describe the bug**
LH messages can get retried indefinitely

**To Reproduce**
1. Go to '[...](https://app.datadoghq.com/logs?query=region%3Aus-west-1%20service%3Alighthouse-prover-subscriber%20failed%20&cols=host%2Cservice&event=AgAAAYjlOy2BgG3q3AAAAAAAAAAYAAAAAEFZamxPeV9yQUFDdXJBU2ZydFVFWFFBQQAAACQAAAAAMDE4OGU1M2ItMmVhNi00MWU4LTk4YjAtMmM3ZGY2MjYzNWJl&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1687472161447&to_ts=1687473061447&live=true)'
<img width="1048" alt="image" src="https://github.com/connext/monorepo/assets/1195648/e4b01527-ddaf-4ee0-a700-4aec3f0d603c">

**Additional context**
There are a few options:
1. Let publisher retry, so client can drop
2. If client retries, (as of right now), it should timeout after each attempt

3 Using retry counts like in sequencer to try a max number of times before dropping it.

**Comment by preethamr** [comment]
Additional context:
https://app.datadoghq.com/logs?query=host%3Aip-172-17-1-246.us-west-1.compute.internal%20service%3Alighthouse-prover-subscriber%20container_id%3A4cf2357956b1475297c7b354a919cc1c-2228731739%20task_arn%3A%22nxtp-ecs-core-testnet-production%2F4cf2357956b1475297c7b354a919cc1c%22&cols=host%2Cservice&context_event=AYjlqdU6AAAuncAXeOKISAAA&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=&from_ts=1687468309990&to_ts=1687482709990&live=true
<img width="2026" alt="image" src="https://github.com/connext/monorepo/assets/1195648/1d6f589c-4cae-4912-8470-ecc1522ff15d">

**Comment by wanglonghong** [comment]
Would you post the brief explanation why it throwing with `!MessageStatus.None` here?

**Comment by LayneHaber** [comment]
retry mechanism is not always robust enough and we self-dos sometimes. still working, but slower

fixing this to meet throughput goals

**Comment by rhlsthrm** [comment]
Merged, monitoring testnet prod. Might need to add another mechanism to limit retry count. Once it gets queued, it shouldn't get re-queued again, need to add a status.

**Comment by wanglonghong** [comment]
Its fixed by the message cache implementation
