### ISSUE TITLE
The user's large transaction has not been passed for more than two hours.

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#4582]
Tx Id
 
https://connextscan.io/tx/0x655c85ec2b46673efa5277085167a6634ba3ccee283b74944879f4558a43450f
**Additional context**
https://discord.com/channels/454734546869551114/1122110428579905636/1122110433478840353

**Comment by oswy-cpu** [comment]
Another one: https://connextscan.io/tx/0x54fc6c544a3c4cab66254a4872eb7c9ca13484be0f5af1789b6ef3ac17177764

99k from BNB to ETH. 5h atm

**Comment by preethamr** [comment]
> Tx Id
> 
> https://connextscan.io/tx/0x655c85ec2b46673efa5277085167a6634ba3ccee283b74944879f4558a43450f

This transfer has completed. No bids were received in fast.

**Comment by alexwhte** [comment]
Finished in 5:40 min. Leaving up for oncall to check why it took this long

**Comment by sanchaymittal** [comment]
these happened due to low router liquidity, and the network involved is polygon which has delayed checkpoint creation to complete slow path.
