### ISSUE TITLE
Passing BSC UI-block.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#4583]
**Describe the bug**
The user found a way how to use Connext from/to BSC through the UI.

**To Reproduce**
1. Go to 'swap' page
2. Pick BSC and change the network in Wallet
3. Return back to 'Bridge' page

**Additional context**
https://discord.com/channels/454734546869551114/1122582528092549130/1122591862994256104

**Comment by alexwhte** [comment]
@coinhippo can we please
- Remove BSC in the bridge options entirely
- Add handling to automatically prompt user to switch to Arbitrum default whenever enters the Bridge UI with BSC connected

ALSO, a couplte new things i found:
1-
Currently there is buggy behavior in the Pool UI when I switch to BSC it automatically prompts me to switch to arbitrum
This should not happen as BSC is still available in Pools and Swaps 
https://www.awesomescreenshot.com/video/18629049?key=95d1c383dcdbd7073c1500c592ce253d

2- 
BSC should not be hidden from Swaps either
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/95d2a5a2-6eaf-4c06-b46c-b2d3061a0c69)

**Comment by alexwhte** [comment]
@coinhippo can we please
- Remove BSC in the bridge options entirely
- Add handling to automatically prompt user to switch to Arbitrum default whenever enters the Bridge UI with BSC connected

ALSO, a couplte new things i found:
1-
Currently there is buggy behavior in the Pool UI when I switch to BSC it automatically prompts me to switch to arbitrum
This should not happen as BSC is still available in Pools and Swaps 
https://www.awesomescreenshot.com/video/18629049?key=95d1c383dcdbd7073c1500c592ce253d

2- 
BSC should not be hidden from Swaps either
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/95d2a5a2-6eaf-4c06-b46c-b2d3061a0c69)

**Comment by pjenviri** [comment]
It is fixed and merged. https://github.com/CoinHippo-Labs/connext-bridge/pull/140
