### ISSUE TITLE
Get commmitlint to put some respect on the default squash+merge commit string

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4591]
## Problem

Commitlint doesn't like the default commit string for squash+merged PRs.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

Makes CI red.

## Proposed Solution

Make a custom exception in the commitlint config to be okay with the default commit string.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Commitlint doesn't prevent CI from completing for squash+merged PRs

**Comment by alexwhte** [comment]
if we dont fix this we cant release things without going back and fixing and it wastes engineering capcity

**Comment by sanchaymittal** [comment]
is this still an issue? I couldn't find the commits which failed at prod. Can you guys link a case here?
