### ISSUE TITLE
Connextscan UI issue - Router's detail by asset (mobile)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#4592]
**Describe the bug**
Router's detail by asset looks messy lol. It happens with every chain site and i've tried a few mobile browsers.

![image](https://github.com/connext/monorepo/assets/26097731/11103f2d-dff9-4f85-9417-a7fa55a7f801)

**To Reproduce**
1. Go to https://connextscan.io/gnosis or any other chain (on mobile browser)
2. Navigate to the bottom

**Additional context**
None.

**Comment by pjenviri** [comment]
Fixed.

**Comment by MinistroDolar** [comment]
> Fixed. 

It's better but still a bit buggy.
(Note that im setting the zoom to the minimum)

If i choose the default config its even worse 

Min zoom:
![image](https://github.com/connext/monorepo/assets/26097731/d856cbca-1fc1-4267-9c24-cbdc8b5543e7)

Default:
![image](https://github.com/connext/monorepo/assets/26097731/34fcdc7b-309f-4eb7-ad23-e3b1add4bb56)

**Comment by pjenviri** [comment]
Updated. Please try it on your device again. Thanks!

**Comment by MinistroDolar** [comment]
> Updated. Please try it on your device again. Thanks!

It's awesome now. 
![image](https://github.com/connext/monorepo/assets/26097731/70045a66-fc9b-4372-86d7-1f0ddbc89754)
![image](https://github.com/connext/monorepo/assets/26097731/a3e16044-2504-48ce-bcab-89d5b9b22617)

Thanks!!
