### ISSUE TITLE
Avoid using hardcoded gasLimit in the codebase.

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4597]
## Problem
The gasLimit is needed to make a request to gelato service. Right now, we're using hardcoded ones in the codebase which makes difficult to update if needed.

## Proposed Solution
Use gasLimit from [crosschain.json](https://github.com/connext/chaindata/blob/main/crossChain.json). 

- [ ] Compute gasLimit from gelato txs on all chains for both execute and reconcile
- [ ] Add/Update gasLimit in [crosschain.json](https://github.com/connext/chaindata/blob/main/crossChain.json) with the values calculated above

## Acceptance Criteria
- [ ] Don't break anything due to the croschain.json changes.
- [ ] Remove everything unnecessary stuff from crosschain.json.

**Comment by alexwhte** [comment]
These are hardcoded in SDK so whenever we want to update we need a new SDK version
It would be better to update the file crosschain.json vs. having to cut a new SDK version 
Change in utlils

**Comment by alexwhte** [comment]
Closing as we discovered we do need to use this in some places per @rhlsthrm
