### ISSUE TITLE
AdminConnector Message Investigation

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4602]
**Describe the bug**
Despite spoke root being aggregated, transfers from bnb are not being processed. most seem to have an incorrect message status (`XCalled` for the older ones, `SpokeRootArrivedOnHub` for the newer ones)

**To Reproduce**
Find oldest and newest transfers with this query:

```sql
select
	status, 
	message_status, 
	message_hash, 
	root, 
	processed,
	index,
	transfers.transfer_id
from transfers 
left join messages on transfers.message_hash = messages.leaf 
where transfers.origin_domain in (
	'6450786' 
) and processed = FALSE order by xcall_timestamp asc limit 2;
```

alternating `asc` / `desc` in order direction

**Additional context**
Here is the root manager transaction showing the root in question being aggregated:

https://etherscan.io/tx/0x2968a0af0598f3b68daf078b91b8b275c3cd4b5dd69bddc5c77955994c668bdd

https://dashboard.tenderly.co/lhaber/project/tx/mainnet/0x2968a0af0598f3b68daf078b91b8b275c3cd4b5dd69bddc5c77955994c668bdd/logs

**Comment by preethamr** [comment]
I see LH Prover never got any messages originating from BnB:
https://app.datadoghq.com/logs?query=region%3Aus-east-2%20service%3Alighthouse-prover%20%40unprocessed.destinationDomain%3A6778479%20&cols=host%2Cservice%2C%40chainId%2C%40destinationDomain%2C%40originDomain&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1687297573284&to_ts=1687902373284&live=true

**Comment by rhlsthrm** [comment]
Issue was the root wasn't sent from BNB spoke connector, sent properly and messages went through.
