### ISSUE TITLE
Multiple lambdas run at the same time

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4607]
**Describe the bug**

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by rhlsthrm** [comment]
Monitoring today and will confirm this is working today.

**Comment by preethamr** [comment]
Confirmed app based mutex as fix for this is working for LH Prover Pub lambda.

Closing this issue.

Any changes needed for other lambdas with the same concern, can be tracked here:
https://github.com/connext/monorepo/issues/4622
