### ISSUE TITLE
fix: defilama stats 

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4616]
**Describe the bug**

defilama stats are wrong for connext, we need to fix it.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by wanglonghong** [comment]
Would you describe the bug in more details? I remember the issue but I don't think it has enough context to fix the bug as soon as possible.  At least, url/screenshot, whatever is fine.

**Comment by LayneHaber** [comment]
@sanchaymittal still relevant?
