### ISSUE TITLE
Slippage on Pools seems to be reversed

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4627]
**Describe the bug**
The slippage seems to be negative where it should be positive, and vice versa.
![image](https://github.com/connext/monorepo/assets/84744304/7283c75d-38cc-4c94-8ec4-992eb12c98e9)
![image](https://github.com/connext/monorepo/assets/84744304/28382c48-d205-4ef6-a1f4-220150f186ee)
The Polygon USDT pool is unbalanced towards nextUSDT, and when withdrawing nextUSDT, you receive more. The slippage in that case should be positive. However, the UI says it's negative.

**Comment by pjenviri** [comment]
I understand that it can be a negative value (similar to what Sanchay mentioned [here](https://discord.com/channels/992549151134982234/994389387834032198/1126554144661061703)). Please let me know if I have misunderstood something.

By the way, when calling the method, the console log is `[removeLiquidityPriceImpact]`.

**Comment by sanchaymittal** [comment]
cc: @Tommy-R8 @wanglonghong ⏫

**Comment by just-a-node** [comment]
@pjenviri We may need to flip the sign for slippage % for withdraw. If you are withdrawing the overweighted asset then your slippage should be positive.

**Comment by pjenviri** [comment]
updated & deployed; [PR](https://github.com/CoinHippo-Labs/connext-bridge/pull/165).

**Comment by Tommy-R8** [comment]
The issue is happening again. It shows positive slippage both ways. Withdrawing USDT should be negative.
![image](https://github.com/connext/monorepo/assets/84744304/66580b17-6d8a-4e73-b398-038a48e8711b)
![image](https://github.com/connext/monorepo/assets/84744304/152e7076-68ad-4626-8888-51f5267d651c)

**Comment by just-a-node** [comment]
Not anymore.
