### ISSUE TITLE
Pool errors 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4632]
**Describe the bug**
Misleading error when depositing into and withdrawing from Pools

Deposit USDT into BSC

**To Reproduce**
1. Go to pools BNB USDT
2. Deposit 1 USDT
3. See error (even though successful)
> [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":3460668160301,"jsonrpc":"2.0","...5a3a57c68656e82af6a33a0715102736d9c87ae8db2235cd7a57a525248688d405bfaa3089f383ce931d336"],"method":"eth_sendRawTransaction"}}}}'

![image](https://github.com/connext/monorepo/assets/37959170/39a32941-cc14-4611-bcca-d91a3bda38ac)

4. Go to Withdraw

![image](https://github.com/connext/monorepo/assets/37959170/70dfb2b5-cfab-491a-950f-284bb51b6c13)

[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"request":{"id":3460668160304,"jsonrpc":"2.0","...b169a0dbf72add6bf5a9aa03966dafd8b14a555689540b4a34f5c8cde281708ff134965f272f1126588d973"],"method":"eth_sendRawTransaction"}}}}'

**Additional context**

**Comment by pjenviri** [comment]
[Fixed](https://github.com/CoinHippo-Labs/connext-bridge/commit/5af33fe6c522a05f63403d028bf030393741d437). It will show `Failed to send transaction` when getting this error.
