### ISSUE TITLE
Chrome network interactions failing

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4633]
**Describe the bug**
Interactions between UI and Metamask wallet switching are not working as expected in Chrome. See video below

https://www.awesomescreenshot.com/video/18861754?key=ded52f3eda68d59d064af3d31c16d806

**Comment by pjenviri** [comment]
We couldn't reproduce it (tested with 4 devices using Chrome and Brave). Could you please check again and let me know if the issue still persists?

**Comment by sanchaymittal** [comment]
I tried reproducing it at my end as well, couldn't see this issue. Closing this for now, we can reopen if we see this issue again.
