### ISSUE TITLE
Allow users to search by destination hash

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4644]
Socket shared transfer below as having issues todayhttps://arbiscan.io/tx/0xfd925701b7735ca5a2adcd89fbcc39cfb2f3d4795ba7143d074dc7b1c4d8a91a

This is the `execute` hash of this transfer https://connextscan.io/tx/0xc820c88bccfacaca6db4fda691e8d44c7bef694d256eea907b3d7c914cb42e1a?src=search

Is not searchable in connextscan by the arbitrum hash
https://connextscan.io/tx/0xfd925701b7735ca5a2adcd89fbcc39cfb2f3d4795ba7143d074dc7b1c4d8a91a?src=search

Solution:
Allow searching by xcall or execute hash

**Comment by pjenviri** [comment]
Understand that the SDK doesn't support searching transaction/execute hash. Could you please confirm? @rhlsthrm @sanchaymittal

**Comment by rhlsthrm** [comment]
Yes, we need to update the SDK for this.
