### ISSUE TITLE
[sequencer] Add supported contract to fee whitelist

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4654]
## Background

Need to add the `Distributor` contract as an origin sender who is not charged relayer fees.

Goerli address: `0xc8D125853346a389A8a68390dd23D719c08BF8F8`

### Linked Issues & Documentation

N/A

## Definition Of Done

Relayer fees are not required for `xcall`s initiated from the goerli distributor contract.

## Tasks

- [ ] Add address to config

**Comment by rhlsthrm** [comment]
@LayneHaber pls review: https://github.com/connext/monorepo/pull/4663
