### ISSUE TITLE
Use USD pricing in explorer for Alchemix assets 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4655]
These should be updated to use pricing oracle across Explorer

ETH: https://connextscan.io/tx/0x06d5c338d3ec8b5e53de8570ccb79c00135668d7e7903045660d5e36c8142427

USDC: https://connextscan.io/tx/0xee2f1bdaf103624ad5f9c2d4d9f002c1bded89b0175282c7ae07bcca5cae4928
-

**Comment by alexwhte** [comment]
note we should figure out for all new xTokens as we scale

**Comment by pjenviri** [comment]
Could you add the field that indicates the USD value of each transfer data?
