### ISSUE TITLE
Bug - Relayer Fees bump for transaction

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4660]
## Background

Connextscan asking for bumping relayer fees even after calculating it from sdk. 
Firstly thought this can be gas spike. but the issue persists from more than a day.

### Linked Issues & Documentation

Example transaction: - https://connextscan.io/tx/0xfc1c7c0537a87942c852a624e9b78a6aa3bd328dfcec5e8e8deb106e648d5c77?src=search

**Comment by wanglonghong** [comment]
It looks like the sdk method returns zero relayerfee so something is wrong here. let me start debugging it

**Comment by wanglonghong** [comment]
Figured out why.
TL;DR; Its not a protocol bug. There was an issue in use of sdk method @prathmeshkhandelwal1 confirmed about that.
