### ISSUE TITLE
Test for burst load

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4666]
**Describe the bug**
Simulate the anticipated burst load during token launch, by initiating as many transfers as possible, in a very short period of time, ideally within the same minute.

**Additional context**
We want to know how our system reacts, when we initiate, say 50K transfers simultaneously.

**Comment by alexwhte** [comment]
Goals: Measure expected peak scenario simultaneous crosschain claim
- measure how long it takes to get through a backlog and if claimin users will see significant delays
- find unforseen issues with our system handling a large burst of load

**Comment by rhlsthrm** [comment]
Nothing more to do here, closing.
