### ISSUE TITLE
"bad result from backend" when withdrawing from LP

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4676]
**Describe the bug**
A user tried to withdraw USDT from the Arbitrum pool and got a "bad result from backend" error. Trying a custom amount with 1 USDT less than the balance worked. 
![image](https://github.com/connext/monorepo/assets/84744304/e9078c18-86d2-49a8-a7c6-9440f8155093)

**Additional context**
https://discord.com/channels/454734546869551114/1128332983074558022/1128333100309553214

**Comment by just-a-node** [comment]
Could not repro this exact path. This might be an intermittent error from Metamask and rpcs. Would ask the user to try a different rpc provider next time.

@pjenviri Will leave this open to see if you can reproduce. A potentially? related error is if you select withdraw 100% it will sometimes (not always, oddly) give an "amount < LPToken balance" error. This resolves if you withdraw 75% first and then 100% of the remainder. Seems like a rounding issue.

**Comment by pjenviri** [comment]
This [pr](https://github.com/CoinHippo-Labs/connext-bridge/pull/147) fixes the rounding decimals issue, which is expected to solve this ticket.

**Comment by sanchaymittal** [comment]
let's monitor if the above fixes resolved the ticket!
