### ISSUE TITLE
Transaction takes too long and wrong approximate time on aggregator page (bungee)

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#4682]
User has transferred funds more than 3 hours ago and UI on bungee said that it'll take 3 minutes for this transaction to be proceed
![image](https://github.com/connext/monorepo/assets/93597601/6b7d3bf4-cd12-45da-814b-75d9f36f1c28)

https://connextscan.io/tx/0xec663cd308e8d9cecb4ca2e56c53a1aef1f4ce6d6a0eda60ed56fd0112289014?src=search

https://discord.com/channels/454734546869551114/1128475068616429589

**Comment by LayneHaber** [comment]
delayed because of lack of liquidity and slow lighthouse rate. manually ran:
https://connextscan.io/tx/0xec663cd308e8d9cecb4ca2e56c53a1aef1f4ce6d6a0eda60ed56fd0112289014?src=search
