### ISSUE TITLE
"My Positions" tab not working

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4683]
**Describe the bug**
The "My Positions" tab on the pools section of the bridge site doesn't work. 
![image](https://github.com/connext/monorepo/assets/84744304/597f785b-2206-4952-82c8-954c0b40a372)

**To Reproduce**
1. Go to bridge.connext.network/pools
2. Click on My Positions
3. See error

**Comment by pjenviri** [comment]
The issue is fixed. https://github.com/CoinHippo-Labs/connext-bridge/pull/146
