### ISSUE TITLE
Dynamic time estimates 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4685]
## Problem
Time estimates are often wrong and are not dynamic nor are they based on the paths, which play a big factor

## Solution
NOTE: This is the only best solution without contract changes
Routers won't bid unless evenly divisible. Need to implement changes to allow bids for remainders in the same way we do onchain: https://github.com/connext/monorepo/blob/4c057678966204b0f65dfd2d63acd4b6f051ca67/packages/deployments/contracts/contracts/core/connext/facets/BridgeFacet.sol#L904-L91

Expose this in a way that integrators can also call this endpoint

## Acceptance criteria
- [ ] Time estimates are accurate according to the above variables
- [ ] This is able to be accessed both in our UI and integrators 

## Other notes
NOTE Socket has this API but it does not appear we can use it 

Socket estimates time to receive funds based on last 60 minutes combination of bridge+origin+destination
We should test out using their API vs building our own

we have an API endpoint here:

curl -X 'GET' \
  'https://api.socket.tech/v2/supported/bridges' \
  -H 'accept: application/json'

![telegram-cloud-photo-size-5-6156783126181951387-y.jpg](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/79c1fd59-2607-4339-b7ee-4b715ead133a)

**Comment by pjenviri** [comment]
The API endpoint doesn't support passing any parameter. So, the responses for the `Connext` object are usually 240s for every chain pair, symbol, amount, and other option. Endpoint doc: https://docs.socket.tech/socket-api/v2/supported/bridges
