### ISSUE TITLE
Not seeing MessageProcessed events on mainnet from Wormhole connector

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4686]
**Describe the bug**

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by liu-zhipeng** [comment]
https://etherscan.io/tx/0x5ca71ce18aa027bf942ba9ca261ab687985cbbd0fae711093a5bf2876bb9defd

i could execute `receiveWormholeMessages` on my local. ^^ tx is the process message tx for the latest tx of bsc. I am contacting to wormhole team as well.

**Comment by rhlsthrm** [comment]
Root cause is Wormhole relayer service was not working. Continuing to monitor. Will create other tasks if necessary to work around.
