### ISSUE TITLE
lighthouse pg error

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4688]
**Describe the bug**

Seeing: "error: cannot execute INSERT in a read-only transaction" on process from root in lightouse

- https://app.datadoghq.com/logs?query=index%3Amainnet-production%20service%3Alighthouse-process-from-root%20&cols=host%2Cservice&event=AgAAAYlKuHqmORoLpAAAAAAAAAAYAAAAAEFZbEt1SWJPQUFBWHBUeU85dkJkYVFDVAAAACQAAAAAMDE4OTRhYjgtOTVkYS00ZTllLTg2MjYtZDNjZDhmM2IxZTdm&index=mainnet-production&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1689108659560&to_ts=1689123059560&live=true

**Comment by preethamr** [comment]
This is seen in testnet too:
https://app.datadoghq.com/logs?query=region%3Aus-west-1%20service%3Alighthouse-process-from-root%20status%3Aerror&cols=host%2Cservice&event=AgAAAYlGOzPglhyXCAAAAAAAAAAYAAAAAEFZbEdPMVJxQUFDSmxnZ2t5akk2MXdBYwAAACQAAAAAMDE4OTQ2NmEtZDhjNS00NDY0LThjMGEtYjE0ZjZkOThiYzU1&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1688922588973&to_ts=1689181788973&live=true

RCA:
Using reader URL to write. Needs a simple config-code change.
