### ISSUE TITLE
Set up Integration Tester repo

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4691]
## Problem
_What problem are we solving?_ 
Build integration tester.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
We need to test op roots.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
* Create new repo.
* Set up file structure.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Repo exists.
- [ ] Files exist with a nice structure.
- [ ] able to run forge scripts in order to update storage

**Comment by sanchaymittal** [comment]
done, https://github.com/connext/integration-test
