### ISSUE TITLE
CLI to spin up and down resources.

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4692]
## Problem
_What problem are we solving?_ 
The integration tester needs a CLI. This is just first phase. 

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
Integration tester is needed for op roots testing.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] CLI is created.
- [ ] CLI consumes config file and passes them into docker config.
- [ ] Command for spinning up resources.
- [ ] Command for spinning down resources.

**Comment by sanchaymittal** [comment]
In progress, Add a script to take up and down resources.

**Comment by sanchaymittal** [comment]
In progress

**Comment by sanchaymittal** [comment]
- fixing the devnet script spin-up
