### ISSUE TITLE
Took 12 minutes to bridge from Polygon To Arbitrum

### ISSUE THREAD

**Issue by maxlomu** [connext/monorepo#4696]
8 USDC

https://connextscan.io/tx/0xfcef6a8dd916418c9833b9ce294254bf32e4325d1936b0bf57a492bc8e12e23d?_gl=1*tdpvyl*_ga*MTE2NzU5NzUzOS4xNjg0MTY3NTI4*_ga_MPYZEDRVQ0*MTY4OTI2NDAzOS4yMC4xLjE2ODkyNjQxNzQuMC4wLjA

Also I have read a couple of complaints on Twitter that we often go to slow path with Ethereum as destination chain, not sure if it's lack of liquidity or other issue.

**Comment by just-a-node** [comment]
No valid bid combinations received by sequencer. Unclear if this is a liquidity issue or routers aren't bidding properly.
