### ISSUE TITLE
Chain abstraction hacker kit

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4702]
## Background

In preparation for Connext hackathons, we need to organize streamlined developer resources. Ideally, this is a 1-pager with links to relevant chain abstraction docs, SDK methods and examples, and the reference UI (or some forkable equivalent). 

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Public 1-pager

**Comment by alexwhte** [comment]
not just under guides

add use cases sectoin
