### ISSUE TITLE
xTokens in docs 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4703]
## Problem
Move xTokens to docs

## Impact
https://www.notion.so/connext/Public-xTokens-Setup-Guide-be4e136a6db14191b8d61bd60563ebd0

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by alexwhte** [comment]
ensure steps are quite clear
highlight usecases

**Comment by rhlsthrm** [comment]
Closing until we figure out how lockbox will look.
