### ISSUE TITLE
Burst load test with 1k/min with Gelato limit increase

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4704]
## Problem
_What problem are we solving?_ 

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by alexwhte** [comment]
Waiting for gelato to confirm tomorrow they are ready

**Comment by rhlsthrm** [comment]
Test has been run.

**Comment by alexwhte** [comment]
https://discord.com/channels/992549151134982234/1136885438062272552/1139816341713457192
Router >1K 
Gelato ~1.2K limit 
Sequencer ~800 
Lighthouse ~900
Routers are still missing bids 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFVGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a62f3d4fd36775bd3db8d016bb52415f8e4d3506/image.png)
