### ISSUE TITLE
Params invalid error when updating slippage

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4707]
**Describe the bug**
The user is prompted to update slippage but gets a "Params invalid" error message. 
![image](https://github.com/connext/monorepo/assets/84744304/80819629-1a07-4093-a5fc-0a0c4f84da71)

https://connextscan.io/tx/0xadf1572a9fe20e834aa6dbff9b135a769b1e1ba240569e15d747a491d4b946e6

**Additional context**
https://discord.com/channels/454734546869551114/1130602845540991156/1130605610254205108

**Comment by preethamr** [comment]
This seems like a UI value input error. Should `slippage` param be a string ?
<img width="1079" alt="image" src="https://github.com/connext/monorepo/assets/1195648/a86c4a90-891e-4bb1-a64e-7254cff9359e">

**Comment by just-a-node** [comment]
> This seems like a UI value input error. Should `slippage` param be a string ? <img alt="image" width="1079" src="https://user-images.githubusercontent.com/1195648/254078368-a86c4a90-891e-4bb1-a64e-7254cff9359e.png">

Yeah it can, input is typed as `TIntegerString`

**Comment by pjenviri** [comment]
Updated the `param` to be a string. However, I think it might be because: https://github.com/connext/monorepo/blob/main/packages/agents/sdk/src/sdkBase.ts#L460.

**Comment by alexwhte** [comment]
@preethamr or @just-a-node can you please check the last comment?

just saw this and im not sure how to replicate/test

**Comment by just-a-node** [comment]
Fixed
