### ISSUE TITLE
Help measure onchain usage data for Zodiac 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4709]
## Problem
We have no idea how to measure usage of our zodiac module

## Impact
Zodiac team is seeking to goal around this 

## Proposed Solution
Measure using this info. Can you help point me to how?

> Skeletor Spaceman, [Jul 11, 2023 at 1:38:30 PM]:
> GitHub - defi-wonderland/zodiac-connext-module-factory
> Contribute to defi-wonderland/zodiac-connext-module-factory development by creating an account on GitHub.
> 
> Skeletor Spaceman, [Jul 11, 2023 at 1:38:30 PM]:
> address of deployed factories: https://github.com/defi-wonderland/zodiac-connext-module-factory#deployments
> 
> Alex White, [Jul 11, 2023 at 1:39:50 PM]:
> ty!
> 
> Skeletor Spaceman, [Jul 11, 2023 at 1:41:35 PM]:
> hmm but we don't save it on an internal mapping and we do not emit any event on the factory.
> the connext module does tho: emit ModuleSetUp(owner(), avatar, target, originSender, origin, connext);
> 
> but since the owner and a few other parameters are the actual factory, you can easily filter them too :)
> 
> _connextModule = new ConnextModule{salt: _moduleSalt}(
>       // Hardcoded values are replaced with the correct values
>       // after creating the safe (owner, avatar, target, connext)
>       _FACTORY_ADDRESS, // Hardcoded for ownership control (owner)
>       _FACTORY_ADDRESS, // Hardcoded for ownership control (avatar)
>       _FACTORY_ADDRESS, // Hardcoded for ownership control (target)
>       _moduleData.originSender,
>       _moduleData.origin,
>       _FACTORY_ADDRESS // Hardcoded, factory is connext (connext)
>     );

**Comment by LayneHaber** [comment]
stale, closing
