### ISSUE TITLE
User should send and receive adopted Alchemix assets

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4716]
## Problem
Currently Alchemix assets in our bridge UI force into nextalUSD and nextalETH
This is because our implementation is a bit custom and requires wrapping/unwrapping
For more context see https://discord.com/channels/992549151134982234/1060165785558982697/1114215305896534108

## Impact
Alchemix is one of our key well known early implementations and a showcase we want to use to generate more xToken demand

## Proposed Solution
Wrap into and out of alchemix adopted assets where needed
![image](https://github.com/connext/monorepo/assets/37959170/31c4332b-5ca4-4378-a2a0-d6a6395965a7)

L2 gateway contracts
Optimism gateway 0xb46eE2E4165F629b4aBCE04B7Eb4237f951AC66F
arbitrum 0xb77750E48C2B1E1657cC5Ad7F329133c64A8321F

See 
https://github.com/alchemix-finance/v2-foundry/blob/l2-al-asset/src/bridging/connext/AlchemixConnextGateway.sol

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] User can send and receive adopted alUSD and alETH 
- [ ] This works correctly between Ethereum, Arbitrum, and Optimism
- [ ] Toggling to receiveLocal correclty changes this

**Comment by prathmeshkhandelwal1** [comment]
https://docs.google.com/spreadsheets/d/1Ct66hKrcyn_fEBMO1-XDeaIpSrmXwgiU0swhQlg0I9Q/edit#gid=0

Sheet with tx links to test all permutation and combination for bridging alETH and alUSD
