### ISSUE TITLE
Unable to bridge WETH from Polygon to Gnosis

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4723]
**Describe the bug**
A user reported they weren't getting the Metamask transaction popup when they were trying to bridge WETH from Gnosis to Polygon. When I tried to reproduce the issue, I started by getting some WETH out of Polygon and into Gnosis.  This resulted in an eternally loading "Checking for Approval" and the console shows an error: 
![image](https://github.com/connext/monorepo/assets/84744304/37c01ff7-ddf1-4bce-a43c-f26e624516e5)
![image](https://github.com/connext/monorepo/assets/84744304/4f4694c1-172e-487d-94e9-5c116954f52e)

**To Reproduce**
1. Go to the bridge
2. Try to bridge WETH between Polygon and Gnosis Chain
3. See error

**Additional context**
https://discord.com/channels/454734546869551114/1131627210428645376/1131750581720076438

**Comment by liu-zhipeng** [comment]
![image.png](https://images.zenhubusercontent.com/63331283a97e6555fde71ad4/8656a9ae-d758-42ab-a1d5-ecb8e2a2fb60)

I can reproduce this issue on my end.

**Comment by liu-zhipeng** [comment]
![image.png](https://images.zenhubusercontent.com/63331283a97e6555fde71ad4/5e01b3c3-15e2-46f7-9055-69383d5513fc)

![image.png](https://images.zenhubusercontent.com/63331283a97e6555fde71ad4/2b2dd2ee-2bf4-417b-a83d-a43abbbe4c0d)
I believe this part has problem now. @pjenviri

**Comment by pjenviri** [comment]
Fixed (by handling `e-` value). https://github.com/CoinHippo-Labs/connext-bridge/commit/0b267a75ca98383e59acd948ca95c50edb8e266f

**Comment by pjenviri** [comment]
a feedback from Liu on [Discord](https://discord.com/channels/992549151134982234/1032728270791262360/1131958028418154627):
>  It didn't show previous error on console. but after Checking Approval..., it didn't pop up metamask and return back Send. I can't see any log on console. could you check again?

Update: We downgraded the SDK version to `2.0.3-alpha.11` (it was `2.1.1`). It works on our end now.
