### ISSUE TITLE
Bridge from Goerli to Mumbai not working

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4724]
**Describe the bug**

comms at TG of Autopay
https://testnet.connextscan.io/tx/0x0fa3aec523d616fa693765ef1d167ed2a75da5b615de2c03b45684fa79d0f223

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by liu-zhipeng** [comment]
![image.png](https://images.zenhubusercontent.com/63331283a97e6555fde71ad4/cef7c6a0-48db-4af4-a863-b745678f9f54)

It said `Low RelayerFee` and i bumped a few times.
0.048792WETH = 92$
The estimated relayer fee is too high. that might be an issue.

**Comment by rhlsthrm** [comment]
We don't support WETH transfers, closing this.
