### ISSUE TITLE
Recommended slippage is not accurate

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4725]
**Describe the bug**
Recommended slippage is not accurate

**To Reproduce**
1. [Go to '...'](https://testnet.connextscan.io/tx/0x0fa3aec523d616fa693765ef1d167ed2a75da5b615de2c03b45684fa79d0f223)
<img width="478" alt="image" src="https://github.com/connext/monorepo/assets/1195648/30fdb39e-89d4-4663-ba92-63b149db30df">

**Additional context**
Calculations that lead to this user CTA, should be reviewed, as in this case there is prob no need for user CTA.

**Comment by alexwhte** [comment]
@coinhippo can you check exactly what the estimate is here? 
it's possible if new tolerance == current then we should display higher decimal precision, or otherwise there is a bug

**Comment by pjenviri** [comment]
The UI shows the exact value of the `destinationSlippage` returned by the SDK; only convert it from BigNumber to Decimal number. (hex: 0x261b -> decimal: 9755)
![Screenshot_2566-07-25_at_01.28.59.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/a65f4c0f-6c06-4bd0-9c6d-dbb65fecbcf2)

**Comment by alexwhte** [comment]
@preethamr thoughts on next steps here?

**Comment by rhlsthrm** [comment]
Confirmed this is not a bug.
