### ISSUE TITLE
Transaction ongoing for 11 hours

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4728]
**Describe the bug**
https://connextscan.io/tx/0xbc4e9e2f7753608fc89e389d0b1f9116e10c6729be2403dc3683680bcb65b697 This transaction of WETH from BNB to Optimism has been processing for 11 hours.

**Additional context**
https://discord.com/channels/454734546869551114/1133077002803494992/1133077036609572995

**Comment by liu-zhipeng** [comment]
https://bscscan.com/address/0xc667de991c8b40c969f6996b4f6167851527c9f6#internaltx

**Comment by liu-zhipeng** [comment]
![image](https://github.com/connext/monorepo/assets/57480598/8073c316-dc03-4c50-b6be-914fa18bc1e7)

sent 5 days ago. This might be the reason of current issue

**Comment by wanglonghong** [comment]
ok will keep monitoring.

**Comment by rhlsthrm** [comment]
Topped up RelayerProxy contract.
