### ISSUE TITLE
execution reverted when trying to bridge alUSD

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4729]
**Describe the bug**
A user is trying to bridge alUSD from Arbitrum to Ethereum and gets "unpredictable gas limit" "execution reverted" 
![image](https://github.com/connext/monorepo/assets/84744304/61c0669b-6ade-4c2f-9f55-39c36ccacad9)

**Additional context**
https://discord.com/channels/454734546869551114/1133190397162692608/1133201464085463130

**Comment by 0xanedi** [comment]
Extended logs
![image](https://github.com/connext/monorepo/assets/89958919/1fa14e87-911a-4335-b83e-7b3b76d988d8)

**Comment by sanchaymittal** [comment]
bug on the integrator side.
