### ISSUE TITLE
Transfers taking too long to load

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4733]
I saw this for 10 seconds https://connextscan.io/tx/0x108521bee91ec023fa7fc3a0e42d60d0862a77f8e5d3de576fca4be6ed2a7eb6

![image](https://github.com/connext/monorepo/assets/37959170/7fea9767-22da-4343-9768-75cbf53202ce)

**Comment by pjenviri** [comment]
It was rapidly loaded for me, probably ~2-3 secs. Please confirm if it is still so slow on your end.
