### ISSUE TITLE
Very delayed Router fast path transfers (12-18min)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4734]
Another (small) tx stuck: https://connextscan.io/tx/0xa2366577259abb0da2a873870b620a251a6556991a5ae1eceb18f866b1324b09?source=search
Transfer | Connextscan
[Transfer | Connextscan](https://connextscan.io/tx/0xa2366577259abb0da2a873870b620a251a6556991a5ae1eceb18f866b1324b09?source=search)
Explorer for the Connext protocol
Image
This should be treated as ultra critical, including for token launch
if our routers aren't bidding properly, then this will mean our crosschain airdrop totally fails
cc/ @alexblanq
By the way, this has happened every single time i have used Connext in the past two weeks. Completely unusable
not sure how this is going to work for partners like fuji btw. The above bridge transaction is to GC to fill my wallet so I could play with the Fujii flow. I specifically picked GC because lots and lots of liquidity. I'm willing to bet rn that we see exact same issue with needing to go through slow path when I finally get liquidity and try to use Fuji's dapp
We likely need to escalate this into a p0 to investigate
arjun — Today at 1:51 PM
Completed. Odd?
eddie | MST — Today at 1:51 PM
can't glean from logs exactly what happened here, looks like routers indeed did not bid on this initially
arjun — Today at 1:51 PM
Why did it take 18 minutes?
eddie | MST — Today at 1:51 PM
but yeah it completed just now
arjun — Today at 1:51 PM
Yea this is very weird and bad
@Preetham | PST cc^
Preetham | PST — Today at 2:09 PM
Looking into this
arjun — Today at 2:09 PM
Another: https://connextscan.io/tx/0x108521bee91ec023fa7fc3a0e42d60d0862a77f8e5d3de576fca4be6ed2a7eb6

**Comment by preethamr** [comment]
Routers that bid:
<img width="2050" alt="image" src="https://github.com/connext/monorepo/assets/1195648/8a9dec6e-1486-4820-8b9f-507bc02109e4">

https://app.datadoghq.com/logs?query=region%3Aus-east-2%20%40requestContext.transferId%3A0x108521bee91ec023fa7fc3a0e42d60d0862a77f8e5d3de576fca4be6ed2a7eb6%20-service%3A%28router-publisher%20OR%20router-subscriber%29&agg_q=%40bid.router&cols=host%2Cservice%2C%40bid.router&index=&messageDisplay=inline&sort_m=&sort_t=&stream_sort=time%2Cdesc&top_n=10&top_o=top&viz=sunburst&x_missing=true&from_ts=1673810905780&to_ts=1673897305780&live=true

**Comment by preethamr** [comment]
Router that bid for `0x9ee68898913a7c062f893c57969afdc5dfd8cd06b51c3ad4f3229a92b1bfae48`:

<img width="2045" alt="image" src="https://github.com/connext/monorepo/assets/1195648/a3d8dd66-28ad-40aa-95d1-4084be0d4f7c">
https://app.datadoghq.com/logs?query=region%3Aus-east-2%20%40requestContext.transferId%3A0x9ee68898913a7c062f893c57969afdc5dfd8cd06b51c3ad4f3229a92b1bfae48%20-service%3A%28router-publisher%20OR%20router-subscriber%29%20&agg_q=%40bid.router&cols=host%2Cservice%2C%40bid.router&index=&messageDisplay=inline&sort_m=&sort_t=&stream_sort=time%2Cdesc&top_n=10&top_o=top&viz=sunburst&x_missing=true&from_ts=1673810905780&to_ts=1673897305780&live=true

**Comment by preethamr** [comment]
Likely root cause:
Sequencer does not update auctions data structure, on subsequent bids if this check is false (which is the case when there is a pending execution):
https://github.com/connext/monorepo/blob/7e80436cc42f47a3b60621f349d8b6083e78dc7c/packages/agents/sequencer/src/lib/operations/execute/fastpath.ts#L81

This is where we update auctions:
https://github.com/connext/monorepo/blob/7e80436cc42f47a3b60621f349d8b6083e78dc7c/packages/agents/sequencer/src/lib/operations/execute/fastpath.ts#L97-L108
