### ISSUE TITLE
Crosschain claiming not working / strange in explorer

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4737]
**Describe the bug**
I submit one crosschaiin claim. 
Why are there 2? 
Why do they look weird?

https://testnet.connextscan.io/tx/0xbf7e8772f722eb49b1c97912e798dd6b00ead206f06540cfdcab1ebcb8476897
https://testnet.connextscan.io/tx/0xf36731aab0d82c2fdd49b183f489a611f3e5052c4f0f4ed5cf4b0ed612fbd625

**To Reproduce**
1. Go to https://connext.stagetokensoft.com/claim/0xde56a1d74f83ec3983001ad2538f9dd4c85c722a
2. Make sure your address is whitlisted by Tokensoft to test this app
3. Begin crosschain claim to Optimim 
4. Check explorer

**Additional context**

**Comment by just-a-node** [comment]
Could not repro with another crosschain claim to OP: https://testnet.connextscan.io/tx/0xbc0497a38ee5e7792d194b99db0111942b7702c6b1934d3d714f372b2fe097bd
