### ISSUE TITLE
Create Init script for initializing contracts deployed by forge script

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#4744]
## Background
Need init script to initialize contracts deployed using forge deploy script.
The feature will be exactly same as init cli.

### Linked Issues & Documentation
https://github.com/connext/monorepo/issues/4718

## Tasks

- [x] Init script for assets
- [x] Init script for messaging
- [ ] Task 3

**Comment by sanchaymittal** [comment]
In progress!

**Comment by sanchaymittal** [comment]
- Init script for messaging has been done.
- in progress with script for assets

**Comment by sanchaymittal** [comment]
- internal testing and QA going on

**Comment by sanchaymittal** [comment]
- testing going on, and other action items.
- writing script for fast path case
