### ISSUE TITLE
Set up fast-path processing agents

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4747]
## Tasks
For fastpath processing, we should run the following agents

- [ ] Cartographer 
- [x] Relayer
- [x] Sequencer
- [x] Router

SHOULD be a part of [setup-integration-devnet-test.sh](https://github.com/connext/monorepo/blob/4708-protocol-backend-tasks-for-integration-test/setup-integration-devnet-test.sh)

**Comment by sanchaymittal** [comment]
in progress

**Comment by wanglonghong** [comment]
Relayer, Router and Sequencer parts done. Cartographer depends on devnet database.

**Comment by sanchaymittal** [comment]
we bumped the estimtate, given the time spent on this task. More details will be shared soon here.

**Comment by liu-zhipeng** [comment]
Need help @wanglonghong  @preethamr

**Comment by preethamr** [comment]
Updating the starter script to first bring up DB, and then bring up carto.

ETA by EOD tmrw, perhaps earlier.

**Comment by sanchaymittal** [comment]
- follow up on the rest of the fast-path agents by team hydra

**Comment by LayneHaber** [comment]
@preethamr working on pulling up the data layer at start

open question: how much data do we want in the database when we bring it up? need at most one snapshot period (30min) prior to the devnet start.

**Comment by preethamr** [comment]
Updated with steps to ingest a snapshot version of mainnet DB from S3 into test env cartographer DB.

Steps take ~2 mins in local, with a broadband connection

**Comment by sanchaymittal** [comment]
- config fast-path agents

**Comment by rhlsthrm** [comment]
Config templates for docker build, script for generating config files.

**Comment by rhlsthrm** [comment]
Agents running with dynamic configs. Still seeing a couple errors from docker containers, looks like config issue.
