### ISSUE TITLE
Update decimals and precision in UI

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4753]
## Problem
> Feedback: The decimal and commas on your bridge UI are quite confusing. 
> 
> In the input field you use no decimial seperator and at the output field and the top (balance) you use , as a decimal separator. Would be nice to have this be consistent

![telegram-cloud-photo-size-2-5345841902823524964-y.jpg](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/83116fb9-2796-41e3-8efa-cdfa94518667)

## Proposed Solution
- Dont use commas in any entry boxes of the UIs (ie 'You send' and 'You receive' entries) 
- Limit to 6 decimal precision

**Comment by pjenviri** [comment]
- We never set the input format, and I can't reproduce it. Could it be a locale setup on the device? 
- I quite disagree with limiting it. I think the UI should allow users to fill as many decimals as they prefer. For example, if they want to fill _max_ value stored in their wallet, they should be able to do it. ?

**Comment by alexwhte** [comment]
1. it could be for input format. the reporitng party (gelato founder) is in switzerland

2. I agree to letting them add more decimals if they choose 


Here's another example:
The received amount should not have a decimal here 
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/608b1101-cb83-43b2-a45c-27fc4b25b7bc)

**Comment by pjenviri** [comment]
updated & deployed; [PR](https://github.com/CoinHippo-Labs/connext-bridge/pull/165).
