### ISSUE TITLE
Buggy wrap/unwrap behavior

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4754]
**Describe the bug**
Two issues
1. When I try to wrap ETH, but close out of my wallet before confirming, it keeps spinning / does not exit correctly
It should stop spinning and allow the user to click wrap again. 
https://www.awesomescreenshot.com/video/19564489?key=90667446a8edf844abb63aa5a0e6f964

2. When i enter to wrap 0.01 ETH, it shows 1.0 in my wallet 
It should try to wrap the correct amount
 ![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/bdc5b9bd-d991-4d1f-b2d6-afa2786b9319)

**Additional context**

**Comment by pjenviri** [comment]
Fixed. Please try it once again.
