### ISSUE TITLE
Slippage too low for default

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4756]
Where is this error about slippage from again?  What estimate is the SDK returning?

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/5b6dc002-f79d-48f5-9800-97f0ee40dc21)

I think we have enough liquidity

![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/1b410614-3318-4e67-adf6-9070e0a2f5bb)

**Comment by pjenviri** [comment]
For some reason, the SDK's `calculateAmountReceived` returns `destinationSlippage` = 99.99% when the source chain is Binance.

**Comment by preethamr** [comment]
Looking at the console, this is what we see for that error:
<img width="1958" alt="image" src="https://github.com/connext/monorepo/assets/1195648/61e2b2d9-2f61-432f-96ee-a8cd39a2d4f3">

**Comment by preethamr** [comment]
amountReceived:
```
{
    "originDomain": "6450786",
    "destinationDomain": "1634886255",
    "originTokenAddress": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d",
    "destinationTokenAddress": "0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8",
    "amount": "1000000000000000000",
    "isNextAsset": false,
    "checkFastLiquidity": true,
    "response": {
        "amountReceived": {
            "type": "BigNumber",
            "hex": "0x0f4254"
        },
        "originSlippage": {
            "type": "BigNumber",
            "hex": "0x270f"
        },
        "routerFee": {
            "type": "BigNumber",
            "hex": "0x01f3"
        },
        "destinationSlippage": {
            "type": "BigNumber",
            "hex": "-0x07"
        },
        "isFastPath": true
    }
}
```
