### ISSUE TITLE
Init script doesn't handle assets set up for subset of domains

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4759]
**Describe the bug**

The init script should handle registration of new assets even if not all the domains are configured. Some projects may only want assets deployed to a select number of chains.

**Additional context**

**Comment by LayneHaber** [comment]
Tested against PR: https://github.com/connext/monorepo/pull/4811/files

worked with the following command:

```sh
yarn workspace @connext/smart-contracts initialize --name "assets" --network "testnet" --env "production" --apply "false" --domains "1735353714" "9991"
```
