### ISSUE TITLE
Improve explorer pagination and filtering

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4766]
## Problem
Current navigation in Explorer is quite difficult and we have gathered feedback from users recently
https://connextscan.io/transfers

## Proposed Solution
a) Pagination 
See the current UX https://www.awesomescreenshot.com/video/19605022?key=be26c507b004bf92655c729644c2b31a
We should automatically load all the results the user selects to view per page (if they say view 25 then load 25, if they say view 100 then load 100)
Instead of only numbers, have 'Next' and 'Previous' page buttons 
![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/72f81a70-acec-41c3-85c0-70effca14ab2)
Automatically preload the next page behind the scenes before the user clicks 'Next'. When the user clicks 'Next' then again load the following page behind the scenes

b) Filtering
Allow the user to filter 
- by a date range (Start Date and End Date)
- by boosted transfers (yes vs. no) from fast liquidity 
- by transfer time (minimum and maximum)

**Comment by pjenviri** [comment]
The SDK currently doesn't support providing the total number of pages. Additionally, it doesn't currently support filtering by time, boost status, or time spent.

**Comment by just-a-node** [comment]
a) SDK has options for `range?: { limit?: number; offset?: number }` but not a specific return for total # of pages. However, you could get that by the number of rows returned when leaving the `range` option empty and dividing by total rows displayed per page. Would that work, @pjenviri ?

b) 
- For boosted transfers, we have `status = CompletedFast`. This would only filter for *completed* fast transactions but if that suffices, then the UI can sort on that @alexwhte.
- For transfer time, we could just take `execute_timestamp - xcall_timestamp` for the returned transfers and then do an in-place sort on that, @pjenviri.

**Comment by pjenviri** [comment]
Pushed an update for "b)". cc. @alexwhte 

@just-a-node, regarding "a)", did you mean to suggest that the UI should query all transfers (by iteratively calling `getTransfers` method to get array lists of transfers for all pages) and then calculate the total # pages before displaying the output? If so, I don't think this approach would work well. It could lead to performance issues, slower page load times, and increased backend workload.

For example, if the total number of transactions is 100k, we would need to query 1k times for each user.
