### ISSUE TITLE
User unable to see nextUSDC balance on BSC

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4767]
**Describe the bug**
A user is unable to see his BNB Chain nextUSDC balance on the bridge (and also the swap page). Already tried different RPCs. Other chains detect the balance just fine.

**Additional context**
https://discord.com/channels/454734546869551114/1135561378804023356/1136131124301668402

**Comment by sanchaymittal** [comment]
seems to be fixed! closing it.
