### ISSUE TITLE
Testnet Transfer pending for 24 hours

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4771]
**Describe the bug**

https://testnet.connextscan.io/tx/0xe25c47880ea1af0accbc0e6aa665b0c5a718da09dcc66548014dde6d5ab5f7f4
https://cdn.discordapp.com/attachments/1136185343998181426/1136249936804057098/Screenshot_2023-08-02_at_4.21.19_PM.png

Need to check why slow path isn't working and testnet status as well.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by LayneHaber** [comment]
closing, transfer resolved
