### ISSUE TITLE
Retry mechanism issue in lighthouse-prover

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4772]
**Describe the bug**
We have a retry mechanism implemented in lighthouse-prover. Sometimes it doesn't work properly

**To Reproduce**
Happened in both mainnet / testnet.

1. Go to [DappRadar tx stuck thread](https://discord.com/channels/992549151134982234/1136185343998181426/1136227948723183667)

What I did here is to clear the lighthouse cache, and it worked 
 
2. Go to [messaging-alerts channel](https://discord.com/channels/992549151134982234/1105163410615828480/1136564140920553503)

Also cleared the lighthouse cache to see how it goes. it finally worked.

**Comment by preethamr** [comment]
This fix was merged and tested with 28K transfers load. No issues where found.

**Comment by wanglonghong** [comment]
It happened recently again so reopening @preethamr

**Comment by alexwhte** [comment]
@wanglonghong can you please provide an update here?

**Comment by sanchaymittal** [comment]
completed.

**Comment by wanglonghong** [comment]
> completed.

It still persists. will take a look as p0.
