### ISSUE TITLE
As a user I would like to sort by a specific columns in explorer transfers

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4776]
## Problem
We cant currently sort data, this would help debugging.

## Proposed Solution
Allow the user to sort by a column
The result should be all data sorted, not just visible rows 

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_

[TBD - should have these defined with an action plan of implementation to close this issue; requirement is spec]

- [ ] I have a strong understanding of 
- [ ] Performance impacts are reasonable (we should test impact)

**Comment by pjenviri** [comment]
SDK doesn't support sorting by a specific metric. We can't do it solely on UI.

**Comment by just-a-node** [comment]
We'll need to expose sort fields in the SDK. 

@alexwhte If we can be more specific on which columns exactly, that would be helpful. Would it just be all the fields we see in the connextscan results? 
<img width="1353" alt="image" src="https://github.com/connext/monorepo/assets/16638982/56061505-3d91-4432-9413-4f3a1e16db59">

For some of these, sort order needs to be defined (e.g. for `transferId`, what is the point of sorting it?).

**Comment by rhlsthrm** [comment]
Need @alexwhte comment here to address above.

**Comment by alexwhte** [comment]
@liu-zhipeng can you help size this? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclNRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08ba1dc87ef90a27d7173998aea2a7aa84d7a5d5/image.png)

**Comment by LayneHaber** [comment]
not ready for implementation / sizing as its not clear what types of filters we want. 

@alexwhte can you add more detail here? changing the issue to descope to have the targeted outcome as a spec instead of this feature

**Comment by LayneHaber** [comment]
likely to be part of a larger analytics update; not clear if there is user demand for this
