### ISSUE TITLE
Sequencer unable to execute

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4777]
**Describe the bug**
Sequencer should be able to execute without error.

**To Reproduce**
1. Go to '[...](https://app.datadoghq.com/logs?query=region%3Aus-west-1%20service%3Asequencer-subscriber&cols=host%2Cservice&event=AgAAAYm-7XLcdDpjEQAAAAAAAAAYAAAAAEFZbS03WE9CQUFCc3VTcHpJUkFSV0FBQQAAACQAAAAAMDE4OWJlZWQtNzYxYS00MjIxLThjYmUtODEwNTdlMWFmMjhl&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1669230253610&to_ts=1669231153610&live=true)'

2. 
<img width="1125" alt="image" src="https://github.com/connext/monorepo/assets/1195648/e5bb0288-879f-4d53-b299-a11d2a914400">

**Additional context**
Likely related to recent changes to gelato API

**Comment by sanchaymittal** [comment]
r4r: https://github.com/connext/monorepo/pull/4779
