### ISSUE TITLE
Problem with bump, very big value

### ISSUE THREAD

**Issue by doxe1** [connext/monorepo#4778]
**Describe the bug**
A user complained that the transaction was taking a long time. Slippage was at 0.1%, so it was suggested to increase it. And on the site we can see this message. Also, when setting 0.5% - it gives the error - Params invalid.

**Additional context**
Ticket - https://discord.com/channels/454734546869551114/1137032166258249869
taylorodette997 - user Discord ID
TX ID - https://connextscan.io/tx/0xd1a023bbeee2bb528a2841fbdb1547e7cbf15eeb8b4287b956e2e59d89e38ab3

![image](https://github.com/connext/monorepo/assets/84589100/93b1db86-0bc1-43e4-8877-661644c27aa2)
![image](https://github.com/connext/monorepo/assets/84589100/e58ecc1f-4f4a-4e16-982e-db0baf222473)

**Comment by ValerywArz** [comment]
One more: https://connextscan.io/tx/0xf8164b3ea83833a164fc85a47f63d07cb97d8e237685ea15310c4199fc33112d

**Comment by wanglonghong** [comment]
For the tx:"https://connextscan.io/tx/0xf8164b3ea83833a164fc85a47f63d07cb97d8e237685ea15310c4199fc33112d", it was kind of slippage issue. 

After he bumps the slippage, it worked.

"Params invalid" also shows when trying to bump the slippage with not a delegator.
We should also show the proper messages in that case.

**Comment by pjenviri** [comment]
@wanglonghong , we've customized the error message: https://github.com/CoinHippo-Labs/connext-bridge/commit/fd2332941a8df65920879e34d3a8e374ef05b9f5.

We use the same message shown in https://github.com/connext/monorepo/blob/main/packages/agents/sdk/src/sdkBase.ts#L462

**Comment by just-a-node** [comment]
@pjenviri Let's use `@connext/sdk-core` version `2.1.3-alpha.0`. It should resolve the odd calculations.

**Comment by just-a-node** [comment]
Fix for this is in `sdk-core` actually, we'll keep UI package separate for now: https://www.npmjs.com/package/@connext/sdk-core

PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/175

**Comment by pjenviri** [comment]
@just-a-node, here's the pr with preview for testing: https://github.com/CoinHippo-Labs/connext-bridge/pull/176

**Comment by LayneHaber** [comment]
update: actively testing
