### ISSUE TITLE
[watcher] Review new implementation ops

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#4781]
## Background

Review deployment + ops of new watcher implementation.

### Linked Issues & Documentation

- https://github.com/connext/watcher/tree/feat/upgrade

## Definition Of Done

Watcher deploys to testnet.

## Tasks

- [ ] Successful testnet deployment

**Comment by alexwhte** [comment]
Closing of duplicate of work @carlomazzaferro is doing already

**Comment by alexwhte** [comment]
https://github.com/connext/watcher-deploy/tree/main-v2
