### ISSUE TITLE
Volume not loading in the router TVL page

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4783]
https://connextscan.io/router/0xbe7bc00382a50a711d037eaecad799bb8805dfa8

<img width="1703" alt="image" src="https://github.com/connext/monorepo/assets/37959170/9767dc51-2aa7-4219-beb2-4a9161a75876">

{"code":"42703","details":null,"hint":null,"message":"column daily_transfer_metrics.router does not exist"}

**Comment by pjenviri** [comment]
Updated

**Comment by pjenviri** [comment]
The issue is fixed.
