### ISSUE TITLE
Router missed many transfers

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4784]
**Describe the bug**
In a recent load test, we found transfers stuck in `XCalled` status for over 4 hours after.

Example transfers:
```
                            transfer_id                             | origin_domain |   status   | error_status |      to_timestamp      
--------------------------------------------------------------------+---------------+------------+--------------+------------------------
 0x71baa058fe8f864025747ad71dc5013066d75b0aef99119e37067d4acf5d841c | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0x7b9a84806e29566a165d851ef97cc290c1ea28cc017379d9a9c0659c408aa4d1 | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0xf5d4fc4e8734ade09bccc71aa9d585267b712526acc141445dc572b06aef8a6d | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0xdbe273c5d113ebffd633e0d585edd6e0fcbb4ce9aac5abdbb79636a62d6a4c1b | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0xdbe7d07d4dd7f0682e92dca5843379163234765f11cc2b025b2e622d1356219e | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0xbccc0e27100789b8c303cafceb62c2a29a0bf751e60cae6d39499b94367b4277 | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0xfd4ab3a74063ebdbb2e8812bc1eac8e6fc9fb6d0f8a7db7024c317b46c6507a9 | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0x903cb2ad54ead9d3d0389a97a66eae633b6aee614133dd84608f63b4b4dab4c4 | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0x878085076ae9b4e5c021d9ead9bb37c376be10ef86d6487f64dbdb78b63188a4 | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00
 0xc9bcf77b2082b7f5c4bb0da630143cb5563476ea6bc3ab7bc57c623691f8ece2 | 9991          | 1735356532 |              | 2023-08-04 17:25:59+00

```

**To Reproduce**
1. Go to '[...](https://app.datadoghq.com/logs?query=region%3Aus-west-1%20%40requestContext.transferId%3A0xbccc0e27100789b8c303cafceb62c2a29a0bf751e60cae6d39499b94367b4277%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1691112872618&to_ts=1691199272618&live=true)'

**Additional context**
Router:

Here are how the logs for transfers are when it is included:
https://app.datadoghq.com/logs?query=region%3Aus-west-1%20service%3Arouter-publisher%20Published%20%40requestContext.transferId%3A0xe3967808c55f5f57bfcb5f9a0bcba2fcca28a84c5002861fa27ec7eaeaa5e9ce&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1691112872618&to_ts=1691199272618&live=true

Fast path:
https://app.datadoghq.com/logs?query=region%3Aus-west-1%20%40requestContext.transferId%3A0xe3967808c55f5f57bfcb5f9a0bcba2fcca28a84c5002861fa27ec7eaeaa5e9ce%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1691112872618&to_ts=1691199272618&live=true

Carto state:
```
 origin_domain |  error_status  | count |              now              
---------------+----------------+-------+-------------------------------
 1734439522    |                |  7528 | 2023-08-05 01:25:00.266229+00
 1735356532    |                |    10 | 2023-08-05 01:25:00.266229+00
 9991          | ExecutionError |     5 | 2023-08-05 01:25:00.266229+00
 9991          | NoBidsReceived |    19 | 2023-08-05 01:25:00.266229+00
 9991          |                | 20557 | 2023-08-05 01:25:00.266229+00
 ```

**Comment by sanchaymittal** [comment]
#4794

**Comment by rhlsthrm** [comment]
Found that this was caused by router throughput limitations. Parallelized loops to achieve higher throughput, latest test shows 6% missed by router.

**Comment by LayneHaber** [comment]
Running final load test today with all fixes incorporated

**Comment by alexwhte** [comment]
@preethamr please note next steps

**Comment by preethamr** [comment]
Next steps:

1. Add more instrumentation and repro, to help narrow down the cause, weather it is subgraph or chain conditions related, or query processing, concurrency, or load related.
2. Implement a poller that gets nonce gaps from DB, and cache.

**Comment by sanchaymittal** [comment]
final load test happen, and we nailed it!!
kudos @preethamr @wanglonghong @liu-zhipeng and every engineer!!
