### ISSUE TITLE
Ready airdrop server for PROD

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4790]
## Background

Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by rhlsthrm** [comment]
@sanchaymittal we need status updates and a description in the issue.

**Comment by sanchaymittal** [comment]
- we have feedback-based updates happening at server and db.

- hosting of prod server will happen in next couple of days
- and we have started with crunching data for load testing.

**Comment by sanchaymittal** [comment]
- pr is ready, we are going host the prod server today
