### ISSUE TITLE
[Bridge UI] Use multicall for RADAR <> xRADAR exchange

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4792]
## Problem
_What problem are we solving?_ 

We request 2 transactions right now from the user when sending RADAR, one for the `exchange` and one for the `xcall`. Should combine both.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_

Users who miss the 2nd transaction get stuck with xRADAR and would have to `exchange` it back manually or figure out how to `xcall` it manually.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by sanchaymittal** [comment]
-  we are moving forward with permit2, @just-a-node if you can share the latest update here.

**Comment by just-a-node** [comment]
PR sent to wonderland repo, Creed notified. Next step is to prepare UI-side PR to accommodate the permit2 flow.

**Comment by sanchaymittal** [comment]
Thanks for the update! @just-a-node can you add an estimate to this issue?

**Comment by sanchaymittal** [comment]
- pr is created, waiting for the audit from creed

**Comment by sanchaymittal** [comment]
- waiting for creed to response

**Comment by rhlsthrm** [comment]
Q about smart contract wallets that can't sign. Need to investigate the flow here.
