### ISSUE TITLE
Router should cover data gaps in subgraph pull

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4794]
**Describe the bug**
Routers can have gaps in certain (unknown conditions) that cause routers to never see an xcall.

**To Reproduce**
1. Go to '[...](https://discord.com/channels/992549151134982234/1136885438062272552/1138335976557649942)'

**Additional context**
Likely cause for gaps, ordering on query results is not guaranteed. Older records may show up later.

**Comment by rhlsthrm** [comment]
Durable retry logic:

Create a secondary poller loop that does the following:
For each configured domain:
- Grab `transferId`s from `originTransfers` in a chunk of 1000 nonces.
- Correlate each `transferId` to a `destinationTransfer` on the corresponding `destinationDomain`
- If `destinationTransfer` is null, add to retry cache.
- If all `originTransfers` in the chunk of 1000 have a matching `destinationTransfer`, save a cursor for `completedBatch` for the domain in the cache. Now we know we can move past that.
- Increment the starting nonce by 1000 and repeat.
- Once we get to the latest nonce, start again from the `completedBatch`.

**Comment by rhlsthrm** [comment]
Modifying algorithm to make simpler based on some assumptions:
- We only need to query transfers _more recent_ than the latest received aggregate root.
- Nonces are monotonically increasing for origin transfers.

Algorithm:
For each domain:
- Query latest received aggregate root.
- Query `originTransfers` by `nonce` at `blockNumber` > latest received aggregate root in a batch of 1000.
- Correlate each `transferId` to a `destinationTransfer` on the corresponding `destinationDomain`.
- If `destinationTransfer` is null, add to retry cache.
- Increment the starting nonce by 1000 and repeat.
- Once we get to the latest nonce, start again by querying the latest aggregate root.

Question: Do we need to track completed batches or is it fine to just query the whole epoch again (from latest received root)? Depends on how long it would take to get through the epoch.

**Comment by sanchaymittal** [comment]
QA done, looking good.
