### ISSUE TITLE
Slow path taking too long - (stuck on Transfer processing)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#4796]
**Describe the bug**
This txn is taking too long to reconcile (ARB to Mainnet)
https://connextscan.io/tx/0xee53331d943c529a602a72e40e36fb67626dcf6fa545065cf45339d8ece287df

<img width="1915" alt="image" src="https://github.com/connext/monorepo/assets/26097731/be67acf3-deeb-434c-89ea-afb2009a60b0">

**Additional context**
ticket on discord:
https://discord.com/channels/454734546869551114/1138524067624919171

**Comment by sanchaymittal** [comment]
within the time limit after decreasing the frequency of the slow path roots
