### ISSUE TITLE
Decentralized one not working during the hosted-service downtime

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4805]
**Describe the bug**
Getting `Invalid auth` issue from decentralized subgraphs.

**To Reproduce**
1. Go to [datadog](https://app.datadoghq.com/logs?query=%40requestContext.transferId%3A0x56a9ce61d2632498b481e18b31f769f59a8bb852627259b915f91b498511498b%20&cols=host%2Cservice&event=AgAAAYnzTvF7FQkr7AAAAAAAAAAYAAAAAEFZbnpUdlNWQUFET3pUZFhJczFpR0FBQQAAACQAAAAAMDE4OWYzNTUtODZiYy00MjUxLWEzMWEtYjc4YzgzYTM5MmFk&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1691917912606&to_ts=1692004312606&live=true)

2. We didn't have `Invalid auth` issue when we generate the graphclient without hosted-service endpoints.
But as soon as the hosted-service downtime starts, it shows `Invalid auth`.

**Additional context**

**Comment by rhlsthrm** [comment]
This was an issue on Graph's end.
