### ISSUE TITLE
Update bridge transfer message 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4807]
When submitting a transfer

![image](https://github.com/connext/monorepo/assets/37959170/35ce7145-1daa-445f-a650-a00ae9c34733)

Add this text:

Your funds will arrive at the destination in about 3m 20s
.
**💡 Connext plugs into the chain native bridges for optimal security and trust minimization. No oracles or external validator sets are used.**

If you close this window, your transaction will still be processed.

**Comment by pjenviri** [comment]
added the text.

**Comment by alexwhte** [comment]
mm not seing it [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFVHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c73274876a2d9711700b95a903979501705c5b9/image.png)

**Comment by pjenviri** [comment]
Did you refresh the UI before testing? It has been changed on my screen. 
![1.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/c52a11b2-179b-4d41-8b75-e457484374ab)

**Comment by alexwhte** [comment]
It looks too cluttered:

Please add a return space between these two lines, like so:
"Your funds will arrive at the destination in about

💡 Connext plugs into the chain native bridges for optimal security and trust minimization. No oracles or external validator sets are used."

And move this message out of the window into a tooltip on 'X' to close the window
"If you close this window, your transaction will still be processed."
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmVRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a55696c135c26de856d82ce9193234269aee53e7/image.png)

**Comment by alexwhte** [comment]
It looks too cluttered:

Please add a return space between these two lines, like so:
"Your funds will arrive at the destination in about

💡 Connext plugs into the chain native bridges for optimal security and trust minimization. No oracles or external validator sets are used."

And move this message out of the window into a tooltip on 'X' to close the window
"If you close this window, your transaction will still be processed."
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmVRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a55696c135c26de856d82ce9193234269aee53e7/image.png)
