### ISSUE TITLE
not showing balance correctly

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4809]
see swap UI nextWETH on binance

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGdHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--81f4c572b17c82399e1e6550ff4e50f5baba4cc1/image.png)

**Comment by just-a-node** [comment]
@pjenviri Seeing lots of rpc requests to ankr failing on cross-origin errors. Those ankr rpcs look down at the moment, can we switch to another public provider?

**Comment by pjenviri** [comment]
updated RPC endpoints: https://github.com/CoinHippo-Labs/connext-bridge/pull/177

**Comment by ed-ye** [comment]
When connected to BNB on the swap page, I get these rpc request errors:

<img width="526" alt="image" src="https://github.com/connext/monorepo/assets/101655136/65c4f340-7675-4c1e-bafe-5e63c057cfb4">

Why are requests being made to chains besides the current chain (BNB)?

Looks like SDK is correctly using browser/static rpcs but it should only be trying to request from the BNB rpc.

<img width="371" alt="image" src="https://github.com/connext/monorepo/assets/101655136/850f1408-02d2-4df2-8a4e-54455e4997d5">

**Comment by just-a-node** [comment]
When connected to BNB on the swap page, I get these rpc request errors:

<img width="526" alt="image" src="https://github.com/connext/monorepo/assets/101655136/65c4f340-7675-4c1e-bafe-5e63c057cfb4">

Why are requests being made to chains besides the current chain (BNB)?

Looks like SDK is correctly using browser/static rpcs but it should only be trying to request from the BNB rpc.

<img width="371" alt="image" src="https://github.com/connext/monorepo/assets/101655136/850f1408-02d2-4df2-8a4e-54455e4997d5">

**Comment by just-a-node** [comment]
Looks good now with the fix in https://github.com/CoinHippo-Labs/connext-bridge/commit/d462f00323eb405711ee739e2cbac4867fed9c01
