### ISSUE TITLE
Pending WETH transfers to OP Chain

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#4814]
**Additional context**
A few stuck transfers with Low amounts (lower supplied than liquidity):
1. https://connextscan.io/tx/0x2363d65c9d01b4cb6578ad96b32316cc05acb581ed1e0461cf7604c2297a65aa
2. https://connextscan.io/tx/0xcf9d4aa8d41919b586161026a2377868e6efa73ffa1cee449edfd76b501ef1cd
3. https://connextscan.io/tx/0xed49127d1a3d3a3fcd857a4c364fe71ff063107d399a3c5ca67e2f59e5724721

**Comment by just-a-node** [comment]
Low router liq in oETH across the board. These should go through slow path then.

**Comment by just-a-node** [comment]
Actually dokia is supplying enough but haven't facilitated a transfer in 4 months.

**Comment by LayneHaber** [comment]
resolved
