### ISSUE TITLE
Possible subgraph delays on Polygon

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4815]
**Describe the bug**
A 20 minute old transaction from Polygon to Gnosis Chain is not showing up in Connextscan https://polygonscan.com/tx/0xfacd645fca7263cd43366a6b23441e39473eac2d6f54c021f9bbc95f95e6ea03

**Additional context**
https://discord.com/channels/454734546869551114/1141811091580649592/1141811714820673669

**Comment by just-a-node** [comment]
Polygon subgraph was behind but it caught up and this txn has completed.
