### ISSUE TITLE
[UI] Slippage bump input has wrong decimals

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4816]
**Describe the bug**

**To Reproduce**
1. User submitted txn with low slippage: https://connextscan.io/tx/0xae17b199a8922c1177ce293f069871de14a2febc0a4026d9649a5de1e0a228e7
2. Tried to bump with slippage=300
3. `updateSlippage` is called with 300000000000000000000 instead: https://dashboard.tenderly.co/2d_eddie/project/simulator/d3032e01-58b3-47a3-86e4-e98d02a94f68/debugger?trace=0.0

**Additional context**

**Comment by pjenviri** [comment]
We don't pass 18 decimals. This is what we send [Uploading... Screenshot_2566-08-18_at_09.28.52.png]

**Comment by just-a-node** [comment]
Got it - actually stems from parsing in SDK.
