### ISSUE TITLE
Lowest LP Description UI bug

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4817]
**Describe the bug**
![image](https://github.com/connext/monorepo/assets/84744304/cfb6c836-9021-48d5-a535-6e848f7e6c36)
Should show <3000 if lowest lp description is not met

**Comment by LayneHaber** [comment]
https://github.com/connext/airdrop/pull/132/files

**Comment by alexwhte** [comment]
@LayneHaber can you also update this 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcElXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b279d8505c328c3cdac7f20737057e3d6a058d06/image.png)

To something like "Liquidity provided did not meet 30D threshold."
