### ISSUE TITLE
Sync from testnet prod to mainnet prod

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#4818]
## Background

Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by LayneHaber** [comment]
@sanchaymittal ya killing me with these default descriptions

what's going into the release?

**Comment by sanchaymittal** [comment]
noted @LayneHaber!

just created a placeholder to sync the latest updates we have from testnet prod to prod mainnet.
We will add a release note in PR.

**Comment by wanglonghong** [comment]
Linked a [PR](https://github.com/connext/monorepo/pull/4829) with the detailed description.
