### ISSUE TITLE
Setup slow-path processing agents

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4819]
## Tasks
For slowpath processing, we should run the following agents

- [ ] Cartographer 
- [ ] Lighthouse
- [ ] Relayer
- [ ] Sequencer
- [ ] Router

SHOULD be a part of [setup-integration-devnet-test.sh](https://github.com/connext/monorepo/blob/4708-protocol-backend-tasks-for-integration-test/setup-integration-devnet-test.sh)

**Comment by sanchaymittal** [comment]
- config slow-path agents

**Comment by rhlsthrm** [comment]
Config for devnet subgraphs.

**Comment by rhlsthrm** [comment]
Subgraph adapter needs some updates to work with devnet subgraphs.

**Comment by rhlsthrm** [comment]
Testing cartographer with devnet subgraphs.
