### ISSUE TITLE
P8 xToken whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4820]
## Background

Whitelist P8 tokens for xTokens

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/monorepo/pull/4751

**Comment by prathmeshkhandelwal1** [comment]
Added the review here, multiple changes required

**Comment by LayneHaber** [comment]
next step: add multisig transaction

**Comment by sanchaymittal** [comment]
- scheduling a call
- and creating mainnet action items

**Comment by prathmeshkhandelwal1** [comment]
- They wanna move token to polygon potentially we can convert it to xERC20
- They still have few unclear stuff on their end and we will follow with them up over next few calls to clear that out.
cc: @just-a-node

**Comment by rhlsthrm** [comment]
Closing since this is not really happening right now.
