### ISSUE TITLE
ForceUpdateSlippage issue in sdkBase

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4821]
**Describe the bug**
Wrong calculation in forceUpdateSlippage method of sdkBase

**To Reproduce**
1. Go to [sdkBase](https://github.com/connext/monorepo/blob/main/packages/agents/sdk/src/sdkBase.ts#L490)
2. `parseUnits` multiplies by 1e18 if there's no unit name
3. A user has a problem with the slippage bump here: https://discord.com/channels/454734546869551114/1141609769967300618/1142009500610600990

**Comment by LayneHaber** [comment]
expected release today

**Comment by just-a-node** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/176
