### ISSUE TITLE
Token filter not working on Explorer

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4824]
These should filter correclty based on the same config file mapping

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEFhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25f62dea5c2ffbd2295df03b9bb2e9734133c109/image.png)

**Comment by pjenviri** [comment]
The current functionality of the asset filter involves filtering the retrieved transfer data. The SDK supports on-the-fly filtering only based on `originDomain` and `destinationDomain`.
