### ISSUE TITLE
underlying network changed while user is trying to increase slippage

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#4827]
When user is trying to increase slippage on a stuck tx he gets an error "underlying network changed"
Changing of RPC doesn't help

https://connextscan.io/tx/0xb9d0ef66693334817082e7eedd0bd1c07987765c8f1880ac7d79a7b6902d831b

https://discord.com/channels/454734546869551114/1142216420306976939

**Comment by llandelzr** [comment]
hello

**Comment by sanchaymittal** [comment]
we pushed a fix during weekend, should work ideal now. Closing this issue, please open again if the issue persist.

**Comment by 0xanedi** [comment]
https://discord.com/channels/454734546869551114/941007434900721714/1152157010180190309 another case cam up today while bridging WXDAI from Gnosis to polygon DAI

**Comment by liu-zhipeng** [comment]
Already executed
