### ISSUE TITLE
Unable to create an account on the forum

### ISSUE THREAD

**Issue by doxe1** [connext/monorepo#4828]
**Describe the bug**
I wanted to create a forum account - https://forum.connext.network/. After registering and entering all the requested information, I received a message that an activation email had been sent to my e-mail, but alas, nothing had arrived. After checking every possible place, it was still unavailable. Then I went back to the site and pressed “Log In”. After entering all the details, I received the following notification (screenshot 1) that I need to activate my account. Clicking the button, I get an error and in the end, also nothing comes to the mail. 

I checked all the details and the email I entered. It's all correct.

**Additional context**
I tried from other browsers, alas the situation is the same.
Версия 116.0.5845.96 - version of the Chrome 

![image](https://github.com/connext/monorepo/assets/84589100/0506a898-8b32-4124-a5b2-2bda8ed2c1c8)

![image](https://github.com/connext/monorepo/assets/84589100/a62bd916-acc7-490b-a5a2-3a2d0adb9c4f)

**Comment by sanchaymittal** [comment]
@LayneHaber ^

**Comment by doxe1** [comment]
![image](https://github.com/connext/monorepo/assets/84589100/8e5e841f-2dda-4c99-86b0-01f76aac0519)

Here came 2 links, 4 hours ago, but alas when you click on them you get the following.

![image](https://github.com/connext/monorepo/assets/84589100/7a9f77d0-95c1-4762-ab7a-70ca1ce0c4ec)

**Comment by doxe1** [comment]
Anyway, I think the letter started to arrive, just with a big delay. Already verified the account.

**Comment by rhlsthrm** [comment]
This is working, confirmed by other users.
