### ISSUE TITLE
Geoblock sanctioned countries

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4831]
## Problem
Please geoblock these countries 
Cuba, Iran, Syria, North Korea, the Crimea Region of Ukraine, the Donetsk Region of Ukraine, and the Luhansk Region of Ukraine.

With the message "Sorry, Connext is not available in your region."

**Comment by pjenviri** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/180
