### ISSUE TITLE
Relayer Fee estimation is too high

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#4834]
**Describe the bug**
Arbitrum -> BSC relayer fee > 20 USDC

**Additional context**
https://connextscan.io/tx/0x3608c5fdb606a9f325f5882a1baa18458fb2b4ad9d871d3423ab81837687fda4

![image](https://github.com/connext/monorepo/assets/74738120/0325b2f6-9d47-4124-bdc4-2b04eb472f57)

**Comment by sanchaymittal** [comment]
Intermittent issue, trying to figure out the root cause for it:
- query the API overtime period and record the findings
- Check with gelato if they have a history of API responses or records of gas prices.
