### ISSUE TITLE
Limit ability to pay relayer fee in transacting asset to only major assets

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4835]
## Problem
Paying relayer fee in transacting asset should only be an option for the below, because other assets are too volatile 
- USDT
- USDC
- ETH

## Proposed Solution
If user is bridging an altcoin not in the above list, require payment in the native gas assets 
There should be a dynamic mapping file that we can update in the future if we add additional assets to thsi list ie major stablecoins

**Comment by pjenviri** [comment]
updated the config: https://github.com/CoinHippo-Labs/connext-bridge/commit/2c978b23dbe2c8ca9f060be2e3b48586d4d2e1f5.
