### ISSUE TITLE
Explorer took >90s to display

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4836]
**Describe the bug**
Cross-chain claiming flow we link the user to explorer 
https://testnet.connextscan.io/tx/0x6dd69cd8381b2e893db90a75859bdb7f59324b57f0708229122b14521015d7d5 

I saw a 404 error for an extremely long time. This delay is not really acceptable because we link the user immediately to Explorer to track their transfer. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFl2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2186fc8ce1b3fb5155555d3851ead1435db8fd13/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGN2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--616fc5d940066c070dbc542cd7e700b688e55987/image.png)

**Comment by pjenviri** [comment]
updated: https://github.com/CoinHippo-Labs/connextscan-ui/pull/86
