### ISSUE TITLE
Deploy to Sepolia

### ISSUE THREAD

**Issue by waynehoover** [connext/monorepo#4841]
## Problem
Contracts are not deployed on Sepolia.

## Impact
The [Goerli testnet is depricated](https://ethereum-magicians.org/t/proposal-predictable-ethereum-testnet-lifecycle/11575/17) and will not be supported at the end of 2023. 

Sepolia is the [recommended testnet by the Ethereum Foundation](https://ethereum.org/nb/developers/docs/networks/#which-testnet-should-i-use). 

## Acceptance Criteria
- [ ] Contracts are deployed on Sepolia

**Comment by just-a-node** [comment]
This'll be done and tracked in separate tasks.
