### ISSUE TITLE
Bridge UI changes for NEXT

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4859]
Tuesday, September 5th at 1pm UTC (8pm Thailand).  is the launch time for NEXT airdrop. We will naturally see a rush of activity on the bridge. 

## Proposed Solution
On the day of launch
- Add a banner above the Bridge UI "Today is the official launch of our NEXT token 🚀. Transfers may be delayed due to traffic from the airdrop."
- NEXT is visible in Explorer and all necessary Bridge UI modals
- Where the `origin_sender` is the Arbitrum Distributor, then in Explorer display a celebration emoji 🎉  to the left of the airdrop amount (100 in here). With a tooltip on the number and the emoji show "NOTE: Connext has added an additional token amount (5bps) to cover fast claiming fees for your airdrop!"
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFZpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98ef70a5283b0d12a3a5d4c9d463697c66c7f431/image.png)

example: https://testnet.connextscan.io/tx/0xe188edf415f6ff64c3b38f2825a2318130fc3d9946f02695bc36c0f1719f7b67 

Make the below change to enable NEXT bridging in a staging environment that we can turn on when ready. (vercel link?)

We will target making this available about 10-20mins after launch
- Bridging NEXT is available to chains Polygon, Arbitrum, Optimism, Gnosis, Mainnet 
- Bridging NEXT is NOT available to not BSC.  

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ]

**Comment by LayneHaber** [comment]
note: will leave comment when arbitrum production distributor is deployed and verified

**Comment by pjenviri** [comment]
PR:
- Bridge UI: https://github.com/CoinHippo-Labs/connext-bridge/pull/184
- Connextscan: https://github.com/CoinHippo-Labs/connextscan-ui/pull/89

**Comment by pjenviri** [comment]
@LayneHaber any update about the `arbitrum production distributor`?
