### ISSUE TITLE
Metamask/Socket impossible to bump slippage

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4860]
**Describe the bug**
A transaction made on Metamask (through socket) got stuck because of low slippage tolerance. The tolerance is not able to be adjusted by the user because (apparently) the delegate isn't set up correctly. Socket isn't able to help either.
https://connextscan.io/tx/0xe4035b82dd2b191376112dee5e15ba88565c6cdb7079929144f59ed616a0a143
https://socketscan.io/tx/0xa6cd83ed857f440731eb9e98277ff0bad6790fb977d03977b5ebd1c3bd56f851

Metamask and/or Socket should revise the parameters they use (both the default slippage and the delegate).

**Additional context**
https://discord.com/channels/454734546869551114/1146748200640856084/1146749192866377850

**Comment by Tommy-R8** [comment]
Another one stuck with the same issue https://connextscan.io/tx/0x922694abcc02159ab3e594ba4cec08a343d1480dd1a9b53081d8ef6121cb27be

**Comment by LayneHaber** [comment]
all linked transfers resolved

this was an issue with how the delegate is set, which should be fixed on both sides.
