### ISSUE TITLE
Swap page reversing assets

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4861]
**Describe the bug**
When trying to swap WETH to nextWETH on the BNB Pool, I select the asset, input the amount, and after a couple of seconds, the asset selection gets reversed automatically (nextWETH to WETH). Frustrating UX bug.

**Comment by liu-zhipeng** [comment]
I tested this issue on UI. but i can't find bug. maybe fixed. but need confirmation from coinhippo.

**Comment by pjenviri** [comment]
rolled out the fix: https://github.com/CoinHippo-Labs/connext-bridge/pull/199
