### ISSUE TITLE
Insufficient allowance while trying to Bridge NEXT

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#4868]
**Describe the bug**
![image](https://github.com/connext/monorepo/assets/74738120/3f5ee9d8-4620-4a46-9324-f3164951693c)

Not sure if the same also appears in different routes. Users notified us About Poly-Arb1 route.

**Additional context**
[Ticket](https://discord.com/channels/454734546869551114/1148847009512575017)

**Comment by prathmeshkhandelwal1** [comment]
Hey @oswy-cpu , Just checked with the connext bridge, seems working flawlessly, Can you try hard refreshing the UI.

https://bridge.connext.network/NEXT-from-polygon-to-arbitrum?symbol=NEXT

If the issue still persists, ping me here again.

Thanks.

**Comment by oswy-cpu** [comment]
Hey @prathmeshkhandelwal1. Seems the issue still persist for at least 2 users. We've tried hard refreshing and cookie/cache cleaning.

**Comment by prathmeshkhandelwal1** [comment]
That's really weird, Can you try approving through the smart contracts?

**Comment by prathmeshkhandelwal1** [comment]
https://polygonscan.com/address/0x58b9cB810A68a7f3e1E4f8Cb45D1B9B3c79705E8#writeProxyContract#F2

**Comment by prathmeshkhandelwal1** [comment]
Also can you send me your wallet address? 
For approving through smart contract, you need to add spender as connext smart contarcts. `0x11984dc4465481512eb5b777E44061C158CF2259`

**Comment by oswy-cpu** [comment]
Smth wrong with UI? I'll tell them approve manually. 

User Wallet: `0x0C3999eAF580B1B44f9Eff2aAe97411E8dcFC482`

**Comment by prathmeshkhandelwal1** [comment]
Tbh not able to find bug in UI, tried initing few txs without approval and its working fine for me.

**Comment by prathmeshkhandelwal1** [comment]
Is the SS attached to this issue has same wallet address you sent.

> Smth wrong with UI? I'll tell them approve manually.
> 
> User Wallet: `0x0C3999eAF580B1B44f9Eff2aAe97411E8dcFC482`

**Comment by prathmeshkhandelwal1** [comment]
<img width="394" alt="Screenshot 2023-09-06 at 4 22 39 PM" src="https://github.com/connext/monorepo/assets/56167998/64741132-cbe0-426c-bc6d-fb99b711a06d">
Because this user has already approved all the balance to connext contarcts.

**Comment by oswy-cpu** [comment]
> Tbh not able to find bug in UI, tried initing few txs without approval and its working fine for me.

Works for me too, I see their approval but still they can't initiate tx. I'll suggest them to try another browser tho

**Comment by prathmeshkhandelwal1** [comment]
Sure. 

> > Tbh not able to find bug in UI, tried initing few txs without approval and its working fine for me.
> 
> Works for me too, I see their approval but still they can't initiate tx. I'll suggest them to try another browser tho

**Comment by prathmeshkhandelwal1** [comment]
> Ok, it worked with manual approving. Another thing that seems to come up quite often ![image](https://user-images.githubusercontent.com/74738120/266005512-47b88163-9741-489c-a03f-9164c6c2a149.png)

For this, we can create a different issue.

Closing out this issue as resolved.
