### ISSUE TITLE
Stuck txn without error msg.

### ISSUE THREAD

**Issue by kubo-l** [connext/monorepo#4869]
**Describe the bug**
A transaction made an hour and a half ago from Gnosis to BNB Chain sending DAI that should have gone through the fast path because there is sufficient liquidity, is still processing and the UI does not give the option to Bump the transaction.

https://connextscan.io/tx/0x63c704ae3cdfd95b9d77bca0ecca919f588c18dd422628252413ce3a444b9c6f

**Additional context**
Another one stuck tx with the same potential problem:
Similar time, to the same chain.
https://connextscan.io/tx/0xeb5215c8b72a8f4cad7e8518e095cf622e6f172119df2e135aa43fc53c78cdc6

**Comment by liu-zhipeng** [comment]
Executed!
