### ISSUE TITLE
Do not show slippage for xERC20s

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4875]
## Problem
Slippage is not relevant to xERC20s

## Proposed Solution
when user is bridging an xERC20 i.e. NEXT

Rename estimated fees to Additional details

Additional details
```
Router Fee ___
Gas on Destination ___
Infinite approval
Estimated time
```

## Acceptance Criteria
- do the above
- Do this in a way that is easiest to update automatically over time, for example using the same config whenever we add assets and also are setting

**Comment by pjenviri** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/189

**Comment by alexwhte** [comment]
I'm still seeing the same

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWVRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e49cb00d189021120235389678ecdc706468496c/image.png)

**Comment by alexwhte** [comment]
fyi this is loading perpectually  next to additional details

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1NSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--879d96d7fb01a1109fb70e1089c618887a41d5df/image.png)

**Comment by pjenviri** [comment]
- Regarding to this [config](https://github.com/CoinHippo-Labs/connext-bridge/blob/main/config/mainnet/assets.json#L635-L676), I understand that it's not xERC20. (Sorry, I thought I posted it before changing the ticket status, but I didn't)
- Fixed the loading component always showing up. https://github.com/CoinHippo-Labs/connext-bridge/commit/e7673653d134c9b69594e71fdd81a79c3feb25fa

**Comment by pjenviri** [comment]
updated. pr: https://github.com/CoinHippo-Labs/connext-bridge/pull/201
