### ISSUE TITLE
RADAR Eth Mainnet handling 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4876]
## Background

Currently there is an edge case for xERC20s like RADAR where the Lockbox doesn't support Permit2 interactions. 

For example, when bridging from mainnet Ethereum you first need to confirm wrapping into xRADAR in your wallet, then approve xRADAR transfer, then xcall with xRADAR.

## Solution

When user clicks send of an ERC20 from a non-permit-lockbox chain (managed in config), then call this flow without Permit2:
1. Wrap 
2. Approve
3. Send

If user completes 1-Wrap but cancels before completing 3-Send, then they will be stuck with xRADAR so:
1. change RADAR in Sending asset section to xRADAR
2. Populate the xRADAR balance 
3. Populate a warning "Warning you did not complete your RADAR transfer so you have bridgeable xRADAR in your wallet. Please complete your transfer request."

If user enters the UI, when populating assets in the dropdown, only show xERC20 wrapped assets like xRADAR if a balance exists in their wallet. Always show RADAR.

**Comment by pjenviri** [comment]
@alexwhte, 

- We've updated the UI to show xRADAR, and this will populate the xRADAR balance when the user selects it (2)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0IrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be3af53b0e2e4f6c5755995785bec86a238dba91/ui.png)

- Additionally, instead of making users complete their xRADAR transfer, we thought it would be more flexible to let them decide whether they want to bridge xRADAR or unwrap the tokens to get RADAR tokens back. So, we added the 'Wrap/Unwrap UI' under the bridge section, and it will only show up when users pick a token in the lockbox chains. The preview link is in the PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/190. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0YrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d7152dadb510347c145f4e638c7745302a0d39d8/wrap-unwrap.png) 

- But when it comes to (3), we don't know how to differentiate the step. @just-a-node, would you mind helping us make this change? 

Suggestions are welcome.

**Comment by just-a-node** [comment]
Made changes to account for non-permit lockbox xERC20 flow. 

As for (3), we'll first get some feedback on how to handle this from DappRadar tomorrow. @pjenviri there are some inconsistencies with `callProcessing` states at the moment. We want to make sure the "pending" kind of state is shown whenever we're waiting between user transactions (approve, deposit, etc). Could you guys take a look into that?

**Comment by pjenviri** [comment]
@just-a-node updated to the PR:https://github.com/CoinHippo-Labs/connext-bridge/pull/190

**Comment by alexwhte** [comment]
**UX Updates**
1. Only show xRADAR in the asset selection dropdown when user's xRADAR balance is >0
2. Only show wrap/unwrap widget for xRADAR as the selected sending asset 
3. If user has RADAR selected AND they have >0 xRADAR balance, then show a warning:
"It looks like you did not complete a previous RADAR transfer, so you currently have bridgeable xRADAR in your wallet. Would you like to complete the transfer and/or revert back to RADAR?" 
Button: "Yes, switch to xRADAR"
If user selects Yes then switch the sending asset to xRADAR
4. If the user has xRADAR as the selected sending asset and their xRADAR balance is >0, then show a warning
"You have a xRADAR balance because a previous RADAR transfer must have failed. Please complete transferring xRADAR or unwrap back to RADAR below."

**Comment by alexwhte** [comment]
TBD: Step by step tracking of approvals in their wallet

**Comment by pjenviri** [comment]
Updated: https://github.com/CoinHippo-Labs/connext-bridge/pull/190 cc. @alexwhte

**Comment by alexwhte** [comment]
I'm sorry, I just updated the comment before seeing your update PJ

Please change #3 to a popup with the new text and actions provided
Please change #4 to a warning above the bridge with the new text provided

**Comment by pjenviri** [comment]
updated to the same PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/190. Please try.

**Comment by alexwhte** [comment]
@pjenviri can you adopt design like this? 

the popup is hard to read right now as it is the same color without a border, and the font sizes are wrong

https://www.figma.com/file/1QvGTQ69Pps2ZZ5InenPkk/Untitled?type=design&node-id=0%3A1&mode=design&t=vGTHLgWXmc0KorKD-1
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclN0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5d5ce079f5dad382ae70f3bd23ed8b53a024812/image.png)

**Comment by alexwhte** [comment]
Error: Crashing during the unwrap action 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWF1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--97f33615bbe4f34782e8945b61f413f79e1dac7c/image.png)

**Comment by just-a-node** [comment]
Related to Alex's error above:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGl2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c0859f359cf4b6c830a110dde503fec674841e6/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHF2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9efd1b2c2c706c204c36477377a233e0a286df62/image.png)

**Comment by just-a-node** [comment]
Hey @pjenviri, couple more things:
- I started this PR (https://github.com/CoinHippo-Labs/connext-bridge/pull/195) to add in steps for the user when they are sending an asset that requires lockbox interaction. Need your review and to see if there is a more elegant way to accomplish this.
- The button state is a bit finicky. It will sometimes go back to "Send" when you are in between transactions when it should be in the processing state during `await`s.

**Comment by pjenviri** [comment]
- updated modal style
- fixed error after unwrap
- updated tracking status following [pr #195](https://github.com/CoinHippo-Labs/connext-bridge/pull/195)

Please try it at: https://github.com/CoinHippo-Labs/connext-bridge/pull/190.

**Comment by alexwhte** [comment]
Please remove this text warning
> You have a xRADAR balance (bridgeable RADAR) in your wallet because a previous RADAR transfer was incomplete. Please complete the transfer of xRADAR or unwrap back to RADAR.
Instead put a warning in a separate pane below the bridge
"You have a pending balance as xRADAR in your wallet as a previou transfer did not complete. Please complete the transfer or switch back to radar here."
With a single button "Switch back" (same as the popup, which unwraps teh full balance) 

Whenever xRADAR balance is 0, it should switch the user back to RADAR and remove xRADAR from the selectable assets. Basically they should never see this screen
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaU8vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--94b525174b1a90e21190c4d95c55d55cf5817a83/image.png)

**Comment by pjenviri** [comment]
updated.

**Comment by alexwhte** [comment]
Please hide xERC20s before you connect your wallet 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbW5EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c34f2b2ae4eebf5f4a4df86ac7a3e3bead2da50c/image.png)

**Comment by pjenviri** [comment]
updated.

**Comment by pjenviri** [comment]
@alexwhte Should we merge this pr: https://github.com/CoinHippo-Labs/connext-bridge/pull/190 but disable RADAR?

**Comment by just-a-node** [comment]
@pjenviri Yes please merge and disable RADAR for now.

**Comment by pjenviri** [comment]
ok. merged.

**Comment by alexwhte** [comment]
waiting on multisig then we will get this live
