### ISSUE TITLE
(Scoping) Chain abstraction SDK not working with 1inch API anymore

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4879]
**Describe the bug**
Integrators are reporting that the chain abstraction SDK is no longer working.

**To Reproduce**
1. Try to use chain abstraction SDK to get quotes from 1inch.
2. 
3. 

**Additional context**

**Comment by alexwhte** [comment]
Need to scope out what it takes to fix and analyze cost

**Comment by sanchaymittal** [comment]
- 1inch public api has been deprecated.
- If we want to continue with 1inch we will need to use via 1inch dev portal(fyi: it's 1rps for basic account, so for sure pricy to use it.)
- mean finance is using the latest dev portal, https://github.com/Mean-Finance/sdk/blob/854f94f3f14273689c35357e21c1a6f83d57d57c/src/services/quotes/quote-sources/1inch-quote-source.ts#L6. 
- we can put config updates, so dapps can add there own 1inch API.

**Comment by rhlsthrm** [comment]
Yes we should allow them to add their own 1inch API as the quick fix.

**Comment by rhlsthrm** [comment]
Closing this to open a new task.
