### ISSUE TITLE
Add deployed contract addresses to docker config

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4882]
## Problem
After the HH deploy of contracts. The addresses of the contracts needs to be pushed to the agents.

Need this for op roots.

## Impact
Op roots.

## Proposed Solution
We have a part to parse/compose json in the bash script but it is so simple so the detailed plan is 
[ ] create a nodejs script to parse the deployments.json in nxtp-integration package
[ ] use the nodejs script in bash script like yarn workspace @connext/nxtp-integration genconfig --service router

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Config should allow deployed addresses to be specified.
- [ ]  Determine which contract addresses and fetch them
- [ ]  Generate the config.json for each of the agents that need these addresses
- [ ]  Router config updates correctly
- [ ]  Sequencer config updates correctly
- [ ]  Lighthouse config updates correctly

**Comment by LayneHaber** [comment]
update:

@wanglonghong + @preethamr working on this. next steps are to use scripts to update the config added into branch

need to make sure this will bring up proper agents, or get to next phase of debugging
