### ISSUE TITLE
Init new SDK with all the necessary helpers

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4888]
## Background

For the new Connext SDK, we need to clone all the necessary helpers and interfaces

## Definition Of Done

Clone all the helpers using new light weight libraries like viem and bundler like bun

**Comment by LayneHaber** [comment]
blocked by #4889

**Comment by prathmeshkhandelwal1** [comment]
- [ ] Minimise `txService` as a util in new SDK
- [ ] Clone helpers
- [ ] Migrate to viem
- [ ] Add tests using bun framework.
