### ISSUE TITLE
Create SDK-utils package using viem

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4889]
## Background

SDK uses `@connext/utils` which underlying uses ethers for doing the job. We need to create a light weight client package that SDK can use in place of `@connext/utils` using viem.

## Definition Of Done

Create a new SDK-utils package that has all the necessary utils function that SDK can use underlying using viem.

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by prathmeshkhandelwal1** [comment]
List of functions/types SDK is using from @connext/nxtp-utils

- ChainData
- ajv
- Types (Address, TLogLevel, TIntegerString, BaseRequestContext) 
- Logger
- createLoggingContext
- WETHABI
- StableSwapExchange
- formatUrl
- getAssetEntryFromChaindata
- getNtpTimeSeconds
- DEFAULT_ROUTER_FEE = 0.05
- jsonifyError
- getConversionRate
- domainToChainId
- chainIdToDomain
- getCanonicalHash
- XTransferStatus
- XTransferErrorStatus
- transfersCastForUrl
- NxtpError
- getGelatoEstimatedFee
- getHardcodedGasLimits
- getDecimalsForAsset
- calculateRelayerFee
- axiosGet
- MultisendTransaction
- encodeMultisendCall
- Chain plugins

**Comment by rhlsthrm** [comment]
New package working in Viem + Bun, need to test the rest of the functions.

**Comment by prathmeshkhandelwal1** [comment]
Test runner fixed.

**Comment by sanchaymittal** [comment]
Has been completed! ci/cd is under pipeline.

**Comment by LayneHaber** [comment]
steps to clear:

- [ ] check unit tests
- [ ] spin up the npm release
- [ ] setup CI
- [ ] release a beta version
- [ ] ready to test on coinhippo / bridge ui

**Comment by sanchaymittal** [comment]
@just-a-node Can we update the status of this task.

**Comment by rhlsthrm** [comment]
This is done.
