### ISSUE TITLE
Staging op roots not working

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4894]
**Describe the bug**
Functionality of op roots features merged into staging is not fully tested.
Op-roots features in staging should work.

**To Reproduce**
1. Try happy path op/non-op mode in staging

**Additional context**
There are gaps in data handling, and fixes needed to graph handlers to get this working.

**Comment by LayneHaber** [comment]
update: got past contract deployment issues; moving on to the next set of bugs

**Comment by sanchaymittal** [comment]
need an update from @preethamr here.

**Comment by LayneHaber** [comment]
still not working -- xcalls have been made but they are not showing up. 

we have completed the onchain setup (deployment, initializing, router liquidity, etc.). we know the slow path will not work yet, as there are known changes from merge. fast path is a higher priority.

**Comment by sanchaymittal** [comment]
- slow mode working, all the agents live
- optimistic mode is working.

**Comment by preethamr** [comment]
> * slow mode working, all the agents live
> * optimistic mode is working.

This is not the case, yet.

**Comment by preethamr** [comment]
Being tracked in detail here:
https://github.com/connext/monorepo/issues/4975
