### ISSUE TITLE
RADAR Mainnet whitelisting

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4895]
## Background

Any information that gives more context as to why this task exists, and why it matters. This might include: links to discussions, documentation, or other Jira issues / tasks

### Linked Issues & Documentation

https://github.com/CoinHippo-Labs/connextscan-ui/pull/94/files
https://github.com/CoinHippo-Labs/connext-bridge/pull/194/files
https://github.com/connext/chaindata/pull/95
https://github.com/connext/monorepo/pull/4892

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by LayneHaber** [comment]
waiting to be added as minter on bnb token

**Comment by sanchaymittal** [comment]
blocker is dappRadar action item.

**Comment by LayneHaber** [comment]
still waiting on mint permissions

**Comment by prathmeshkhandelwal1** [comment]
Tried Simulating Transactions. Working. Closing this out. @just-a-node
