### ISSUE TITLE
Create transfer and verify tester is working on happy path

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#4900]
## Problem
_What problem are we solving?_ 
We need to verify that a transfer works and is reconciled through slow path.

## Impact
_Why does this matter? Who does it impact? How much does it impact them? What is the urgency?_
Urgent to unblock tester.

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._
- Write simple test scenario to send a single transfer and check it works.
- Create new node script for single transfer.

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Transfer is boosted by router liq
- [ ] Transfer is reconciled and router is reimbursed

**Comment by LayneHaber** [comment]
update: in progress

**Comment by LayneHaber** [comment]
@wanglonghong can you add some clarity here on blockers?

**Comment by wanglonghong** [comment]
Next steps to do:

- [ ] Create 2 xcalls to receive local tokens on both spoke domains.
  [OnChain setup]
  - [ ] Call `xcallIntoLocal` on hub domain using sdk.
  - [ ] Send the root on hub domain to RootManager.
  - [ ] Propagate the aggregated root to spoke domains
  - [ ] Receive the aggregated root on both spoke domains on AdminSpokeConnector.
  [OffChain setup]
  - [ ] Run the cartographer-poller at a regular interval --- this is what we're currently missing from current setup
- [ ] Add router liquidity
- [ ] Create an xcall and make sure both path working.

**Comment by LayneHaber** [comment]
adding:

- [ ] documentation of local setup

**Comment by preethamr** [comment]
Updated documentation to latest, needs further updates once happy path works.

**Comment by rhlsthrm** [comment]
Created xcall with fast path!

**Comment by sanchaymittal** [comment]
fast path and slow path are working 🎉 🎉
