### ISSUE TITLE
ExecutionError in transaction with no possibility to bump

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4919]
**Describe the bug**
The transaction https://connextscan.io/tx/0x5eaefa56787a5b7c1b614ae814478a4442e399e54037e37828a6b277e8647a6d is stuck due to an ExecutionError. The UI shows a "click here to bump" message that doesn't have a hyperlink and can't be clicked 
![image](https://github.com/connext/monorepo/assets/84744304/e22329a6-7dc3-4094-8218-501ab27de970)

**Additional context**
https://discord.com/channels/454734546869551114/1153894701494186036/1153894836278149151

**Comment by preethamr** [comment]
Fails execution because of this error:

<img width="1199" alt="image" src="https://github.com/connext/monorepo/assets/1195648/cb331261-6b70-46f6-b393-7a4e43e1f4df">

**Comment by preethamr** [comment]
This was resolved by redeploying the subgraph.
