### ISSUE TITLE
alUSD fast path transfer error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4920]
**Describe the bug**
The site shows the fast path transfer for OP to ETH alUSD as being available. 
![image](https://github.com/connext/monorepo/assets/84744304/ba94f316-3d9d-44ed-9233-4ccdac6513aa)

However, in the explorer you can see that there's only 3 alUSD of active liquidity provided by our router on Ethereum. 
![image](https://github.com/connext/monorepo/assets/84744304/4d5e37e5-23b3-4c50-8132-16fcc1c11a65)

Also, in the Connext contract on mainnet there's like 400k of alUSD. Are these 400k alUSD just the backing of nextAlUSD on other chains? 
![image](https://github.com/connext/monorepo/assets/84744304/3fc800c3-8d4e-44b8-88ab-0afabd8699f7)

**Additional context**
https://discord.com/channels/454734546869551114/1153902225601597481/1153903608996302959

**Comment by pjenviri** [comment]
fixed. pr: https://github.com/CoinHippo-Labs/connext-bridge/pull/200

**Comment by alexwhte** [comment]
@Tommy-R8 can you please test and close out?
