### ISSUE TITLE
After the user increased the slippage, the transaction still did not go through!

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#4921]
After the user increased the slippage, the transaction still did not go through!

https://connextscan.io/tx/0xbecc0c933ce5bd16756595295772212312f75cf8166b1b2848e5bc7b9264ccda

DC link:https://discord.com/channels/454734546869551114/1153925615225937930/1153925619005001808

Bump link:https://www.bscscan.com/address/0x1A136a883CC6a4254F225Ca0a8bCCD8f2e4433bA

**Comment by liu-zhipeng** [comment]
Need to wait for a while after bump. anyway executed!
