### ISSUE TITLE
Failing to remove liquidity

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4932]
**Describe the bug**

https://cdn.discordapp.com/attachments/975758333757775953/1155145957462257664/image.png

**To Reproduce**
1. User tries to remove liquidity from their router (any asset)
2. Gets the error above

**Additional context**

**Comment by pjenviri** [comment]
It seems that the error in the captured image is an unrelated error. I'm not sure which dependency it's from, but it's not related to the execute reverted issue.

By the way, we've added the console log record: `[removeRouterLiquidityFor]` that contains the parameters passed when calling `removeRouterLiquidityFor`. @just-a-node Could you please take a look and confirm whether all the parameters are correct?

**Comment by sanchaymittal** [comment]
specific issue with one of the router, will follow up with them to debug more.
