### ISSUE TITLE
Search in explorer not working with text (for ENS)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4933]
**Describe the bug**
Search by ENS not working
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2JaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--808807e6802f4677b85f3b77a1f5e10754765e94/image.png)

**To Reproduce**
1. Go to https://connextscan.io/transfers
2. Start typing ENS (i tried 'alex' 'tommy' 'dokia')
3. See no results

**Additional context**

**Comment by pjenviri** [comment]
PR: https://github.com/CoinHippo-Labs/connextscan-ui/pull/99
