### ISSUE TITLE
Router owner should be able to remove router liquidity

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#4949]
**Describe the bug**

UI prevents router owner from removing router liquidity:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXp4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e0ffe0af80076d148314232fdb3a8e142d96e2a/image.png)

**To Reproduce**
1. Be a router owner
2. Try to remove router liquidity 
3. UI prevents router owner from doing so

**Additional context**

**Comment by pjenviri** [comment]
@just-a-node, where can we obtain information about the router owner? Currently, the UI only verifies the router address with the data available at https://postgrest.mainnet.connext.ninja/routers_with_balances.

**Comment by just-a-node** [comment]
@pjenviri Can you read `getRouterOwner` from the Connext contract for now? SDK has `getConnext(domainId)` method which will return the contract address for the domain.

**Comment by pjenviri** [comment]
Updated in this pr: https://github.com/CoinHippo-Labs/connextscan-ui/pull/101
