### ISSUE TITLE
Resolve zksync and zkevm subgraph issues on testnet

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4953]
**Describe the bug**

These subgraph providers/deployments are not functional:
- CONSENSYS-ZKEVM-TEST - 1668247156
- ZkSync - 2053862260

**To Reproduce**
1. Remove the workarounds introduced - https://github.com/connext/monorepo/commit/a88d024a880fa2131856f3ddd1a66fc255bb5870
https://github.com/connext/monorepo/commit/05a40544f83b820dd9136f72606e65de8ec8da8b 
https://github.com/connext/monorepo/commit/5a9824dea418a84623abbe72a0a3f8c451efc12f

**Additional context**
Redeploy working subgraphs, and reenable the chains.

Acceptance criteria:
- [ ] Restored commented code
- [ ] Restored `packages/adapters/subgraph/.graphclientrc.yml` in `testnet` and `staging`
- [ ] Redeployed subgraphs in both staging and testnet
- [ ] fast and slow paths for linea and zksync are working

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/5044
Fix linea subgraph ^^

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/5044
https://github.com/connext/monorepo/pull/5059

Linea goerli subgraph issue has been fixed by above 2 prs. 
Need to check Zksync subgraph again.
