### ISSUE TITLE
Fix Chain-abstraction UI. 

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#4957]
## Background

With the new changes of current chain-abstraction SDK, we need the reference UI to work, as its broken as of now. Add relevant readme for the UI as well. 

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by sanchaymittal** [comment]
- merge the pr is done
- release the version for sdk.
- testing of UI.

**Comment by sanchaymittal** [comment]
deployment is remaining
