### ISSUE TITLE
LH agents should work in OpMode V1 [Staging] 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4972]
## Summary
All LH agents should work in OpMode for all supported domains

## Acceptance Criteria
- [x] TODOs in LH `propose` task are addressed
- [x] Proposal task works
- [x] snapshot roots are propagated
- [x] aggregate root is propagated in ap-mode
- [ ] prover successfully submits proof in op-mode
- [ ] reconcile successfully completes in op-mode

**Comment by LayneHaber** [comment]
fix config: https://github.com/connext/monorepo/pull/4991 

not sure if this counts as points or this just supports this issue, but its a 1 pointer

**Comment by preethamr** [comment]
I got the propose LH task working.
I added our testnet gelato relayer as a proposer to staging  RootManager as a proposer.
And made successful proposal via LH:

https://github.com/connext/monorepo/pull/5011
r4r

**Comment by preethamr** [comment]
Except for https://github.com/connext/monorepo/issues/5029
V1 op mode is working.

**Comment by sanchaymittal** [comment]
done
