### ISSUE TITLE
[Test Plan] Test switch between op-mode and slow-mode 

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4974]
## Summary
Ensure the system moves from op-mode to slow-mode, and vice-versa, while continuing to process messages.

## Acceptance Criteria
- [x] System moves from op-mode to slow-mode while continuing to process messages
- [x] System moves from slow-mode to op-mode while continuing to process messages
- [x] No messages are left behind (all are processed) in any switch

**Comment by sanchaymittal** [comment]
nice work 🎉
