### ISSUE TITLE
[V1.1] Handle Aggregate Root Events

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4994]
## Problem
LH needs to handle changes to Aggregate Root Events to ensure off-chain data availability in all cases.

## Impact
Reduce cost and have reliable operation of the the system in V1.1 Op Mode

## Proposed Solution
Remove support for RootPropagated and OptimisticRootPropagated, instead using the AggregateRootPropagated (emitted in fast and slow cases) and AggregateRootSavedOptimistic (fast only) / AggregateRootSavedSlow (slow only) events

https://www.notion.so/Offchain-spec-for-OPT-roots-V1-1-0fdefbab648e426aabaa96b0eabe232e?pvs=4#aba565478a5b47a19333d069e1fc3dfa

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [x] RootPropagated and OptimisticRootPropagated subgraph, LH code paths, and Carto DB handlers are removed
- [x] AggregateRootPropagated event is added to subgraph, and ingested by Carto
- [x] Fast Path `AggregateRootSavedOptimistic ` event is added to subgraph, and ingested by Carto
- [x] Slow path `AggregateRootSavedSlow ` event is added to subgraph, and ingested by Carto
- [x] Subgraph client is updated
- [x] Subgraph handler is deployed
- [x] Unit tests for new functionality pass

**Comment by preethamr** [comment]
Added new subgraph handlers

**Comment by wanglonghong** [comment]
After complete [Deploy contracts to staging](https://github.com/connext/monorepo/issues/5032), I have updated ABIs in the `root_events` branch

**Comment by preethamr** [comment]
Pushed changes to `root_events` branch.

Next steps need local testing.

**Comment by wanglonghong** [comment]
Debugging both slotpath and fastpath. Fasthpath worked! Slowpath not working due to misconfigured RelayerProxyHubStaging.

It's currently being fixed.

**Comment by wanglonghong** [comment]
a couple of fixes here: https://github.com/connext/monorepo/pull/5055

**Comment by wanglonghong** [comment]
Added a handler for initial state before proposing.
Conversation: https://discord.com/channels/1140773690901004369/1149259142381441065/1166716824973479996
PR: https://github.com/connext/monorepo/pull/5056

Still debugging LH propose, propagate, prover and prover:sub.

**Comment by sanchaymittal** [comment]
completed 🎉
