### ISSUE TITLE
[V1.1] Update LH to support spoke in opmode

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4996]
## Problem
Add propose and finalize paths to LH for non-hub `SpokeConnectors`

## Impact
Reduce cost and have reliable operation of the the system in V1.1 Op Mode

## Proposed Solution
New code paths to support op mode from hub to spokes, when in op-mode

## Acceptance Criteria
- [x] LH Propose validates all spokes are in op-mode, when system is in op-mode, throws ERROR if not
- [x] LH Propose can `propose` on all valid non-hub `SpokeConnectors`
- [x] LH Propogate can `finalize` on all valid non-hub `SpokeConnectors`

**Comment by preethamr** [comment]
Pushed changes to `root_events` branch.

Next steps need local testing.

**Comment by wanglonghong** [comment]
- Updated the way to calculate the snapshotId from onchain call to offchain method.
- Made things clear between finalize and propagate in LH codebase.
- A couple of fixes done in LH propose + propagate codebase.

**Comment by wanglonghong** [comment]
The test of LH proveAndProcess is still remaining
