### ISSUE TITLE
[V1.1] Watcher runs V1.1

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#4997]
## Problem
Ensure Watcher runs V1.1

## Impact
Reduce cost and have reliable operation of the the system in V1.1 Op Mode

## Proposed Solution
Confirm with Defi Wonderland team that Watcher is running

## Acceptance Criteria
- [x] Defi Wonderland confirms successful operation of Watcher

**Comment by sanchaymittal** [comment]
@preethamr updates on this?
