### ISSUE TITLE
[V1.1] Merge V1.1 contract Pr to Staging

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#5030]
## Steps to do

- [x] Create a PR from [defi-wonderland:optimismtic-roots-1.1](https://github.com/defi-wonderland/connext-monorepo/tree/optimistic-roots-1.1) to the `staging` branch.

Draft PR is here: https://github.com/connext/monorepo/pull/4951
- [x] Resolve conflicts if needed
- [x] Merge!

**Comment by wanglonghong** [comment]
Merging the PR as of now.
