### ISSUE TITLE
[V1.1] Deploy contracts to staging

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5032]
## Problem
`staging` env currently has V1.1 draft contracts, they are not currently deployed on staging testnets.

## Impact
Accelerate V1.1 timeline, deploying these will help parallelize some of the V1.1 tasks

## Proposed Solution
Modify contract deployment scripts as need for the RootManger and Spoke connector upgrades needed by V1.1
Additional context
https://www.notion.so/Offchain-spec-for-OPT-roots-V1-1-0fdefbab648e426aabaa96b0eabe232e?pvs=4#5aafc736ffde457183e680118029a58a

## Acceptance Criteria
- [x] Deployment scripts are updated
- [x] Deployment is successful
- [ ] New relayerproxy contracts are funded on all supported chains
- [x] Subgraph deployment config is updated with new address and block numbers

**Comment by preethamr** [comment]
@liu-zhipeng @wanglonghong if you could start on this, that would allow us to go in parallel.

Note: We might have to redeploy, after we get the final contracts, but that will be a minor task since we do all the heavy lifting with this task.

**Comment by rhlsthrm** [comment]
Updating deployment scripts and deploying staging contracts.
