### ISSUE TITLE
Incorrect name for bridged USDC

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5043]
**Describe the bug**
On networks where native USDC is now offered, USDC should be shown as USDC.e on our UIs (bridge, pools, and explorer) because we still use bridged assets from Ethereum. This includes Polygon, Arbitrum, Optimism.

**Comment by Tommy-R8** [comment]
Arbitrum is fixed on the bridge UI, but not on the pools. Optimism isn't fixed yet.
![image](https://github.com/connext/monorepo/assets/84744304/b0f099fd-398c-48a4-ba0f-649e7f761b94)
![image](https://github.com/connext/monorepo/assets/84744304/fdcecfc2-55c6-482f-a447-04033ccd1e57)
![image](https://github.com/connext/monorepo/assets/84744304/bc2ace9d-d52c-4fef-9c73-eda828f68299)

**Comment by Tommy-R8** [comment]
This is still not fixed

**Comment by pjenviri** [comment]
Regarding the Pool UI, we use the name retrieved from `sdk.sdkPool.getPool`.

**Comment by just-a-node** [comment]
Ok, USDC in pools is fine - closing out.
