### ISSUE TITLE
Users can bridge on mainnnet Linea

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5052]
## Background
Task to complete and launch Linea to mainnet
https://www.notion.so/connext/Linea-GTM-Plan-4c514bf7d48d4bd7bec071a4306fc739

## Solution
See full checklist here 
https://www.notion.so/Linea-Tech-Checklist-97f4a9edc2d84c2ead9452af8826462b

## Acceptance Criteria
On Mainnet:
- [x] Able to bridge ETH to Linea slow path all paths
- [x] Able to bridge ETH to LInea fast path all paths
- [x] Able to bridge ETH out of Linea slow path  all paths
- [x] Able to bridge ETH out of LInea fast path all paths
- [x] Able to add pool liqudiity in pool UI
- [x] Able to add router liquidiuty in router UI

**Comment by sanchaymittal** [comment]
- lighthouse agent l1->l2 message isn't working, waiting for linea support.

**Comment by LayneHaber** [comment]
deployed 2 safes using [this cli tool](https://github.com/safe-global/safe-cli)

https://lineascan.build/tx/0x5ca78bcc538f7a0b31e813614377fef3bd9c399735f6432ae9e7723dc092e6c6
https://lineascan.build/tx/0xc9292fdd2e29b52cc2ad172f40d75b594e5cd62b65268b31ccfba1c05dd9fbb1

didn't update ownership there, but have kicked off the timers. there is a script (some fixes pending PR) that transfers ownership properly. that can be invoked with:

```sh
yarn workspace ownership --env "production" --network "mainnet"
```

**Comment by alexwhte** [comment]
Blocked by governance. ETA Oct 15 6pm CST

**Comment by liu-zhipeng** [comment]
https://connextscan.io/tx/0xc346f062195afb693c75df55bed40555ff700e7e53b38402062a092ec57242b4
Linea -> Mainnet slow path

**Comment by liu-zhipeng** [comment]
Completed!!
