### ISSUE TITLE
Create bridge adapter contract

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5053]
## Problem

Too many wallet confirmations when sending XERC20s.

## Impact

Decrease wallet confirmations from 4 to 2.

## Proposed Solution

https://www.notion.so/xERC20-Adapter-to-Simplify-UX-681481442d7f495db50609146133f5f3

## Acceptance Criteria

Adapter implemented as described in the above spec.

**Comment by sanchaymittal** [comment]
-  unit test in progress.

**Comment by prathmeshkhandelwal1** [comment]
- Adding fallbacks unregistered tokens(registry)

**Comment by prathmeshkhandelwal1** [comment]
- unit tests done
