### ISSUE TITLE
Arb to ETH alUSD: Execution Reverted 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5060]
**Describe the bug**
![image](https://github.com/connext/monorepo/assets/74738120/e9ebaff1-0532-4757-b53e-d62ee0b62cd6)

**Comment by oswy-cpu** [comment]
Cache/cookie, decimals isn't working

**Comment by oswy-cpu** [comment]
@just-a-node

**Comment by just-a-node** [comment]
Not enough nextAlUSD liquidity in the gateway. Checking with Alchemix team on whether the DAO will supply more.
