### ISSUE TITLE
Create multi-chain verification script

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5062]
## Background

In the xERC20 repo, the current forge deploy script doesn't pull in explorer keys configured in `.env` and so doesn't verify all newly deployed contracts.

## Tasks

- [ ] Create bash script that loops through all explorer keys defined in `.env` and runs `forge verify-contract` on the contracts in each chain's `broadcast/MultichainCreateXERC.sol/{chain_id}/run-latest.json`. This assumes the user has run the `yarn script:DeployXERC20:broadcast` already and finished deploying the token contracts.
- [ ] Document this in the readme

**Comment by prathmeshkhandelwal1** [comment]
- Not Required. (From wonderland's discussion).
