### ISSUE TITLE
Resolve Zksync subgraph issue on testnet

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#5064]
**Describe the bug**

These subgraph providers/deployments are not functional:
- ZkSync - 2053862260

**To Reproduce**
1. Remove the workarounds introduced - https://github.com/connext/monorepo/commit/a88d024a880fa2131856f3ddd1a66fc255bb5870
https://github.com/connext/monorepo/commit/05a40544f83b820dd9136f72606e65de8ec8da8b 
https://github.com/connext/monorepo/commit/5a9824dea418a84623abbe72a0a3f8c451efc12f

**Additional context**
Redeploy working subgraphs, and reenable the chains.
Linea subgraph issue has been fixed by 2 prs.
https://github.com/connext/monorepo/pull/5044
https://github.com/connext/monorepo/pull/5059

Acceptance criteria:
- [x] Restored commented code
- [x] Restored `packages/adapters/subgraph/.graphclientrc.yml` in `testnet` and `staging`
- [x] Redeployed subgraphs in both staging and testnet
- [x] fast and slow paths for zksync are working

**Comment by preethamr** [comment]
Done
