### ISSUE TITLE
[V1.1] LH Propose signs payloads

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5076]
## Problem

Currently Gelato relayer address is whitelisted as approved proposer by contract owner.
This is not at all a secure setup, as anybody can get a Gelato API key and propose successfully.
 

## Impact
V1.1 cannot ship without this issue resolved. Operating costs are impacted.

## Proposed Solution
https://discord.com/channels/992549151134982234/1135919510164091003/1167358360715280484
```
Currently the proposers are set with a whitelist on the proposing address. however this does not work well in a relayer context, since we dont know addresses beforehand of relayers. so what we need to do is:
whitelist RelayerProxy as a proposer
RelayerProxy contains logic to check signatures on payloads from our lighthouse's PK

then the flow becomes:
Gelato flow:
lighthouse generates payload with signature
call Gelato API endpoint
Gelato calls RelayerProxy which validates sig comes from lighthouse (dont trust Gelato!)
```

## Acceptance Criteria
- [x] LH Propose changes for hub `proposeAggregateRoot` with properly signed payload for `RelayerProxy` via Gelato
- [x] LH Propose changes for spoke `proposeAggregateRoot` with properly signed payload for `RelayerProxy` via Gelato
- [x] LH Propose changes are successfully deployed to `staging` env
- [ ] LH Propose successfully proposes to hub
- [ ] LH Propose successfully proposes to all spokes

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/5144

**Comment by sanchaymittal** [comment]
done, LFG!
