### ISSUE TITLE
Gnosis to Polygon transaction not found

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5083]
**Describe the bug**
This bridge tx https://gnosisscan.io/tx/0xff6e1ac9ddf2c0c7fe941fdf22e3959834276208b9d72bd820c8accdf6ce7952 from gnosis to polygon can't be found on Connextscan (https://connextscan.io/tx/0xff6e1ac9ddf2c0c7fe941fdf22e3959834276208b9d72bd820c8accdf6ce7952). The user also reported that the bridge UI showed that the funds arrived, but they didn't. Is the subgraph missing events?

**Additional context**
https://discord.com/channels/454734546869551114/1168289599760646215/1168291412106813540

**Comment by just-a-node** [comment]
Confirmed transaction is in subgraph and transferId should be this: https://connextscan.io/tx/0xabeba2455b25493f6d2eb743e74d6f3386bf6f5553b2ad374b641585f98dabbc

But it's not in the explorer, so checking why that is

**Comment by Tommy-R8** [comment]
Another transaction https://gnosisscan.io/tx/0x404ea8bbbf8cbf6c4058aff18244ee8d50ac3fd2a4433e23e2f928742cf0c7f5 https://discord.com/channels/454734546869551114/1168309300645593219/1168309595983314964

**Comment by MinistroDolar** [comment]
2 more txns (from gnosis to polygon)

Wallet Address : 0xCd223ff61b0f59983c2899D24314ed53f716fBF5
Transaction Hash : 0x54f7ba9924127fa48c42f3e5bb308858488e273e88eb8952fd693bf9c59b0f32

0x2f85ae42db88562e65e037ef0211f0db9628c2dffdc837f4436ad18cc0453e47

Ticket:

https://discord.com/channels/454734546869551114/1168321487296548947
