### ISSUE TITLE
LH propagate keeps exiting because of RPC issue

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#5085]
**Describe the bug**
LH propagate lambda function crashes because of rpc issue.

https://app.datadoghq.com/logs?query=service%3Alighthouse-propagate&cols=service&event=AgAAAYt-OECc5g91nwAAAAAAAAAYAAAAAEFZdC1PRUZvQUFBRFl0bG5BUUtpWWdBQQAAACQAAAAAMDE4YjdlMzktOWVjZi00ZDMwLWJhOTYtMGRiNGY2N2ZlNjE4&index=mainnet-production&messageDisplay=inline&refresh_mode=sliding&saved-view-id=1285114&stream_sort=desc&viz=stream&from_ts=1698613012621&to_ts=1698627412621&live=true

As soon as we see `504 Gateway Time-out` from https://eth.llamarpc.com, the lambda function exits.

![image](https://github.com/connext/monorepo/assets/30057497/876d6d3e-43d7-46eb-b227-51715c5b1581)

**To Reproduce**
1. Go to [datadog](https://app.datadoghq.com/logs?query=service%3Alighthouse-propagate&cols=service&event=AgAAAYt-OECc5g91nwAAAAAAAAAYAAAAAEFZdC1PRUZvQUFBRFl0bG5BUUtpWWdBQQAAACQAAAAAMDE4YjdlMzktOWVjZi00ZDMwLWJhOTYtMGRiNGY2N2ZlNjE4&index=mainnet-production&messageDisplay=inline&refresh_mode=sliding&saved-view-id=1285114&stream_sort=desc&viz=stream&from_ts=1698613012621&to_ts=1698627412621&live=true)

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/5120

Bad rpc is removed from prod.
