### ISSUE TITLE
Balance doesn't appear when choosing BNB Chain

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5104]
**Describe the bug**
<img width="416" alt="image" src="https://github.com/connext/monorepo/assets/26097731/11f8015b-59f1-4d44-8320-7300b5cb59cc">

![image](https://github.com/connext/monorepo/assets/26097731/8bd3a976-9a49-4871-8d8e-dbdb0b393306)

When trying to bridge tokens from BNB Chain the site does not recognize the balance in the wallet.
Reported by two different users, who have tried changing their RPC, but this did not fix the problem.
The problem was reproduced from my side, reaching the same result after trying other RPCs and performing a hard refresh.

**To Reproduce**
1. Go to https://bridge.connext.network/USDT-from-binance-to-ethereum?symbol=USDT
2. Select an asset you own in your wallet
3. Wait and see

**Additional context**
ticket: https://discord.com/channels/454734546869551114/1169456648365027439
And a user from Spanish Telegram.

**Comment by Tommy-R8** [comment]
Another user can't withdraw their balance from the LP (balance shown as 0) https://discord.com/channels/454734546869551114/1169860639297126450/1169861187492655154

**Comment by liu-zhipeng** [comment]
![image](https://github.com/connext/monorepo/assets/57480598/86035e0c-1207-47de-ab69-306bba4590a2)

**Comment by liu-zhipeng** [comment]
BSC rpc issue @pjenviri

**Comment by liu-zhipeng** [comment]
FIxed
