### ISSUE TITLE
[V1.1] Update LH to support proveAndProcess in both modes

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#5105]
## Summary
With v1.1 we are doing proveAndProcess for the aggregate root at the destination.

## Acceptance Criteria
-  [x] proveAndProcess works in optimistic mode at all spoke 
-  [x] proveAndProcess works in slow mode at all spoke

**Comment by preethamr** [comment]
Found proveAndProcess works in op-mode

**Comment by wanglonghong** [comment]
After a bunch of testing, I am closing the issue as completed
