### ISSUE TITLE
After Click Bump, the transaction still did not go through! Transactions take place on Gnosis

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5112]
**Describe the bug**
After Click Bump, the transaction still did not go through! Transactions take place on Gnosis

1、
DC:https://discordapp.com/channels/454734546869551114/1169611079895228446/1169611084311838790
TX:https://connextscan.io/tx/0xb5f882f205a13c9bd7acd26d70a6dc7c6e353f82e8cc8b2c9921a07e23d9e8c1
2、
DC:https://discordapp.com/channels/454734546869551114/1169607821961207860/1169607826612699136
TX:https://connextscan.io/tx/0x98e5a917113ea3dc62bc1a22038279ea97452a2f2606f7a504904f400e5813ae

**Comment by Tommy-R8** [comment]
Another one https://discord.com/channels/454734546869551114/1169637431448969246/1169637753877704784
