### ISSUE TITLE
Fuji withdrawal can't be found on explorer

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5128]
**Describe the bug**
A user withdrew their lending position from Fuji Finance from Optimism to Arbitrum. The withdrawal was successful but the WETH never arrived to Arbitrum. Trying to search the address and the tx hash results in nothing found on Connextscan. Fuji shows that the bridge from Optimism to Arbitrum had an error status.
![image](https://github.com/connext/monorepo/assets/84744304/3e81aef0-9aaf-4957-bc5f-b916496abca0)

https://optimistic.etherscan.io/tx/0x2fa89d8114e7a40ad6fd00831152d184859df89cc7cbc71333efe7269e524689

**Additional context**
https://discord.com/channels/454734546869551114/1171121919345573968/1171126407728992276

**Comment by Tommy-R8** [comment]
Update: It looks like the Optimism subgraph is behind ~10k blocks

**Comment by preethamr** [comment]
The transfer is searchable and completed sucessfully.
