### ISSUE TITLE
Fallback subgraphs stay buggin my g

### ISSUE THREAD

**Issue by LayneHaber** [connext/monorepo#5137]
**Describe the bug**
Subgraph fallbacks need to be more deeply investigated.

For example, optimism is 10K behind on hosted service and 6 blocks behind on Bware, but cartographer is stalled completely.

**To Reproduce**
Lack of ability to accurately reproduce this is why it's likely gone unfixed for so long. Probably going to need to create some mock classes? 

Not sure best route to reproduce without a subgraph being fully out of sync with existing utilities.

**Comment by LayneHaber** [comment]
Suggested improvement:

Should add max blocks it can fall behind before failover to backups so this doesn't happen again

**Comment by preethamr** [comment]
Fixed, in latest.
