### ISSUE TITLE
Memory leak at router agent

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#5140]
**Describe the bug**
memory leaks seem still to be happening. Service memory usage increases linearly, until it gets OOM'ed and killed. 

https://cdn.discordapp.com/attachments/994129054347317248/1171088482651881482/Screenshot_2023-11-06_at_15.06.54.png?ex=655b6824&is=6548f324&hm=c32ec12b414334104acee4688c08891967c72efe83dfc48bbc6f6d46bcf948c8&

> Initial debugging

If I were to place my bets anywhere it'd be on the polling interval being too short, resulting in having overlapping polling loops happening. At least, that's what the logs seem to indicate 
https://cdn.discordapp.com/attachments/994129054347317248/1171359238992445501/Screenshot_2023-11-07_at_09.02.30.png?ex=655c644d&is=6549ef4d&hm=9bf5ccc9c86ca95f501d78fa485f7a7f0f4f8e19e188cd37bad74bcb64c7eb37&

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by wanglonghong** [comment]
fixed
