### ISSUE TITLE
High relayer fee Optimism to Arbitrum

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5143]
**Describe the bug**
A user got a very high relayer fee on a USDC Optimism to Arbitrum transaction (55 USDC fee). The user says that the amount shown to be received was logical (4997 received when sending 5000). He also says that this happened twice before also on Amarok.
Transactions:
https://connextscan.io/tx/0xe669ced564e84e6e0ad9feef6070ca5b6c4c3101e958e8f350e84d46eaed9963 (55 USDC relayer fee)
https://connextscan.io/tx/0x36150dad51299987806f7fef01fbb0a25860c2d4eedfe2e4ac6f62a5710f91f8 (17 USDC relayer fee)
The user noted that both transactions have Optimism as the origin chain.

**Additional context**
https://discord.com/channels/454734546869551114/1171878046253465610/1171878493882159176

**Comment by preethamr** [comment]
With help from @just-a-node, the best explanation for these high fees:

- There was a change in the gas estimate, from when the UI displayed estimate, and when the user submitted

- This is possible if UI state variables get updated without displaying on the page, as we likely don't continuously query for estimates until there is a manual re-load
- There might have been a gas spike at these times, which caused the displayed and submitted (calldata) to differ
- The user would get an additional notification from the wallet, about the gas, when paying for gas on destination, in transacting asset, but not in this case

@nrsirapop Could you take a look at this from CH side, if that is correct, and what we can do about it ?

**Comment by pjenviri** [comment]
Yes. The UI submits the value displayed: [https://github.com/CoinHippo-Labs/connext-bridge/blob/main/components/bridge/index.js#L2371](https://github.com/CoinHippo-Labs/connext-bridge/blob/main/components/bridge/index.js#L2371).

Gas spikes can occur at any time, and users can submit transactions whenever they choose. We believe that implementing a minGasPrice for L2 chains would help mitigate this issue.

**Comment by LayneHaber** [comment]
> Yes. The UI submits the value displayed: https://github.com/CoinHippo-Labs/connext-bridge/blob/main/components/bridge/index.js#L2371.

To confirm, the relayer fee submitted is exactly what is displayed in the UI?

> Gas spikes can occur at any time, and users can submit transactions whenever they choose. We believe that implementing a `minGasPrice` for L2 chains would help mitigate this issue.

Do you mean `minGasPrice` or `maxGasPrice`? Why would a `minGasPrice` protect against spikes?
