### ISSUE TITLE
Relayer proxy fixes

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5147]
**Describe the bug**
A few of the relayer proxy changes were missed

**Additional context**
These changes are needed:

- `rootManger`.`sendRootToHubSpoke` to be wrapped in `RelayerProxyHub.sol`
- `onlyRelayer` checks need to removed from `finalize`
- Update unit tests as needed
- Redeploy to changed contracts to `staging`

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/5149
