### ISSUE TITLE
SDK changes to support adapter

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5154]
## Background

SDK needs to check whether input asset in `xcall` is registered as an xERC20 and has a lockbox setup. If it does, then call the adapter to perform the lockbox `deposit` + `xcall`.

**Comment by just-a-node** [comment]
Next steps:
- [ ] Deploy adapters to all other chains
- [ ] Deploy registry to all other chains
- [ ] Register alll current assets to all registries

**Comment by prathmeshkhandelwal1** [comment]
-  Features has been added to SDK, Only needs to add config for `adapter` and `registry`, Once we register all the xTokens there
