### ISSUE TITLE
Invalid SSL Certificate on connext.network

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5155]
**Describe the bug**
When trying to enter the connext.network site, some users get this error:
![image](https://github.com/connext/monorepo/assets/84744304/9087e626-d9d9-4fb1-80a9-04242628ed39)
It seems to happen randomly and it acts differently if the user tries to access the site directly from the url or from a link.

**Additional context**
Conversation with a video demonstration here:
https://discord.com/channels/454734546869551114/1173009437192093696/1173011526685315072

**Comment by preethamr** [comment]
Resolved
