### ISSUE TITLE
UI changes to support adapter 

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5163]
## Background

UI should use new SDK function that checks whether an asset is xERC20 and perform the necessary calls.

**Comment by prathmeshkhandelwal1** [comment]
UI changes has been done and pushed to `adapter-xcall` branch in connext-bridge repo. https://github.com/CoinHippo-Labs/connext-bridge/tree/adapter-xcall
Once we release new SDK we just need to update SDK version in UI.

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/272
