### ISSUE TITLE
ALUSD Stuck txn

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5167]
**Describe the bug**
A user tried to bridge nextalusd from arbitrum to ALUSD on optimism.

https://connextscan.io/tx/0x500c8d4b7c05c91d84f96da31f07f9ec4f28330a9f86d3c710cb66953f585fc9

![image](https://github.com/connext/monorepo/assets/26097731/1cd128a8-a6f2-4e69-a8c7-2d308d1fcecb)

Txn is stuck since more than 2 hours despite the fact im seeing fast liquidity on bware labs router:

https://connextscan.io/router/0x8cb19ce8eedf740389d428879a876a3b030b9170

![image](https://github.com/connext/monorepo/assets/26097731/94bc6c66-be7d-4bf2-9b9a-5abb27916684)

And bridge seems to recognize it when i simulate the txn.

![image](https://github.com/connext/monorepo/assets/26097731/3dc19005-8ab4-400c-9750-6eb2e6ac04dc)

**Additional context**

Ticket: https://discord.com/channels/454734546869551114/1173927118971875378

**Comment by Tommy-R8** [comment]
The transaction is also asking for a ridiculously high fee bump 
![image](https://github.com/connext/monorepo/assets/84744304/45d554e4-89cc-434f-9e67-5cf09ea30784)

**Comment by MinistroDolar** [comment]
Now txn was completed but user received nextalUSD instead of alUSD.

I think that the lockbox is out of funds. Btw the implementation seems weird, if the lockbox doesn't have funds the txn shouldn't finish until you can provide the canonical version to the user. Or, at least give them the chance to unwrap it when lockbox have funds again. (Like the unwrap for WETH through dexes)

I also think that we MUST find a way to automate the availability of funds in the lockbox. 
Asking Alchemix team to deposit funds in the contract feels like v1 router issues or relayers going out of funds.

![image](https://github.com/connext/monorepo/assets/26097731/a73d7faf-e4f8-414f-9b5a-f0efef0a8fc1)
