### ISSUE TITLE
Max amount router withdraw doesn't use correct amount

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5179]
**Describe the bug**

We got a report that clicking the "max" amount button when withdrawing router liquidity populates the amount with more than the balance. When decreasing this amount, it works. This doesn't happen all the time so we need to investigate.

**To Reproduce**
1. Go to some router as the owner
2. Click "max" in withdraw window
3. Get "cannot estimate gas" error

**Additional context**

**Comment by pjenviri** [comment]
The UI is getting the balance from `getRoutersData`: https://github.com/CoinHippo-Labs/connextscan-ui/blob/main/layout/index.js#L268
