### ISSUE TITLE
xERC20 loaded in selected asset when ERC20 selected

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5180]
## Issue

For xERC20 assets that have an ERC20, the xERC20 is being loaded as the asset when the ERC20 is selected from the dropdown.

Steps:

1. Go to bridge UI
2. Select RADAR
3. See that xRADAR is loaded

**Comment by pjenviri** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/238
