### ISSUE TITLE
[ST] Reconcile Failures

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5193]
**Describe the bug**
linea subgraphs are down and i think its causing problems with reconciling other messages, seeing a lot of these:

 https://app.datadoghq.com/logs?query=service%3A(lighthouse-prover%20OR%20lighthouse-process-from-root%20OR%20lighthouse-propagate%20OR%20lighthouse-sendoutboundroot)&cols=container_name&event=AgAAAYvasxuUfg7POgAAAAAAAAAYAAAAAEFZdmFzeDA0QUFCVWdNc0ZzWnBpU3dBYgAAACQAAAAAMDE4YmRhYjMtNGIxYi00ZWMxLWJmZDgtNjM3YmQ5MTM2OTM1&index=mainnet-production&messageDisplay=inline&refresh_mode=sliding&saved-view-id=1288966&stream_sort=desc&viz=stream&from_ts=1700177894563&to_ts=1700181494563&live=true

**Screenshots**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff904a17827ff27c27c3060f2e05d0ca709f9f71/image.png)

https://discord.com/channels/992549151134982234/1105163410615828480/1174864342089478164

**Additional context**
@oncall

**Comment by LayneHaber** [comment]
checked both subgraphs in chaindata, neither are working for linea

one has no record of deployment, and the other has an indexing error

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/5194
^^ this pr fixed linea subgraph issue and reconcile issue as well
