### ISSUE TITLE
[ST] USDT transfer stuck

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5202]
**Describe the bug**

This transfer has been stuck for >6 hours:

https://connextscan.io/tx/0x4b9e81508f92fa0a1cb392c310d5ebd5623cca1ccae3574050b422750eabd1a5

**Screenshots**

**Additional context**
@oncall

From Kinetex chat: "This transaction is a part of the transfer in our aggregation service, and our user is very confused about this situation, so we need at least understanding, how long it will take to resolve the issue. 

Besides can you also provide info how can we mitigate this kind of issue in the future and how we can prevent launching slow path?"

**Comment by LayneHaber** [comment]
Checking this out

**Comment by LayneHaber** [comment]
Resolved
