### ISSUE TITLE
[ST] Connext doesn't appear as a route in Jumper aggregator

### ISSUE THREAD

**Issue by maxlomu** [connext/monorepo#5203]
**Describe the bug**

When trying to bridge on https://jumper.exchange/ (Li.Fi) with a destination swap on Gnosis.
Noticed Connext didn't appear.

Tried with other routes and no destination swap. Connext never appears.

**Comment by alexwhte** [comment]
![image](https://github.com/connext/monorepo/assets/37959170/834a1fe1-f6d8-4603-b2ff-3e92136ae537)

stopped the 15th. Pinged lifi

**Comment by Tommy-R8** [comment]
Consider closing this one then: https://github.com/connext/monorepo/issues/5201

**Comment by preethamr** [comment]
@alexwhte is this still an open issue ?

**Comment by preethamr** [comment]
Not an issue anymore
