### ISSUE TITLE
[ST] Gnosis bumping issues 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5207]
## Background

Yubai reported issues with this 

Nacho, [Nov 21, 2023 at 6:00:41 AM]:
had to bump 3 times i think, now it is ok

Arjun | Connext (OOO until Nov 6th), [Nov 21, 2023 at 6:00:43 AM]:
Can you link the tx?

How long did you wait between bumps?

Nacho, [Nov 21, 2023 at 6:01:55 AM]:
4 minutes >

the first one, the other ones 20 secs, but because  that error appeared and i could bump manually again

is this something that could happen to our users too ?

there were several txs, you can check the history here https://gnosis.blockscout.com/address/0x245Bd6B5D8f494df8256Ae44737A1e5D59769aB4

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXoxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a3af3774007c9c874cd0c6bbd8fead5a1152e16/telegram-cloud-photo-size-1-5109628167651437639-y.jpg)

**Comment by preethamr** [comment]
While we have other relayer fee issue with Gnosis, https://github.com/connext/monorepo/issues/5361
This one has not been seen recently and the mentioned issues are closed.
