### ISSUE TITLE
[ST] Bridging nextAssets to Ethereum should not show slippage

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5208]
**Describe the bug**
Bridging nextAssets to Ethereum does not incur slippage. 

This does not incur any slippage and so should not show the below in UI
- slippage %
- minimum received after slippage

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3IyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9c04bd02418954beb2c96828eeca89be5658714/image.png)

**Comment by pjenviri** [comment]
We're waiting for the greenlight to merge the pr : https://discord.com/channels/992549151134982234/994389387834032198/1175615674740125746.

**Comment by pjenviri** [comment]
Since there hasn't been any comment/request change on this for a few days, let me go ahead and merge the [pr](https://github.com/CoinHippo-Labs/connext-bridge/pull/239).

**Comment by just-a-node** [comment]
Thanks, lgtm!
