### ISSUE TITLE
[ST] LI.FI txns getting stuck

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5211]
**Describe the bug**
Im seeing a lot of txns coming from LI.FI getting stuck with execution errors.

https://connextscan.io/tx/0x1415bd16314f673388647bd6f67c9fcdb0e1261db19f3bdb9314d1fa5396bfc5

https://connextscan.io/tx/0x08cdfc7ccbc9dfe0b8d62e9a4ba3fe04ff18fc5a562a90f9771c88053cb2ed98

https://connextscan.io/tx/0x48f8ae4ab0121be7b6ad593037821fe6215f070a19c4d4e3bf828a7801a59e22

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1176789612211998780

https://discord.com/channels/454734546869551114/1176803643278774312

https://discord.com/channels/454734546869551114/1176825158577704990

https://discord.com/channels/454734546869551114/1176837062423494737

**To Reproduce**
1. Go to connextscan.io
2. Click on transfers
3. Filter them by execution error

**Screenshots**

![image](https://github.com/connext/monorepo/assets/26097731/4e07db82-63fa-4efb-bc1e-8df5a12b0364)

![image](https://github.com/connext/monorepo/assets/26097731/ff0749c8-72ea-4da1-9ad6-5a0ecdb5f57a)

![image](https://github.com/connext/monorepo/assets/26097731/5acdb947-4fd5-4c87-82bf-7ea085f71ca1)

![image](https://github.com/connext/monorepo/assets/26097731/abeb0f35-ccbd-4082-b428-748d637a5e4c)

![image](https://github.com/connext/monorepo/assets/26097731/aace2d2d-943e-45e8-94d3-ae43fbaf6d53)

**Additional context**

@oncall

**Comment by Tommy-R8** [comment]
https://connextscan.io/tx/0xfe970088d3a9c50e147c68599ea24a20d21bcbd974ea887c715982ab6fbf138c
https://discord.com/channels/454734546869551114/1176837062423494737/1176837474383822930

https://connextscan.io/tx/0xee12fd3b4702bf9e581dc98a9f34b5463bb820b1ab57b321a595936881c2c5dd
https://discord.com/channels/454734546869551114/1176892267210997782/1176892799988273234

https://connextscan.io/tx/0x044196883e26349b9b0140dfaf083dc9caaa76c1499a7124d00fd640bd07f68d
https://discord.com/channels/454734546869551114/1176914086798299219/1176914827701145610

**Comment by Tommy-R8** [comment]
https://connextscan.io/tx/0x81cf6e43cea8adbfe8f07f55d6205171707839ec2e9d1b0d5a16263101c0d0b2
https://discord.com/channels/454734546869551114/1176934778793103530/1176935125007732798

**Comment by LayneHaber** [comment]
lifi disabled routes, pools have been initialized to support execution in adopted assets.

need to seed the pools with enough liquidity to ensure these clear, or users can opt to accept the next assets and swap later

**Comment by MinistroDolar** [comment]
> lifi disabled routes, pools have been initialized to support execution in adopted assets.
> 
> 
> 
> need to seed the pools with enough liquidity to ensure these clear, or users can opt to accept the next assets and swap later

Users now gets the low slippage error msg instead of execution error

They now are trying to bump the slippage of the txns without success.


![image](https://github.com/connext/monorepo/assets/26097731/b3671233-5620-4187-8428-f4738a4413fe)

https://discord.com/channels/454734546869551114/1177173289005756416

https://discord.com/channels/454734546869551114/1176837062423494737

**Comment by LayneHaber** [comment]
transfers should be cleared, users can check the explorer for any remaining action items. closing this out
