### ISSUE TITLE
[ST] <ExecutionError，Can't click Bump>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5212]
**Describe the bug**
The user's transaction has an ExecutionError error, but I can't do anything on Connext Scan, including clicking Bump

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1176892267210997782/1176892271040401429

**Screenshots**
![Uploading cab142ef0d2c4890fadb634df15d636.png…]()

@oncall

**Comment by LayneHaber** [comment]
link to screenshot not working

**Comment by Tommy-R8** [comment]
Duplicate of https://github.com/connext/monorepo/issues/5211
