### ISSUE TITLE
[ST] <UI BUG: Wrong estimated time>

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5216]
**Describe the bug**
When trying to bridge 800k $NEXT from ARB to MAINNET or 6M $NEXT from ARB to GNO as example, UI shows that it will be completed in less than 4 minutes although there aren't enough router liquidity to support fast path with those amounts.

Btw, why mainnet has only 60k $NEXT in router liquidity? Can we do something about this?

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1177572564621598842

**To Reproduce**
1. Go to bridge.connext.network
2. Select $NEXT as asset and ARB to GNO as desired chains, putting 6m to the amount 
3. Check estimated time (under 4 minutes)

**Screenshots**

![image](https://github.com/connext/monorepo/assets/26097731/5775b169-7985-4e2e-a751-83e6734e047f)

![image](https://github.com/connext/monorepo/assets/26097731/3d16f390-a897-465c-9501-69ba319262dd)

![image](https://github.com/connext/monorepo/assets/26097731/a5571e1a-e7fb-4a7b-8f01-1c713cc51f8a)

![image](https://github.com/connext/monorepo/assets/26097731/7feb848d-88a1-4482-a197-c42eb2fa460e)

**Additional context**
Seems that it only happens with $NEXT since ive tested USDT and XOC and it works fine.
@oncall

**Comment by preethamr** [comment]
It no longer shows fast path for Arb -> Mainnet.
![image](https://github.com/connext/monorepo/assets/1195648/3ac5de51-b37c-4dab-87db-1ff15ecc39cc)

Though, now there is the opposite issue it suggests ever `0.001` NEXT will not be fast pathed.

**Comment by preethamr** [comment]
ARB -> Gnosis looks good now, tracking liquidity on destination:
![image](https://github.com/connext/monorepo/assets/1195648/58710657-5a56-478d-86c6-938b406661f7)
Fast upto 3900000
![image](https://github.com/connext/monorepo/assets/1195648/2838dad2-8a07-41b2-9f04-08fb063cc7b8)
Slow for 4000000
![image](https://github.com/connext/monorepo/assets/1195648/88575abd-54a3-4f1a-b4a3-9471841fa14e)

**Comment by preethamr** [comment]
@MinistroDolar Please close this, if this looks resolved on your end too.

We should track this issue separately - `Btw, why mainnet has only 60k $NEXT in router liquidity? Can we do something about this?

`
