### ISSUE TITLE
[ST] <Stuck txn - $NEXT from Arb to Mainnet>

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5217]
**Describe the bug**
An user is having issues with his txn coming from Arbitrum to Ethereum Mainnet. 80k $NEXT, more than 6 hours without getting a reconcile. No error msg.

https://connextscan.io/tx/0xf51addc9664bb1bdbec6f3d43c85d40027dc860f7ac8aa4a36c36c27712af64f

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1177572564621598842

**Screenshots**

![image](https://github.com/connext/monorepo/assets/26097731/dbe01d34-d0e3-490a-bca1-2a03664b1ce1)

@oncall

**Comment by prathmeshkhandelwal1** [comment]
Resolved!

**Comment by MinistroDolar** [comment]
> Resolved! 

Thanks!!
