### ISSUE TITLE
[ST] NEXT Arbitrum to Ethereum transaction taking longer than 6 hours

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5218]
**Describe the bug**
A user started a bridge transaction sending 168k NEXT from Arbitrum to Ethereum and it's still pending after 6.5 hours. https://connextscan.io/tx/0x451315f6dcb595b2abc8bbfe6d0e88750ee1ca6be10dfc07f4fca9d59f42721d

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1178117601407291455/1178117940596449320

**Comment by LayneHaber** [comment]
Will be able to check this out in an hour or two

**Comment by wanglonghong** [comment]
completed. 

Just fyi, arbitrum amb is a little bit slower than others.
