### ISSUE TITLE
[ST] User added liquidity to Connext router

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5219]
**Describe the bug**
A random user deposited NEXT liquidity on our router (Connext router) on Arbitrum, and was expecting to be able to withdraw it (thought it was the same as just LPing). We need to remove this liquidity and send it back. Also possibly consider adding safeguards to prevent people from doing this in the future
https://arbiscan.io/tx/0x79b817e966b47bc775ae1b7a2eaf67ce26eaac41faaf2e8f787380a77cb52280

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1178335476734754866/1178335679948800031

**Comment by preethamr** [comment]
Working on removing liquidity, and refunding the user.

**Comment by preethamr** [comment]
Refunded the user:
https://arbiscan.io/tx/0x8f5e9a6f25b522e41cab69e9d3008189f7a16b71b7fe652d16179e7bd9b9c9f0

**Comment by preethamr** [comment]
This is a public call in the contract:
https://github.com/connext/monorepo/blob/3c7b59ecd0a9d945973e5a8f4f84b169dba8b6d2/packages/deployments/contracts/contracts/core/connext/facets/RoutersFacet.sol#L438

At best UI should warn to ensure adding funds to router is the user`s intention, and that funds can only be retrieved by the owner of the router.
