### ISSUE TITLE
[ST] Cannot estimate gas (Yubiai)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5222]
**Describe the bug**
Screenshot from user
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29MQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1863e826bcb131488f96c03308713cc776daa461/telegram-cloud-photo-size-1-5127846705956498623-y.jpg)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ce0d4121b9348211e7177f466726228373955b4/image.png)

**Link to ticket in discord**

**To Reproduce**

**Screenshots**

**Additional context**
@oncall

**Comment by prathmeshkhandelwal1** [comment]
@pjenviri , Can you take a look here.

**Comment by pjenviri** [comment]
updated rpc endpoints: https://github.com/CoinHippo-Labs/connext-bridge/pull/263

**Comment by preethamr** [comment]
Closing this as it is currently not affecting users, and the RPC change seems to have resolved the issue.
