### ISSUE TITLE
Add Linea to UIs

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5223]
## Problem
Please do this in staging so we can test

## Proposed Solution
_[OPTIONAL] Thoughts on solution design. We could do <insert idea> to solve this problem._

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [x] Able to add and remove liquidity to Pools 
- [x] Able to ad and remove liquidity to routers
- [x] Able to bridge to and from Linea
- [x] Able to see updates in Explorer

**Comment by alexwhte** [comment]
from #5052

**Comment by pjenviri** [comment]
We were unable to update the SDK version to add Linea support, as mentioned in this [Discord post](https://discord.com/channels/992549151134982234/994389387834032198/1177808014003154974).
