### ISSUE TITLE
[ST] Offline mainnet routers

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5225]
**Describe the bug**
A user made a 6655 USDC bridge from BNB to Ethereum and it didn't receive any bids. There are two routers with 30k each on Ethereum and their last transactions were in mid-October.
https://connextscan.io/tx/0xf8a8b3d86c95cc5f40e7f19b562acd0aa9db6439bb6c9b928c79450a4c9ef09c

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1178764035768983615/1178764224621727927

**Comment by just-a-node** [comment]
If the routers with sufficient liquidity are not bidding then this will go through slow path. Will continue monitoring txn for reconcile.

@Tommy-R8 Can you point out the 2 routers? We'll reach out to them and see if there's any issues.

**Comment by wanglonghong** [comment]
The transfer has been completed. It looks like the router is up again.
