### ISSUE TITLE
[ST] bware labs router is offline

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5239]
**Describe the bug**
A user is trying to bridge RADAR from Ethereum to BNB. The Bware labs router is the one with RADAR liquidity, but the last transaction it made was a week ago. https://connextscan.io/tx/0x2a350b46c9750066b3a65cad79c1a43d6a3d95732fc67f82c5f5523a9245fb3e
Link to router: https://connextscan.io/router/0x8cb19ce8eedf740389d428879a876a3b030b9170

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1179241451708764261/1179241648404824064

**Comment by Tommy-R8** [comment]
Another transaction with the same issue https://connextscan.io/tx/0xc03c065b9bb6674ccb7d6bf317c142920a6bacafa390490d4f1f360696baf045

**Comment by wanglonghong** [comment]
The router is up again and both have been executed.
