### ISSUE TITLE
Insufficient allowance：Click here to bump

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5243]
**Describe the bug**
When the user clicks here to bump on the Connext scan, execution reverted: ERC20: insufficient allowance appears.
**Link to ticket in discord**

**Screenshots**
![b725d2b415bdbc0574a7bfbf7ec4b90](https://github.com/connext/monorepo/assets/92560156/1a5a00a7-e002-49ed-bbda-ea2fe4c80d5c)

**Additional context**
DC link:https://discordapp.com/channels/454734546869551114/1179357092826591293/1179357097553571883
TX ID:https://connextscan.io/tx/0xa0bea728a2b964a9eebb118f9da4dd9e4995fc75472d6da721f0f36e47581f09
@oncall

**Comment by pjenviri** [comment]
deployed the updates in the below PRs: 
- https://github.com/CoinHippo-Labs/connextscan-ui/pull/126
- https://github.com/CoinHippo-Labs/connext-bridge/pull/245
