### ISSUE TITLE
[ST] Transaction delegate address is a CEX deposit address

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5247]
**Describe the bug**
A user bridged USDT from Gnosis to Polygon directly into a CEX deposit address through Jumper. The slippage tolerance was set at 0.1%. Jumper automatically sets the receiver address as the delegate that can update the slippage, so now the user is stuck.
https://connextscan.io/tx/0xd36aeaba25a599e4ed22a50c5e9ff3152ba06db5561d642e076c0a229eda6c29

This also ties into https://github.com/connext/monorepo/issues/5190

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1179617907743928330/1179618311667994635

**Comment by Tommy-R8** [comment]
We have a new case of this. This time the transaction was made through Connext Bridge directly. The delegate is a CEX deposit address.

https://connextscan.io/tx/0x1ed53f4a115c65e78cfe5707a0c531a1421bc940911eb3c032351b7b61f8288e
https://discord.com/channels/454734546869551114/1188229899215970486/1188230471100924015

**Comment by Tommy-R8** [comment]
The tx went through

**Comment by preethamr** [comment]
Resolved
