### ISSUE TITLE
[ST] Unwrapper Execute Tx was reverted

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5254]
**Describe the bug**
User funds stuck in unwrapper contract on Linea. 

5 ETH. 

[**Link to ticket in discord**](https://discord.com/channels/454734546869551114/1179746362426925067)

**Additional context**
[Connextscan](https://connextscan.io/tx/0x9f12bff34780ae9290ba9f39dda276a9fa21ad3cc391d5b961891def1793f9ce)
[Lineascan](https://lineascan.build/tx/0x38ae996853cb7730e0aa0f40543052a703fc7bd34280306f3e8e6aca3eb11d46)
[Unwrapper Contract](https://lineascan.build/address/0xceb49aea4faec437bf1b82ea4a76940df9323273#internaltx)

@oncall

**Comment by just-a-node** [comment]
Swept from unwrapper and returned to the user.
