### ISSUE TITLE
[ST] Gnosis router is offline

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5255]
**Describe the bug**
The router https://connextscan.io/router/0x048a5ecc705c280b2248aeff88fd581abbeb8587 is offline (last transaction made in August). It's pretty much the only one with decent liquidity and people get stuck going to Gnosis because they don't get bids. Tx here https://connextscan.io/tx/0x36418721f996967e50eefe89081383a611f513aca311af6b1d68172ad9769500

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1179872112656257145/1179872356269822072

**Comment by alexwhte** [comment]
pinged gnosis again

**Comment by alexwhte** [comment]
fixed

**Comment by liu-zhipeng** [comment]
Gnosis router is working properly now. 
<img width="1852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3N5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0100101252ba66541163f8b9e9904ef96c7c36b/image.png" alt="image.png" />
