### ISSUE TITLE
[ST] <High relayer fees (any chain to LINEA)>

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5257]
**Describe the bug**
Our system is asking for a too high relayer fee to bridge to Linea. (10x the amount for other L2s)

We've an affected user who already paid almost 0.009 eth (he bumped the txn, relayer fee was 0 at the moment of sending the txn) and his txn hasn't gone through after 2 hours **(seems that there is also an issue with routing)**

https://connextscan.io/tx/0x7fd546a5d46e9c65ceb903fb69f26f12b9620cd3f94fa31fec467bb8a63aea09

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1180056771319054417

**To Reproduce**
1. Go to bridge.connext.network
2. Select any chain on origin and Linea on destination
3. Compare relayer fees with Arbitrum or Optimism

**Screenshots**

Relayer fee miscalculated: (pic before the bump from the user)

![image](https://github.com/connext/monorepo/assets/26097731/541d21b7-3ad1-4b9b-9b77-8231ac6b30f7)

![image](https://github.com/connext/monorepo/assets/26097731/c95d3233-c1e5-43bf-a8e6-f447f9ef1330)

![image](https://github.com/connext/monorepo/assets/26097731/1192ab29-00ed-493b-9631-cded06e97d38)

Stuck txn: (seems not getting bids)

![image](https://github.com/connext/monorepo/assets/26097731/92b2df28-0915-45b4-9007-0f2ed654971a)

@oncall

**Comment by liu-zhipeng** [comment]
That is normal.
![image](https://github.com/connext/monorepo/assets/57480598/cecef848-c6ff-43a5-a3de-89d6fa365d29)
**
![image](https://github.com/connext/monorepo/assets/57480598/33a5d9b8-8543-48ad-a9ec-6debfa9b33a0)
**
GasPrice on Optimism is `0.1 Gwei`. But gasPrice on linea mainnet is `3.1 Gwei`, that is 31 x

**Comment by liu-zhipeng** [comment]
We will take a look!!. Thank you for report.

**Comment by wanglonghong** [comment]
Thank you both! I've just rolled out the fix. Would you please check again?

**Comment by MinistroDolar** [comment]
> Thank you both! I've just rolled out the fix. Would you please check again?

<img width="375" alt="image" src="https://github.com/connext/monorepo/assets/26097731/1fbbd57c-6964-4902-8a40-f979e31e009d">

It's better now! Thanks!!
