### ISSUE TITLE
[ST] Airdrop page shows nothing for the eligible users

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5259]
**Describe the bug**
Airdrop page shows nothing for the eligible users

[**Link to ticket in discord**](https://discord.com/channels/454734546869551114/1180014270914764800) and a few more cases in other channels reported.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/74738120/baff8912-e45f-4f11-a6d1-3484046e7f66)

@oncall

**Comment by alexwhte** [comment]
@oswy-cpu Can you share any affected users wallets in here please?

**Comment by alexwhte** [comment]
here's one 
address: 0x120f5C9cEE73bC3283a506005EBE966a709D7Fb9

Transaction Hash
0xeee18e53663194cb6ecd22dc47685bb745ea942146fb663612159d540f1213cb
0xc172fe7325e75a88a2d4ff2c78ea7d78b1171abe801d359d368656b8a66edbfc
0x292b2a9100bcf6bd761d78ee5a3691c0ae8c4ee7c92f379e38aeb405636c2518
0x8e258357d854ea6590a1c14dfce04aeb8e3024d95f24ef2d398933075bf942ce
0xdf5b8fbd67f7d4a76e91ac21a05be24b68ece1dbd005a85fee98b0ecfe2cdbec
0x51b91a47b0334c5585ce2f2f0c9b9bf8de14ff341ecf441a954fa924b4066302

**Comment by oswy-cpu** [comment]
@alexwhte 

0xDe6BAa64154B19C4475CFa2DcB4cf27DbBcCA36B
0x3c43aa8e525d0ca2fab672cd55f79de777295e99
0x21ff8AcA19D780F19167767635C679B920CAaBD4
0x8e94cc64F82C485AB51f23835A6db517A3D61Ee0
0xd3F4fE3B11A30EB4a5B8e3B49b41Af804C3940DB

There's all wallets we have from Discord

**Comment by cr-walker** [comment]
Thanks! We are reviewing this now.

**Comment by ajtokensoft** [comment]
This issue has been resolved

**Comment by preethamr** [comment]
Closing as it is resolved.
