### ISSUE TITLE
Migrate graph studio subgraphs to arbitrum one

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#5267]
## Impact

> Benefits of transferring your subgraphs⁠
> 
> The Graph's community and core devs have been preparing to move to Arbitrum over the past year. Arbitrum, a layer 2 or "L2" blockchain, inherits the security from Ethereum but provides drastically lower gas fees.
> 
> When you publish or upgrade your subgraph to The Graph Network, you're interacting with smart contracts on the protocol and this requires paying for gas using ETH. By moving your subgraphs to Arbitrum, any future updates to your subgraph will require much lower gas fees. The lower fees, and the fact that curation bonding curves on L2 are flat, also make it easier for other Curators to curate on your subgraph, increasing the rewards for Indexers on your subgraph. This lower-cost environment also makes it cheaper for Indexers to index and serve your subgraph. Indexing rewards will be increasing on Arbitrum and decreasing on Ethereum mainnet over the coming months, so more and more Indexers will be transferring their stake and setting up their operations on L2.

From [thegraph docs](https://thegraph.com/docs/en/arbitrum/l2-transfer-tools-guide/#benefits-of-transferring-your-subgraphs)

## Proposed Solution
Follow up their guide [here](https://thegraph.com/docs/en/arbitrum/l2-transfer-tools-guide)

## Acceptance Criteria
We should have all graph studio subgraphs(mainnet,polygon,gnosis) migrated to arbitrum one.

**Comment by liu-zhipeng** [comment]
Completed
