### ISSUE TITLE
[ST] Offline router

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5268]
**Describe the bug**
The router https://connextscan.io/router/0x5d527765252003acee6545416f6a9c8d15ae8402 made its last transaction on October 18th. It's the only one with significant USDC liquidity on mainnet and there's a transaction with no bids as a result of this. https://connextscan.io/tx/0xc1107829b372bba089550684499366912b232f106ec3959e6154c2d4440e5d4d

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1180576480548364348/1180576606792728687

**Comment by just-a-node** [comment]
01node restarted router, bidding again.
