### ISSUE TITLE
[ST] Incorrect fee to mainnet

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5271]
**Describe the bug**
A user bridged 0.842 ETH from BNB to Ethereum through Bungee. They say their site quoted that he'd receive 0.842 ETH. When the transaction completed, he ended up with 0.659 ETH on Ethereum, with the rest (0.182 ETH = $390!!!!) being taken as the relayer gas fee. This fee is outrageous even for mainnet. The transaction on mainnet ended up costing 0.0128 ETH ($28).

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1180734817244033137/1180735152498933780

**Screenshots**
Here's what a normal estimate should look like:
![image](https://github.com/connext/monorepo/assets/84744304/13e63c5a-c7f1-4c3e-957d-f157a00ebad4)

**Additional context**
We had some other tickets coming from Bungee users regarding fees being taken without notice (although none that were so extremely out of the ordinary like this one). I believe there's something in either our relayer fee estimations that they quote or something in their front end that ends up in these weird cases. Like if in some cases they just displayed basically 0 relayer fee but then the user gets charged for it anyway.

**Comment by Tommy-R8** [comment]
Another one: https://connextscan.io/tx/0x1a18e2a46fd84027159982033d1db8611d7bdf8da06c4fb96a14d51665d2640f
https://discord.com/channels/454734546869551114/1180930865874874429/1180931611718582282

**Comment by preethamr** [comment]
@prathmeshkhandelwal1 could you close this, with you findings, or mark as won't fix

**Comment by prathmeshkhandelwal1** [comment]
They had the issue where the relayer fees calculation had issues with `priceIn` field (usd or native). We sent the code snippet to fix it and the list of txs where they had to refund the user.
<img width="1127" alt="Screenshot 2024-02-06 at 2 22 20 PM" src="https://github.com/connext/monorepo/assets/56167998/d57c200c-208c-4cef-8b57-8c2f0952f98e">
fund user
