### ISSUE TITLE
[ST] Linea relayer fee too low

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5274]
**Describe the bug**
Test shows low relayer fee
https://connextscan.io/tx/0xb472fffceaa72b17d169825215ac5de9edd975e4681a0f55b1597830a9c2725c

![image](https://github.com/connext/monorepo/assets/37959170/5f5f0de6-52ff-4f6e-a074-52e42dc7ae5b)

**Comment by alexwhte** [comment]
Why is the estimate wrong?

**Comment by wanglonghong** [comment]
We've fixed it, It was just a cache issue.
