### ISSUE TITLE
[ST] Optimism subgraph with issues again

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5280]
**Describe the bug**

Seems that our subgraph on Optimism isn't working properly again. 

A few users reported that their txns never arrived:

https://optimistic.etherscan.io/tx/0xb0711d1663f8bc3b46763fba3cc6ec70e7e1ad1b5dc7178f5adfc2e5cee53cae

https://optimistic.etherscan.io/tx/0xc014f6bb03aa36e3b73ef1eed0aad8929d5a7e120e0b9241c107895e85d9db6d

https://optimistic.etherscan.io/tx/0xe5bbb231599fa62b94f8f951aaf00e01fbab52486abb620cb0debf6ab2bb7b1d

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/3b2fee99-11ec-4e2c-9860-5d88972f4c42">

You can also check that there are a lot of incoming txns in the last 2 hours that aren't displayed on connextscan:

https://optimistic.etherscan.io/address/0x8f7492de823025b4cfaab1d34c58963f2af5deda#tokentxns

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/732df5de-db04-4c59-a075-45c74f85e0d3">

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/b517c562-7ed1-4106-825c-80ac83a88c00">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1181547142020608090

https://discord.com/channels/454734546869551114/1181553921483874345

https://discord.com/channels/454734546869551114/1181560324076347452

**Additional context**

This is the 3rd time in a few days:
https://github.com/connext/monorepo/issues/5252

https://discord.com/channels/454734546869551114/840312279223238656/1171158836191694908

@oncall

**Comment by wanglonghong** [comment]
The previous fallback strategy was not working, so even though bwarelabs worked at that time, it was just trying to fetch from the hosted-service which was unsynced.
