### ISSUE TITLE
Socket user refund data

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5281]
Please review socket chat and help confirm if we can calculate baseed on logs

![image](https://github.com/connext/monorepo/assets/37959170/6610dc0e-569c-4070-bd7c-7812ec274f87)
refunds for affected users working from this sheet - https://docs.google.com/spreadsheets/d/1GUW3oEyRSXnyTtTmu2_qNBm4nTtTasWyumi-ELHfIc4/edit#gid=0

![image](https://github.com/connext/monorepo/assets/37959170/e99bf316-8dbd-432c-90fa-77a057654c0f)

**Comment by LayneHaber** [comment]
update: responding in thread to make sure they can properly calculate the differences

**Comment by just-a-node** [comment]
@prathmeshkhandelwal1 Please post your findings here

**Comment by LayneHaber** [comment]
these users were refunded, via socket (and we closed out with them) 

going to close this issue
