### ISSUE TITLE
[ST] alUSD txns ends up sending nextalUSD to the user

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5289]
**Describe the bug**

The user states: 

"As you can see from the screen shot, When I bridge nextALUSD from Optimisim to Arbitrum I cann choose to get alUSD which is available on many DEX but, even after three successful bridges I get nextALUSD on the other chain."

![image](https://github.com/connext/monorepo/assets/26097731/00952143-3845-42a5-83d9-c4e1f59ed06b)

https://connextscan.io/tx/0x6f8623dac027d3e21ddc87319cdd87220dedcf4fbe34587beb3fb7efdc15213c

https://connextscan.io/tx/0x3ef9d3450387382e9e85c9c456154feb95ebc32e2db311c626a8f134557b0504

https://connextscan.io/tx/0x86ba7d43b27649c7eae3914c3f88b61d9b609e7ebd5b628e49d24a36610b8009

I have observed on Connextscan that several users solve this by sending to mainnet, but in cases like this where the user is sending small amounts this is 100% unfeasible.

There should be a definitive solution for this, for the moment I have instructed the user to change his nextalUSD to alUSD in Optimism by interacting directly with the "ExchangeOldForCanonical" function of the alUSD contract.

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1181517136359854090

**Additional context**

I remember that we had a similar issue here: 

https://github.com/connext/monorepo/issues/5167 (at that time, Eddie helped the user to "exchange" the next tokens for the canonical ones)

@oncall

**Comment by preethamr** [comment]
This has been resolved by the above fixes.
