### ISSUE TITLE
Socket bumping issue 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5292]
## Background
https://connextscan.io/tx/0x8d60a0e25f6f2824179153bf4f3966e386987850f98cfce65447ddfe9ca1a353

Vamsi, [Dec 6, 2023 at 10:13:15 AM]:
https://arbiscan.io/tx/0xb40fc2ad421838793e9d55a40809887f898b3aaf685d5c878dc34ed58bf33678

This is the latest one.
https://arbiscan.io/tx/0x1af2cf2be2f485dcd47ee0f6d0d04680b49935f4cb336ef502f4b7252005c4ed

I have also done it like this two times before.

**Comment by just-a-node** [comment]
Socket bumped to 0.3% and then 0.27%. Execution is failing on destination because the slippage is still too low. 

Related but separate issue is that UI is only showing the transfer's original slippage instead of the updated slippage. This will be handled in a separate bug #5293.

**Comment by just-a-node** [comment]
> Note:
> 
> Sequencer **should not** wait to retry as part of exponential backoff loop in the case of a bump. We should instead listen for bump event, **retry immediately**, and then reset the exponential backoff.

Btw, confirming that this is the case right now. When a bump is detected we reset backoffs so retry happens immediately. On additional failures, exponential backoff kicks in.
