### ISSUE TITLE
Base chain launch

### ISSUE THREAD

**Issue by liu-zhipeng** [connext/monorepo#5299]
## Problem
Users can bridge tokens from/to Base goerli/mainnet.

Launch plan
https://www.notion.so/connext/Base-Launch-Plan-4769dbbdbdad4847aabbef61719bb995

### Linked Issues & Documentation
<img width="528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e0c055419141cc370b9610dfbe18d2a06936c0e/image.png" alt="image.png" />

## Definition Of Done
- [x] #5300
Testnet & Mainnet: 
- Transfers work from L1<->Base and L2<->Base fast path in UIs
- Transfers work from L1<->Base and L2<->Base slow path in UIs
- Pool deposit withdrawals for in UIs
- Swaps work in UI

**Comment by preethamr** [comment]
Covered by More Chains
