### ISSUE TITLE
[ST] Ethereum to Gnosis transaction going through slow path unnecessarily

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5301]
**Describe the bug**
A 16.6 WETH transaction from Ethereum to Gnosis is going through the slow path when there are multiple routers that could fulfill this transaction. Our own router has more than 20 WETH. https://connextscan.io/tx/0xd15aca6328e51c642d8ec7b89e7d8a37483b20113e12d0f07cadde4dba060f94

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1182399403634466848/1182399468046385272

**Comment by MinistroDolar** [comment]
Another one, going through slow path from Gnosis to Linea unnecessarily: (Router has 4985 usdt)

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/f9db4e62-4e90-410a-b006-d3b8ab5643e3">

https://connextscan.io/tx/0x45d392073341d9c1fb1eb99ba82fa8ae192d38026fb81a4887b9ae4f9daf5ced

**Link to ticket in discord:**
https://discord.com/channels/454734546869551114/1182436742020730971

**Comment by preethamr** [comment]
This was due to delayer subgraphs, that kept he routers in the dark, and could not bid.
This is nor resolved, and recent transfers get router bids
