### ISSUE TITLE
[ST] Gnosis transactions missing

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5311]
**Describe the bug**
Transactions originating from Gnosis Chain can't be found on Connextscan. I believe the latest transaction it shows from this domain is from 1h45m ago. Gnosis subgraph is probably very delayed
Transaction links: https://gnosisscan.io/tx/0x86d704f72dce90bc57504b2ef4c5aa6a1d697d931199db331687b71dfb9b7f7d
https://gnosisscan.io/tx/0xc56d50b2b49dfcf1d0fa267508364c573cd7049c26829577c16614d9c9a5b130

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1183083693774995608/1183084371079614515

**Comment by preethamr** [comment]
Taking a look at the db.

**Comment by preethamr** [comment]
As suggested subgraphs where behind.
They are now on connextscan, and are executed.
https://discord.com/channels/454734546869551114/1183083693774995608/1183113779383373854
