### ISSUE TITLE
[ST] Router is not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5321]
**Describe the bug**
A 29.7k USDC tx from BNB to Ethereum is not getting bids https://connextscan.io/tx/0x68afb8dd5d4f69a809244d7d77753d9e63f1e029310dec45412ca8d70f9dc489. The router https://connextscan.io/router/0x5d527765252003acee6545416f6a9c8d15ae8402 has enough USDC to cover this transaction but the last transaction it made was 2 days ago.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1183953066836381697/1183953773488525372

**Comment by preethamr** [comment]
Sequencer has notnot seen bids from this router since `
Dec 09 02:07:18.850`

**Comment by preethamr** [comment]
@Tommy-R8 This router is likely down. We need to message the router operator asking them to check if it looks healthy on their end

**Comment by preethamr** [comment]
@Tommy-R8 We should update or close this issue, since there is not much we can do from our side, beyond this atm
