### ISSUE TITLE
[ST] Linea to Gnosis txn stuck more than 2 days

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5324]
**Describe the bug**

A txn from Linea to Gnosis is stuck (52 hours at this moment) and the slow path never happened (or at least that's what the scan is showing right now)

https://connextscan.io/tx/0x6e77565ffa6c4ad5e9bd4a6087f7749a597911ec8a78a44458b6a0522cef2ebf

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/606b5519-526f-46b4-aeb4-3edccfc6646e">

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1184117623840055326

**Additional context**
@oncall

**Comment by prathmeshkhandelwal1** [comment]
Seems like linea AMBs are slow that’s why we are expecting a delay

**Comment by MinistroDolar** [comment]
> Seems like linea AMBs are slow that’s why we are expecting a delay

More than 2 days? And why he needs slow path to bridge 170 usdt? There is a lot of fast liquidity on gnosis.

**Comment by prathmeshkhandelwal1** [comment]
> > Seems like linea AMBs are slow that’s why we are expecting a delay
> 
> More than 2 days? And why he needs slow path to bridge 170 usdc? There are 42k of fast liquidity on gnosis.

There docs mentioned 32 hrs of approx time for AMBs.
Transactions on gnosis was going through forced slow path due to underlying sync issue. Issue for forced slow path has been resolved. 
All the txs going to gnosis seems healthy for fast path.

**Comment by prathmeshkhandelwal1** [comment]
Marking this as completed
