### ISSUE TITLE
[ST] Optimism and Gnosis subgraphs failing again

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5325]
**Describe the bug**

Seems there is a delay in both subgraphs again.

Optimism examples:

https://optimistic.etherscan.io/tx/0xa98a2ba84129b224aab1d99289c1926f220e14ed21e601c73948fc04bab69cd3

<img width="1055" alt="image" src="https://github.com/connext/monorepo/assets/26097731/27d2123b-5f94-4f01-8e3f-e6632c117955">

<img width="1429" alt="image" src="https://github.com/connext/monorepo/assets/26097731/8ee826f4-3451-48e4-9342-425c34c059e9">

https://optimistic.etherscan.io/tx/0x9041cdc1d4b67e045dfd3f0464f8ae6cf71e533784ac19ecb56d14d733011f92

<img width="1052" alt="image" src="https://github.com/connext/monorepo/assets/26097731/7bb82cd2-465c-4875-b89b-d82ec1428a3f">

<img width="1381" alt="image" src="https://github.com/connext/monorepo/assets/26097731/d00bc73f-b98b-4f19-9582-7e989ee31b25">

Gnosis examples:

<img width="1052" alt="image" src="https://github.com/connext/monorepo/assets/26097731/0a09336e-9a7f-496e-aa33-9ff5ea15a91b">

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/877bc273-f5c8-429e-9f4c-b8a53b92afb2">

https://discord.com/channels/454734546869551114/1184087471869407272

https://discord.com/channels/454734546869551114/454734546869551116/1184093938596970566

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1184113210014580776

https://discord.com/channels/454734546869551114/1184102988135014461

**Additional context**
@oncall

**Comment by preethamr** [comment]
Both these issues have been resolved, and recent transfers looking healthy
