### ISSUE TITLE
[ST] P2P Router not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5327]
**Describe the bug**
This transaction https://connextscan.io/tx/0xe5205c754d27d26ae427580bfeb459b3a99a6f82545a1ee95308ce55e6389f6b should get bids from the P2P router (https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4). I'm seeing the latest tx it made was a couple of hours ago. 

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1184139611925139537/1184141953013645362

**Comment by preethamr** [comment]
I see ongoing bids from P2P router.
https://connextscan.io/tx/0x33686e43c3128c692aff9d22757f38d37eabdaa0147b9eaa6fbcaf06f70bc65f

Looks like the router had intermittent issues, was not bidding for a few hours, from our logs:
<img width="1427" alt="image" src="https://github.com/connext/monorepo/assets/1195648/6784cfc8-6952-4e46-ba00-6e46a066f745">

**Comment by preethamr** [comment]
@Tommy-R8 lemme know if I need to look into this further.

**Comment by preethamr** [comment]
Resolved.

As of now router is active. Latest transfer < 1 hour ago:
https://connextscan.io/tx/0x21c467443124c1a433859dea1ec27f6fcc905507e231cc2a880f0af363fa92b3
