### ISSUE TITLE
[UI] Slippage warning doesn't show up without expanding the dropdown

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5352]
## Problem
If a transaction's estimate exceeds slippage, it should show a warning. The problem is that this warning is only visible if you expand the "Additional Details" dropdown to modify the slippage tolerance. The warning should be clearly visible from the main screen.
![image](https://github.com/connext/monorepo/assets/84744304/e1489c26-52bb-47f2-8f2b-42dd5c3ef8bd)
![image](https://github.com/connext/monorepo/assets/84744304/215f8a21-e53e-4c07-be57-70f9f2b4cd88)

## Impact
If users don't see the warning they will get their transaction stuck

## Proposed Solution
Show the warning on the main screen without needing to expand the menu

## Acceptance Criteria
The user should instantly and clearly see in the main UI if their tx won't succeed because the estimated slippage is higher than the tolerance

**Comment by pjenviri** [comment]
Updated and deployed.  
PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/271
