### ISSUE TITLE
[ST] Tx stuck on fee bump

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5362]
**Describe the bug**
A transaction has been stuck in LowRelayerFee for more than 2 days https://connextscan.io/tx/0xc233527b3a2789ddf215188179ab7ef0588a998c6b1ae18b8963ea16a542ed0d. The modal now asks for 0 xDai extra, and when trying to connect a wallet and bump, it just endlessly loads.
![image](https://github.com/connext/monorepo/assets/84744304/ec6f6978-c4cb-4ff4-b640-b53889d4a0d8)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1184491694792638524/1184492083285864610

**Comment by pjenviri** [comment]
I didn't get 0. 
<img width="1432" alt="Screenshot_2566-12-16_at_19 55 06" src="https://github.com/connext/monorepo/assets/87146398/68f89420-e1d0-4d38-86d9-9152799b657c">



Btw, when the UI shows 0, could the fluctuation in gas prices be a factor? Perhaps the newRelayerFee at that time was lower than the relayer fee that had been paid?

**Comment by prathmeshkhandelwal1** [comment]
Resovled.
