### ISSUE TITLE
[ST] User bridged into low liquidity pool

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5364]
**Describe the bug**
A user bridged ~373 DAI to Gnosis Chain, where the pool's TVL is merely 800 nextDAI-DAI. We need to prepare the calldata for him to force receive nextDAI and be able to bridge back.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1185810170866044968/1185810718906396782

**Comment by preethamr** [comment]
This has been resolved by funding the bump ~$14 - on the house

**Comment by Tommy-R8** [comment]
Closed the wrong issue. This tx is still pending https://connextscan.io/tx/0xab15a2dd885dede29ef44d4af0f78422ceb92c4d44a1133e08dec6317ff17210
