### ISSUE TITLE
[ST] Transaction with 100% slippage

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5365]
**Describe the bug**
A user tried to send xDai to Gnosis chain. He bumped the slippage up to 100% and even then it's asking for 100.1%. We'll also need to give him the calldata to force receive local

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1186011453879238809/1186011561056276521

**Comment by preethamr** [comment]
This transfer executed by the time I could generate the params for force receive local.
The user took ~7.65% slippage on this.

Not much we can do for the user at this point.

Resolved
