### ISSUE TITLE
[ST] High relayer fee to Ethereum

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5366]
**Describe the bug**
A LiFi transaction going from Gnosis Chain to Ethereum took 125 xDai as the relayer fee, while the fee that ended up being paid on mainnet was only $55. Looking at historical gas prices, the relayer fee estimate seems incorrect. https://connextscan.io/tx/0x63edbf9d9b66cd45b6806123c12dfd313e20e9dbdc84cabeac169010afe87e22

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1186057584894029936/1186057617928364092

**Comment by preethamr** [comment]
Our findings so far, this is due to inaccurate relayer fee estimate, that happened due the gas conditions at the time.
