### ISSUE TITLE
Allow disabling chain+asset combo in UI config

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5370]
## Background

Currently, we can set `disabled: true` at the asset-level in the UI config but we need a way to more granularly disable specific chain+asset combos. 

For example: if we want to disable DAI on Gnosis without disabling on other chains, we should be able to set this in the config:
```
      {
        "contract_address": "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d",
        "chain_id": 100,
        "decimals": 18,
        "image": "/logos/assets/wxdai.png",
        "symbol": "WXDAI",
        "next_asset": {
          "contract_address": "0x0e1D5Bcd2Ac5CF2f71841A9667afC1E995CaAf4F",
          "decimals": 18,
          "symbol": "nextDAI",
          "image": "/logos/assets/nextdai.png"
        },
        "wrappable": true,
        "is_pool": true,
        "disabled": true
      },
```

When we move back to `@connex/sdk` package instead of `sdk-core` we should just enabled assets from `sdk.getSupported()`.

**Comment by pjenviri** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/275
