### ISSUE TITLE
[ST] Txns to ETH Mainnet with "No bids received"

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5389]
**Describe the bug**

A few txns are going to Mainnet through the slow path but there is enough router liquidity to fulfill them. 

https://connextscan.io/tx/0x6ad2007fbcda3358c7cf26f9cbc59486a0be7ef30dc356692f680445aca3bad4

<img width="1471" alt="image" src="https://github.com/connext/monorepo/assets/26097731/675e2902-0033-43c2-91e1-64762b0b06d6">

https://connextscan.io/tx/0xd97e7e798648e7432716d68ae97035a4ee3983a05011e0ce497f001ae4954a12

<img width="1591" alt="image" src="https://github.com/connext/monorepo/assets/26097731/0afdd624-a605-42b6-92d5-f452d245e99e">

https://connextscan.io/tx/0x2d9d5863a9c51cea0082581555fce6d513e5ab19811493cf5930085ba887fe5f

<img width="1530" alt="image" src="https://github.com/connext/monorepo/assets/26097731/689c3932-c2af-4604-a399-adaa502e6e68">

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/1a6b75e5-8f6c-4b0d-9e40-1d88669f4d44">

https://connextscan.io/ethereum

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/67c47ce4-40a5-4ba6-a2e4-18a4099172ae">

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1186722473534820524

https://discord.com/channels/454734546869551114/1186758571153698846

https://discord.com/channels/454734546869551114/1186771416465543198

**Additional context**

Maybe related to Bacco's upgrade? 
@oncall

**Comment by just-a-node** [comment]
Completed.
