### ISSUE TITLE
[ST] Signer Address Missing

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5397]
**Describe the bug**
When bridging any asset from Optimism to Arbitrum, users get a "Signer Address Missing" error when they click send. This was reported 3 times today already and it's the first time I've seen the issue
![image](https://github.com/connext/monorepo/assets/84744304/328a470a-7990-42db-8251-48bf045c13f3)

**Comment by just-a-node** [comment]
Repro'd. Console logs:

<img width="426" alt="image" src="https://github.com/connext/monorepo/assets/16638982/375d5863-c49c-43b5-8e05-f99ecb8971ab">

**Comment by pjenviri** [comment]
We haven't been able to replicate it. Could you explain how to reproduce the issue? We've attempted to connect, disconnect, and switch chains multiple times, but I've never encountered that error.

**Comment by just-a-node** [comment]
It seems to happen intermittently after switching chains and attempting to transfer. I've had similar problems with adding liquidity to routers. We might need to check how on how the wallet state is managed. Usually a refresh of the page fixes it.

**Comment by just-a-node** [comment]
It is hard to consistently reproduce this, but there is definitely an issue. @pjenviri I'll pass back to you for you guys to take a deeper look into wallet state.

**Comment by pjenviri** [comment]
We have tried to hard-set the signer in this PR: https://github.com/CoinHippo-Labs/connext-bridge/pull/281. Let me know if the issue persists.

**Comment by just-a-node** [comment]
Seems good now, will close.
