### ISSUE TITLE
Low Slippage Bump button not working properly

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5404]
## Background

Vamsi, [20-Dec-2023 at 4:33:50 PM]:
I have been bumping this from 0.3 to 1.2 now.

Still shows it increased by 0.1 everytime I open it.

https://connextscan.io/tx/0xb202c08ccbe164d0b05605cbd0b8245b712b95cc24b994c98e2ee12e28e3a369

Unsure if its an issue on the UI

Can you give me a connext address to set when the user is a contract, I am gonna open it up now for users themselves to bump it.

Msg from socket team.

**Comment by pjenviri** [comment]
According to the attached screenshot, the response of the `calculateAmountReceived` shows the fund was sufficient at that time (the response value < the paid one). However, we were still getting `error_status` on lowSlippage.
<img width="908" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--978169c41c2aeed6f9f9d47d6fd99c47008191b0/Screenshot_2566-12-20_at_21.09.26.png" alt="Screenshot_2566-12-20_at_21.09.26.png" />

Previously, someone on the team told us to prompt users to increase their funds by 0.1 on UI when encountering this scenario to make it go thorough. Here's the current logic on the UI: https://github.com/CoinHippo-Labs/connextscan-ui/blob/main/components/action-required/index.js#L333-L334
