### ISSUE TITLE
[ST] Internal JSON-RPC Error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5426]
**Describe the bug**
A user is trying to bridge NEXT from Polygon to either Arbitrum or BNB. Both give the error "Internal JSON-RPC Error". Removing the decimals didn't work either.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1188143909340201073/1188144757533315193

**Comment by just-a-node** [comment]
@pjenviri Please take a look at this one as well

**Comment by pjenviri** [comment]
changed the rpc endpoint: https://github.com/CoinHippo-Labs/connext-bridge/pull/281
