### ISSUE TITLE
[ST] Routers not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5427]
**Describe the bug**
This tx https://connextscan.io/tx/0xfb6fe03332de0e8bb73a9420a3e8bcb67544788af6aaca788e7862966552c51f can be fulfilled by 2 routers:
- https://connextscan.io/router/0xc4ae07f276768a3b74ae8c47bc108a2af0e40eba
- https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1188161447256137779/1188161687950475344

**Comment by preethamr** [comment]
Trying to figure if this was because of subgraph migration I was working on yesterday.

**Comment by preethamr** [comment]
This is going to mainnet and should have slowpathed by now. That is a separate issue, we are out of funds again !

I will fund it first, and then figure how the router issue

**Comment by preethamr** [comment]
This transfer is now executed
