### ISSUE TITLE
[ST] Shit's fucked yo

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5431]
**Describe the bug**
There are no completed transactions newer than 9hs ago on the explorer. I thought it was a subgraph issue with polygon and arbitrum but it's on every chain. Could it be a sequencer issue?

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1190970457684459560/1190970607538540654

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/18aeafe9-e748-4850-8519-3b6767eea20e)

**Comment by Tommy-R8** [comment]
Edit: The ~~cake~~ explorer is a lie. When filtering by CompletedFast it shows really old transactions but if you don't filter by that you can still see quite recent (sub 30 min) CompletedFast transactions.

The actual chains where I can't see any completed transactions for the past few hours are Ethereum and Arbitrum.

**Comment by LayneHaber** [comment]
Relayer balance was depleted, funded and these transfers should be completed.
