### ISSUE TITLE
[ST] Bungee xDai tx to Gnosis stuck

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5432]
**Describe the bug**
An xDai bridge to Gnosis is stuck because of the pool's lack of liquidity. The user was able to initiate it because it was made through Bungee. We need to have the Socket team forceReceiveLocal for them to get it unstuck.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1190995029666304020/1190995209870397440

**Comment by LayneHaber** [comment]
received: https://connextscan.io/tx/0x67fdfb56e0177cf316fb069e215082160c773681c6dd6928eb51423671f72d2a
