### ISSUE TITLE
[ST] Tx reconciled but not executed

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5436]
**Describe the bug**
This transaction to BNB already reconciled but didn't execute https://connextscan.io/tx/0x81ff557a56c99a823e209f3b43a94d17bcc782470853e7fe7ee4dee180cbafd2

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1191437672460337325/1191438264184361030

**Comment by preethamr** [comment]
Taking a look

**Comment by preethamr** [comment]
This transfer completed.
Root cause: sequencer backlog
