### ISSUE TITLE
[ST] No bids received (yeah, again)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5437]
**Describe the bug**
Low amount txns aren't receiving fast liquidity through routers. 

![image](https://github.com/connext/monorepo/assets/26097731/4b2e380b-3328-42f9-92c2-9306d58cf91e)

![image](https://github.com/connext/monorepo/assets/26097731/c8aafd01-c1e6-46e5-a8c5-82661c3e3c33)

https://connextscan.io/tx/0x77769a95372e72c6c240d0c24fdacb38d231254b4f81bfd199504e9dc3b5763f

https://connextscan.io/tx/0xb59df0f13d6fc5aecbfe553f7be71f120e41fc2d6a3263ae27fc373067b499fd

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1191448481865404436

https://discord.com/channels/454734546869551114/1191438269515304990

@oncall

**Comment by preethamr** [comment]
Root cause: sequencer backlog

This transfers is awaiting slippage update from the user @MinistroDolar 
The other one completed.
