### ISSUE TITLE
[ST] Stuck slippage transaction

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5438]
**Describe the bug**
This transaction is stuck on Low Slippage: https://connextscan.io/tx/0x2f8bb01c3ef11dbcd1319141e5809382d71c35ebcf7796d37594551965a6979a
The user needs the calldata and instructions to forceReceiveLocal to bridge back or swap manually

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1191242455228616828/1191243081585020999

**Comment by prathmeshkhandelwal1** [comment]
Only delegate can call the `forceReceiveLocal`.
Delegate address in above transaction is: `0x0e1b5ab67af1c99f8c7ebc71f41f75d4d6211e53`

Can we confirm if this address is hold by user?

**Comment by prathmeshkhandelwal1** [comment]
Confirmed the wallet address is of socket, pinging socket team to call `forceRecieveLocal` on the behalf of user

**Comment by Tommy-R8** [comment]
Socket was able to do the transaction yesterday.
