### ISSUE TITLE
[ST] Karpatkey router not working

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5439]
**Describe the bug**
Karpatkey flagged their router is not working and provided us their logs

[sub (1).log](https://github.com/connext/monorepo/files/13811119/sub.1.log)
[pub (1).log](https://github.com/connext/monorepo/files/13811120/pub.1.log)
[executor.log](https://github.com/connext/monorepo/files/13811122/executor.log)

**Comment by alexwhte** [comment]
please make sure we go back to Karpatkey in our Gnosis telegram chat when we have a full resolution

**Comment by preethamr** [comment]
Reviewing the logs now

**Comment by preethamr** [comment]
All the errors in the logs point to intermittent subgraph/connectivity
I would be surprised if this is still the case, if so I want to see if a manual restart of router agents helps with it.

**Comment by preethamr** [comment]
Messaged on Gnosis TG

**Comment by preethamr** [comment]
Resolved
