### ISSUE TITLE
[ST] Polygon subgraph delays

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5441]
**Describe the bug**
Looks like the Polygon subgraph is behind by 1-1.5 hs
![image](https://github.com/connext/monorepo/assets/84744304/0c67bc7a-3bee-4893-b21a-c64ab02b4107)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1191827571541815427/1191827655759249479

**Comment by Tommy-R8** [comment]
also here https://discord.com/channels/454734546869551114/1191830491544957140/1191833221852307637

**Comment by Tommy-R8** [comment]
https://discord.com/channels/454734546869551114/1171878046253465610/1191843876068134923

**Comment by preethamr** [comment]
Investigating this

**Comment by preethamr** [comment]
This is related to: #5442 

Affected this path too:
<img width="1186" alt="image" src="https://github.com/connext/monorepo/assets/1195648/0d4e9684-9f9e-40e5-a761-8917c01fb406">
