### ISSUE TITLE
[ST] Eth to BNB with no bids

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5443]
**Describe the bug**
There's more than 100k USDT to fulfill this USDT Ethereum to BNB transfer (even on our own router): https://connextscan.io/tx/0x920f739c0a37e0bdee7586959c98c27da0b29e5c5b3bfa92604e831ec4e91305

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1191861066460836031/1191861143556341860

**Comment by Tommy-R8** [comment]
This transaction went through as soon as the messaging error cleared

**Comment by alexwhte** [comment]
This took over an hour, this is still a valid bug

**Comment by preethamr** [comment]
This is related to: #5442 

<img width="1148" alt="image" src="https://github.com/connext/monorepo/assets/1195648/1efa5b39-bd81-4804-9499-25a13d5eabdd">
Same issue with this path too.
