### ISSUE TITLE
Lighthouse retry mechanism issue

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#5446]
## Background

The retry mechanism of LH isn't working properly after op roots upgrade.

We try to clear cache whenever it happens. 

## Definition of Done
Should be processed without clearing the cache.

**Comment by preethamr** [comment]
We have another instance of this:
leaf:
`0x962fbe8ef09e9cee6e0d23ad04e1a219282424e441c23c47fe1182112b961dcc`

Enqueue:
https://app.datadoghq.com/logs?query=region%3Aus-east-2%20service%3Alighthouse-prover%20Enqueued%20%40brokerMessage.messages.leaf%3A0x962fbe8ef09e9cee6e0d23ad04e1a219282424e441c23c47fe1182112b961dcc%20&cols=host%2Cservice&index=&messageDisplay=inline&refresh_mode=sliding&stream_sort=time%2Cdesc&view=spans&viz=stream&from_ts=1704228208580&to_ts=1704401008580&live=true

Proof attempt:
https://app.datadoghq.com/logs?query=region%3Aus-east-2%20service%3Alighthouse-prover-subscriber%20%40leaf%3A0x962fbe8ef09e9cee6e0d23ad04e1a219282424e441c23c47fe1182112b961dcc%20&cols=host%2Cservice&index=&messageDisplay=inline&refresh_mode=sliding&stream_sort=time%2Cdesc&view=spans&viz=stream&from_ts=1704228221558&to_ts=1704401021558&live=true
