### ISSUE TITLE
[ST] Arbitrum to BNB taking too long

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5460]
**Describe the bug**
This NEXT transaction going through the slow path is taking too long to complete https://connextscan.io/tx/0xf12ada6a9b36d06f7938c4d8e12b7f8cfb5a653647ccf6ab99159d5518676391

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1192449764365713498/1192450367066226779

**Comment by preethamr** [comment]
This transfer is completed.

There is another issue tracking why some transfers are taking so long on slow path:
https://github.com/connext/monorepo/issues/5446
