### ISSUE TITLE
[ICE: 4] Discrepancy in pool liquidity numbers in bridge UI

### ISSUE THREAD

**Issue by par94** [connext/monorepo#5475]
**Describe the bug**
Different values for liquidity are shown on the main screen (https://bridge.connext.network/pools), and the detailed view (https://bridge.connext.network/pool/USDC-on-binance)

**Link to ticket in discord**
-

**To Reproduce**
1. Go to '(https://bridge.connext.network/pools)'
2. Check the liquidity for Binance USDC
3. Click on 'Binance USDC'
4. Check the liquidity for Binance USDC
5. See error

**Screenshots**
<img width="1298" alt="Screenshot 2024-01-04 at 17 57 23" src="https://github.com/connext/monorepo/assets/2881654/c1d5e0fb-ae57-493f-86b5-36e78bb59163">
<img width="1236" alt="Screenshot 2024-01-04 at 17 55 30" src="https://github.com/connext/monorepo/assets/2881654/6158fd7f-e598-428b-b09d-936c9cb72d8a">

**Additional context**

**Comment by pjenviri** [comment]
We've updated the value displayed in UI to use the sum of balances instead of the supply value. https://github.com/CoinHippo-Labs/connext-bridge/pull/285

**Comment by par94** [comment]
The issue is still present
<img width="874" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEYxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--849089ac083e923bb683dd6af07c1dd8fef399ab/Screenshot%202024-04-18%20at%2016.20.27.png" alt="Screenshot 2024-04-18 at 16.20.27.png" />

**Comment by ekbainova** [comment]
#6088

**Comment by just-a-node** [comment]
Closing in favor of #6088
