### ISSUE TITLE
[ST] Linea router not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5478]
**Describe the bug**
110 USDC from Optimism to Linea transaction (https://connextscan.io/tx/0xe2ca03de7e7533b1d29cb5ba99f37d91604562706a78e8ceca5c4b432036cdbb?source=search) should be completed by this router: https://connextscan.io/router/0x58507fed0cb11723dfb6848c92c59cf0bbeb9927
It looks like the router is active (it made a transaction 40 mins ago) but is not bidding

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1193270849646629035/1193270998557012069

**Comment by Tommy-R8** [comment]
![image](https://github.com/connext/monorepo/assets/84744304/af856c02-d2fa-4a30-a2c6-eaf688be2dc6)
Actually there are multiple transactions in this status for 6+ hours

**Comment by preethamr** [comment]
The router is active, and bidding for Linea destination, but not from Optimism origin, for USDC.e.

The last to in this path where:
<img width="1512" alt="image" src="https://github.com/connext/monorepo/assets/1195648/3b177408-91e4-4b91-b898-d27013b94f46">
Dec 22:
https://connextscan.io/tx/0x5b97ebd7078e087ba6625692638b020736121e3fdddb4fc62bbb7d9bf1fcff6c

Dec 10
https://connextscan.io/tx/0xc39017131551f76d5b4198b0a9ce09e67ee8519e61847c463e6ae78dc2fca039

None of the routers are bidding this path, last fast path transfers:
<img width="1511" alt="image" src="https://github.com/connext/monorepo/assets/1195648/635c82db-f2f8-4bba-aed3-90fbee0917f6">

CC: @Tommy-R8

**Comment by Tommy-R8** [comment]
Another tx https://connextscan.io/tx/0xdf73237bdfb4558d8b456bfead8e95ceca3a95f0db984df303e40cd9acefc73c?source=search
