### ISSUE TITLE
[ST] Polygon routers not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5482]
**Describe the bug**
4000 USDC Optimism to Polygon transaction isn't getting bids: https://connextscan.io/tx/0x385ad62475431468dfeb7eb4c3d6d7eee80a49607af2ba2984866553f2b3968a

Routers with USDC on Polygon: https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4
https://connextscan.io/router/0xc4ae07f276768a3b74ae8c47bc108a2af0e40eba

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1193750677034369054/1193750860572917860

**Comment by preethamr** [comment]
We received split bids but not full.
