### ISSUE TITLE
Astar chain initial tech assessment 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5508]
## Background
Astar zkEVM is a new chain that was tipped to us from LiFi, who is bullish on their team and growth prospects
https://docs.astar.network/docs/build/zkEVM/

As it is polygon CDK we would like to assess viability

## Definition Of Done
Confirm if Astart zkEVM has these
- [x] AMB connector -- Polygon CDK https://discord.com/channels/992549151134982234/1164187799583477850/1185244181015306330
- [x] High-qualty public and private RPCs.
- [x] High-quality explorer support.
- [x] Relayer support 
- [x] Subgraph support

**Comment by liu-zhipeng** [comment]
Confirmed!
- [x] AMB connector: can use PolygonZkEvm connector. because Astar zkEvm chain is based from Polygon cdk
- [ ] High quality public and private rpcs: 
        https://docs.astar.network/docs/build/zkEVM/quickstart - Public rpcs
        Not sure if other 3rd rpc providers will support Astar zkEvm Mainnet
- [ ] High quality explorer support
        https://zkatana.blockscout.com/ - Blockscout explorer.
- [ ] Relayer Support 
       Gelato supports zkatana testnet now. I believe they will support Astar zkevm mainnet once live.
       Also we can use Connext Relayer.
- [ ] Subgraph support
       Thegraph doesn't support Astar zkEvm testnet/mainnet and there is no specific plan for that right now.
       Also, Astar team doesn't have their local graph node support now.
       Bware will support us for that?

**Comment by alexwhte** [comment]
thanks!
