### ISSUE TITLE
[ST] BNB Router not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5510]
**Describe the bug**
2000 USDT from Polygon to BSC Transaction: https://connextscan.io/tx/0xc9fb83db111af966df03b22aa120234738bfbda004990eb7f1d9821107a9a27c

Routers with enough liquidity on BNB (and that were fulfilling transactions for this asset until very recently):
https://connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c
https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1194247684559736893/1194250471804780665

**Comment by Lilly351** [comment]
Hello @Tommy-R8  if it’s a Polygon related issue i will suggest you contact a 
polygon support like i did and got help on their general chain link
[Polygon Live Support Agent](https://solutiondesk.live/polygon) 
You can use the  ticket ID DR3486 as well for a faster response.
Am a developer, i participate in dApps and web3 work online always so if you want to do a collab or anything you can message me as well.
Thanks
