### ISSUE TITLE
Transaction stuck from/to Arbitrum [From Socket team]

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5512]
## Background

https://www.socketscan.io/tx/0x0adc257e56438124a825bcc7c25447e8eb331c9957f8a6761bac26777b10307f
https://www.socketscan.io/tx/0xf147e4a10dda7a798bf958965e99a8bb831887f7b036c2eaacd7dd4161564438
https://www.socketscan.io/tx/0x6536f73f5a31265e7485ff41ee9f7a359cc36c4ed928b5686f957a60ffe3996f

- Checked the datadog: it shows no error

Seems like txs are going through slow path.

**Comment by just-a-node** [comment]
Transfers completed.
