### ISSUE TITLE
Txn not retried after Gelato was out of funds

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5516]
## Background

BNB -> ETH transfer hasn't been retried since Gelato funds were re-upped (https://connextscan.io/tx/0xc3322d5864fb58c8d07eaca397b21fa60cacbb27efcb1995ced42017acd83c95).

**Comment by just-a-node** [comment]
This txn was sent to Gelato when we ran out of funds - it wasn't retried. Needs follow up on why it didn't get retried. Clearing LH cache for now to see if it gets picked up.

**Comment by just-a-node** [comment]
Cache cleared, txn finished. Need to investigate the edge case nonetheless.

**Comment by wanglonghong** [comment]
fixed
