### ISSUE TITLE
[ST] Slow path Arbitrum to Optimism

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5517]
**Describe the bug**
tx: https://connextscan.io/tx/0x117994b735354fc026154e1a532e84097e3716204c6f16dc2e7091560734a97a
routers: https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4
https://connextscan.io/router/0xc4ae07f276768a3b74ae8c47bc108a2af0e40eba

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1194429290037657741/1194430205444501594

**Comment by just-a-node** [comment]
A "routers not bidding" issue? Going to close this out as we have a thread on this and the transaction in question has completed.
