### ISSUE TITLE
[ST] Optimism to Ethereum slow path

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5524]
**Describe the bug**
Tx: https://connextscan.io/tx/0x74aa7b32484d948d5ed5168f0a1ae189eda9dba8c35ee33bd647d6729394f19c
Router with enough funds: https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4
The router hasn't fulfilled an Optimism to Ethereum transaction in 10 days 

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1194745127546126511/1194745463568617584

**Comment by just-a-node** [comment]
Same, router bidding needs investigation. Txn completed.
