### ISSUE TITLE
Metis chain initial tech assessment 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5528]
## Background
LiFi is apparently really bullish on Metis and the Metis team needs a better bridge that can support it.  
They have a large treasury, the current bridging UX is quite bad, and LiFi would ask for a grant for us to support.
They asked for a technical assessment before Friday this week in order to get back to Metis team

## Definition Of Done
Confirm if Metis has these
- [ ] AMB connector -- Assumption is they are a fork of op. Can we use OP connector? https://docs.metis.io/dev/protocol-in-detail/cross-domain-messaging
If they dont support the below, we would need 
- [ ] High-quality public and private RPCs 
- [ ] High-quality explorer support 
- [ ] Relayer support  
- [ ] Subgraph support

## Notes
We will assess impact to growth goals in parallel
We will need governance approval ultimately to luanch this quarter

**Comment by LayneHaber** [comment]
> AMB connector -- Assumption is they are a fork of op.

they are a fork of pre-bedrock optimism. we have a non op-roots version of that connector [here](https://github.com/connext/monorepo/tree/65b86dd5d3d1f9d2a20ab83cdfeb4dff68628c29/packages/deployments/contracts/contracts/messaging/connectors/optimism).

we will have to make sure these contracts are modified properly to work with optimistic roots.

**Comment by alexwhte** [comment]
subgraph = $200/mo * 2
gelato = $25k/yr 
most likely to have bugs
