### ISSUE TITLE
[EXPLORER] Connect Wallet button not working

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5538]
**Describe the bug**
A user's transaction from Ethereum to Polygon was initiated with 0 as the relayer fee. When trying to bump the transaction on the explorer, the user isn't able to connect their wallet to the site to make the transaction. They tried with both Exodus wallet and Metamask.
https://connextscan.io/tx/0xfa490eea9f7a8da911f948da66da9843e3c46d9e380f85c39ce1c016a6c5c3cc

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1195063888773926915/1195065359422717972

**Comment by just-a-node** [comment]
Bumped on their behalf. Wallet issues are not reproducible, likely user env related. Closing out.
