### ISSUE TITLE
[Reliability review] Relayer fees are too high

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5541]
## Background

From feedback recently my Ministro
> Tere are many cases where the relayer fee has been excessive. He’s afraid most of the cases are forgotten
> Seeing lots of relayer fee issues even between L2s. 
> ex/ This user bridged Arbitrum to Optimism and he paid $50 and he hasn’t received a good answer. Had another $18 from optimsm to binance chain
> - https://discord.com/channels/454734546869551114/1171878046253465610/1171878870241263637

I'm very concerned that this is actually impacting our pricing and volumes and we dont know it 

## Analysis
We see sporadic results
- We can look at relayerFee quotes plotted against time, compare with actual gas prices, and implement an anomaly detection scheme to determine how often our quotes are totally off.
    - This is something we can build into a data pipeline
    Quoted relayerFee for transfers with Ethereum as destination chain
    Gas prices on Ethereum in the same period
- % anomalous estimates by destination chain
    - at 30% deviation threshold
        - ETH: 10.02%
        - BNB: 16.87%
        - Arb: 10.81%
        - Op: 1.88%
        - Poly: 22.11%
    - at 50% deviation threshold
        - ETH: 6.79%
        - BNB: 12.79%
        - Arb: 6.95%
        - Op: 1.32%
        - Poly: 14.54%
## Tasks
Next steps:
- Dig into:
    - 1) transactions with 0 relayer fee → unable to repro
    - 2) reproduce / look into specific bad transfers (like the socket one thru MM) → unable to repro
    - 3) close out some of the current reliability bugs
    - later) relayer fee calculation (calldata size, gas price oracle, conversion rates, gelato API consistency)
    - later) set up archive logs on DD (probably want at least 1 month of lookup)

**Comment by alexwhte** [comment]
user is saying the issue is optimism origin
from convo this would just be a conversion rate bug if truly based on origin chain

**Comment by alexwhte** [comment]
next thing to look at is how can we optimize the relayer fee function
may be less necessary with V2?

**Comment by par94** [comment]
https://lookerstudio.google.com/u/0/reporting/3f9ca497-05b3-4a97-a623-9a776917b579/page/p_oa9ycsgsfd/edit?pli=1

**Comment by alexwhte** [comment]
keeping open for a full fix
