### ISSUE TITLE
[ST] Optimism to Arbitrum path - Routers online but not bidding the route

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5543]
**Describe the bug**
The following txn didn't receive any bids and it's going through the slow path but there are 3 routers with more than enough liquidity to support a fast path route.

https://connextscan.io/tx/0xa7fc01529c646d8a6f8ff35dd70517d54d3c926d634ad41104a0bb8a2cd601a9?source=search

<img width="1504" alt="image" src="https://github.com/connext/monorepo/assets/26097731/e9ca2eec-941d-4361-ab5e-cc7039fa7192">

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/e520a89c-1ed5-4cb7-a101-f1a89f7950e9">

Routers:

1. https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4 (last txn from Op was 4 days ago)
2. https://connextscan.io/router/0xc4ae07f276768a3b74ae8c47bc108a2af0e40eba (last op-arb txn was 8 days ago and last txn from OP 7 days ago)
3. https://connextscan.io/router/0x49a9e7ec76bc8fdf658d09557305170d9f01d2fa (last txn was 2 days ago, seems offline)

**Link to the ticket in discord**

https://discord.com/channels/454734546869551114/1195509484857077760

@oncall

**Comment by just-a-node** [comment]
Will deal with as part of the larger 'routers not bidding' bug.
