### ISSUE TITLE
[Testnet-Prod] LH propose didn't propose the aggregate root for about 3 days

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#5545]
## Problem

The last propose tx:
https://goerli.etherscan.io/tx/0xd7dfab89df036297b9851bf6b82ee885dab6b9418a1335a0a409a8c7e3d5e4c1

No propose happened for about 3 days after the above one.

**Comment by preethamr** [comment]
Testnet-prod is not in op-mode

**Comment by preethamr** [comment]
Resolved by change LH Propose frequency to every 15 minutes.
