### ISSUE TITLE
[ST] [testnet] Goerli to Optimism tx errors

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5554]
**Describe the bug**
A goerli to optimism goerli transaction has been going on for 18 hours. https://testnet.connextscan.io/tx/0xdd2e72721a0a8c18a07fdda1c694b9895c4f6ef3007c1e46ff2583accec20616
Earlier today, it showed a LowRelayerFee error, but now the error disappeared and it looks like the transaction is still pending. Could this be due to a subgraph issue on the receiver side?

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1196839605689925713/1196840167311421451

**Comment by preethamr** [comment]
QAing the fix:
https://github.com/connext/monorepo/commit/93685905f019e06fafdcffc1ac5101a52860eb84

**Comment by prathmeshkhandelwal1** [comment]
Closing this out as tx got resolved
