### ISSUE TITLE
[ST] Could not detect network error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5555]
**Describe the bug**
A user is unable to bridge from Polygon to Gnosis (https://bridge.connext.network/USDC-from-polygon-to-gnosis) due to the site giving a "Could not detect network" error. They tried restarting the browser, clearing cache and cookies, but it didn't work.
Setup: Metamask, Chrome (119.0.0.0), OS X 10.15.7

**Link to ticket in discord**
Ticket on Intercom

**Comment by Tommy-R8** [comment]
Another instance of the issue: https://discord.com/channels/454734546869551114/1197016108935430144/1197016521847877632

**Comment by pjenviri** [comment]
it looks like the RPC endpoint configured in user's metamask doesn't work properly?

**Comment by Tommy-R8** [comment]
The first user was asked to switch RPCs and it didn't work

**Comment by just-a-node** [comment]
Still seeing instances of this:

<img width="465" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFZUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bec4047910ad007bd9bde3ed7cc96af05d70b636/image.png" alt="image.png" />

**Comment by just-a-node** [comment]
This may be the same issue as #6041 - if so, we can close this as dupe. @regexpressyourself please help me verify if that's the case.

**Comment by just-a-node** [comment]
Closing along with #6041.
