### ISSUE TITLE
[ST] Delegate is a SAFE multisig

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5559]
**Describe the bug**

<img width="1766" alt="image" src="https://github.com/connext/monorepo/assets/26097731/c5af6d79-83c8-40ad-93bd-a90889d380c6">

The estimated slippage in this case is around 0.51% but the delegate address is a SAFE multisig. Is there any way to update the slippage or he should force to receive nextUSDT?. (in this case, we need the parameters to do it)

https://connextscan.io/tx/0x4e70e2b631b41d1977d5789e48e1f04c64e920182ed777012cd613f17ecb1437

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1197581975658180628

@oncall

**Comment by prathmeshkhandelwal1** [comment]
Transaction went through. Closing this out
