### ISSUE TITLE
[ST] Unable to update slippage

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5563]
**Describe the bug**
A user is unable to update the slippage of a LiFi transaction because the UI says that the address is not the delegate.
https://connextscan.io/tx/0x3ebec56b91025ed41a41cb446fc9ff200705255f6f23f3e314df74cb53554618
What's the delegate in this transaction?

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1198020959467229304/1198021192364347413

**Comment by Tommy-R8** [comment]
The UI is bugged. The user is connected with the delegate address but it still says "must update with delegate"
https://discord.com/channels/454734546869551114/1198020959467229304/1198275433951657994

**Comment by Tommy-R8** [comment]
Another transaction by the same user has the same issue https://connextscan.io/tx/0x3cbfbcced153a0d4ed6f5b6c2bdc67eade4f2a4b5948d9943ce2235e7d2ac4bc

**Comment by pjenviri** [comment]
I don’t think UI can’t do much for this scenario. It doesn’t the one who set error status or determine  whether to continue processing transaction when the slippage is added or good to proceed. The transfer (& error) status is obtained from the SDK.

**Comment by ValerywArz** [comment]
most likely that's the same issue (as I see slippage % is the same): https://connextscan.io/tx/0xb0b9b2483ddae35da2efc6354e67fd2b14477bde8e7b806b452a1c5dabc2c3db
User has transferred USDT from how wallet to exchange but can't update slippage
support ticket: https://discord.com/channels/454734546869551114/1199289393391878214

**Comment by preethamr** [comment]
> https://connextscan.io/tx/0x3ebec56b91025ed41a41cb446fc9ff200705255f6f23f3e314df74cb53554618
> What's the delegate in this transaction?

The issue here seems to be slippage, hence up to the user.
To answer the user:
https://discord.com/channels/454734546869551114/1198020959467229304/1199411343254638612

I have suggested:
https://discord.com/channels/454734546869551114/1198020959467229304/1199430853227462657

I have updated the transfer meta data to not retry for 30 days, as per user request.

**Comment by preethamr** [comment]
Resvoled
