### ISSUE TITLE
[ST] Polygon subgraph out of sync

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5564]
**Describe the bug**
Checked the bridge status in Connext and found that all routes related to Gonsis/Polygan were delayed.

![image](https://github.com/connext/monorepo/assets/92560156/f415b9bc-735b-4739-8485-d84fd72d4a28)

**Comment by QQHHUH** [comment]
Polygan:
https://polygonscan.com/tx/0x67b4c3fc917095f4d215e9494edd5f154a570d1eacc1dbf6da9314e30fa44101
https://polygonscan.com/tx/0x1d720251d49177acc4331b26b02db4e58272a1a256a04ec2b53cfc3cdcc3d800
https://polygonscan.com/tx/0x927deb3edeffdd4b0af042c30dae519d7e3acd1dab1aa559fefc6d8afcb81a33

These Tx ids cannot be queried on Connext scan!

**Comment by preethamr** [comment]
This issue is not in play anymore, and that route looks healthy now.
