### ISSUE TITLE
Add additional input params into SDK calls

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5569]
## Problem

Currently in SDK we calculate what slippage will be on origin and destination. We want to compare estimates with the slippage experienced by individual transfers. Current logs in SDK server come from UI calls but they’re not linked to any specific transfer. This task is to add the signer address and other input params to logs to help link transfers.

## Impact

This will help us decouple and link specific transfers with estimates calculated by the server.

## Proposed Solution

Add `signer` and any other input params that can help decouple transfers to the following SDK functions:
- `calculateAmountReceived`
- `estimateRelayerFee`
- `getActiveLiquidity` (used within `calculateAmountReceived`)

## Acceptance Criteria
- [ ] Get additional input params in the logs for the above functions
- [ ] Release SDK version

**Comment by prathmeshkhandelwal1** [comment]
I believe the way we are adding signers as optional param, We will be only covering the txs that are coming from connext bridge UI. And for that UI has to pass signer address that is connected as param in all those functions. If that is the case can we also send timestamp with all those functions which will can then help with linking the transfers given here in the issue: 
https://arc.net/l/quote/lsxdoape
cc: @just-a-node

**Comment by prathmeshkhandelwal1** [comment]
Going ahead with getting this released, But do need to discuss timestamp stuff for linking.

**Comment by just-a-node** [comment]
> I believe the way we are adding signers as optional param, We will be only covering the txs that are coming from connext bridge UI. And for that UI has to pass signer address that is connected as param in all those functions. If that is the case can we also send timestamp with all those functions which will can then help with linking the transfers given here in the issue: #5570 cc: @just-a-node 

We can only force the use of optional params on the UI anyways so this is expected. Basically we will have an easier time decoupling UI transactions from this change. Timestamps already exist in the server logs, no need to add them in the functions.

**Comment by just-a-node** [comment]
Reopening until we have NPM package available and the UI task done.

**Comment by prathmeshkhandelwal1** [comment]
Added the sdk-server into the UI

**Comment by just-a-node** [comment]
Want to update UIs to use this after we enable logs in #5612.

**Comment by prathmeshkhandelwal1** [comment]
Moving this in backlogs
