### ISSUE TITLE
[ST] Impossible to upgrade relayer fee

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#5574]
User is trying to upgrade fee (UI asks for 0 MATIC) but it doesn't help
tx: https://connextscan.io/tx/0x76b12839ccf6e3f6fd4915ed7f77ae3ced5a7c560c6523e3a338c79829ea9a29
![image](https://github.com/connext/monorepo/assets/93597601/3696182e-1379-46bb-b8fa-50a7901224a3)

support ticket: https://discord.com/channels/454734546869551114/1199363125904937000

**Comment by just-a-node** [comment]
The `needed` amount looks like it's priced in USD. Does sequencer do the conversion correctly, I wonder.

**Comment by just-a-node** [comment]
<img width="498" alt="image" src="https://github.com/connext/monorepo/assets/16638982/762564d9-2834-416c-9e66-b48bcf085e92">

Price of the transacting asset comes back as 0 here.

**Comment by wanglonghong** [comment]
It worked after a bump in native token. 

So the problem is that UI and Sequencer calculates the fee value differently if the fee token isn't supported by Gelato.
We also need to give an option to bump in origin native token in connextscan.
