### ISSUE TITLE
[ST] Slow path of 16+ hours

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5584]
**Describe the bug**
A transaction is taking its sweet time completing. https://connextscan.io/tx/0xd7a4ec68de9028858ccf5188f023c7f0fc4739b738b98e97705c982967939026

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1199689471579390043/1199690102906040392

**Comment by preethamr** [comment]
I have cleared the LH house cache.
Not yet sure, why this took this long.

**Comment by preethamr** [comment]
Resolved
