### ISSUE TITLE
[ST] Gnosis Chain slippage keeps increasing

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5591]
**Describe the bug**
A user bumped the slippage on a 10 USDC transaction to Gnosis Chain up to 90% and now it's still asking for 90.1%. The destination Pool has more than 2 million USDC and is very well balanced. This seems to be an issue with Gnosis Chain specifically, as it happened before (https://github.com/connext/monorepo/issues/5558).
Transaction: https://connextscan.io/tx/0xa2039a9560c2febc01c2b5cdde3fd29c6bda149ab1e25e1648aeeef78cb5ca66
![image](https://github.com/connext/monorepo/assets/84744304/ff1048c9-4557-4d35-9e59-77cc5c914b0c)

To keep bumping the slippage shouldn't really be a solution. Wouldn't this create an opportunity for an MEV bot to rekt a user?

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1200467684366745721/1200467757775466556

**Comment by preethamr** [comment]
Looks like this is resolved with no slippage:
<img width="1748" alt="image" src="https://github.com/connext/monorepo/assets/1195648/ea0454bc-4faa-4915-ad9e-f5d84d5529a0">
