### ISSUE TITLE
[ST] RADAR slow path to BSC 10+ hours

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5600]
**Describe the bug**
TX is stuck for a 10 hours, there's lack of liquidity on BSC side, but still extremely long slow path. 

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1201116451629699103

**Additional context**
https://connextscan.io/tx/0x98097fc8d85178168eec505351d63ff25c0ca3d409abc0a20b911bab9d144ead
@oncall

**Comment by prathmeshkhandelwal1** [comment]
No fast path liq available. Checked the logs. All looks okay. 
Not sure why its taking too long.

**Comment by prathmeshkhandelwal1** [comment]
Can see the last root received 1.5 hrs ago. Feels like its just slow. @preethamr do you have any idea?

**Comment by prathmeshkhandelwal1** [comment]
Resolved
