### ISSUE TITLE
[ST] sdk-server request error

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5604]
**Describe the bug**
![image](https://github.com/connext/monorepo/assets/84744304/1ddbef38-75c6-434d-819e-796eadde0b58)
Happening when trying to bridge from polygon

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/454734546869551116/1201540556518592553

**Comment by just-a-node** [comment]
Known issue in UI use of SDK. Rolled back.
