### ISSUE TITLE
Update all the error links to direct to intercom 

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#5610]
## Problem
UX improvements. Support through Discord is confusing: Low ART (average response time) of support to any bridge transaction issues, difficulties with clustering of tickets in Discord. No clear dashboard of Customer Support Performance. 

## Impact
It is important because now it is no clear metrics of Customer Support: neither ART (average response time), ATR (average ticket resolution) others
UX can be a unique advantage for the end user. Hardcore Labs HCL (LP): "Customer support is a real staff. The very complicated market for everybody except leaders."

## Proposed Solution
Change in all errors 

> To file a support request, please create a ticket on our discord here 

to this 

> Submit an Intercom ticket here

Link inserted in here:  https://www.connext.network/support

## Acceptance Criteria
H1 [error intercom button, bubble, Discord in menu]: if we create a button (or link) when an error occurs and save the bubble in the corner and Discord link in the menu then we collect 60% of tickets through Intercom (now it is 25%) and increase ART (average response time) by 10% in a month

**Comment by ekbainova** [comment]
Link: https://connext2.webflow.io/support

**Comment by alexwhte** [comment]
removing high... @ekbainova i think we can do this without eng help

**Comment by ekbainova** [comment]
@alexwhte the link is created. We are ready to move to Intercom.

**Comment by regexpressyourself** [comment]
https://github.com/connext/frontend/pull/59

**Comment by just-a-node** [comment]
Any way we can force an error from a transfer to test this?

**Comment by just-a-node** [comment]
@ekbainova https://frontend-connext-bridge-git-sm-sof-5610-0c568b-connext-979dc950.vercel.app

**Comment by regexpressyourself** [comment]
Deploy here: https://frontend-connext-bridge-git-sm-sof-5610-0c568b-connext-979dc950.vercel.app/

**Comment by regexpressyourself** [comment]
> Any way we can force an error from a transfer to test this?

I can push up a separate branch version that auto-errors if we want?

CC @just-a-node @ekbainova

**Comment by regexpressyourself** [comment]
@ekbainova You can see a test error message on this deploy: https://frontend-connext-bridge-3asn3wh4a-connext-979dc950.vercel.app/EZETH-from-ethereum-to-arbitrum?amount=1234

To trigger it, pair a wallet and enter an amount higher than your balance. I've replaced the "insufficient balance" error with a test error message that shows the format of the intercom link.

**Comment by ekbainova** [comment]
Works as expected.

**Comment by ekbainova** [comment]
Ready to merge @regexpressyourself

**Comment by ekbainova** [comment]
Do not forget about this error also: https://connextscan.io/tx/0xad6d30f95e461fa0e9f8384b58d95c84f2370da8ac29d9d46356b89796fbecbc

<img width="1583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2pJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd82a16655e99ecb5f91c63622cc23da981e85bf/image.png" alt="image.png" />

**Comment by regexpressyourself** [comment]
@ekbainova My bad! Just pushed an update for that one
