### ISSUE TITLE
[ST] Long slow path Ethereum to Gnosis

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5621]
**Describe the bug**
A transaction is taking more than 13 hours to complete through the slow path from Ethereum to Gnosis
https://connextscan.io/tx/0x829899dba38ecdc8859f53ee97186a5d1cdf39756d5cf1ba79086189db8a4fa2

**Link to ticket in discord**
Ticket 117 on Intercom

**Comment by just-a-node** [comment]
Unfortunately no longer have the logs for this one.
