### ISSUE TITLE
[TESTNET] Goerli destination not working for 6 days

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5626]
**Describe the bug**
Transactions going to Goerli haven't been completing since 6 days ago.
https://testnet.connextscan.io/tx/0x7a46f5c4fec5874a4f67ccf24e10134db52e70ca1546493059212e8db76457c1

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1202328672204488755/1202330691338252299

**Comment by just-a-node** [comment]
Probably due to Goerli deprecation - we'll be migrating Sepolia ASAP.
