### ISSUE TITLE
[ST] Perpetually increasing slippage tolerance

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5633]
**Describe the bug**
The bug described in #5591 happened to a user bridging from Ethereum to BNB, making them bump it up to 6% and now asking for 6.1% https://connextscan.io/tx/0x71c708c31c3eb2d1feb577707b6b0f790752de1816979fe66911851886a49fae

**Link to ticket in discord**
Ticket #123 on Intercom

**Comment by just-a-node** [comment]
Also resolved with the updated slippage at 6%. Asking for additional bumps is something we need to root cause. Filing new bug for that investigation
