### ISSUE TITLE
[ST] Bridge UI completion animation bugs

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5634]
**Describe the bug**
2 issues below:

1) After I see completion state. If I click away to a different tab and back, it restarts the animation 
https://www.awesomescreenshot.com/video/24573368?key=5e6aadc57c48f2478cc4a93f220cb2a1

2) Transfer showed completed state immediately in our UI before it had actually completed 
https://connextscan.io/tx/0xff40519244efca633d142ab64353b079cf1b6b8b13ed3ac14bbe5f63fe9cc49f
<img width="1155" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abfd36c67a67fde1f798ef1e2bab60b033f22039/image.png" alt="image.png" />

Steps to reproduce the behavior for 2:
1. Go to https://connext-bridge-mainnet-git-feat-config-coinhippo.vercel.app/DAI-from-arbitrum-to-gnosis?amount=30
2. Send DAI to gnosis
3. See almost immediate completion state in UI ("Car arrived at destination"), but it doesn't show this in the sidebar yet 
<img width="654" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f89b4bcfc80f0fe46089df4e56507171012cd67/image.png" alt="image.png" />

**Comment by just-a-node** [comment]
Fixed
