### ISSUE TITLE
Users continuously prompted to bump slippage

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#5635]
## Background

When slippage is too low, users are asked to bump. In some cases they are continuously asked to bump. Eventually these transfers resolve.

Issues like:
- https://github.com/connext/monorepo/issues/5633
- https://github.com/connext/monorepo/issues/5591

## Definition Of Done

Identify the root cause for this behavior.

## Tasks

- [ ] RCA

**Comment by Tommy-R8** [comment]
Another case: https://connextscan.io/tx/0xa1d8f56c78314e6396b7d97f2d3d62b4b691db619eb4d8f9969636f85517ec9f
https://discord.com/channels/454734546869551114/1213193419992727642/1213209406163124254

**Comment by Tommy-R8** [comment]
Another case: https://connextscan.io/tx/0xa33360ff489aba326f167ebf83171364b3e651e42a3e549bfd9108bb3d6a1c68
https://discord.com/channels/454734546869551114/1213747833132285983/1213748286683353128

**Comment by LayneHaber** [comment]
looking into these, seems to be happening around socket as well

**Comment by Tommy-R8** [comment]
Another transaction from Metamask
https://connextscan.io/tx/0x4feff0d9253b3d1be532b67c14ad187b3a4066e75d9d2d58f6753111b8f66291
https://discord.com/channels/454734546869551114/1215752449323696238/1215753118860574801
![image](https://github.com/connext/monorepo/assets/84744304/fe61afd6-90d2-4cb6-a2d0-fcadbc628892)

This transaction reconciled already so I don't understand why it's not completing

**Comment by preethamr** [comment]
https://discord.com/channels/992549151134982234/1032728270791262360/1215783179181359235

**Comment by preethamr** [comment]
To be root caused, needs further investigation

**Comment by Tommy-R8** [comment]
https://connextscan.io/tx/0x1a23759b7708b5266cc2d09f946194e459048b03c749fcb52f2cd9f2b6df7278
https://discord.com/channels/454734546869551114/1218016262454513764/1218208876537712671

**Comment by Tommy-R8** [comment]
https://connextscan.io/tx/0xf6ca8a0aac55fb53d12d032f044763a65724bc8266d943883be2e446d7ea16b8
https://discord.com/channels/454734546869551114/1218728740968992780/1218729892145926154

**Comment by 0xanedi** [comment]
Another case here: https://discord.com/channels/454734546869551114/1224602419992989767

https://connextscan.io/tx/0x14e5eca972bad9997e5b28f164547c61f7b3d4f055f8846ce625d16945109990

**Comment by alexwhte** [comment]
fixed
