### ISSUE TITLE
[ST] Gnosis router is down

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5636]
Down since jan 21

Dk | karpatkey, [Feb 1, 2024 at 10:48:15 AM]:
@alexblanq  please!

this is the image id: sha-4fb5d1e

providing logs separate

**Comment by alexwhte** [comment]
https://connextscan.io/router/0x048a5ecc705c280b2248aeff88fd581abbeb8587

**Comment by just-a-node** [comment]
Router boosting transactions again.
