### ISSUE TITLE
[ST] Airdrop site "Event not found"

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5641]
**Describe the bug**
Users trying to claim the airdrop are getting the "Event not found" error despite their wallets being eligible.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1203187628682383371/1203194036819591219
https://discord.com/channels/454734546869551114/1203262501425250304/1203263576350134312
https://discord.com/channels/454734546869551114/1203284430823755827/1203285076452843621

**Comment by 0xanedi** [comment]
Users getting following message also. Probably related
![image](https://github.com/connext/monorepo/assets/89958919/e7f94b50-395e-402d-941c-6f3f2bef8a50)

**Comment by preethamr** [comment]
Tokensoft fixed, good to go on their end.

User needs to retry these
@Tommy-R8

**Comment by 0xanedi** [comment]
@preethamr there's some cases that are still getting "Event Not Found":
Examples:
https://discord.com/channels/454734546869551114/1205122360777383946/1205182378025418772
https://discord.com/channels/454734546869551114/1205147605001044072/1205147715596718181

**Comment by preethamr** [comment]
> @preethamr there's some cases that are still getting "Event Not Found": Examples: https://discord.com/channels/454734546869551114/1205122360777383946/1205182378025418772 https://discord.com/channels/454734546869551114/1205147605001044072/1205147715596718181

@0xanedi  Tokensoft pushed a fix for this.
Could you ask the users to retry ?

**Comment by 0xanedi** [comment]
Working now!
https://discord.com/channels/454734546869551114/1205122360777383946/1205687572400177222
