### ISSUE TITLE
[ST] "Params invalid" when trying to bump the slippage

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5645]
**Describe the bug**
The user has to bump the slippage but it says "params invalid" when he tries, seems that he has increased the slippage several times previously. https://arbiscan.io/address/0x29c63e01ad48728a0768bb575e3e2a5b867bd7de

https://connextscan.io/tx/0xe75e3b0fc8529e08fa010e65744728c26658bcc0b629f2f6f029b6a8386f0dca

![image](https://github.com/connext/monorepo/assets/26097731/f8cf6f7d-2a64-4491-8085-6dd6f6b7029c)

Btw, the estimation in the UI seems to be correct, I get the same result when simulating the swap in Arbitrum.

<img width="338" alt="image" src="https://github.com/connext/monorepo/assets/26097731/9a275663-b686-4e82-960b-23976644a3ad">

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1203723165457715230

**Additional context**
It could be related to: https://github.com/connext/monorepo/issues/5635 but I'm not sure because the estimation seems right (at least now, idk if was lower before the user report)

@oncall

**Comment by just-a-node** [comment]
Will continue to investigate the bump issues in 5635. Closing this out since the user's transfer completed.
