### ISSUE TITLE
Error transferring Gnosis to Metis (getReceiptsError)

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5647]
`getReceipts error: nonce too high: address 0xCE7e86725FA9Ef1F5Cd0F266Bf5d48AF1686f445, tx: 340288 state: 0
`
This error showed in the UI on a failed slow path transfer . I dont have a screenshot of the error anymore but the send button turned red and showed this text and asked me to file a ticket 

<img width="460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6be0bf33bcf4ed3af09b503a91c96d6afff08107/image.png" alt="image.png" />

**Comment by alexwhte** [comment]
I was sending 11.69 from gnosis to metis
it worked on my second try...

**Comment by just-a-node** [comment]
Unable to repro on my side
