### ISSUE TITLE
Incorrect fast/slow estimates and countdowns for users 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5648]
## Issue
We are showing buggy behavior with expected time to receive assets. I obvserved the below

**When transferring 11 USDC from Gnosis (more than exists in any router)**

1. in the initiatial estimate in Bridge UI entry pannel, it correctly showed me estimated time = <300mins (slow path)
2. I send the transfer
3.  i clicked into the explorer for that transfer and see the blue lightning bolt and "Pending boost" . However there is not enough liquidity for a router boost. We should be using the same logic as in step 1 above
4. In the car animation, the estimate countdown was 4 mins. It should be 300 mins
<img width="631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzRuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0fd5ea6049292f1a363cfd3ecba6f7bdba5083e/image.png" alt="image.png" />
so we set really bad expectations and didnt say why this is taking longer than expected here 
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca8c3756f250b269cfe550b3abd55f7c14faf313/image.png" alt="image.png" />

**When sending 11.99 from Optimism**

1. In the bridge UI entry it estimated 300 mins again (slow path)
2. This time the car animation countdown started at 2 hours, s it entered into the right slow path state
3. However it _switched_ to the fast path countdown instead - see At 1:18 in this video https://www.awesomescreenshot.com/video/24648086?key=6f7a85d759b1e3fcfe132388dafacbb8
4. It again showed pending boost in explorer

## Recommended changes
1. We should not even show a time estimate for slow path. Say this instead 
"Your funds are on the way! /n
Funds are taking our slow path as our router intent network could not boost your transfer. We estimate completion in less than 5 hours. Thank you for your patience."
2. Make sure we **never** show fast states for expected slow transfers. We need to make sure we are accounting for liquidity correctly in the a) car animation countdown b) explorer lightning bolt

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/CoinHippo-Labs/connext-bridge/pull/311

**Comment by alexwhte** [comment]
@prathmeshkhandelwal1 can you test and close if this is gtg

**Comment by prathmeshkhandelwal1** [comment]
Changes made -
according to recommended steps:
- Car animation in case of fast path:
![Screenshot 2024-02-12 at 7 56 26 PM](https://github.com/connext/monorepo/assets/56167998/0b318719-41c1-45a8-a8a0-357a37157986)
- Car animation in case of slow path:
![Screenshot 2024-02-12 at 8 01 25 PM](https://github.com/connext/monorepo/assets/56167998/1ec7e66f-9228-483b-9c74-aff6fe7a90b6)
Router speed boost icon in case of slow path:
![Screenshot 2024-02-12 at 7 57 08 PM](https://github.com/connext/monorepo/assets/56167998/8d05ae15-e8a2-4b7f-bf1d-844189cc50a8)
