### ISSUE TITLE
[ST] goLinea -> Poly Mumbai | Relayer not bumping.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5649]
**Describe the bug**
The user bumped relayer with additional fees a few times on Linea Goerli, the UI shows `Additional required relayer fee` is 0. TX is stuck for 48 hours.

**Additional context**
Lineascan: https://goerli.lineascan.build/tx/0x4398146d5535acd1d406afbe55843d09f104ae491f2a1811e4f7d5ca6892eda8
Connextscan: https://testnet.connextscan.io/tx/0xe00dfbf4039ff756ac346c02bd4c5229a2b55e09a146935db06b2f75132c9043

@oncall

**Comment by just-a-node** [comment]
It completed. Fee estimate on testnet is kinda jank right now.
