### ISSUE TITLE
Migrate to Sepolia

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5670]
## Background

Our Testnet environment is borked, `goerli` is RIP

We need to setup a Sepolia testnet environment, supporting chains we want in the testnet. 

### Linked Issues & Documentation

We need a working testnet env, to de-risk product development.

## Definition Of Done

Testnet is migrated to Sepolia

**Comment by preethamr** [comment]
Next steps move this to testnet-prod

**Comment by just-a-node** [comment]
Last task is to update docs.
