### ISSUE TITLE
Aquire Sepolia ETH

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#5671]
## Background

Acquire  Sepolia ETH into testnet deployer waller

## Impact
Needed to setup testnet migration

## Proposed Solution
Buy or faucet

## Acceptance Criteria
_From an end user perspective, the below criteria must be met to consider this done:_
- [ ] Testnet deployer has much (>10 ETH) Sepolia ETH

**Comment by alexwhte** [comment]
have to go on twitter or something

**Comment by liu-zhipeng** [comment]
https://grabteeth.xyz/
we can get 10 eth here

**Comment by preethamr** [comment]
Done
