### ISSUE TITLE
[ST] Metis -> ETH stuck for 10 hours.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5677]
**Describe the bug**
Looks like there's no liquidity on ETH side and slow path takes too long. 

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1205125094150774795

**Additional context**
https://connextscan.io/tx/0xc58fa9bc2f2dc4344b8ead1b62f0f57cc11685b708205c123bead74c471d89c3

@oncall

**Comment by prathmeshkhandelwal1** [comment]
Checked the logs, No Error there. Looking more

**Comment by prathmeshkhandelwal1** [comment]
Due to Router liq transaction went slow path( Completed now). Closing this as completed.
