### ISSUE TITLE
[ST] Slow path longer than expected

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5680]
**Describe the bug**

User sent WETH from Arbitrum to Polygon. Slow path is taking almost 6 hours when seems it should take 3 (check the screenshot below) (i know It should go through fast path, it was already reported [here](https://github.com/connext/monorepo/issues/4982#issuecomment-1934157387)).

<img width="960" alt="image" src="https://github.com/connext/monorepo/assets/26097731/9a9d84d8-e87f-4a65-aa43-ded709c8b85a">

<img width="960" alt="image" src="https://github.com/connext/monorepo/assets/26097731/822da592-bfb7-4421-ac07-5da3cc15523c">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1205144727813619744

**Additional context**
@oncall

**Comment by prathmeshkhandelwal1** [comment]
Tx resolved, Tagging @preethamr for checking why slow path is taking too long

**Comment by just-a-node** [comment]
6 hrs is within the expected window.
