### ISSUE TITLE
[ST] Airdrop Claim says Event not found please help

### ISSUE THREAD

**Issue by ninz420** [connext/monorepo#5685]
**after clicking the token it will say event not found**

**L
![received_1041796260455497](https://github.com/connext/monorepo/assets/159519012/4616a407-bd92-4968-b0b7-ee035707dc6b)
**

**To Reproduce**

**Screenshots**
![received_821067133041134](https://github.com/connext/monorepo/assets/159519012/44a0e568-c775-4399-b162-5c6ed55ee6a2)

**Additional context**
@oncall

**Comment by ninz420** [comment]
@sfoxdev 
@aandreakis

**Comment by ninz420** [comment]
@prathmeshkhandelwal1  can you help me?

**Comment by preethamr** [comment]
@ninz420 Tokensoft pushed a fix for this.
Could you ask the users to retry ?

**Comment by ninz420** [comment]
Thanks , I will update you

**Comment by ninz420** [comment]
> @ninz420 Tokensoft pushed a fix for this. Could you ask the users to retry ?

Still the same event not found after clicking token

**Comment by ninz420** [comment]
![Uploading received_961657775678384.png…]()

**Comment by ninz420** [comment]
Its okay now thanks, sending reports inawhile

**Comment by prathmeshkhandelwal1** [comment]
Hey @ninz420 , is it resolved yet?
