### ISSUE TITLE
[ST] Funds stuck on delegate addr - Gnosis

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5686]
**Describe the bug**
The user funds are stuck on delegate addr: https://gnosisscan.io/address/0x9c3b4677781f147f0020ab11d54fa78ce35176d2#tokentxns

**Connextscan**
https://connextscan.io/tx/0x048f648578d15f413bfb0878edba862960051f492ab0b0ffcc295b4f1463b1a4

@oncall

**Comment by prathmeshkhandelwal1** [comment]
I can see the target address and delegate addresses are same which is: `0x9c3b4677781f147f0020ab11d54fa78ce35176d2 `

**Comment by oswy-cpu** [comment]
@prathmeshkhandelwal1 can we do smth?

**Comment by prathmeshkhandelwal1** [comment]
![image](https://github.com/connext/monorepo/assets/56167998/e87caf2a-5c8f-40d8-ad33-4e233b005b30)

**Comment by prathmeshkhandelwal1** [comment]
> @prathmeshkhandelwal1 can we do smth?

smth?

**Comment by oswy-cpu** [comment]
> > @prathmeshkhandelwal1 can we do smth?
> 
> smth?

Can we withdraw funds for the user?

**Comment by prathmeshkhandelwal1** [comment]
Let me confirm with the team on next steps

**Comment by prathmeshkhandelwal1** [comment]
cc: @alexwhte

**Comment by prathmeshkhandelwal1** [comment]
![Screenshot 2024-02-19 at 8 02 03 PM](https://github.com/connext/monorepo/assets/56167998/fb9849a0-da0f-4ebc-baa6-baed350bdc00)
Hey @oswy-cpu , But I can not see any option of putting custom delegate and target address in UI.

**Comment by preethamr** [comment]
No action needed from us.
This has been passed to Kinetix team
We cannot reimburse in cases like this;
