### ISSUE TITLE
Tokensoft fixed, good to go on their end.

### ISSUE THREAD

**Issue by ninz420** [connext/monorepo#5687]
Tokensoft fixed, good to go on their end.

User needs to retry these
@Tommy-R8

_Originally posted by @preethamr in https://github.com/connext/monorepo/issues/5641#issuecomment-1933321647_

**Comment by ninz420** [comment]
@preethamr its still event not found , 
![received_1041796260455497](https://github.com/connext/monorepo/assets/159519012/b3a1d77f-41f3-4af2-aca1-e71d128f815e)
![received_821067133041134](https://github.com/connext/monorepo/assets/159519012/39775fd0-271f-4dc3-8e67-79c8bc5e28ac)

**Comment by prathmeshkhandelwal1** [comment]
Closing this out cause its similar to this? we will keep it track there. https://github.com/connext/monorepo/issues/5685
