### ISSUE TITLE
Mode chain support 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5689]
## Problem
Mode team wants to be a Defi hub 
https://docs.mode.network/introduction/introducing-mode
https://www.notion.so/connext/Mode-0ac06a4d0f724b9ab50cc732b712a327

## Impact
Expected volume growth
Also impact to RST leads. 
Aori has on their roadmap and is a key distribution partner 

## Proposed Solution
Launch to Mode 
- Op stack chain 
- Other prerequisites need validation 
## Acceptance Criteria
Prerequisites
- [ ]  Demonstrated message-passing ability on testnet (if possible) or manually via mainnet, as well as fuzz and unit-testing.
- [ ] High-qualty public and private RPCs
- [ ] High-quality explorer support
- [ ] Relayer support - Should pitch chains to get Gelato to support them
- [ ] Subgraph support  - Bware can run subgraphs if they/we need, for a cost

Launch 
- [ ] Fast transfers work L1 to L2 in bridge UI in <5min
- [ ] Fast transfers works L2 to L2 in bridge UI in <5min
- [ ] Slow transfers work L1 to L2 in bridge UI in <5hr
- [ ] Slow transfers works L2 to L2 in bridge UI in <5hr
- [ ] User can add and withdraw pools in UI
- [ ] User can swap in UI
- [ ] Exploer navigation works as expected

**Comment by alexwhte** [comment]
Redacted cartel has restaking token specifically asked for Mode chain

**Comment by just-a-node** [comment]
Handling this in #5706
