### ISSUE TITLE
Transfer of ETH to ARB not working

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5708]
Transfers of ETH to arbitrum not working

![Screenshot 2024-02-15 at 7 03 07 PM](https://github.com/connext/monorepo/assets/56167998/3cac6fb5-dff4-49f5-97a2-4c5acc896219)

**Comment by MinistroDolar** [comment]
Yeah i've an open ticket with this txn: (sending ETH from BNB Chain to Arb)

https://connextscan.io/tx/0x453b620812b51a6862f3388c81eb9a89c1c03816674ac0100c358caa0a072147

Reconcile still pending after 10 hours.

Ticket:
https://discord.com/channels/454734546869551114/1207666693359411220

**Comment by MinistroDolar** [comment]
Txns of WETH from Arbitrum seems failing too. Slow path is taking too long

Example:
https://connextscan.io/tx/0x2089fc90e840fc8f95e715990054925bd9a66ca24e095e2850c060b2c4a5629b

<img width="957" alt="image" src="https://github.com/connext/monorepo/assets/26097731/3e87bf76-2ffe-454a-8521-a57319f1291f">

<img width="959" alt="image" src="https://github.com/connext/monorepo/assets/26097731/7f583c76-754a-407a-a135-745fd2cb0031">

Ticket: https://discord.com/channels/454734546869551114/1207832878164086864

**Comment by just-a-node** [comment]
They completed but took a while. Recent transfers on this path have completed fast so closing it out.
