### ISSUE TITLE
[ST] Recommended slippage tolereance is 10% 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5709]
**Describe the bug**
ETH-nextETH BSC pool is at 9,31 ETH, the amount of trasnfer is 9,96 ETH. The UI suggests user to bump slipp to 10%, transaction have been stuck for 77 hours.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/74738120/6d677f2d-c89b-4243-92d8-00033950070e)

**Additional context**
https://connextscan.io/tx/0x3cd70026c1d11f2c5f80c124bec67860b32ef34e346465bc7fe1b1089702bee9
@oncall

**Comment by prathmeshkhandelwal1** [comment]
Slippage is due to lack of ETH liq.
Transferred amount: `9.961858442846171613 ` WETH
Amount in Pool to release: 9.32 WETH
![Screenshot 2024-02-15 at 8 15 36 PM](https://github.com/connext/monorepo/assets/56167998/be9e8354-b2c2-497e-8471-47edf22535b8)

**Comment by oswy-cpu** [comment]
@prathmeshkhandelwal1 I know, but what's the workaround for the user?

**Comment by alexwhte** [comment]
@oswy-cpu can you please link the ticket?

**Comment by oswy-cpu** [comment]
> @oswy-cpu can you please link the ticket?

https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/159?view=List

**Comment by oswy-cpu** [comment]
@alexwhte ^

**Comment by alexwhte** [comment]
@oswy-cpu thanks
We are working with our largest LP to deepen this BNB-ETH pool this week. I cant promise an ETA on it but we are putting pressure 

The alternative option is receiving local asset nextWETH and bridging that to arbitrum or gnosis or mainnet . That would give them the funds faster

**Comment by oswy-cpu** [comment]
Closing as completed

**Comment by oswy-cpu** [comment]
<img width="452" alt="image" src="https://github.com/connext/monorepo/assets/74738120/bb29fcf1-e73e-45b3-9282-de9b7edc9956">

@alexwhte any chance to help him? This is really crazy.

Also: 
<img width="590" alt="image" src="https://github.com/connext/monorepo/assets/74738120/81ed3bb4-ce9c-49ee-9d10-d6eb5a491d02">

**Comment by just-a-node** [comment]
Well, only the delegate can bump slippage and the slippage for that txn was set to 10%, so...

**Comment by just-a-node** [comment]
This was the delegate: `0x2a30c87e66ebce213fab2800fe120ad1e3b3fc67`. Does the user own this?

**Comment by preethamr** [comment]
Based on liquidity at the time
