### ISSUE TITLE
[ST] InfraSingularity router not working

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5710]
**Describe the bug**
Router 0x49a9e7ec76bc8fdf658d09557305170d9f01d2fa

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3hoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f7c08fee99262f8f963443e322a7654f57a5a83/telegram-cloud-photo-size-5-6228561753504071802-y.jpg" alt="telegram-cloud-photo-size-5-6228561753504071802-y.jpg" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3RoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24c1372681eb899f6a84645dcf3921b9c294b071/telegram-cloud-photo-size-5-6228561753504071803-y.jpg" alt="telegram-cloud-photo-size-5-6228561753504071803-y.jpg" />

This is our router version `ROUTER_VERSION=sha-9aa3ba4`

@oncall

**Comment by just-a-node** [comment]
Should resolve after updating their router based on new guide.

**Comment by preethamr** [comment]
Waiting in confirmation from 0x49a9e7ec76bc8fdf658d09557305170d9f01d2fa

**Comment by LayneHaber** [comment]
new router instructions sent, waiting for confirmation from operator
