### ISSUE TITLE
[ST] WETH fail from Gnosis to Base

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5714]
Error sending .002 WETH failed in our bridge UI 

getReceipts error: nonce too high: address 0x1B9430E7ab7cB6f9D3B33e14755302Fa1A3D8d85, tx: 95568 state: 0

Sending .02 WETH worked fine

**Comment by alexwhte** [comment]
Is this just too small of a transfer?

**Comment by prathmeshkhandelwal1** [comment]
Not able to repro, inited tx with 0.001 WETH
https://connextscan.io/tx/0x672dadd43ede6503f2dfc0288f20bc4aac9a86c4de7a9187d254bb8ffb7f8f75

**Comment by alexwhte** [comment]
@prathmeshkhandelwal1 this is the same ongoing uissue?

**Comment by preethamr** [comment]
Handle MM/wallet errors in a better way in the UI

**Comment by prathmeshkhandelwal1** [comment]
Closing this out as completed, Due to not able to repro, and also not being able to see many tickets on this issue
