### ISSUE TITLE
[ST] Shows received WETH but i got ETH (Base) 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5715]
**Describe the bug**
i sent WETH, and the UI (Bridge and connextscan) shows me sending and receiving WETH, but I received unwrapped ETH in my wallet 

https://connextscan-mainnet-git-feat-add-base-coinhippo.vercel.app/tx/0x53af99391404938bb5f688a30558c6cbf0af324fb78129b51ab86d9956a0bfb7

https://basescan.org//tx/0xaeb5daec822bcd50dd0eed4c2a3ffd607aa690fe41b435839686afee95ac91d2

**Comment by just-a-node** [comment]
Not able to repro. It's possible you sent the txn in this state (it defaults to ETH on dest):
<img width="151" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8748316280eaa300ebc40e005acebf4e9873bfb/image.png" alt="image.png" />

**Comment by prathmeshkhandelwal1** [comment]
Received right assets confirmed. 
Got ETH on selecting ETH and WETH on selecting WETH. 
Attaching both tx:
WETH: https://connextscan.io/tx/0xb11bd960e821ed5d32d8ee491ca22ec19902168ddd6bc54b9f645a709c15da4d
ETH: https://connextscan.io/tx/0x672dadd43ede6503f2dfc0288f20bc4aac9a86c4de7a9187d254bb8ffb7f8f75
