### ISSUE TITLE
[ST] Txns from BASE to BNB Chain/Linea pending or not getting bids.

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5720]
**Describe the bug**
Txns going from Base to BNB Chain/Linea are pending or not getting bids.

Example:

https://connextscan.io/tx/0x6a70fa8b473d2e54790353af63e1710988b03fe6eab04f1ba6da65f2c32b42b9?source=search

<img width="960" alt="image" src="https://github.com/connext/monorepo/assets/26097731/1d4386d6-519b-4ccd-b47f-f2fe2574aa10">

<img width="960" alt="image" src="https://github.com/connext/monorepo/assets/26097731/b350b8f0-5346-4fc3-b854-0d7a7ff06786">

All of them seems initiated through Li.Fi!

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1208045501455532045

@oncall

**Comment by prathmeshkhandelwal1** [comment]
Seems like only connext router `0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c` is trying to bid on it. And it doesnt have liq for these tokens. @preethamr

**Comment by Tommy-R8** [comment]
Another transaction from LiFi but in inverse order: https://connextscan.io/tx/0xa9b750a0a1810496478bfda7cbefb4b981f781e469bb859133ce26703cb9d148

Ticket 166 on Intercom

**Comment by just-a-node** [comment]
Hopefully resolved when routers update based on new instructions
