### ISSUE TITLE
[ST] <Linea transfers to Base are stuck>

### ISSUE THREAD

**Issue by A-Keyboard** [connext/monorepo#5722]
**Describe the bug**
Linea transfers to Base are stuck

**To Reproduce**
Connextscan transfers from Linea to Base:
1. https://connextscan .io/tx/0xf4d946dc7c31bbcbaf925793ec17f8c4e47d6b8911b556e6ad2449b55f0f6801
2. https://connextscan.io/tx/0x5019b0731b987c3f939a31fba846ed72c01bf04dcb3f32a4638dca0c997de87f
3. https://connextscan.io/tx/0x3f67ff211f9590cd0613d22c673c36237f7971a90f743349dbc02fdddbb1a3f0

@oncall

**Comment by prathmeshkhandelwal1** [comment]
Transactions here are stucking due to router not bidding @preethamr

**Comment by just-a-node** [comment]
Unstuck.
