### ISSUE TITLE
Metis <-> Base routes not getting filled by Routers in either direciotn

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5725]
these should be fast path
Other routes to Base are coreclty going fast path

https://connextscan.io/tx/0xad1524bc351b9b6860eec2629a7dc5d0a116f13208f49f3bcb89c19c74856344
https://connextscan.io/tx/0x51f40ccc0e41db38edc817352ef9396a07bc6e80f87f9954bd8a518df79edc2f

**Comment by preethamr** [comment]
This is solved after the router updates
