### ISSUE TITLE
[ST] UI showing wrong ETA

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5730]
When trying to bridge 3 ETH from Mainnet to Arbitrum (as an example) it shows an ETA lower than 4 minutes when router liquidity is lower than 1 ETH (the only router with more than 3 eth is not active: https://connextscan.io/router/0x49a9e7ec76bc8fdf658d09557305170d9f01d2fa)

<img width="416" alt="image" src="https://github.com/connext/monorepo/assets/26097731/85df121f-1845-4874-883d-5d0c0243fc50">

<img width="961" alt="image" src="https://github.com/connext/monorepo/assets/26097731/04cfaed9-29a2-45f8-a97c-0e5e7eff0dc3">

**Additional context**
I don't understand why the fast liquidity for ETH is so low on Arbitrum being that 7 hours ago it passed a 13 ETH tx with no issues.

<img width="1879" alt="image" src="https://github.com/connext/monorepo/assets/26097731/02567ac2-810c-4e9c-8ff0-07973cc29555">

@oncall

**Comment by just-a-node** [comment]
Expected behavior. The estimation logic cannot tell if a router is 'actively bidding', only if there's sufficient liquidity. We can add some better heuristics to take historical activity into account but currently that information doesn't make its way into the estimation. 

Fast liq could be low if previous transfers haven't been reconciled yet.

**Comment by just-a-node** [comment]
Pls close this out if that answered your questions, otherwise happy to follow up here.

**Comment by MinistroDolar** [comment]
> Expected behavior. The estimation logic cannot tell if a router is 'actively bidding', only if there's sufficient liquidity. We can add some better heuristics to take historical activity into account but currently that information doesn't make its way into the estimation.
> 
> Fast liq could be low if previous transfers haven't been reconciled yet.

I understand it would be ideal to be able to incorporate more information into the estimate since users get too frustrated when the estimate differs between a few minutes and 5 hours (aka, ticket: https://discord.com/channels/454734546869551114/1209217534373531718).

As for the low liquidity, it seems that indeed the reconcile is taking quite some time.
