### ISSUE TITLE
slow path is taking too long

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#5733]
User has transferred nextAlETH and nextAlUSD from Optimism to ETH but transfers are processing for longer than 10 hours

https://connextscan.io/tx/0x3147bbfcca45192fec9e21542acd7935baaba0b5f355ad2d6348b973fa529e00
https://connextscan.io/tx/0x9c53e250307388caa0a7a40400ecbb46ab567b315ba4e01c3e29c6f068c176fa

Ticket: https://discord.com/channels/454734546869551114/1209854275044507719

**Comment by ValerywArz** [comment]
Completed in 11:05 and 10:48

**Comment by alexwhte** [comment]
old issue, closing for now
