### ISSUE TITLE
[ST] Relayer fee bump isn't working 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5750]
**Describe the bug**
https://connextscan.io/tx/0x53739eba4890289a7da4fea06ec74c9773a154632c37b757e3a15b7c758a6077

The user bumped TX three times, nothing helps. New relayer fee in scan: 0 NEXT. 

**Screenshots**
<img width="421" alt="image" src="https://github.com/connext/monorepo/assets/74738120/7c1ee2ef-407f-4927-95e4-a80b516c57be">

@oncall

**Comment by wanglonghong** [comment]
The tx went through after a bump in a native token but also noted that NEXT token fee calculation seems a little bit off.
