### ISSUE TITLE
[ST] Transaction reverted without a reason

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5758]
**Describe the bug**
A user is trying to bridge NEXT from Ethereum to Arbitrum and after approving gets this error
![image](https://github.com/connext/monorepo/assets/84744304/6e5876f9-7db6-412e-8250-9d6279572c32)

I wasn't able to reproduce. Deleting the decimals doesn't fix it. The user also tried with just 1 NEXT and got the same error.

Ticket 195 on Intercom

**Comment by alexwhte** [comment]
old issue, closing for cleanup
