### ISSUE TITLE
[ST] Metis and Base transactions No Bids Received

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5769]
**Describe the bug**
Transactions involving Metis and Base are not getting bids despite there being a lot of liquidity on both.
![image](https://github.com/connext/monorepo/assets/84744304/ae98880c-393d-427d-a8a5-0009e480bec2)

Example tx: https://connextscan.io/tx/0x828346b73797f49189332b90aac193757d9510f570d90c38547a6d9139ee0f63
Router with 100+ WETH on Base: https://connextscan.io/router/0x6fd84ba95525c4ccd218f2f16f646a08b4b0a598
![image](https://github.com/connext/monorepo/assets/84744304/0f7c5c2f-f64b-4947-b469-a356abd5c59b)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1212114342237962250/1212115645039124550

**Comment by Tommy-R8** [comment]
Another transaction: https://discord.com/channels/454734546869551114/1212115837276913705/1212117817227477022
https://connextscan.io/tx/0x29608fec53f32f21ddcece152b0c533ee74e0c6212abd14ed3aef20b7d0651c0

**Comment by MinistroDolar** [comment]
Another one:

https://connextscan.io/tx/0xd1387e4e49a4b5f061efe069ca1b9b779275301c6d68ba08d976a3e51da767f2

**Comment by LayneHaber** [comment]
closing, stale
