### ISSUE TITLE
WalletConnect should easily connect with Safe multisigs

### ISSUE THREAD

**Issue by A-Keyboard** [connext/monorepo#5785]
## Problem

From 1kx: Most people are already familiar having to use WC to connect a safe, so I would make sure that the connection via WC also works...(the safe connection was a WC link in the end anyway, so I don't get why direct WC connection didn't work)

## Impact

Most Safe multisig owners are using Wallet Connect directly, delaying the process or making it difficult  will cause users to give up on initiating transfers

## Proposed Solution

Fix or Integrate WC with Safe properly

**Comment by just-a-node** [comment]
Handling in #5974
