### ISSUE TITLE
[ST] UI requesting successive bumps

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5797]
**Describe the bug**
Txn: https://connextscan.io/tx/0x17c1aadb4c13798b1660892d60089ffcec581eed765f08a31be9a1602b480109

User already bumped the slippage once (it asked for 0.53%): https://basescan.org/tx/0xbe892b955f5ba10d5c750e3ade691d33659c98a85c499984230bc888a5f10618

But now it's asking for 0.63%

<img width="291" alt="image" src="https://github.com/connext/monorepo/assets/26097731/f91820f8-261a-4278-a163-b040e31aa419">

The main issue is that asking the user to bump this again takes him to pay $2 on just over $6 bridged to bump the slippage (without the guarantee that it will work, the first time it seems that the delay impacting our system caused more transactions to enter in the middle and worsened the situation)

Also it is not a great UX being requested 2 times to do the same thing.

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1212808986106269806

**Additional context**
@oncall

**Comment by ekbainova** [comment]
https://app.zenhub.com/workspaces/integrations-engineering-6536ae0de1eacd002199c371/issues/gh/connext/monorepo/5953
