### ISSUE TITLE
[ST] Linea receiver failed transact to destination wallets

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5800]
**Describe the bug**
Looks like something reverts internal transaction to send eth to destination addresses on this receiver: https://lineascan.build/address/0xc10d6962bff9516ec1584d334a482f36af98b191#internaltx

**Link to ticket in discord**
[Click](https://discord.com/channels/454734546869551114/1212938163694211092)

**Additional context**
One of affected txs: https://connextscan.io/tx/0xfc543633319aaec1971185dad348f47d8d41a29e93cf1ac732b4d8032fa36e1c
@oncall

**Comment by MinistroDolar** [comment]
Another reported txn:

https://connextscan.io/tx/0xc5dfa7483d05a50e70671963675cc43d5cee1b109b5198082d4a8fcfcdb8058e

https://lineascan.build/tx/0x81c0c374248bbdef97c5a714af8bb9a6a62a83d03d88f69047276d40c4e64be3

Seems it's li.fi related.

Ticket: 

https://discord.com/channels/454734546869551114/1213128580142211112

**Comment by LayneHaber** [comment]
digging into receiver implementation.

**Comment by LayneHaber** [comment]
the receiver seems to be reverting with `UnAuthorized`. [Source](https://lineascan.build/address/0xc10d6962bff9516ec1584d334a482f36af98b191).

and the amarok router is not set (see attached images):
<img width="1571" alt="Screenshot 2024-03-01 at 12 02 40 PM" src="https://github.com/connext/monorepo/assets/12769011/187a939d-8a80-47be-9459-b58c0f25c693">

<img width="1551" alt="Screenshot 2024-03-01 at 12 03 02 PM" src="https://github.com/connext/monorepo/assets/12769011/76edcfa2-8f7f-49ef-90e9-9d44bd832b47">

**Comment by LayneHaber** [comment]
lifi reimbursed and fixed, closing
