### ISSUE TITLE
[ST] <Users cannot manually update slippage>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5803]
**Describe the bug**
Users cannot manually update slippage

**Link to ticket in discord**
DC ：https://discord.com/channels/454734546869551114/1213059139899752458/1213059144660164678
Link:  https://connextscan.io/tx/0x64bd618d23ec9309fc1e47e6090cf5b4ad4fc23d5c0f961cfe5944fc9b4b652e

**Screenshots**

![image](https://github.com/connext/monorepo/assets/92560156/5cc0c688-d523-4f2a-9aa9-eb30dd8c6dc5)

@oncall

**Comment by QQHHUH** [comment]
Same problem here   
DC ：https://discord.com/channels/454734546869551114/1213059371895099402/1213059376429146163

TX  ：https://connextscan.io/tx/0xe268c758432f145189966ce1b1379b760f460b3c79ed0fcd88c279ccfad6ca30

**Comment by LayneHaber** [comment]
stale, closing
