### ISSUE TITLE
[ST] Linea router not bidding

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5809]
**Describe the bug**
This USDC tx from Gnosis to Linea is not getting bids. https://connextscan.io/tx/0x81d9847e1547df827fd2d4c63ce16077e671487b372f22fce71ec65f27672e4d
Could it be because this router doesn't have Gnosis in their config? https://connextscan.io/router/0x58507fed0cb11723dfb6848c92c59cf0bbeb9927

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1213536850526867507/1213537203729342564

**Comment by LayneHaber** [comment]
resolved in slow path, router updates have been pushed. going to close this
