### ISSUE TITLE
[ICE: 315] iOS user unable to connect wallet

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5810]
**Describe the bug**
A user on iOS is unable to connect their wallet to the bridge site. They tried Metamask, Trust, OKX wallet, and also different browsers.
On Metamask, this error shows up:
![image](https://github.com/connext/monorepo/assets/84744304/5e192030-96a0-48b0-b088-567261644b03)
The error doesn't go away after clearing cache and cookies.
Trust wallet meanwhile stays like this:
![image](https://github.com/connext/monorepo/assets/84744304/89481d8f-8225-4ccd-a8f4-efff9dfb56fa)

Ticket 216 on Intercom

**Comment by ekbainova** [comment]
@just-a-node For Chrome/Safari it works with Metamask. Do we still have this problem?

**Comment by just-a-node** [comment]
I don't think we have any new issues about this. Plus, mobile compatibility is something we need to specifically design for later.
