### ISSUE TITLE
[ST] Poly Mumbai -> Linea Testnet transfer stuck for 200 hours

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5813]
**Describe the bug**
https://testnet.connextscan.io/tx/0xc35344f8645f58c4d763600efdddc2a398a8baec692be23179f1245650998bc2

@oncall

**Comment by LayneHaber** [comment]
prod testnet still connected to goerli, up time and reliability is variable there as it is in the middle of being deprecated.

waiting for some downstream dependencies to upgrade before we can make the cutover
