### ISSUE TITLE
[ST] nextAlUSD -> ETH L1 AlUSD tx takes 19hours.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5814]
**Describe the bug**
Next implementation of Alchemix USD from Arb to Mainnet takes already 19 hours and not yet complete. Is there something wrong with canonical bridge?

TX: https://connextscan.io/tx/0x4fdd800d933ce4d9374a0c5cbb36e95d827b0b85aec6216a5939a125c65ae593

**Additional context**
There's not enough native AlUSD on L1 (16k), tx value ~18k

@oncall

**Comment by LayneHaber** [comment]
resolved, closing
