### ISSUE TITLE
Higher slippage 

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#5815]
**Describe the bug**
Over the past two days, we've experienced higher slippage than the default of 0.5%. Now is status of LowSlippage has 13 transfers 
We have a request from Socket about the reason. 

"seeing this become a big enough problem on our end that we would love your thoughts on"
"It’s already at 5% and I don’t really want the user to continue bumping excessively"

https://connextscan.io/tx/0xba66a2097c61a451568b95492e11e3ecd5c6d53177e023fee3eea12dd1ed465a
https://connextscan.io/tx/0x92ccb4b266095af9aaac26ce8600f2454ce3077464aa08ea4e768aba7079f94a

**Screenshots**
![telegram-cloud-photo-size-5-6280482281705552840-y](https://github.com/connext/monorepo/assets/18751995/6da4bd49-c2fe-4f57-8bec-bc6ed7a917e6)

**Comment by prathmeshkhandelwal1** [comment]
https://connextscan.io/tx/0x92ccb4b266095af9aaac26ce8600f2454ce3077464aa08ea4e768aba7079f94a
this one needs to be bumped. Other tx is cleared
