### ISSUE TITLE
[ST]After the user manually updated the slippage, the transaction was still Stuck.

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5816]
**Describe the bug**
Users cannot manually update slippage

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1214168327518162995/1214168331616256020
Tx ID:https://connextscan.io/tx/0x92ccb4b266095af9aaac26ce8600f2454ce3077464aa08ea4e768aba7079f94a
https://optimistic.etherscan.io/tx/0x92ccb4b266095af9aaac26ce8600f2454ce3077464aa08ea4e768aba7079f94a
**Screenshots**
![image](https://github.com/connext/monorepo/assets/92560156/38bbac05-f4af-4045-bd1e-9a387a347fad)

@oncall

**Comment by LayneHaber** [comment]
resolved, closing
