### ISSUE TITLE
[ST] ezETH slowpath taking too long

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5826]
**Describe the bug**
There is a 209 ezETH transaction that has not been executed via slow path for more than 11 hours. 

https://connextscan.io/tx/0x274216303773183929aa6271a8f1695350a2769571530c7930b2767089708dce

<img width="946" alt="image" src="https://github.com/connext/monorepo/assets/26097731/c4422784-686a-4d11-b63a-5882736b1516">

I report it since the average execution time seems to be less lower than that.

<img width="937" alt="image" src="https://github.com/connext/monorepo/assets/26097731/252999c2-9fed-41c4-948c-d5638b29e69d">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1216098831133839400

@oncall

**Comment by preethamr** [comment]
```cast call 0x397aeeedd44f40326f9eb583a1dfb8a7a673c40b  "leaves(bytes32) (address)" 0xfd622f61aa0dbb07780b2b83f9a15a028e095861081df3dd73e11ee0df8e0811  --rpc-url https://mainnet.mode.network/
0x0000000000000000000000000000000000000002```

The message is proven, and processed on chain, but subgraph not saying it is reconciled

**Comment by preethamr** [comment]
The message is proven, and processed on chain, but subgraph not saying it is reconciled

**Comment by MinistroDolar** [comment]
> The message is proven, and processed on chain, but subgraph not saying it is reconciled

Hey! Do you have any update on this?

**Comment by LayneHaber** [comment]
wip

**Comment by LayneHaber** [comment]
resolved, closing
