### ISSUE TITLE
[ST] ezETH bridge choosing Ethereum destination by itself

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5842]
**Describe the bug**
A user tried to bridge ezETH from Ethereum mainnet to Blast. They instead started a transaction with Ethereum destination. They used our bridge UI and are positive that Blast network was chosen correctly.
https://connextscan.io/tx/0x4a5a090b2041bba7886937de7784e21fe8a8f94a3874c406a353032390d6f0fc

Same case as https://github.com/connext/monorepo/issues/5825

![image](https://github.com/connext/monorepo/assets/84744304/91acd546-a87e-4628-9e68-c596daa29dac)

To make matters worse, the destination relayer fee is still not shown on the main UI so the user got an unexpected $100 fee.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1217308845597134859/1217308929885864007

**Comment by Tommy-R8** [comment]
Another case of the issue:
https://discord.com/channels/454734546869551114/1217314487644717187/1217314578506059797

**Comment by just-a-node** [comment]
Arb -> Blast should not be possible. If a user tried to do this, the UI automatically routes the destination to ETH.

**Comment by just-a-node** [comment]
Fix was deployed to explicitly disable any origin chain other than Ethereum when bridging to Blast.
