### ISSUE TITLE
[ST] Routers on Metis are not bidding

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5848]
**Describe the bug**
200 USDC tx - https://connextscan.io/tx/0x3fe4dffbb166867353e8ba83608285ac8d8a46b4dbb8f6cfa95c2f6e29764f03

None of routers are bidding for this for some reason.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1217754268971434047

@oncall

**Comment by LayneHaber** [comment]
due to metis rpc / subgraph issues, should be resolved. closing
