### ISSUE TITLE
[ST] Metis transfer missing on Connextscan

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5851]
**Describe the bug**
A USDT transaction from Metis to Polygon can't be found on Connextscan
https://andromeda-explorer.metis.io/tx/0xef20d282ade97521ce015f9bf4e0cd1110c8084c4a7aaeaf66f7f917ea27674a
User address: 0x73B41FAfc67fbee0Afd35EAEAba76e7468083f07

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1218016262454513764/1218017013012762676

**Comment by oswy-cpu** [comment]
One more here

USDC transfer from Metis
https://andromeda-explorer.metis.io/tx/0x96f08f7c1778e9fe365650ffdfc280a1e27a45adbd99a914c129a1de60cd9d26

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1218065990592626770

**Comment by oswy-cpu** [comment]
+1 

WETH
https://andromeda-explorer.metis.io/tx/0x410896fd00f07c7deae8f1f10f5f217ab17281600796a76dbdbbc56da1237bb4

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1218112377946505228

**Comment by LayneHaber** [comment]
due to metis issues, should be resolved for all transfers listed. closing.
