### ISSUE TITLE
[ST] Slow path to arb taking too long

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5853]
**Describe the bug**
1) ETH -> Arb1 (WETH -> nextWETH) | 288.74 ETH: https://connextscan.io/tx/0x8ebe8a5d5cf7594004ebe3b4604aae911761e6a87d36a513cfa199ca29b71acc stuck for 6 hours

2) ETH -> Arb1 (ezETH) | 566.94 ETH: 
https://connextscan.io/tx/0xbec41ec00cfc2b5c7851ab2fd39d166d27a1c3fa4c50b51e9ec65aa742c0bcd0 stuck for 6 hours

**Link to ticket in discord**
1) https://discord.com/channels/454734546869551114/1218112473882689616
2) https://discord.com/channels/454734546869551114/1218119441456562257

@oncall

**Comment by LayneHaber** [comment]
due to metis issues, should be resolved. closing.
