### ISSUE TITLE
[ST] BSC slow path takes 8+ hours

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5854]
**Describe the bug**
For some reason ETH->BSC ezETH tx stuck for 8+ hours:
https://connextscan.io/tx/0x220c26e1a4ec32a9d61c49ff8fe499ff7c73f0630218ba53af959d9c1cef88a2

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1218103860275449856

@oncall

**Comment by LayneHaber** [comment]
due to metis issues, should be resolved. closing.
