### ISSUE TITLE
[ST] <There is a problem with the Metis network and the bridge transaction hash cannot be displayed on the Connext scan.>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5858]
**Describe the bug**
There is a problem with the Metis network and the bridge transaction hash cannot be displayed on the Connext scan.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1218448723902730381/1218448727333802077

Connext Link:https://connextscan.io/tx/0x59ca3a79f638aa2915feef03352e0c74f8723c089aba6f8bdaf1c38e321ac884
wallet:0xB02fA29BFD054dB5514115533B6faC39DAc75391
From Metis>Polygan
**Screenshots**
![image](https://github.com/connext/monorepo/assets/92560156/f63363be-8781-4ef2-8b29-17b96e3781c9)

@oncall

**Comment by LayneHaber** [comment]
this is due to the subgraphs being behind, they should be syncing now.

this transfer appears. closing this
