### ISSUE TITLE
[ST] Missing Metis transaction

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5860]
**Describe the bug**
This transaction from Metis to Base is missing on Connextscan: https://explorer.metis.io/tx/0xd71c3ccd71105fd85606bc03dfc7a7be94125a79a927f73a518c07e09de46851

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1218605323015819450/1218614064649998387

**Comment by LayneHaber** [comment]
https://connextscan.io/tx/0xd71c3ccd71105fd85606bc03dfc7a7be94125a79a927f73a518c07e09de46851

should be present -- there was a gap in the subgraph metis transfers
