### ISSUE TITLE
Unexpected high slippage

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#5868]
UI showed to users positive slippage but they've received less amount than expected

1. https://connextscan.io/tx/0x9097925550e347e6a4dc83d776fdef902148ebcfcf3619ba44644cd6fde0916f — Polygon - Arbitrum 2.07 WETH - 2.06 aETH
Discord ticket: https://discord.com/channels/454734546869551114/1219353219440836718 (user made screenshot too late so UI doesn't show positive slippage already)

2. https://connextscan.io/tx/0x73d9c1dc6c0c7a6fbb557a133f72aed86f06dd6a454bf07c54d7c60005e07de8 — Polygon - Base 0.28812 WETH - 0.287287 WETH (UI showed 0.289431 ETH to receive)
Discord ticket with a screenshot of positive slippage: https://discord.com/channels/454734546869551114/1219352273201922138

3. https://connextscan.io/tx/0x382e4137ec58c2e8460d87996320e86cc1950d83a22594888e3d4b6773a3d440 — Polygon - Gnosis 1.2 WETH - 1.19 WETH

**Comment by MinistroDolar** [comment]
At the second case, he said that he set slippage at 0,05 but txn says 3% i think:

<img width="1044" alt="image" src="https://github.com/connext/monorepo/assets/26097731/233a12d5-6166-4a72-b47a-d0c74f9d4a50">

https://polygonscan.com/tx/0xa9e6aaf16bcaeee14d2aec1cc5deef1019437f4b9f3394775cd2cec59b5de65a

The other 2 guys also set 3% slippage tolerance:

https://polygonscan.com/tx/0x97afe18ed5648a09fcb1235e778744eb143cafa0f9c2c1f13542941411c63bdd

https://polygonscan.com/tx/0x382e4137ec58c2e8460d87996320e86cc1950d83a22594888e3d4b6773a3d440

We can't guarantee that the received amount will match what the UI showed at first.

**Comment by LayneHaber** [comment]
300 is 0.03% slippage tolerance (`raw_slippage / 10_000`)

we can't guarantee the slippage, only that the slippage tolerance is respected as the floor. users should specify a 0% slippage tolerance if they only want positive slippage, and then receive next assets otherwise.

unfortunately, I was not able to reproduce this and these are very moment-in-time dependent scenarios

**Comment by MinistroDolar** [comment]
> 300 is 0.03% slippage tolerance (`raw_slippage / 10_000`)
> 
> we can't guarantee the slippage, only that the slippage tolerance is respected as the floor. users should specify a 0% slippage tolerance if they only want positive slippage, and then receive next assets otherwise.
> 
> unfortunately, I was not able to reproduce this and these are very moment-in-time dependent scenarios

Oh, my bad. But I've 1 doubt, if all of them set 0.03% why does the second case get -0.741792% from the amount shown in the UI?

received: 0.287287 WETH 
UI showed 0.289431 ETH to receive

![image](https://github.com/connext/monorepo/assets/26097731/6fa513fd-e6c3-48ab-ab86-26723315b43f)

https://connextscan.io/tx/0x73d9c1dc6c0c7a6fbb557a133f72aed86f06dd6a454bf07c54d7c60005e07de8
