### ISSUE TITLE
[ST] Execution error

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5877]
**Describe the bug**
A txn (0.82 WETH) going from Arbitrum to Mode got an execution error. Reconcile already happened. It's asking for a bump (idk why xD) but I can't click the button

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/f6092b32-0f7d-4029-b921-2d316774d9e4">

https://connextscan.io/tx/0xbf9684b0aab0ba40be9193df855965509350e0aa8c74d5bc9cb63c97b4a77da4

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1219576483379417089

@oncall

**Comment by Tommy-R8** [comment]
Another case, BNB to Polygon

https://connextscan.io/tx/0x2383cdd28423134bded6154da4b31db87e17584925a8f073f1eb2cee57f08697
https://discord.com/channels/454734546869551114/1219747497778352148/1219748073761276028

**Comment by MinistroDolar** [comment]
Another case ezETH from Mode to Arbitrum

https://connextscan.io/tx/0x028858d777af75d74cd98a86473b805e7d466e3cad5ea57931241f2779b133c3
https://discord.com/channels/454734546869551114/1219773620159643698

**Comment by MinistroDolar** [comment]
The last 2 cases were fixed and funds arrived, but the first one is stuck since 31 hours. Any update on this?

**Comment by Tommy-R8** [comment]
This transaction says execution error
https://connextscan.io/tx/0x34f65b85eeb0813d2c99dc1c66910f9c18e13b7ed3052092e4b73effb5645d15

Ticket 311 on Intercom

**Comment by Tommy-R8** [comment]
Another tx: https://connextscan.io/tx/0x1d359986bcb901f0d630ad4909006644413501512eddc95f819901526c48cd77
Ticket 314 on Intercom

**Comment by Tommy-R8** [comment]
The last 2 also completed. The first transaction in the thread still remains in ExecutionError after 33 hours

**Comment by LayneHaber** [comment]
https://connextscan.io/tx/0xbf9684b0aab0ba40be9193df855965509350e0aa8c74d5bc9cb63c97b4a77da4

completed as well after resetting the error status.

I think this and #5892 are related to error status being stale and UI prompts based on that.

@preethamr how are the error statuses on transfers set?

**Comment by LayneHaber** [comment]
https://github.com/connext/monorepo/pull/5900

**Comment by ekbainova** [comment]
#5656?
