### ISSUE TITLE
[ST] Relayer fees bump not detected - Keep asking for more

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5886]
**Describe the bug**
The user initiated a txn from Arbitrum to Linea with 0 relayer fees (this could be a calculation bug on our side)

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/88ddacba-cea7-4c87-9b42-c6fe1c66e94f">

https://connextscan.io/tx/0x5fbe311c626e640be067e7ae2908302a515bec2bed100e15f7f3bb59a1a47d2f

He bumped the first time here: https://arbiscan.io/tx/0xd475b7b07ca0b4a45e478e12c984282b94165319649dd5ae8831fe347f18c902

Then, the system requested him to bump it 2 more times: 
https://arbiscan.io/tx/0x23f1969c364a45d204e90b21fe469546f5895fb7f9bb42a33b7f02f4f913b878
https://arbiscan.io/tx/0xaae0be675647c754d32fd813451ffeaa823dec4720a59fbc9d3512afa7e8deab

It seems that despite successive bumps the system is still showing the relayer fee at 0.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1219801005328175124

@oncall

**Comment by just-a-node** [comment]
Closing unless we see more instances of this post-cutover.
