### ISSUE TITLE
[ST] Slow path taking too long

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5887]
**Describe the bug**
A few txns from Mode to Arbitrum (involving ezETH) are stuck and slow path is delayed

Example:

https://connextscan.io/tx/0xe4b7ac56cf2dfe9008abe646eb75f50e507f1a8b1cfbfad7fa37a27ec9d2bb8d

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/a9b09d3c-17c1-46f9-96f7-dff5f27e2d4e">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1219817729574309948

@oncall

**Comment by MinistroDolar** [comment]
Now i've 1 more taking too long but different path an asset (WETH Mainnet to nextWETH arbitrum):

https://connextscan.io/tx/0x3562fa6631f0494151af4a5be671919dee5bffbe75d4be9f3708c9c0f0633ce0

a whale one

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1219832634448936971

**Comment by MinistroDolar** [comment]
Another case. USDT from BNB to Linea

https://connextscan.io/tx/0x66fd68b562b7a8e23059e786bf40301fe6777afa4ad83fdcde3bc6a82901bf49

average ETA seems to be like 3-5 hours

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/f446d677-55fe-46ec-9bb5-0ec6842dda00">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1219843169328431164

**Comment by ValerywArz** [comment]
another case: USDC from BNB to Linea
![image](https://github.com/connext/monorepo/assets/93597601/56c20cd8-740f-4efe-bc32-59ca0a70924f)
https://connextscan.io/tx/0x491056614e6c72da2ac69d7b8eb9268a9a012fb171171c231ca6006cee8a2e88
link to ticket: https://discord.com/channels/454734546869551114/1222158976133759057
