### ISSUE TITLE
[ST] Txn stuck at bump relayer fees step

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5892]
**Describe the bug**
User already bumped the relayer fees but the system seems stuck

<img width="1919" alt="image" src="https://github.com/connext/monorepo/assets/26097731/a2c68602-4139-4b9c-9c15-aa72f7afc9e1">

https://connextscan.io/tx/0x4d9f593badebf750ffdb9f4c0efe523c139d7b1ecff49249f970f38727d5c72d

bump tx: https://arbiscan.io/tx/0xf12a4a35caedeca9804f0ef820b17197b0227c258e7af76e751815d19b15a045

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1219912405761392682

@oncall

**Comment by MinistroDolar** [comment]
I've another similar case, in this opportunity user bumped twice and system is asking for more bumps.

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/95949fde-5f16-44bd-9a4d-1d5e34ab51bc">

https://connextscan.io/tx/0x7766d0a4d797fadb1685f8d716180dd1b11eee81102d0dbd530a3b25d6e183bf

bump1: https://bscscan.com/tx/0x6a913ef2f0474f79604862dd5a42cfbe8156eb91a18ee509253542e263866752
bump2: https://bscscan.com/tx/0x9170a7630197c1a836c6f1ceea0647a35b05c089b3379c04b80d45cb8628bd26

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1220076908545573025

**Comment by Tommy-R8** [comment]
Another case: https://connextscan.io/tx/0x2114dbe145065e78b22758675c30418473d86a740deb81db1d8a5ae78b01bd4b
![image](https://github.com/connext/monorepo/assets/84744304/f827de6e-a5cd-4b17-b47c-e249f94c12f5)

Ticket 313 on Intercom

**Comment by LayneHaber** [comment]
all are executed:
- https://connextscan.io/tx/0x4d9f593badebf750ffdb9f4c0efe523c139d7b1ecff49249f970f38727d5c72d
- https://connextscan.io/tx/0x7766d0a4d797fadb1685f8d716180dd1b11eee81102d0dbd530a3b25d6e183bf
- https://connextscan.io/tx/0x2114dbe145065e78b22758675c30418473d86a740deb81db1d8a5ae78b01bd4b

unfortunately, these are subject to a JIT estimation and are really difficult to track down.

@pjenviri do you know how the slippage is updated in the UI? wondering if its consistent with carto.

@Tommy-R8 do you know how long they waited in between?

**Comment by LayneHaber** [comment]
https://github.com/connext/monorepo/pull/5900
