### ISSUE TITLE
[ST] <User cannot Bump,The button always shows waiting for bump>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5895]
**Describe the bug**
<User cannot Bump,The button always shows waiting for bump>

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1220263019649699851/1220263022355021845

![image](https://github.com/connext/monorepo/assets/92560156/2b01b88d-f685-4543-a7b8-a2bca2fd7d4f)

TX ID：https://connextscan.io/tx/0x7b8ea1e1da130ef70ff51acb81e0ebe9ab90b545e2a771d56094d586e8520798
@oncall

**Comment by QQHHUH** [comment]
Another case
DC:https://discord.com/channels/454734546869551114/1220290505083195412/1220290836458373230
 tx id:https://connextscan.io/tx/0x70a2357d2b61f8ce401b2f80739a1e50522ac69128626d90e4f9ac0c22b162d6

**Comment by MinistroDolar** [comment]
I've another case

![image](https://github.com/connext/monorepo/assets/26097731/38a1c35d-5a55-4c67-a0f5-3c40e0859a28)

Tx:
https://connextscan.io/tx/0xac6ad8159815a29b5feb26dc5e185c8e8a87f37180c9089678964bf5cc8369af

Ticket
https://discord.com/channels/454734546869551114/1223243317777793045
