### ISSUE TITLE
[ST] Fast and Slow path not working?

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5908]
**Describe the bug**
A user bridged ezETH from Arbitrum to Linea. More than 6 hours have passed and the slow path didn't happen. 

https://connextscan.io/tx/0x55872c3813085970cf1d24c4b00d1b6f11b646ab479296d33040a1d21eb70d3b

Then, when I checked the transfers I noted that no slow path txns were confirmed in the last 6 hours

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/2f3fa2e9-82d2-4cdb-ae9e-4c1662726ef0">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1220815688411643956

@oncall

**Comment by MinistroDolar** [comment]
Now i see that fast path is also down

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/206605f7-41ec-4787-b3e3-d89a26b6cad5">

**Comment by LayneHaber** [comment]
should be resolved
