### ISSUE TITLE
[ST] Long slow path

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5911]
**Describe the bug**
Some slow path transactions are taking too much time to complete.
![image](https://github.com/connext/monorepo/assets/84744304/4411e792-ab87-49ec-9d08-583dd4c466f2)
https://connextscan.io/tx/0x55872c3813085970cf1d24c4b00d1b6f11b646ab479296d33040a1d21eb70d3b
https://connextscan.io/tx/0x4a4fa3f612cd8d26af1ff0acb88f3241aa14191cc67cc3dd8ae7a40305bcd56d
https://connextscan.io/tx/0xb4377e4d18e255e3a6a314b10e887095bc3a8d4c1cb1f444cdfd3574d6cd678e

**Comment by LayneHaber** [comment]
resolved, closing
