### ISSUE TITLE
[ST] Execution reverted ezETH ETH->Blast

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#5915]
**Describe the bug**
TX fails on call, eg:
1) https://etherscan.io/tx/0x081166f1a652af6ec1cc23b1e58757c46650f79d7e589913a4d26398ea15cad0?locale=en-US&utm_source=imtoken
2) https://etherscan.io/tx/0x2f507998f2f6abc20c7c695c582578d5cf388e6d3a6ceee8fff7764804e10932?locale=en-US&utm_source=imtoken
3) https://etherscan.io/tx/0x0012fd6fefcedf6bfa7f674871c498c4492696b67eff232c82dd928af4309f84

Successfull transfer which was sent right after tx №3 (in the list above): https://etherscan.io/tx/0xd832aa2ca3bb5cde8cf37025e9608ef162d8af05d983453bf5f74d8c7262cbcb

**Additional context**
The user spent ~75$ paying fees for nothing. There's enough allowance and enough ETH for gas in the user's wallet. 

@oncall

**Comment by LayneHaber** [comment]
> https://etherscan.io/tx/0x081166f1a652af6ec1cc23b1e58757c46650f79d7e589913a4d26398ea15cad0?locale=en-US&utm_source=imtoken
https://etherscan.io/tx/0x2f507998f2f6abc20c7c695c582578d5cf388e6d3a6ceee8fff7764804e10932?locale=en-US&utm_source=imtoken
https://etherscan.io/tx/0x0012fd6fefcedf6bfa7f674871c498c4492696b67eff232c82dd928af4309f84

all of these succeed in simulations provided the gas is increased. do you know how these transactions were initiated @oswy-cpu ?

**Comment by LayneHaber** [comment]
bridge UI?

**Comment by oswy-cpu** [comment]
@LayneHaber thanks Layne, I'll ask the user and will suggest him to bump the gaslimit

**Comment by LayneHaber** [comment]
was not able to repro locally in the bridge ui, fwiw the gas for these transactions is not calculated within the SDK but from the users injected provider or the static provider on the bridge page. I would also recommend they rotate providers in their metamask.

going to close this for now
