### ISSUE TITLE
[ICE: 10] Relayer fee in ezETH

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5916]
**Describe the bug**
An ezETH transaction from Mode to Ethereum has been stuck for 2h+ because of LowRelayerFee. It says that no additional fee is required, and that the current fee is a mix of ETH and ezETH
![image](https://github.com/connext/monorepo/assets/84744304/fe7c2704-a9fe-4dcf-8d08-9f9da9537266)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1221676346317606924/1221676522348347433

**Comment by ekbainova** [comment]
#6141
