### ISSUE TITLE
[ST] High relayer fee estimates

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5919]
**Describe the bug**
This week we've received 2 separate reports of users getting quoted an enormous destination relayer fee. One of these was to an L2 and it said it was around 0.7 ETH. The other one was to Ethereum and it was hovering around 50-60 ETH. This is not just a UI display issue because at the moment of starting the transactions the users actually get the prompt in their wallets to send that much. This should be investigated because the relayer fee is still not shown in the main UI (https://github.com/connext/monorepo/issues/5843) and someone can get rekt without knowledge of it.

![image](https://github.com/connext/monorepo/assets/84744304/80348c25-5480-425f-9ed2-e26852990f64)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/454734546869551116/1220577999490121790

**Comment by preethamr** [comment]
Took a look, I am unable to repro this:
![image](https://github.com/connext/monorepo/assets/1195648/8fae961a-8a17-45c9-a9da-9d95e0c33c16)

**Comment by preethamr** [comment]
@Tommy-R8 more context on how to run into this issue could help

**Comment by Tommy-R8** [comment]
> @Tommy-R8 more context on how to run into this issue could help

There isn't much to it. These past few days sometimes you could connect your wallet, input an arbitrary amount of tokens to bridge between two chains, and just see super high fee estimates. Nothing in the procedure would be out of the ordinary bridging experience/process

**Comment by 0xanedi** [comment]
Another tkt about this: https://discord.com/channels/454734546869551114/1225388163048935516

https://connextscan.io/tx/0xbc4bf5cf29b8fbb90a51d88d6537a6cba64f4960fb04e58ae98fc095b52b470e

**Comment by alexwhte** [comment]
Feedback from Gnosis team 
![image](https://github.com/connext/monorepo/assets/37959170/420c4318-f043-4674-bf64-1715470e2872)

**Comment by prathmeshkhandelwal1** [comment]
> Feedback from Gnosis team ![image](https://private-user-images.githubusercontent.com/37959170/319632382-420c4318-f043-4674-bf64-1715470e2872.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDM0OTcsIm5iZiI6MTcxMjI0MzE5NywicGF0aCI6Ii8zNzk1OTE3MC8zMTk2MzIzODItNDIwYzQzMTgtZjA0My00Njc0LWJmNjQtMTcxNTQ3MGUyODcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE1MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MGI1NzNiNTcwN2EwOWQ3MTY2N2U5Yzk4OTdjODYzNWI0NmM4Y2RkODgwMGRkZjRjNTA3NTFlYzhmMTczYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FWll07EDIZXAcdZYrgqpFkzRRTTwSlmHK8zqTh_xQSk)

@alexwhte Can you link us up with above tx?

**Comment by alexwhte** [comment]
asked and added you

**Comment by alexwhte** [comment]
@prathmeshkhandelwal1 https://gnosis.blockscout.com/tx/0x129ac5f77dd892d997319bccf561506edda5cdc6ce340c892b16c13234b6a401?tab=internal
can you pinpoint this in connext side?

**Comment by ekbainova** [comment]
@alexwhte Examples in one list here. 

As mentioned in ZenHub (here):
https://discord.com/channels/454734546869551114/454734546869551116/1220577999490121790
https://discord.com/channels/454734546869551114/1171878046253465610/1222194937488216245
https://discord.com/channels/454734546869551114/1225388163048935516

As mentioned in Github (https://github.com/connext/monorepo/issues/5958): 
https://tickettool.xyz/transcript/v1/993555046891540570/1220778385920229467/transcript-closed-2332-phong.html/661967f8/6606f2f8/9d8fbfc23e3bebdf61092659aed64bcfd1d5e5161edd826d48685832a3657e2e
https://discord.com/channels/454734546869551114/454734546869551116/1224666931647348856
https://discord.com/channels/454734546869551114/1224379407234502736
https://discord.com/channels/454734546869551114/1224426322940661831
https://discord.com/channels/454734546869551114/1224632011344576584

Intercom tickets: 
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/315?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/417?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/354?view=List

Discord: 
https://discord.com/channels/454734546869551114/454734546869551116/1224708965653418024
https://discord.com/channels/454734546869551114/1224201377589493910
https://discord.com/channels/454734546869551114/1224249766838272010/1224253018749407293
https://discord.com/channels/454734546869551114/454734546869551116/1219563212836569189

**Comment by alexwhte** [comment]
@prathmeshkhandelwal1 can you take next steps

**Comment by just-a-node** [comment]
Fixed recently
