### ISSUE TITLE
[ST] Can't bump txn

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5923]
**Describe the bug**
Getting a "waiting for bump" msg when trying to bump the txn, it doesn't let you click on it.

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/2553c7c1-1ab2-4959-9e52-8f2587fefe38">

https://connextscan.io/tx/0xafbed8e573bc5fb69d381686bef40adf4a5a466ee0f18be956f31d9639e5bc80

**Link to ticket in discord**
[Intercom 362 ](https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/362?view=List
)

@oncall

**Comment by preethamr** [comment]
This has been resolve
