### ISSUE TITLE
[ST] <Linea transfers going through slowpath even tho there is router liquidity>

### ISSUE THREAD

**Issue by A-Keyboard** [connext/monorepo#5937]
**Describe the bug**
There is enough ETH in the router liquidity on Linea.

The bridge UI quotes me fast path for my transfers.

Transfers goes through slow Path

Happened to me 3 times in a row https://connextscan.io/tx/0x0c8f6fbafbfccb2914c0714467ba7c82fcca9a89494125b55d3cfa50d6608bee
@oncall

**Comment by preethamr** [comment]
@A-Keyboard investigating this furhter
