### ISSUE TITLE
[ST] slow path taking too long

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5949]
**Describe the bug**
Tx: ezETH from Mode to Linea - Slow path taking more than 6 hours

https://connextscan.io/tx/0xa0375c3b9b22aa9edc2673835c144bd5e845a5139501c1cf7f9467fd962c453b

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1223633791457693858

@oncall

**Comment by preethamr** [comment]
This has been resolved:
More details on:
https://discord.com/channels/992549151134982234/1223662877463019592
