### ISSUE TITLE
[ST] Cant approve ezETH with Fireblocks + Walletconnect

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5951]
**Describe the bug**
Maven capital is trying to bridge ~500 ezETH 

**To Reproduce**
They are using Fireblocks+Walletconnect

![telegram-cloud-photo-size-4-5778568331865998895-y](https://github.com/connext/monorepo/assets/37959170/62394dd6-39fa-424f-8a90-a598a63fa54f)

**Comment by preethamr** [comment]
Need more info to be able to analyze this one. I asked for the same on their TG channel.

Maven has a setup, that is not straight forward to replicate.

**Comment by alexwhte** [comment]
closing for other Fireblocks bug
