### ISSUE TITLE
[ST] slow path linea to metis stuck for more than 9 hours

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5952]
**Describe the bug**
4996 USDC from Linea to Metis stuck since more than 9 hours

https://connextscan.io/tx/0x97180fa2478bb6f2474acb8c149c69916f123018170f31e8edb77ae65431f5a1

![image](https://github.com/connext/monorepo/assets/26097731/bda2ac59-2cdd-44bd-8907-5d86d825e6ef)

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1223790050852999178

@oncall

**Comment by prathmeshkhandelwal1** [comment]
Tx went through resolved
