### ISSUE TITLE
DAI from BNB to Linea (unsupported path) txn stuck since 13 days.

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5953]
**Describe the bug**

The user initiated a txn from Li.fi to bridge DAI from BNB to Linea (an unsupported path) and now he has his funds stuck since 13 days.

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/cda53890-abf3-4c91-9e7c-f9dfb5ba413b">

https://connextscan.io/tx/0xcd2af36a2b829e47b2866f6710f0d3743a7aa4fc7fa5e2338bf50a5d28642d75

https://bscscan.com/tx/0x353bf1ea5af7c232929077beeabdae1e498634babd7d2d71f7a0a5da1ad83cdf

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1223910960616443954

@oncall

**Comment by MinistroDolar** [comment]
I've another case:

https://connextscan.io/tx/0xa54a318bc26665ee08462cc72e3ac432b1056faadd809ef41fd8a77d546f9f2d

Ticket:

https://discord.com/channels/454734546869551114/1225915180022501470

**Comment by ekbainova** [comment]
#5993
