### ISSUE TITLE
[ST] Slowpath down?

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5954]
**Describe the bug**
Last txn completed via slow path was like 5 hours ago:

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/df8985e9-4b65-4860-a44d-abb092ded865">

@oncall

**Comment by preethamr** [comment]
After funding the relayers, this issue is now resolved.
<img width="2432" alt="image" src="https://github.com/connext/monorepo/assets/1195648/34859e73-03b1-4c08-a1c8-bc8e2d16e598">
