### ISSUE TITLE
[ST] Destination gas fees UI BUG

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5958]
**Describe the bug**
When simulating a bridge txn, seems that the cost in ETH of gas fees at destination is not updated and shows the same amount in ETH as for stablecoins.

I have tried in different browsers, clearing cache and cookies, it has also happened to an arbitrageur who moves considerable volumes on the network:

<img width="551" alt="image" src="https://github.com/connext/monorepo/assets/26097731/264bc7ae-8a7a-4af3-bf43-845a56549286">

https://discord.com/channels/454734546869551114/454734546869551116/1224160928057135144

<img width="376" alt="image" src="https://github.com/connext/monorepo/assets/26097731/4a17e3fd-bf33-443d-a494-20c3460b8970">
<img width="397" alt="image" src="https://github.com/connext/monorepo/assets/26097731/82545e90-00a1-4ede-9fda-8e09db099a67">
<img width="391" alt="image" src="https://github.com/connext/monorepo/assets/26097731/792cfdea-e6da-475d-8164-2abd3f75f1ae">
<img width="413" alt="image" src="https://github.com/connext/monorepo/assets/26097731/53f7b5ef-e682-4af8-85b5-71923c1357ef">

The issue seems to be independent of the network you choose and previously happened to me (I fixed it with a hard refresh, but in this case I can't manage to do it).

**To Reproduce**
1. Go to bridge.connext.network
2. Simulate a bridge with USDC or USDT
3. Then change the asset to WETH

@oncall

**Comment by MinistroDolar** [comment]
I've a refund case:

Txs: 
https://connextscan.io/tx/0x20b1b5c47a57af8fb560b5c3f8642e5823f388a494d4838111825afe8e449d38
https://connextscan.io/tx/0x6c41becc7f5e179ed3401a281bb18f614501b3ea37140888bb4b0514ecec1f3e

Link to the ticket:
https://discord.com/channels/454734546869551114/1224379407234502736

**Comment by ekbainova** [comment]
https://tickettool.xyz/transcript/v1/993555046891540570/1220778385920229467/transcript-closed-2332-phong.html/661967f8/6606f2f8/9d8fbfc23e3bebdf61092659aed64bcfd1d5e5161edd826d48685832a3657e2e

**Comment by ekbainova** [comment]
https://discord.com/channels/454734546869551114/454734546869551116/1224666931647348856

**Comment by MinistroDolar** [comment]
Another case:

tx: https://connextscan.io/tx/0x26e1e4b0ce0a0102023a06fe69692c394315143b25e311487977a5648db96a37

ticket: https://discord.com/channels/454734546869551114/1224426322940661831

**Comment by MinistroDolar** [comment]
Another:

Wallet : 0x97219ef57a528c1f28a07a8c028b13c25464aea9
TX : https://connextscan.io/tx/0x21d2d55b32a5569a69b750bf29cc26792f5b6b2c63ea781115d5f443086545fb

ticket: https://discord.com/channels/454734546869551114/1224632011344576584

**Comment by just-a-node** [comment]
Should have been fixed with this 3 days ago: https://github.com/connext/frontend/commit/a42479983cf481e6190a7b475caef59cc5d36df3
