### ISSUE TITLE
[ST] <User feedback that RelayerFee is too high>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#5960]
**Describe the bug**
User feedback that RelayerFee is too high

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1224249766838272010/1224249769845588120
TX ID:https://connextscan.io/tx/0xf7b0563dcd10fb17235c9b0709cb9935646644d73f6ae333f82323068656e125

**Screenshots**
![image](https://github.com/connext/monorepo/assets/92560156/ac058168-f5bf-4ada-ba64-ec6c24d6d26c)

The user displays the Gas fee as 0.13ETH on the UI front end, but the sdk estimateRelayerFee has always been normal. Users believe that estimateRelayerFee uses two calculation methods: native and usd. The front-end page should use usd, which results in high gas for front-end calculations.

@oncall

**Comment by QQHHUH** [comment]
DC:https://discord.com/channels/454734546869551114/1224184339210702969/1224184342126006377
TXID:https://connextscan.io/tx/0x8f24eac565a1c547a1ead398be19ba65f04af4b59c42e57294a3074b1621747c

RelayerFee is too high

**Comment by MinistroDolar** [comment]
The issue was reported here: https://github.com/connext/monorepo/issues/5958

**Comment by QQHHUH** [comment]
thanks
