### ISSUE TITLE
UI: Set better expectations around slow path and relative path latency 

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#5966]
## Problem
Currently, we do not effectively manage client expectations.
It's not clear that even if I see the estimated time, it's not guaranteed that I will make transaction within that timeframe.
We currently fetch if theres sufficient available router liquidity to fill a transfer fast, but we CANT check if routers are actually working 

And we have only three expected time: 
1) <4 mins for fast path
2) <5 hours for slow path 
3) This transfer will be sent through the Blast Canonical Bridge. Withdrawals will be subject to the 14 day waiting period and must be performed manually.

## Impact
We have observed that 48% of tickets are related to "Slow path taking too long" and "Active routers not bidding (unexpected slow path)", with 100% of them involving transfers above $10,000.

## Proposed Solution
There's at least 3 ways we can improve. This is meant to be a bandaid solution so please ensure this is a quick fix. In our protocol upgrade we should have router telemetry and better feedback 

### Recommendation 1: Fast transfer override
We want to make sure we are overriding anomalies and issues where there's router liquidity but it's not filling transfers for some reason. Something like below, but I trust engineer on best solution. 

If estimated latency = fast path
then `select status from transfers where (same destination domain & same asset) and time <= 3 hours ago limit 20`
if >50% of results are status=`completedSlow`, then _instead_ display estimate slow path 
else display fast path

### Recommendation 2: Show average times per bucket
After recommendation 1 logic is added to override unexpected slow path, check recent average latency

If estimated latency = fast path
then display the latest average fast path times, for example:
`select avg(execute_timestamp-xcall_timestamp) from transfers where (same origin->dest path & same asset) and status=**completedFast** limit 20` 
round up to by minute precision

If estimated latency = slow path
then display the latest average slow path times, for example:
`select avg(execute_timestamp-xcall_timestamp) from transfers where (same origin->dest path & same asset) and status=**completedSlow** limit 20` 
round up by hour precision

https://www.figma.com/file/Z3iq2LOM12K1BeSGQc1Dal/Connext-Concept?type=design&node-id=0-1&mode=design&t=XHHTz5vstc2uPKek-0

<img width="890" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1NDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57fc7c48c78eb3b49d725eaccf5b73fdfb63a375/image.png" alt="image.png" />

### Recommendation 3: Log our estimates
We should log what we are estimating and especially be able to compare to each transferid status result
This may be sufficiently complex to move into a new issue instead

## Acceptance Criteria
- [ ] at least recommendation 1 is completed
- [ ] this is tested in a staging version of the ui over at least 10 transfers and ideally on a path that is creating active tickets or known router downtime 

We have <=15% of tickets regarding to this unexpected slowpath .

**Comment by just-a-node** [comment]
`SdkUtils.getTransfers()` can provide data for transfer times per path+asset. 

Relevant `params`:
```
{
  status?: XTransferStatus, // should only look at "CompletedFast" and "CompletedSlow" transfers
  originDomain?: string;
  destinationDomain?: string;
  range?: { limit?: number; offset?: number };
}
```

However, we should make sure not to entire the entire history of transfers every time a client loads a new path+asset. By default "limit" is 10 (need to find the right balance of results) and should paginate until the last 7 days are found. Then the average can be calculated. This will likely benefit from caching at some level.

**Comment by jwtong** [comment]
Ok so based on this info, we need a few different pieces. Assuming we're not using react-query, we need
1. useEffect() hooks that async getTransfers from past 7 days from source => destination chain
2. helper functions to derive "a - b <timerange>" for both slow and fast routes, as well as average speed  (median?) across both slow and fast. Not sure if we have that, but at first glance, it looks like a lot is hardcoded
3. local storage that has JSON data { destination, source, slowText, fastText, medianText} to prevent unnecessary load on sdk.sdkUtils.getTransfers() calls
4.  TSX component file that includes 1. TimeEstimateTooltip consuming the display hooks/functions defined above, potentially including the [!] icon with it 2. Generic text formatters to display median time or median time range

**Comment by jwtong** [comment]
I think we'll need an SDK based solution that caches the time ranges and average we want to display, otherwise it's to query intensive for the client to perform

**Comment by jwtong** [comment]
@ekbainova need some specification also on what "a" and "b" are in the text a-b. Is it from minimum to median, or minimum to maximum. Cause if it's min to max across a large number of transactions, you could see for instance (1 - 300 hours) for a slow value.

**Comment by just-a-node** [comment]
@ekbainova Can we consider last N transfers instead of 7 days? This will be easier to implement and guarantee decent performance.

**Comment by jwtong** [comment]
https://frontend-connext-bridge-8g4w2vcrt-connext-979dc950.vercel.app/

**Comment by just-a-node** [comment]
> https://frontend-connext-bridge-8g4w2vcrt-connext-979dc950.vercel.app/

@jwtong does this include the new considerations for the task description? (edited last week)

**Comment by jwtong** [comment]
frontend-connext-bridge-git-jt-estimated-time-connext-979dc950.vercel.app

**Comment by ekbainova** [comment]
ETH-Blast route. [i] shouldn't be shown in this route. Estimated time also. <img width="540" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMSs2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--046a8d4c86455c6013d19735edfe46133ae41c21/image.png" alt="image.png" />

**Comment by ekbainova** [comment]
Transfer was in progress on connextscan and animation was in progress, but there was

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmU2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03023137c274fe5aebdba97b0f83a025b4c8b406/image.png" alt="image.png" />

**Comment by ekbainova** [comment]
**Not critical.** If the duration of the slow path consists of double-digit minutes, then the numbers are very close to those of the fast path's time

<img width="380" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0M2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36aa1de01239385817b3451e8f8216009f2dba56/image.png" alt="image.png" />

**Comment by ekbainova** [comment]
@jwtong Ready to merge. I will ask @regexpressyourself to fix minor bugs (in another task).

**Comment by ekbainova** [comment]
We should deploy it separately today. @just-a-node
