### ISSUE TITLE
[ST] Linea router down

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5976]
**Describe the bug**
The router https://connextscan.io/router/0x58507fed0cb11723dfb6848c92c59cf0bbeb9927 is not completing txns since yesterday. 

Example of txns that should get bids from this router: https://connextscan.io/tx/0x0ccd169c648506800eb8c7329db1694cd178990c75e446a62aff0e436bd2a0de

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/0e3b956d-8511-4998-b3fc-e28125542a26">

Last tx processed: 

https://connextscan.io/tx/0x0ccb6ea9f55fcbbe9e6a37045dd0ce42eb83054f86cfa511378b1747287ede8f

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1224837944293199912

@oncall

**Comment by 0xanedi** [comment]
https://connextscan.io/tx/0xbbdbce23fc58f09da4d72b6ed08f49ffc53bcf7a37c181f924d95f186e86c7cf

**Comment by alexwhte** [comment]
this is in review

[router-subscriber-logs-3h.txt](https://github.com/connext/monorepo/files/14962403/router-subscriber-logs-3h.txt)
[router-publisher-logs-3h.txt](https://github.com/connext/monorepo/files/14962402/router-publisher-logs-3h.txt)

**Comment by ekbainova** [comment]
https://discord.com/channels/992549151134982234/1223342633393459261

**Comment by preethamr** [comment]
@ekbainova 
Dialectic router is still not bidding.
Reviewed the logs, not seeing errors, but also it is not detecting new xcalls.
Asked, them on TG to upgrade to a recent router image
Their config looks ok

**Comment by ekbainova** [comment]
https://github.com/connext/monorepo/issues/6062

**Comment by ekbainova** [comment]
Today:
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/580?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/579?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/576?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/578?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/574?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/575?view=List

**Comment by alexwhte** [comment]
removing high for now @ekbainova can you close if needed
