### ISSUE TITLE
[UI] Showing unsupported route

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#5993]
**Describe the bug**
UI showing dai from BNB to Linea with crazy return amount, which should not be the case
Attaching the ss below
<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTQvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6dd4c8391feb0f1f770235e919227023336c140/Screenshot%202024-04-08%20at%202.25.06%E2%80%AFPM.png" alt="Screenshot 2024-04-08 at 2.25.06 PM.png" />

This should be happening due to asset data pulled from `getAssetData` endpoint, We should only put routes which are in the `getSupported` route.

**Additional context**
@oncall @jwtong

**Comment by prathmeshkhandelwal1** [comment]
Tasks:
- Disable LIFI Route
- Check # of transfers with linea (DAI) route
- Calculate refund amount

**Comment by prathmeshkhandelwal1** [comment]
https://www.notion.so/connext/Reliability-a695483dfdd746bfb0700917985ee40f

**Comment by prathmeshkhandelwal1** [comment]
Query results:

BNB -> Linea:

- `0x6868a7b67116f3ead4eff99da4cf1901e5e06c064e8264e670c5d8450a35080d`
- `0xcd2af36a2b829e47b2866f6710f0d3743a7aa4fc7fa5e2338bf50a5d28642d75`
- `0x3f6425da52fd5f173f0a04c111f1c9d860f2c22a51f0a472cbf7911329f82b19`
- `0xea72bea7e4bf4f8d2c02fc47fc96ce9398da16bc419d5bde6351b7efafc5eb48`
- `0x19567dff384fc41dc9cfbb8b0652767bb1ce3ddf8b7186b1e6c1ae082f53ff9d`
- `0x4d78c4d4388c89719c166edd8666600dd5115fe0230a8ec0913e597fa09ab12d`

**Comment by ekbainova** [comment]
@alexwhte the total amount of refunds is about 610$, I am going to use rest of WETH from you to refund it by myself, approve?

**Comment by ekbainova** [comment]
@prathmeshkhandelwal1 Could you help me determine if this problem has a similar nature? Here is the transaction link: https://connextscan.io/tx/0xa54a318bc26665ee08462cc72e3ac432b1056faadd809ef41fd8a77d546f9f2d. Do you think we should issue a refund in this case? You didn't mention it.

**Comment by alexwhte** [comment]
lifi is fixing it

yes @ekbainova any DAI transfer to linea

**Comment by just-a-node** [comment]
LiFi to use `getSupported` instead of `getAssetsData` endpoint. This prevent their UI from displaying routes we've disabled on the server side.

**Comment by just-a-node** [comment]
Still waiting on LiFi to confirm fix is deployed.

**Comment by just-a-node** [comment]
Still waiting on LiFi to confirm fix is deployed.

**Comment by ekbainova** [comment]
#6143 - one more case.

**Comment by just-a-node** [comment]
Confirmed on Lifi
