### ISSUE TITLE
[ST] Insufficient gas for the destination gas fee when trying to bridge ezETH from Ethereum to Blast 

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#5997]
**Describe the bug**
User is trying to bridge ezETH from Ethereum to Blast.

The user has enough ETH to pay gas on destination fees (i guess, bc he has 0.013 ETH) but UI says "insufficient gas for t he destination gas fee (showing as 0) https://etherscan.io/address/0xfed74f78700bB468e824b6BfE4A2ED305a9D86ba

![image](https://github.com/connext/monorepo/assets/26097731/d2905cd7-4b1f-43cb-bbb2-98cde859bca9)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1226982905180590130

**Additional context**
@oncall

**Comment by regexpressyourself** [comment]
PR: https://github.com/connext/frontend/pull/29

**Comment by regexpressyourself** [comment]
Merged to `cutover-iterim`
