### ISSUE TITLE
Connextscan UI TVL not displaying properly

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6005]
**Describe the bug**

Connextscan home page TVL is wrong. It currently shows $3m and it should be a lot higher.

**Link to ticket in discord**

**To Reproduce**
1. Go to connextscan site
2. Check out the TVL value
3. This is much lower than it should be

**Comment by regexpressyourself** [comment]
Going to keep monitoring this. I haven't seen the bug in the last two days, so it's tough to reproduce.

**Comment by MinistroDolar** [comment]
> Going to keep monitoring this. I haven't seen the bug in the last two days, so it's tough to reproduce.

I'm seeing now: 
<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/5fab80d6-9b78-4a77-9716-c63e11b1de84">

Tried on several browsers and did hard refresh

**Comment by MinistroDolar** [comment]
Hmmm fixed after leaving the site open for a while, seems that it's too slow

<img width="1911" alt="image" src="https://github.com/connext/monorepo/assets/26097731/5a6ddb3e-2850-4e77-858f-f94d7531fffb">

**Comment by just-a-node** [comment]
Fixed now - however, it will load slowly until we optimize some things under the hood.

**Comment by just-a-node** [comment]
https://github.com/connext/frontend/pull/30

**Comment by alexwhte** [comment]
can we close

**Comment by just-a-node** [comment]
Was monitoring, looks good now. Closing
