### ISSUE TITLE
React-Query useQuery() Refactor

### ISSUE THREAD

**Issue by jwtong** [connext/monorepo#6020]
## Background

https://tanstack.com/query/latest/docs/react/reference/useQuery

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Implement across general redux queries
- [ ] Implement for page-specific data flows (e.g. transfers)
- [ ] QA Functionality

**Comment by jwtong** [comment]
https://frontend-connext-bridge-git-jt-react-query-connext-979dc950.vercel.app

https://frontend-connextscan-ui-git-jt-react-query-connext-979dc950.vercel.app

**Comment by ekbainova** [comment]
Merge scheduled: 1 pm UTC on 14th of May

**Comment by ekbainova** [comment]
QA is here: https://www.notion.so/connext/96a0cc2229784b63b6c0598ea3f5655d?v=6baea494a900437c85312898fe359d46

**Comment by just-a-node** [comment]
Gas estimates are failing from QA, need to fix that before we can merge this.

**Comment by jwtong** [comment]
I don't have access to the notion page linked above @just-a-node

**Comment by just-a-node** [comment]
I don't have permissions to share pages within this org so I created a copy for you here: [[Smoke QA test](https://www.notion.so/96a0cc2229784b63b6c0598ea3f5655d?pvs=21)](https://www.notion.so/96a0cc2229784b63b6c0598ea3f5655d?pvs=21)
