### ISSUE TITLE
Front-end Utils Refactor

### ISSUE THREAD

**Issue by jwtong** [connext/monorepo#6022]
## Background

Remove bad utils (e.g. toArray, equalsLowerCase, etc...(

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Implement across app
- [ ] QA Functionality

**Comment by ekbainova** [comment]
@just-a-node @jwtong Let's plan 5pm CET Monday 13th of may for deploy.

**Comment by ekbainova** [comment]
@just-a-node @jwtong Let's plan 5pm CET Monday 13th of may for deploy.

**Comment by ekbainova** [comment]
@jwtong provide me with the link for QA
