### ISSUE TITLE
Transfers with LowRelayerFee are not displayed

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6029]
**Describe the bug**
Can't I filter LowRelayerFee transfers on connextscan.io. I'm getting an error: 'Application error: a client-side exception has occurred' It looks like a bug. 

Also can't find the transfer with LowRelayerFee error: https://connextscan.io/tx/0x65d84d1f23aac37ab882f5156707d2be1a91d740d1a87f83d8b351e372c1aca4

<img width="665" alt="Screenshot 2024-04-12 at 13 31 29" src="https://github.com/connext/monorepo/assets/18751995/f6d8c53b-2a56-47f8-8a34-d661e4363181">
@0xanedi

**Comment by ekbainova** [comment]
@prathmeshkhandelwal1 @just-a-node 
Is it a bug? Want to keep in touch with Socket regarding it.

**Comment by prathmeshkhandelwal1** [comment]
> @prathmeshkhandelwal1 @just-a-node Is it a bug? Want to keep in touch with Socket regarding it.

It could be due to bware subgraph issue we faced

**Comment by ekbainova** [comment]
The same bug if you choose error: Lowrelayerfee on https://connextscan.io/transfers and try to open the second page (or last) page. 
[Uploading... Screen Recording 2024-04-17 at 21.11.44.mov]

**Comment by prathmeshkhandelwal1** [comment]
Cant able to filter on basis of Errors (Specifically low relayer fees)

**Comment by regexpressyourself** [comment]
I'm seeing this in prod, but not on `main-sync-with-cutover`.

The transaction linked in the issue does not load on prod, but does on the latest `main-sync-with-cutover`:

- [Prod (not working)](https://connextscan.io/tx/0x65d84d1f23aac37ab882f5156707d2be1a91d740d1a87f83d8b351e372c1aca4)
- [`main-sync-with-cutover` (working)](https://frontend-connextscan-ui-git-main-sync-w-136440-connext-979dc950.vercel.app/tx/0x65d84d1f23aac37ab882f5156707d2be1a91d740d1a87f83d8b351e372c1aca4)


Additionally, filtering and paging will break on prod, but not on the `main-sync-with-cutover` branch.

I believe this is likely solved in the `main-sync-with-cutover` changes. @ekbainova can you take a look and see if the aligns with your expecations?

**Comment by just-a-node** [comment]
@ekbainova to check the (working) link above. Should be fixed in the main cutover version now.

**Comment by just-a-node** [comment]
I've QA'd this, still seems to be crashing with the application error if you select "LowRelayerFee" as the filter.

**Comment by regexpressyourself** [comment]
Got a draft fix up here: https://github.com/connext/frontend/pull/60

**Comment by regexpressyourself** [comment]
Deploy here: https://frontend-connextscan-ui-git-sm-6029low-f8f792-connext-979dc950.vercel.app/

**Comment by ekbainova** [comment]
Works as expected.
