### ISSUE TITLE
UI bug: :Cannot read properties of undefined

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6030]
**Describe the bug**
Users are encountering cases with the error message: `:Cannot read properties of undefined`. It seems that changing the RPC or cleaning cookies resolves the issue.

https://discord.com/channels/454734546869551114/1228254800853078060
https://discord.com/channels/454734546869551114/882349989672673312/1228242507847172166
https://discord.com/channels/454734546869551114/1227991740124758027
https://discord.com/channels/454734546869551114/1227740569313480727
https://discord.com/channels/454734546869551114/454734546869551116/1227739829983514655
https://discord.com/channels/454734546869551114/1227022762695069697
https://tickettool.xyz/transcript/v1/993555046891540570/1226991403629019167/transcript-closed-2725-denitro88.html/6626c7cb/661452cb/7c50d9875aaa9f7d5214436b81c5a9ea8e3db5f41f55fe179ff9bc4fc38d3fa0
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/501?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/524?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/521?view=List
https://discord.com/channels/454734546869551114/1228381238721515520

@just-a-node please, could you please link this with the bug mentioned here: https://discord.com/channels/992549151134982234/1032728270791262360/1227594235038142494

**Comment by ekbainova** [comment]
@prathmeshkhandelwal1 @just-a-node try to repro.

**Comment by just-a-node** [comment]
It was this: https://github.com/connext/monorepo/issues/3331

**Comment by prathmeshkhandelwal1** [comment]
Figured how to repro, 
- Connect wallet and choose mode to arb path for ezETH
- Disconnect wallet
- Refresh
- Reconnect wallet
- Try bridging, issue will be encountered

**Comment by prathmeshkhandelwal1** [comment]
@just-a-node , Should we close this issue out?

**Comment by just-a-node** [comment]
Fixed as of latest main cutover.

**Comment by ekbainova** [comment]
One more; https://discord.com/channels/454734546869551114/1232121959161135187
