### ISSUE TITLE
[ST] < UI issue for ezETH Router and nextWETH >

### ISSUE THREAD

**Issue by A-Keyboard** [connext/monorepo#6033]
**Describe the bug**

* Currently there is an UI affecting the current balance of routers of ezETH/nextWETH when they try to add liquidity. It shows them they have 0 ezETH even they are holding those assests. (Affecting two routers)

* Also, one of the router had an issue where they couldn't wrap their ezETH on mainnet ETH. They mentioned clicking on wrap doesn't do anything for them (Browser: Firefox/ wallets: Coinbase extension and metamask)

* Another LP tried to add some nextWETH on the pools, but their balance shows 0 nextWETH

**Screenshots**

**Additional context**
@oncall

**Comment by regexpressyourself** [comment]
@A-Keyboard Are you able to provide additional details on the last bullet point?

> Another LP tried to add some nextWETH on the pools, but their balance shows 0 nextWETH

I've been able to get an approval request going on nextWETH without issue. Is there maybe some more info/context on how to trigger the bug there?

**Comment by regexpressyourself** [comment]
I haven't been able to reproduce any bugs when wrapping or adding liquidity. 

I've been working off the latest main-sync-with-cutover branch as of aa2dc21, and tried a bunch of different routers. All tokens showed balances (0 or otherwise) and allowed me to initiate a wrap when the balance was available.

**Comment by 0xanedi** [comment]
@OnCall Today I encountered a related issue, but for a user. User has necessary ezETH in wallet, yet balance didn't show for nextETH and for ezETH.
Solution ended up being deactivating his VPN. VPN is interfereing with some layer of data pulling. User demands it to be fixed.

TICKET: https://discord.com/channels/454734546869551114/1231995967931416651

**Comment by just-a-node** [comment]
On issue bullet 3 of the original post:

We're still seeing issues with selecting tokens from the router add liquidity modal. For example:

<img width="986" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekdiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38aab527e9d4e4186654058f226af17b324c19c6/image.png" alt="image.png" />

User has no balance of nextWETH on Arbitrum. They select nextWETH from the dropdown. Then the UI changes it to WETH:

<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37ad49cf02229c16d4813eaacf706b95746acbfa/image.png" alt="image.png" />

They should never be supplying router liquidity in nextAssets on non-ETH chains.

**Comment by ekbainova** [comment]
@just-a-node need to force it.  It is a blocker for some LPs to add additional liquidity (Mesh LP and dialectic).

**Comment by regexpressyourself** [comment]
https://github.com/connext/frontend/pull/56

**Comment by just-a-node** [comment]
@regexpressyourself See my comments in https://github.com/connext/frontend/pull/56#issuecomment-2084440281.

**Comment by regexpressyourself** [comment]
Deploy here: https://frontend-connextscan-ui-git-sm-sof-6033-9394b0-connext-979dc950.vercel.app/

**Comment by ekbainova** [comment]
@regexpressyourself  #5724 and #6010 are included or not?

**Comment by regexpressyourself** [comment]
> @regexpressyourself #5724 and #6010 are included or not?

@ekbainova I don't believe so

**Comment by ekbainova** [comment]
Let's deploy it separately from #6020 today. @just-a-node
