### ISSUE TITLE
[ST] AI router seems down

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6037]
**Describe the bug**
The router didnt complete txns in the last hour (not normal)

https://connextscan.io/router/0x6fd84ba95525c4ccd218f2f16f646a08b4b0a598

Last tx: https://connextscan.io/tx/0x237a420fb6a91568346cc8f4d3f45bc9046dfc6f527c644e121c777998b54bc9

Now the only two routers available in Base are down, as [this router has been down for 4 days:](https://github.com/connext/monorepo/issues/6014).

https://connextscan.io/router/0xc770ec66052fe77ff2ef9edf9558236e2d1c41ef

<img width="1906" alt="image" src="https://github.com/connext/monorepo/assets/26097731/5cfdd9a0-88c8-4768-94a6-045dbe2dd33d">

It is expected that most of the txns to Linea and Base will go through the Slow Path.

@oncall

**Comment by preethamr** [comment]
Dokia (AI) is bidding recently (~ 2hours ago), to base and others:
https://connextscan.io/tx/0x237a420fb6a91568346cc8f4d3f45bc9046dfc6f527c644e121c777998b54bc9
https://connextscan.io/tx/0x5bb17a8796351089a94678fc244416041815727df9bcf0aee16682a54c04c97a
https://connextscan.io/tx/0x5bb17a8796351089a94678fc244416041815727df9bcf0aee16682a54c04c97a

@MinistroDolar is there a particular route that Dokia should be bidding on but it is not ?

**Comment by MinistroDolar** [comment]
> Dokia (AI) is bidding recently (~ 2hours ago), to base and others:
> 
> https://connextscan.io/tx/0x237a420fb6a91568346cc8f4d3f45bc9046dfc6f527c644e121c777998b54bc9
> 
> https://connextscan.io/tx/0x5bb17a8796351089a94678fc244416041815727df9bcf0aee16682a54c04c97a
> 
> https://connextscan.io/tx/0x5bb17a8796351089a94678fc244416041815727df9bcf0aee16682a54c04c97a
> 
> 
> 
> @MinistroDolar is there a particular route that Dokia should be bidding on but it is not ?

That router is one of the most active in the network, is not normal to be 2 hours inactive. There are more than 100 txns pending to Base. 

Also as i said, the other router on Base is down, so dokia router should bid those txns at least.

**Comment by MinistroDolar** [comment]
8 hours without bids from ai router @preethamr

**Comment by alexwhte** [comment]
different from the the Linea router issue?

**Comment by MinistroDolar** [comment]
> different from the the Linea router issue?

Yes. Dokia router is down.

**Comment by alexwhte** [comment]
Dmed them
