### ISSUE TITLE
[ST] User complaint: the accepted slippage was not met.

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6038]
**Describe the bug**
I'll copy here the user statement:

> Hi, I've made a bridge tx from from Optimism to Metis, token USDT, 5000 units. The UI showed I will receive 5065, and since I had issues with the bridge in the past, I made sure to set the slippage low, and so it says that the minimum I will receive is 5030. Yet, I received lower than that, 5014.

He says that, at the moment of initiating the bridge, the UI showed an estimated amount received of 5065, and he set a slippage of 0.5% as shown in the tx details: https://optimistic.etherscan.io/tx/0x36e48db774dc1c4c09f1d7584c341b871c55bb26ec9560b49793002fed88f4df. But he finally received 5014 which is 1% lower than the estimated amount received.

The issue here is that he doesn't have any screenshots and I don't know if there is any way to prove his statement.

**Link to ticket in discord**
[Intercom 539](https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/539?view=List)

**Link to the tx**
https://connextscan.io/tx/0x159bf3666b7a7405766e7f32d605df3b5de1ea584599b63a6959b83b8823f431

**Additional context**
@oncall

**Comment by preethamr** [comment]
This is not reproducible as seen by this user so have to look if this is a pattern among others

**Comment by preethamr** [comment]
> The issue here is that he doesn't have any screenshots and I don't know if there is any way to prove his statement.

This is no way to prove afaik, as we don't have the exact history pertaining to this users experience.

But is prob true, if other users/tickets have noticed the same on their end.

**Comment by MinistroDolar** [comment]
> > The issue here is that he doesn't have any screenshots and I don't know if there is any way to prove his statement.
> 
> This is no way to prove afaik, as we don't have the exact history pertaining to this users experience.
> 
> But is prob true, if other users/tickets have noticed the same on their end.

1 more thing, the user said this:

> Anyway, you can check yourself that the UI has some issues, and it displays incorrect values.
> If I understand it correctly when I bridge a token from chain A to chain B, what happens under the hood is that the token is swapped to NextToken on chain A, then NextToken is bridged to chain B, then the received amount of NextToken is swapped to the token on chain B.
> 
> So, if this is correct, you can see what the bridge shows on the UI (for USDT, for example, involving Metis), then you can try doing this process individually and see that you get different amounts.

The funny thing is that he is right, check this:

First simulating a USDT bridge from Optimism to Metis
<img width="394" alt="image" src="https://github.com/connext/monorepo/assets/26097731/04cee67c-cd19-4b46-8cfb-d23e09adccb0">

Then, simulating the first swap (USDT to nextUSDT) needed to initiate a bridge
<img width="386" alt="image" src="https://github.com/connext/monorepo/assets/26097731/bb14fb59-d8c7-4103-988f-4bbcaa7879c4">

And finally, simulating the swap on Destination side
<img width="394" alt="image" src="https://github.com/connext/monorepo/assets/26097731/7602780b-ebe4-4e2e-beea-8d1a9536e785">

The router fee is: 2.49 USDT and Relayer fees are 0.39 USDT (both deducted from the final amount)

So, there are almost 9 USDT diff without explanation.

I'm doing something wrong?

**Comment by just-a-node** [comment]
Nobody yet, this is in progress because Preetham was triaging it. Since nobody is working on it actively, this should be in backlog. Summoning @ekbainova here for help prioritizing this, whether we need to look at this vs. other bugs.

My initial analysis of this is that since the *actual* slippage for the user's 5K transaction was a net positive return (>5K received), the slippage they set at 0.5% was in fact met. 

0.5% slippage means they will not receive anything <4997.5. The estimate is simply an estimate at the time of the transaction initiation - depending on the state of the destination chain pool when the transaction gets to the destination chain, the swap may output something different from the initial estimate. As long as the final amount is >4997.5, it will execute and deliver whatever amount comes out of the pool at that point in time. If the final amount is <4997.5 then the execution will fail and the user will be prompted to bump their slippage or wait it out.

**Comment by prathmeshkhandelwal1** [comment]
We dont have enough proof for this, and also user received amount greater than what was minimum after 0.5 slippage. Their is nothing technically wrong here

**Comment by MinistroDolar** [comment]
> Nobody yet, this is in progress because Preetham was triaging it. Since nobody is working on it actively, this should be in backlog. Summoning @ekbainova here for help prioritizing this, whether we need to look at this vs. other bugs.
> 
> My initial analysis of this is that since the _actual_ slippage for the user's 5K transaction was a net positive return (>5K received), the slippage they set at 0.5% was in fact met.
> 
> 0.5% slippage means they will not receive anything <4997.5. The estimate is simply an estimate at the time of the transaction initiation - depending on the state of the destination chain pool when the transaction gets to the destination chain, the swap may output something different from the initial estimate. As long as the final amount is >4997.5, it will execute and deliver whatever amount comes out of the pool at that point in time. If the final amount is <4997.5 then the execution will fail and the user will be prompted to bump their slippage or wait it out.

The issue with this statement is that our UI calculates the minimum amount to receive by applying the slippage on the ESTIMATE at DESTINATION and not on the amount sent. 

As you can see in this image, the 0.5% is calculated on 5014, which, if the user had a screenshot confirming that the estimate to receive was 5065, the slippage was not met.

<img width="1612" alt="image" src="https://github.com/connext/monorepo/assets/26097731/ad375ff1-61a5-4467-ae6d-fd63a8805a70">

**Comment by ekbainova** [comment]
@just-a-node Oh, I also encountered an issue with the definition of 'Minimum received after slippage.' After researching our competitors, we should completely remove this string from our UI as it causes a lot of confusion.

There is no task, we can skip.
