### ISSUE TITLE
[main] Wallet connect doesn't fully connect

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6040]
**Describe the bug**

This happens on all deployments forked from `main`.

Connecting a wallet doesn't fully reflect on the UI state. 

**Link to ticket in discord**

**To Reproduce**
1. Go to bridge in a disconnected state
2. Connect with MM, Rabby, etc
3. After connecting, the "Connect Wallet" prompt still shows
4. If a refresh is performed, then the state updates such that the wallet is shown as connected

**Comment by jwtong** [comment]
https://vercel.live/link/frontend-connext-bridge-git-jt-path-loa-9c466f-connext-979dc950.vercel.app?via=deployment-domains-list-branch

**Comment by jwtong** [comment]
UPDATED LINK: https://frontend-connext-bridge-l678pmv1n-connext-979dc950.vercel.app/EZETH-from-ethereum-to-arbitrum?amount=

**Comment by jwtong** [comment]
jt/path-load-refactor-continued-1 is the correct branch to merge, no issue with main-sync-with-cutover

**Comment by just-a-node** [comment]
Merged into `main-sync-with-cutover`.
