### ISSUE TITLE
[main] Underlying network changed

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6041]
**Describe the bug**

This happens on all deployments forked from main.

This error crops up with a specific wallet connection state. Details below. 

<img width="519" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b806ed0f6de3ed5574363b191baf2dbcec32560/image.png" alt="image.png" />

**Link to ticket in discord**

**To Reproduce**
1. Go to bridge (defaults to sending ezETH from Ethereum to Arbitrum)
2. Make sure Metamask is fully disconnected from the site. Disconnect -> refresh page.
2. Switch to Arbitrum in Metamask
3. Make sure bridge page is still sending ezETH from Ethereum to Arbitrum
4. Click "Connect Wallet" -> choose Metamask -> connect
6. If #6040 isn't fixed yet, you may need to refresh to see the wallet connected state
7. Click "Switch to Ethereum". Should see MM switched to Ethereum
8. Send, see error above

To get it working, you have to:
9. Flip to sending ezETH from Arbitrum to Etheruem
10. Click "Switch to Arbitrum"
11. Send, see error above
12. Flip to sending ezETH from Ethereum to Arbitrum (the original path)
13. Click "Switch to Ethereum"
14. Send, this time it will prompt the transaction in MM correctly

**Comment by regexpressyourself** [comment]
I was able to reproduce this when there were failing coin gecko responses, but not with coin gecko working. 

Following the reproduction steps above on prod and local allow to me send a bridge request to metamask.

**Comment by just-a-node** [comment]
Have tested and able to reproduce this again with `main-sync-with-cutover` branch.

**Comment by just-a-node** [comment]
Now testing in: https://github.com/connext/frontend/pull/31
