### ISSUE TITLE
[ST] The user's transaction has not been completed for nearly 9 hours

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#6044]
Tx ID:https://connextscan.io/tx/0x48036afee92339ea0f99c914f5a416c9ed6645e39fa4d34605ac86883726988e
DC LINK:https://discord.com/channels/454734546869551114/1229659211932237845/1229659215778414662
From Polygan> Metis
![image](https://github.com/connext/monorepo/assets/92560156/7e115a0d-3389-4965-9325-65a39390d31c)

**Comment by prathmeshkhandelwal1** [comment]
All the metis transfers are stuck

**Comment by prathmeshkhandelwal1** [comment]
All the transfer should be clearing now, Issue raised due to relayers being out of funds

**Comment by QQHHUH** [comment]
https://connextscan.io/tx/0xdc036da52192a41ad8184b0d801978d17b160b385004a07bd52094566bb41800

Another case! Does this require the repeater to replenish funds manually, or?

**Comment by prathmeshkhandelwal1** [comment]
Hey @QQHHUH , Seems like this is not related to relayer. I am taking a more deeper look here

> https://connextscan.io/tx/0xdc036da52192a41ad8184b0d801978d17b160b385004a07bd52094566bb41800
> 
> Another case! Does this require the repeater to replenish funds manually, or?

**Comment by prathmeshkhandelwal1** [comment]
Resolved @QQHHUH 

> https://connextscan.io/tx/0xdc036da52192a41ad8184b0d801978d17b160b385004a07bd52094566bb41800
> 
> Another case! Does this require the repeater to replenish funds manually, or?

**Comment by prathmeshkhandelwal1** [comment]
Closing this out as completed
