### ISSUE TITLE
[ST] Insufficient gas for the destination gas fee when trying to bridge ezETH from Linea to Ethereum 

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6045]
**Describe the bug**
User is trying to bridge ezETH from Linea to Ethereum.

The user has enough ETH to pay gas on destination fees but UI says "insufficient gas for t he destination gas fee.

The balance: 
![image](https://github.com/connext/monorepo/assets/18751995/0b5bbff2-58d5-4627-867a-86e95ecdb9a4)

The error:
![image](https://github.com/connext/monorepo/assets/18751995/17d88b31-9169-403f-8b5f-0e1ec39fc7c8)

**Ticket**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7092575/conversation/565?view=List

**Comment by prathmeshkhandelwal1** [comment]
Not able to repro, Can you @ekbainova ?

**Comment by ekbainova** [comment]
@prathmeshkhandelwal1 user used Metamask interface - it works. Tried on connext UI in different browsers - not.

**Comment by ekbainova** [comment]
Another ticket:
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/562?view=List

**Comment by ekbainova** [comment]
https://discord.com/channels/454734546869551114/1230109357555843123

**Comment by jwtong** [comment]
Is this when they click "send" or does it show up even beforehand?

**Comment by oswy-cpu** [comment]
@jwtong it happens before they click "send"

**Comment by alexwhte** [comment]
<img width="772" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenQ4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4a398612b7dd097b6c0805473e6d7e9577a1e86/image.png" alt="image.png" />

**Comment by jwtong** [comment]
@ekbainova - may have been fixed in `main-sync-with-cutover` with balance fetching issues

**Comment by jwtong** [comment]
Should click on asset selection and see what ETH balance is would be helpful (don't change from ezETH to ETH, but just screenshot the balance as recorded by connext)
