### ISSUE TITLE
[ST] Execution reverted when bridging alUSD through our UI

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#6049]
**Describe the bug**
Users are unable to bridge alUSD due to `execution reverted`

Cases:

**[DC Case 1](https://discord.com/channels/454734546869551114/1229243391414374452)**
**[DC Case 2](https://discord.com/channels/454734546869551114/1229504901973938237)**

**To Reproduce**
1. Go to 'https://bridge.connext.network/'
2. Try to bridge alUSD from OP to Mainnet Ethereum.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/89958919/e812721e-05eb-48c2-a425-18285b0dd34e)
**Additional context**
Additional info: there was a [similar issue](https://github.com/connext/monorepo/issues/5513) in the past, supposedly only for transactions from Optimism to Arbitrum.

@oncall

**Comment by preethamr** [comment]
This is a known issue:
https://github.com/connext/monorepo/issues/5513#issuecomment-1883690277

**Comment by preethamr** [comment]
Right now there is enough `nextAlUSD` locked to support this transfer:
<img width="391" alt="image" src="https://github.com/connext/monorepo/assets/1195648/4c109fc4-1cbe-48a0-94e7-38f35f31c038">

**Comment by preethamr** [comment]
@0xanedi Can we ask the these two users to try again, since it has been > 12 hours since they saw these errors and alUSD contract looks good for the amounts they are trying.

**Comment by ekbainova** [comment]
2 More: 
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/540?query=alUSD&view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/563?query=alUSD&view=List

**Comment by alexwhte** [comment]
@prathmeshkhandelwal1 can you leave a comment on next step?

**Comment by prathmeshkhandelwal1** [comment]
Moving this in ToDo, as alchemix will be clearing out the prev locked liq on connext contracts and the de-register this asset where we are facing this, new alUSD/alETH tokens will be up.
To track that check the issue here: https://github.com/connext/monorepo/issues/5992

**Comment by prathmeshkhandelwal1** [comment]
VERY IMPORTANT: alUSD/alETH should not be up in our UIs, If we see any case we should be informed as soon as possible. Initing bridge now can put more work on alchemix team to migrate
cc: @ekbainova

**Comment by just-a-node** [comment]
Closing as alAsset contracts have been updated.
