### ISSUE TITLE
[ST] Base to Gnosis Slow Path USDC transactions not completing

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#6050]
**Describe the bug**
A transaction in USDC going from BASE to Gnosis that goes to slow path does not complete.

**[Link to ticket in discord](https://discord.com/channels/454734546869551114/1229159652420354099)**

**To Reproduce**
1. Go to https://bridge.connext.network/
2. Select BASE to Gnosis
3. Bridge

**Screenshots**
![image](https://github.com/connext/monorepo/assets/89958919/b2f98fc4-04ec-413e-9a82-6d80298f1229)
**Additional context**
[Connextscan](https://connextscan.io/tx/0xa4b05710aa4ac0710f920b92aefe2b9ab015a7eea7a7d3d5b6b1a53cca8b6751)

@oncall

**Comment by preethamr** [comment]
Has executed now.
