### ISSUE TITLE
Reconnecting wallet doesnt update state

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [connext/monorepo#6052]
## Background

In the `main-sync-with-cutover` branch, UI doesnt update proper wallet connection state after reconnecting. It shows connect wallet button after reconnecting.

### Steps to repro
- Go to `main-sync-with-cutover` branch and run locally
- Connect wallet and then disconnect and reconnect
- Wallet state still shows `connect-wallet` button

Img after reconnect
<img width="879" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejluQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--000ac8955182314b46283300b84cd3ea6553d983/Screenshot%202024-04-17%20at%2012.08.35%E2%80%AFAM.png" alt="Screenshot 2024-04-17 at 12.08.35 AM.png" />
 
After clicking connect button
<img width="460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZuQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0c558c56ecc34cec3739174f67f89d22e163d0a/Screenshot%202024-04-17%20at%2012.09.06%E2%80%AFAM.png" alt="Screenshot 2024-04-17 at 12.09.06 AM.png" />

## Definition Of Done

State updates properly after reconnect

**Comment by just-a-node** [comment]
Looks good now in current `main-sync-with-cutover`.
