### ISSUE TITLE
[ST] <Bridge transactions have been delayed by 30 hours!>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#6053]
Tx ID:https://connextscan.io/tx/0x93a3b0798d52ae498623605ca3a11569695c78aef91cd6fe100cc1fa165343b4
DC :https://discord.com/channels/454734546869551114/1229891241978761256/1229891247112454145
Token:oLIT
From Arb to ETH

![image](https://github.com/connext/monorepo/assets/92560156/242755ac-d375-4f44-b5ff-fbce1ce4f8a5)

**Comment by prathmeshkhandelwal1** [comment]
Not able to find specific issue here, Checking with core team what's wrong here

**Comment by prathmeshkhandelwal1** [comment]
Resolved.
