### ISSUE TITLE
[main] WETH labeled for balance instead of ETH

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6060]
**Describe the bug**

Selecting ETH to send shows WETH next to the balance (the balance shown is in ETH, though). This happens for all chains where ETH is an option for the origin chain.

<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbfaca38baab2bafd17ff1089c6b9475a2814eb6/image.png" alt="image.png" />

**Link to ticket in discord**

**To Reproduce**
1. Go to bridge
2. Set ETH as the asset for Linea, Arb, Opt, etc
3. See the balance labeled as WETH but showing the wallet's balance of ETH

**Comment by prathmeshkhandelwal1** [comment]
State handling was wrong, adding a fix

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/frontend/pull/40
