### ISSUE TITLE
[ST] Linea router not bidding

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6062]
**Describe the bug**
There's enough liquidity on linea side, but `nobidsreceived`

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/578?view=List

**Additional context**
https://connextscan.io/tx/0x91e55727bd3dca0a04d42f15b6b8e26406e7c975f1fa5b00d31b53215437578f?_gl=1*11yj794*_ga*MTQzNzM4ODY1Mi4xNzEzMzU4ODQ0*_ga_MPYZEDRVQ0*MTcxMzM1ODg0NC4xLjEuMTcxMzM1ODg5NS4wLjAuMA

@oncall

**Comment by MinistroDolar** [comment]
Yeah the router is down again:

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/807148fa-d045-4e6f-adf8-e68bc03af2b3">

router address: https://connextscan.io/router/0xc770ec66052fe77ff2ef9edf9558236e2d1c41ef

Last tx bidded (Apr 16, 2024 21:54:32 PM): https://connextscan.io/tx/0x2e58d6aa9a3364238a0cad63714cb4ed54ec9dfb6b8022ac8cd15d3dd280a76a

**Comment by MinistroDolar** [comment]
> Duplicate

Do you mean is duplicated bc of this [issue](https://github.com/connext/monorepo/issues/6014)?

The router came back to life and then rip again like 16 hours ago.

Also, there is another Linea router down (more than 24 hours ago)
https://connextscan.io/router/0x58507fed0cb11723dfb6848c92c59cf0bbeb9927
