### ISSUE TITLE
Carto transfers not updating slippage bumps

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6063]
**Describe the bug**

For example, this bump txn: https://polygonscan.com/tx/0x74259e3159ca7a7b8fdd5c088695184e7a9404bc9a12c6b640c5d1947a6390b0

It's reflected in subgraph but not Carto. 

**Additional context**

We're seeing Carto errors in `bindTransfers` context.

@oncall

**Comment by ekbainova** [comment]
1 TX:
https://connextscan.io/tx/0x3c41dc4382c59bdf62f65f929a2ef6aa9426f2abbb949e5d36220167ab6c705d 
Bump:
1) https://polygonscan.com/tx/0x74259e3159ca7a7b8fdd5c088695184e7a9404bc9a12c6b640c5d1947a6390b0
2) https://polygonscan.com/tx/0x659b73b5a4b4f34c29d95b308de2256c3ce6b87715db25d7c624e91af4761ef2 

2 TX: https://connextscan.io/tx/0xbcee0465ee35ae6989c199e132bb262a0a8455b83745d57b14c5b9d4400df14d
Bump: https://polygonscan.com/tx/0xe7f729913efe11a5c6fd8a37bd5c09396975518b5fe3d70e5e717f6013e24352 

3 TX:
https://connextscan.io/tx/0xee2624d208e7bf8cf37efc01244e92db68306d8cf84f67378be68bba743cbac5
Bump:
https://polygonscan.com/tx/0x7cb4f82183a0ee61b2eb01f49f5a605621b5814c0a314619866b31fbfa03287b

4TX:
https://connextscan.io/tx/0x37a5c58f3e96e890d3ecd6751e38704cacd46b44306f44e3ae4dfa7d6de49352
Bump:
https://polygonscan.com/tx/0x639b90329f34fe5178c4c86cfe523ae8e56b240d0f15c81e279d683f1606caac

**Comment by preethamr** [comment]
Working with bware, will push a hotfix as needed, shortly.

**Comment by preethamr** [comment]
Root caused it:
carto poller for fee increases got stuck on polygon, fetching the same 100 from the checkpoint `1712803193` which is likely when we did mass realer fee bumps.

**Comment by preethamr** [comment]
Resolved.
These transfers are no completed.
