### ISSUE TITLE
[ICE: 19] Wrong number of chain is displayed

### ISSUE THREAD

**Issue by par94** [connext/monorepo#6069]
**Describe the bug**
Explorer shows 11 chains instead of 10 chains displayed

**Link to ticket in discord**

**To Reproduce**
1. Go to https://connextscan.io
2. Only 10 chains are displayed, but the number in the top right corner shows 11
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVYxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--052cfbfa5a051611da60771f018989da48f7e5cf/Screenshot%202024-04-18%20at%2018.15.44.png" alt="Screenshot 2024-04-18 at 18.15.44.png" />

**Screenshots**

**Additional context**
@oncall

**Comment by ekbainova** [comment]
Should check figures, guess it is fixed.
