### ISSUE TITLE
[main] Estimated time doesn't show up for smaller amounts

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6074]
**Describe the bug**

Irrespective of the asset and chain path, using smaller amounts doesn't show an estimated time:

<img width="586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelIyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d86e1654ddaf5f590887a1c8072ff12fc3a5064/image.png" alt="image.png" />

**Link to ticket in discord**

**To Reproduce**
1. Go to bridge
2. Choose any path and any asset
3. Use a pretty small amount
4. See that estimate doesn't show

**Comment by regexpressyourself** [comment]
Looking like the most likely culprit is missing `router_asset_balances_data` here: https://github.com/connext/frontend/blob/main-sync-with-cutover/apps/connext-bridge/components/bridge/index.tsx#L3712

**Comment by just-a-node** [comment]
Clarifying, you should be able to bridge Arb USDC.e, the address is `0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8`.

**Comment by jwtong** [comment]
https://github.com/connext/frontend/pull/47 - fix

**Comment by just-a-node** [comment]
@jwtong Still not seeing the estimated time for situations like this:

<img width="493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8e9d0f15d621322cdf405180d0fffd1a7c2bd5b/image.png" alt="image.png" />

**Comment by just-a-node** [comment]
Ignore ^, was testing on wrong deployment.
