### ISSUE TITLE
[main] Relayer fee not being converted to native asset

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6075]
**Describe the bug**

With Ethereum as destination chain, the relayer fee estimate is being requested in USD. However, it's not being converted to the native asset that will be paid by the user when the estimate is displayed.

<img width="559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBengyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4d0f4371a2b9cc8dae5c87ddc4ea1157448df22/image.png" alt="image.png" />

**Link to ticket in discord**

**To Reproduce**
1. Go to bridge
2. Use Eth as destination
3. Check fee request params and response is in USD
4. See that UI displays USD value, not converted to ETH

**Comment by regexpressyourself** [comment]
https://github.com/connext/frontend/pull/44

**Comment by just-a-node** [comment]
Tested on preview.

**Comment by just-a-node** [comment]
Reopening this because we noticed an issue with choosing the native asset as the fee asset. If you go into advanced options and select aETH as the asset instead of the default USDC.e, you'll see that the "Gas on destination" is still in USDC.

<img width="817" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZLQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b492de90fad498840cd8fac36144a5eee13a4cb8/image.png" alt="image.png" />

**Comment by regexpressyourself** [comment]
@just-a-node Got a fix pushed up here:https://github.com/connext/frontend/pull/48

**Comment by just-a-node** [comment]
Tested, looks good! Merged.
