### ISSUE TITLE
Connextscan link should show up in the new entry that appears under "Latest Transfers"

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6077]
**Describe the bug**

After a new transaction is fired off, a new item in the 'Latest Transfers' panel appears but the transaction link to Connextscan doesn't show up.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDEzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91b16952522deba0ddc67a98036b7f4292046265/Round%203%20Screen%20Recording.mov)

**To Reproduce**
1. See attached recording. It's not clear if all transfers behave this way.

**Screenshots**

**Additional context**
@oncall

**Comment by jwtong** [comment]
This code is all windy and confusing, I have a guess of what is the issue. I think I can improve the behavior, but I don't want to fire off transaction after transaction to test. I'll probably implement a solution for QA and then we can discuss back and forth.,

**Comment by alexwhte** [comment]
removed as high, please link tickets and reset as needed
