### ISSUE TITLE
Arb WETH pool not showing historicals

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6078]
**Describe the bug**

Arb WETH pool isn't showing historical data. Other asset pools seem fine. Need to investigate whether this is all WETH pools or all Arb pools. What's the pattern here, why isn't the data being returned? 

<img width="961" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1IzQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f694a82e2029da9a0982146f31f5cc3c31e72724/image.png" alt="image.png" />

**To Reproduce**
1. Go to Arb WETH pool

**Comment by jwtong** [comment]
https://postgrest.mainnet.connext.ninja/daily_swap_tvl?day=gt.2024-04-17 - returns []

**Comment by just-a-node** [comment]
Backend issue. Not only present in `main-sync` so removing the `[main]` tag and this should not block cutover.

**Comment by regexpressyourself** [comment]
@just-a-node @ekbainova Question on this:

My assumption is that we should see daily TVL and volume data charted here. Are we supposed to be seeing line charts for these pools? The code appears to get a single day's stats but not getting 30 day, 90 day, etc. 

Just want to make sure I understand the intended functionality before wiring up a fix.

**Comment by regexpressyourself** [comment]
https://github.com/connext/frontend/pull/61

**Comment by regexpressyourself** [comment]
Fixes deployed here: https://frontend-connext-bridge-9b8ta04y6-connext-979dc950.vercel.app/?vercelToolbarCode=Do8pYbCYcjEkX8x

**Comment by just-a-node** [comment]
This is now blocked by backend data issues. We're missing stableswap volume data for past few weeks
