### ISSUE TITLE
[ST] None of Mode routers are bidding for ezETH transfer 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6079]
**Describe the bug**
9.9 ezETH stuck between Linea and Mode

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/596?view=List

**Additional context**
https://connextscan.io/tx/0xd421b317a69e29fb31131944b50ba34321edc987a1e0ef7cd46e984d7da13437

@oncall

**Comment by alexwhte** [comment]
threre is available liquidity 
![image](https://github.com/connext/monorepo/assets/37959170/1ba5288c-4cae-454c-837e-ee95a74876bd)

**Comment by alexwhte** [comment]
We are seeing Bware bidding https://connextscan.io/router/0x8cb19ce8eedf740389d428879a876a3b030b9170

**Comment by alexwhte** [comment]
@oswy-cpu please drop in other examples? we are still investigating

**Comment by preethamr** [comment]
I currently don't see any in `XCalled` state on that route:
<img width="1216" alt="image" src="https://github.com/connext/monorepo/assets/1195648/c8a54737-900b-4418-8eea-d0dcba220600">

**Comment by preethamr** [comment]
@oswy-cpu please close if this issue is not ongoing.
