### ISSUE TITLE
[main] Router add liquidity should show nextAssets

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6080]
**Describe the bug**

The asset selector for adding liquidity to a router on a non-Ethereum chain shows the adopted asset (WETH, USDC, etc) instead of the local asset (nextWETH, nextUSDC, etc). 

<img width="922" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmw3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eeb1c6c3cf24f9ac6c6de1cfc633efd944eb703b/image.png" alt="image.png" />

Context:
- The adopted version of a token is the "most used / popular" version of the token on that chain.
- The local version is the Connext-mintable version (usually prepended with "next", eg "nextUSDC").
- On Ethereum, there are no pools because Ethereum is the canonical domain for all assets (as of now). This means an asset on Ethereum is both the adopted version and the local version of the token. 
- On all other chains, there are pools comprising "Asset" <> "nextAsset". "Asset" is the adopted version and "nextAsset" is the local version. Users send/receive "Asset" while Connext swaps to the "nextAsset" under the hood (because we can't directly bridge "Asset").
- On each chain, routers add liquidity of *local* assets. For Ethereum, this means all assets as is. For non-Ethereum chains, this means they should add the "nextAsset" version of all assets. This is why this is a bug - we need to allow routers to add the "nextAsset"s for non-Ethereum chains.

**Comment by regexpressyourself** [comment]
Identified a fix: https://github.com/connext/frontend/pull/46
