### ISSUE TITLE
[ST] Linea router down again

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6081]
**Describe the bug**
Linea router https://connextscan.io/router/0x58507fed0cb11723dfb6848c92c59cf0bbeb9927 is down [again](https://github.com/connext/monorepo/issues/5976). It doesnt bid since 4 days.

@oncall

**Comment by preethamr** [comment]
Notified Hashquark about their router

**Comment by QQHHUH** [comment]
Can I attach here some of the bridging transactions involved?

https://connextscan.io/tx/0xe3705ec0927cfad94628487f67bc84fcf0c2cc24c530116384ae5addeaab0ca3 / 22hours
https://connextscan.io/tx/0x42d92b13dd6570b8b55198915188d1aa35ca5cf4195f74f7a4e535d278d2f81d /10hours

**Comment by oswy-cpu** [comment]
Up, down again 

https://connextscan.io/tx/0x3f003f28fb1d11508bc9758f27383e99700bccbd24aa0ec8e30d020b59adcdc6

**Comment by alexwhte** [comment]
dupes
