### ISSUE TITLE
All transfers to Metis are not processing for more than 17h

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#6082]
Transactions are in pending for more than 17 hours (last completed transaction was like 18 hours ago
![image](https://github.com/connext/monorepo/assets/93597601/d6e2e1b3-f47f-4f1e-b865-1dfdef80416e)
Bot fast and slow paths are down
@oncall

**Comment by ValerywArz** [comment]
All transactions are stuck once again (for 10 hours now)

**Comment by preethamr** [comment]
After funding these are are now completed.
