### ISSUE TITLE
[ST] DAI appears as supported asset to Linea - Weird estimations (Li.Fi UI issue)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6087]
**Describe the bug**
Seems that Li.Fi UIs allow users to initiate a bridge of DAI to Linea despite that we don't support that asset on that chain. (and also it's providing weird estimations)

<img width="740" alt="image" src="https://github.com/connext/monorepo/assets/26097731/98cceca7-a780-4c30-835d-574352a11505">

Now, there is at least 1 users with his txn stuck:

https://connextscan.io/tx/0x01a994d0e80e8e06bd00064a9c060bd08dd2912cbb5f51e64e7e7fd88a53c5a3?source=search

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1232016619220242442

@oncall

**Comment by just-a-node** [comment]
LiFi will be disabling this route in the next ~2 days. On our UI, this should not be possible (the screenshot shows Eth as destination, btw).

**Comment by MinistroDolar** [comment]
> LiFi will be disabling this route in the next ~2 days. On our UI, this should not be possible (the screenshot shows Eth as destination, btw).

Yeah, In my haste I did not notice that the chain was automatically changed.

**Comment by alexwhte** [comment]
Closing as route being removed
