### ISSUE TITLE
[ICE: 12] Pool volume stops on April 11 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#6088]
Should be up to today 

<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fdf27efb7c1aff823cad6affb1db5a5f82faee3/image.png" alt="image.png" />

**Comment by alexwhte** [comment]
reported by linea

**Comment by ekbainova** [comment]
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelNyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd713cf257419acf3354f2d1f8d7e3dafc82d735/Screenshot%202024-05-01%20234145.png" alt="Screenshot 2024-05-01 234145.png" />
The BNB-WETH pool for the past 7/30 days shows inconsistent historical data figures.

**Comment by alexwhte** [comment]
User reported a balance issue 
![image](https://github.com/connext/monorepo/assets/37959170/500b7e03-34df-4dcf-bafa-8f48b26836ce)

**Comment by alexwhte** [comment]
we should combine this with #5475 i think?

**Comment by alexwhte** [comment]
[Uploading... image.png]

**Comment by just-a-node** [comment]
This is also #6078

**Comment by just-a-node** [comment]
Pool data coming from DB is missing for recent weeks. This will be handled in #6088.
