### ISSUE TITLE
[ST] Gnosis Router is down

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6092]
**Describe the bug**
Main router on Gnosis is down (last bid was more than 24 hours ago)

https://connextscan.io/router/0x048a5ecc705c280b2248aeff88fd581abbeb8587

And also these 2 routers aren't bidding this tx (i don't know why):

Routers:
https://connextscan.io/router/0x97b9dcb1aa34fe5f12b728d9166ae353d1e7f5c4
https://connextscan.io/router/0xc4ae07f276768a3b74ae8c47bc108a2af0e40eba

Tx: https://connextscan.io/tx/0x25c58b46f76f7ede8dbaa15bbf79a12f2edfcb42247983f0c06c459387d1a771

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/56a45a31-5c63-4ab9-bce1-123ea29953d8">

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1232454012931145758

@oncall

**Comment by MinistroDolar** [comment]
seems working now.

**Comment by alexwhte** [comment]
working
