### ISSUE TITLE
[ST] Wrong ETA for Slow path txns to Mainnet

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6093]
**Describe the bug**
A user reported a bug: our UI says that a txn going through the Slow Path to Ethereum Mainnet will arrive in less than 5 hours when that Path takes like 12.

<img width="387" alt="image" src="https://github.com/connext/monorepo/assets/26097731/a101c0a9-fe2b-4dcd-b889-878f20d14652">

![image](https://github.com/connext/monorepo/assets/26097731/b855f333-6832-4789-933c-b479a94810f9)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1232474700295180308

@oncall

**Comment by alexwhte** [comment]
fixed
