### ISSUE TITLE
Hyperlane xERC20 Prototype

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#6101]
## Background
We proposed for Hyperlane to be the ezETH bridge while we complete Chimera this quarter. 

This enables Renzo to continue expansion and competition on a transport layer that we will later be able to adopt 
More context on strategic goal: https://www.notion.so/connext/Renzo-Connext-Hyperlane-Proposal-e92b6fc98b05468ab8d6f4ec96862439

Hyperlane provided their feedback and stance on the proposal here 
https://hyperlanexyz.notion.site/Hyperlane-Connext-Renzo-Implementation-e38cc856034643e4b6d98c38b23cd5d6

## Solution
We need to size out what it would take to have a UI with native xERC20 bridging through Hyperlane routes 

Use xERC20 adapter to ensure xERC20 works in Hyperlane transport layer https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/3486

## Definition Of Done
We have a clear sizing of the below:
- [ ] Users can bridge ezETH as an xERC20 between Ethereum and L2s (where Hyperlane is deployed) 
- [ ] Users can bridge ezETH through a UI with Hyperlane routes
- [ ] Approval for bridging UX is 2 steps or less 
- [ ] Users can offramp ezETH on Blast through this UI
- [ ] Assets are minted and burned as expected 
- [ ] The UI is maintained over time

**Comment by just-a-node** [comment]
Next step: poke HL on SDK + warproute UI work.

**Comment by just-a-node** [comment]
No longer doing.
