### ISSUE TITLE
[ST] <Slippage error occurred in a large area of ezETH>

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#6103]
https://connextscan.io/tx/0xd0f6dcaeb8eecb16e403ef74c93fdb08d254b4ace23f5ad7ff03f1be8a1c0126
https://connextscan.io/tx/0x30c569111b5ef6fd8b5b4423ddf1359331cf6aeefae59c4cc154d5333607f8ed
https://connextscan.io/tx/0x3001bf631f590a4e3a419254996aa902aae321fd9eb9b53d9be59f19f612d431
https://connextscan.io/tx/0x7f3dc11649860297638451100c01d76d48dc65ffabec78ea4a7ddfa2d4e8d112
In theory, ezETH's bridge should not have slippage errors.

![image](https://github.com/connext/monorepo/assets/92560156/41d93952-b663-47b9-9af7-ce3595ecb8ff)

**Comment by MinistroDolar** [comment]
Slippage error is happening also for txns where ezETH is not involved:

The user increased slippage and it keeps asking for more

https://connextscan.io/tx/0xf752c5d9410828500bee71665a91d2ed9b94969dcf9f4a9b628c8d6bde4d8bde?source=search

discord: https://discord.com/channels/454734546869551114/1233057732387672075

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/c9f01eec-fc29-492c-99f4-8a99b7b7e046">

another case:

https://connextscan.io/tx/0xade4feb550f025383e2eff27bb52c3d23beb08b2d410eb09712b0eff9e6027c9?source=search

discord: https://discord.com/channels/454734546869551114/1232844355090513972

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/cac5f830-8506-4633-a9a7-c9f809f16dd6">

**Comment by MinistroDolar** [comment]
Another case, with ETH: (weird bc it has 4% slippage tolerance and its asking for 3% lol)

https://connextscan.io/tx/0x28d6d468fc8409c5ce736e0fef27585701cd6be8c6cf1bc411bcfe8077d998fe?source=search

discord: https://discord.com/channels/454734546869551114/1233061181087027312

<img width="1916" alt="image" src="https://github.com/connext/monorepo/assets/26097731/8b560c0a-b81a-44d0-a655-e996dd0d850b">

**Comment by oswy-cpu** [comment]
Another one with USDC: https://discord.com/channels/454734546869551114/1233065056015482991

Scan: https://connextscan.io/tx/0x4dce35285eef0ea05c93c43c361670ff39c8f3cc52a3288f6bfa4f687015ca0b

**Comment by just-a-node** [comment]
For ezETH (and other xERC20s) it should never be the case that `lowSlippage` is an error.

**Comment by MinistroDolar** [comment]
> For ezETH (and other xERC20s) it should never be the case that `lowSlippage` is an error.

Yeah but for some reason the UI is showing slippage error for ezETH going through the slow path:

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/18080bbf-582f-41f4-977a-6ec5e1609bd2">

https://connextscan.io/tx/0xb6377b96ce824ab3dbef480870e942412dee8249c95769db65b2398dd44e491d

**Comment by ekbainova** [comment]
@prathmeshkhandelwal1 @just-a-node  add some guardrails on the UI side to block slippage errors from being surfaced for xERC20s entirely because that should never happen (even if db says otherwise)

**Comment by alexwhte** [comment]
i think we found the issue on this

**Comment by just-a-node** [comment]
> @prathmeshkhandelwal1 @just-a-node add some guardrails on the UI side to block slippage errors from being surfaced for xERC20s entirely because that should never happen (even if db says otherwise)

Let's file into a separate enhancement. Keep this current task to check if https://github.com/connext/frontend/commit/a0923bfee3f0046ef91bd356e94bf3284e26376b fixes these.

**Comment by just-a-node** [comment]
@jwtong 
https://connextscan.io/tx/0xff572a48a9128ac29cc862367ded36945de5e950b3a6dae7590d2edc28472198 example of a txn where the slippage issue is still present

**Comment by ValerywArz** [comment]
https://connextscan.io/tx/0xade4feb550f025383e2eff27bb52c3d23beb08b2d410eb09712b0eff9e6027c9 this one is still pending too

**Comment by ekbainova** [comment]
@jwtong ping

**Comment by LayneHaber** [comment]
found a bug, pushed to prod. should monitor for more cases and if none close out issue

**Comment by just-a-node** [comment]
Unhardcoding commit: https://github.com/connext/frontend/commit/57756cdabfad167f6c3eef6de7d6fbf8c60c7a59

Monitor in QA.

**Comment by LayneHaber** [comment]
closing, no new bugs
