### ISSUE TITLE
[ST] Connext router is not bidding

### ISSUE THREAD

**Issue by par94** [connext/monorepo#6105]
**Describe the bug**
Connext router is not bidding

**Link to ticket in discord**

**To Reproduce**
1. Go to https://connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c
2. Click on the last transfer
3. See error

@oncall

**Comment by preethamr** [comment]
RCA, Connext router was affected by this:
https://github.com/connext/monorepo/issues/6089
