### ISSUE TITLE
[ICE: 11] Token selector is not visible

### ISSUE THREAD

**Issue by par94** [connext/monorepo#6106]
**Describe the bug**

**Link to ticket in discord**

**To Reproduce**
1. Go to https://connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c
2. See error

**Screenshots**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGVRQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a3707cd31b3ba3baaff668403bf07531596b748/Screenshot%202024-04-25%20at%2002.16.59.png" alt="Screenshot 2024-04-25 at 02.16.59.png" />

**Additional context**
@oncall

**Comment by ekbainova** [comment]
Can't repro it with Chrome. @regexpressyourself Could you check it?

**Comment by regexpressyourself** [comment]
> Can't repro it with Chrome. @regexpressyourself Could you check it?

@ekbainova I see this token selector, but I don't see the usual list. Is that expected, or is this a bug?

<img width="660" alt="image" src="https://github.com/connext/monorepo/assets/5316399/ce7d762e-bf0d-48b1-8dfd-9c5486b47e77">
