### ISSUE TITLE
[ST] insufficient funds

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6108]
**Describe the bug**
UI always shows insufficient funds on OP-MODE route. 

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1233010668257546341

**Screenshots**
<img width="572" alt="image" src="https://github.com/connext/monorepo/assets/74738120/18a3ecc9-63eb-4089-b0ef-8b12dd304565">

@oncall

**Comment by MinistroDolar** [comment]
Another case:

![image](https://github.com/connext/monorepo/assets/26097731/3083e5e2-ec23-4fe2-a6ce-c60d159f99f5)

Discord: https://discord.com/channels/454734546869551114/1233063761930092584

**Comment by MinistroDolar** [comment]
Another case, with nextUSDC:

![image](https://github.com/connext/monorepo/assets/26097731/393f5541-e96d-4045-bf87-dc9cce0d8ade)

https://discord.com/channels/454734546869551114/1233072091041890428

**Comment by MinistroDolar** [comment]
Another case, ETH Arb to Mode:

![image](https://github.com/connext/monorepo/assets/26097731/1506d47d-19c6-4d15-a5fe-d5a8df937b6c)

https://discord.com/channels/454734546869551114/1233115537328967700

**Comment by ekbainova** [comment]
Here is the list of past tickets:
https://app.intercom.com/a/apps/qge2vd8z/inbox/inbox/conversation/645
https://app.intercom.com/a/apps/qge2vd8z/inbox/inbox/conversation/643
https://app.intercom.com/a/apps/qge2vd8z/inbox/inbox/conversation/644
https://app.intercom.com/a/apps/qge2vd8z/inbox/inbox/conversation/647

**Comment by regexpressyourself** [comment]
Seeing a mismatch of contract addresses. Not sure yet why that's occurring.

**Comment by regexpressyourself** [comment]
https://github.com/connext/frontend/pull/52

**Comment by regexpressyourself** [comment]
Closed with https://github.com/connext/frontend/pull/52
