### ISSUE TITLE
[ST] WETH Pool deposits isn't working 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6109]
**Describe the bug**
`execution reverted: mint < min` appears when we trying to deposit funds in [WETH pool](https://bridge.connext.network/pool/ETH-on-base) on base.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1232934046464479264

**Screenshots**
![image](https://github.com/connext/monorepo/assets/74738120/0c66d9ce-f083-4a7f-ba91-4eb415ca0699)

@oncall

**Comment by ekbainova** [comment]
Need to check what else has the same error @ekbainova

**Comment by jwtong** [comment]
Can we setup some WETH on the dummy wallet?

An arbitrary scale factor for min seems to be being applied here
```

            const rawMinToMint = await sdk.sdkPool.calculateTokenAmount(
              domainId,
              contract_address,
              amounts,
              true
            )
            const minToMint = rawMinToMint.mul(9995).div(10000).toString()
```

**Comment by ekbainova** [comment]
One more: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/652?view=List

**Comment by ekbainova** [comment]
@jwtong DM Eddie if you need the wallet for testing it.

**Comment by just-a-node** [comment]
Added WETH to base on wallet.

**Comment by just-a-node** [comment]
FYI @jwtong this an arbitrary buffer applied to the min amount coming back from the SDK. Looks like the buffer is too small so we're going to 10x it to 50bps: https://github.com/connext/frontend/pull/57

Looks like a magic value right now, we can consider pulling into a better variable name later.

**Comment by just-a-node** [comment]
https://frontend-connext-bridge-git-ey-6109mina-9792b0-connext-979dc950.vercel.app/
