### ISSUE TITLE
Blast withdrawel notice 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#6115]
Needs to be more clear 

<img width="491" alt="image" src="https://github.com/connext/monorepo/assets/37959170/7db9cfef-a116-49de-b66d-a80d6ca37175">

Please update:
1. Make it red
2. Change the text "Withdrawals of ezETH are not yet available with Blast native bridge. This is using the Blast native bridge directly, not the Connext bridge protocol. Please be aware and reach out with any questions."

**Comment by alexwhte** [comment]
https://bridge.connext.network/EZETH-from-ethereum-to-blast

**Comment by just-a-node** [comment]
Done

<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeStXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01a716d0acd4e60ec3eb5751c756e0f47ef77d1a/image.png" alt="image.png" />
