### ISSUE TITLE
Slippage --> Nowhere to bump --> Gets sorted out alone

### ISSUE THREAD

**Issue by maxlomu** [connext/monorepo#6125]
2nd transaction today that requires me to bump slippage.

![image](https://github.com/connext/monorepo/assets/57088593/a572a21a-ce32-4295-94b1-37d4621b91dc)

When I click on click here
It opens an empty box

Then after a few seconds the transaction is confirmed
(0x4ef914544b2fe7b5a34bb2fce464d8fbc25e2d010bfa0cd6997d999887cde6d5 tx id)

**Comment by maxlomu** [comment]
To note my slippage is set at 3%

**Comment by LayneHaber** [comment]
there is always a chance that the slippage behavior gets sorted out alone as its dependent on the network state at the time of execution.

I'm not seeing the transfer in [connextscan](https://connextscan.io/tx/0x4ef914544b2fe7b5a34bb2fce464d8fbc25e2d010bfa0cd6997d999887cde6d5), is that the right ID? `

**Comment by ekbainova** [comment]
I had the same issue with this transfer: https://connextscan.io/tx/0x6a700478ac19f9eee76b4a1d47e89bdec5ba482cce0eaa6aedec9ed8df8d90a6?_gl=1*15sn2d1*_ga*MTg1NTIwODk5MC4xNzEzNzk1NDI4*_ga_MPYZEDRVQ0*MTcxNDQxNzg5Mi4xOC4xLjE3MTQ0MTc4OTYuMC4wLjA.

Here is the screenshot: https://www.notion.so/connext/Round-4-90e17afcc10d47b2a266273669644cb3?pvs=4#3f099c1c507c425d87eeec42ff949e4d
