### ISSUE TITLE
Set estimated destination time to 12 hrs for all SLOW transfers with Ethereum destination

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#6128]
Users are expecting 5 hours. Current latency is around 12 hours 
We should set Estimated Time to <12 hours for all transfers (any asset) to Ethereum destination

![image](https://github.com/connext/monorepo/assets/37959170/85c7927f-15d7-43a5-ae0d-28d36cfac2a5)

**Comment by regexpressyourself** [comment]
https://github.com/connext/frontend/pull/55

**Comment by just-a-node** [comment]
@alexwhte could you confirm if this is for *all* transfers to Ethereum including fast/slow or just slow?

**Comment by alexwhte** [comment]
updated for slow only

**Comment by alexwhte** [comment]
sorry missed that detail

**Comment by regexpressyourself** [comment]
:+1: Updated!

**Comment by regexpressyourself** [comment]
See deploy here: https://frontend-connext-bridge-git-sm-sof-6128-9b02d3-connext-979dc950.vercel.app/EZETH-from-arbitrum-to-ethereum?amount=1
