### ISSUE TITLE
[ICE: 35] routers on Mode are not bidding

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6137]
**Describe the bug**
It seems none of routers on Mode are bidding for this transaction: https://connextscan.io/tx/0xf8912996ca08c676f2217e82d3ccac3a7055c1a16620b160e46d1b2fd8bf24ad

**Link to ticket in discord**

https://discord.com/channels/454734546869551114/1234951068681638010

@oncall

**Comment by alexwhte** [comment]
this router is bidding https://connextscan.io/router/0x6fd84ba95525c4ccd218f2f16f646a08b4b0a598
not sure why it was slow though

**Comment by alexwhte** [comment]
queueing up to check

**Comment by ekbainova** [comment]
Was it sufficient to ask Bware Labs to restart the router? 1:38 is not too long. @alexwhte how to check it?
