### ISSUE TITLE
[ICE: 25] XCalled transfers are not displayed

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6142]
**Describe the bug**
Connextscan doesn't display filtered XCalled transfers.

**To Reproduce**
1. Go to 'https://connextscan.io/transfers'
2. Click on 'XCalled status'
3. See error

**Screenshots**
<img width="1661" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3l0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0f33f434097a4ff4207eb747ed7cb18848b3922/image.png" alt="image.png" />

**Comment by regexpressyourself** [comment]
@ekbainova Is this still occurring? I'm not seeing the error live: https://connextscan.io/transfers


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEhjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--720a2e233c6fcd2fa9dc78939615486c1b0c844d/Screen%20Recording%202024-05-14%20at%209.56.16%E2%80%AFAM.mov)

**Comment by just-a-node** [comment]
@ekbainova Continue monitoring for more cases of this error.
