### ISSUE TITLE
[ICE: 8] EXECUTION ERROR - DAI from ARB to Base stuck (unsupported path)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6143]
**Describe the bug**
The user tried to send DAI to Base using an embedded wallet on transfer.xyz (erc-6900). The aggregator chose Connext but that asset is not supported on Base.

https://connextscan.io/tx/0x7fcad6fde48b266752bcdd3de080a00cfaf51c4717472ed1e4e1a35e91f41e2d

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/636744e1-94c3-4b3d-b048-26ca6d410ae1">

The user is already in contact with the team of the aggregator in question, in particular, to give them notice to remove the route.

He has also shared with me the information that DAI appears in Connext's docs as a supported asset in Base: 

https://docs.connext.network/resources/deployments#base

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1235675982820675715

<img width="1142" alt="image" src="https://github.com/connext/monorepo/assets/26097731/a1a4ed71-ad65-47df-aa8d-65b182aeb7da">

**Comment by just-a-node** [comment]
User refunded.
