### ISSUE TITLE
Mode subgraph is broken

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#6149]
Scan Link:https://connextscan.io/tx/0x620d6be72cee942d5204b5fc2b316f98d90ca0ee33864357f543f4d867f52208

Wallet:0x65395a0331b23f3fe62532cacac2b5e5d0c45e44

From Mode>ETH

Token:ezETH

amount:90.54

![Uploading image.png…]()

**Comment by ekbainova** [comment]
One more: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/688?view=List
