### ISSUE TITLE
Mode subgraph is broken_2

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6150]
**Describe the bug**
Arb routers are not bidding for ezETH tx from Mode 

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/681?view=List

**Additional context**
https://connextscan.io/tx/0xbe261f7581815f3e906f09762e1933a770c2013e6dd48735c8c691a02d22b323
@oncall

**Comment by oswy-cpu** [comment]
It seems the problem larger - another WETH tx stuck for the same route:

TX: https://connextscan.io/tx/0x95ef7288cdb5cb02c1d407b9008b7c1eee521b815bcb09fb927cac4f2aafabe8
Ticket: https://discord.com/channels/454734546869551114/1237390728540196977

**Comment by MinistroDolar** [comment]
Another one MODE to BASE

TX: https://connextscan.io/tx/0xf4bc13344b7a93030a066a0e259f336907c2a014a634538958cf33f88c880b62

Ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/680?view=List

Seems that the issue is on MODE side.

**Comment by MinistroDolar** [comment]
More cases:

Mode to ARB

https://connextscan.io/tx/0x1f2ba6143da75caa7b428d067d3bdc989d257fa1a156999b831d8dcb556be3ba?source=search

Ticket: https://discord.com/channels/454734546869551114/1237396476481638500

Mode to ARB

https://connextscan.io/tx/0x147a59e985701c067b908df14e52d2f6c6b3270bf328367b480be7db1f014b51

Ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/685?view=List

Mode to ARB

https://connextscan.io/tx/0xa5678d84825b2caa84f9d0894e265bcf157d7da8fc1dffb9f0ae7df5f1edb242

Ticket: https://discord.com/channels/454734546869551114/1237398818685714574

BNB to ARB (i don't know if it's related)

https://connextscan.io/tx/0x1ac78e29f6ef6e774b99d4b0e53dacdcb31732a65bae519a5999f4a9898673b0

Ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/682?view=List

Polygon to BASE (i don't know if it's related)

https://connextscan.io/tx/0x50fb7a1ebb08e2b03ccc19dc8daad290fec2a6f6c1e0a63f4d3ceae960b35b66

Ticket: https://discord.com/channels/454734546869551114/1237398283928993886

**Comment by oswy-cpu** [comment]
One more Mode -> Base

tx: https://modescan.io/tx/0x09133162e26afed639d5196192329226521c78c94bc957e3685a52800a98ace4
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/688?view=List

**Comment by oswy-cpu** [comment]
another one:

tx: https://connextscan.io/tx/0x88ed89613e7b208b72dfdafd383897f699eb10acf427edbecef41cd4096d3474
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/690?view=List

**Comment by oswy-cpu** [comment]
another one

tx: https://connextscan.io/tx/0xc0922887a35942b5fe385c45164ab59ebc43240ba6fa7289144db412076b4de5
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/692?view=List

**Comment by oswy-cpu** [comment]
tx: https://connextscan.io/tx/0x620d6be72cee942d5204b5fc2b316f98d90ca0ee33864357f543f4d867f52208
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/693?view=List

**Comment by oswy-cpu** [comment]
txid: 0x47f8c78a2cbf2b63b3d7e0149c32ac7fc092830723a1aa26d4b08652a92483e2
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/698?view=List

**Comment by oswy-cpu** [comment]
txid: 0xa96a8c8521b22b08d57ccc09f42e8761bb3d64ed951378fd7b0521ea5285a4c1
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/699?view=List

**Comment by oswy-cpu** [comment]
txid: 0x47f8c78a2cbf2b63b3d7e0149c32ac7fc092830723a1aa26d4b08652a92483e2
ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/697?view=List
