### ISSUE TITLE
[ICE: 12] RPC bug UI <could not detect network>

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6153]
**Describe the bug**
It is impossible to change the Wallet from MetaMask to OKX,
The UI bug called: <could not detect network>

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1237667306608529469

**Screenshots**
<img width="904" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9FQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354c120f77fc335181ab461dc1d22f4adcdcd5ea/image.png" alt="image.png" />

<img width="1560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNERFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91208af089bb6a28fb88813ef7831a0a85841490/image.png" alt="image.png" />

**Comment by ekbainova** [comment]
I guess one more: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/705?view=List

**Comment by ekbainova** [comment]
@regexpressyourself to do for you

**Comment by regexpressyourself** [comment]
@ekbainova I'm unable to see the discord or intercom, but given what I have here I am unable to reproduce this at the moment. Below is a screengrab of me switching from Metamask to OKX. I did have to retrigger the OTX connection, but it seemed to work fine other than that.

Are there any more details that might help me reproduce this?

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fea84566581ed8c522d2e6570694537dad0bf076/Untitled.mov)
