### ISSUE TITLE
[ICE: 18] Txn stuck at Low relayer fee error but can't bump it

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6155]
**Describe the bug**
User sent ezETH from Mode to Ethereum Mainnet but his txn is stuck because of a low relayer fee error msg:

https://connextscan.io/tx/0x66714e545ac2e365496a2348963b248a59487092da93f5786d258e5b867bb933

User can't bump it (and i can't bump it too) because of the "Waiting for a bump" msg.

<img width="1920" alt="image" src="https://github.com/connext/monorepo/assets/26097731/a1177ebc-f9f2-43e2-9c6a-ffbed3bd6ff6">

Also additional relayer fee requested is 0

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1237846461652406312

@oncall

**Comment by MinistroDolar** [comment]
> Should not be taking fees in ezETH.

I thought about that but I wasn't 100% sure if that was the issue.

**Comment by just-a-node** [comment]
Moving this to UI team to fix, two issues:

1) Bridge page - `relayerFeeAssetType` should be `native` for ezETH. I do see in the current bridge page that relayer fee is denominated in ezETH rather than ETH:

<img width="425" alt="image" src="https://github.com/connext/monorepo/assets/16638982/4a735913-9b08-4599-9418-b8ee30dc73d0">

The resulting `xcall` however has the correct data where the fee taken is in native ETH.

2) Connextscan - User should be able to bump the fee. Not sure why we're in "waiting" state. For xERC20 assets we should always be asking for relayer fee bump in the native asset. For stables, we accept in transacting.

**Comment by just-a-node** [comment]
Will resolve this user's issue manually by bumping in native.

**Comment by MinistroDolar** [comment]
> Moving this to UI team to fix, two issues:
> 
> 1. Bridge page - `relayerFeeAssetType` should be `native` for ezETH. I do see in the current bridge page that relayer fee is denominated in ezETH rather than ETH:
> 
> <img alt="image" width="425" src="https://private-user-images.githubusercontent.com/16638982/329045393-4a735913-9b08-4599-9418-b8ee30dc73d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDE5NzksIm5iZiI6MTcxNTIwMTY3OSwicGF0aCI6Ii8xNjYzODk4Mi8zMjkwNDUzOTMtNGE3MzU5MTMtOWIwOC00NTk5LTk0MTgtYjhlZTMwZGM3M2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDIwNTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YjZjYjMzYjMxYTNhOTI0ZmYxYzI5Yjc3NWI0M2ZjYTBlYmE0N2Y5NzNlZTMxOTQyZWJiMmEyMDIxMzMyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1lGt_9xuMTdbkA3qMMOHn0PkMaEAdWtJGmQ2yriczr0">
> The resulting `xcall` however has the correct data where the fee taken is in native ETH.
> 
> 2. Connextscan - User should be able to bump the fee. Not sure why we're in "waiting" state. For xERC20 assets we should always be asking for relayer fee bump in the native asset. For stables, we accept in transacting.

Gas on destination is denominated in ETH in the picture you sent and also is the case if you try with Mode to Mainnet
<img width="406" alt="image" src="https://github.com/connext/monorepo/assets/26097731/52041896-b794-415a-ab4f-1a9f08dcd136">

I don't understand how he paid the relayer fee in ezETH
<img width="775" alt="image" src="https://github.com/connext/monorepo/assets/26097731/05e64b26-76ca-443c-8199-7e32c62c7170">

**Comment by just-a-node** [comment]
Oh my bad, I was reading router fee. Okay, then it is not clear how the user was able to send with ezETH as relayer fee.

**Comment by alexwhte** [comment]
where did they initiate this? @ekbainova 
it shouldnt be possible to send with ezETH relayer fee

**Comment by MinistroDolar** [comment]
> where did they initiate this? @ekbainova 
> it shouldnt be possible to send with ezETH relayer fee

OKX Bridge (in wallet). They also delivered the xERC20 asset for ezETH instead of native one (Ethereum Mainnet). Bad implementation, we should tell them about this.

**Comment by just-a-node** [comment]
Resolved for this user with manual guidance. Passed the implementation issues to OKX team.
