### ISSUE TITLE
[ICE: 5] Arbitrum ETH Pool incorrect metrics

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6159]
**Describe the bug**
The Arbitrum WETH pool seems to be showing incorrect metrics. The graph doesn't load (for any combo of Volume/TVL and timeframe) and a user reported that the WETH balance percentage has been stuck on 47% for some time. Looking at Connextscan and the Arbitrum contract on Arbiscan, there seems to be quite a difference in the numbers of how much WETH and nextWETH is in the pool.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/378c7db3-9b48-4e5e-8090-b2847e252df6)
![image](https://github.com/connext/monorepo/assets/84744304/cae0f308-fd8e-4a45-a7ad-81945021c877)
![image](https://github.com/connext/monorepo/assets/84744304/f07fbba9-d829-4ec5-8808-13d6311c3fa7)

**Comment by alexwhte** [comment]
dupe #6078
