### ISSUE TITLE
[ST] Polygon to Base not completing

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6160]
**Describe the bug**
There are some transactions from Polygon to Base that are taking too long to complete. We received complaints from users that they weren't getting their funds. The slow path seems to work for some other transactions with Base destination.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/35a050d3-9070-4c54-bb60-045345de51a5)
![image](https://github.com/connext/monorepo/assets/84744304/de86b34a-fa7e-4311-a663-3bdebdc2ff34)
![image](https://github.com/connext/monorepo/assets/84744304/847dae9a-2257-4240-95ba-201b10fa4992)

**Comment by ekbainova** [comment]
#6174
