### ISSUE TITLE
[ST] Transactions from Polygon aren't completing

### ISSUE THREAD

**Issue by tann9949** [connext/monorepo#6161]
**Describe the bug**
Recent transactions coming from Polygon aren't completed. It's been 10 hours since last the `CompletedFast`and `CompletedSlow` transaction.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/34812325/9c90a1ef-7083-4956-816f-052bbe8f63fe)
![image](https://github.com/connext/monorepo/assets/34812325/feaf7d32-2de3-4e84-9302-c798e31d3455)
@oncall

**Comment by prathmeshkhandelwal1** [comment]
Just checked last completed was an hour ago

**Comment by prathmeshkhandelwal1** [comment]
Seems healthy rn
