### ISSUE TITLE
[ST] Mode routers are not bidding 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6162]
**Describe the bug**
OP->Mode ETH tx stuck (low value). Routers are not bidding 

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/754?view=List

**Additional context**
https://connextscan.io/tx/0x2e9876d6463c4ed9a1fe93a6b7e2a334792ea8b71aa219d01be528faabb21365

@oncall

**Comment by ekbainova** [comment]
#6174
