### ISSUE TITLE
Graph query in router fails

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#6167]
**Describe the bug**
Graph query in router fails

Sample log:
https://app.datadoghq.com/logs?query=host%3Aip-172-17-2-242.us-east-2.compute.internal%20service%3Arouter-publisher%20container_id%3Add500a2f20bc42c68fbc00ab7959e3ad-1167413380%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AY9y2BpQAADj34oh_etjAgAC&event=AgAAAY9y2BgDfqOmqwAAAAAAAAAYAAAAAEFZOXkyQnBRQUFEajM0b2hfZXRqQWdBQwAAACQAAAAAMDE4ZjcyZDgtNmVjMS00OTkwLWFmNmUtOTVhZjYwN2RkYTQw&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAY9y2B61C7PUQAAAAAAAAAAYAAAAAEFZOXkyQ0lyQUFDN2k3Qy1SeDJ1ZUFBSgAAACQAAAAAMDE4ZjcyZDgtNmVjMS00OTkwLWFmNmUtOTVhZjYwN2RkYTQw&viz=&from_ts=1715618415651&to_ts=1715618717366&live=false

**Link to ticket in discord**

**To Reproduce**
1. Go to [DD](https://app.datadoghq.com/logs?query=host%3Aip-172-17-2-242.us-east-2.compute.internal%20service%3Arouter-publisher%20container_id%3Add500a2f20bc42c68fbc00ab7959e3ad-1167413380%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AY9y2BpQAADj34oh_etjAgAC&event=AgAAAY9y2BgDfqOmqwAAAAAAAAAYAAAAAEFZOXkyQnBRQUFEajM0b2hfZXRqQWdBQwAAACQAAAAAMDE4ZjcyZDgtNmVjMS00OTkwLWFmNmUtOTVhZjYwN2RkYTQw&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAY9y2B61C7PUQAAAAAAAAAAYAAAAAEFZOXkyQ0lyQUFDN2k3Qy1SeDJ1ZUFBSgAAACQAAAAAMDE4ZjcyZDgtNmVjMS00OTkwLWFmNmUtOTVhZjYwN2RkYTQw&viz=&from_ts=1715618415651&to_ts=1715618717366&live=false)

**Additional context**
```

**Comment by just-a-node** [comment]
Resolved with CI re-run. Previous Bware-only mode change didn't apply to AWS.
