### ISSUE TITLE
[ICE: 24] Change Ownership for router blocker

### ISSUE THREAD

**Issue by A-Keyboard** [connext/monorepo#6169]
From p2pvalidator chat:
" we have another blocker issue: we just tried to change ownership via proposeRouterOwner/acceptProposedRouterOwner methods via louper.dev, but it fails on the last step - on the acceptProposedRouterOwner. The estimated gas fee is some huge value of millions dollars. The same time, I can get the correct address of new owner via getProposedRouterOwner, we are sure we are connected with the correct wallet of new owner and we tried this for 3 networks: on Arbitrum, BSC and Gnosis. I think the big estimated gas fee is some smart contract guard from accepting the new router owner from not correct address, but the thing is that we have the correct one wallet which is trying acceptProposedRouterOwner method. So definitely need your help here, there might be smart contract issue, I think we are the first ones who tries to change the router owner"

https://connextscan.io/router/0xC4Ae07F276768A3b74AE8c47bc108a2aF0e40eBa

@oncall

**Comment by just-a-node** [comment]
They need to wait 7 days

**Comment by just-a-node** [comment]
Nothing to do here, router can accept ownership after 7d elapses.
