### ISSUE TITLE
Arbitrum => Base transactions stuck for 3 hours

### ISSUE THREAD

**Issue by ValerywArz** [connext/monorepo#6170]
Transactions from arbitrum to base are stuck with NoBidsReceived issue
![image](https://github.com/connext/monorepo/assets/93597601/61020bef-6e50-4969-9aa9-ca1426d2961c)

**Comment by ValerywArz** [comment]
![image](https://github.com/connext/monorepo/assets/93597601/95950efa-b490-447b-8c2c-17c987849a8b)
![image](https://github.com/connext/monorepo/assets/93597601/95950efa-b490-447b-8c2c-17c987849a8b)


Base to Mode router is also stuck

**Comment by ValerywArz** [comment]
Linea to Mode (only one transfer passed in a last 3 hours
![image](https://github.com/connext/monorepo/assets/93597601/d86772d7-8dfb-41d6-9846-02cd37b69bde)

**Comment by ValerywArz** [comment]
Arbitrum - Base stuck again
Transactions to Mode are stuck too

**Comment by ekbainova** [comment]
#6174
