### ISSUE TITLE
[ICE: 27] Balances not showing on Mode - RPC Issues

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6171]
**Describe the bug**
We have had a few reports of users not being able to see their balance when starting a bridge from Mode.

After checking with them and trying to reproduce the issue, I have found a CORS block on my console (and also on the users'). We have tried changing our RPC (in the attached image I am using https://mode.drpc.org/ but it is https://1rpc.io/mode in the console error).

The error is intermittent, sometimes I get the balance and sometimes it disappears. As example, right now i just did a CONTROL+F5 refresh and ezETH its there, but after a while, it disappears

![image](https://github.com/connext/monorepo/assets/26097731/b02ffacc-5f53-4c38-b0d8-615c3a5be882)

![image](https://github.com/connext/monorepo/assets/26097731/9fc175fd-8435-49e6-b9df-91f3e47ad46f)

**Ticket:**

https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/769?view=List

@oncall

**Comment by just-a-node** [comment]
It's a rate limit on the public RPC. Unfortunately we don't have better options atm.

**Comment by Tommy-R8** [comment]
Is there no possible fix for this? (other than users waiting)
Some reported trying throughout several hours and still getting the error

**Comment by Tommy-R8** [comment]
Are RPCs on the frontend automatically rotated between a set of public ones? If not, we should probably rotate based on user reports

**Comment by alexwhte** [comment]
can try Blast https://blastapi.io/chains/mode

**Comment by ekbainova** [comment]
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/777?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/775?query=RPC%20Mode&sort=newest
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/705?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/779?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/conversation/804?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/809?query=RPC%20Mode&sort=newest
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/772?query=RPC%20Mode&sort=newest
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/769?query=RPC%20Mode&sort=newest
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/768?query=RPC%20Mode&sort=newest
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/786?query=RPC%20Mode&sort=newest
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/763?query=RPC%20Mode&sort=newest

**Comment by just-a-node** [comment]
Looking at replacement options

**Comment by ekbainova** [comment]
@just-a-node Returned to QA and code review

**Comment by prathmeshkhandelwal1** [comment]
https://github.com/connext/frontend/pull/70

Created a PR for this

**Comment by just-a-node** [comment]
Added private blast rpcs.
