### ISSUE TITLE
[ICE: 25] Router Remove tab is buggy

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6172]
**Describe the bug**

Routers facing issues withdrawing. Specifically they are seeing this issue with Metis but could be widespread.

Issues:
1. We don't see our balances (or sometimes 0.0000something for just one token)
2. Switch network button doesn't work
3. Remove liquidity tab sometimes active, sometimes not for the same wallet connected (usually it works after refresh page, then it might be blocked)

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**
N/A. Raised in private tg 

**To Reproduce**
1. Go to Router management 
2. Check issues 1-3

**Screenshots**

SLA: 2 working days

**Comment by just-a-node** [comment]
Any updates since the log addition?

**Comment by regexpressyourself** [comment]
@just-a-node I still haven't been able to trigger anything on main or test net. Have we been able to capture any logs from users experiencing this issue?

**Comment by just-a-node** [comment]
@ekbainova Do we see this issue for anyone else besides the one router who messaged us?

**Comment by ekbainova** [comment]
@just-a-node no

**Comment by just-a-node** [comment]
From P2P:

BTW, we have good news about this issue - we found a workaround. The issue is that the owner MUST have Metamask switched to the network we want withdraw funds from BEFORE opening router page. Switch network button communicates with Metamask if network is different, but even after switching Remove button is not active. Full page refresh is required. Can you please try to reproduce the issue? 

The second small issue: dropdown list of tokens doesn't show actual balance, the correct balance is shown only when we choose any token.

Otherwise it works fine, we managed to change the owner, so only these minor issues are in place so far

**Comment by just-a-node** [comment]
@jwtong Could you take a look at this issue?
