### ISSUE TITLE
[ICE: 50] Gnosis destination stuck in ExecutionError

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6174]
**Describe the bug**
Several reconciled transactions going to Gnosis are stuck in ExecutionError

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/9ec81711-5b7d-4b61-a7ff-a4f967d7c8e8)

SLA: 1 working day

**Comment by ekbainova** [comment]
Other:

https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/784?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/783?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/782?view=List
https://connextscan.io/tx/0xb0f85d859b3db642c2bd9f6d7d8239ceff979d8473a1ba5217a3d0175b537c84

**Comment by just-a-node** [comment]
Cleared now from the processing lag yesterday.

**Comment by ekbainova** [comment]
33 tickets:
https://app.intercom.com/a/inbox/qge2vd8z/inbox/tickets/807/linked-conversations?show_bulk_edit_modal=false&view=List
