### ISSUE TITLE
RPC Mode balance issue

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6188]
**Describe the bug**
The balance on Mode is not displayed.

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/809
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/501
https://app.intercom.com/a/inbox/qge2vd8z/inbox/search/conversation/769

**Comment by alexwhte** [comment]
closing as dupe of 6171
