### ISSUE TITLE
[ICE: 14] Router bidding only on BNB

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6189]
**Describe the bug**
For Dokia and Dialectic router bidding only on BNB. 
Details in TG chat with Dialectic

**To Reproduce**
Dificulties with reproduce the bug

**Screenshots**
<img width="663" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a12e154e990490e03b04e243130a8d92d1e16e79/telegram-cloud-photo-size-4-5922484997963498087-y.jpg" alt="telegram-cloud-photo-size-4-5922484997963498087-y.jpg" />

**Additional context**
@just-a-node 

SLA: 1 working day

**Comment by just-a-node** [comment]
Dialectic router has bid on a couple non-BNB ones recently:
- gno: https://connextscan.io/tx/0x37ef00de639274d261874c5b34d0f8522c7df306f573f8c01367bf0781f3cc5b
- eth: https://connextscan.io/tx/0x2c76b7b9f52d2df8386101907da565c91e9393bb9284c043417a0280b26098bb

**Comment by ekbainova** [comment]
@just-a-node What does it mean? No issues?

**Comment by just-a-node** [comment]
Yes, for now. I will leave in QA if we discover they stop bidding in the next day or two.

**Comment by just-a-node** [comment]
Still seeing bids for other chains, will close now.

**Comment by ekbainova** [comment]
Need a retro on it. The slow path in Linea was a consequence of it, wasn't it?

**Comment by alexwhte** [comment]
Reopening as still an issue here https://discord.com/channels/992549151134982234/1242844696489754715/1242857231561658368

**Comment by ekbainova** [comment]
23/05
<img width="1175" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM29HQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5aa93f2365bc3931e37d42c86913760910d41e39/Screenshot%202024-05-23%20at%2013.56.25.png" alt="Screenshot 2024-05-23 at 13.56.25.png" />

**Comment by ekbainova** [comment]
Ready to close? @just-a-node

**Comment by alexwhte** [comment]
@ekbainova i think it's fine to close as we have an engineering solution

for next steps can you check in here and coordinate with khalil? https://lookerstudio.google.com/u/0/reporting/ab897c02-675c-4f00-93bd-0ac05e3bf595
