### ISSUE TITLE
[ICE: 13] Connextscan completed ExecutionError filtered transactions are shown as Processing

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#6192]
**Describe the bug**

Filtering for "ExecutionError" transactions shows transfers "Processing" but when clicking into these transfers, they are already completed (both Reconciled and Executed).

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**

**To Reproduce**
1. Go to Connextscan
2. Filter by "ExecutionError"
3. Click into a "Processing" Transaction
4. It's complete. It should've shown "SUCCESS" in the list view

**Screenshots**

**Additional context**
@oncall

SLA: 2 working days

**Comment by ekbainova** [comment]
It should be fixed with the merge of new Refactoring version.
