### ISSUE TITLE
[ICE: 21] Linea routers are not bidding for ezETH

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6194]
**Describe the bug**
Linea routers are not bidding for ezETH

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/851?view=List

**Additional context**
https://connextscan.io/tx/0x4db3ae81b1da162f47862db7a5fc0e74dea752eff55b5317eae4d87a97811605
@oncall

SLA: 2 working days

**Comment by ekbainova** [comment]
#6189 connected?
