### ISSUE TITLE
[ST] Linea slow path taking too long

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6198]
**Describe the bug**
A user reported their transaction to Linea started taking more than 5hs and it still didn't complete. Indeed, there are some that have been processing for 6+ hours.

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/980154ad-49c6-44ce-9a7b-a4a17f0980a7)

**Comment by just-a-node** [comment]
These have all completed
