### ISSUE TITLE
[ICE: 21]  Routing from Optimism/Arbitrum and more chains to Mode is not working properly (in the last 8 DAYS)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6203]
**Describe the bug**
If you take a look those 3 routers with huge liquidity on Mode are not bidding txns in the last 8 days when the path is Optimism /Arbitrum and more to Mode.

https://connextscan.io/router/0x6fd84ba95525c4ccd218f2f16f646a08b4b0a598 (this one is only bidding txns from Ethereum Mainnet/BNB Chain/Gnosis when Mode is the destination chain, **it also didn't bid txns from polygon in the last 8 days)**
<img width="1906" alt="image" src="https://github.com/connext/monorepo/assets/26097731/10de6f03-7474-4320-ac80-738c289274a9">

https://connextscan.io/router/0x8cb19ce8eedf740389d428879a876a3b030b9170 (this one is only bidding txns from Ethereum Mainnet/BNB Chain/Gnosis when Mode is the destination chain)
<img width="1910" alt="image" src="https://github.com/connext/monorepo/assets/26097731/68682b85-3b82-4116-9cca-5eee582dca48">

https://connextscan.io/router/0xc770ec66052fe77ff2ef9edf9558236e2d1c41ef (**this one IS DOWN - NO BIDS IN THE LAST 15 HOURS** - but it was only bidding txns from Base/Linea/Metis when Mode is the destination chain, bid a few from BNB Chain like 2 days ago)
<img width="1913" alt="image" src="https://github.com/connext/monorepo/assets/26097731/c409b345-bbc8-4f75-9946-8fd0b502a57d">

This means that most of the txns go through the slow path (unless the user sends less than 0.001109 ETH (because our router is working lol https://connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c).

<img width="1904" alt="image" src="https://github.com/connext/monorepo/assets/26097731/b637083b-0dbc-4194-b1f3-cbbe577cc413">
<img width="1907" alt="image" src="https://github.com/connext/monorepo/assets/26097731/7dd78b22-4ae6-4db1-847f-0f93f90a7581">
<img width="1908" alt="image" src="https://github.com/connext/monorepo/assets/26097731/0f282f89-47c3-4f98-939d-08665e9886b7">

**Additional context**
% of txns going to the slow path
![image](https://github.com/connext/monorepo/assets/26097731/39f3ca8e-98fe-4ab7-b336-c8f45ff33090)
![image](https://github.com/connext/monorepo/assets/26097731/162ae43b-9474-4fde-bd3e-b811bf391b2b)
![image](https://github.com/connext/monorepo/assets/26097731/8104b624-8b60-4e5f-aca0-af257d02a9da)

@oncall

**Comment by ekbainova** [comment]
#6189 connected?

**Comment by oswy-cpu** [comment]
Looks like there's one more: 

intercom: https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/1005?view=List
scan: https://connextscan.io/tx/0x67c5b73adf39719231b12d2c9fa17b9f86c583b53bf87ae650e36452e16e0507
