### ISSUE TITLE
[ICE: 8] Metis slow path delays

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6211]
**Describe the bug**
Some Metis slow path transfers have been processing for 9 hours.
Example: https://connextscan.io/tx/0xf236ed65ea2ddd1d1bb04bf4d32daaf7e906359ca9ef81842dbd0cb1cab6bdad

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/ec68a3b4-0994-4b67-a967-fb2c42279a64)

SLA: 1 working day

**Comment by oswy-cpu** [comment]
one more:

https://connextscan.io/tx/0x3158d74eb3b2411e1135cc2f9c9dddf27c763d6a96dbfab50462960412cbb7e4

https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/1021?view=List

**Comment by oswy-cpu** [comment]
one more:

https://connextscan.io/tx/0xba8eff614c064cfe8ce1cadc952782c8b337bf119a0261b4ff2e2a33cb57c287

https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/1022?view=List

**Comment by ekbainova** [comment]
Once again happened @LayneHaber 
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVk5QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e800cf8cc54c0c6ffad411ca31a28b1462b0d7ad/Screenshot%202024-06-05%20at%2022.58.27.png" alt="Screenshot 2024-06-05 at 22.58.27.png" />

**Comment by just-a-node** [comment]
Slow txns are completing (latest was 11.5 hrs). Leaving this up for monitoring another few hrs.
