### ISSUE TITLE
[ST] Add estimation override logic to API 

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6216]
Update:
This is for an enhancement to add the same logic from https://github.com/connext/monorepo/issues/5966
This assumes it will be easy for partners to adopt as part of their current integration setup

**Describe the bug**
When simulating a bridge (as example, ETH from Optimism to Base) on our UI you can see the right ETA (3 hours):

![image](https://github.com/connext/monorepo/assets/26097731/dd157a83-d6ca-4822-9779-8f743faada7a)

But, when doing the same simulation on Li.Fi, it shows 3 minutes:

![image](https://github.com/connext/monorepo/assets/26097731/3570ed05-8470-4ec1-9e14-704d972e479f)

It should be fixed to avoid users getting angry about wrong estimations, like this one:

https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1038?view=List

https://connextscan.io/tx/0x5428c6092cf5feb41ea4ffa7864c287059efa7af6570195a7022ba308d716e32?source=search

**Where did the user initiate this transfer?**
Jumper

@oncall

**Comment by alexwhte** [comment]
This is because we have new logic in UI that overrides slow estimates based on recent transfers (to help with routers going down)
We are looking at the same in API
