### ISSUE TITLE
[ICE: 48] Mode-Blast route is displayed

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6223]
**Describe the bug**
Mode-Blast is looks like supported route with some warning.
It should be displayed here: "Route is not supported" 

**Where did the user initiate this transfer?**
https://bridge.connext.network/EZETH-from-mode-to-blast?amount=12

Ticket: https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1066?view=List

**Screenshots**
<img width="491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6291bce270cf2c79cfb632aa0c3428aea8e121b/Screenshot%202024-05-24%20at%2016.19.09.png" alt="Screenshot 2024-05-24 at 16.19.09.png" />

**Comment by ekbainova** [comment]
Ensure that the fields can be filled only for Ethereum - Blast ezETH, and nowhere else.

**Comment by regexpressyourself** [comment]
> Ensure that the fields can be filled only for Ethereum - Blast ezETH, and nowhere else.

@ekbainova It appears that this is usually true, but you can still break the UI by:

1. Choose Ethereum as source
2. Choose Blast as destination
3. Change source to something else
4. Bug appears: User has Blast destination and non-Ethereum as source

I've pushed up a change here: https://github.com/connext/monorepo/issues/6223

My update will automatically change the source to Ethereum when Blast is chosen as the destination. If we want a different approach let me know! I've attached a screengrab of the change in action:


https://github.com/connext/monorepo/assets/5316399/27d5cb98-0d50-4df3-9d16-afb3412773f8
