### ISSUE TITLE
[ICE: 18] Swap has a UI bug 

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6224]
**Describe the bug**
It is imposibble to swap on Linea for some users.
Can't repro it.
"not able to swap, nextweth->weth"
"no token to select"

**Why it is important?**
This is a period of Linea LXP-L points 

**Link to ticket in Intercom**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1073?view=List
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1067?view=List

**Screenshots**
<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a15d99ea0a333c21a22e4ab1abae35eadfca0b7/image.png" alt="image.png" />

**Comment by Tommy-R8** [comment]
This doesn't happen only for Linea. Check #6627

**Comment by ekbainova** [comment]
@just-a-node @regexpressyourself the high priority now.

**Comment by regexpressyourself** [comment]
@ekbainova I'm not seeing this live right now. I also see it working for the support person in the linked conversation: <img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfe372516b0e4c899b7548855dde94c0acdb8835/image.png" alt="image.png" />


At this time I'm not sure how to reproduce this issue.

**Comment by ekbainova** [comment]
https://app.intercom.com/a/inbox/qge2vd8z/inbox/tickets/1076/linked-conversations?show_bulk_edit_modal=false&view=List

**Comment by ekbainova** [comment]
It is happening still, we have a ticket 30 min ago - https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1099?view=List

**Comment by ekbainova** [comment]
Okay, I am trying to collect all tickets on different problems in the #Reliability channel.

**Comment by just-a-node** [comment]
I am able to see the issue here:
https://www.loom.com/share/79d4577ed53449f685850960ab52d89d?sid=e9831952-abf6-4937-aa3d-d7fe2f0120bb

**Comment by ekbainova** [comment]
Any progress? @just-a-node

**Comment by jwtong** [comment]
Please let me know if this still needs a fix, possible other things could have fixed this
