### ISSUE TITLE
[ICE: 18] UI bug WETH/ETH token

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6225]
**Describe the bug**
Base origin - is impossible to choose ETH as a Token, it is automatically switched to WETH
The bug was identified on QA7
https://www.notion.so/connext/Wallet-balance-86ceef885ea14385a320ab310d095090?pvs=4

**Link to ticket in Intercom**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7092575/conversation/1074?view=List

**To Reproduce**
1. Go to 'https://bridge.connext.network/ETH-from-base-to-linea?symbol=ETH'
2. Click on 'ETH'
3. See error

<img width="623" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8555350162f0217148d35accc464e4269737ab20/Screenshot%202024-05-24%20at%2020.25.03.png" alt="Screenshot 2024-05-24 at 20.25.03.png" />

**Comment by just-a-node** [comment]
Not chain-specific. Selecting ETH is bugged.
https://www.loom.com/share/4354adb4e68044f4806757123a966827?sid=4d67b8ee-2922-4930-8c46-34b60edff0c3

**Comment by jwtong** [comment]
Issue is in the asset config, ETH is selected, but WETH is the "symbol" that's selected from the assets config

**Comment by just-a-node** [comment]
We may need to make an exception for ETH. When user selects ETH, the SDK constructs a multicall that includes swapping ETH->WETH and `xcall` with WETH. The `sdk.xcall()` function still expects the WETH address as input (but with `wrapNativeOnOrigin: true`). That's why we have WETH defined under ETH.
