### ISSUE TITLE
[ST] Swap UI bug - nextAsset to Asset

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6227]
**Describe the bug**
When attempting to swap nextUSDT > USDT on BNB, the swap button disappears, and the wallet doesn't open to initiate a transaction.

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/454734546869551116/1243703507568033832

**Screenshots**
![image](https://github.com/connext/monorepo/assets/84744304/1984a5b4-af9f-4656-b93c-2e09f4a0981b)

**Additional context**
User says they're able to reproduce this and it apparently happens only for nextUSDT to USDT and nextUSDC to USDC on BNB.

**Comment by tann9949** [comment]
Saw this issue on ticket 518 as well. User can't swap `nextWETH` on the swap UI

I was able to reproduce the error as shown here
<img width="491" alt="Screenshot 2567-05-25 at 09 47 31" src="https://github.com/connext/monorepo/assets/34812325/0c8d5663-b625-4658-bf1e-4239ba4ae1e4">

Here's the procedure (assumed that I already have nextWETH in my account):
1. Proceed to https://bridge.connext.network/swap/ETH-on-linea?from=nextWETH
2. Specify the amount to bridge, the swap button will appear
<img width="481" alt="image" src="https://github.com/connext/monorepo/assets/34812325/57115ea0-8f97-488f-861a-2e0848444868">
3. Upon clicking swap, the swap button loaded for a second then the button disappear without triggering wallet call
<img width="485" alt="Screenshot 2567-05-25 at 09 53 15" src="https://github.com/connext/monorepo/assets/34812325/5e915827-31b1-4f0c-87c0-f9581cbf07ec">

**Comment by Tommy-R8** [comment]
Another user had it for nextWETH to WETH on Optimism
https://discord.com/channels/454734546869551114/454734546869551116/1243760253795958804
with this error
![image](https://github.com/connext/monorepo/assets/84744304/438de3ca-f583-43df-b8b7-05b78762f16f)

**Comment by Tommy-R8** [comment]
Duplicate of https://github.com/connext/monorepo/issues/6224
