### ISSUE TITLE
[ST] BNB to Arbitrum estimated time is slow, others to Arbitrum are fast

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#6233]
**Describe the bug**
Estimated time should be based on destination chain only
Currently it shows slow path sending ETH from BNB to Arbitrum (3hrs) . This is mislabeled as fast path in the tooltip
<img width="707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e6201e92eeb1e08ef05e8d3517d1c9fd94e15a4/image.png" alt="image.png" />

Fast path from Ethereum to Arbitrum (3 mins)
<img width="579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMThUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b191f98e8b6636c17e9bbde1331cb8a6fd7379a2/image.png" alt="image.png" />

**Next steps**
1. Check the logic we have implemented. It should be consistent at least
2. Check why BNB to Ethereum is showing 3hrs
3. Remove the tooltip that shows fast transfer when it is slow

**Comment by alexwhte** [comment]
per @maxlomu from Arbitrum team

**Comment by jwtong** [comment]
Estimated time is based on last 20 transfers between source chain and destination chain.

**Comment by jwtong** [comment]
https://github.com/connext/frontend/pull/76

**Comment by ekbainova** [comment]
Previously, Estimated time is based on last 20 transfers between source_chain and destination_chain. We modified it to just transfers with the destination_chain

**Comment by ekbainova** [comment]
It is deployed. We can close. @just-a-node
