### ISSUE TITLE
[ICE: 10] ChainID check have not happened before the tx init.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6237]
**Describe the bug**
The user tried to initiate transaction from Linea without changing chain in his wallet manually. The website have not passed chainID checks and allowed user to send transaction with the current chain (Blast). This resulted in the user sending funds to the Linea contract address on the blast network (i.e. loss of funds) 

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/1110?view=List

**Screenshots**
![image](https://github.com/connext/monorepo/assets/74738120/90c04165-9dbb-407e-9df6-4c55a312c60d)

**Additional context**
User Address: 0x9ca8fbe5594209aef565502ce2162a2f7ff68fc8
Linea contract: https://lineascan.build/address/0xce157927222cd68b9c7057e84344ce6f0cee89b2
Funds fell to: https://blastscan.io/address/0xce157927222cd68b9c7057e84344ce6f0cee89b2

@oncall

**Comment by oswy-cpu** [comment]
upd, happens only with Rabby Wallet 
![image](https://github.com/connext/monorepo/assets/74738120/99b8ebd1-f26a-43b2-8c69-eda0b06e7cd6)

**Comment by ekbainova** [comment]
All tickets are here: https://app.intercom.com/a/inbox/qge2vd8z/inbox/tickets/1118/linked-conversations?show_bulk_edit_modal=false&view=List

**Comment by just-a-node** [comment]
We need to check wallet state sync - the "Send" button should instead be a "Switch chain" prompt.

**Comment by Tommy-R8** [comment]
This doesn't happen only for Rabby. Here's a case where it happens on mobile OKX Wallet:
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1115?view=List
![image](https://github.com/connext/monorepo/assets/84744304/1eb47d3f-e8ea-4bba-9937-77b71eb8cb9f)
![image](https://github.com/connext/monorepo/assets/84744304/300e65ec-9098-45e2-bb2d-b4bef05c1ec8)
![image](https://github.com/connext/monorepo/assets/84744304/f89155f0-f6c9-4345-a8a3-00b9575e33f3)

The user is completely unable to get a transaction started from Ethereum

**Comment by just-a-node** [comment]
Fix merged to main already.
