### ISSUE TITLE
[ICE: 50] Routers are not bidding on transfers from Mode/Arb

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6239]
**Describe the bug**
Base routers are not bidding for TX going from Mode

**Where did the user initiate this transfer?**
Jumper

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/1117?view=List

**Additional context**
https://connextscan.io/tx/0x7ef587ca6cfbd77c21c51a640d5418cc6bad6f7b6986f61552b36ccf09dcea6b

@oncall

**Comment by alexwhte** [comment]
The issue looks to be transfers from Mode origin 
<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b770acaa2ab38383ec96ec7d1ec1ef4bd3020283/image.png" alt="image.png" />

**Comment by ekbainova** [comment]
@just-a-node 800 transfers from Mode had slow path  <img width="1310" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmc4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--268eb714dbbda686146c54757d88a54d4f7fbef6/Screenshot%202024-06-05%20at%2021.47.04.png" alt="Screenshot 2024-06-05 at 21.47.04.png" />

**Comment by ekbainova** [comment]
Any updates? @just-a-node

**Comment by just-a-node** [comment]
Mostly due to Dialectic being down.
