### ISSUE TITLE
[ST]The transaction was expected to take 3-5 hours, but was actually delayed by 14 hours

### ISSUE THREAD

**Issue by QQHHUH** [connext/monorepo#6245]
Users trying to bridge URUS tokens from ETH to BNB have been delayed for 14 hours

Link: https://connextscan.io/tx/0x64c89ad1ae0ae8a15dfef6ce56ceb1bc471b046f37e4862e78d048f15f4c8c9b
From ETH-BNB
Token:URUS
![Screenshot_20240601_204152_Chrome](https://github.com/connext/monorepo/assets/92560156/7940b6db-f61c-4b5d-87b3-b680ef3a3a27)

@oncall

**Comment by ekbainova** [comment]
#6247
