### ISSUE TITLE
[ST] Large ezETH transfer from Ethereum mainnet stuck in slow path

### ISSUE THREAD

**Issue by tann9949** [connext/monorepo#6247]
**Describe the bug**
There're two transactions reported in the ticket that the transaction stuck longer than expected for slow path
- (16.22 ezETH) https://connextscan.io/tx/0xce08c923ecb56287968d560d4dffaa867d4d5d9aa716a5d9b98534759f78c851
- (205.81 ezETH) https://connextscan.io/tx/0x37abd0cc93f0d8a47082c6b5b3552b8b41560e5aa8d0f47953bb12b11bf1ec98

One tx took more than a day to complete

**Where did the user initiate this transfer?**
Connext UI

@oncall

**Comment by Tommy-R8** [comment]
Other transactions here:
https://connextscan.io/tx/0x5cc5a17d085b919d4659695370b5c4909981e60a7e3de00a8fcba91c83b954f4
https://connextscan.io/tx/0x113800963a7f162733a6f314193dfc0c8ede156432ae70757bba8ffa09d6d93b
https://connextscan.io/tx/0xd8ad5849556aeb198c6552451b6caf8ba2458b03f020c9e9895006b351dd0637
https://connextscan.io/tx/0x5841c3726f4c76535fe2ca04c0dd66c92d36108355d56e1f5ba7a468bada6918
https://connextscan.io/tx/0x8cbb9d0ec31385b449022a3939accef7cc08df262339be82d8bbae810da22a01
https://connextscan.io/tx/0xd336c209647672562fe8def636422c25f7ef732ca2a7afc043dd15510c454308

**Comment by Tommy-R8** [comment]
https://connextscan.io/tx/0xf7f807dc1f5a57073b3ac25f7338ca988f16493d2cfd7cf084df673a7345f0cc
