### ISSUE TITLE
[ST] bware-labs routers bidding from Ethereum delayed by 50 minutes

### ISSUE THREAD

**Issue by tann9949** [connext/monorepo#6249]
**Describe the bug**
Bware Labs router bidding transaction from Ethereum 50 minutes slower than expected. This is probably an Ethereum subgraph issue and is related to #6244 

**Where did the user initiate this transfer?**
Connext UI

**Screenshots**
Recent [transactions from `bware-labs.eth` router](https://connextscan.io/router/0x8cb19ce8eedf740389d428879a876a3b030b9170) delayed by around 50 minutes as shown here:
![Screenshot 2567-06-02 at 15 04 00](https://github.com/connext/monorepo/assets/34812325/d4eeff53-bda0-4c3c-af9e-8d6e5bf2aed2)

@oncall

**Comment by tann9949** [comment]
Found this issue with `ai-router.eth` as well
https://connextscan.io/router/0x6fd84ba95525c4ccd218f2f16f646a08b4b0a598
![image](https://github.com/connext/monorepo/assets/34812325/b58a035e-88f0-42ba-a0b7-d0eb7911a279)

**Comment by ekbainova** [comment]
#6247
