### ISSUE TITLE
[ICE: 12] Send button disappeared when bridging

### ISSUE THREAD

**Issue by tann9949** [connext/monorepo#6250]
**Describe the bug**
When bridging, after clicking "SEND", the UI showed "checking approval" and the button disappeared. Upon monitoring the console, we found this error message:
![image](https://github.com/connext/monorepo/assets/34812325/28991804-b98e-4672-9363-37364f3f2798)

**Where did the user initiate this transfer?**
Connext UI

**Screenshots**
![image](https://github.com/connext/monorepo/assets/34812325/feec9955-2a1f-425a-9787-97cd120181aa)

@oncall

**Comment by tann9949** [comment]
I also being able to reproduce this error by trying to bridge NEXT from Ethereum mainnet to Arbitrum
![image](https://github.com/connext/monorepo/assets/34812325/2e40b9ea-c446-4f99-aae9-868206b4af6e)

However, on my console, I faced a different error message as shown below:
![image](https://github.com/connext/monorepo/assets/34812325/584ed6fe-2977-4ae4-8a74-44f8cdac2f7d)

**Comment by ekbainova** [comment]
All tickets on it: https://app.intercom.com/a/inbox/qge2vd8z/inbox/tickets/1183/linked-conversations?show_bulk_edit_modal=false&view=List
