### ISSUE TITLE
[ST] TXs from and to Linea are stuck (ETH)

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6258]
**Describe the bug**
It seems transfers coming both from and to linea are stuck (as I can see only ETH transfers are affected). No errors, enough liquidity according to scan.

**Where did the user initiate this transfer?**
Connext UI & Jumper

**Link to ticket in discord**
1) https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/1243?view=List
2) https://app.intercom.com/a/inbox/qge2vd8z/inbox/admin/7089273/conversation/1242?view=List

**Additional context**
1) https://connextscan.io/tx/0x5d07281b13a55cc169c8810d4065bd53318b70bc4c087f258c14de11762b190c
2) https://connextscan.io/tx/0xbec133aae8719bb5a166dd7b27a08debcadf91a8e51e4c7a9a3474aa74f17013

@oncall

**Comment by ekbainova** [comment]
#6239
