### ISSUE TITLE
[ICE: 16] Router can't withdraw ezETH in UI

### ISSUE THREAD

**Issue by ekbainova** [connext/monorepo#6259]
**Describe the bug**
The bug filed by bwarelabs and Dialectic

Not only ezETH, also stablecoin. 

...We are having some issues when trying to unwrap xezeth back to ezEth in the UI.
We don't receive any Metamask pop-up to allow tokens to be spend, only that error.

**Screenshots**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjVBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3097b3f5466e45a3707a6e4f38dde5bd41f7af7/telegram-cloud-photo-size-4-5983471360313246247-y.jpg" alt="telegram-cloud-photo-size-4-5983471360313246247-y.jpg" />

SLA: 1 wd

**Comment by jwtong** [comment]
```
      const contract_data =
        contractData || getContractData(chain_id, contracts!);
      const { xERC20, decimals, lockbox } = contract_data || {};
      const _amount = parseUnits(data?.amount, decimals);

      console.log("[unwrap]", { contract_address: xERC20, amount: _amount });
      const contract = new Contract(lockbox, ABI, signer);
      const response = await contract.withdraw(_amount);
```

Something in this logic doesn't account for allowance?

**Comment by ekbainova** [comment]
@jwtong any updates?

**Comment by jwtong** [comment]
Maybe need @just-a-node  to weigh in whether we're missing an allowance call

**Comment by just-a-node** [comment]
Yeah, it should check allowance first and call it if needed before wrap/unwrap.

**Comment by jwtong** [comment]
https://github.com/connext/frontend/pull/93/files

**Comment by jwtong** [comment]
https://frontend-connext-bridge-git-jt-approve-52d024-connext-979dc950.vercel.app/?vercelToolbarCode=Js4Fx9Jb1p386Wr

**Comment by ekbainova** [comment]
This is what i see. <img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--035710b115896e8d67becb1957a22b389707c4a5/Screenshot%202024-06-13%20at%2015.07.21.png" alt="Screenshot 2024-06-13 at 15.07.21.png" />
