### ISSUE TITLE
[ST] MODE-ETH ezETH transfer stuck for 12+ hours.

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#6284]
**Describe the bug**
See a title. There's enough liquidity, but it seems none of the routers are bidding. 

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/unassigned/conversation/1409?view=List

**Additional context**
https://connextscan.io/tx/0xdf91b165b6f9aa8b97a87d5232a6e95296f2b5cba6ae614780f82e32f92ab6f8

@oncall

**Comment by wanglonghong** [comment]
It's completed right now.
