### ISSUE TITLE
[ST] 1000 ezETH to Ethereum taking 2 days

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6287]
**Describe the bug**
A transaction of 1000 ezETH from Arbitrum to Ethereum has been processing for more than 1d22h https://connextscan.io/tx/0xf8f092a341752a68f2fb4db593b9ffc06406776f1a65e0c943d4aaed34337b8b

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in discord**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1432?view=List

**Comment by Sweetmind300** [comment]
Over 4days now?

**Comment by oswy-cpu** [comment]
Another big guy here: https://connextscan.io/tx/0x3f8c0a04ef0b36ae75fc0858f0dcc6a94a72058ec736b32abbff5695ba435554

800 ezETH

**Comment by Sweetmind300** [comment]
Similar issues?

**Comment by Tommy-R8** [comment]
Solved manually by Renzo
