### ISSUE TITLE
[ST] ETH to Mode execution problems

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#6311]
**Describe the bug**
A 1.01 ETH transaction from Ethereum to Mode is reconciled but not executed https://connextscan.io/tx/0xeb3bfae3165373d309286c8950dfc87350c93ec2e92a07d4075dab4332ffab11
The user was prompted to bump slippage a couple of times (now sitting at 5%), but the pool's balance is atrocious (see screenshot). What can we do to get the transfer completed while avoiding high slippage for the user?

**Where did the user initiate this transfer?**
Connext UI

**Link to ticket in intercom**
https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1552?view=List

**Screenshots**
![image](https://github.com/user-attachments/assets/34b712a6-6fb2-4851-932a-81da7db4d9ac)

**Comment by just-a-node** [comment]
It's executed now
