### ISSUE TITLE
[ST] Connext router is down (since 18th july)

### ISSUE THREAD

**Issue by MinistroDolar** [connext/monorepo#6322]
**Describe the bug**

router.connext.eth is down since 18th July!

https://connextscan.io/router/0xf26c772c0ff3a6036bddabdaba22cf65eca9f97c

Last tx:

https://connextscan.io/tx/0xa4cac31ac5342dbb1159886f8e770d0b3efba35d2a1b352b7ec9a5984304050f

timestamp: 07 18, 2024 19:19:10 PM

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/30553153-025d-4fc0-baa3-57ae75ebfb12">

**Link to ticket**

https://app.intercom.com/a/inbox/qge2vd8z/inbox/shared/all/conversation/1588?view=List

**Additional context**

@oncall

**Comment by oswy-cpu** [comment]
bump here with another transfer stuck: https://connextscan.io/tx/0x967b496ce53077a4152c422366dc72cb22b1c6c953e68f53c0dbe2733a5166a3

**Comment by preethamr** [comment]
> router.connext.eth is down since 18th July!

Connext router was stopped on that day, and will not participate any new bids.

**Comment by Tommy-R8** [comment]
@preethamr Can we de-list the router or something? Because the router having liquidity creates incorrect fast path estimates for users
