### ISSUE TITLE
As connext we should measure bridge user retention over time

### ISSUE THREAD

**Issue by massimol** [connext/monorepo#661]
It would be nice to measure some on-chain retention metrics.
 
Some suggestions for possible data to use:

n° of wallets who did a transaction this month/week & the previous month/week  / n° of total unique wallets in the same period

or

n° of wallets doing a transaction for the first time / # total number of wallets doing transactions in [period]

Thanks!

**Comment by alexwhte** [comment]
Note: There's a few ways to look at a 'single user', each of which is imperfect but useful for this analysis. 

On-chain = use wallet as source of truth.  Does not account for users (or businesses) with multiple wallets. Do airdrop farmers typically use multiple walletss? 

Off-chain = Unique user definition from our given analytics source. With privacy-aware solutions vs. cookies this is also somewhat assumed

Plausible:  https://plausible.io/vs-cloudflare-web-analytics#different-definitions-of-unique-visitor
> Plausible Analytics and Cloudflare Web Analytics have different definitions of what a unique visitor is.
> Like Plausible Analytics, Cloudflare Web Analytics [doesn’t use cookies nor local storage to track visitors](https://plausible.io/blog/google-analytics-cookies) so a different method of counting is necessary.
> In Cloudflare Web Analytics, “a visit is a successful page view that has an HTTP referrer that doesn’t match the hostname of the request”.
> Basically Cloudflare counts the number of times someone landed on any page of your site from another site. They say that “you should expect this number to differ from other analytics tools”.
> This is because it may differ greatly from other analytics tools depending on the type of site and audience you’re attracting.
> If the same person visits your site ten times in one day, Cloudflare Web Analytics lists that person as ten unique visitors while tools such as Plausible Analytics will show that visitor as one unique.
> Plausible Analytics doesn’t attempt to generate a device-persistent identifier either because these are considered [personal data under GDPR](https://plausible.io/blog/google-analytics-gdpr).
> Instead, we generate a daily changing identifier using the visitor’s IP address and User Agent. To anonymize these datapoints, we run them through a hash function with a rotating salt. You can learn more about our method in [our data policy](https://plausible.io/data-policy).

Matomo: https://matomo.org/faq/general/how-is-the-visitor-config_id-processed/

> Matomo does not use a fingerprint to track visitors.
> Instead of a fingerprint, Matomo uses the most privacy-friendly industry-leading measures to [protect](https://matomo.org/docs/privacy-how-to/) users [privacy](https://matomo.org/privacy/) instead of fingerprinting: the config_id is used by Matomo to group different actions into “visits” during a short window of up to 24-hours.
> The visitor config_id is a randomly-seeded, privacy-enabled, time-limited hash of a limited set of the visitor’s settings and attributes. The config_id or config hash is a string calculated for a visitor based on their operating system, browser, browser plugins, IP address and browser language. Unlike other tools that use fingerprinting, Matomo does not do fingerprint, and the config_id is only valid for less than 24 hours and only valid for one particular website domain:
> the config_id is only valid for 24 hours maximum and is then rotated, meaning the same visitor will have a different config_id each day.
> The config_id randomly changes and is fully anonymised every 24 hours. The randomly-generated seed is discarded each day and cannot be recovered.
> the website ID is used to process the config_id which means that on your Matomo (Piwik) instance, a given user/visitor will always have a different config_id when browsing your different websites and domains.
> the IP address used to create the config_id will be the anonymised IP address when you have enabled IP anonymisation which is the default privacy setting in Matomo (when you select “Also use anonymised IP when enriching visit: No” then the full IP address will be used in the hash calculation).

**Comment by massimol** [comment]
I would simply treat on chain wallets as separate users.
Airdrop farmers should have disappeared in the last month, and if people /
businesses have different wallets for different use cases we can segment
the market that way, and then elaborate further down the line.

**Comment by alexwhte** [comment]
closing, we are able to measure this and buildling dashboards now 

https://dapplooker.com/chart/activity-of-top-wallets-with-20-xcalls-made-2040
