### ISSUE TITLE
As a user I want to call an API to get cross-chain info such as supported tokens, chains

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#893]
**Problem**
Currently parse out of JSON with helpers, but is a little cumbersome

**Ideas to solve this**
We can serve the [`crossChain.json`](https://github.com/connext/chaindata/blob/main/crossChain.json) from an API which would be better than the current way of pulling JSON in.

**Acceptance Criteria**
[ ] The same info can be accessed via an API
[ ] 

**Other**
Where do we serve this out of? Cartographer?

**Comment by alexwhte** [comment]
P3 - Nice to have

**Comment by kolebayevv** [comment]
Also suggest to add information about liquidity pools for all supported chains! It well be good for better UX
